### ISSUE TITLE
"Did you mean to 'npm install' first?"

### ISSUE THREAD

**Issue by aredridel** [npm/npm#10032]
I forget to run `npm install` on fresh clones _all the time_.

It'd be great that if there's no `node_modules` and there are `dependencies` or `devDependencies` in the package.json that if a lifecycle script fails, the CLI's error message made it super obvious that I forgot to do this.

**Comment by othiym23** [comment]
This would indeed be handy to have. Attached to the road map!

**Comment by Toltar** [comment]
Could we implement it where when it knows its missing `dependencies`, it would just do the installation for you when prompted the error? If the CLI makes an obvious statement, couldn't that be caught and then install all of the `dependencies` and`devDependencies` for you. I'm pretty open to discussing this.

**Comment by othiym23** [comment]
This is a nice-to-have, buuuttt the CLI team isn't going to have time to work on it themselves this year. If @aredidel gets inspired and turns this into a patch, we'll land it, which also extends to the rest of the community. Because the team isn't going to be able to get to it, I'm closing this feature request. Thanks for the suggestion and your time, @aredridel and @Toltar!

**Comment by KenanY** [comment]
Pending patch from @timkrins: https://github.com/npm/npm/pull/10043
