### ISSUE TITLE
npm v3 installs unexpected packages

### ISSUE THREAD

**Issue by medikoo** [npm/npm#10079]
Running `npm install some-package-name` on v3.3.8, also tries to install missing packages in other packages residing in _node\_modules_ folder  of a project (ones totally not related to `some-package-name` which was requested to be installed).

Is this expected in version v3 (it doesn't happen on v2)? if it's so, where that behavior is documented?
At least it was totally unexpected to me, it caused issues which were hard to debug for a while.

Thanks

**Comment by othiym23** [comment]
Yes, this is expected with `npm@3` – the new installer code creates an ideal tree in memory and then applies the changes necessary to make the on-disk tree look as close to the ideal tree as possible. This is implied in the release notes for v3.0.0, but I don't know that it's spelled out anywhere explicitly – npm's documentation doesn't lay down the details of how most of its algorithms work, which is something the team is working on improving.

In any case, this is a major part of how the `npm@3` installer is supposed to work, and any changes to e.g. restrict the installer to only operate on a requested package and its dependencies (which could be tricky due to the flattened install layout + needing to change dependency versions in ways incompatible with other dependencies) would be semver-major changes. That's not to say that it can't happen, if it becomes necessary, just that there are backwards compatibility concerns to keep in mind.

**Comment by medikoo** [comment]
@othiym23 all sounds great, apart of a fact, that (if I understand right) following command in npm v3:
```
npm install some-package
```

Is conceptually same to following in v2

```
npm install
npm install some-package
```

To me it doesn't look as expected, and actually raises issues in my setup. Currently we work with large project that has some WIP packages in node_modules, where information in package.json is not necessary accurate or complete.
When we try to  add some external package using npm v3, our repository gets totally messed up, as it tries to "fix" totally not related packages to our install.

It would be way better if after calculating the tree, npm will still  try to install _just_ requested packages and if some missings or inconsistencies (not related to given install) are discovered, they're just reported in a console with suggestion to run `npm install`. It's a bit how that works in npm v2. After `npm install some-package` I get bunch of warnings about discovered inconsistencies in other deps and that's great.

**Comment by othiym23** [comment]
The installer in previous major versions of npm had a number of quirks to its behavior that `npm@3` was designed to address. One of the most significant was that running `npm install` against a `node_modules` that had already been installed would only look at the first level of dependencies in the on-disk tree. `npm@3` reads the whole installed tree (and reconstructs it into a logical tree of dependencies).

This has many consequences, but I bring it up here to explain why there's no direct analog between what happens when you run `npm install <package>` in different major versions of npm. Actions can be happening at any level of the tree, and because `npm@3` creates a maximally flat layout for packages, there are many more cases in which it will need to replace or move packages to bring the tree up to date, even in what seems like a simple install of one new package.

One of the goals of npm as a product is _consistency_: if you run `npm install` for a freshly-cloned application, and then later your colleague does the same, and then both of you run `npm install --save bluebird`, you should end up with dependency trees that look the same at that point. The old installer code was _not good_ at this, and this was one of the major motivators of `npm@3`. Addressing this goal is a major step forward for npm, even if it makes some developer workflows more difficult (or even impossible).

The situation you describe sounds like a good use case for `npm link`. Packages that are linked into the current dependency tree are treated as opaque by `npm@3` (except for npm ensuring that the linked package's dependency requirements are satisfied within the current tree. It's explicitly intended to be the way to have stuff in your `node_modules` tree that's in progress. If your workflow is such that you need to commit `node_modules` into version control, you can replace the linked package by installing it as a local package. This isn't directly analogous to how you were doing things before, but it does give you most of the latitude to be working in multiple packages simultaneously without needing special behavior from the installer.

Thanks for outlining your use case in such detail, and I hope `npm@3` ends up being a net positive upgrade for you.

**Comment by medikoo** [comment]
@othiym23 I can understand the difficulty. I take that what's happening when I do `npm install x`, is that npm calculates the tree talking into account:
- settings in project's package.json
- already installed packages in node_modules (but not mentioned in project's package.json)
- packages that were requested to install.

Then after tree is calculated, it applies all the changes that are needed to reflect the calculated tree. 

From my perspective it would be way better if it would only apply changes, that are needed just for requested packages to work without issues (but of course with respect to calculated three). I assume that's conceptually possible.

Anyway if that's not the case at this point, is there anyway that I can force npm@3 to install new package for me, but old way? So without calculating project-wise tree. I just want the new package to be placed in _node\_modules_ with its dependencies in its _node\_modules_?

**Comment by othiym23** [comment]
Please take another look at my previous response – consistency is one of the primary goals of switching to the multi-stage installer, and if we just applied the smallest set of changes available at that time, it's more likely than not that multiple install trees from the same package.json would drift out of sync with each other. Your use case is a valid one, but it's one that that the current incarnation of npm's installer is not intended to support, because there are other goals we're trying to satisfy.

> is there anyway that I can force npm@3 to install new package for me, but old way? So without calculating project-wise tree. I just want the new package to be placed in node_modules with its dependencies in its node_modules?

No. The new installer is pretty much a complete rewrite, and while there is some special-case code to install packages into siloed subdirectories, that's only available when doing global installs, to simplify packaging and managing shared tools.
