### ISSUE TITLE
npm's -v flag prints the version?

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10072]
POSIX defines the `-v` flag as being used for "verbose", with `--verbose` being the long-opt alternative, however `npm` spits out the version (I generally see this as `-V` or `--version`).

This causes me quite a bit of grief as I frequently forget that there is no short flag for verbose and wind up seeing the version all the time.

**Comment by othiym23** [comment]
The [short flag for verbose output](https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties) is `-dd` (`-d` is for `info`-level output, `-ddd` is for hyper-verbose `silly` output). `npm -v` has been the shortcut to print out npm's version since its creation, and changing it now would be hugely disruptive for a large portion of the user base. As such, it's very unlikely that the team will ever change this behavior.
