### ISSUE TITLE
package.json 'private' field should only affect to npm repository

### ISSUE THREAD

**Issue by piranna** [npm/npm#10083]
When having set the `private` field of `package.json` to `true` and at the same time you have defined a custom `scripts/publish` script, when executing `npm publish` it fails saying that the project has been set to `private`, so it can't be published. I have set NodeOS as private because I don't want to publish it on npm because it doesn't make sense, because the intended usage is people download (or clone) it from GitHub and generate it themselves to the platform that they want and there's no option to `require()` it, and in this case it is published only pre-build images as GitHub releases, but it fails. The check for the `private` field should be done only when using the default `scripts/publish` command (it's said, publish it to a npm repository), and *maybe* show a warning message when using custom ones.

**Comment by othiym23** [comment]
Since the package script for `publish` is run _in addition_ to the built-in publishing code, not _instead_ of it, it seems like what you're actually asking for is a way to override npm command behavior with package scripts, which would be a big change from the current way npm works, and one that gives me the heeby-jeebies. In less technical terms, this is a semver-major change, and not one I think is worth the cost.

If I'm understanding your use case correctly, it seems like a better way to handle this is to leave `"private": true` and create a new package script called "release" that calls `npm version && `npm pack` and then uploads the tarball to GitHub.

**Comment by piranna** [comment]
> **If I'm understanding your use case correctly**, it seems like a better way to handle this is to leave "private": true and create a new package script called "release" that calls npm version &&npm pack` and then uploads the tarball to GitHub.

Sort of :-) What I'm uploading are [pre-build disk images of the OS](https://github.com/NodeOS/NodeOS/releases) instead of tarballs, but mostly [that's the idea](https://github.com/NodeOS/NodeOS/blob/master/bin/publishRelease). The quick fix I've done is to exec directly the script with `npm run publish` instead of `npm publish`. Using `npm run release` seems to be a good alternative name :-)
