### ISSUE TITLE
npm commandline option for specifying npmrc

### ISSUE THREAD

**Issue by spikegrobstein** [npm/npm#10098]
I'd like to request a feature where I can specify an npmrc for a specific run of `npm`

there already exists the `-C` option, which lets you specify a "prefix" where a `.npmrc` file may exist. This doesn't really solve problem because I would need to create `~/.npmrc-collection/{org1,org2,org3}/.npmrc` structure. I'd much rather just have `~/.npmrc-orgX` files and point to the specific one, that way I have shared `~/.npm` directory, but can have different configs.

something like `--config` and `-c` would be cool. But I'll leave that up to you guys.

Does this sound like something viable?

**Comment by othiym23** [comment]
`--userconfig=/path/to/npmrc` is what you're looking for!

**Comment by spikegrobstein** [comment]
can you please point me to where that is documented?

**Comment by othiym23** [comment]
It's in [the `config` docs](https://docs.npmjs.com/misc/config#userconfig).

**Comment by spikegrobstein** [comment]
hm. it's not indicated that that is a commandline option. I put in a ticket on `npm/docs` to fix that page to reflect commandline options.

thanks for pointing that out.

**Comment by othiym23** [comment]
Everything on that page is a command-line option. That's how npm's configuration works – every piece of configuration can be set as an environment variable (with `npm_config_` prefixed onto it), a command-line option, or an option in an `npmrc` file (which I believe is documented at the top of the config page I just linked to). It's an open question how best to frame all this information so that people know what they can do where, and is something @ashleygwilliams and the CLI team (among others) will be puzzling over in the next few weeks.
