### ISSUE TITLE
Npm installs binaries of flattened dependencies into node_modules/.bin

### ISSUE THREAD

**Issue by sheerun** [npm/npm#10095]
Hey,

I've noticed that when installing `electron-rebuild` with npm@3, then `npm` binary is added to `node_modules/.bin`.

How to reproduce:

```
export PATH=./node_modules/.bin:$PATH
npm --version # 3.3.10
npm init
npm install --save electron-rebuild
npm --version # 2.14.8
```

I'd expect that `npm` binary is only installed into `electron-rebuild/node_modules/.bin` (and that's the behavior of npm 2.x). I don't want to pollute my binaries by dependencies of my dependencies. The only binary I want when installing `electron-rebuild` is `electron-rebuild`.

Any comments? :)

**Comment by sheerun** [comment]
I'd also be happy with not symlinking binaries of dependencies of dependencies at all. `.bin` is probably meant for interactive use by developer, and not programmatically (electron-rebuild can use `node_modules/npm/bin/npm` instead).

**Comment by othiym23** [comment]
This is the intended behavior, and is necessary so that package scripts (which use those links) will continue to work with maximally flat install tree in `npm@3`. What do you mean by "polluted"? Is there a specific concern you have about this behavior? I'm going to close this issue, as this is the intended behavior, but I'm interested in your thoughts.

(FWIW, adding `./node_modules/.bin` to the head of `PATH` is a bad idea for the same reason that adding `.` is - you can end up inadvertently running untrusted versions of common binaries that could do any number of unexpected things, as you've demonstrated. This is also, if you think about it a little, a significant security risk. Those binaries are meant to be consumed via package scripts.)

**Comment by sheerun** [comment]
> This is the intended behavior, and is necessary so that package scripts (which use those links) will continue to work with maximally flat install tree in npm@3.

How are they supposed to work? How `electron-rebuild` knows it needs to look into `../.bin/npm` instead of `./node_modules/.bin/npm`? I think no scripts are using it dependencies this way. For example `electron-rebuild` is using npm binaries by resolving with `require.resolve('npm/node_modules/node-gyp/bin/node-gyp')`, and that works without symlinking unnecessary binaries to `.bin`.

**Comment by othiym23** [comment]
It shouldn't be doing that. In the case of a direct install of npm, that will work, because npm bundles literally everything to solve bootstrapping problems, but the first time somebody runs `npm dedupe` on a tree where code is hard-coding assumptions about the shape of the on-disk package tree, things are going to break horribly. Package scripts are the correct way to do this, and they work because the npm run-script code knows enough about the package tree to concatenate the proper things to the path for the script, which is run as a child process.

**Comment by sheerun** [comment]
What do you mean? `require.resolve('npm/node_modules/node-gyp/bin/node-gyp')` resolves to npm binaries wherever they are (even in parent node_modules). What is then proper way to do it?

**Comment by othiym23** [comment]
I mean that after a dedupe run, `node-gyp` may no longer be installed in `npm/node_modules` – it may have gotten hoisted higher in the dependency tree. This isn't new to `npm@3`, by the way – this is how dedupe has always worked. Making assumptions about where packages are located has always been hazardous as a result. If the string `/node_modules/` appears in a `require()` or `require.resolve()` call, something is going to break someday.

There are two things `electron-rebuild` should be doing differently: if it wants to be using `node-gyp`, it should be depending on it directly, and the safest way to call out to a dependency's binaries is to add a package script with that call and then do a child process call to `npm run <package-script>` so that npm can take care of all the necessary path gymnastics for you.

(I suspect that `electron-rebuild` was using the version of `node-gyp` bundled with npm because we had to float some patches on top of npm's bundled `node-gyp` to make it work properly with io.js; the latest versions of `node-gyp` have been fixed to no longer require patching in this case, and either way, these patches were only included in the versions of npm bundled with io.js, so this wouldn't have worked anyway.)

**Comment by sheerun** [comment]
In node's case `node-gyp` is bundled, so it's not an issue. Anyway, I meant that `npm` is located by `require.resolve` call. So for example `require.resolve('npm/bin/npm')` always works, regardless of where npm is in dependency tree. So let's take aside that electron-rebuild assumes that `node-gyp` is inside `npm/node_modules`.

1. What about `require.resolve('npm/bin/npm')`? Is it a good way to locate npm binary?
2. When you'd expect package script to know about `npm` inside one of parent `.bin`?

**Comment by othiym23** [comment]
1. Sure.
2. I'm not sure I understand the question, but the safest assumption is that a package script will use the "nearest" version of a binary to it in the package tree. If `electron-rebuild` depends on npm, but another dependency depends on a conflicting version of npm, it's safe to assume that an `electron-rebuild` package script will get the version of npm it expects.

**Comment by sheerun** [comment]
So going back to `.bin` directory:

1. When running external binary by executing `require.resolve('npm/bin/npm')` the `.bin` directory is not used in any way, so in this case we don't need to symlink `npm/bin/npm` to `.bin/npm`.
2. So I assme that the only case when `.bin` is used is internally by `npm run <package-script>`? I'd imagine that instead of using `.bin` it could use `require.resolve` as well, no?

So if:

1. Packages don't need `.bin` to run binaries of their dependencies and
2. npm doesn't need `.bin` to run scripts via with `npm run`

When you'd recommend to use `.bin` for running dependencies of dependencies? I can't see such reason, because as you said, if you want to run binary of dependency you should use `npm run`..

If all of that is true, `.bin` can be useful only when using it interactively from terminal, like this: `node_modules/.bin/electron-rebuild`. But then I'd expect only my direct dependencies' binaries in `node_modules/.bin`. Hm?

**Comment by sheerun** [comment]
@othiym23 Please reopen this issue

**Comment by othiym23** [comment]
I don't understand why you think that's n Cesar's. As I've explained, the current behavior is intentional and required for the current behavior of npm and package scripts, and I still see no reason for it to be changed.

**Comment by sheerun** [comment]
Because you didn't answer why it's intendend behavior and why it's required for npm run to work, as well you didn't answer question in my last comment.

There are [lots](https://www.google.pl/search?es_sm=91&q=node_modules+bin&oq=node_modules+bin&gs_l=serp.3..35i39j0i7i30j0i30l5.359.3413.0.3515.16.14.1.0.0.0.152.1226.0j10.10.0....0...1c.1.64.serp..7.9.971.ElDMu6zBo6Q) of people that add this directory to PATH. Including my colleagues.  So it's clearly an issue and regression from 2.x behaviour.

Isn't it rude to close issue first and then discuss it?

**Comment by othiym23** [comment]
> So I assme that the only case when `.bin` is used is internally by `npm run <package-script>`?

This is the intended and supported use for making the links in the `.bin` directories.

>  I'd imagine that instead of using `.bin` it could use `require.resolve` as well, no?

It could, but see above – the current behavior is the behavior that npm was designed to have, for npm's own use. The fact that it's in a hidden (dot-prefixed) directory is as clear as possible that this is part of npm's internal machinery, and that other uses for it are secondary.

> There are [lots](https://www.google.pl/search?es_sm=91&q=node_modules+bin&oq=node_modules+bin&gs_l=serp.3..35i39j0i7i30j0i30l5.359.3413.0.3515.16.14.1.0.0.0.152.1226.0j10.10.0....0...1c.1.64.serp..7.9.971.ElDMu6zBo6Q) of people that add this directory to PATH. Including my colleagues.  So it's clearly an issue and regression from 2.x behaviour.

Many, if not most, of those mentions are links to the [documentation page](https://docs.npmjs.com/files/folders) that recommends _not_ prefixing package scripts with `node_modules/.bin` because npm sets that up for you when running package scripts.

> So it's clearly an issue and regression from 2.x behaviour.

This is the way that npm has always behaved, e.g. when using `npm dedupe` to explicitly flatten the tree in `npm@2` and earlier, so I have difficulty in seeing how it could be called a regression.

**Comment by isaacs** [comment]
I'm not seeing a "regression", per se.  You'd have the same problem if you did `npm install npm` in your project with that setup, or ran `npm dedupe`.

It seems like you're requesting that we stop linking metadep bins into the `node_modules/.bin` folder.  That's not gonna work.  The purpose of `node_modules/.bin` is to have a predictable location for dep bins that are used in npm run scripts.  Either we link bins into that folder (so that they can be used by scripts) or we don't link bins there (in which case it's pointless to have it in your own PATH anyway, and also, we violate the contract we've established, which *would* be a regression).

A slightly different request could be that we only link the top-level deps into `node_modules/.bin` and link metadeps into their dependents' `node_modules/.bin` folder.  That is not completely unreasonable, but definitely a deviation from the current design, and it's extra work.  The info is there in the local metadata, so it it's not impossible in theory.  Extra typing and tests and so on.

Personally, I don't recommend having `node_modules/.bin` in your PATH environment variable for exactly this reason.  Install stuff globally if you wanna use the global one, or via an npm script if you want the local one.  But that's just me.  You set up your computer however you like :)

If @othiym23 and team think this is a reasonable feature request, I'd recommend stating the specific change more clearly as a new issue, rather than re-opening this one, since it's got a lot of distracting back and forth.

**Comment by sheerun** [comment]
> It seems like you're requesting that we stop linking metadep bins into the node_modules/.bin folder

Not at all. In the first comment I said "The only binary I want when installing electron-rebuild is electron-rebuild.". i.e. I think only top-level binaries should be linked. Not binaries of dependencies of them.

I still think I'm right, but I won't be pushing this issue further as well. I think I already explained it best I could :) Just let me know if you change your mind so I can open another issue with more clear request.

**Comment by isaacs** [comment]
> > It seems like you're requesting that we stop linking metadep bins into the node_modules/.bin folder
> Not at all. In the first comment I said "The only binary I want when installing electron-rebuild is electron-rebuild.". i.e. I think only top-level binaries should be linked. Not binaries of dependencies of them.

I am feeling confused.  You started your statement with the words "not at all", and then as far as I can tell, appeared to restate exactly what you were ostensibly disagreeing with.

"Metadep" in this context means "dependencies of dependencies".  `electron-rebuild` is the dependency.  Its dependencies are the "metadeps".  You don't want those bins in `./node_modules/.bin`.  However, you may well NEED those bins in `./node_modules/electron-rebuild/node_modules/.bin` (even though that's not what you're requesting explicitly) so that the scripts in the `electron-rebuild` package can access them.

Please correct me on the specific point I'm getting wrong if you think I'm still missing your request.

It's not all that useful to establish whether you're right or wrong.  The fact is, it's working as intended right now (speaking as one of those intenders who was involved with the design in question), but you'd like it to be something else.  That is a reasonable request, but it is also additional work to implement.

**Comment by sheerun** [comment]
It's because front the beginning I meant your the "slightly different request" you've mentioned:

> A slightly different request could be that we only link the top-level deps into node_modules/.bin and link metadeps into their dependents' node_modules/.bin folder. 

For project with electron-rebuild the tree for npm 2.x is something like:

```
.
├── .bin
│   └── electron-rebuild -> ../electron-rebuild/lib/cli.js
└── electron-rebuild
    └── node_modules
        └── .bin
            ├── ncp -> ../ncp/bin/ncp
            ├── npm -> ../npm/bin/npm-cli.js
            └── rimraf -> ../rimraf/bin.js
        ├── ncp
        ├── npm
        ├── rimraf
```

The current tree for npm 3.x is something like this: (btw. there's no node_modules/.bin in electron-rebuild!)

```
.
└── .bin
    ├── electron-rebuild -> ../electron-rebuild/lib/cli.js
    ├── ncp -> ../ncp/bin/ncp
    ├── npm -> ../npm/bin/npm-cli.js
    ├── rimraf -> ../rimraf/bin.js
    └── window-size -> ../window-size/cli.js
├── electron-rebuild
├── ncp
├── npm
├── rimraf
└── .......
```

I'd like it to be something like this:

```
.
├── .bin
│   └── electron-rebuild -> ../electron-rebuild/lib/cli.js
└── electron-rebuild
    └── node_modules
        └── .bin
            ├── ncp -> ../../../ncp/bin/ncp
            ├── npm -> ../../../npm/bin/npm-cli.js
            └── rimraf -> ../../../rimraf/bin.js
├── ncp
├── npm
├── rimraf
└── .......
```

Am I clear enough now? :)

**Comment by sheerun** [comment]
And honestly I don't really care if electron-rebuild gets its `node_modules/.bin` (it seems it doesn't for npm 3.x). What I really care about is only `electron-rebuild` in my project's`node_modules/.bin`.

If you really need `node_modules/.bin` in every dependency, then I'm ok with that / indifferent.

---

Another side note. If in npm 3.0 you do `npm install electron-rebuild && cd node_modules/electron-rebuild && npm bin`, you get `project/node_modules/electron-rebuild/node_modules/.bin` that is **not** existent.. The real binaries are in `project/node_modules/.bin`. It's all every confusing at least.
