### ISSUE TITLE
Feature: Add a setting to support searching a package in a local folder when dev

### ISSUE THREAD

**Issue by Alphapage** [npm/npm#10103]
Hello,

It would be really great to let npm search a local package in a predefined folder during development.
I mean when executing : "npm install acustompackage" , npm will search acustompackage in /mydevpackages/\* local folder where the name of the folder is acustompackage which contains the package.json. If the package is missing locally, then try to get it from npm webservice.
If the setting isn't set, then try to get it from npm webservice directly.

This is easier, faster than npm link and I think not so hard to implement.

Thanks in advance for your suggestions.

**Comment by KenanY** [comment]
@Alphapage So, like, a cache?

**Comment by Alphapage** [comment]
Well not exactly.
A cache system will download the package first.
My request is to search the specific folder defined in settings first,then download if not found.

**Comment by Alphapage** [comment]
I will give an example:
I tell npm.settings.json (don't know where to save it or in ENV_PATH maybe) to search in "/test/mydevFolder".
Suppose I want to code for the rimraf module.
I put the rimraf package folder in "/test/mydevFolder".
When requesting "npm install rimraf", npm will install rimraf from "/test/mydevFolder/rimraf" using the updated code locally.
If I remove rimraf from "/test/mydevFolder/" then npm will install rimraf from webservice.

Hope this is more understandable.

**Comment by KenanY** [comment]
@Alphapage

> search in the specific folder defined in settings first,then download if not found

Really sounds like a cache to me (which `npm` already has).

> download in the dev folder, but download to install.

What is the "dev folder"? What do you mean by "download to install"? How are the two different?

I'm not sure I see the use-case for this. I see two possibilities as to how this could be used:

1. Quickly install frequently-used modules since they are already in the filesystem (this is a cache).
2. Easily install custom, [local packages](https://docs.npmjs.com/files/package.json#local-paths). It is my experience that local packages are usually local because they are private and not intended to be upload to the npm registry. Thus, this feature would only be used for saving a few characters: `npm install acustompackage` vs. `npm install ~/mydevpackages/acustompackage/`

Sorry if I am misunderstanding anything.

**Comment by KenanY** [comment]
@Alphapage So you would download the `rimraf` module and put it in a folder so that `npm` does not have to re-install it? `npm` already does this for you with its own cache directory.

**Comment by Alphapage** [comment]
With a caching system, you can loose the changes you made in the code.
With my example, you can develop without problem because npm will never overwrite the folder.

**Comment by Alphapage** [comment]
This is more a kind of proxy which tells npm to search somewhere locally before using the webservice as it does in the normal way.
