### ISSUE TITLE
No way to override registry in .npmrc for scoped packages w/--registry flag

### ISSUE THREAD

**Issue by brianreavis** [npm/npm#10117]
I have a scoped package that I want to publish publicly to the main NPM registry. The problem is: I have that scope set up in `.npmrc`, set to a private registry (to act as a default). With npm there seems to be no way to override this when publishing. I've tried setting `--registry` and `publishConfig.registry` to "https://registry.npmjs.org/" and neither override it (npm v3.3.9)

Semi related: https://github.com/npm/npm/issues/5522

**Comment by mhofman** [comment]
I just found out that using `publishConfig["@scope:registry"]` properly overrides the .npmrc scoped registry value

**Comment by KidkArolis** [comment]
Just ran into this issue - we find it very surprising that command line argument `--registry` does not override the scope registry specified in `~/.npmrc`.

@othiym23 would you accept a PR where `--registry` cli arg overrides the registry specified in '~/.npmrc'? I don't know how the `publishConfig` setting should behave..

_The boring details_: We use an internal npm registry and by default everyone has it configured for our scope in `~/.npmrc`. However we also use dev and staging registries (since this registry is part of our application functionality) and we want to be able to override this for our QA process. It seems that this used to work in an old `npm@2.14.9`.

**Comment by mhofman** [comment]
@KidkArolis , it does work, you have to use `--"@scope:registry=registryURL"`, not `--registry=registryURL`.

What doesn't work is overriding `publishConfig["@scope:registryURL"]` using `--"@scope:registry=registryURL"`

**Comment by KidkArolis** [comment]
Oh, awesome! Thanks for the clarification!

**Comment by brianreavis** [comment]
Thanks for clearing this up @mhofman! I suppose this is safe to close now. Out of curiosity, is there somewhere you found this documented?

**Comment by mhofman** [comment]
I honestly don't remember. I might have guessed it from how npm structures the `npmrc` file knowing that all lines in there are actually parsed the same as command line parameters.

It might be good for the docs to make this a little more clear.
