### ISSUE TITLE
npm allows to publish version 1.0.0 and then it can be downgraded and can be published 0.0.1, is it intentional or problem

### ISSUE THREAD

**Issue by vinayakjadhav** [npm/npm#10129]
npm allows to publish version 1.0.0 and then it can be downgraded and can be published 0.0.1, is it intentional or problem.
If user is not allowed to publish same version again, same should apply for downgrading the version.
In certain condition it should be allowed to override current version.

**Comment by othiym23** [comment]
This is absolutely intentional. We've talked about maybe emitting a warning when a package is published to the `latest` dist-tag with a version that's lower than the current `latest`, but there are many use cases where publishers want to be supporting multiple release lines of a single package at once (npm does this itself – see `npm@latest-2`, which is `npm@2.14.18`, and `npm@latest-3`, which is `npm@3.3.10`).
