### ISSUE TITLE
npm can't install a package with the same name as a file

### ISSUE THREAD

**Issue by calvinmetcalf** [npm/npm#10155]
clone [parse-asn1](https://github.com/crypto-browserify/parse-asn1) and try to manually install asn1.js and it will instead throw an error

``` bash
npm ERR! not a package /Users/me/path/parseASN1/asn1.js
npm ERR! addLocal Could not install /Users/me/path/parseASN1/asn1.js
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/share/npm/bin/npm" "install" "--save" "asn1.js"
npm ERR! node v4.2.1
npm ERR! npm  v2.9.0
npm ERR! path /var/folders/zr/y9zyc9fj4n357gsd41qw7rg8xh062c/T/npm-50891-a8fe7436/unpack-be67c41ae18f/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/zr/y9zyc9fj4n357gsd41qw7rg8xh062c/T/npm-50891-a8fe7436/unpack-be67c41ae18f/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

was able to fix locally by deleting the file locally (as it was still in git)

**Comment by KenanY** [comment]
ref. https://github.com/npm/npm/issues/12455#issuecomment-214439949, which goes over how fixing something like this is not really worth it for the core team to spend time on (that issue is in regards to `package.json`, but it can be applied to any file in your current directory which matches the name of a dependency you want to install). Perhaps the most appropriate fix would be to do this next time:

``` bash
$ npm install asn1.js@latest
```

**Comment by KenanY** [comment]
Closing as per above.
