### ISSUE TITLE
Downloads project from git instead of using linked version

### ISSUE THREAD

**Issue by andy-hanson** [npm/npm#10203]
I have a package.json looking like:

```
{
    "dependencies": {
        "mason-compile": "mason-lang/mason-compile"
    }
}
```

I have already run `npm link ../mason-compile` and intend to use my local version of that project.

However, when I run `npm install`, npm downloads the online `mason-compile`'s dependencies and installs those to `node_modules`. (The linked version was a dummy package with no dependencies, so nothing else should have been installed.)

**Comment by smikes** [comment]
Thanks for bringing this up.

I believe that this is expected behavior.  Running `npm install` will cause npm to try to install all dependencies as specified, and in this case you have specified the `mason-compile` module using the git shorthand.

I don't know, architecturally, how hard it would be to change this behaviour.
