### ISSUE TITLE
swap request lib for bhttp

### ISSUE THREAD

**Issue by stevenvachon** [npm/npm#10240]
[npmjs.com/bhttp](https://npmjs.com/bhttp)

**Comment by othiym23** [comment]
`request` is heavyweight and includes lots of things that npm will never use. It _also_ has a liberal but open license compatible with npm's, and extensive support for several of the proxy types used by many, many npm users. Without the latter, especially, it's impossible to swap out `request`, and the amount of new test code we'd need in `npm-registry-client` to make sure that the agent, proxy, SSL, and connection code contained no regressions due to the swap would be huge. Thanks for the suggestion, but npm is stuck with `request` for now.
