### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by Slepperpon** [npm/npm#10263]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:226:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.7-v7+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v0.12.6
9 error npm  v2.11.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
Hello @Slepperpon! From the error message, it looks like you are running `npm run start` in a directory whose `package.json` does _not_ define a `"start"` script. `npm` has no idea what you want it to do, so it throws that "missing script" error.

What are you _expecting_ to happen when you run `npm run start`? Perhaps I can help you get your desired result.

**Comment by Slepperpon** [comment]
It is the command to start homebridge  a program on rpi 2  i had it working then i did os update now not working

Date: Wed, 4 Nov 2015 10:56:56 -0800

**Comment by KenanY** [comment]
@Slepperpon I guess [this](https://github.com/nfarina/homebridge) is `homebridge`? If so then I don't see any mention of `npm start` anywhere in that repository after a cursory search. From the "Installation" section it looks like you should just run `homebridge` or `node bin/homebridge`. If you continue to have issues you should probably direct them to the author(s) of homebridge rather than here unless you experience a problem with `npm` specifically.

**Comment by Slepperpon** [comment]
thank you

Date: Wed, 4 Nov 2015 12:21:21 -0800
