### ISSUE TITLE
Important issues reference a currently-missing "multi-stage" branch

### ISSUE THREAD

**Issue by sompylasar** [npm/npm#10292]
Many actual issues were closed with a message "Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)", but the link is broken -- [the branch is missing from the branches list](https://github.com/npm/npm/branches/all?utf8=%E2%9C%93&query=multi-stage).

The similarly-named milestone is also missing: https://github.com/npm/npm/milestones/multi-stage%20install , so the links to it are broken, and the history is lost.

What happened to this branch and how do I find the referenced fixes in the code and in the history of npm, e.g. in which version was this fixed, was the fix released etc.?

**Comment by sompylasar** [comment]
Example: https://github.com/npm/npm/issues/5827
@iarna, could you please shed some light? Looks like you are responsible for this.

**Comment by iarna** [comment]
The multi-stage branch is https://github.com/npm/npm/tree/master now, anything in multi-stage has been available since v3.0.0. Generally, these were issues that were fixed by rewriting the installer as a whole, which involved completely changing its architecture. As such, you can't find a specific commit that fixed a given issue.

**Comment by sompylasar** [comment]
@iarna, thank you for the clarification and quick reply!
