### ISSUE TITLE
Suggestion: store sha256sums in npm shrinkwrap

### ISSUE THREAD

**Issue by nakedible-p** [npm/npm#10300]
When a user runs npm-shrinkwrap, the idea is to ensure that no package versions may change. However, this still trusts "registry.npmjs.org" to always produce the same package to be true. In case of an exploit, this might assumption might not hold.

By including SHA256 checksums for each package in `npm-shrinkwrap.json` and having npm verify those checksums on `npm install`, the user could feel safe that nobody has substituted any code after running `npm shrinkwrap`.

This is not a full security solution for npm and is not meant to be, but it is meant to help the case where the project being compiled/installed is trusted (coming from a private git repo, or similar) but no outside sources are trusted - and I can't think where it would be harmful.

I am willing to do most of the legwork in implementing this, but for that I need to know that a) this feature is something that would be accepted in npm, b) somebody else besides me wants this to happen.

**Comment by anko** [comment]
I'd want this. Version numbers say nothing about the actual contents—a SHA256 says everything.

**Comment by gasteve** [comment]
Shrinkwrap is practically useless without this...so yes, I would want it.  On the point of security, it would be nice of npm also had some ability to keep a database of code signing keys and verify signatures on the hashes of the downloads or the git commits.  For each module, a set of acceptable / required code signing keys could be specified and used to check signatures.

**Comment by braydonf** [comment]
I think this is a good idea, fills a missing gap to verify that the file downloaded is exactly what is expected.

**Comment by busches** [comment]
@othiym23 @KenanY is this a feature npm would consider adding with a PR?

**Comment by othiym23** [comment]
It's long been a goal of the CLI team to add content hashes to `npm-shrinkwrap.json`. Getting the shasums into the file is relatively simple, because that metadata's available at shrinkwrap time. What's harder is resolving the shasums back to packages at install time. There are brute-force ways to do this that might be relatively simple to code, but I have concerns about how that would affect install performance when used. So, I certainly don't discourage experimentation here, and am happy to review and provide feedback on patches, but be aware that there are dragons here. Thanks for asking!
