### ISSUE TITLE
save-prefix, shrinkwrap, generate automatically

### ISSUE THREAD

**Issue by cztomsik** [npm/npm#10321]
(This is not a bug, rather humble question/feature request)

What's the reason for `save-prefix` set to `^`?
Because here's what I've been experiencing in multiple companies:

1. someone gets the project started and does `npm install pkg1 pkg2 pkg3 --save`
2. he make it to the point when it is working somehow and push it to SCM and describe somewhere how to setup dev env
3. other people join the project (at this point it's usually okay)
4. as the project goes on, more people are involved and they fetch and `npm install`
5. the later they join the bigger chance is they will install newer versions
6. some libraries introduce bugs in these versions and it's really hard to find (to anybody who has not yet experienced this) not to mention they can be platform specific.
7. **it happens quite often**

Setting save-prefix is useless because those semvers are in libraries as well which kinda makes it all much much worse. The only way from this is generating shrinkwrap each time - which can't be easily automated so there's a chance somebody might miss it.

Are you going to address this somehow in upcoming versions? Like honoring carrets only for manual updating or **introducing some option** which might be set in `.npmrc` and which would cause shrinkwrap to get generated automatically?

**Comment by cztomsik** [comment]
Also, `save-exact` does not solve anything as it works only for top-level dependencies...

**Comment by halhenke** [comment]
I imagine the reason for save-prefix being set to `^` by default is that it *shouldn't* break your code if people are using semver properly and not shipping broken code. In practice of course things work differently.

I also perhaps wouldn't mind an option to run shrinkwrap automatically following an install but in the meantime theres a pretty simple workaround in terms of using npm scripts - something like this

```
  "scripts": {
    "goodInstall": "npm install",
    "postgoodInstall": "npm shrinkwrap --dev",
  }  
```

would automatically shrinkwrap if you install things like so:
`npm run goodInstall -- -D react-animate`

Not perfect and there can still be compliance issues with people forgetting to use that command but you could probably make it a bit nicer with a shell alias/function etc

**Comment by othiym23** [comment]
> Are you going to address this somehow in upcoming versions? Like honoring carrets only for manual updating or introducing some option which might be set in .npmrc and which would cause shrinkwrap to get generated automatically?

Probably not. npm is built around semver, and while as a community we can encourage people to follow good practices around versioning their packages, npm can't enforce semver correctness. Shrinkwrapping by default feels like an attempt to patch around bad use of semver, and that doesn't feel like a healthy way for npm to engage with its ecosystem. Also, shrinkwrapping is first and foremost a deployment tool – it's meant to be used to prepare your package when you're ready to put it into production. We want to make sure that it's better-integrated into the rest of the CLI so that it's more useful as a deployment tool, but we don't plan to move in the direction of making it a clone of `Gemfile.lock`. That's too heavyweight for most packages, and we want to encourage people to actually use semver as intended.

However, if you _do_ want to use shrinkwrap in this way, `npm@3` includes some significant improvements that should make it a lot easier. Both `npm install --save[-dev|-optional]` and `npm update --save` will update an existing `npm-shrinkwrap.json` if one exists with `npm@3`, so once the package is shrinkwrapped, keeping the shrinkwrap up to date is much simpler.

Thanks for your time, and I hope my reasoning makes sense!

**Comment by halhenke** [comment]
Wow had no idea that shrinkwrap was automatically updated when an install modifies the `package.json`. Have witnessed a lot of grumbling around this exact issue in a Slack channel that I hang out in lately - seems like this sort of thing is not well known. Will try to spread the word.

**Comment by othiym23** [comment]
Remember that's a feature that's new to `npm@3`! There's definitely more work to be done on `npm shrinkwrap`, but it's substantially improved in `npm@3`.

**Comment by cztomsik** [comment]
@othiym23 that's great improvement, thx for that!
