### ISSUE TITLE
A way to add alias easily by user

### ISSUE THREAD

**Issue by watilde** [npm/npm#10332]
There are nice [34 pieces of aliases](https://github.com/npm/npm/blob/master/lib/npm.js#L61-L95) in the npm and all of pieces are very user friendly. However, the decision to add a new alias seems very difficult because sometime it require a subjective judgement. I think it's nice if npm user add easily like the following way:

Add a new alias from cli:
```
$ npm config set alias-pit "prune && install-test"
```

Then, a new line has come to the `.npmrc`
```
alias-pit=prune && install-test
```

Any thought on this feature-request please :)
Thanks!

**Comment by othiym23** [comment]
This is an intentional choice by the current npm product manager (by which I mean me). My goal is to have npm be a tool with a _closed extension model_ for its user experience – that is, it has a reasonably small set of commands built into it, and people who want to extend its behavior use mechanisms provided by the tool (i.e. package scripts, configuring, and higher-level tooling). The goal is that the tool can eventually be mastered by a relatively frequent users (which is already a tough goal for npm to satisfy, given the flexibility and complexity of npm's configuration).

If anything, I'd like there to be _fewer_ top-level commands and built-in aliases than there are now. I find that the _open extension model_ used by Git (among others) imposes a high cognitive cost, because then users have to remember which extensions they've installed, start relying on behavior that's specific to their installation, and the like. I understand why this is an appealing feature to many users, but this is functionality that I'd prefer to leave to shell aliases, scripts, `.bat` / `.cmd` scripts, and similar external mechanisms.

Thanks for making the suggestion, @watilde-san. I always appreciate your ideas!

**Comment by othiym23** [comment]
(`install-test` is a special exception just because that is _such_ a common use case for heavy package developers that `npm it` represents a significant time savings on its own. npm is opinionated about some things!)

**Comment by watilde** [comment]
I appreciate your clear explanation everytime! I understood what's the closed extension model which is one of your goal and I'm interesting in the design.
Thanks again!
