### ISSUE TITLE
npm on ARM (Cortex-A9) fails when transfers are > 64K

### ISSUE THREAD

**Issue by waTeim** [npm/npm#10352]
At this point I'm not sure where the error lies.  It feels like a combination of node and npm.  It may be related to various issues recorded here where at least the outward error is **ECONNRESET**, indeed, this was the primary problem I encountered, but there are others.  I believe the transfer (or various transfers) are failing when more than 1 64K buffer is required (assuming the buffer is 64K).  This instance of node and npm is a result of cross-compilation for an ARM Cortex A9 based platform.  As far as I know this is the first time anyone has attempted this on this particular system. It could indeed be a basic failure of node or the compile or even the OS or the intermediate base station that connects things.  The later is less likely as it's built to transport H.264 streams and in any case a workaround is to npm install on another machine and then transfer the resulting node_modules directory via tar and scp after which things work, however that scp is working with a low bandwidth-delay product and there are as yet no extensive tests.  It still could be many things.

I did, though, want to communicate this early in hope of some guidance, next steps to narrow down this problem.

Some examples:

    # npm -g --verbose install express
    npm info it worked if it ends with ok
    npm verb cli [ '/usr/bin/node',
    npm verb cli   '/usr/bin/npm',
    npm verb cli   '-g',
    npm verb cli   '--verbose',
    npm verb cli   'install',
    npm verb cli   'express' ]
    npm info using npm@2.14.7
    npm info using node@v4.2.2
    npm verb install initial load of /usr/lib/package.json
    npm verb readDependencies loading dependencies from /usr/lib/package.json
    npm verb cache add spec express
    npm verb addNamed "*" is a valid semver range for express
    npm verb addNameRange registry:https://registry.npmjs.org/express not in flight; fetching
    npm verb request uri https://registry.npmjs.org/express
    npm verb request no auth needed
    npm info attempt registry request try #1 at 22:17:47
    npm verb request id 4f74f7c5e45296ce
    npm http request GET https://registry.npmjs.org/express
    npm http 200 https://registry.npmjs.org/express
    npm verb bad json {"_id":"express","_rev" 

.... followed by approximately 65000 more characters

    npm ERR! registry error parsing json
    npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
    npm verb headers   etag: '"4OB4CL5GNOR7UYF8XM68CXBYM"',

If you add up the size of the header + this json, then the number of characters is really close to 65536.

Also, some more evidence

    # npm -g install coffee-script
    npm ERR! Linux 3.10.17-rt12-1.0.0_ga+g0378a87
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "-g" "install" "coffee-script"
    npm ERR! node v4.2.2
    npm ERR! npm  v2.14.7

    npm ERR! shasum check failed for /tmp/npm-7936-92173586/registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz
    npm ERR! Expected: 12938bcf9be1948fa006f92e0c4c9e81705108c0
    npm ERR! Actual:   a0eee690bab8512438fccf5c2ec1217ba2842784
    npm ERR! From:     https://registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    # ls -l /tmp/npm-7936-92173586/registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz
    -rw-r--r--    1 root     root         65004 Nov 11 22:08 /tmp/npm-7936-92173586/registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz

downloading via browser reveals the true size of this file:

    75406 Nov 11 17:51 coffee-script-1.10.0.tgz

**Comment by othiym23** [comment]
For network fetches, npm uses `npm-registry-client`, which in turn uses `request` for all its HTTP traffic. `request` just uses the HTTP API from Node core, so this problem is most likely coming from Node.js, not npm, which is just being handed the download stream by request. The size + `ECONNRESET` leads me to believe that something pretty low-level in Node – probably `libuv`, as V8 doesn't do any of the network access itself – is encountering something (an alignment issue? something specific to Buffers?) that's causing it to bail on the download.

The [Node.js build working group](https://github.com/nodejs/build) is probably the best place to start on the Node side, because @rvagg (among others, I think) has set up the ARM build farm, and may have encountered some of these issues with older iterations of ARM. I couldn't tell you off the top of my head if they've already gotten an A9 machine up and running yet, but they might have some helpful tips as far as what build settings are likely to help you stay out of trouble.

Since this isn't an npm issue (unless I've badly misunderstood the problems you're having), I'm going to close this issue. Good luck getting this sorted out, though! And thanks for including so much detail in the report!
