### ISSUE TITLE
install/postinstall scripts run before devDependency install

### ISSUE THREAD

**Issue by chrismikehogan** [npm/npm#10366]
Given I have a package.json with `dependencies`, `devDependencies`, and a `postinstall` script, when I run `npm install`, then the postinstall script runs _after_ dependencies install, but _before_ devDependencies install.

```
$ npm -v
2.14.7
$ node -v
v4.2.2
```

```
{
  "name": "example",
  // ...
  "scripts": {
      "postinstall": "echo 'POSTINSTALL POSTINSTALL POSTINSTALL POSTINSTALL POSTINSTALL '"
  },
  "dependencies: {
    "node-uuid": "1.4.1"
  },
  "devDependencies: {
    "protractor": "^2.5.1"
  }
  // ...
}
```

**Comment by apoterenko** [comment]
We have the same trouble at our project (npm 2.14.20).

**Comment by rempatterson** [comment]
unsubscribe

**Comment by lili21** [comment]
same issue here. I need move those devDependencies to dependencies to fix this problem.

**Comment by jordwalke** [comment]
Exact same problem but for `peerDependencies`. (on old node 0.12.3).

This is really important. I believe the order that these scripts should be executed in should be topological ordering regardless of if dependencies are peer dependencies, or dev dependencies.

**Comment by slurmulon** [comment]
This is really hurting several of my Babel 6-based node packages. Because of this issue, I have to do a hack in order to ensure Babel is installed (and no, `postinstall` isn't sufficient for some reason, it never seems to work for me. the code pushed to NPM never includes the compiled code):

```
"scripts": {
    "build": "node ./node_modules/.bin/babel src --out-dir lib",
    "preinstall": "npm install --ignore-scripts && npm run build"
}
```

I also found that I have to call the Babel binary with a relative path, you can't just do `babel src --out-dir lib`. This also doesn't work consistently between NPM 2 and 3 (3 only). I haven't tested it yet, but I imagine this would impact any package that defines a `bin` in its `package.json`.

This solution is also lacking because it dramatically slows down the build process, forcing NPM to needlessly re-process the entire dependency tree just so that one or two modules are guaranteed to be available in your `scripts`.

Another "solution" is to simply switch any problematic `devDependencies` to `dependencies`, but this has many implications, especially with popular packaging tools like `webpack` and `browserify`.

---

```
$ node -v
v5.0.0

$ npm -v
3.3.6
```

**Comment by rotemdan** [comment]
What I need might be slightly different, but could address this as well (or is already possible?):

I'm looking for a way to set up a script to _only_ run when `npm install` is executed over a local existing `package.json` file (i.e. not when `npm install myLibrary` is run), as well as _after_ `devDependencies` are installed. The idea is that the one command would cause the project dependencies and dev dependencies  to be installed, immediately followed by the initiation of a build/compilation of the project.

Is there any way to achieve that? something like `postdevinstall`?

**Comment by HansHammel** [comment]
+1 Not working for normal dependencies either. Win10 Pro, npm v4.1.1, node v6.9.1. Cause: Modules folder doen't exist when posinstall scipt is executed. Very annoying!
