### ISSUE TITLE
3.4.1 install <package>  gives latest for all but npm 

### ISSUE THREAD

**Issue by dkebler** [npm/npm#10384]
I've been having to explicitly upgrade npm with suffix @3.x.x or npm will as expected install the latest stable instead of the pre-release.  So I installed 3.4.1 and happily noticed in the release notes that installing a package with no suffix would now give me the latest version pre-release or not.  

So I thought great, maybe it applies to installing npm itself....Let's test it I thought stupidly.

      sudo npm install -g npm

and I would get the latest 3.x version.... i.e. 3.4.1

instead npm just got trashed and I had to install from scratch.

Just thought you should know or at least mention in the release note it works for all packages except npm itself if that was the intention.

**Comment by othiym23** [comment]
This is due to npm's [release process](https://github.com/npm/npm/wiki/Release-Process#the-npm-release-train) – each new release is published as `npm@next` (or `npm@next-2` for the current LTS series) and given a week to bake in before being retagged as `npm@latest`. "`latest`" is a [dist-tag](https://docs.npmjs.com/cli/dist-tag), and isn't _always_ the most recently released version of a package (or the version of with the greatest semver version), although it often is, because `latest` is the default dist-tag, and publishers are more often than not publishing the highest version of the package. So the behavior you're getting is the intended behavior.

That said, I'm sorry to hear that your version of npm got stomped, and glad to hear that you were able to get things back to normal.

**Comment by dkebler** [comment]
For those who did the same stupidity and are running a flavor of linux here is the easiest way to fix this.

First delete the npm directory likely in /usr/local/lib/node_modules if you are running *nix.
I had to do this or the reinstall kept throwing errors.

Then get the script mentioned on the github repo readme
https://github.com/npm/npm
https://www.npmjs.com/install.sh

The curl download and run didn't work for me I had to download the script and then run it.

But that did it....loads in 3.4.0.    

_So is 3.4.0 then the current latest?  So if I understand you If I were to try this again (which I am not!) will it just reinstall 3.4.0?_

**Comment by othiym23** [comment]
Yes:

```
bauchelain% npm dist-tags ls npm
3.x-latest: 3.4.0
3.x-next: 3.4.1
latest-1: 1.4.29
latest-2: 2.14.10
latest: 3.4.0
next-2: 2.14.11
next: 3.4.1
v3.x-latest: 3.4.0
v3.x-next: 3.4.1
```

```
bauchelain% npm view npm@latest version
3.4.0
```

```
bauchelain% npm view npm@next version
3.4.1
```

**Comment by dkebler** [comment]
It's kinda a catch 22, if I load 3.4.1 and do this then it loads something earlier that doesn't support the new "latest" syntax.  I suppose anyone wanting to try this should wait until 3.4.1 finally becomes the "latest" release or they will be sorry like me.

ok thanks....close this.
