### ISSUE TITLE
sudo npm install

### ISSUE THREAD

**Issue by wangdepeng** [npm/npm#10397]
npm ERR! Error: UNKNOWN, symlink '../shelljs/bin/shjs'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/vagrant/devops-kungfu
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path ../shelljs/bin/shjs
npm ERR! code UNKNOWN
npm ERR! errno -1

**Comment by KenanY** [comment]
@wangdepeng Please try using the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag if your system does not support symlinks. If you still receive an error be sure to [update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) before posting a new log since `npm@1` is only mildly supported anymore.

**Comment by KenanY** [comment]
@wangdepeng It has been several months now with no reply from you. Are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned and not an issue with `npm`.
