### ISSUE TITLE
cordova error,help

### ISSUE THREAD

**Issue by cordoy** [npm/npm#10398]
C:\Users\Administrator>cordova
module.js:339
    throw err;
    ^

Error: Cannot find module 'cordova-lib'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\cordova\src\help.js:20:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by cordoy** [comment]
what should i do with this?

**Comment by snopeks** [comment]
HI @cordoy it doesn't look like there are any npm issues here. If you're seeing any errors trying to `npm install` cordova modules please copy them into this issue, we'll be happy to help. Otherwise, I recommend taking this to issues.cordova.io, they'll be more helpful. Offhand, it looks like `cordova-lib` is missing, you could try installing cordova again to see if that solves the problem. 

`npm install -g cordova`.

**Comment by freed00m** [comment]
#10340 as we try to point out, since npm 3.3.12 and up, the ability do download cordova-lib always fail.

doing npm install -g cordova now will do you no good, downgrade your npm to 3.3.8 and then you will be able to download packages that requires cordova-lib

**Comment by busches** [comment]
@cordoy  @freed00m the latest `npm` is installing and running `cordova` fine for myself, can you retest and see if this is still an issue you're facing? If so, please update with the version of `npm` and `node` you're using. If not, please close the issue.

**Comment by freed00m** [comment]
I no longer work on cordova projects but I just successfully installed cordova with cordova-lib as its dependency. 

So please @cordoy close the issue :)

```
$ npm -v
3.10.5
$ node -v
v6.3.1
```
