### ISSUE TITLE
npm install --depth 0

### ISSUE THREAD

**Issue by guyellis** [npm/npm#10435]
The current 3 series of npm prints the installed tree once `npm i` completes. Would it be possible to default it to printing just level 0 of the tree instead of the entire tree? i.e. by default add a `--depth 0` style flag to it.

Example:

Current:

```
├─┬ webpack-merge@0.2.0 
│ └─┬ lodash.isplainobject@3.2.0 
│   └── lodash._basefor@3.0.2 
└─┬ yql@1.0.2 
  ├─┬ request@2.34.0 
  │ ├── aws-sign2@0.5.0 
  │ ├── forever-agent@0.5.2 
  │ ├─┬ form-data@0.1.4 
  │ │ ├── async@0.9.2 
  │ │ └─┬ combined-stream@0.0.7 
  │ │   └── delayed-stream@0.0.5 
  │ ├─┬ hawk@1.0.0 
  │ │ ├── boom@0.4.2 
  │ │ ├── cryptiles@0.2.2 
  │ │ ├── hoek@0.9.1 
  │ │ └── sntp@0.2.4 
  │ ├── http-signature@0.10.1 
  │ ├── mime@1.2.11 
  │ ├── oauth-sign@0.3.0 
  │ ├── qs@0.6.6 
  │ └── tunnel-agent@0.3.0 
  └── underscore@1.6.0 
```

Default wanted:

```
├─┬ webpack-merge@0.2.0 
└─┬ yql@1.0.2 
```

**Comment by alistairjcbrown** [comment]
+1 to this - outputting the full tree after an install adds ~4300 lines to the console output. Being able to limit, or even turn this off, would be great.

**Comment by othiym23** [comment]
Hmm... that tree has valuable diagnostic information in it (like new packages added, as well as packages that have been moved around) that would be lost were it to default to something like `--depth=0` on install. Is there a reason you couldn't wrap this up in a script and pipe `> /dev/null`?

**Comment by guyellis** [comment]
@othiym23 that would work but it's not very "default" and newbie friendly. The default for `npm outdated` was changed to be `--depth 0` because (I assume) that the output, although sometimes useful, was overwhelming and not needed in 99% of cases.

I completely agree with you that there's some valuable information in there. However I think that 99% of the time it's not needed and that 1% when it is needed it can be switched on.

I think that the default should cater for the most common case and then switches used for the less common cases.

**Comment by othiym23** [comment]
> @othiym23 that would work but it's not very "default" and newbie friendly.

I think this is where we disagree. It may be that people don't get a lot of value out of the tree output right now, but I think that's mostly because they don't know how to interpret what it's telling them, and with the new details included in that output in `npm@3` (i.e. the heavier use of color and emphasis) and the new way the installer works, it's a more useful and informative tool than you may realize, especially on non-initial installs.

> The default for npm outdated was changed to be --depth 0 because (I assume) that the output, although sometimes useful, was overwhelming and not needed in 99% of cases.

The use cases for `npm outdated`, `npm ls`, and `npm install` are all pretty different. `npm outdated` only really makes sense for the top level – is there a newer version of a package I'm using directly? `npm ls` both allows you to see the whole logical tree for your application (i.e. simply running `npm ls`), as well as answer questions like "how many different versions of `readable-stream` am I using?" (`npm ls readable-stream`). The tree that gets printed out at the end of `npm install` is the most concise representation of what it actually _did_, which (again, especially with `npm@3`) can be quite dramatic (and sometimes surprising), given all the flattening and deduping that can occur.

We _could_ change the output to only include the list of packages added and removed, but I'm afraid that that would, on balance, be _less_ useful than what's there today, because the tree provides valuable context about what happened as the result of the install.

**Comment by guyellis** [comment]
@othiym23 I completely agree with you that the (current) complete tree provides useful and valuable information. I just think that 99% of the time it's not needed or wanted.

**Comment by alistairjcbrown** [comment]
@othiym23 Given that the tree output is diagnostic information, could it be controlled through the `loglevel` flag?

**Comment by othiym23** [comment]
From @isaacs's point of view, historically, the tree _is_ the output of `npm install`, and is the part of the contract of the command, which is why previous attempts to quiet or make controllable this output have gone nowhere. I think this discussion is blocking on our differing opinions about the usefulness of the output – "99% of the time it's not needed or wanted" is a subjective value statement, as is "it's useful but misunderstood". What's another way we can frame this discussion? I'm still not persuaded that it's in the best interests of npm's users to hide that information.

**Comment by guyellis** [comment]
What if this could be configured through .npmrc? That way those of use who want an abbreviated output would only have to change this setting once per machine.

**Comment by othiym23** [comment]
I've let this sit in the back of my mind for a week or so, and I still feel pretty strongly that the tree output is useful to most users, and if anything needs to be evangelized more so people understand what it's telling them. I think that it's useful for people to see just how big and complex an install is when a dependency is first installed. I also think, especially with  `npm@3`, it's good to see what's changed in the install tree when making smaller changes to the tree.

If you really don't want to see that output, or don't want to show it from tooling that's in turn calling npm, it's easy enough to redirect `stdout` to `/dev/null` or filter it for only the list of additions and removals.

Thanks for talking it through with me!

**Comment by guyellis** [comment]
Thanks for consider this @othiym23

**Comment by jmas** [comment]
Can we add some option that can only check zero-dependencies level. Mainly for speed-up build process.
Currently I have 20+ dependencies and CI server we each time do `npm install` to be sure that all dependencies are installed. But it takes 7+ seconds only for check 20+ items. Maybe we can add option `npm install --chek-depth 0` to check only zero-level of dependencies and that decide: do `npm install` or not.

**Comment by guyellis** [comment]
@othiym23 I just tried `npm i --depth 0` and it looks like this feature has been added to npm. Awesome work - thank you for doing that! I'm using npm 3.10.7. Do you know which version this was added in?
