### ISSUE TITLE
Updating from npm 3.4.0 to 3.4.1 using npm install npm -g on Windows

### ISSUE THREAD

**Issue by sgwatgit** [npm/npm#10470]
I'm on Windows and have `npm` installed globally and the global version is the one I've been using instead of the version bundled with `node`.

Recently I tried updating to `3.4.1` and I've been encountering errors so I replayed the install of `npm` globally from scratch.

First I run `npm -v` and get `3.3.12` which is bundled with `node 5.1.0`

Then I run `npm install npm -g`

I update my `PATH` to look at npm's directory before node's and restart my shell and run `npm -v` again which returns `3.4.0`.

Now (`npm` at version `3.4.0` when I run `npm install npm -g` I get errors

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sean\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.0
npm ERR! path C:\Users\Sean\AppData\Roaming\npm\npm
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Sean\AppData\Roaming\npm\npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\Sean\AppData\Roaming\npm\npm']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Sean\\AppData\\Roaming\\npm\\npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

Note that any time I install a global package I run my shell as an Administrator and my `PATH` contains `C:\Users\Sean\AppData\Roaming\npm` for accessing the globally installed `npm`.

I have also used `npm` to update itself globally in the past without issue.

**Comment by manishsankari1** [comment]
I'm having same problem .

**Comment by oh-ren** [comment]
I run into these kind of errors somewhat on a regular basis (updating packages). Could well be my AV is the culprit (see e.g. Medium/phantomjs#28)

Just trying again works most of the time in my case. I run as a regular user, and never actually have to switch to administrator.

Other times the issue seems more tenacious, and in that case it seems to work to close everything that uses node (packages), including command prompts in which I worked with node/npm earlier (could be file handle issues?) Sometimes issues can get resolved by restarting explorer.exe, but I don't think I have had to do that in this regard..

**Comment by darkmorpher** [comment]
@sgwatgit > *I update my PATH to look at npm's directory before node's*

Are you sure you set the path is correctly? Check your env path `echo %path%`

Because this looks odd (when I compare with mine):

C:\Users\Sean\AppData\Roaming\npm\ ~~npm~~
C:\Users\Sean\AppData\Roaming\npm\node_modules~~\npm~~ \bin\npm-cli.js

**Comment by darkmorpher** [comment]
@sgwatgit > *I update my PATH to look at npm's directory before node's*

Are you sure you set the path is correctly? Check your env path `echo %path%`

Because this looks odd (when I compare with mine):

C:\Users\Sean\AppData\Roaming\npm\ ~~npm~~
C:\Users\Sean\AppData\Roaming\npm\node_modules~~\npm~~ \bin\npm-cli.js

**Edit**: 3.4.1 is known to break npm when updating itself #10394. Switch to 3.5.x when safe or stick npm version that ships Node.JS
