### ISSUE TITLE
Several .js files have illegal return and throw statements at the top level

### ISSUE THREAD

**Issue by yurivict** [npm/npm#10486]
Here is the complete list of files, esprima complains about them:
```
node_modules/fstream-npm/node_modules/fstream-ignore/test/common.js
node_modules/init-package-json/node_modules/promzard/test/exports.js
node_modules/init-package-json/node_modules/promzard/test/fn.js
node_modules/lockfile/test/stale-contention.js
node_modules/mkdirp/bin/cmd.js
node_modules/node-gyp/bin/node-gyp.js
node_modules/osenv/test/unix.js
node_modules/osenv/test/windows.js
node_modules/request/node_modules/bl/test/test.js
node_modules/slide/lib/async-map-ordered.js
```

Here is the program that parses .js:
```
#!/usr/bin/env node

esprima = require('esprima')
const stripShebang = require('strip-shebang');
fs = require("fs");

function parseFile(fname) {
  var str = fs.readFileSync(fname, "utf8")
  str = stripShebang(str)
  esprima.parse(str)
}

parseFile(process.argv[2])
```

**Comment by othiym23** [comment]
We ensure that the npm source passes through `standard` as of `npm@3`, but otherwise don't apply syntax checking to the files. Thanks for putting this together, and thanks for the list, but this isn't something that we're interested in changing in the distribution.

**Comment by othiym23** [comment]
Also, to be clear, most of those are in npm's dependencies, and it's not been our policy to do anything with dependencies except filter out obvious cruft when upgrading those dependencies for bundling by npm. I'm reluctant to change this policy because it's another step in the merge process that doesn't materially benefit the CLI team.

**Comment by yurivict** [comment]
This is an invalid JS syntax. Any tools that are run on npm that analyze/modify code will fail.

The worst offenders are node-gyp, slide, mkdirp, others are in tests.

I am trying to run the line tracer to understand why npm runs differently on different platforms. But how can this be done of the code can't be parsed in a standard way.

**Comment by othiym23** [comment]
Because Node.js wraps CommonJS module files within function wrappers at load time, those top-level returns and throws are valid syntax for JavaScript consumed by Node.js. If a parser intended for use with Node.js programs fails due to those statements, that's a bug in the tool, not in npm's code. If you're working with generic JavaScript tools and don't have time to modify (or find) tools that will work properly with the CommonJS module format, I suggest you modify the source locally and float a patch for use with your testing.

Alternately, you can submit pull requests to the affected packages, as I think all of those dependencies are maintained by the npm CLI team (save `request`), and I don't think we'd have any objection to accepting patches as long as they didn't result in changes to the affected packages' behavior. That will probably take a couple months before everything gets landed and upgraded, though, so a floating patch (or tools that don't have problems with CJS) would be a lot simpler.

**Comment by yurivict** [comment]
Look at this file: https://github.com/npm/npm/blob/master/node_modules/slide/lib/async-map-ordered.js

-- Error: Line 66: Unexpected end of input
This can't be okay by any standard.

**Comment by othiym23** [comment]
Look at the second line of that file – it's not meant to be used, and I highly doubt anything in `slide` (much less npm) uses it. What are you using for instrumentation? Is there a way to get it to only look at code that's required by an application cation? I'd like to help, but the issues you've highlighted thus far aren't issues that cause problems for npm itself, especially given that they're in npm's bundled dependencies, and not in npm's own code.

**Comment by yurivict** [comment]
Okay, no problem, thanks!
