### ISSUE TITLE
Spurious warnings when installing non-bundled dependencies

### ISSUE THREAD

**Issue by iarna** [npm/npm#10489]
It looks like:

```
npm WARN In npm-registry-mock@1.0.1 replacing bundled version of util-extend with util-extend@1.0.1
```

And it happens when a non-bundled dependency is due to have another module nested under it.

We should check to see if this dependency is included in its parent module. If it isn't, it shouldn't warn.

See: lib/install/action/extract.js

**Comment by jpaulin** [comment]
How is this issue going at the moment? Can I get pointers further to it?

Because in real life, getting a lot of these 'replacing bundled version of' bla bla. :) 

A background primer would also be of value, if not somekind of live issue to it. I gather that what is happening is that due to a recent change (to npm, the software) there's now a new mechanism how to deal with nested deps ?
