### ISSUE TITLE
enhance the "main" field of the package.json for entry folder

### ISSUE THREAD

**Issue by taijiweb** [npm/npm#10506]
I hope that the "main" field can specify a folder as the module entry, so that the root folder can be not polluted by many JavaScript files and folders.

npm should can distinct file entry from folder entry by a tailing slash.

Say, for the folder structure like below:

	foo
	|----src
	|    |---- a.coffee
	|    |---- b.coffee
	|    \---- index.coffee
	|
	|----lib
	|    |---- a.js
	|    |---- b.js
	|    \---- index.js
	|
	|---- .gitignore
	|---- gulpfile.js
	|---- package.json
	|---- license
	\---- readme.md

And with the package.json file as below:

    {
      ...
      main: "lib/"
      ...
    }

By this method, we can tell npm to use foo/lib/index.js as the module entry. If there exists only one file in lib/ folder, it will be used, and it should can use other file name.

We can also use the syntax below to specify a entry file for the "foo" module

    {
      ...
      main: "lib/ @ path/to/foo-entry.js"
      ...
    }

Some spaces before or/and after @ are permitted and can be omitted.

Without the improvement above, we must write require("foo/lib/a"), require("foo/lib/b"). It's a bit annoying. To avoid this, under the current package.json specification, we must put all the folders and script files under the root folder, like below:

	|----src
	|    |---- a.coffee
	|    |---- b.coffee
	|    \---- index.coffee
	|
	|---- a.js
	|---- b.js
	|---- index.js
	|---- .gitignore
	|---- gulpfile.js
	|---- package.json
	|---- license
	\---- readme.md

Here two annoying problems exists: 

1. the module's root folder is a mess with mixing the script files and other kind of files. 
2. It's more annoying while we are writing the build script.

E.g. for "gulp clean", we need write the code below

    del = require("del");
	gulp.task("clean", function(callback){ 
      del(["*.js", "!gulpfile.js"], callback); 
    })

Especially while there are a lot of sub folders and scripts in foo/src folder, some code like below need to be written:

    del = require("del");
	gulp.task("clean", function(callback){ 
      del([ "*/", 
            "!doc/", 
            "!test/",
            // ... other folder should not be deleted 
            "*.js", 
            "!gulpfile.js",
            // ... other js files should not be deleted
          ], callback); 
    })

I'm always afraid to delete some other files by mistake while I am doing this.

With the improvement described as above, we can use `{ ... main: "lib/", ...}` in package.json to enable writing require("foo/a"),  require("foo/b") instead, simply. So we can organize the module and api more conveniently, and small sub modules is encouraged.

I think the syntax `{ main: "entry-folder/" } or `{ main: "entry-folder/ @path/to/entry-file.js" }' will not break the existed package.json. We can talk about this more deeply.

I'm not sure this improvement should be implemented in npm or in node.js. I'll submit this in node.js project, too.

Below is the specification for the "main" field in npm document:

	main
	
	The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module's exports object will be returned.
	
	This should be a module ID relative to the root of your package folder.
	
	For most modules, it makes the most sense to have a main script and often not much else.

**Comment by taijiweb** [comment]
I've submitted the same issue on the [node.js project](https://github.com/nodejs/node/issues/3953).

If this should be done in node.js, please close this issue here. Thanks.

**Comment by richard-flosi** [comment]
This is exactly what I'm trying to do right now. Is this not possible?

**Comment by taijiweb** [comment]
@richard-flosi , I'm glad to hear that you'll being work on this. I think this should be possible. this is my issue about this  on node.js project, https://github.com/nodejs/node/issues/3953, but they seems not to going to do this. Maybe the next big version of node.js is a chance.

**Comment by othiym23** [comment]
This would require changes to the Node module resolution algorithm. As was noted on nodejs/node#3953 when @evanlucas closed it, the Node module loader is basically sacred writ at this point, and won't be changed. As such, it doesn't really make sense just to change it on the publishing side in npm-land, so the CLI team won't be landing changes like this either. Thanks for your time, and thanks for your patience.

**Comment by andynoelker** [comment]
Does anyone have an alternative solution to this problem, since it will in no way be changed through node module resolution?

I am developing a local package. Just like OP, I currently have to `require("foo/lib/a")` when I really want to `require("foo/a")`. I have tried adding a `postinstall` step that moves the contents of lib to the root directory and then removes the lib directory, like this: `"postinstall": "mv slib/* ./ && rm -rf lib"`.  However, because it is a `postintall` script, it gets run every time I run `npm install` when just working on the package (rather than only getting run when installed as a module in other packages) so it doesn't work for me. Anyone else have other ideas?

**Comment by iramgutierrez** [comment]
@andynoelker You can run npm install with --ignore-scripts flag to prevent execute postinstall script when you working on your package

**Comment by andynoelker** [comment]
@iramgutierrez hey thanks! I didn't know about that one. It would make my workaround a more viable solution, but I'm still not in love with it. Curious if other people have better ideas for this sort of thing.

**Comment by lostpebble** [comment]
Is there potential that this may be looked at in the future? I would really like a way to get rid of that `/lib/` or `/build/` in my module requires.

It just seems that building out my modules works out easier to require various things relative to the module root instead of doing a single file entry such as `index.js` which has to consolidate everything. Things like tree-shaking are also more fool-proof this way, because webpack and the like can cherry-pick a single export from a single file.. using the current method of just doing a whole bunch of `export * from x` in an `index.js` tends to cause headaches - and there may be unforeseen collisions in those * exports. It also seems like a lot of repetition and kind of counter-intuitive (since we've created a folder structure and defined our module exports already pretty clearly).

Would love to be able to just do something like: `import { convertToSlug } from "@company/common-utils/StringUtils";`

I'm a little surprised this is not already possible - seems like a reasonable and practical use case.

**Comment by richard-flosi** [comment]
@lostpebble Since you are using webpack, you can use `resolve.modules` for your `/lib/` or `/build/` directories.
See: https://webpack.js.org/configuration/resolve/#resolve-modules

**Comment by lostpebble** [comment]
Thanks @richard-flosi , but I'm not using webpack only. I'm separating a lot of my Node.js code out into separate modules for re-usability. These modules are then symlinked using yarn workspaces in a parent `node_modules`.

In order to keep the build and the resolution of these modules easy, I have a `src` folder and a `build` folder inside each module where `build` is simply a JavaScript mirror image of the TypeScript code in `src` (with `d.ts` typings alongside each file).

It's working really well for me so far, but my imports all look something like this:

```
import { ArrayUtils } from "@company/common-utils/build/dataTypes/ArrayUtils";
```

`postinstall` script hacks to remove `/build`, like the one above, are also not really feasible because it will clash with my development environment.

I would however like to release some of the frontend stuff on npm and github at some point, and I think module resolution by relative path like this is quite a viable way to require only certain parts and reduce bundle code size. I've noticed `rxjs` does it quite nicely - although it looks like they also have quite a complex build script to make it work out. Would just be really nice to have a simple way to define a build folder as root in `package.json`.
