### ISSUE TITLE
Cannot npm login

### ISSUE THREAD

**Issue by TimMeade** [npm/npm#10509]
trying to login on osx.    seems it may be old issue.  Have reinstalled node after removing older.

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:millicorp
```

**Comment by inorganik** [comment]
Same error. Tried troubleshoting tips [here](https://github.com/npm/npm/wiki/Troubleshooting#npm-login-errors) and problem persisted.

**Comment by othiym23** [comment]
In both your cases, this is probably due to it having been sufficiently long since you changed your npm passwords that the stored hashes are in a format the current registry doesn't know how to deal with. If you use the [forgotten password](https://www.npmjs.com/forgot) flow on the web site, it should be able to get you unstuck.

**Comment by inorganik** [comment]
The troubleshooting page I linked suggests changing my password on npmjs.com, and I've done that several times. You'd think that would accomplish the same thing, but I'll try the forgotten password flow.

**Comment by inorganik** [comment]
Still same issue.

**Comment by othiym23** [comment]
@inorganik, I'm having our registry team take a look at this, because that definitely should not be happening. I know this is a super basic question, but you've verified that you're using the right combination of username, email address, and password in both places, right?

**Comment by TimMeade** [comment]
I think it may have something to do with the changeover to orgs…

I can login now, and publish but I can see the private npm because it says I'm not a paying customer when I am.

When I publish it says I'm not a paying customer but the NPM is visible on the web page.

I opened another ticket this morning.

Tim

**Comment by inorganik** [comment]
Thanks. Yea, I've logged out and logged back in on npmjs.org several times to make sure. I've run `npm update`, changed directories just for the heck of it... tried again and again... no luck

**Comment by othiym23** [comment]
Since this is an issue with the registry infrastructure, it'll probably be easiest to ensure that neither of you fall through the cracks if you both get in touch with support@npmjs.com. I'll leave this issue alone until the problem's resolved, but right now I'm playing a game of telephone with the various other engineering teams here, and the support team's much better placed to handle that than I am. Feel free to mention me or this issue in your messages so the support team knows who to ping.

**Comment by inorganik** [comment]
Thanks for your help @othiym23 !

**Comment by inorganik** [comment]
updating npm solved this form me. Simply running `npm update` won't update it though, you need to run `npm install -g npm`.

**Comment by snopeks** [comment]
@inorganik glad to hear your login issue was resolved by upgrading your npm version. 

@TimMeade since your login issues are fixed now as well, I'm going to close this as resolved.
