### ISSUE TITLE
[Learning Help] external lib files for sample project

### ISSUE THREAD

**Issue by DeChrish** [npm/npm#10561]
IF ITS NOT THE RIGHT FORUM - Please suggest me the right place to clear my doubts

I have shared lib files as a repo, and i need to import the lib files for my sample project. 
But i am not able to access the lib files from sample project. 

Steps done: 
1. Created lib files as repo with package.json - https://github.com/DeChrish/webdriverjs-lib.git
2. Created sample project including ablove lib repo in package.json - https://github.com/DeChrish/webdriverjs-sample-project.git
3. Created a sample test.js in sample project
4. running the test.js with node

Failure:
Error: Cannot find module './node_module/webdriverjs-lib'

**Comment by dasilvacontin** [comment]
You should simply do:

var  env = require('webdriverjs-lib')

Make sure the dependency is correctly installed.

**Comment by DeChrish** [comment]
That's what I did, but it's not finding it from node modules

**Comment by dasilvacontin** [comment]
That's not what I see in the screenshot. When you install a module, you require it using only it's name, `require('webdriverjs-lib')`.

Also, your lib's `package.json` is missing the `main` field. So it shouldn't know what to return when `require`d.

**Comment by DeChrish** [comment]
Can you mark where is the err, i tried adding the 'main' in the 'package.json' . still i am getting error

**Comment by dasilvacontin** [comment]
It still fails because the `"main"` field you added to the lib's `package.json` is invalid. The value of the `"main"` field should be the file (module) you want to "return" when your package is `require`d. So the value of the `"main"` field should be an existing file. https://docs.npmjs.com/files/package.json#main

Remember to re-install `webdriverjs-lib` in your sample project to pull any changes you've made to it.

**Comment by DeChrish** [comment]
@dasilvacontin Thanks
