### ISSUE TITLE
Turn off dedupe

### ISSUE THREAD

**Issue by Auxolust** [npm/npm#10591]
Is there an option that can return npm to its nested files structure rather than its flat listing? The current version of npm is constantly messing with my file structure and producing a lot off noise on the file system by deleting and moving resources, as well as constantly breaking dependancy links and sometimes taking more than 5 minutes to get a dependancy as its trying to update hundreds of packages and dedupe trees.

**Comment by othiym23** [comment]
This behavior is by design, and is one of the major features of `npm@3`. As such, we're not going to turn it off, and I hope that you find it more useful than annoying after you spend some time with it. Keep in mind that the deduping is a very small part of what's changed in the install process, and the files getting moved around and the network and filesystem activity in `npm@3` would be happening mostly regardless of how flat the top-level `node-modules` is.
