### ISSUE TITLE
V3 flat deps: Accidental reliance on a dependency's dependency.

### ISSUE THREAD

**Issue by damncabbage** [npm/npm#10599]
(I had a look through the issues list, but haven't found anything covering this; pardon me if this is a duplicate.)

npm v3+'s flat installation of dependencies in the NODE_PATH means that it's now possible for developers to accidentally shoot themselves in the foot by `require()`ing dependencies they haven't explicitly added to their own `package.json`.

For example ([see code listing](https://gist.github.com/damncabbage/5edce1b671464386d969)):

```
$ cat package.json
{
  "name": "depdep",
  ...
  "dependencies": {
    "gulp": "^3.9.0"
  }
}
$ cat index.js
var gulp    = require('gulp')
  , through = require('through2')  // This is Gulp's dependency; we haven't added it ourselves.

console.log("Doesn't complain about me using through2.");
```

When run with npm v2.x:

```
$ node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/...../index.js:2:15)
...
```

And now with npm v3.4.1:

```
$ node index.js
Doesn't complain about me using through2.
```

Although initially this doesn't seem like such a bad thing, if Gulp were to upgrade through2 to a backwards-incompatible version (or drop it entirely), my code would suddenly stop working. If it's not allowed (or at least emits a warning), then at least I'll know up-front if I've accidentally made an error.

For example, this is Cabal warning me that I've used `lens`, a package that's used by one of my library's dependencies, but not listed in my `mylibrary.cabal` file:

```
src/MyLibrary/Example.hs:23:18:
    Could not find module ‘Control.Lens’
    It is a member of the hidden package ‘lens-4.9.1’.
    Perhaps you need to add ‘lens’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

(I've made this particular mistake this multiple times in other languages, and now once in JS with npm 3. Having talked to other people, it's definitely something that people run into.)

How to solve this? I'm not sure, to be frank. The things that come to mind (though I've no idea how practical these are):
- Overriding `require()` (like Bundler does in Ruby); doing so would give the opportunity to raise an error.
- An optional static-analysis of uses of `require()` in the code, a little like Browserify's AST-parsing sweep, that could be run as part of a build process.

I'd love to hear your thoughts on this. Thanks for all your collective work on npm. :smiley:

**Comment by yortus** [comment]
I have the same concern. I had an idea for a possible solution too, where npm could install indirect dependencies one level deeper, in a second-level `node_modules` folder.

So in your example you'd get a folder structure like:
```
depdep
|---node_modules
    |---gulp
    |---<...all other direct dependencies>
    |---node_modules
        |---through2
        |---<...all other indirect dependencies>
```

According to the [modules API docs](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders), this structure would allow `gulp` to `require('through2')` successfully, but doing `require('through2')` from `depdep` would fail.

But in practice this does not work despite what the module loading docs say. I opened [this issue](https://github.com/nodejs/node/issues/3873) on the node repo, and the team has clarified that the docs are wrong, not the loader.

It's a shame because it would be a simple solution that allows for both a flat dependency tree and for early failure when `require`ing undeclared dependencies.

**Comment by dbuentello** [comment]
Ive noticed this as well (did a quick sanity check). Seems like this would have a lot undesired consequences.

**Comment by doowb** [comment]
I've been running into this also. I don't always recognize it until I tried to use a library in another module and I get the "cannot find module X" error. This happens because in development, the module might be a dependency of a dev dependency (like with gulp) and won't be installed when used as a dependency in another module.

We use [lint-deps](https://www.npmjs.com/package/lint-deps) to do a static analysis like @damncabbage suggests above. It will report all missing dependencies that are found in `require` statements, but not in the `package.json`. You may also choose to install them and add them to `dependencies` or `devDependencies`.

We usually run it manually, but it could be integrated into a pre-build/publish step.
