### ISSUE TITLE
Effect of acceptance terms in node.js 4.x.x, 5.x.x, and io.js 3.3.x

### ISSUE THREAD

**Issue by scriptjs** [npm/npm#10601]
The terms of service of NPM were included by reference in each copy of node downloaded since Sept 2015. These terms were attached to the Artistic License by NPM's lawyer. NPM is in the process of taking steps with v3.5.1 to resolve this but it has not yet come into any release of node.

https://github.com/nodejs/node/issues/3959

That said, changes for the future do not remedy the hundreds of thousands (or more) downloads distributed and in use since Sept 2015 including all node 4.x.x  LTS and node 5.x.x stable software releases. This also involves io.js releases at 3.3.x.

Users had not been made aware of the changes to the license and entered into the terms without their knowledge and consent (as a result of the download). The terms also inferred ambiguous references that included among other things, a free license to use your code in any way NPM wants (whether it is open or closed source).

```
You own Your Content, but grant npm a license to use it free of charge. 
That license allows npm to do whatever it needs to do with your content, 
within reason, to provide and improve npm Services, for you and other users. 
That license lasts, for each piece of Your Content, until the last copy disappears
from npm's backups, caches, and other systems, after you delete it from the
Website or the Public Registry.
```

Making matters more confusing, the license user's believe they were accepting in the installer and that they see on the node site was not the same license that was bundled in in the node software itself.

I am requesting that NPM prepare language to properly and publicly communicate to the community about the error and to advise users that may have inadvertently accepted NPMs terms of service on this basis, that they will NOT be bound to the terms of service of the NPM site if they do not use the service. In addition, to bind the terms to the License was a mistake that is being corrected with specific node patch releases.

**Comment by isaacs** [comment]
Hi, @scriptjs.  Despite the impressive amount of words you've written on this subject, I'm still not clear exactly what the problem is here that needs to be addressed in any way.

Everyone who uses the npm registry does so according to the Terms of that Service, and like all Terms of Service, they only apply to the Service.  This is obvious to everyone.  Please stop trying to convince me that I have asserted rights which I am telling you I have not.  There's no damage done, so there's no reason for us to apologize on that front.

Prior to the most recent change to the Terms of Service, the effective rules for using the npm registry were "Isaac will delete whatever he wants, store it wherever he wants, and in general, do all the things necessary to ensure that the registry is a functional commons (in his opinion)".  Now, the terms explicitly delegate that authority and responsibility to a company, in a way that is *not* implicit or unstated, which is especially important as we're no longer storing strictly open source code.  It's better.  You yourself have acknowledged that the current state of the npm cli license and the npm registry ToS is perfectly 100% ok.

We have emailed everyone whose email address we have about the new ToS.  That's everyone affected, because those are the people sending content to us.  We're also moving forward with the goal of eventually making ToS acceptance an explicit part of the sign-up flow, but it's difficult for backwards-compatibility reasons to do all in one go.  We developed the ToS in the open, and have discussed user feedback in the open.  You'd be hard-pressed to find *any* company, in OSS or elsewhere, as transparent about their Terms of Service.  I am insulted by the implication that we're trying to slip something by our users.

It was unfortunate that the license in the iojs/Node.js installer did not show the most recent npm license.  It also did not show the most recent Node.js license!  It's not the responsibility of anyone at npm, Inc. or on the npm team to ensure that these installers stay up to date.  If you want some kind of public apology or contrition, you should be bugging the Node Foundation about that.

If anything, it seems npm should be upset with the Node folks about shipping our software without accurately representing our license terms, but we're very forgiving.  Virtually no one reads those installer disclaimers anyway, so I'd be more concerned about the intent expressed in the LICENSE file itself in the source and on GitHub, as that's where any well-informed dev will know to look for those terms later.  The license shipping with npm has said for over a year that there are additional terms on the website.  Those terms got *more* explicit, and *more* lenient, rather than less, so I'm not sure what the real problem is there.

The Node.js project is moving forward on pulling in a version of npm with the new license, and also adding process in place to make sure that the license in the installer matches those in the various files it pulls from.

I and many other members of the npm and Node.js teams have gone above and beyond to try to do the right thing here.  Numerous professional lawyers have been involved and have reviewed the various licenses and agreements with an eye to the actual legal issues involved for all parties.  Everyone seems to agree that this is not a fire worth worrying about, and yet you continue to agitate on this issue in numerous different forums.  It's extremely distracting.

What's going on?  Can you please just state in clear simple words exactly what you want?  Is it really just that you want us to apologize that the installer showed the wrong license file?

I'm losing patience for this issue, and I cannot allow it to continue sapping time and attention that could be spent making Node and npm better.  Tell me what you want.

**Comment by scriptjs** [comment]
@issacs The issue has been straight forward on the matter of licensing from the start. It was filed to bring about needed changes and corrections. Until the corrections were made, I asked the Node Foundation to stop distributing NPM with the download. Under the circumstances, the Node Foundation has been perpetuating the issue with their knowledge. If there are legal consequences, doing nothing to mitigate the circumstances once known makes the matter worse.

Your company has demonstrated a defensive posture. For two weeks you chose not to address this issue by having a dialog. Rather, a flurry of actions and changes were being made by your team and lawyer. Courtesy would dictate that if you are going to respond to the issue and ask for details as you have done here late last night, that you leave the issue open long enough to allow for a reply after make your statements.

Rather you closed it and this is the level of consideration and courtesy I have received. It is shameful.

At this point, I do not believe that there is any misunderstanding of the issue but one of posturing concerning accountability for dealing with it. For your benefit and those following this, I will make the issue as plain a possible below:

### The issue

1.   **NPM made a change the license of the NPM package bundled with node that extended what was previously a liberal and open source license (for the CLI) to include terms that made no differentiation between the CLI and the services of the registry.** 

This is unusual and not an accident. It is not the first company to attempted the manipulation of open source and will not be the last. As we both know, legal terms are crafted by lawyers that are given instructions to do so by their masters. The included terms were over-reaching and ambiguous. As they stood (when the issue was raised), they also permitted your company to make further changes without notice to developers.

This concerns me and should concern every developer, company or consumer of node on number of levels. This license brought a changing legal landscape into node since you bundle NPM with it. Your company brought this into the Node 4 LTS release. As a result it could mean changing legal impacts during the lifecycle of the release.

At the time I reported the issue, the terms included by reference asserted NPMs right to a free license of a developer's software for virtually any use by connecting this with your to your Open Source Terms.  This is a serious concern to commercial software development.

You team has spent two weeks cleaning several things up since to create a proper separation between the CLI and registry services. That is appreciated. If this issue not come to light, I am not so certain this would have occurred.

If your company was not concerned about the audacity of your actions in the first place, there would not have been the flurry of correction. That said, NPM not gone far enough. These changes affect what happens with the NPM package and node downloads in the future but no statements were made for users that accepted the terms of the offending license without their knowledge. You have done nothing rescind the term that millions of developers would have entered into during the course of more that a year of distribution.

2.   **NPM brought additional terms into the Artistic 2.0 License by reference. As an open source license, the Artistic 2.0 license prohibits the inclusion of additional terms. This undermines the integrity of open source and rights assured under the license.**

This is not to be taken lightly. It is disturbing that no one was aware until recently. The reasons it was not detected appear to be the following:

* The license terms on the Node website did not reveal the objectionable license.
* The installer did not reveal the objectionable License
* NPM did not notify users of changes to the license in its CHANGELOG
* NPM did not notify Joyent or the Node Foundation of these changes.
* Joyent did not notify developers of the changes.
* The Node Foundation did not notify developers of the changes.

In fact, the only way one could encounter this license was to see it on your system. Since what you saw and read as licensing terms was different than what landed on your system. This is a slight of hand and deceptive.

The Node Foundation will assess this with their legal team this week. From my perspective, it may be revealed  the NPM package on this basis was not open source software at all – but being distributed as such. If this bears true, it is a deception that played out affecting a large number of people and companies. For companies that are required to use open source or commercial companies that inadvertently accepted your terms, I would urge them to pursue this legally.**

3.   **When your lawyer made changes to the license, your company made no notification to developers in its CHANGELOG for NPM. As an up upstream of node, no notification was made in commits of NPM nor did any dialog seem to occur with node collaborators concerning any possible impact upon developers of node. The changes evaded detection until they were recently discovered and brought to light. During this time, the tainted license was distributed in approximately 20 - 30 million downloads and millions of companies and developers world wide.**

This is not transparency. Rightfully, there should to be outrage about how this occurred. Particularly how it entered the node release cycle undetected. The Node Foundation has pledged that it will conduct an audit. Your company has said or done nothing to address the community or NPMs culpability for this.

4.   **Developers receive node with what they believe to be liberal licensing. The NPM client client had been bundled and distributed under the Artistic License (prior to the addition of terms that tainted the license). The tainted license was inserted into node, that bound anyone receiving the download to your terms without their knowledge or consent. Companies and developers were also receiving this without choice.**

Choice is an important factor in determining whether to use software or not. The choice to use NPM is not one that developers made but that Joyent (prior to the Node Foundation's involvement) made to bundle NPM with node. Personally, I feel that it was a poor decision that eliminated a diversity of potential solutions. It is a fact there is nothing in the node module system that requires NPM, nor does it need to remain this way.

My recommendation is that based on what has occurred here, that this is an indication of the vulnerability in the ecosystem and that the Node Foundation and developers need to actively work to eliminate this monopoly. You will see this addressed here:

https://github.com/nodejs/TSC/issues/21

This goes beyond package distribution since your company has also been asserting itself with changes to the package.json. The manifest is something that is in the community interest and any changes ought to be highly consultative.

In any case, when the offending license was included, and done so without informing developer of the changes there was no opportunity for developers or the community to express concerns or to reject the changes. This slight of hand allowed millions of downloads before being discovered in mid November – this is unacceptable.

###Resolution

I have addressed what I expect to be the resolution of the issue in the past at least two or three times. I will repeat it here for your benefit:

1.   I expect the Node Foundation (that distributed the node software with the tainted license) to use its public channels to communicate about the issue and how it is being resolved.

2.   I expect NPM to use its public channels to communicate about the issue and the resolutions it its putting forward. I believe the community needs assurance of greater transparency and handling of these issues. Along these lines, there needs to be a complete review of how this software entered node releases.

3.   NPM and the Node Foundation need to update the licenses and restore the Artistic License on the NPM client software. These changes have worked their way through the recent NPM releases but are not yet in node.

https://github.com/nodejs/node/blob/v5.1.1/deps/npm/LICENSE
https://github.com/nodejs/node/blob/v4.2.3/deps/npm/LICENSE

```
The following additional terms shall apply to use of the npm software, the npm
website, the npm repository and any other services or products offered by npm,
Inc.:

...

Additional policies relating to, and restrictions on use of, npm products and
services are available on the npm website.  All such policies and restrictions,
as updated from time to time, are hereby incorporated into this license
agreement. By using npm, you acknowledge your agreement to all such policies
and restrictions.
```

4.   Given the circumstance that you broadly bound terms to the CLI software and millions of downloads were received this way, your company must rescind the terms attached that were inadvertently accepted in the download for use of the CLI software.

Even while you have since manipulated your policies to make them more palatable since the issue was reported, this would eliminate any doubt that that what you have done was ill conceived, and you are in the process of working with the Node Foundation to restore a proper open source license to bundle with node.

5.   Lastly, I want the Node Foundation to communicate a legal opinion about whether the tainted license is an open source license. I want Linux Foundation lawyers to determined whether they feel there is an impact to users on this basis, and if the terms as there were are enforceable given they conflict the Artistic License that prohibits the inclusion of additional terms.

**Comment by isaacs** [comment]
The npm cli was never licensed under anything other than the Artistic License 2.0.  The additional terms did not apply to the cli itself, but to the use of npm registry services, website, and other products.

This has been pointed out to you several times.  Professional lawyers who have reviewed the situation (both working for npm as well as other parties) have said that this interpretation is accurate.

It wasn't clear enough, as your misunderstanding demonstrates.  We've clarified it.  That issue is over, and I have nothing more to say about it.

> This goes beyond package distribution since your company has also been asserting itself with changes to the package.json. The manifest is something that is in the community interest and any changes ought to be highly consultative.

I suspect that you're referring to the changes to how the npm cli warns on the `license` field using SPDX format.  Those changes were, in fact, highly consultative.

I've asked you to stop claiming that we have asserted rights that we have not asserted.  Since you have not complied with that request, well past the bounds of good faith, this conversation is over.
