### ISSUE TITLE
Cannot find module (sub dependency) after successful install with npm@2.14.13 & node@4.2.2

### ISSUE THREAD

**Issue by gr2m** [npm/npm#10634]
Starting last week, we have seen issues with starting node apps after successful npm installs, where it would complain that a module like `rc` is missing, although it is clearly listed as dependency of the sub module. @bcoe looked a bit into it and thinks the problem could be the depth of the folders.

Here is a log of how to reproduce the issue with one of our modules with a clean node & npm install (using nvm): https://gist.github.com/574ff5c49620a24a280a

The part at the end (when running `npm ls`) is what we can’t understand:

```
npm ERR! missing: couchdb-bootstrap@1.10.4, required by kazana-bootstrap@2.1.0
npm ERR! missing: moment@2.10.6, required by kazana-bootstrap@2.1.0
npm ERR! missing: nano@6.1.5, required by kazana-bootstrap@2.1.0
npm ERR! missing: rc@^1.1.2, required by kazana-config@5.3.0
npm ERR! missing: rc@^1.1.2, required by kazana-transform@1.5.1
```

We worked around the problem by adding the dependencies directly to our apps, but we would still love to understand what the problem here is.

**Comment by iarna** [comment]
I would give a try w/ npm@3, as it was a rewrite of the whole install process and while we haven't ironed out _all_ the bugs as yet, they're not the same bugs as npm@2.

Further, npm@3 can fix a tree with missing modules like that without having to start over.

**Comment by gr2m** [comment]
yeah, the issue does not exist in npm@3. But unfortunately we can’t use npm@3 in our case, we work on the LTS versions of Node & npm

**Comment by othiym23** [comment]
I dug into this a little bit, and it looks like it's a bundling issue. `kazana-server` bundles `kazana-bootstrap`, but the `kazana-bootstrap` that's bundled in `kazana-server@3.8.0` is missing its own dependencies (which is probably just due to them not having been installed when `kazana-server@3.8.0` was published). The workaround is to publish a new version of `kazana-server`, running `npm ls` _before_ publishing to ensure that all the dependencies are available to bundle. (That preflight checking should probably be part of `npm publish`, and if somebody wanted to add a check that all `bundleDependencies` are installed before packing the tarball, that would be _rad._)

The install works in `npm@3` and not `npm@2` because `npm@3` has changes to ensure that when installing `bundleDependencies`, it fills in any of their missing dependencies. This is a bug in versions of `npm@<3`, but I don't think the CLI team will have much time to devote to this in the near to medium term. If you were to figure this out and submit a fix, the team would (of course) get it merged and released in fairly short order.

npm's LTS is an evolving thing, but it's really meant to ensure that the version of npm packaged with Node LTS is free of critical bugs and security flaws. This _is_ something fixed in `npm@3`, so the best course of action is to upgrade to the new version. I understand that external requirements may dictate otherwise, so give the workaround from above a shot and tell us how it goes.
