### ISSUE TITLE
【npm@3】too many folders..i just require 2 package

### ISSUE THREAD

**Issue by tommyZZM** [npm/npm#10643]
but it gives me tens of folder in node_modules..

how can i install package like before ? 

or should i just roll back to npm@2 ?

**Comment by drkibitz** [comment]
@tommyZZM This is intentional. Those 2 packages depend on things, which depend on more things, which depend on more things, etc..

The structure of this directory is to help NPM alleviate the duplication of module installations. With a simple `ls ./node_modules` this also results in a much broader view into what you are actually depending on.

`npm ls` gives you a clear view already, but now your node_modules directory will reflect a little more of this as well.

**Comment by othiym23** [comment]
As @drkibitz said, this is one of the key features of `npm@3`, which is that it flattens and dedupes the package tree by default. You can learn more about this [in `npm@3`'s release notes](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat).

**Comment by tommyZZM** [comment]
thx
