### ISSUE TITLE
throw an error if user is trying to publish a package bundled with node.js

### ISSUE THREAD

**Issue by capaj** [npm/npm#10689]
I recently inherited a project, where a developer thought that all modules have to be installed via NPM.
By all I mean literally. He installed 'crypto' and 'path'  and couple of others. Let me give you links:
https://www.npmjs.com/package/crypto
https://www.npmjs.com/package/path

I was baffled. When I inspected those, I had worked with node.js and I always thought those were bundled with node.js. Of course they are! No one should be wasting megabytes of bandwidth to download those.
The module from node.js is preferred over that from node_modules, so it is fairly safe, because these 'fake' native modules don't get executed when you require them(unless you specify the require with a path). Well and that is the whole point I guess. If you can't really require them, why have them in npm?

They are useless, confusing for beginners and just plain awful. In some cases, even their maintainers don't know what they are for:
https://github.com/jinder/path/issues/6

So please remove those modules from NPM and ban people from publishing them.

**Comment by othiym23** [comment]
The versions of those modules up on the registry are used by some browserify workflows, which would break were we to remove them from the registry. It can be confusing, because Node.js won't use the locally-downloaded modules (as you know), but that also means this is a pretty small problem (and I believe that most of those stub modules, except maybe `crypto`, which has some additional legacy attached to it existing prior to the built-in module, are pretty tiny). I agree that it's confusing, but people are relying on it.
