### ISSUE TITLE
specify CXX via npm config?

### ISSUE THREAD

**Issue by Mischi** [npm/npm#10716]
Hi all,

can i somehow specify CXX via npm config? I know i could set the CXX env variable but i don't want to do this every time i run npm install. I probably could create an alias but it would be nice if i could place it next to the python config setting in my npmrc.

Setting CXX in my .bashrc is not an option as i only want npm to use the non default CXX on my system.

Example:
```shell
npm config python /usr/local/bin/python2.7
npm config CXX /usr/local/bin/eg++
```

This issue was originally created here https://github.com/nodejs/node-gyp/issues/834 but as @bnoordhuis suggested, i will move the issue over to npm itself.

Best Regards,
Fabian

**Comment by othiym23** [comment]
This is something that probably needs to be hashed out in the `node-gyp` world first because of the recent changes to the requirements to build native modules against the latest versions of V8. Because they require a C++11-supporting compiler, I have some concerns about ABI interoperability if the user is overriding CXX for native module builds that I'd like to hear someone on the `node-gyp` side weigh in on before we add something to npm that could potentially be a very obscure and frustrating footgun. It's also possible there may be a way to do this via `config.gypi`, which would be a better solution if available.

**Comment by zkat** [comment]
This is something your build script can handle through regular environment stuff, and certainly not something we'll add directly to the npm configuration. @othiym23's comments might also be something to keep in mind when actually doing this, but otherwise there's not much to do here so I'm closing this.
