### ISSUE TITLE
Attempting to use NPM on Ubuntu Mate 15.10 (PowerPC) results in a core dump

### ISSUE THREAD

**Issue by PFCKrutonium** [npm/npm#10720]
Every command I try results in

```
Illegal instruction (core dumped)
```

the first time, then it fails silently every time afterwards - tell me what to do and how I can help debug this.

**Comment by othiym23** [comment]
Probably the best thing to do is run Node under a debugger like gdb to capture a stack trace when it crashes. npm is a pure JavaScript application, so any crash resulting in a core dump is almost entirely likely to be an issue with the Node.js runtime and not npm itself. Given the newness of the PowerPC port of V8 / Node.js, I wouldn't be surprised if there were some kinks to work out. I'll leave this open as a tracking issue, but I'd be really surprised if the fundamental issue turns out to be in npm rather than node.

**Comment by PFCKrutonium** [comment]
Would it be possible for you to tell me how to get gdb to do a stack trace?

**Comment by othiym23** [comment]
```
$ gdb $(which node)
(gdb) run /usr/local/bin/npm install
<wait for crash>
(gdb) bt
(gdb) info threads
```

That said, unless you're used to reading C++ stack traces, there's not going to be a lot in there that's useful to either of us. You really want to find somebody who knows something about the PowerPC ports of V8 and Node.

**Comment by PFCKrutonium** [comment]
Thanks, and I will see who I can find.
