### ISSUE TITLE
2.14.14: npm shrinkwrap output is inconsistent between runs

### ISSUE THREAD

**Issue by xaka** [npm/npm#10731]
It's quite interesting (and very annoying when it comes down to code review). 

So sometimes the output is:

```
     "bluebird": {
       "version": "2.2.2",
       "from": "https://registry.npmjs.org/bluebird/-/bluebird-2.2.2.tgz",
       "resolved": "https://registry.npmjs.org/bluebird/-/bluebird-2.2.2.tgz"
     },
```

And sometimes it's:

```
     "bluebird": {
       "version": "2.2.2",
       "from": "bluebird@>=2.2.1 <2.3.0",
       "resolved": "https://registry.npmjs.org/bluebird/-/bluebird-2.2.2.tgz"
     },
```

As you can see, `from` property is constantly being changed between semver format and full URL. It happens without even touching `bluebird` in `package.json`.

**Comment by callmevlad** [comment]
This is known behavior of npm2, and as far as I know is addressed in npm3. In the meantime, you need to use [uber/npm-shrinkwrap] to get predictable shrinkwraps with npm2.

**Comment by evocateur** [comment]
Alternatively, [https://www.npmjs.com/package/shrinkwarp](shrinkwarp) will make npm2 behaviour even cleaner.

**Comment by othiym23** [comment]
As @callmevlad said, `npm@3` produces a shrinkwrap that is much more consistent across runs than `npm@2`, so I'm going to call this issue resolved. If there are inconsistencies in the output of `npm@3`'s shrinkwrap, those should be treated as bugs and fixed, although because npm itself primarily depends on the `resolved` fields, churn in `from` has historically been treated as a relatively low priority.
