### ISSUE TITLE
npm v3 - dependencies installed inconsistent with package.json file

### ISSUE THREAD

**Issue by mpukit** [npm/npm#10733]
I've upgraded to npm v3 and am running into some unexpected activity in my modules folder. 

I run <code>npm install</code> and get oodles of unexpected packages installed into my project as a result.

Issue <a href="https://github.com/npm/npm/issues/10079">#10079</a> touches on the problem, but i'm not clear on why the dependancies I list in my package.json file are not the only dependancies installed into my project? Is there a way or a more specific command to do only fetch the packages I specify, and is it safe to delete the others?

**Comment by KenanY** [comment]
@mpukit You've already found the detailed explanation over at https://github.com/npm/npm/issues/10079. I guess I could simplify it for you, if it would help you understand. Those other packages are dependencies of the packages you have defined in your `package.json`. So no, it is not safe to delete them.

> Is there a way or a more specific command to do only fetch the packages I specify

With our without the dependencies of those packages?

**Comment by othiym23** [comment]
As @KenanY implies, the primary thing that makes `npm@3` a higher major version are the changes to the installer – the fact that it runs in discrete phases now, the fact that it deduplicates by default, and the fact that installs a maximally flat tree in `node_modules`. The [`npm@3` release notes](https://github.com/npm/npm/releases/tag/v3.0.0) are a good place to start to understand why those folders are in `node_modules` now – before, they were nested dependencies, and now they've been flattened out. Even though there's more in `node_modules` now, it's typical for an install with `npm@3` to use significantly less disk space.

Since this is the intended, designed behavior of `npm@3`, I'm going to close this issue.

**Comment by mpukit** [comment]
Thanks for the clarification.
