### ISSUE TITLE
npm 3.5.1 y 3.5.2 "npm install" all but not my packaje from packaje.json

### ISSUE THREAD

**Issue by alex-facio** [npm/npm#10751]
There many problems with this update... when you run 'npm install" in any project... npm start download all package but don't my package from package.json.
![npm](https://cloud.githubusercontent.com/assets/14911484/11672575/6d55e294-9dd7-11e5-932e-bfddbf8b7bdc.JPG)

**Comment by KenanY** [comment]
@alex-facio This is intentional... `npm@3` tries to install the dependencies of your modules as flatly as possible. [Here](https://github.com/npm/npm/blob/v3.0.0/CHANGELOG.md#flat-flat-flat) is the relevant bit in the `CHANGELOG`.

**Comment by alex-facio** [comment]
@KenanY Thanks, I finished to read change log, but I can't understand how works?, now... is confused, I tries to run npm install package.json, and fail... you can give me a example how install just package that need it? Sorry my English..

**Comment by KenanY** [comment]
@alex-facio Perhaps a small example will help. Say you have two modules, called `a` and `b`, and both modules depend on a third module named `c`. Instead of having `c` be duplicated into the `node_modules/` directories of both `a` and `b`, `npm@3` will put `c` in your project's `node_modules/` directory where both `a` and `b` can access it.

> I tries to run npm install package.json

I cannot help very much without knowing what the problem specifically is. Could you please provide more information, such as uploading the `npm-debug.log` file that is generated after an error to [gist.github.com](https://gist.github.com/)?

> you can give me a example how install just package that need it?

`npm` has always installed only the modules you need and nothing more. It has worked like this for years. The new behavior you are seeing is not `npm` installing "un-needed" modules, but simply moving "up" modules that previously were in child `node_modules/` directories.

**Comment by othiym23** [comment]
This is how the `npm@3` installer is supposed to work, so I'm closing this issue as resolved. Thanks for providing a clear example, @KenanY!
