### ISSUE TITLE
Add a warning for the cases when npm is interrupted with ^C

### ISSUE THREAD

**Issue by mik01aj** [npm/npm#10762]
I'm coming from http://stackoverflow.com/questions/34134836/is-it-safe-to-interrupt-a-running-npm-install-with-c/34135224

If interrupting npm is not safe, maybe npm could warn about it by displaying a message like this when `^C` is pressed:

```
You just interrupted a running npm process. This might cause problems if you try to use
the partially-installed packages, therefore you might need the following commands:

* rm -rf node_modules/ - to remove all your locally installed modules,
* npm cache clean - to clean the npm cache
```

Of course the text needs to be improved, but you get the idea :wink:

**Comment by kevinSuttle** [comment]
:+1: Great idea.

**Comment by zkat** [comment]
As of npm@3, anything that modifies your `node_modules` folder (such as `npm install`) will automatically repair your `node_modules/` folder -- so, if you break things with `^C`, just rerun `npm install` and you're good to go!

We consider this a good enough way to address the issue of interruptions (which have their own level of complexity), so I'm closing. Thanks for your time~

**Comment by mik01aj** [comment]
Is the npm@2 line totally closed? I believe it would make sense to add it in npm@2, because it will be still used for quite some time (it is the default in Node 4.2 LTS, which will be actively supported until April 2017).

**Comment by othiym23** [comment]
Appropriate changes to the LTS branch include fixes for severe bugs resulting in crashes, addressing security issues, and adding support for new registry features (when practical). Which of these is this proposed feature?

Also, the CLI team is not going to have the resources to get to this in the next 6-12 months, which is our current rubric for deciding whether to keep imfeature requests open. It's important that the community have a clear sense of what we're doing and what we're going to have the time to do. If you or someone else wants to send us a patch with this functionality, and it comes with tests, then it should get merged, because we've been pretty relaxed about accepting community patches to `npm@LTS` when the changes are patch-level, and I think that's useful enough to become part of the LTS policy. However, if the team doesn't intend to ship a feature ourselves, we're going to close feature requests. It's an essential part of getting the issue tracker back to being a useful tool for the community to communicate with npm's contributors.

**Comment by nathan7** [comment]
@othiym23 The suggestion seems to be basically this:
```javascript
process.on("beforeExit", function() {
  console.warn([
    "You just interrupted a running npm process. This might cause problems if you try to use",
    "the partially-installed packages, therefore you might need the following commands:\n",
    "* rm -rf node_modules/ - to remove all your locally installed modules,",
    "* npm cache clean - to clean the npm cache",
  ].join("\n"))
})
```

I'm willing to concede that it doesn't fall under "fixes for severe bugs resulting in crashes", but I think "warnings for bugs that *may result in crashes or undefined behaviour* we won't fix" shouldn't be out of scope.

**Comment by othiym23** [comment]
I think that if you frame the discussion in terms of, "what merits prioritizing LTS work for the CLI team over other maintenance or features work?" it gets a lot less ambiguous. Something must be both important and urgent for that to happen, and nice to haves like this, which are uncommon in most developer tools, are neither.
