### ISSUE TITLE
Two factor auth

### ISSUE THREAD

**Issue by jdalton** [npm/npm#10770]
With @ChALkeR's [post](https://github.com/ChALkeR/notes/blob/master/Do-not-underestimate-credentials-leaks.md) in mind is something like dual authentication
(similar to github, twitter, namecheap, gmail, etc.)  doable and the roadmap?

**Comment by othiym23** [comment]
This is more in the bailiwick of the registry team, as they're the ones responsible for the auth and login service, so you probably want to file this on [`npm/public-api`](https://github.com/npm/public-api) or [`npm/newww`](https://github.com/npm/newww) instead of here, because the only piece of this that affects the CLI is providing the prompts for authentication (or conceivably integration with platform auth strategies). This is something that's on the road map, in large part because npm On-Site already supports this for on-site registries. I don't think there's a timeframe set for it, though, so you'll want to raise this with @seldo or @ceejbot.

**Comment by jdalton** [comment]
Cool! @seldo / @ceejbot any preference on where I move this issue to?

**Comment by seldo** [comment]
I think keeping it here is a good tracker to prevent future duplicates, but cross-referencing in https://github.com/npm/public-api/issues/13

**Comment by brentvatne** [comment]
Hello! I agree that this would be very nice to have. Can I donate somewhere to help make this happen?

**Comment by ChALkeR** [comment]
@seldo That link is dead now. Is there a public issue for 2FA somewhere?

**Comment by ChALkeR** [comment]
Seems like https://github.com/npm/npm/issues/17408 is the new link now :smile:.
