### ISSUE TITLE
npm install requires login? 

### ISSUE THREAD

**Issue by bryanrasmussen** [npm/npm#10791]
I just did the following command

 sudo npm install npm -g

and got back the response 

This request requires auth credentials. Run `npm login` and repeat the request.

but that isn't going to work because I have been struggling with login / adduser whatever being broken for the last couple days over several different versions of npm. 

Is this only an old version problem, obviously installing npm should not be tightly bound to npm's auth system, since you will need to swtich versions sometimes to figure out what the hell is going on.

**Comment by bryanrasmussen** [comment]
so I completely removed npm, reinstalled node, npm version with node -v v4.2.3 is evidently 2.14.7 
running sudo npm install npm -g gives
Password:
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm" "-g"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

running npm adduser 

gets to 

npm ERR! registry error parsing json
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! Unexpected token <
npm ERR! <!doctype html>
npm ERR! <html>
npm ERR! <head><meta charset="UTF-8"><noscript><meta http-equiv="refresh" content="0; URL=/-/user/org.couchdb.user:bryanrasmussen?no_pagelet_js=1"

and so on and so forth. 

so I guess I don't know what the reason is why installing npm would require adduser first...
anyone can answer that?

**Comment by bryanrasmussen** [comment]
I figured out that if I rm $HOME/.npmrc then I can install, so I guess it might make sense to come with that in a message.

**Comment by thephilip** [comment]
Do you, by chance, have a copy of the .npmrc or are you willing to recreate the issue and create a gist of the .npmrc file and reference it here?

**Comment by bryanrasmussen** [comment]
Hey,

I get the issue with this .npmrc

always-auth=true
strict-ssl=true
ca=""
registry=https://dr.npm.nodejitsu.com/

however I note that nodejitsu.com itself is giving a 400 right now,
although I can login to our registry (which looks bad due not getting
various stylesheets whatever from nodejitsu, so not sure if that will have
 anything to do with it. ) We are trying to move over to npm itself, so if
it being on nodejitsu is itself an issue this might fix it.

Thanks,
Bryan Rasmussen

**Comment by thephilip** [comment]
Everything I've seen appears to be an authentication issue, but I'm not super experienced with private repos.  Do you get any errors when you `npm login`?

**Comment by thephilip** [comment]
One other thing could be the `strict-ssl=true` line.  Are you behind a firewall?

**Comment by bryanrasmussen** [comment]
I'm assuming I'm behind a firewall here, I am just here for a couple weeks
fixing some things.

I don't think it is authentication or firewall stuff - although I thought
it was authentication at first.

I think it is something about my system that meant that adduser either
couldn't save the token it got back from couchdb although not sure where it
needs to save it, or the token was saved in a bad way - or maybe it is some
complicated interplay of various issues.

The reasoning is -

we moved from nodejitsu (spur for the move was the problems I was having,
but it was long in planning anyway) to just straight up npm.

as part of this I had to set the scope.
and run npm adduser

I was still having the same problems though, just weird I would do npm
adduser and go through the steps but there wasn't a response coming out, it
didn't say if I failed or it worked.

but if I did npm publish it would tell me to run npm adduser.

so I went in to adduser.js and console.logged everything coming back

error was null, in the response there was the token.

I tried to run npm publish, it told me to run npm adduser.

I took that token out I got from the last run of adduser and went into
publish.js

added my username, password, email and token by hand to auth.

ran npm publish and it worked.

after I published the first time, I removed the stuff from auth I had added
in, and I can publish fine now.

my npmrc now looks like this ( my authtoken not shown)
scope=@dr
@dr:registry=https://registry.npmjs.org/
//registry.npmjs.org/:_authToken=AUTHTOKEN HERE

This process is why I am leaning towards the some sort of complicated
confluence of issues theory.

Thanks,
Bryan Rasmussen

**Comment by othiym23** [comment]
1. Try nuking `scope` from your `.npmrc` – That's hardcoding all your operations to happening within the `@dr` scope, which is very rarely what you want. Having `@dr:registry=` in `.npmrc` is sufficient to ensure that `@dr/package` always gets sent to the registry for that scope.
2. This output:

    ```
    npm ERR! <!doctype html>
    npm ERR! <html>
    npm ERR! <head><meta charset="UTF-8"><noscript><meta http-equiv="refresh" content="0; URL=/-/user/org.couchdb.user:bryanrasmussen?no_pagelet_js=1"
    ```
indicates that there's a proxy in the mix. CouchDB-based registries, and the npm primary registry (which is not really a CouchDB registry anymore) will always return JSON in response to CLI requests. I'm not sure what Nodejitsu's registry does in this case.
3. Using `always-auth=true` with the primary registry is probably going to cause surprising behavior.

All in all, what you probably want is:

```ini
registry=https://registry.npmjs.org/
@dr:registry=https://dr.npm.nodejitsu.com/
@dr:always-auth=true
//dr.npm.nodejitsu.com/:_authToken=averysecrethexstring
//registry.npmjs.org/:_authToken=anotherverysecrethextstring
```

If you're trying to migrate packages from `dr.npm.nodejitsu.com` to a scope named `@dr` on the primary registry, you're probably going to want to use two entirely separate `.npmrcs` for both, because the scope-based registry configuration isn't really designed to support being logged into the same scope on two different registries. (You can also use `--scope=@dr --registry=https://dr.npm.nodejitsu.com` for individual installs or publishes, given the way that the tokens, scopes, and registries, are decoupled from each other if you use a config file format like the above.)

Let us know if this helps, and good luck!

**Comment by othiym23** [comment]
(Also, you can run `npm login --scope=@dr --registry=https://dr.npm.nodejitsu.com/ --always-auth=true`, and most of the above `.npmrc` will get created for you by the CLI.)
