### ISSUE TITLE
Package index

### ISSUE THREAD

**Issue by strarsis** [npm/npm#10807]
Tools like eyeglass traverse the node_module folder on its own 
to find/discover files of specific name and/or extension.

This is time consuming (a full scan each time) and is reimplemented/reinvented for each project.

Therefore adding an API to search for files by criteria (globbing) in currently installed packages, 
using a fast database (similar to locate in *nix) that is updated by npm 
when doing package operations, 
could speed this up dramatically and allows other projects to easily 
add this kind of discovery mechanism.

Also when package folders are missing (aborted/"dirty" npm installation), 
npm itself could detect + intervene 
(like showing a warning or even stopping the project using it by throwing an Exception).

Ideally, the package index would be generated automatically on package publish 
and then those package indices added to an overall searchable installation index 
of the project that installs+uses those packages (next to node_modules or directly inside of it).

With best regards

**Comment by othiym23** [comment]
This would also have the nearly-unavoidable side effect of considerably complicating the installer code and significantly slowing down initial application installs (because of the overhead of building the search index). Is the benefit worth the cost?

My answer (for now, at least) is that it isn't, and that this is something better handled by tools (like eyeglass) themselves. The CLI doesn't actually know that much about the contents of the files that it installs, and with `npm@3`'s new install code, incomplete or erroneous installs are much less of an issue.

> Ideally, the package index would be generated automatically on package publish and then those package indices added to an overall searchable installation index of the project that installs+uses those packages (next to node_modules or directly inside of it).

Given the existence of package scripts, git dependencies, and a number of other complicated corner cases, this is behavior that would have to live on both the registry and CLI sides. Also, like all the dependencies of the CLI, it would have to be pure JavaScript (to make npm bootstrappable). It's certainly not impossible, but it's a much bigger job than the CLI team is prepared to tackle right now, especially given that the benefits are fairly modest for the CLI itself.

So, I'm going to close this out, because this isn't something that's likely to make it on the team's roadmap in the foreseeable future. Thanks for taking the time to put together this request, though!
