### ISSUE TITLE
Way to `npm view` information from the package.json when it's not in the registry

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [npm/npm#10816]
If I'm working on an unreleased project with a `package.json`, `npm view` with no arguments fails:

    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/Paws.js
    npm ERR! 404 
    npm ERR! 404  'Paws.js' is not in the npm registry.

It's very useful for querying the JSON content of the `package.json` without farming out to other JSON tooling, whereas `npm` is guaranteed to be available in the environment; so it'd be really nice if this functioned for the *current `package.json`* without round-tripping to the registry.

Is this desirable functionality? (=

**Comment by jimmibond** [comment]
have you used json tool like http://jsonformatter.org to validate json data?

**Comment by othiym23** [comment]
> Is this desirable functionality?

My first concern is that it's confusing to have that command sometimes accessing the network and sometimes looking at what's local. I do think that using something like [`json`](http://npm.im/json) is preferable for parsing stuff out of `package.json` locally, if only because that makes very clear when you're talking to the network and when you're looking at what's on disk.

**Comment by ELLIOTTCABLE** [comment]
Hm, that's not a bad point. `json` is just about perfect; and saves some weight in `npm` itself.

So, let's call this an Issue a request to explicitly document that this is *not* something `npm view` will do? Because while I agree it's most intuitive for its behaviour to be internally consistent in all circumstances; it's *also* easy to assume that it will view local-package information; and mentioning that this is not included functionality seems worthwhile?

**Comment by othiym23** [comment]
Patches welcome! :wink:

**Comment by finnp** [comment]
Also `npm view` is currently not documented. Honestly I thought the behavior described here would be the default already. I was surprised that it is not.

**Comment by halhenke** [comment]
I can understand the consistency argument about network vs local lookups (especially since the docs describe the command as being used to "View registry info") - still this is something that I frequently find myself wishing npm could do considering how convenient it is. It also seems intuitive that `npm view .` would use the actual local package.json file rather than using the registry - and if you wanted to use the registry then you could always use the package name itself. Then again I recognise that "intuitive-ness" is in the eye of the beholder and i might be on my own with this.

Anyway - @othiym23 sorry i wasn't quite sure - are you saying that you would be happy to change this behaviour? Or is the patch about improving documentation? I would be happy to have a go at making the change if thats the intention.

**Comment by zkat** [comment]
Yes, having that documentation tweak would be nice, but not, we will probably not change the behavior of `npm view`. If you feel up to cooking up that doc PR, please send it in, but I'll close this issue for the time being.
