### ISSUE TITLE
Installing devDependencies for specified module

### ISSUE THREAD

**Issue by chrisblossom** [npm/npm#10814]
Is it possible to install devDependencies for a module listed in dependencies?

I am currently doing this with a postinstall script, although I suspect there is a better way to do it. Any better ideas are welcomed.

https://github.com/bdefore/universal-redux/issues/2
https://github.com/bdefore/universal-redux/pull/6

**Comment by iarna** [comment]
There is not any way for a package to declare its devDependencies to be installed when it is being used as a dependency of something else. devDependencies are very specifically intended for development OF the package in question, not development WITH it.

You could have your users run something like:
```
npm explore universal-redux npm install --only=dev
```
But I think that really doesn't meet your needs either– I think having a separate `-dev` package is probably the best solution. One caveat is it would need to act as dependency injection for your main module, where if present, it's used to load its dependencies, rather than `require`ing them directly, as that latter bit wouldn't be guaranteed to work (eg, in `npm@2`, or under some circumstances in `npm@3`).

**Comment by othiym23** [comment]
Closing, because this is npm behaving as expected, and the approaches that @iarna outlines are good ones for getting the desired result. Good luck finding a solution that feels comfortable!
