### ISSUE TITLE
Value of $npm_package_repository_url in a script different from value in package.json

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [npm/npm#10815]
With this line in the `package.json`,

```
"repository" : {"type" : "git", "url" : "https://github.com/Blah/Widget.git"}
```

`npm run-script` provides the following value as `"$npm_package_repository_url"`:

```
git+https://github.com/Blah/Widget.git
```

This fails with commands like `git clone ${npm_package_repository_url }` and similar. As far as I can tell, this is the only property which comes out _differently_ in a env-var than it's encoded in the `package.json`; I can't tell if this is intended, but undocumented, functionality; or a strange bug. (What even _is_ that syntax?)

**Comment by othiym23** [comment]
The values that are set in the environment variables are what comes out of `normalize-package-data`, which canonicalizes a lot of the values in `package.json` fields, including links to git repositories. That format is what npm uses internally to distinguish Git dependencies from other things hosted via HTTP[S]. I don't think this is a bug, because that's exactly the value I'd expect that to have, but maybe if you describe what it is you're trying to do, somebody can help you work through getting what you need. At a bare minimum, a calling script should use `sed` (or JavaScript!) to strip the `git+` off that URL if it's there.

**Comment by ELLIOTTCABLE** [comment]
I mean, of what use is *npm*'s internal format? I understand how ‘npm exposes whatever's set internally’ is *simple* to understand, but … I'm kind of surprised that we're not on the same page that that behaviour isn't *useful* or *desirable* to people outside of npm?

Like, unless I'm not understanding some use-case that the envvars are exposed for, they're for scripts to operate based on, right? But a value exposed in some internal format is … not useful to operate on. (Even if I know, and can fix, that value myself.)

For instance, this is what I'm resorting to at the moment to get the same data:

    repository_url="$(node -pe "require('./package').repository.url")"

Now, this obviously isn't, like, super-important to me or anything. There *are* a dozen easy ways around it. I'm just pointing out that I think exposing internal configuration data is less-useful to a large array of scripting purposes, than exposing the actual data in the `package.json`? (I *can* list use-cases for scripts using the data in `package.json`, if you'd like, but I feel like you can imagine)

**Comment by othiym23** [comment]
I agree that this isn't the most sensible or understandable format for use outside the CLI, but if you take a look at what [`lib/utils/lifecycle.js` is doing](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L269-L366), it's pretty a simple-minded of what's in the configuration and the package into the child environment. I have no objection to making changes to that data to make it more ergonomic for people writing package scripts, although I'd prefer it to be done in a systematic way (`"repository"` is far from the only piece of information to be transformed like this – `npm run env` will allow you to see at once how much data there is, and how it gets transformed).

The tricky part is that would need to happen in `lifecycle.js` itself, because otherwise it could break npm. This is why it's relevant that this dump is based on the internal representation used by the CLI itself. I also have concerns that there are people out there depending on the current representation, so changes here should be considered semver-major (which is fine – I anticipate another semver-major release, just for these kinds of changes, sometime in February or March of 2016). The CLI team itself is probably not going to have any cycles to get to this for the foreseeable future, though.

**Comment by ELLIOTTCABLE** [comment]
Hm. So your suspicion is that this would be a difficult change for an outsider to tackle? (Not that I'm particularly offering, but if you think it's approachable, and nobody inside the team is likely to have time anytime soon, I can put it on my contributions ‘stack’ …)

**Comment by othiym23** [comment]
> So your suspicion is that this would be a difficult change for an outsider to tackle?

I think it should be relatively straightforward, but it would be best for it to be a pretty interactive process so that we can get some kind of rough consensus about what it's reasonable to expect to be handed by npm as a package script author, because I don't think we've spent much time discussing (or thinking about this, really) as a community.
