### ISSUE TITLE
Should "version" be a parent object?

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#10859]
As discussed in https://github.com/npm/newww/issues/1655, here's how this would work.

```json
"version": {
   "build": "3.5.3"
   "changelog": "https://github.com/npm/npm/releases/tag/v3.5.3"
}
```

**Comment by othiym23** [comment]
To do that would be a breaking change, because every version of npm to date assumes that `"version"` is a string. It's a pretty extreme solution to a fairly small UX niggle, so I don't think it makes sense. What is the actual problem you're trying to solve here? Why does `"changelog"` need to be tied to the version in this way? Why can't it be a plain property on `package.json`, like `"readme"` (which is generated by the registry at publish time), `"license"`, or `"repository"`?

**Comment by kevinSuttle** [comment]
Totally could be a separate property, but since it can be tied directly to the version number, it could sense as an object. Perhaps just a convention to include it on the line below `version` would suffice.

**Comment by othiym23** [comment]
It might make sense as an object if it didn't break literally every version of the CLI currently in existence. ;) `"name"` and `"version"` are the two essential properties of every package, and they've been required to be strings since the inception of the CLI. 

There's nothing stopping you from adding that property to `package.json` today, and even writing tooling that would populate it on `preversion` (or some other lifecycle event) so that it gets updated automatically. In general, that's how I would prefer to see new metadata land in `package.json`: pioneered outside npm itself, to see how it works out in practice, and then incorporate it into the CLI and the web site. That's how we've been dealing with the changes to the `"license"` field, and while, due to the nature of licensing, it's been a little contentious, it's been pretty smooth aside from that.

**Comment by kevinSuttle** [comment]
👍🏼
