### ISSUE TITLE
git-based dependency pulling without git

### ISSUE THREAD

**Issue by stelcheck** [npm/npm#10894]
I know how this sounds, but please bear with me.

I am trying to develop a cli application which will be delivered through NPM. During development, I had to fork one of the modules I was using to make fixes, and decided to use that branch in my package.json for the time being.

Except, I cannot expect my end-user to already be using git, not do I want to make this a requirement.

Which bears the question: what would it take to strip out the dependency on a preinstalled git binary? I assume we'd need to use a library, and make sure this lib also behaves like the git binary in terms of configuration (config, ssh keys, etc)

**Comment by aredridel** [comment]
Not answering your issue head-on, but check out the package `scope-it`, which lets you alter a package to have a scoped name and publish it in your own namespace, but to the npm registry, not just leaving it in git.

**Comment by stelcheck** [comment]
Actually, the answer to my specific problem was actually simpler: point to a tarball on GitHub.

Example:

```
git+https://github.com/stelcheck/yargs.git#fixes/nested-command-order
```

Becomes:
```
https://github.com/stelcheck/yargs/archive/fixes/nested-command-order.tar.gz
```

Since NPM now has shorthands for download from GitHub, it could be nice if those shorthands were pointing to https instead of git+ssh. It's a breaking change, so perhaps that wouldn't be acceptable, but then instead we might want to add a marker to say, download from GitHub https? This would likely make installs faster than a full git clone on every install I presume.

With that being said, when depending on public git repos that do not require authentication, it would be nice if a git binary was not required I think.

**Comment by othiym23** [comment]
In order to properly support git dependencies properly (dealing with the needs of various hosting providers, getting a clean clone of the repo into the cache, not wasting too much time repeatedly pulling down full repositories), npm has a pretty heavily specialized git workflow that relies on special-purpose git commands, some of which are arguably reaching into the low-level plumbing commands of git. https://github.com/NodeOS/NodeOS/issues/67 discusses the work necessary to replace the git binary in npm, and as you can see, it's a nontrivial effort.

Regarding your suggestion of using tarballs, this is something that only works for certain hosting providers, and isn't a generic enough feature to justify that significant additional complexity it would require.

Overall, having git installed is one of the relatively few prerequisites necessary for using npm (also needed: Node, and Python 2.7 and a C++ toolchain if you want to include native modules), in practice, if not an ideal world. The CLI team isn't going to have time to commit to changing this for the foreseeable future, but we'd include a patch if one were sent along, assuming it handles all the use cases that npm handles today.
