### ISSUE TITLE
Callback called more than once. npm install err meanjs

### ISSUE THREAD

**Issue by goelmayank** [npm/npm#10914]
https://gist.github.com/thenaughtychild/c9246240b9567697672e

**Comment by thenaughtychild** [comment]
C:\GitHub\meanjs>npm install

> meanjs@0.4.2 postinstall C:\GitHub\meanjs
> bower install --config.interactive=false

npm WARN unmet dependency C:\GitHub\meanjs\node_modules\mongoose requires async@
'0.9.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\async,
npm WARN unmet dependency which is version 1.5.0
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\nco
nf requires async@'0.2.9' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\async,
npm WARN unmet dependency which is version 1.5.0
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\nco
nf requires optimist@'0.6.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\opt
imist,
npm WARN unmet dependency which is version 0.6.1
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\fla
tiron\node_modules\broadway requires cliff@'0.1.9' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\cli
ff,
npm WARN unmet dependency which is version 0.1.10
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\fla
tiron\node_modules\broadway requires winston@'0.8.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\win
ston,
npm WARN unmet dependency which is version 0.8.3
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\for
ever-monitor\node_modules\broadway requires cliff@'0.1.9' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\cli
ff,
npm WARN unmet dependency which is version 0.1.10
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\for
ever-monitor\node_modules\broadway requires winston@'0.8.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\forever\node_modules\win
ston,
npm WARN unmet dependency which is version 0.8.3
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\mocha\node_modules\jade
requires commander@'0.6.1' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\mocha\node_modules\comma
nder,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\mocha\node_modules\jade
requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\mocha\node_modules\mkdir
p,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\grunt-contrib-jshint\nod
e_modules\jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-jshint\node_modules
\jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-eslint\node_modules
\eslint requires object-assign@'^4.0.1' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-eslint\node_modules
\object-assign,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-mocha\node_modules\
mocha\node_modules\jade requires commander@'0.6.1' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-mocha\node_modules\
mocha\node_modules\commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-mocha\node_modules\
mocha\node_modules\jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\gulp-mocha\node_modules\
mocha\node_modules\mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\karma\node_modules\log4j
s requires async@'~0.2.0' but will load
npm WARN unmet dependency C:\GitHub\meanjs\node_modules\async,
npm WARN unmet dependency which is version 1.5.0

C:\GitHub\meanjs>grunt
Loading "concurrent.js" tasks...ERROR
>> Error: Cannot find module 'pumpify'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'cli'
Loading "eslint.js" tasks...ERROR
>> Error: Cannot find module 'estraverse'
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'engine.io'
Loading "ng-annotate.js" tasks...ERROR
>> Error: Cannot find module 'simple-fmt'
Loading "nodemon.js" tasks...ERROR
>> Error: Cannot find module 'async-each'
Loading "protractor_coverage.js" tasks...ERROR
>> Error: Cannot find module 'dargs-object'
Loading "protractor_coverage.js" tasks...ERROR
>> Error: Cannot find module 'dargs-object'
Warning: Task "concurrent:default" not found. Use --force to continue.


Aborted due to warnings.
