### ISSUE TITLE
How does npm link create symlinks in Windows without admin priveleges?

### ISSUE THREAD

**Issue by bmahsman** [npm/npm#10926]
I can use npm link in a non-elevated process and it creates symlinks. I've been using `npm link` on Windows 7. The only method for creating symlinks that I know of is `mklink`, which requires administrator privileges. I've never been able to do this through a batch script (I once tried using `runas` in a batch script, but it was too complicated and didn't quite work).

I saw that some issues are tagged as support, so I assumed I could ask this question here. If there is a better place, sorry and please met know. Thanks.

**Comment by ben-page** [comment]
npm is open source. It's easy to figure this out.
https://github.com/npm/npm/blob/master/lib/utils/link.js#L54

It turns out it's just calling the build in function to create symlinks: fs.symlink().
https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback

I couldn't find any specific information about junction point permissions. But really, I doubt junction point permissions differ from regular NTFS file permissions. i.e. If you can create a file in the folder, then you should be able to create a junction there too.

And a quick test verifies it:
```
C:\Users\bpage>mklink /j test Desktop
Junction created for test <<===>> Desktop
C:\Users\bpage>cd test
C:\Users\bpage\test>
```

And you don't need permissions for the destination to create the junction:
```
C:\Users\bpage>mklink /j test "c:\System Volume Information"
Junction created for test <<===>> c:\System Volume Information
C:\Users\bpage>cd test
Access is denied.
```

**Comment by iarna** [comment]
@bmahsman As @ben-page say's, we use `fs.symlink(from, to, 'juction')` to create junctions (not symlinks) between folders. This works between ntfs filesystems, but does not work with remote filesystems (virtualbox shared folders). It also only works for folders (not for files).

I recently did some testing to show the full bounds of links on windows here:

https://github.com/iarna/win-symlink-test#readme

If you have further questions, feel free in this vein, feel free to hit me on [twitter](https://twitter.com/ReBeccaOrg) or IRC (I'm iarna, in the #npm channel).
