### ISSUE TITLE
doc: no --userconfig commandline option documented

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/npm#10970]
from https://github.com/npm/docs/issues/404 cc/@spikegrobstein @KenanY @othiym23 

my understanding is this is documented in `npm-config` but we should make it clearer. perhaps add a list of the 5-6 most commonly used.

i know that the question of doucmenting the config options is an on-going issue. this is an issue to remind us that in October we said we'd be dealing with it and we haven't yet.

**Comment by othiym23** [comment]
I think it would be useful to add the most commonly used options for each command to the manpage (even cooler would be to add analytics to the CLI so we know what the most commonly used options are!). Even were we to do that, though, I'm pretty sure the `--userconfig` option isn't one of the 10 most frequently used options for any npm command, and it is indeed documented in `doc/misc/npm-config.md`. So that seems like the right place for it to be. Thanks for sheepdogging this through to this repo, Ashley!

**Comment by spikegrobstein** [comment]
so you won't document this option online, where google takes me when I search and which has nice, pretty formatted documentation because it's not popular enough?

am I understanding this correctly?
