### ISSUE TITLE
npm v3: Non-deterministic dependency tree - avoid by appending version number to folder name

### ISSUE THREAD

**Issue by SetTrend** [npm/npm#11004]
The current situation of non-deterministic folder structure in NPM v3 isn't satisfying. Depending on the installation order, deep nested directory structures may still occur.

I suggest to append the version to the package name, then all packages may be installed into the same directory:

```
$ tree -d node_modules/
node_modules/
|-- mod-a@1.0.0
|-- mod-b@1.0.0
|-- mod-b@2.0.0
|-- mod-c@1.0.0
```
from
```
$ npm install
|-- mod-a@1.0.0
| |-- mod-b@1.0.0
|-- mod-c@1.0.0
| |-- mod-b@2.0.0
```

**Comment by othiym23** [comment]
Because of the need of npm to work with the [Node module loader](https://nodejs.org/api/modules.html#modules_all_together), which controls how packages are resolved, this is a feature that, while periodically requested, isn't possible within the context of the Node and npm ecosystem. Thanks for your time!
