### ISSUE TITLE
Is there a way to redirect package dependency?

### ISSUE THREAD

**Issue by strrchr** [npm/npm#11013]
For example, pouchdb@5.1.0 dependends on leveldown@1.4.2.
When I npm install pouchdb@5.1.0, it will also install leveldown@1.4.2 from npm.
But I want redirect it to leveldown@1.4.3 without modify pouchdb's source code.
So I think it would be nice if there is a way to pass a config file to npm command line to redirect package dependencies.
For example:
```npm install pouchdb@5.1.0 --custom=custom.json```
In custom.json:
```
{
  "redirections": [
    ["leveldown", "1.4.2", "1.4.3"],
  ]
}
```
It means that if a package depends on leveldown 1.4.2, it will be redirect to 1.4.3.

**Comment by othiym23** [comment]
There isn't a direct way to do this in npm, but if you're comfortable working with the `npm-shrinkwrap.json` files produced by `npm shrinkwrap`, you can explicitly set the versions of packages for your own use. (Also, it might be worth lobbying the `pouchdb` maintainers to use looser semver ranges rather than pinning all their own dependencies.) Good luck, and thanks for your time!
