### ISSUE TITLE
Add Code of Conduct option to npm init

### ISSUE THREAD

**Issue by lewiscowper** [npm/npm#11048]
In a similar vein to bundler/bundler#3305, I'd like there to be a way of adding a Code of Conduct to `npm init`. I think npm could help raise awareness of the existence of codes of conduct in software, in a similar way to bundler, but for the JavaScript world.

Ideally I'd see this working as a question during `npm init`, something like:

```
code of conduct: (filename/url/generate/no)
```

I foresee either a filename of a pre-existing CoC, a url to another CoC, generating a default (I'd suggest http://contributor-covenant.org/), or not adding a CoC (the default option).

Although generating a default isn't something npm does already, so that might be more of a stretch goal. Maybe having a set of known names, combined with some kind of SPDX style CoC validity checking. I'm not sure, but yeah.

However, important points were raised in the above thread, starting with https://github.com/bundler/bundler/pull/3305#issuecomment-67024669, about the implications of adding a code of conduct that may or may not be enforced by the project maintainer being as bad as not having one at all. For that reason, I believe that the default should be no, and `npm init --yes` should not add a Code of Conduct to a project where one is unlikely to be enforced.

Finally, I think that there should be something akin to a first-run experience, as seen here: https://github.com/bundler/bundler/blob/e2b14375c3ed2ef679fed1ca894dd346cbcefcf1/lib/bundler/cli/gem.rb#L99-L106

```
Do you want to include a code of conduct in gems you generate?
Codes of conduct can increase contributions to your project by contributors who
prefer collaborative, safe spaces. You can read more about the code of conduct at
contributor-covenant.org. Having a code of conduct means agreeing to the responsibility
of enforcing it, so be sure that you are prepared to do that. Be sure that your email
address is specified as a contact in the generated code of conduct so that people know
who to contact in case of a violation. For suggestions about
how to enforce codes of conduct, see http://bit.ly/coc-enforcement.
```

Although we don't do this for the license field (unlike bundler/bundler, who prompt here https://github.com/bundler/bundler/blob/e2b14375c3ed2ef679fed1ca894dd346cbcefcf1/lib/bundler/cli/gem.rb#L90-L93), so there's not precedence to prompt the user to *really* confirm their choices in `npm init`.

I hope this at least allows discussion, even if the feature isn't added in the end.

**Comment by MechMK1** [comment]
I like the idea of that!

**Comment by othiym23** [comment]
For every person who thinks `npm init` would benefit from another value prompt, there seems to be at least 2 or 3 people who think the current `npm init` interview script is overly involved. At the very least, this implies that any new interview question added to `npm init` should apply to all (or at least the vast majority) of npm's users. I'm not convinced that the scope of the typical npm package is such that it makes sense to ask _everybody_ to choose (or not) a Code of Conduct at the time of a package's creation. Codes of Conduct seem more appropriate at the community or ecosystem level.

Also, while they superficially resemble licenses, they have very important differences (most notably, licenses have direct legal implications for people who are interested in using a package, which is a huge part of why licenses get special attention in `package.json`).

On a more mechanical level, there isn't currently a way to denote the Code of Conduct in the `package.json`, which is something that should probably come first, and be around for a while, before integrating it more deeply within the rest of the tool.

I'm conflicted, because I think Codes of Conduct are valuable, and I think encouraging communities to adopt them as early as makes sense is beneficial for a community and its participants, but I'm not convinced that this is the right way to encourage them. As it stands, I'm -1 on making a change like this, but I'm interested in what others think.

**Comment by othiym23** [comment]
The consensus of the CLI team is that it's easy to add new configuration to `package.json` for individual projects to try this out and see how it feels; without having done that first adding it to `npm init` is premature. If people try this in their own projects and it starts to get adoption, we can come back and take another look at.

We're agreed that Codes of Conduct are important, and we encourage people to adopt them when possible. Thank you for writing this up, Lewis!
