### ISSUE TITLE
Update dependencies to avoid deprecation messages for util._extend

### ISSUE THREAD

**Issue by rmg** [npm/npm#11104]
The undocumented (but widely used anyway) `util._extend` from node core is being deprecated in nodejs/node#4593.

Most (all?) of npm's dependencies that make use of it have issues and/or PRs to avoid the impending deprecation warnings, so I'm opening this to make sure those deps get updated when they have releases available to pull in.

See also:
* nodejs/node-gyp#858
* request/request#1997
* isaacs/node-glob#240

**Comment by othiym23** [comment]
Since the npm release manager update outdated dependencies as part of npm's regular [release process](https://github.com/npm/npm/wiki/Release-Process#tuesday-preparing-the-release), and as this issue isn't directly actionable, I'm going to close it. If you need any help poking, say, `node-gyp` to get the update landed, let me know and I'll see what I can do. Thanks for the heads up!

**Comment by rmg** [comment]
@othiym23 sounds good :+1:
