### ISSUE TITLE
perform basic test before installing / replacing / updating npm itself

### ISSUE THREAD

**Issue by jokeyrhyme** [npm/npm#11110]
I've seen `npm` itself break during an install or update, and I wonder if it would be a good idea to perform basic tests on the incoming version of npm during any operation that replaces the existing copy.

It isn't feasible to test every CLI package when it is installed by default, however `npm` is a special case: it's incredibly important that it always work; and we know what it's behaviour should be when called.

What if we ran `npm version` or maybe even just `npm` against the temporary copy of an incoming version of npm? If we don't get the expected output, then we consider the copy corrupt and error out. If the test passes, then we continue with whatever operation we were doing.

Something like this might be a way to tackle the following sorts of support issues:

- https://github.com/npm/npm/issues/10727
- https://github.com/npm/npm/issues/11107
- https://github.com/npm/npm/issues/11088

**Comment by othiym23** [comment]
This is a good idea, and it would be interesting to come up with a short list of smoke tests when using npm to install itself. That said, this isn't something that the CLI team is going to have time to get to this year, so I'm going to close this feature request. If you want to write a patch that includes a version of this, the team can work with you (or whomever comes along) to get it into shape to land, but I'd suggest submitting that patch fairly early on (before writing tests), because this is something where there are likely to be lots of lurking footguns and strongly-held opinions we can help you avoid. Thanks for your time!
