### ISSUE TITLE
Alow package.json "engines" to support LTS

### ISSUE THREAD

**Issue by SteveALee** [npm/npm#11113]
Its seems useful to be able to specify you want the latest in a LTS version when the highest version is not specifically known.

1) You don't know what the latest LTS version is so following format could work
{ "engines" : { "node" : ">=4.2LTS" } }

2) Would be useful to get an alert when a later LTS version is available Eg later version with same even major. This would require an online check of latest versions though.

I think this is safe as long as new LTS releases do not break anything (minor version change only)

**Comment by othiym23** [comment]
As the LTS concept is one that's controlled by the Node.js LTS Working Group, which is a separate team from the npm CLI, this is likely to be tricky to get into npm. The CLI team isn't going to have time to get to this in the near-to-medium term, so I'm going to close this feature request.

If you want to see this functionality land, if somebody wanted to put together a patch to support this, we'd be happy to merge it. The first thing to do would be to get the Node.js project to expose an HTTP endpoint that points to the supported LTS release series (probably by code name, as `4.2LTS` does not make sense as semver _or_ a dist-tag) so that tools like npm could query it. The next step would be to come up with a way to query that from npm such that you can say `{ "engines": { "node": "argon" } }`.

Good luck, and thanks for your time!

**Comment by SteveALee** [comment]
@othiym23 Thanks for your response. I guessed it would be complicated but still worth a "suggestion"

**Comment by binoculars** [comment]
nvm uses https://nodejs.org/dist/index.tab

https://github.com/creationix/nvm/blob/master/nvm.sh#L958
