### ISSUE TITLE
`npm outdated` doesn't work with custom registry

### ISSUE THREAD

**Issue by antpaw** [npm/npm#11122]
I can use `npm install` without any problems, but not `npm outdated`, is this a npm or gemfury issue?

    // .npmrc
    registry=https://npm.fury.io/fjaAoan59AFo/me/

    // bash
    antpaw:web antpaw$ npm outdated
    npm ERR! Darwin 15.2.0
    npm ERR! argv "/Users/antpaw/.nvm/versions/node/v4.2.2/bin/node" "/Users/antpaw/.nvm/versions/node/v4.2.2/bin/npm" "outdated"
    npm ERR! node v4.2.2
    npm ERR! npm  v3.5.0
    npm ERR! code E404

    npm ERR! 404 Registry returned 404 for GET on https://npm.fury.io/fjaAoan59AFo/me/grunt-curl
    npm ERR! 404 
    npm ERR! 404  'fjaAoan59AFo' is not in the npm registry.
    npm ERR! 404 Your package name is not valid, because 
    npm ERR! 404  1. name can no longer contain capital letters
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/antpaw/Projects/tickaroo/web/npm-debug.log

**Comment by othiym23** [comment]
It looks like GemFury is confused by the URL paths that the `outdated` command uses, or perhaps you don't have the right path set up for it (can you install using that registry URL?). Either way, you should ask them for help with this, as this isn't something that's changed in the CLI for a while, and it's working as designed. Thanks for your time, and good luck getting this sorted out!

**Comment by antpaw** [comment]
Thanks it turns out i had to use the proxy api 
`registry=https://npm-proxy.fury.io/AUTH_TOKEN/USER_NAME/`

It seams pretty crazy to me that npm can only use one registry per project. Is that true?

**Comment by othiym23** [comment]
It's sorta kinda true, mostly due to how npm developed over time. Take a look at [scopes](https://docs.npmjs.com/misc/scope) for how to pull packages from multiple registries in a single project (which also requires you to use per-project `.npmrc` files and to be [logged in to multiple scopes](https://docs.npmjs.com/misc/scope#associating-a-scope-with-a-registry)). You can also use tarball URLs, but then you have to give up on semver, and auth / privacy gets tricky. To answer the unspoken question, fixing this in a backwards-compatible way is an extremely dicey proposition, and mostly the community has worked around it by making private registries into caching proxies.
