### ISSUE TITLE
npm Error when run git push origin

### ISSUE THREAD

**Issue by entingwu** [npm/npm#11163]
<img width="803" alt="2gitpushorigin" src="https://cloud.githubusercontent.com/assets/9926385/12363976/c650d78e-bb80-11e5-87bd-b923e0eade9d.png">
<img width="1106" alt="3errorwarning" src="https://cloud.githubusercontent.com/assets/9926385/12363982/cc7bf044-bb80-11e5-9cc9-0cfb879f2094.png">

**Comment by entingwu** [comment]
I finished the installation steps and try to update the changes using "git push origin", "git push entingweb". 
It seems that my file can be uploaded to the github and the changes can be shown on github.
However, when I try to upload changes to openshift, there are some error messages shown in terminal, such as 
" remote: npm ERR! addLocal Could not install ssh://56985cd90c1e66eaeb00015c@cs5610spring2016-entingwu.rhcloud.com/~/git/cs5610spring2016.git/". 
​
Then I run "node server.js" on the terminal, and go to the overshift website, I find out that the changes have been updated. 
So I wonder whether these error message would affect running project or not?

**Comment by othiym23** [comment]
In the `package.json` where you're depending on that (very log) ssh git URL, you need to prepend a `git+` to it so that npm knows that it's a git repository. The install of the dependency is failing because it's unable to figure out what kind of thing that string is, and is defaulting to treating it like a local filesystem path, which it's not finding. If you clean that up, the install should proceed without issue.

Also, FWIW, that may be the version of npm bundled with OpenShift, but `npm@1.4.28` is outdated and unsupported. You might want to configure the OpenShift bootstrap process to run `npm -g install npm@latest` as part of setting up its environment.

Closing as resolved.
