### ISSUE TITLE
Insufficient information in case of an EBADF

### ISSUE THREAD

**Issue by 0xR** [npm/npm#11172]
I get an EBADF when I'm trying to install certain npm packages on an encfs mount. It could be that the filename is too long or something, but I'm not sure which file is causing the error since NPM won't tell me. Installating on a normal FS won't cause the issue, but that defeats the purpose of encryption.

I'm running npm 3.5.3
These are the errors in npm-debug.log:

```
96083 warn optional Skipping failed optional dependency /chokidar/fsevents:
96084 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.6
96085 verbose stack Error: EBADF: bad file descriptor, close
96085 verbose stack     at Error (native)
96086 verbose cwd /home/user/workspaces/angular-universal
96087 error Linux 4.3.3-2-ARCH
96088 error argv "/usr/bin/node" "/usr/bin/npm" "i"
96089 error node v5.4.0
96090 error npm  v3.5.3
96091 error code EBADF
96092 error errno -9
96093 error syscall close
96094 error EBADF: bad file descriptor, close
96095 error If you need help, you may report this error at:
96095 error     <https://github.com/npm/npm/issues>
96096 verbose exit [ -9, true ]

```

Expected behavior: Print the file that has caused the `EBADF`

**Comment by othiym23** [comment]
This is indeed frustrating, but without having a better idea of what's going on with the filesystem, it's hard to say how tough this error would be to fix, because it could be coming from any one of a number of code paths touching the filesystem, and without explicitly handling `EBADF`, there's not a generic way for us as maintainers to annotate fs errors with more context. Would you be interested in trying to patch this yourself? Barring that, a repro case would be extremely helpful, when somebody does have the cycles to take a look at this.

**Comment by pauloppenheim** [comment]
+1 - it doesn't happen on smaller installs (typescript, socketio, not much else), only larger (react / react native / babel / etc) and also with encfs.
