### ISSUE TITLE
npm shrinkwrap --production

### ISSUE THREAD

**Issue by natew** [npm/npm#11189]
I have a module that has devDependencies. When i `npm shrinkwrap` it fails with extraneous errors.

It seems for now my only option is to manually remove the devDependencies fields and modules before releasing, and then add them back in after.

I searched around a bit and see some related tickets, but nothing suggesting this. I would think the `npm shrinkwrap` would ignore devDependencies by default, and write out shrinkwrap with just the regular ones. But at least having a `--production` option would let us build the shrinkwrap without the devDeps included.

**Comment by cchamberlain** [comment]
@natew: This set of scripts is working pretty well for me using @iarna in-publish module as a prod dependency:

```json
    "release-patch": "npm version patch && npm publish",
    "postversion": "npm rm history",
    "prepublish": "in-publish && npm dedupe && npm prune --production=false && npm shrinkwrap || not-in-publish",
    "postpublish": "rimraf npm-shrinkwrap.json && git push --follow-tags",
```

Only issues I've had lately with extraneous was the history module (https://github.com/react-bootstrap/react-bootstrap/issues/1395) and when I was attempting to shrinkwrap one of my libraries and then shrinkwrap that into my app which is a bad idea.

If you see history as one of them try sticking an npm postversion remove step like I did.

**Comment by natew** [comment]
@cchamberlain trying to understand this, but does this just remove the shrinkwrap if it fails?

My ideal is: it shrinkwraps just the dependencies, ignores the devDependencies. I want the regular deps shinkwrapped though.

For now I've scripted around it but it's less simple than just removing it.

**Comment by cchamberlain** [comment]
@natew - I have npm-shrinkwrap.json in my .gitignore along with all my other built files but if I didn't this would ensure that it does not get committed to git.  I also exclude my src directory from what I publish to npm via package.json files node.  The only time I want the npm-shrinkwrap.json is when I'm actually publishing, and after that I discard it since its been published to npm with the package version.  Having shrinkwrap sitting around in the package while you're developing gets very annoying since it messes up npm installs.

I'm following @iarna's guide here -> https://re-becca.org/2015/01/publish-only-shrinkwrap/

**Comment by natew** [comment]
I too have it in gitignore. The guide is nice but that doesn't solve my problem.

Basically have this package.json:

```
{ "devDependencies": { "reapp-ui": "1.0.0" } }
```

`npm install`

Now you run `npm shrinkwrap` you get an error "extraneous". So what can you do to avoid having to wipe out node_modules and reinstall every time you shrinkwrap?

**Comment by cchamberlain** [comment]
@natew Do you use `npm prune --production=false`?

That is meant to wipe out all extraneous dependencies, using explicit false ensures it will keep the dev dependencies even if NODE_ENV is production in your environment.  It will not remove optional dependencies so you'd have to remove those with a custom build step.  Not sure if you've been using this already.

**Comment by shinout** [comment]
```sh
npm prune --production
npm shrinkwrap
```
This satisfies the requirement to omit all dev-dependent modules in `npm-shrinkwrap.json`.

**Comment by natew** [comment]
Haven't seen this ticket so not sure if this solves it! But if I remember
that snippet would then require you re-install dev deps after every time
you publish right?

**Comment by cchamberlain** [comment]
`npm prune --production` would require you to reinstall all dev dependencies again, yes. Don't like this solution since the build time gets blown up.

Would be nice if there was something like `npm archive --production --shrinkwrap <path/to/archive>` that would do all of this and export the result to a separate directory and leave the build directory intact.

**Comment by shinout** [comment]
On npm v2,

- `npm shrinkwrap` omits dev-dependent modules
-  wrongly omits dev-dependent modules which are sub-dependent

On npm v3,
- `npm shrinkwrap` includes some (not all) of dev-dependent modules
- after `npm prune --production`, it's ok

Currenlty, the following process is the only way to get the correct result on npm >=v2.

```sh
rm -rf node_modules
npm install --production
npm shrinkwrap
```

I hope this would be fixed.

**Comment by vincentwoo** [comment]
I believe shrinkwrap with devDependencies on npm 3 is broken. Right now it tries to do things like:

`npm WARN shrinkwrap Excluding devDependency: yargs@4.7.1 { bugsnag: '*',`

But this check is very naive. It does not check if packages were pulled in by devDependencies, and so there are many extraneous entries in the shrinkwrap.
