### ISSUE TITLE
Unaught exception: TypeError: Object #<Object> has no method '_extend'

### ISSUE THREAD

**Issue by ghost** [npm/npm#11206]
This appears to only happen if Node.js version 5.4.1 is running. If I tell the server to use 5.4.0 this does not happen... and on that note, unsure if this issue should be posted here or elsewhere.

The rest:

Unaught exception: TypeError: Object #<Object> has no method '_extend'
Application:     at new Request (D:\home\site\wwwroot\node_modules\request\request.js:126:8)
Application:     at request (D:\home\site\wwwroot\node_modules\request\index.js:55:10)

**Comment by othiym23** [comment]
I know there are plans to deprecate `util._extend` in Node core, which would break some of npm's dependencies. I didn't think it had taken effect yet, though. @rmg, you were the last person to be in my field of view talking about this – do you have any insight here? (Also, this is why hard-deprecating stuff in Node.js core is both hard and makes me sigh.)

**Comment by othiym23** [comment]
@Yelnik, what version of npm are you seeing this with?

**Comment by Yelnik** [comment]
The app is running on Azure when it does that, so is there a way I can console.out the NPM version while my app is running?

Otherwise, on my local machine NPM is 3.3.12, but I don't believe this issue comes up on my local machine actually.

**Comment by Yelnik** [comment]
Come to think of it this could be an issue of Azure updating Node.js to 5.4.1 but not updating NPM as well.

**Comment by rmg** [comment]
@othiym23 the PR you're referring to (nodejs/node#4593) is still open and only does a soft deprecation (if I understand what you mean by hard deprecation).

This would happen if a customized version of the `util` module was pulled in as a dependency. Also, since npm 3 flattens the deps, if some other code was doing something inappropriate to the object returned by `require('util')` the effects would be "global" in that they would affect all uses of that module.
