### ISSUE TITLE
Rational using of disk space. Smart NPM

### ISSUE THREAD

**Issue by nervgh** [npm/npm#11210]
I use NPM more than 2 years. It's really great, thanks!

But I have many projects where I use npm for package management. These projects have many identical dependencies. As result I store all these identical dependencies in my local `node_modules` folders. They occupy many disk space.

For example, one of my `node_modules` folder occupy ~100mb.
If I have 30 projects with same dependencies they require 30*100 Mb disk space.

I think NPM could be more smart.
Currently NPM use versioned cache. I mean the 
```
~/.npm
```
folder. I think we could be use same behaviour. We could be store all our installed dependencies in single place and create symbolic links in projects.

May be the feature already implemented. Please, tell me how that works?

**Comment by othiym23** [comment]
A couple thoughts on that:

1. This is one of the main benefits of `npm@3`, since it flattens and deduplicates the install tree by default. This was mostly done to make npm work better on Windows and with front-end dependencies, but it also has the side effect of shrinking the disk space used by large installs significantly. If you're not already using `npm@3`, give it a shot! (You'll need to remove and reinstall `node_modules` on a project to take advantage of the flattening & deduping.)
2. Symlinking local installs into the cache is not a good general-purpose strategy, in part because of limitations with symlinks in many situations (e.g. Windows, Docker, Vagrant), as well as a number of tricky aspects of making that work with the Node module resolution algorithm. For this and other reasons, we're unlikely to change this aspect of the CLI's design.
3. We are thinking about other ways to make the installer more efficient, including things like making the installer be smarter about which version of a commonly-depended-upon package to pull higher up in the install tree during deduplication, so that we're using a minimum amount of space per install.

Since this isn't a directly actionable feature request or bug, I'm going to close to this issue. Thanks for your thoughts, though, and thank you for your time!
