### ISSUE TITLE
option to exclude transitive dependencies

### ISSUE THREAD

**Issue by chrylis** [npm/npm#11254]
I am working with a couple of packages [(`karma-phantomjs-launcher` being the most notorious)](http://stackoverflow.com/questions/31616837/exclude-npm-module-dependency) that hard-code inaccurate or undesirable dependencies. In a system such as Maven, I can easily specify that a transitive dependency pulled in by a direct dependency should be ignored, and this feature would be immensely helpful to have in NPM.

**Comment by zkat** [comment]
Hey! Thanks for filing this issue!

The CLI team talked it over for a bit, and we concluded that the best way to think about issues like this is to treat that bad dependency just like any other bug -- and solve it the same way. You have more than one possibility here, including manually writing scripts (and using npm scripts or git hooks) to modify packages. Our recommended approach, though, is to simply fix the problem in a fork and submit a PR to the offending repository, as well as any dependents that need that version updated -- and in the meantime, you can manually maintain those forks yourself.

Yes, it's a quite bit more trouble than having some kind of npm-specific mechanism for injecting or replacing dependencies or code, but we believe this pays off in the long run by preventing users from breaking their own builds, which npm is designed to avoid, or having to maintain increasingly complicated forks at the package level, instead of solving the core issue, which is simply a bug in the package in question.

**Comment by solmetricchris** [comment]
There is solving the problem, and there is warning about the problem.  

It would be great if there was a clear warning from NPM that a possible transitive dependency version collision has occurred.

**Comment by jingxue** [comment]
The ability to exclude transitive dependencies can be more useful than fixing some package dependencies. For example, I'm working on an AWS Lambda package which uses amazon-cognito-identity-js, which has aws-sdk as a dependency. OTOH aws-sdk is automatically provided for every Lambda package already. So it is a legitimate use case for me to exclude the aws-sdk delcared by amazon-cognito-identity-js.
