### ISSUE TITLE
setup and clean code for tap tests

### ISSUE THREAD

**Issue by gagern** [npm/npm#11269]
Currently, quite a number of test files contain special tests called `setup` or `clean` which apparently prepare the setup environment and tear it down again. I consider this bad style because

* it prevents running single tests without the matching setup and/or clean steps
* it prevents running tests in a different order, e.g. most-recently-failed tests first
* it reports multiple failures even if there was only a single problem with setup
* it can be quite confusing to contributors who are used to a different style

Mocha would nicely allow modeling this approach you have here using its `suiteSetup` and `suiteTeardown` hooks. I haven't seen something like that in Tap. In most cases you could do the setup and teardown once per test case, hopefully without causing too much extra overhead.

**Comment by substack** [comment]
Most of the tests are in their own files, so to run a test individually you can simply `node test/tap/whatever.js` and it will run the tests for a single feature. This is nice because you don't need a special runner that injects globals like mocha. Using `test()` for setup and teardown also has nice economy of features and is basically exactly the same as having custom built-in methods, but this is a different approach from many other test harnesses.

**Comment by othiym23** [comment]
There is less than no chance the npm test suite will be ported away from tap, as the test suite is the single largest sunk cost in the entire npm code base. In addition, npm and `node-tap` have grown together, and there's a bunch of stuff it's easy to do with tap that would be much harder with mocha. Also, as @substack indicates, the idiom npm uses was consciously chosen, and is pretty flexible at handling the many different kinds of tests in `test/tap`.

I'd love to get rid of the global setup and tear down test files, but they mostly just help ensure idempotent test runs in a way that it's difficult for individual tests to do. Also, folding the legacy, non-tap tests into the tap directory is also on the agenda.

Thanks for the thoughtful proposal and your time!
