### ISSUE TITLE
Change node_modules folder name to something shorter

### ISSUE THREAD

**Issue by Frondor** [npm/npm#11261]
Sometimes when using a lot of dependencies on our projects, 
There's a known problem on windows about deleting `node_modules` folder because of the insane deepness that some paths become, for example: `C:\Users\PC\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback\node_modules\nodemailer\node_modules\mailcomposer\node_modules\buildmail\node_modules\addressparser` (this is a "short" one, though).

I suggest renaming `node_modules` to something like: `nm`, `n_m`, `nmods`.

**Comment by KenanY** [comment]
@Frondor You would need to ask Node.js to change the module loader to recognize the new folder name. Module system is locked though so stuff like this will be rejected for the foreseeable future. Are you still using `npm@2`? `npm@3` should be doing a better job at preventing such "deepness".

**Comment by Frondor** [comment]
Ok.
I'm using npm@3.5.0 and it's a complete mess regarding to this issue.

**Comment by felixfbecker** [comment]
@Frondor try `npm dedupe`. You should end up with a flatter structure.

**Comment by caseyhoward** [comment]
I don't think this is a good idea. This would break everyone's existing installs.

This also doesn't even fix the problem. It just makes it take longer to surface. You could still end up with a file path that's too long for windows. I believe the maximum length for a module name is 214 characters. If you have two nested modules that length you're already hosed.

If anything make this some sort of option. As a non-windows, I don't want to end up with an obfuscated directory name because of windows. The only real solution for this problem is for npm to support installing all modules flat.

**Comment by othiym23** [comment]
@Frondor, if you delete your `node_modules` and reinstall your project from scratch with `npm@3`, the new install will use `npm@3`'s maximally flat install algorithm, which will remove as much of the nesting from the install as can be done without causing conflicts between the semver ranges of the package's dependencies. This is one of the major changes in `npm@3`, and it was specifically intended to address this particular pain point of using npm on Windows.

As for the rest, the spelling of the `node_modules` directory isn't npm's to change: it's baked into the Node [module loader specification](https://nodejs.org/api/modules.html), and is also hardcoded into probably thousands of existing packages. This is requested frequently enough that the old, deprecated FAQ had several questions devoted to this, but the upshot is that `node_modules` is one of the few truly unchangeable things about npm. As a result, I'm going to close this issue, and hope that this explanation is enough to make clear why. Thanks for your time!
