### ISSUE TITLE
discuss npm install behaviour: do not install locally if available globally

### ISSUE THREAD

**Issue by fibo** [npm/npm#11274]
I would like to discuss here this feature.

If approved, I could try to implement it, it does not look so complex.

If I do `npm install` and a package, for instance *standard*, is in my devDependencies, but it is available globally, it would be nice if npm skips the local installation (which takes time) since the *standard* package is already available globally.

This could be governed by a flag, something like `npm install --skip-packages-available-globally` which is too verbose by now, just to have an idea.

**Comment by zkat** [comment]
For the case of libraries -- node does not have a global search path. For the case of a command line tool like this, there may be a use case, but it seems too narrow to really save any time on the larger scale, since even some of those prefer to be installed locally per project.

The use-case is even narrower when you take into account semver compatibility -- you might end up with a subset of subset of projects that are actually able to use this, and the optimization from having npm@3's flattening already does a ton to easy this (along with our local caching).

All-in-all, I can see the intent of this feature and really appreciate it, but it's very likely not something that would make it into the CLI as far as my understanding of it goes. Thanks for taking the time to write up the feature, as that is already appreciated <3
