### ISSUE TITLE
Proposal: { "scripts": "moduleA" }

### ISSUE THREAD

**Issue by donaldpipowitch** [npm/npm#11284]
It is quite common in the Node community to use `$ npm run` for build scripts and other scripts like tests. See [here](http://substack.net/task_automation_with_npm_run) for an older example and [here](https://medium.com/@housecor/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8) for a newer example. In my opinion this is generally a good thing as you have fewer dependencies on plugin authors for task runners like Grunt or Gulp as they aren't often _that_ necessary and add complexity. There _are_ some pitfalls you still need to keep in mind like _"Don't use comments in JSON files."_ (surprisingly unexpected for many people) or _"Don't use `$ rm -rf`, but the `rimraf` module for cross-platform compability."_ What is _really_ great about `$ npm run` is that you can use common commands like `$ npm run start` (or `$ npm start`) across projects without learning new commands like `$ grunt` or `$ gulp` and without installing additional modules like `grunt-cli` or `gulp-cli`.

But `$ npm run` can also be very limiting. Look at [this `package.json`](https://github.com/AngularClass/angular2-webpack-starter/blob/master/package.json#L8). It is not uncommon to have so many commands/scripts. We certainly have them. But we also have many projects which all use the same scripts and configurations. So how do we share and version the `scripts` field in our `package.json`? It is not really possible. If we just change one tool, we need to update all `package.json`s manually. We have more constraints. We have many people who are happy command line users and use our tools, but aren't JavaScript developers. We want to offer them a nice experience on the command line without the need to look in our JavaScript source code. Grunt allows us to list all commands with descriptions via `$ grunt -h`. Can we do the same with `$ npm run -h`? Sadly, no.

So what do we do? We don't use Grunt (at least not anymore), we don't use Gulp, we don't use `$ npm run`. We have a small module which acts as a nice little facade to other Node modules we need for our tooling like Babel, JSCS, Karma and so on. This facade is just a small commander.js application which offers a nice and coherent command line interface for a multitude of different Node modules - each offering other interfaces. Our developers learn our interface with generic command like `start`, `test`, `serve` and so on and we as JavaScript developers swap out the underlying modules as needed. (Like switching for JSHint to ESLint or something like, but keep a single `lint` command.)
This approach has two caveats. We want a uniform way to call this module, so we have another module for calling our facade (just like `grunt-cli` or `gulp-cli`). The other problem is that we loose common and known commands like `$ npm start` (at least, if we don't alias it in our `package.json` which could be a problem if we have many projects and many commands).

So here is my proposal to solve these problems:

Instead of adding an object to `scripts`, you can add a string which acts just like `require('myModule')`. E.g.:

```
{
  "scripts": "myModule"
}
```
```
{
  "scripts": "./scripts/custom.js"
}
```
If you reference a JS file like this every command and param from `$ npm run` will be passed to this script. That way we can easily share and version complex configuration, but can still use already known commands like `$ npm start` or `$ npm test` - at least if they are handled by the referenced modules. A `$ npm run -h` would print the help the referenced module offers. That way you can use Node modules directly (instead of using Grunt or Gulp), but you can wrap them in a small commander.js interface or something similar to offer a nice interface with printable help.

**Comment by Jameskmonger** [comment]
:+1:

**Comment by iarna** [comment]
I'm hearing several different pain points that you're hoping this will address:

First, that writing cross-platform npm lifecycle scripts is difficult. 

Second, that lifecycle scripts often end up complicated and you would like to be able to share them between projects without copying.

Third, you would like to provide some mechanism to understand what the available scripts are and what they're for. `npm run` displays a list of course, but shows the contents of the command, and for complicated commands this isn't very helpful.

And finally, because you replace `npm run` with a stand alone command, it means that you can't use `npm start`/`npm run` where there's an overlap between npm's core functionality and your stand alone command's.

This feature request, as written, would be a breaking change because existing versions of `npm` would explode if they saw a `scripts` property that wasn't an object. But even with a different key name, there are some deeper issues with this solution. As I imagine you know, scripts are also used internally by npm to manage the publication and installation of modules. We believe a feature like this has the potential to cause problems with that workflow for users. The CLI team don't think this is the right direction for this kind of platform integration to go, and so we're not going to land these kinds of changes.

The above issues are still valid and worth addressing, but it would involve multiple, and more granular feature requests/PRs. We're closing this for the time being, but having those fine-grained changes would still be something we're more open to addressing.

For your first pain point, the CLI team's solution for that is to evaluate the command lines in scripts in npm, instead of passing that to the system shell (see #11291 for details).

For your second and third pain points, using an external tool seems to be the best solution. npm's lifecycle scripts are intentionally simple and those are good indications that they're no longer a good match for your problem.

For your fourth pain point, you could have your command line tool add its own aliases to your `package.json`– this would allow the two to remain in sync without having to manually synchronize them. This is admittedly sounds awkward and is probably unsatisfactory. A better solution to this problem would be appreciated.

I'm going to close this because this request as described won't make it into the CLI. But we are open to other approaches to resolving the underlying issues, and so if you have suggestions along those lines we would welcome feature requests or even very early pull requests.

**Comment by donaldpipowitch** [comment]
@iarna Thank you very much for your detailed and fast answer. I understand that you don't want breaking changes (I actually forgot that npm uses the scripts internally, while writing this - sorry) and that every pain point probably deserves its own solution. If I can come up with a better solution I'll write another issue.

**Comment by iarna** [comment]
@donaldpipowitch Awesome! Looking forward to it!
