### ISSUE TITLE
Lifecycle hook for when any dependency is changed:

### ISSUE THREAD

**Issue by jamestalmage** [npm/npm#11297]
See https://github.com/jamestalmage/find-cache-dir/issues/1#issuecomment-170851452 (the whole discussion is worth reading to fully understand why we want this).

Both `nyc` and AVA now provide transform caching (`nyc` for `istanbul` transforms, AVA for Babel transforms). The difficulty, in both cases, is invalidating the cache anytime a dependency changes (Babel makes this especially difficult because it uses lots of small modules that all contribute to the transform - and there is no good way to build a salt value that takes the entire dependency graph into account).

It would be really helpful to have a lifecycle hook that ran any time a dependency changed. In the above cases, we would simply use that to delete our cache any time any dependency changed. 

I see potential for a number of hooks, each with slightly different semantics: 

 1. A hook that only runs a script in the top level package any time there is a package change. (anytime `npm install` or `npm update` makes any change to the dependency graph, execute a script from the top level `package.json`).

 2. A hook for installed (nested) packages that runs any time a dependency anywhere in it's defined dependency graph changes (i.e. any change to anything listed in `dependencies` / `optionalDependencies` / `peerDependencies` - or any of their dependencies on down the line). 

 3. A hook for installed (nested) packages that runs any time *any* dependency changes (any change anywhere in the dependency graph triggers it). This is important for situations (like Babel) where a plugin architecture is used, and it is impossible to explicitly list every dependency.

From the perspective of what we are trying to do, `3` seems ideal. However, I am guessing `1` would be a lot easier to implement. We could make `1` work, but it would be a lot less user friendly as it requires users specify a hook themselves (and we would have no way of verifying/warning them if they don't).

**Comment by sindresorhus** [comment]
I would like to see `3` happen. It's the most flexible one. I don't think `1` would be of much use for us as I don't want to require the user to do anything.

@jamestalmage Maybe you could provide a usage example on what `3` would look like?

**Comment by jamestalmage** [comment]
My thought was to simply define another script in `package.json`:

```json
{
  "scripts": {
    "dependency_changed" : "node ./clear-the-cache.js"
  }
}
```

The interface would be the same for all 3 examples above (just different script names). Now, picking a good script name... that is going to be difficult. :smile:

**Comment by othiym23** [comment]
What you're proposing is a useful feature, and it's an instance of a more general class of problem, which is coming up with a way to make available to developers the kinds of information that are a byproduct of npm's operation that would otherwise be laborious to figure out. I think the best way to implement #3, which I agree is the best (or at least most general) approach, would be to have a new lifecycle event, `changed`, that will call the script attached to that key in `"scripts"` in `package.json`. It should happen only once – after all the installs are completed, and probably after `postinstall` – and that script should be invoked with the space-delimited list of all of the relative paths to affected modules. The list should include all of the packages changed by the install, whether they're newly-installed, updated, or removed, and it should be up to the called script to determine what's happened to them. (This should be sufficient for selectively updating caches, and is an easy enough list to generate as a byproduct of the installation process, according to @iarna.)

The CLI team isn't going to have time to get to this in the next year, but I do think it would be nice functionality to have, so I'm marking this as `patch-welcome` and closing it, which is how the team is currently handling features that we don't intend to ship ourselves. The team _is_ available to help get a feature like this implemented, so if you decide to build it, open a PR as you get started and we can help you figure out what needs to be done to get it merged.

As a side note, I'm feeling dissatisfied with the design of the lifecycle. The current implementation is limits users to a single workflow, which has the advantage of simplicity, which makes it easy to teach and only slightly harder to learn. However, this results in a confusing conflation of scripts that are clearly part of the lifecycle (like "preversion" and "postinstall"), scripts that are standardized package scripts (like "test" and "start"), and arbitrary package scripts consumed by `npm run-script`. All three are valuable, but combining them is confusing and inflexible. I'm starting to think about what the replacement might look like, and am thinking about the possibility of splitting the two apart, and also coming up with a more finely-grained eventing system that would allow scripts to be called on individual phases of the install and other fine-grained discrete actions. I'm just now starting to think this through, but if people have thoughts on how they might want the lifecycle to change, we're interested in seeing them.
