### ISSUE TITLE
Recommended conflict resolution for packages that access global scope (like Angular modules)

### ISSUE THREAD

**Issue by keithajackson** [npm/npm#11294]
Hi folks,

I've been researching a conflict-resolution issue on my team's project for two days and haven't figured out a satisfactory solution to the problem I'm having; I'm hoping that you might be able to point me in the right direction of what to try next.

My team uses Angular for our front-end and NPM@3 for package management.  NPM seems like a pretty common resource in the Angular community; from large, official packages like [angular-material](https://www.npmjs.com/package/angular-material) to independent projects like [angular-password](https://www.npmjs.com/package/angular-password).  All we need to do to use these directives/features is `npm install` and `require()`, at which point the package self-registers with Angular and is ready to use.

The self-registration is causing me significant headache, in something that was noted about a year ago [on the npm blog](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging): differing versions of Angular (or Angular components) clobber each other if they are loaded as sub-dependencies of different packages, without explanation or warning.

The most recent issue I ran into with this was when my app had two widgets which depended upon incompatible versions of `angular-material`:
```
my-unassuming-angular-app@1.0.0
  \
   - reader-widget@0.1.0
   |   \
   |     - angular-material@^1.0.2
   |
   - comment-widget@0.1.0
       \
         - angular-material@^0.11.2
```
The install completed without warning, but when I started the app, both versions of `angular-material` loaded, which resulted in the CSS from `0.11` loading with the JS from `1.0` and everything looking broken.

I get the sense that 'global scope' is an NPM antipattern, but since the convention is firmly entrenched in Angular, I'm looking to develop the best conflict management strategy.  I have two goals:

1. Dedupe and flatten 'global-scope' packages like `angular`, `angular-material`, to the top level to ensure only one is in `node_modules`, ever
2. Throw some sort of user error or warning when # 1 is impossible (specifically: throw a warning or error when there is a major version difference between 2 required versions of a package)

In case of # 2, I'm fine with resolving it myself -- it's not something that NPM could automatically take care of -- but I want to be able to have a warning when it's coming up, and not have to diagnose from a "something broke" symptom.

There are two strategies I've found to addressing this:

- Don't manage global dependencies at all; just put them in the package.json.  `angular-material` takes this approach, in that it tells you in the docs that you'll have to install `angular-aria` and `angular-animate` at the same time as `angular-material` (and assumes that every version of `angular-aria` and `angular-animate` will be compatible with `angular-material`). I'm not a huge fan of this strategy because it makes the entire process manual, and if you have a project with two or more levels of dependencies from the top-level app, this gets infeasible.

- List all Angular "global" npm modules as `peerDependencies` in my modules like `reader-widget` and `comment-widget`, so that they're listed in `my-unassuming-angular-app` as required peer modules to-be-installed when I install `reader-widget` and `comment-widget`.  This is a little bit better, but it doesn't seem like it's really what `peerDependencies` is meant to do, and it quickly breaks down when sub-dependencies have peer-dependencies, at which point you have to repeatedly scan for and install peer dependencies until you can't find any more.  
Specifically, this gets tricky:  
```  
my-unassuming-app@1.0.0
\
 - (PEER) reader-widget@^0.1.0
    \
      - (PEER) angular-material@^0.11.0
      - (PEER) comment-widget@^0.1.0
          \
            - (PEER) angular-material@^1.0.2
```  
When I first clone `my-unassuming-app`, the only peer dependency I will see is `reader-widget`.  After installing `reader-widget`, then I'll have two more peer dependencies: `angular-material@^0.11.0` and `comment-widget@0.1.0`.  After I install those, I'll see that I have a conflict in `angular-material` versions.  Doing this manually will become really unmanageable very quickly, so I've been working on a bash script to help automate it...but it essentially consists of running `npm i` zeroing in on any lines that mention `peer dependency required`, and trying to install the package listed.

---------------------------------------------------------------------------------

I'm not totally happy with either of these solutions, but I haven't found any other way to manage global dependencies without gambling on (a) failing silently or (b) making an unscaleable project.  Are there any other approaches I can take to tackle this issue, or best practices I can apply to improve one of the listed solutions?

**Comment by zkat** [comment]
Hey, @keithajackson!

This is indeed something the CLI team has been thinking about how to address, since it’s a good example of the sorts of requirements present in front end packages that npm could really be better at serving.

As of right now, the main thing that’s been done in this direction is talk about [`assets/`](https://github.com/npm/npm/issues/9354) as some first-class thing within npm that would do stuff like flattening trees and making sure singletons like this are more predictable than with the usual nested structure of node modules.

This is also something that’s not really on the immediate roadmap (so, on the scale of longer than a year for this to be actively worked on by a core team member). This is a good time to be exploring needs of the various browser (and such) projects out there that might benefit from this work, so that we can write a spec and get the requirements turned into something ready to implement.

That said, there’s a lot that can be done in the meantime to explore these ideas without requiring anything in core npm (which is ideal ‘cause we’d love to see more ideas floating around in the ecosystem!). For example, you can check out @aredridel’s [`copy-browser-modules`](https://www.npmjs.com/package/copy-browser-modules), which simply runs a task after modules are installed to copy and dedupe resources.

I hope this gives you some direction for the time being. I *am* going to close this, though, since it’s a feature request that won’t be getting time allocated for the next year, and that’s just how those are being handled right now to keep the tracker under control. Please keep thinking about and looking into solutions for this, and hopefully something good will come out of it all that will make npm work *really well* for front end devs’ needs. :) Thanks a lot for taking the time to do the detailed writeup and laying out some of the various concerns that this would need to solve!

**Comment by othiym23** [comment]
You can also take a look at the [`front end`](https://github.com/npm/npm/issues?q=label%3A%22front+end%22) and [`flat dependencies`](https://github.com/npm/npm/issues?q=label%3A"flat+dependencies") issue labels, which we're working on attaching to enough issues to provide some context around how we're thinking about this problem.
