### ISSUE TITLE
Error on "npm install & bower install"

### ISSUE THREAD

**Issue by saahon** [npm/npm#11302]
After installation, the new jhipster project appeared here such error:
![Error Screen] (http://i.stack.imgur.com/uaDOz.jpg)

it is written there: "if you need help, you may report this error at:<https://github.com/npm/npm/issues>" 
and therefore I'll write here. Help me why this error occurs?

**Comment by rmilesson** [comment]
The actual error is written out right there in that log.

`Fatal error: Unable to find local grunt.`

You need to install grunt.

I would suggest you head over to jhipster and talk to them at their [issue tracker](https://github.com/jhipster/generator-jhipster)

**Comment by saahon** [comment]
I have installed grunt for windows. for each project need separately installed grunt?

**Comment by anshulguleria** [comment]
@saahon Grunt is now seperated in two parts `grunt-cli`(installed globaly) and `grunt`(installed for each project).

The global one just runs commands using the local grunt present in your project beside the `Gruntfile`. Thus you need to install grunt locally for each project also.

```js
// for global install
npm install -g grunt-cli
// for local install within each project
npm install --save-dev grunt
```
This is documented in grunt site also. For cli read [grunt-cli](http://gruntjs.com/getting-started#installing-the-cli) and for local install read [local grunt](http://gruntjs.com/getting-started#package.json)

**Comment by ashleygwilliams** [comment]
hi! @anshulguleria's advice is excellent. you are receiving this error because node cannot find `grunt`. you do not have `grunt` installed. you'll need to install the `grunt-cli` globally: `npm install -g grunt-cli`

you might want to recommend that the maintainer of the project add the `grunt-cli` to their `devDependencies`, as npm scripts can access those, ridding the users of the need to install something globally on their machine.

hope that helps! if you continue to have trouble please open a new issue.
