### ISSUE TITLE
Support an array for the package.json repository field

### ISSUE THREAD

**Issue by MoOx** [npm/npm#11315]
Since Git has been designed to be decentralized, it would be cool to support an array for the "repository" field in package.json, so we can add several git repo (eg: mirrors, especially nice when there is a github outage).

Before you ask [it's currently very easy to push to multiple repos](http://stackoverflow.com/questions/849308/pull-push-from-multiple-remote-locations/3195446#3195446)

Can this be considered?

Maybe like author and authors, add a "repositories" field?

**Comment by othiym23** [comment]
When npm has been changed to allow multiple types of values for `package.json` fields in the past, the results have almost always turned out to be a mess, and in some cases can cause otherwise perfectly functional old versions of npm to explode, making these changes riskier than they might at first appear. While in some cases it may be worth the cost, I don't believe this proposal rises to that level, so I'm going to close this out. Thanks for your time, though!

**Comment by MoOx** [comment]
Why "adding“ random values might break things? It's not like if this field is used in many place. I only see it on npmjs.com. I was guessing npmjs.com could just use this field to display all repos...

**Comment by othiym23** [comment]
@MoOx It's used by the CLI itself, for the `npm repo` and `npm bugs` (as a fallback), which means that `read-package-json` (or maybe `normalize-package-data`), which is used by the CLI for a number of things, needs to be able to read and handle the values of those fields. And, since you brought up the web site, this change would not only affect the display code on the web site, but also the middleware microservice that pulls down package metadata and transforms it into a form the web site can use. Like I said, there are cases where that level of change is justified, but I don't think this is one of them.

**Comment by MoOx** [comment]
Wow. Ok. Thanks for this very precise explanation 👌🏼.
