### ISSUE TITLE
Install a tarball from a private repository release

### ISSUE THREAD

**Issue by ManuelRauber** [npm/npm#11382]
Hi!

Normally you can use `npm install https://github.com/myorg/repo/releases/download/v0.0.1/release.tar.gz` to install a package from a released tarball from your repository.

But if your repo is private, npm fails with 404, since it can not find the tarball, because you need to be logged in to get the repo.

I tried using HTTP basic auth via `https://myuser:mypassword@github.com....` as well as API token via `https://mytoken:x-oauth-basic@github.com....` without success.

This issue is somewhat similar to #2183, but using the repo itself is not possible in my case. I just want to have the download of the tarball from a private repo. Is there any possibility doing this?

Thanks!

**Comment by othiym23** [comment]
To access a GitHub private repository via HTTPS, GitHub requires your session information to verify that you have the right to see the repository in question. Since that session information isn't available to npm, and there isn't any way for npm to log into GitHub itself (and because npm doesn't know this is anything other than an ordinary tarball served via HTTPS because you're not using the repository), there's no way to do this, no. As such, I'm going to close this issue, but I am curious: is there no other way for you to get at this release? Why can't you just depend on `"myorg/repo#v0.0.1"`?

**Comment by weirdan** [comment]
>  I am curious: is there no other way for you to get at this release? Why can't you just depend on "myorg/repo#v0.0.1"?
Possible motivation might be that someone doesn't want to check build artifacts (such as `.js` files, when you're working on a project using some transpiled language) into the source repository.

**Comment by simlu** [comment]
Did you ever resolve this? We're struggling with the exact same issue...
