### ISSUE TITLE
Documentation when copying executables to .bin directory is done

### ISSUE THREAD

**Issue by elhigu** [npm/npm#11395]
I ran into problem, when running `npm install` for package which has 

```
{ 
  "bin" : { 
    "name": "/path/to/code/generated/in/prepublish/cli.js" 
  } 
}
```

Looks like binary is tried to be copied, before prepublish is ran. Is this intentional or am I doing something wrong?

**Comment by jordwalke** [comment]
I was also very unclear about when the `.bin` links are setup. In my case, the binaries needed to be generated as part of the postinstall process, and so the `.bin` links would fail because the destinations were not produced yet. I would recommend having the symlinks point to broken destinations, if they must be set up before the `postinstall` hooks etc. Then if you want to perform validation on them, do it after the entire install process. Would the temporarily broken links solution work on Windows?

Either way, I think this current behavior should be documented and ideally improved.
