### ISSUE TITLE
the description of package.json

### ISSUE THREAD

**Issue by gdennie** [npm/npm#11406]
the description of the home page field is a waste of space.

**Comment by othiym23** [comment]
What's the problem with having that information there? What would you rather see instead?

**Comment by gdennie** [comment]
Sorry for the vagueness. It is saying both to put a url and not to put a
url. I know it is some kind of joke but it doesn't help the newbie.

**Comment by othiym23** [comment]
The current wording implies a certain level of familiarity with CommonJS that most npm users probably lack, so it is a bit confusing, but it's not actually contradicting itself – it's saying that `"homepage"` should be a URL, but that URL should not be in a field named `"url"`, which has a different, special purpose.

I'd be happy to take a patch to the docs that removes that bit of language (the relevant documentation lives in `doc/misc/package.json.md`), which I agree is at best distracting. Since this isn't something that on its own rises to the level of being a bug, I'm going to close this issue. Thanks for your time!
