### ISSUE TITLE
Using npm.commands.install Never Returns

### ISSUE THREAD

**Issue by atom0s** [npm/npm#11408]
I am trying to use npm internally within my project but I am running into an issue with callbacks never getting fired. 

    var prefixPath = 'C:\some\path\to\a\sub\folder';

    npm.load({ prefix: prefixPath }, function (err) {
        
        npm.commands.install(['async'], function(err, res) {
            // This never gets called and we just die into nothing..
        });
        
    });

Above is a simple example in my project that fails no matter what. I can leave the configs passed to load blank, with another path, etc. and no matter what install's callback is never fired. The actuall task does finish and the package installs, but I get no callback to handle the next step.

I am using npm 3.6.0 and I also have tried 3.7.0 and 3.7.1. All of which fail to work.

Running on Node.js 5.5.0.

**Comment by othiym23** [comment]
There are some subtleties to using the internals of the CLI code base programmatically that have led the CLI team to decide that it's unfit for use as an external API, which is why the "API documentation" disappeared in `npm@3`. The supported way to use npm from your own programs is via a child process invoking the CLI. 

We neither support programmatic use nor do we encourage anyone outside the team to do so. We do have plans to offer a proper, component-based API for the various tasks performed by npm, but that's still a ways off. Thanks for your time, and if you have questions about effectively using npm as a child process, let us know.

**Comment by atom0s** [comment]
Well if having to use it as a child process is my only option then sure, I could use some help with that. I need to be able to specify the directory where the package will be installed to.

**Comment by othiym23** [comment]
npm always puts packages into a `node_modules` directory, and you can set the root relative to which that `node_modules` directory will be created by passing the `--prefix=/path/to/app/root` / `-C` option to the CLI.
