### ISSUE TITLE
npm script conventions

### ISSUE THREAD

**Issue by DannyDelott** [npm/npm#11425]
`npm start` and `npm test` seem to be the only two scripts that don't require you to execute them as `npm run <script>`. By promoting these two scripts, it enables the community to create conventions for them.

While `npm test` is self-explanatory, what is the rule for `npm start`? Is it intended to be reserved for whatever script might launch your server? [The docs](https://docs.npmjs.com/cli/start) say it will run `node server.js` by default, which may lead one to believe that if your package does not need a server, then maybe it shouldn't be used.

Case in point:

I am building a library that does not require a server at all. It just needs to lint, transpile some ES6, test, concat, and minify.  Should all of this be done under `npm run build` instead? Are there examples of npm packages where `npm start` has been repurposed for building the package?

**Comment by ashleygwilliams** [comment]
hi! this is an interesting question.

generally i think your experience re: `npm start` starting a server is correct. for projects that don't require a server, i have seen `start` used for something like [`live-server`] for development purposes. 

if there is a build step, putting that step in a `build` script is best, at least in my opinion. primarily because you likely need to use it for other things, such as tests, and the semantics of the word `start` suggest something that would need to be stopped, while `build` exits after it is complete. e.g. mine tend to look like:

```
// package.json
{
  "name": "my-site",
   "version": "1.0.0",
   "scripts": {
      "build": "bin/build.sh",
      "test": "npm run build && mocha",
      "start": "npm run build && live-server ."
   }
}
```

npm doesn't explicitly enforce any conventions (on purpose!), but these are the trends i've seen. would make an interesting blogpost!

[`live-server`]: https://github.com/tapio/live-server

**Comment by aredridel** [comment]
you may actually want the `prepublish` script, which while badly named, runs after a root level install, and prepares the module for use if it's published.

**Comment by othiym23** [comment]
As this issue posed a question, and @ashleygwilliams and @aredridel have provided good answers, I'm going to close this issue. The CLI docs around package scripts are reference docs, which means that they tell you what and how the scripts work, but do a less good job of explaining the why, as well as what you might want to use them for. 

@ashleygwilliams is npm's editor in chief, and while I can't speak for her, she might be interested in hearing more from you about your experiences in trying to learn how to use package scripts; they're a powerful feature, and npm doesn't yet have a standard guide on how to use them. So thanks for opening this issue, and thanks for your time!
