### ISSUE TITLE
Cloning and Forking of packages should be included in the cli

### ISSUE THREAD

**Issue by ArikMaor** [npm/npm#11443]
# Current Situation
Lot's of people are doing [this things][article], and for a good reason!

# Proposition
I believe the process should be integrated in the cli like this:

## Cloning
This will allow users to quickly edit packages outside of the npm database
`npm clone package [dest] [--clone] [--link]`
1. Copies a package to the current directory (or specified in dest)
2. if `--clone` is specified, clone the repository specified in `package.config`
3. if `--link` is specified, run `npm link` after copying/moving the package

## Forking
`npm fork package [--organization org_name] `
1. Forks the package on GitHub (after you called clone)
2. Sets the new repository as the origin remote
3. Optionally uses an organization account
4. Uses credentials from npm GitHub [integration]

__This can be implemented easily using [hub]__

[article]: http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb
[integration]: https://docs.npmjs.com/enterprise/github
[hub]: https://hub.github.com/

**Comment by ArikMaor** [comment]
@felixge

**Comment by zkat** [comment]
This is a subset of a much larger problem in a small-module world. There are many other considerations and workflows to cover when trying to solve this, and we need a larger solution that takes more of those cases into account -- for example, better linking might help as well.

Furthermore, while we do have some git features, they are fairly limited in their scope (mostly just the ability to specify git repos and versions as dependencies in the installer), which goes against our desire to work more symbiotically with things like git.

All that said, we think the best solution right now, and for the time being, is to document reliable workflows for stuff like this, and maybe even point out other tools (such as [linklocal](npm.im/linklocal) and [hub](https://github.com/github/hub)) that can be used to make this process easier. This’ll also help us have, written down, the various workflows that we need to keep in mind in the future as we design a more complete solution to this. Just the stuff you wrote in this issue is a good start for that documentation, I think, since you outlined what the commands would actually do.

So I’m going to close this feature request, but I encourage you to keep an eye on related discussions (for example, our `link` label), and docs really would be great. :)

p.s. you get super-sweet npm socks if you submit documentation stuff to npm! :grin:
