### ISSUE TITLE
npm3 does not flatten a dependency structure completely

### ISSUE THREAD

**Issue by rafek** [npm/npm#11457]
npm3 brought to use dependencies flattening so that a `node_modules` folder is flat. Apparently that's not always true. I have my application, let's name it `A` and a module I'm developing, `B`. That module has `gulp` as a dependency and some `gulp` plugins, like `gulp-rename`. I was expecting to have `gulp` and `gulp-rename` in the `node-modules` folder of my app `A` (as it has `B` as a dependency). But this is not the case. `gulp-rename` is in fact in `A/node_modules` but `gulp` itself is in `A/node_modules/B/node_modules` folder.

Is aboved a desired behaviour? If so how npm determines which package should be installed flat and which should not?

**Comment by ashleygwilliams** [comment]
hi! without knowing the version numbers of the packages you are describing, it is hard to know whether what you are describing is intended behavior. i can say for certain that while npm3 does *more* dependency flattening, it certainly doesn't produce a completely flat tree by any means. there is no mechanism for npm3 or otherwise to hold 2 versions of the same package at the top level of the dep tree as the dir names would be the same and no file system allows for two identical dir names in a single dir.

for more information about how npm3 works, please read this page in the docs: https://docs.npmjs.com/how-npm-works/npm3

if you continue to have trouble, please open a new issue!

**Comment by rafek** [comment]
@ashleygwilliams thanks for the answer. I've isolated my issue and it seems that it's not happening because there's other version of gulp elsewhere. See https://github.com/npm/npm/issues/11466
