### ISSUE TITLE
npm COMMAND DOES NOTHING

### ISSUE THREAD

**Issue by mojoboss** [npm/npm#11469]
I was trying to login using npm, but I was getting some errors. I updated to the latest version using
`npm install npm@3 -g`
But now nothing happens whenever I try npm commands. Here's a screenshot
![screenshot from 2016-02-08 11 45 18](https://cloud.githubusercontent.com/assets/8466448/12879479/c501bf24-ce59-11e5-8487-cec22f5c0d42.png)

**Comment by erwin16** [comment]
same issue too...

**Comment by othiym23** [comment]
This isn't a failure I see very often, and I can't reproduce it locally, so can either of you tell me a little more about your environment so the team can get a reproducible of this to troubleshoot?

- Are you running Homebrew and / or nvm?
- If you run `npm || echo $?`, what does it return?
- What does `which npm` return?
- Are both of you running Linux?
- Did you start from the system-provided `nodejs` and `npm` packages? If so, do you have `nodejs-legacy` installed?

**Comment by mojoboss** [comment]
I'm running nvm & I'm using Linux Mint 17.1 Rebecca.
`which npm` returns `/usr/local/bin/npm`
`npm || echo $?` returns 1.

**Comment by apepper** [comment]
It's probably not the exact same issue, but today I was dealing with something very similar: Calling `npm test` would not do anything and just exit with exit code `0`. The same was also true with all other scripts, listed in the `package.json`.

I was able to "fix" this issue, by completely nuking `node`, `npm` and `nvm` as well as the `node_modules` folder from the system and reinstalling it from scratch (using `brew install nodejs`). `rm ~/.npm/` was a really important step to achieve this.

Just to give some context: My system is running OS X 10.11 (El Capitan) with `zsh`, but with `bash` the same was also true. I just recently upgraded from Yosemite to El Captain, where `npm` was already installed.

Most likely `npm` was broken because of a broken module from `~/.npm/`.

**Comment by sachpatel** [comment]
Was experiencing the exact same issue as @mojoboss on Linux Mint 17.3 (Rosa)

`npm || echo $` - returns nothing

Installing nodejs-legacy has actually fixed the issue, hopefully that helps anyone else

**Comment by InfiniteStyles** [comment]
I'm having this issue on Windows 10 and don't know how to deal with it.

**Comment by rpitera** [comment]
Found this in another thread and it solved the issues for me:

"Note: If you get "301 Moved Permanently" then try curl -0 -L http://npmjs.org/install.sh | sudo sh to follow redirects. Also notice I added sudo before the sudo sh command depending on your users permissions."

Can't find the original thread again but the user was @mikemoser and he has my gratitude!

**Comment by seanf** [comment]
This was mikemoser's comment, for what it's worth:
https://github.com/tj/n/issues/101#issuecomment-40827196

**Comment by rpitera** [comment]
Thanks Sean - couldn't find the link in my history for some reason.  But this solved the issue for me; I would have thanked him in the thread but it was closed.

**Comment by svobom57** [comment]
Had the same issue, as @sachpatel pointed out, installing legacy solved it.

**Comment by dave** [comment]
I had these symptoms today, and traced it to running `apt-get install node`. I assume the `node` package isn't actually anything to do with `nodejs`, and installs a `node` executable which breaks `npm`?
