### ISSUE TITLE
npm3 does not flatten a dependency when it's listed by name in a bin field (package.json)

### ISSUE THREAD

**Issue by rafek** [npm/npm#11466]
Having an app `A` and a module I'm developing, `B`. That module has `gulp` as a dependency and a package.json `bin` property defined as following (`B`'s package.json):

``` javascript
"bin" {
    "gulp": "<some_valid_path>"
}
```

I was expecting to have `gulp` in the `node-modules` folder of my app `A` (as it has `B` as a dependency and because of npm3 dependency flattening). But apparently npm leaves it in `A/node_modules/B/node_modules` folder. Is it an intended behaviour and why?

**Comment by pawelgalazka** [comment]
I'm experiencing the same thing. The issue also is that this can produce kind of not correct `peerDependency` warnings. Let's say that I have `plugin1`, `plugin2` and `core1` modules in dependencies. `plugin1` and `plugin2` have `peerDependency` on `core1`, but name of `core1` exists in `bin` so it is not flattened but plugins are. So even if I specified `core1` in deps I get `peerDependency` warnings from plugins because plugins are resolved higher in the tree.

**Comment by wallw-bits** [comment]
I have a similar issue with a `project` which depends on `moduleA` and both the project and `moduleA` depend on `modernizr` and expect that binary to be available in npm scripts. After running `npm install` on `project`, `modernizr` resides in `project/node_modules/moduleA/modernizr`, but its binary `modernizr` is not linked in `project/node_modules/.bin`, which causes several of the aforementioned scripts to fail. Is there any way to correct this in the `package.json`?

Running `npm install modernizr` within `project` fixes the problem, but that is annoying and somewhat unintuitive after just having run `npm install` to install all the dependencies.
