### ISSUE TITLE
npm ls --parseable doesn't seem to respect depth argument

### ISSUE THREAD

**Issue by glenpike** [npm/npm#11495]
If I run

```
npm ls --depth=0 --parseable
```
I get a lot of cruft about nested dependencies - I should only see the top level ones listed.

**Comment by zacdoe** [comment]
I have written a potential fix for this bug, however in order to properly test my changes I would have to alter the underlying `npm-registry-mock`. I have a failing test and fix for `npm ls --depth=0 --parseable --long` and am working on the test for `npm ls --depth=1 --parseable --long` but the mocked out packages only go one dependency deep, so there is no way to verify whether the depth has stopped at the correct level. There needs to be one more level of depth in the mocked packages to properly test the distinction between `--depth=1` and `--depth=Infinity`. Can anyone advise me on the best strategy for achieving this?
