### ISSUE TITLE
Command for listing teams a user belongs to just lists all teams

### ISSUE THREAD

**Issue by sliddell** [npm/npm#11491]
Using the instructions in the npm documentation I'm trying to [list the teams that a particular user belongs to within my org](https://docs.npmjs.com/orgs/teams#list-teams-a-member-belongs-to). However, when I run `npm team ls [my org] [my user]` I just get a listing of all of the teams in my org. This will even happen if the username I provide does not exist.

There are currently two teams in my org; developers and testteam. 

When I run  `npm team ls [my org]`
I get:

> [
>   "[my org]:developers",
>   "[my org]:testteam"
> ]

I have a user who is only a member of the developers team.
However when I run `npm team ls [my org] [username]`
I get:

> [
>   "[my org]:developers",
>   "[my org]:testteam"
> ]

Also, when I run `npm team ls [myorg] dsafjhbdafgdjghasdf`
I also get
I get:

> [
>   "[my org]:developers",
>   "[my org]:testteam"
> ]

I'm using npm 3.7.1 and as per the troubleshooting guide I've tried upgrading node 4.3.0 LTS to 5.6.0. I'm working on Windows 10. No errors are being thrown, so there's no debug for me to attach.

**Comment by othiym23** [comment]
This is an oversight; you should be able to do this in some form with the CLI right now, and we just forgot to include it in the first round of teams and orgs work because there was kind of a rush to get things out the door. The team needs to figure out exactly what the UX for this should be, and we also need to confirm with @npm/registry-team that the endpoint we need will be available on the primary registry. After that, we can change the status of this issue to `patch-welcome`, and if nobody else beats us to it, we will implement this ourselves, probably within the next 3-6 months. Thanks for bringing this up!
