### ISSUE TITLE
upgrade problem from 3.7.2 to 3.7.3

### ISSUE THREAD

**Issue by leandroong** [npm/npm#11513]
C:\WINDOWS\system32>npm install -g npm@3.7.3
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lean\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@3.7.3"
npm ERR! node v6.0.0-nightly201602102848f84332
npm ERR! npm  v3.7.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

C:\WINDOWS\system32>

**Comment by othiym23** [comment]
`npm@3.7.2` (and **all other versions of npm _except_ `npm@3.7.3` / `npm@2.14.19`**) is incompatible with Node.js 6 due to a change in how Node 6 handles `process.bindings` and caching of built-in modules. You'll either need to install npm from master by cloning it via git, or wait until a build of Node 6 is released with a patch for that change (which I believe is coming – see nodejs/node#5102), or which includes a patched version of npm.
