### ISSUE TITLE
How to handle this error??

### ISSUE THREAD

**Issue by mueedahmed1** [npm/npm#11564]
error ts1148: cannot compile modules unless the '--module' flag is provided.

**Comment by KenanY** [comment]
@mueedahmed1 Is `npm` giving you this error? If so, then there should be a `npm-debug.log` file in your current working directory, which you can upload to [gist.github.com](https://gist.github.com/). My suspicion however is that this error is coming from whatever you are using to compile TypeScript files (which `npm` has nothing to do with).

**Comment by othiym23** [comment]
This does indeed look like an issue with TypeScript, as @KenanY suggests. You might want to take a look at the [TypeScript FAQ](https://github.com/Microsoft/TypeScript/wiki) to see if they have suggestions on how to get up and running with TypeScript's build tools. Because this is an issue unrelated to npm, I'm going to close it. Thanks for your time!

**Comment by mueedahmed1** [comment]
![prob](https://cloud.githubusercontent.com/assets/12622228/13085693/4dccadfc-d501-11e5-8983-e70825ad2e96.png)
check out this..

**Comment by mueedahmed1** [comment]
![probl](https://cloud.githubusercontent.com/assets/12622228/13085784/c40d9026-d501-11e5-934b-40f13531a0f2.png)
This is file structure..

**Comment by KenanY** [comment]
@mueedahmed1 Yup, that screenshot confirms my suspicion that this is not an issue with `npm` at all. Why don't you try using the `--module` flag as the error message suggests? If you need anymore assistance, I would go ask over at StackOverflow or some forum for TypeScript developers since you will find more people who are familiar with TypeScript at those sites rather than here.
