### ISSUE TITLE
npm network issues?

### ISSUE THREAD

**Issue by rafek** [npm/npm#11565]
I'm not sure how to name this particular issue as npm itself does not end with npm ERR! or anything like it. It just hangs on:

loadDep:xtend → network ▌ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

And it takes forever to finish (if ever). That happens for various packages. I've increased the log level to debug and haven't seen anything special there.

I assume it's network related as it states, but I'm not sure what kind of error hides behind that.

Any clues how to tackle that?

**Comment by othiym23** [comment]
Things that are helpful when running into these kinds of network issues include disabling firewall software on your PC or router, trying the install with a wired connection (if you can), or switching to a different network. It's on the CLI team's roadmap to rework npm's network code (which we're looking to get to this year), because there's a wide variety of things that can cause this particular problem, and it's caused by npm overloading the local network connection and not any specific single bug.
