### ISSUE TITLE
Pr-encouraged label

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#11563]
This is a non-code issue :) I think labels here might be missing a `pr-encouraged` or `pull-request-encouraged` label that tells us which of the 1888 issues would be ready for a PR but the time or priority is lacking.

**Comment by KenanY** [comment]
There's [`patch-welcome`](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=label%3Apatch-welcome).

**Comment by othiym23** [comment]
The current policy of the npm CLI team is to close feature requests that the team doesn't intend to work on themselves, and to add `patch-welcome` if it's a feature that we would land if submitted as a patch. For bugs, we leave them open, because we do intend to get them all fixed eventually, but if the change is straightforward and needs no further discussion, then we'll add `patch-welcome` to those as well. Thanks for your time and contribution!

**Comment by martinheidegger** [comment]
Thank you for taking the time to explain this.
