### ISSUE TITLE
'link:./module'

### ISSUE THREAD

**Issue by KoryNunn** [npm/npm#11585]
To solve the `require('../../../../module')` issue, npm could implement a dependency format similar to `file:` that installs local modules as a link so that they can be required cleanly.

## Example:

dir structure:
```
root/
    foo/
        sub/
            thing.js
    bar/
        /dooby.js
```

### thing.js

Currently:
```
require('../../../bar/dooby')
```

With `link:`:
```
require('bar/dooby');
```

### package.json

```
{
    ...
    dependencies:{
        ...
        bar: 'link:./bar'
    }
}
```

### node_modules
```
/node_modules
    /bar <- linked version of ./bar
```

I'd definitely be open to alternative implementations because this is a problem I've been trying to solve for a long time.

**Comment by KenanY** [comment]
[`linklocal`](https://github.com/timoxley/linklocal) does this amazingly :)

**Comment by thonymg** [comment]
+1

**Comment by jwulf** [comment]
This would be awesome. Totally over the `./../../` stuff. Very 90's.

**Comment by KoryNunn** [comment]
@KenanY Thanks, it works reasonably well, but feels a bit tedious to set up/maintain since everything linked needs a package.json. Also it would be great to not have to run postinstall scripts for something this useful.

I could see the functionality in linklocal being integrated into npm quite nicely, maybe like: 

```
npm i --link ./some/dir
```

which could add a `link:./some/dir` line to package.json,
and npm could automatically create a package.json in node_modules for any linked module that doesn't have one.

**Comment by othiym23** [comment]
This feature request is closely related to two other existing features: [package linking](https://docs.npmjs.com/cli/link) and [local dependencies](https://docs.npmjs.com/files/package.json#local-paths). This framing of the problem feels tied to a workflow that is specific enough that it doesn’t justify adding a third feature, especially when third-party solutions like `linklocal` exist.

The CLI team agrees that there are probably useful refinements to be made to

1. working on multiple packages simultaneously during development, and
2. making it easier to support monorepo-style flows where multiple packages are hosted and installed from a single repository.

The team’s sense is that there are quite a few other things we’ll need to get to before those changes are a priority, and this is definitely something that requires careful design and discussion before it’s implemented. For that reason, and because the team isn’t going to be able to get to this within the next 6-12 months, we’re going to close this feature request. Thanks for your time!
