### ISSUE TITLE
npm install never ends

### ISSUE THREAD

**Issue by jhyland87** [npm/npm#11661]
I m trying to npm install some packages, (any package, this happens with anything), and no matter what I try, npm never seems to get past the initial download phase. I can see its listing the same packages over and over...

I think it may be similar to [this issue](https://github.com/npm/npm/issues/7318)

Ive tried:
- Clearing the cache
- setting the `TEMP` var to `/tmp` (which it wasnt even set before)
- Re-installing npm (Version *1.3.6*)

Heres the [console output](http://pastebin.com/bw84jppE) of the install log, (I eventually aborted the install, but you can see so many duplicates)

What throws me off even more.. is the npm_debug log is empty

**Comment by KenanY** [comment]
@jhyland87 Does this also occur with the latest stable release of `npm`?

**Comment by othiym23** [comment]
`npm@1.3.6` is two and a half years old and completely unsupported. You should [update to the latest stable npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) on the build host. The latest stable versions are `npm@3.7.3` by default, and `npm@2.14.19` for npm LTS.

> What throws me off even more.. is the npm_debug log is empty

Since `npm-debug.log` is only created when npm crashes, there won't be one if npm is still in the process of installing.

Good luck getting this sorted out!

**Comment by jhyland87** [comment]
Wow! I had no idea it was that old.. literally just created this EC2 instance, and `yum update && yum -y install nodejs npm ...`, so I kinda assumed it would be at least somewhat close to the latest version..

Sorry about that. Seems to work now.
