### ISSUE TITLE
npm completion does not work with : 

### ISSUE THREAD

**Issue by electricBonfire** [npm/npm#11696]
I have the following scripts `copy` `copy:all` `copy:js` `copy:css`

I have added the completion script.

If I type `npm run copy:<tab>` It completes to `npm run copy:copy:`

Also if I run `npm run copy:cs<tab>` it completes to `npm run copy:copy:css`

**Comment by gustavnikolaj** [comment]
I have a variant of this problem.

When I type `npm run copy:a<tab>` it doesn't do anything, where I expected it to complete to `npm run copy:all`, but when I type `npm run copy<tab>` it list me all the options.

So it seems that there's something funky tripping it up.

After a little bit of googling I found the answer. It's outside of npm's reach; The reason is bash, which has an env variable called `COMP_WORDBREAKS`. It has a list of characters that the completion logic should use as word separators.

https://github.com/scop/bash-completion/blob/dde1d314c4e8934693e7090ef4467dfac7d72a92/bash_completion#L492-L508

As noted in the above referenced comment, it can be fixed by running the follwoing in a shell (removing the colon from the list of word breaking characters: 
```
$ export COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
```

To enable it permanently you can add it to your `.bashrc` file.

**Comment by KrekkieD** [comment]
Same issue, on OSX. I understood changing `COMP_WORDBREAKS` is not really recommended, since it might break something else. It does make it work though.

**Comment by gustavnikolaj** [comment]
There is not really anything the npm team can do to fix it. You will have to either do the word-break change in your shell or use another character for separation :-)
