### ISSUE TITLE
Feature request: packages naming

### ISSUE THREAD

**Issue by delvedor** [npm/npm#11724]
Hi all, I've tried to search in the issues, but I don't know how call this "feature".

A lot of little modules approach is better than some big modules approach, but the problem of the *"little modules approach"* is that you need to nominate these, and you will need **a lot** of names!
So, I'm not a god of math, but is very easy that two people want to give the **same name** to different packages.

So my question is:
Why npm don't have / don't adopt a different packages naming?
A good example could be **username/package**.
So after publish a package named *foo*, I can install it by typing
```
npm install delvedor/foo
```
or if I want the *otherUser* foo package
```
npm install otheUser/foo
```

It was already proposed?
- If not, do you think could be a good idea? Why?
- If yes, where?

Thanks.

**Comment by delvedor** [comment]
Yeah, a sort of.
In scoped packages the **@ scope** can be any name, my proposal is to apply this "new naming" to all npm packages.

Real world example:
[Ringpop](https://www.npmjs.com/package/ringpop) is a Uber package.
I want to make a my implementation of that code and I want to use the **same name**.
At the moment is not possible, but if npm will adopt the **username/package** naming by default when I publish my ringpop version with
```
npm publish
```
On the npm public registry I will find:
```
uber/ringpop
delvedor/ringpop
```

Then I can install one (or both) by typing
```
npm install uber/ringpop
```
or
```
npm install delvedor/ringpop
```

I hope I explained it well.

**Comment by othiym23** [comment]
Supporting the on-the-fly aliasing or replacement of packages in a drop-in way cuts against the grain of how npm dependency trees are designed to work. End users shouldn’t have to make choices at installation time between multiple implementations or forks of a package, because this considerably complicates things for newcomers, and also makes the goal of repeatable, unattended deploys much harder to reach. For that reason, and also because this would be a very significant change to the registry, which currently has well over 200,000 packages that are unscoped, this isn’t a change that the CLI team is interested in landing for npm.

Also:

> In scoped packages the @ scope can be any name

That’s not exactly true; at least for the primary npm registry, a scope must share its name with either  a user name or an organization name, so in many ways it’s the namespace you’re looking for. Moving to making all packages scoped by default would also play havoc with the way that scopes are distributed across multiple registries (for example, when your company has some packages that are scoped onto a company-specific registry, while fetching or publishing the majority from the primary registry). To make this change would be a significant architectural departure.

Thanks for your proposal, and thanks for your time!

**Comment by delvedor** [comment]
Clear and complete explanation, I didn't understand from the docs that a scope must share its name with either a user name or an organization name.

Thanks for answering and thanks for your amazing job with npm!

**Comment by delvedor** [comment]
Sorry if I'm reopening this.
Don't you think that force a naming based on `username/package` could avoid situations like *azer/left-pad/kik*?

So in this specific situation there would be two packages:
`kik/kik`
`azer/kik`
And the users can make a choice based on the readme/downloads/whatever.

Thanks for your work.
