### ISSUE TITLE
`--depth Infinity` has no effect on `npm update`

### ISSUE THREAD

**Issue by GriffinSchneider** [npm/npm#11726]
I have a package `package-a`, which depends on `package-b`, which depends on `package-c`.

I'm working in `package-a`, and all the commands here are run from its root directory (with its `package.json`). 
For this example, lets say that `package-b` depends on `"package-c": "^1.0.0"`. I have `v1.0.0` of `package-c` currently installed in `node_modules/`, and there's a `v1.0.1` of `package-c` published to npm.

Based on the docs (https://docs.npmjs.com/cli/update), I would expect `npm --depth Infinity update` to install `package-c@1.0.1`, but it doesn't. After running `npm --depth Infinity update`, I am left with `package-c@1.0.0` installed in my `node_modules` directory.

Other things I've tried:
- `npm update` does not install a new version of `package-c`. This is what I expect based on the docs.
- `npm --depth 9999 update` _does_ install the new version of `package-c`, which is also what I'd expect. I see that the docs were changed in https://github.com/npm/npm/pull/11150 to recommend `--depth Infinity` instead of `--depth 9999`, but as mentioned above `--depth Infinity` does not seem to work.

Tested on `npm@3.8.0`.

**Comment by othiym23** [comment]
This is a braino on my part; I gave advice to the person who landed this change recently to use `--depth Infinity` when in fact it's the magic value used by npm to set the depth to 0 so that npm can default the depth to 0 for some operations and not others. If you switch back to 9999, then you will indeed get the output you're expecting. I think the proper solution to this is to rework this code so that we're not using magic values to get around the fact that this is a shared configuration value, but in the meantime, we'd happily accept a patch to revert the docs back to what they said before. Thanks for the clear report!

**Comment by GriffinSchneider** [comment]
Sure, reverted the docs here: https://github.com/npm/npm/pull/11762
