### ISSUE TITLE
npm ERR! Darwin 14.5.0 (cant install plugins or anything)

### ISSUE THREAD

**Issue by rav-sohal** [npm/npm#11734]
I am getting this error:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "npm" "-g"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'github-url-from-git'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ravs/npm-debug.log
```

Also i can't install no plugins for cordova etc...

Any ideas?

**Comment by othiym23** [comment]
It looks like your install of npm got broken at some point. The easiest way to fix it is to reinstall Node and then rerun `npm install -g npm@latest`, which will get you a more up-to-date version of npm at the same time.

Since I'm pretty sure this will address the problem, I'm going to close this issue, but if you're still having problems after doing the above, let me know, and I can reopen this issue. Thanks for your time!

**Comment by Ib467** [comment]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "-g" "install" "npm"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbookpro/npm-debug.log
