### ISSUE TITLE
Npm escapes scope slashes to %2F, which does not work when registry is hosted on Apache

### ISSUE THREAD

**Issue by spadfield** [npm/npm#11738]
**Context:** Hosting a private npm registry on an Apache-based server (e.g., Artifactory), and using package scopes to distinguish private packages from public ones.

**Description**
The use of a slash character in scoped package names (e.g., "@myorg/mypackage") causes the `npm publish` and `npm install` commands to escape the slash to '%2f'. By default, Tomcat is configured to reject requests containing an escaped slash, so these commands always fail. The only workaround is to reconfigure the web server's default settings, which is not always feasible.

This is effectively a barrier to entry for adopting npm.

Ideally npm should allow an alternative delimiter to be used that does not have special significance for HTTP servers. Some examples might be: "[myorg]mypackage", "myorg@mypackage", or "myorg:mypackage".

Failing that, it would suffice to have a configuration flag that controls whether the slash is escaped or not.

**Comment by othiym23** [comment]
This is a carefully-designed aspect of the specification of scopes. Its intent to make the slash part of the package name, and therefore ensure that npm remain interoperable with a wide variety of registry software in a backwards-compatible way (including, significantly, most CouchDB-based registries, including the primary npm registry).

I know that Artifactory users have set up support for scoped packages in their registries, so I'm confident that this can be configured to work properly. As this is pretty heavily baked into the design of how scopes work across npm (not just for installation), this is a sufficiently significant change that the justification would need to be more than making it easier to work with the defaults of a single suite of registry software.

As such, I'm going to close this issue. Thanks for your time!

**Comment by spadfield** [comment]
I believe this is an Apache issue, not an Artifactory one.

I'm not against slashes, but can you tell me why they are being URL-encoded in HTTP request URLs? IIS treats %2F in the path the same as a slash, and my understanding is that Apache's default configuration does not allow %2F at all. What's wrong with not encoding them?

Requiring your users to contact their operations and security departments to reconfigure an in-house server seems like an unnecessary barrier to entry.

**Comment by othiym23** [comment]
> I believe this is an Apache issue, not an Artifactory one.

From your description, it sounds like a Tomcat / application container issue, which is why I said "a single suite of registry software".

> I'm not against slashes, but can you tell me why they are being URL-encoded in HTTP request URLs?

If you're curious, there was [extensive discussion](https://github.com/npm/npm/issues/5239) around this feature before it was rolled out in `npm@2`. The URL-encoded slash was chosen because it was the least disruptive way to roll out scoped packages, including both the original npm registry software stack and the breadth of alternative registry offerings.

The slashes in scoped package names are part of the name, not part of the request path. This is important for working with CouchDB-based registries, as I said, but it's also proved to be relatively straightforward to other registries like `sinopia` and `cnpmjs`.

> Requiring your users to contact their operations and security departments to reconfigure an in-house server seems like an unnecessary barrier to entry.

This isn't something that users should have to deal with at all; it's something that should be handled by the team standing up the private registry. Ideally, this is something that should be part of the Artifactory install script and / or documentation, and you might want to raise this issue with them in some way.

**Comment by gkohen** [comment]
From Artifactory's Wiki:
**Npm 'slash' character encoding**
By default, the npm client encodes slash characters ('/') to their ASCII representation ("%2f") before communicating with the npm registry. If you are running Tomcat as your HTTP container (the default for Artifactory), this generates an "HTTP 400" error since Tomcat does not allow encoded slashes by default. To avoid this error when using npm scope packages, you can override this default behavior by defining the following property in the catalina.properties file of your Tomcat:
org.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true

**Comment by willsheppard** [comment]
This article appears to explain the Apache configuration required to make this work: https://techblog.dorogin.com/setting-up-artifactory-as-npm-repository-behind-apache-7541d5140492
