### ISSUE TITLE
Use short github-url with private github installation

### ISSUE THREAD

**Issue by dylancwood** [npm/npm#11749]
We use github enterprise, which we access via an internal hostname. It would be great if we could configure the hostname used for resolving short github urls (e.g. `org-name/repo-name`) in npmrc. Does this functionality exist (couldn't find docs)? If not, are you open to a PR on it? 

Thanks.

**Comment by othiym23** [comment]
What it sounds like you’re requesting here is something like Bower’s “custom resolvers”, which allow you to dynamically remap the target of shorthand syntax. The CLI team has been advised by a number of people connected to Bower that this is a footgun disguised as a useful feature, because it breaks the self-sufficiency of the package manifest. That’s a fancy way of saying that that `package.json` should consume the same sources regardless of what other configuration is set on the part of the CLI user.

In this case, you’re trading slightly shorter syntax when specifying GitHub Enterprise dependencies for ambiguity about where those dependencies should be obtained. Should you ever decide to make the code using that shortcut syntax public, you’ll have to scrub and replace those shortcut usages, and it’s really easy to see ways in which some would be overlooked, which is enough of a reason to outweigh the terseness provided by making that syntax remappable (in my opinion, at least). It’s a lot safer just to use the explicit hosted git dependency syntax in this situation.

As such, we’re not going to land this feature, and probably not ever going to land changes that make shortcut syntax remappable in this way. I hope this explanation is sufficient justification. Thanks for your time, and thanks for writing this up.

**Comment by dylancwood** [comment]
Thanks @othiym23. I see where you are coming from, and appreciate your response. Your points are well made, and I have to agree with you. 

Just to be difficult, I'll ask this as well:
Would it avoid the :footprints: :gun: to declare the custom git hostname in package.json instead of in .npmrc?

**Comment by othiym23** [comment]
> Would it avoid the :footprints: :gun: to declare the custom git hostname in package.json instead of in .npmrc?

It would, but it wouldn't handle a host of other edge cases related to how npm and other tooling consume shortcut syntax. What's hard about including full hosted Git URLs in `package.json`?

To provide a little more context, we'd have to put a significant amount of work into a number of npm's dependencies, for a feature that the team has already been advised is more trouble than it's worth. I'd like to deprecate the unqualified GitHub shortcut syntax in favor of `github:org/repo`. This is in part because I don't think it makes sense for npm to be so tightly bound to a single other service provider, and in part because I think it's easier for users to understand `package.json` when things are explicit, even if that requires them to be a little more verbose.

**Comment by dylancwood** [comment]
That makes sense. Thanks again for the detailed response.

> What's hard about including full hosted Git URLs in package.json?
Nothing is _difficult_ about it, however coming from using the shorthand syntax on previous projects, it just looks bad ;-)
