### ISSUE TITLE
Allow UTF-8 for package names

### ISSUE THREAD

**Issue by zanona** [npm/npm#11769]
Hey guys, at the moment, using special character for package names seems to be a trouble, however I believe that perhaps this is something that may be reconsidered, since nowadays even TLD such as .com allow domain names with special characters?

```sh
$ npm init
name: (jöker) 
Sorry, name can only contain URL-friendly characters.
```

**Comment by othiym23** [comment]
This is a limitation that applies to the whole npm ecosystem, and not just the CLI. The CLI should be able to deal with anything that can be serialized to JSON, which in practice amounts to anything that fits into UCS-2 (which is similar to, but not quite the same as UTF-8 – a number of non-Basic Multilingual Plane character sets, particularly including East Asian languages, don't fit all the way into UCS-2). However, the primary registry, including some of its microservices, and the wide variety of private registries, are not necessarily great at handling non-ASCII characters, so this is something that would probably need to be addressed from the back end forwards.

Since this is a registry issue and not a CLI one, I’m going to close this feature request. I think the best place to pursue this conversation further on the npm side is via the [`public-api` repository](https://github.com/npm/public-api/issues). Realistically speaking, I don’t there’s anybody at npm opposed to making this change, but at the same time, it’s not likely to be a high priority anytime soon. I hope this explanation is satisfactory, and thanks for your time!
