### ISSUE TITLE
npm init should assume v0.0.0 instead of v1.0.0

### ISSUE THREAD

**Issue by DannyDelott** [npm/npm#11774]
From the docs on [npm init](https://docs.npmjs.com/cli/init):

> It attempts to make reasonable guesses about what you want things to be set to, and then writes a package.json file with the options you've selected.

It seems odd that when initializing a new package.json it would assume that you already have a v1.0.0 major release in your current directory. This is because, at least for me, I tend to run `npm init` directly after `git init`, so there isn't a major release just yet.

I would suggest initializing the package with v0.0.0 by default.

**Comment by othiym23** [comment]
Because semver has a bunch of [weird, counterintuitive rules](http://semver.org/) governing how versions work when the major version is 0, and because almost nobody can intuitively model the behavior for both `~` and `^` for 0.0.x and 0.x.y version ranges, the CLI maintainers decided about a year and a half ago to change the default initial version to 1.0.0.

You can override it if you like, but the current default is much less confusing to newcomers. Since we're not going to change this, I'm going to close this issue. Thanks for your time!

**Comment by DannyDelott** [comment]
Glad this was thought through already. Thanks for the quick response!
