### ISSUE TITLE
Make npm version create annotated tags using commit messages

### ISSUE THREAD

**Issue by pensierinmusica** [npm/npm#11796]
Hi,

I think it'd be pretty neat if there was an option when using `npm version` to have it automatically generate annotated tags that include all commit message titles since last tag separated by newline.

For example, imagine there are these commits and tags:

```
docs: update docs
chore: add tools
v0.2.0
fix: repair smth
feat: add smth
v0.1.0
Initial commit
```

Now, if we were to create version `0.3.0` we could have a command like `npm version minor -auto` create the annotated tag, including this text:

```
v0.3.0
docs: update docs
chore: add tools
```

Any chance this could be implemented?

Thanks, cheers!

**Comment by whmountains** [comment]
+1

**Comment by othiym23** [comment]
From `npm help version`:

> If  supplied  with  -m  or --message config option, npm will use it as a commit message when creating a version commit.  If the message config contains %s then that will be replaced with the resulting version number.  For example:
> 
>          npm version patch -m "Upgrade to %s for reasons"

This is about as much metadata as it makes sense for the npm CLI itself to add onto a version tag. If your workflow is specific enough that you're including other classes of annotation, it makes sense (to me, at least) to create specific tooling that supports that workflow. One of the advantages of `npm version` is that it's a relatively simple tool, and it's about as complicated in its use of Git as makes sense, given the fact that it needs to support a broad range of Git versions (since the CLI uses the already-installed version of Git), and given that this is designed to be a simple affordance to simplify working with semver when publishing npm packages.

As such, I'm going to close this issue. Thanks for your time, and thanks for the clear problem statement!
