### ISSUE TITLE
npm install should warn when loading from shrinkwrap

### ISSUE THREAD

**Issue by joshjung** [npm/npm#11817]
Just spent the last hour making changes to package.json and not wondering why they were being taken. There should be a flag of some sort after an `npm install` indicating that X packages were ignored in package.json and instead loaded from the shrinkwrap JSON.

**Comment by zkat** [comment]
As far as the CLI team can tell, you’re most likely filing this issue against `npm@2`. In `npm@3`, this would not be a problem: `npm@3` acts as if it first installs whatever is in your shrinkwrap, as specified, and *then* does a regular `npm install`, overriding anything from the shrinkwrap with what’s in your `package.json`. If you want to avoid this problem happening again, my recommendation is to simply upgrade to `npm@3` is at all possible (with `npm install -g npm`)

As far as having `npm@2` report these issues, I think this sort of patch would be out of scope for a version that is already in LTS. My general story with how to treat shrinkwrap issues people have in `npm@2` has been “just upgrade”, since so many things got fixed with it in `npm@3`.

I’m gonna close this issue, since it’s not a problem in `npm@3`, and because shrinkwrap in `npm@2` has enough issues that doing even this much simply doesn’t seem worthwhile, taking into account all the other things we want to fix and improve. Nevertheless, thanks for taking the time to submit the issue, and I hope upgrading resolves things for you! Please let me know if this continues to be a problem. :grin:

**Comment by joshjung** [comment]
Well this is really strange then. Because I am on npm 3!

    joshuas-mbp:~ jjung$ npm -v
    3.3.12

I've resolved the issue on my end, but my shrinkwrap file was saying to load from the repository at version X and I was trying to change the package.json to say to load from a GitHub url and at the time I ended up having to delete my npm-shrinkwrap.json file in order to get it to work.

**Comment by zkat** [comment]
We'll take a closer look, then. Sorry about that :)

**Comment by fizker** [comment]
I can verify this issue with `npm@3.7.3`. I manually added a new dependency to `package.json`, but it never was installed on other machines because it was missing from `npm-shrinkwrap.json`.

A warning listing the differences between `package.json` and `npm-shrinkwrap.json` would really have helped me diagnose the issue.
