### ISSUE TITLE
'artifactory' is not in the npm registry

### ISSUE THREAD

**Issue by qinfchen** [npm/npm#11834]
If one of the dependencies specified in the package.json file is not found, npm will return the following error which is not very informative. I had to look at the debug log to figure out which dependency causes 404. The depedency name is not `artifactory` :)

```
npm ERR! 404 Not Found: artifactory
npm ERR! 404
npm ERR! 404  'artifactory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'test'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by KenanY** [comment]
@qinfchen This happens with a custom registry?

**Comment by qinfchen** [comment]
Yes, we use a custom registry.

**Comment by othiym23** [comment]
I agree that the error message is confusing, but that's due to how Artifactory is configured in your environment. In general, the component of the npm CLI that talks to registries (`npm-registry-client`) can't know how every suite of registry software formats it's URLs, and in error cases like 404s it follows conventions that may or may not work with a specific registry. It's switched between using the first and last elements of the request path over the years, and neither one is right in all cases. It's unfortunate, but not something the CLI team has control over.

As this is something the CLI team can't fix, and as there isn't a generally reliable heuristic to hack around it, I'm going to close this issue. Thanks for your time, and I hope this explanation is useful, even if the resolution isn't completely satisfying!

**Comment by qinfchen** [comment]
Cool. Thanks for the explanation.

**Comment by flekmatik** [comment]
is there at least some workaround how to print name of package which actually failed?

or any switch to display full URL ... that would be totally sufficient

**Comment by orangewise** [comment]
I had the same issue and could fix it by changing the url:

npm publish --registry http://<your artifactory host>/artifactory/api/npm/<name of your local artifactory registry>

**Comment by dannalieth** [comment]
+1 Ran into the same issue.

Note: the resolution is correct if the packages have been npm-shrinkwrapped, but breaks on new fetches

Here's the output when running with verbose:
```
npm verb afterAdd /Users/diranl/.npm/@elements/blueprint/2.23.0/package/package.json written
npm verb stack Error: 404 Not Found: artifactory
npm verb stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:250:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at Request.emit (events.js:185:7)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
npm verb stack     at emitOne (events.js:95:20)
npm verb stack     at Request.emit (events.js:182:7)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
npm verb statusCode 404
npm verb pkgid artifactory
npm verb cwd /Volumes/git/contour/contour-voltron-app
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 Not Found: artifactory
npm ERR! 404
npm ERR! 404  'artifactory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'contour-voltron'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]
```

**Comment by Que3216** [comment]
@othiym23 This error message has been consistently confusing devs on our team.

Looks like the offending code is here: https://github.com/npm/npm-registry-client/blob/master/lib/request.js#L276.

Would it be possible to have whatever code is calling `npm-registry-client` pass through the name of the module it is trying to get, so that when it fails it can print the correct name of the module that it failed to get? Or alternatively could the calling code catch the exception somehow, and rethrow it adding the module it's trying to load to the error message?

If this isn't possible would you accept a PR that adds a line to the error message with the full URL? For example:

```
npm ERR! 404 Not Found: artifactory
npm ERR! 404 GET request for 'https://somedomain/artifactory/api/npm/all-npm/i-do-not-exist' returned a 404
npm ERR! 404
npm ERR! 404  'artifactory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by Que3216** [comment]
I've posted a second issue here: https://github.com/npm/npm-registry-client/issues/144

**Comment by soleil0-0** [comment]
install latest npm will fix it.

`npm install -g npm@latest`

**Comment by cschensai** [comment]
怎么解决的

**Comment by cschensai** [comment]
纠结一下午了。。。。
