### ISSUE TITLE
TypeError: Invalid Version: 0.0.1alpha1

### ISSUE THREAD

**Issue by markusb79** [npm/npm#11840]
Receiving the following error when running _npm install generator-aspnet_:
```
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/bin/npm" "install" "generator-aspnet"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! Invalid Version: 0.0.1alpha1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mbraasch/npm-debug.log

```

[npm-debug.log.txt](https://github.com/npm/npm/files/166262/npm-debug.log.txt)

**Comment by othiym23** [comment]
From looking at `npm-debug.log`, it appears that this install was using a private registry as its install source. Because of #11837, it's possible to publish packages with `version` fields that are invalid as far as npm's install code is concerned. (If you don't feel like reading through that issue, the reason it doesn't affect users of all registries is that most registry suites normalize the package field when serving metadata.)

The fix is pretty simple – unpublish the version containing the erroneous package field (valid semver for the package in the issue would be `0.0.1-alpha.1` – note the dash, and the period between `alpha` and `1`). The CLI team is going to change the validation on publishing to ensure that anything published will be installable, but in the meantime, that's how you fix it by hand.

Thanks for your time, and I hope this explanation was useful!

**Comment by msneiQA** [comment]
I am getting same error. how do I unpublish the version ? and how do I find out the erroneous package field?
Thanks!!

**Comment by johnflux** [comment]
I have the same problem.  How do we unpublish the version?

**Comment by L3au** [comment]
I ran into this because of shelljs problem.  https://github.com/shelljs/shelljs/issues/390

If you use a private registry (e.g sinopia), you need to clear registry local cache.
