### ISSUE TITLE
`npm outdated` ignores private modules from git repos

### ISSUE THREAD

**Issue by WCPetersen** [npm/npm#11869]
`npm outdated` ignores private modules so that it doesn't bother checking the registry for unpublished modules. However, that means it also ignores private modules that are stored in git repos.
[Relevant code](https://github.com/npm/npm/blob/v3.8.2/lib/outdated.js#L283)

**Context:**
I have some modules in private git repos and mark them private in their `package.json`. When they are dependencies, `npm install` installs them, but they won't come up in `npm outdated` or `npm update`.

Instead of using `npm update`, I've been using `rm -rf node_modules; npm install`, which is a pain.

**To reproduce:**
```
mkdir module module/foo module/bar

# Create foo, a module hosted in a git repo
cd module/foo
git init
echo '{ "name": "foo", "version": "1.0.0"}' > package.json
git add package.json
git commit -m "First foo commit"

# Create bar, a private module hosted in a git repo
cd ../bar
git init
echo '{ "name": "bar", "version": "1.0.0", "private": true }' > package.json
git add package.json
git commit -m "First bar commit"

# Create a module that has foo and bar as dependencies
cd ..
echo '{ "dependencies": { "foo": "git+file://'$PWD'/foo", "bar": "git+file://'$PWD'/bar" } }' > package.json
npm install # Both foo and bar are installed
npm outdated # Only foo is shown
```

**Comment by othiym23** [comment]
This is an edge case, and as such it’s not something the CLI team is likely to address soon. You’re right that it’s more difficult than it should be to keep packages marked as private up to date with how the code works right now, though. It would be convenient to be able to just run `npm update` and get the latest version of a dependency hosted on Git, so the CLI team would be happy to take a patch to that effect. That’s why this issue is being closed, but marked as `patch-welcome` – we don’t have time to do it, but we agree it would be nice to have.

However, before that patch can be added, #8300 will need to be resolved, because currently `npm outdated` / `npm update` don’t track the up-to-dateness of hosted Git packages either. If you feel like pitching in on that project, excellent, otherwise keep an eye on it so that it becomes clearer when this change can be landed. Be aware that there’s a little bit of complexity in implementing this, because you need to know what the source is of a dependency before deciding whether it should be filtered from the updated list, so the code may need a little rearranging. That said, the team is happy to answer questions about implementation. Thanks for your time and for the clear problem statement!
