### ISSUE TITLE
Make save-prefix = '' by default

### ISSUE THREAD

**Issue by taoeffect** [npm/npm#11874]
Reality is:

- people don't follow semver (whether on purpose or on accident)
- nodejs apps have a bazillion dependencies
- if just one of them breaks, the whole project can mysteriously break
- people complain about this constantly, and it's a legit complaint

This can be fixed by simply making `save-prefix = ''` by default.

That makes sense after all, as the default should be: **this code should behave exactly as it did when the developer released it.** The current default of `^` is more like, "the probability that this app will break for users approaches 100% is `t -> inf`".

Edit: fixed 20 typos.

**Comment by othiym23** [comment]
npm has a number of design principles that guide its design and maintenance, and at the head of the list is, "npm is a bet on semver." Semver isn't perfect, given that it's a set of conventions rather than a set of objective criteria, but it's what npm is built on. It's a cornerstone of the small package ecosystem, in that `~` and `^` make it easier than not for typical users to pick up bug fixes and security patches more easily than not. This is far more of a benefit than the occasional versioning mistake is a detriment.

`save-prefix` and shrinkwrap are among the tools available to developers who want tighter control over their apps' versions. The team wants to ensure that developers have the tools they need to manage their dependencies as they see fit, and we have plans to keep iterating on shrinkwrapping until it works as well as its users expect it to. This is the best means I can think of to avoid the kind of bitrot you describe.

That said, I'm going to close this issue, because I don't think it's in the community's best interests to change the CLI's default behavior, for the reasons I've described. Thanks for your time, and I hope you find my explanation reasonable, even if you disagree with my conclusions.

**Comment by taoeffect** [comment]
Let me see if I understood what you said, from what I can tell you gave one or two reasons and that's:

- make it easier than not for typical users to pick up bug fixes and security patches more easily than not

That does not seem to hold much water though, does it?

Who is the "user" in this case? There are two users I'm aware of:

1. Developers who install modules/frameworks for their app to ship with
2. End users who install nodejs apps and tool

- For case (1), it is the developer's responsibility to keep track of security and bug fixes for their app's dependencies, and release an update as appropriate. The current default of `^` can help fix bugs, sure, but if a developer notices a dependency is buggy they will notice it immediately and take appropriate action. The bugs that `^` is intended to fix are ones they likely did not run into because their app didn't call that buggy code. On the other hand, `^` *introduces* **new bugs** into NodeJS apps that would otherwise work.
- For case (2), apps that would otherwise be working perfectly fine, get broken down the line depending on when the user installs it. No other app/tool distribution system works this way (except perhaps Ruby gems). `apt` doesn't behave this way, and none of the App Stores out there behave this way (unless you count OS upgrades).

@othiym23 Would you consider leaving this issue open to at least allow time for discussion? The issue was open for a mere 14 minutes. :-\

**Comment by othiym23** [comment]
This issue is one that's been raised many times in the past, with the same resolution each time. Also, as I said, npm's use of semver is central to its design and purpose. This is one of the main areas in which npm's design is opinionated, and that isn't going to change.
