### ISSUE TITLE
1.x and 1.0.x will use root's dependence version if matched instead of try to get the maximal version from registry?

### ISSUE THREAD

**Issue by dead-horse** [npm/npm#11887]
assume we have three packages(a, b and c) 

package a:

``` json
{
  "name": "a",
  "dependencies": {
    "c": "1.0.0",
    "b": "1.0.0"
  }
}
```

package b:

``` json
{
  "name": "b",
  "dependencies": {
    "c": "1.0.x"
  }
}
```

and package c has tow versions: `1.0.0` and `1.0.1`.

when we install `a`, `a` and `b` will both use `c@1.0.0`, is this by designed? `1.0.x` means use the maximal version match `1.0.x` from installed(if we already installed). `~1.0.0` means use the maximal version match `~1.0.0` from registry(even if we installed a smaller version)?

**Comment by dead-horse** [comment]
seems like there is no difference between `~1.0.0` and `1.0.x`, they all worked like what I described before. the question is __does this behavior designed to be__? for we can control the sub dependencies' version in the root `package.json` ?

**Comment by dead-horse** [comment]
ping @othiym23 @iarna

**Comment by shaoshuai0102** [comment]
It seems likes a bug. I think version requirements should be satisfied independently, since npm itself designed the isolated node_modules mechanism for each package.

**Comment by iarna** [comment]
You are correct, there's no difference between `~1.0.0` and `1.0.x`. I would hasten note, however, that there _is_ a difference between ~1.0.1` and `1.0.x`. the `x` means match any number here. By contrast, the `~` prefix says "match any patch version greater than or equal to the one I specified".

This is all by design.

@dead-horse I don't understand the following, can you try rewording it?
> for we can control the sub dependencies' version in the root package.json ?

@shaoshuai0102
> I think version requirements should be satisfied independently, since npm itself designed the isolated node_modules mechanism for each package.

`node_modules` for each package are not isolated. Every module looks in itself and in modules above itself in the tree. It has always been the case that if you had a version of a module installed at the top level that deeper modules required that they'd use the top level version. It only does this when you've indicated via semver that you can work with that version. With npm@3 this happens even more often due to the mostly-flat nature of its `node_modules` folder.

**Comment by dead-horse** [comment]
sorry for my poor english.

@iarna as I understand, there have tow different way to install modules from registry with semver.

1. always request the registry to get the maximal version that satisfied the range.
2. before request the registry, if there is already a version in local satisfied the range, `npm` won't try to request the registry and use the local module.

for example, if we have a dependencies like:

```js
// package a
{
  dependencies: {
    b: '1.0.0',
    c: '1.0.0'
  }
}

// package b
{
  dependencies: {
    'c' : '~1.0.0'
  }
}
```

and package `c` has tow versions: `1.0.0`, `1.0.1`. 

if we use the first way to install package `a`, the result will be:

```
a/node_modules/c@1.0.0
a/node_modules/b@1.0.0
a/node_modules/b/node_modules/c@1.0.1
```

and the second will resulted:

```
a/node_modules/c@1.0.0
a/node_modules/b@1.0.0
```

and `npm` choose the second?

If `c@1.0.1` fixed an important bug for `b`, and package `b`'s maintainer won't upgrade the dependencies because `~1.0.0` include all these bug fix. But npm's behaviour break this, ___npm don't follow the semver___. Any specific reason for npm to choose the second implementation?

**Comment by shaoshuai0102** [comment]
@iarna I totally understand what you are saying, and this design came out according this distinction between `1.0.x` and `~1.0.0`.

My opinion is slightly different. When we specifying whether `1.0.x` or `~1.0.0`, we actually are "talking" to the npm registry, not to the locally installed npm client. Since as an package owner, I do not know how my package is used , or where it's installed.

So it is this difference that really makes @dead-horse 's concern happen.
