### ISSUE TITLE
Unable to install Volo

### ISSUE THREAD

**Issue by DisonDavis** [npm/npm#11907]
Hi,

I am unable to install Volo using npm install -g volo command. I have installed node.js 
node vesion
![nodeerror](https://cloud.githubusercontent.com/assets/17847845/13773440/3df70066-eabf-11e5-9b5b-108fb74f151b.png)
: 4.4.0
npm version: 2.14.20

Thanks & Regards,
Dison Davis

**Comment by zkat** [comment]
Hey!

In order to use the main npm registry at registry.npmjs.org, you need to have access to that URL. getaddrinfo errors like this one tend to be because of proxy issues because of users behind corporate firewalls. You can [configure a proxy for npm to use](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/) and see if that helps.

**Comment by DisonDavis** [comment]
Thanks for the reply.
