### ISSUE TITLE
Please help users move their dependencies forward

### ISSUE THREAD

**Issue by ronkorving** [npm/npm#11901]
Just a simple paste from an `npm install` run on my project:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

Here's my problem. None of these modules are required directly by my project. They're some dependency's sub-(sub-sub-)dependency. But NPM doesn't tell me which. So I'm gonna have a hard time trying to figure out which module to make a pull request to in order to get their dependencies updated. If the output would improve, that could save me a lot of time.

**Comment by finnp** [comment]
Just wanted to create another issue about this :smile:  This is generally a problem about warnings.

There is already at least one duplicate issue: https://github.com/npm/npm/issues/10438

**Comment by othiym23** [comment]
You're right: only warning messages that are actionable for developers working on the current project should be printed (as warnings) by default. Right now, the architecture of the part of the install and listing code that reads and evaluates the package tree is such that these kinds of warnings have to be filtered out on a case-by-case basis; a changed architecture that puts the warnings on the node for the package that has the problem would make it much easier to filter out non-actionable issues, or at least print them out at `info` or `debug` level, so that they don't clutter up the install output by default (when the default logging level is `warn`).

This is something that the team will probably deal with as part of a more comprehensive UX audit for the CLI. It's clear to me that npm has accreted a fair number of opinionated bits about how it interacts with its users that are awkward in many cases (or that work for UNIX and not Windows, or vice versa). The team is going to try to at least perform the audit in 2016, even if we aren't able to get all of the results implemented for a while. Thanks for your time!

**Comment by iamstarkov** [comment]
@othiym23 can i try to fix it?

**Comment by iarna** [comment]
@iamstarkov Absolutely!

**Comment by kevinSuttle** [comment]
Even the peerDeps warning as a starting ux would be nice:

```bash
npm WARN @watson-iot/platform-ui-primitives@0.0.7 requires a peer of npm-check-updates@^2.6.5 but none was installed.
```

**Comment by boneskull** [comment]
This is somewhat tangential, so excuse me if it's the wrong issue.

I've seen this happen quite a few times with Mocha, and elsewhere:

- Package *A* at version *X* is marked deprecated by its maintainer(s).
- Users of package *B*, which depends on *A* at version *X*, see a warning when installing package *B*.
- Helpful users of package *B* create multiple, duplicate issues notifying maintainer(s) of package *B* of the deprecation.  Issues are closed as duplicates, but keep getting created, since searching on GitHub will only show "open" issues by default.
- Helpful users of package *B* may also create multiple PRs which upgrade the *A* dependency to a not-deprecated verison *Y*.  These upgrades may or may not pass a local `npm test`, but will ultimately fail CI, insofar as a PR can run the entire suite (hint: [it often can't](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions)).
- Maintainers of package *B* must continually close issues and PRs and kindly ask users to do search good.

Why does this happen?  Many users *cannot tolerate warnings* upon `npm install`.  I am not a psychologist and cannot tell you why this is.  Ultimately, the intolerance creates overhead for package maintainers--or at least those whose packages have dependencies.

This is a complex issue; `npm` only plays a role in it.  If:

1. package *A*'s maintainer didn't deprecate version *X*, or
2. `npm`'s default behavior didn't warn users about deprecations, or
3. a full CI build or local facsimilie for a PR was *safe*, or
4. GitHub didn't have questionable defaults when searching issues

...maybe--just *maybe*--it wouldn't be a problem.  If *one item* can be struck from the above list, it would go far to address the issue.

Now, what @othiym23 wrote sounded good:

> only warning messages that are actionable for developers working on the current project should be printed (as warnings) by default.

That sounds close enough to the second list item above.  This would be super, *super*, **super** helpful.  👍
