### ISSUE TITLE
`npm ls` (list) sometimes overwrites package devDependencies info with linked dep's

### ISSUE THREAD

**Issue by jmm** [npm/npm#11911]
Say you have:
- an app called `app`
- `app` has a devDep on `dev-dep@1.0.0`
- `app` depends on `local-dep` via `npm link` or otherwise via symlink
- `local-dep` has a devDep on `dev-dep@2.0.0`

In some cases `npm ls` (in `app`'s root dir) will display the info for `local-dep`'s dependency on `dev-dep` instead of `app`'s. It's non-deterministic in the sense that it depends on the name of the linked package (e.g. results may be different if it's `a-local-dep` vs `z-local-dep`). If it comes after the name of the main package in the sort implemented by `npm`, then the linked package's devDep information will overwrite the main package's in the output.

With `node@5.6.0`, `npm@3.8.1`, on Ubuntu 12.

[Minimal repro](https://github.com/jmm/npm-ls-linked-dep-dev-dep-overwrite-repro).

Key action is happening here:
- [mutate-into-logical-tree.js#L27-L35](https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/install/mutate-into-logical-tree.js#L27-L35)
- [mutate-into-logical-tree.js#L71](https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib/install/mutate-into-logical-tree.js#L71)

**Comment by schmod** [comment]
I'm not sure if this is the same issue, but I've encountered similarly-spurious behavior with `npm ls`, linked packages, and devDependencies.

In particular, it seems like `npm ls` will *ALWAYS* show any installed devDependencies of a linked package in your tree.

So, if you have something like this:

```
pkg
├── async@2.0.0 (symlink)
└── underscore@1.6.0 (DEP)
```

```
$ (cd ../async && npm install --prod)
$ npm install
$ npm ls

us-link@1.0.0 /Users/schmod/source/us-link
├─┬ async@2.0.0-rc.5 -> /Users/schmod/npm/lib/node_modules/async
│ └── lodash@4.13.1
└── underscore@1.6.0
```

This seems fairly reasonable.  I personally don't think that I should be seeing the transitive dependencies of async, but this isn't exactly _unexpected_ either.  

---

I wonder what happens if I install `async`'s devDeps?

```
$ (cd ../async && npm install)
$ npm ls

us-link@1.0.0 /Users/schmod/source/us-link
├─┬ async@2.0.0-rc.5 -> /Users/schmod/source/async
│ ├── async@1.5.2 extraneous
│ ├─┬ babel-cli@6.9.0
│ │ ├─┬ babel-polyfill@6.9.0
│ │ │ └── babel-regenerator-runtime@6.5.0
│ │ ├─┬ bin-version-check@2.1.0
│ │ │ ├─┬ bin-version@1.0.4
│ │ │ │ └─┬ find-versions@1.2.1
│ │ │ │   ├── array-uniq@1.0.2
│ │ │ │   ├─┬ meow@3.7.0
│ │ │ │   │ ├── camelcase-keys@2.1.0
│ │ │ │   │ ├─┬ loud-rejection@1.3.0
│ │ │ │   │ │ └── array-find-index@1.0.1
│ │ │ │   │ ├── map-obj@1.0.1
│ │ │ │   │ ├─┬ normalize-package-data@2.3.5
│ │ │ │   │ │ ├── hosted-git-info@2.1.5
│ │ │ │   │ │ ├── is-builtin-module@1.0.0
│ │ │ │   │ │ └─┬ validate-npm-package-license@3.0.1
npm ERR! extraneous: async@1.5.2 /Users/schmod/source/us-link/node_modules/async/node_modules/async
npm ERR! missing: async@^1.5.2, required by form-data@1.0.0-rc4
npm ERR! missing: async@1.x, required by istanbul@0.3.22
npm ERR! missing: async@^1.4.0, required by handlebars@4.0.5
rect@1.0.2
│ │ │ │   │ │   │ └── spdx-license-ids@1.2.1
│ │ │ │   │ │   └─┬ spdx-expression-parse@1.0.2
│ │ │ │   │ │     └── spdx-exceptions@1.0.4
.... some more tree stuff....
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@1.0.0-rc4
│ │ │ │ └── UNMET DEPENDENCY async@^1.5.2
│ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ ├─┬ is-my-json-valid@2.13.1
... and this goes on for quite some time...
```

Hooboy.

Not only am I seeing `async`'s devDeps (which might be understandable, given a sufficiently-pedantic vision of what `npm ls` is meant to do), but the tree is WRONG, particularly having a lot of trouble with cyclical dependencies.

---

What if I only `ls` my prod deps?
```
$ npm ls --prod
[ same thing as above]
```

Nope.  Prints the same thing as above.  Here, even an obnoxiously-pedantic interpretation of what `npm ls` does should consider `async`'s devDependencies to be extraneous.  [ Currently, `npm ls` marks extraneous dependencies, and does not traverse/list their children ]

---

Maybe `async` didn't install correctly.

```
$ (cd ../async && npm ls)  
async@2.0.0-rc.5 /Users/schmod/source/async
├─┬ babel-cli@6.9.0
│ ├─┬ babel-polyfill@6.9.0
[...lots more output...]
```

Also nope.  This prints a big tree, but it's the correct one for `async`, and `npm ls` exits cleanly without errors.

---

What if I only look at the root-level dependencies?
```
$ npm ls --depth=0

# nope.  still weird.

us-link@1.0.0 /Users/schmod/source/us-link
├── async@2.0.0-rc.5 -> /Users/schmod/source/async
├── babel-core@6.9.0
├── babel-plugin-transform-es2015-modules-commonjs@6.8.0
├── bluebird@2.10.2
├── karma@0.13.22
├── rimraf@2.5.2
├── semver@4.3.6
└── underscore@1.6.0

npm ERR! extraneous: async@1.5.2 /Users/schmod/source/us-link/node_modules/async/node_modules/async
npm ERR! missing: async@^1.5.2, required by form-data@1.0.0-rc4
npm ERR! missing: async@1.x, required by istanbul@0.3.22
npm ERR! missing: async@^1.4.0, required by handlebars@4.0.5
```

wat.

```
$ tree
.
├── node_modules
│   ├── async -> ../../../npm/lib/node_modules/async
│   └── underscore
└── package.json
```

`npm ls --depth=0` is somehow gobbling up `async`'s root-level dependencies. 

---

Wait.   **Are** these `async`'s root-level dependencies?  

```
async@2.0.0-rc.5 /Users/schmod/source/async
├── babel-cli@6.9.0
├── babel-core@6.9.0
├── babel-plugin-add-module-exports@0.1.4
├── babel-plugin-transform-es2015-modules-commonjs@6.8.0
├── babel-preset-es2015@6.9.0
├── babelify@7.3.0
├── benchmark@2.1.0 (git://github.com/bestiejs/benchmark.js.git#3ce818ca5392e5aca325312f8d0c51801ae95bc7)
├── bluebird@2.10.2
├── chai@3.5.0
├── coveralls@2.11.9
├── es6-promise@2.3.0
├── fs-extra@0.26.7
├── jscs@1.13.1
├── jscs-jsdoc@1.3.2
├── jshint@2.8.0
├── karma@0.13.22
├── karma-browserify@4.4.2
├── karma-firefox-launcher@0.1.7
├── karma-mocha@0.2.2
├── karma-mocha-reporter@1.3.0
├── lodash@4.13.1
├── lodash-es@4.13.1
├── mocha@2.5.3
├── native-promise-only@0.8.1
├── nyc@2.4.0
├── recursive-readdir@1.3.0
├── rimraf@2.5.2
├── rollup@0.25.8
.0
├── rollup-plugin-npm@1.3.0
├── rsvp@3.2.1
├── semver@4.3.6
├── uglify-js@2.4.24
└── yargs@3.9.1
```

Hahahahaha, nope.  This is different too.

Also, `.0` has crashed our party for some reason.  

---

Given that `npm link` has led to other bugs (ie. #10343), and similarly confusing behaviors, I think that NPM should start treating linked packages the same way that we treat extraneous packages, and _leave them alone_.

`npm ls` shouldn't traverse linked packages; `npm install` and `npm update` shouldn't try to do anything with the linked package's dependencies.  `npm shrinkwrap` is more complicated, but we can probably treat that as a special case.

This seems like it would be fine for most development workflows.  The current behavior doesn't seem like it would have much practical application, _even if it worked_.
