### ISSUE TITLE
Need links to reference LTS branches

### ISSUE THREAD

**Issue by watilde** [npm/npm#11927]
Currently there are three different version of npm are live and two of them are in LTS branch.
+ v1.4.x: https://github.com/npm/npm/tree/1.4.x
+ v2.x: https://github.com/npm/npm/tree/2.x
+ v3.x: master branch

To check some commits/updates in LTS branches, it's not easy to find the exactly branch because there are too many branches here and there might be no link on any docs. How do you think have a link to reference LTS branches?
https://github.com/npm/npm/branches

**Comment by othiym23** [comment]
There are only two active lines of development, `master` and `2.x`, both of which are linked from the [LTS policy page](https://github.com/npm/npm/wiki/LTS). `npm@1.4` is no longer supported or under development – the `dist-tags` pointing to `npm@1` are a convenience for the Node.js Build WG, which is in the process of updating Node 0.10 to include `npm@2`.

I'm a little hesitant to curate the list of branches too much, because a lot of what's on the branches page is works in progress, but we have discussed renaming `2.x` to `lts` – would that help?

**Comment by watilde** [comment]
Thanks a lot for your quick response! Now I can find the branch easily on the wiki. Also, this is really helpful! If it doesn't affect anything, let me plus one.
> renaming `2.x` to `lts`
