### ISSUE TITLE
silly lockFile 24130cfd-phonegap-latest phonegap@latest

### ISSUE THREAD

**Issue by Mounika-Marri** [npm/npm#11989]
HI,
I have tried installing Phonegap using CLI and i was getting Darwin error for the command "sudo npm install -g phonegap@latest" 

in the npm-debug.log file , it shows the below.

"silly lockFile 24130cfd-phonegap-latest phonegap@latest"

Kind request to help me in overcoming the same.

Thanks,

Mounika M

**Comment by KenanY** [comment]
Hello @Mounika-Marri! Is that the only line in the entire log file?

**Comment by othiym23** [comment]
As @KenanY is implying, @Mounika-Marri, the line you pasted is only diagnostic output that doesn't indicate an error or bug. If you have the whole output in your terminal, cut and paste it here. Even better, if an `npm-debug.log` file is left behind, upload that.

If there's no `npm-debug.log` because npm has hung, you might want to try [updating npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). Over the last few weeks we've landed some changes that should make it easier to install large, complicated packages like Phonegap over imperfect network connections.

**Comment by KenanY** [comment]
@Mounika-Marri Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
