### ISSUE TITLE
"npm install "fail after finish installing bootstrap.

### ISSUE THREAD

**Issue by HanYif** [npm/npm#11997]
![lu4dy qrc_4 e3570x gg](https://cloud.githubusercontent.com/assets/13132465/13940424/3ce03072-f018-11e5-9ec0-de1be0663d75.png)

**Comment by sleepdeprivation** [comment]
This looks very much due to your own system config.
There are repeated references to your CAfile.
On that note, information about your configuration (eg what is in "bootstrap", what version, where did you get it, etc) would be helpful.
Was anyone able to replicate this?
I'm new here, so someone correct me if I'm doing it wrong.
