### ISSUE TITLE
npm upgrade fails on optional dependencies

### ISSUE THREAD

**Issue by MarshallOfSound** [npm/npm#11992]
When running `npm install` with `optionalDependencies` the install will succeed if any optionalDeps fail.  This is expected behavior, however if after a few weeks you want to update your dependencies and you run `npm upgrade` you won't be able to if any optional dependency fails.

This seems very counter intuitive, the behavior I would expect would be for `npm upgrade` to do the same thing as `npm install` and ignore failing optional dependencies

**Comment by iarna** [comment]
Agreed, that's definitely not right. 

For when someone goes to fix this:

This is happening because of how `update`/`upgrade` is implemented– it runs `npm outdated` and passes that output to `npm install`. 

`npm install` ordinarily won't count an optional dep failure as a fatal error, EXCEPT if you explicitly asked for it on the command line, eg, if you added `foobar` as an optional dep and then later run `npm install foobar` we'll explode because you explicitly were trying to install IT, not just the deps of the current module.

The problem comes in because of how `npm update` calls `npm install`, `npm install` thinks they were passed in directly by the user and uses the wrong semantics.

To solve this, I'd like to see `npm update` rewritten to not use `npm outdated` and instead just build directly on the underlying class that `npm install` is built on, using some (to be determined) hook to look for more recent versions of modules at whatever depth was specified.

**Comment by asyncanup** [comment]
Is a fix expected for this anytime soon?

**Comment by dcposch** [comment]
I just ran into this. 

This bug seems pretty bad. It means there's no easy reliable way to bring your dependencies up to date short of `rm -rf node_modules && npm install`, which of course is slow.

In practice, many Node.js CI setups, deployment and packaging scripts I've seen do exactly that -- install everything from scratch on every run -- but they really shouldn't have to.

Let us know if there's a fix coming soon.

CC @feross
