### ISSUE TITLE
`npm install` fails with Z_BUF_ERROR when using shrinkwrap

### ISSUE THREAD

**Issue by oconnor663** [npm/npm#11993]
Apologies in advance for not having a minimal repro for this. When we run `npm install` in the Keybase repo, we had been getting this error intermittently:

```
npm ERR! tar.unpack unzip error /tmp/npm-28814-d055d95c/registry.npmjs.org/fsevents/-/fsevents-1.0.8.tgz
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
```

As of today, that error happens 100% of the time, though last week it might've been more like 50%. Removing `npm-shrinkwrap.json` or running `npm install --no-shrinkwrap` seems to fix the problem, though we would prefer to keep using shrinkwrap. (`npm update` also seems to work. I suppose that has the same effect as `--no-shrinkwrap`?) Here are the exact repro steps:

```
git clone https://github.com/keybase/client
cd client/desktop

# optional, prevents some global installs in case the following command actually succeeds
export KEYBASE_SKIP_DEV_TOOLS=1

npm install
```

(We did try `npm cache clean` as suggested on [other tickets](https://github.com/npm/npm/issues/11674), but that hasn't helped. So far repro'd on Arch and Ubuntu, but not on OSX.)

**Comment by oconnor663** [comment]
Followup: It looks like the issue might be tied to an old version of one of our dependencies. Not sure which one, but updating our shrinkwrap file (and then continuing to use it) also seems to fix the issue.

**Comment by zkat** [comment]
Hey! And thanks for the follow-up!

I looked into this a bit, and I don't have much else to say beyond how this error is almost always some kind of bad cache issue that we really haven't quite gotten to the core of -- I tried downloading the specific tarball that was failing (for fsevents 1.0.8) and was able to untar and install it on both windows and ubuntu 14.04 (it's been a while since I ran Arch, so I don't have that handy :<).

So I guess tl;dr is there's not much here that's actionable, but it's nice you found a workaround for this specific case. Hopefully in the future we'll have found all the various little gaps where tarballs somehow end up incomplete in our cache, which already shouldn't be happening.

I'm going to mark this as a bug and leave it open because I'm not seeing any other open bugs that refer to this recurring Z_BUF_ERROR problem, for the sake of tracking it for the future, even though it's particularly hard to reproduce and there might be more than one way about it.

**Comment by oconnor663** [comment]
I think we ruled out cache issues by running `npm cache clean` a lot and also by repro'ing inside of docker containers, unless maybe a cache issue early in `npm install` is breaking something that happens later in the same command.

I confirmed that the `/tmp/npm-.../registry.npmjs.org/...` directories in those errors contained truncated tarballs, like the errors suggested. Something responsible for fetching those tarballs must be getting killed early?

We have a pretty consistent repro in our project history, so if you want us to try anything, let me know.

**Comment by zkat** [comment]
Excellent, thank you! I'm not sure this is an issue we'll tackle right away, but we'll definitely keep this open. And I'll link here to https://github.com/keybase/client/commit/38bbc63ec6912d76736806e2b2a728b7932096cc as the commit that helped y'all fix it. :)

**Comment by oconnor663** [comment]
Best of luck with this one :-D

**Comment by rdubigny** [comment]
Hi ! We just got the same exact issue with node 5.9.0 and node 5.9.1 and node 5.10.1.

Our workaround is to use `npm install --no-shrinkwrap && npm install` but we lose precious amount of time during deployment phase.

Maybe this issue may be left opened.

**Comment by zkat** [comment]
@rdubigny the issue is still open. It's the related one that got closed (https://github.com/npm/npm/issues/12026)

**Comment by gabriel** [comment]
Doesn't `npm install --no-shrinkwrap && npm install` produce different node_modules?

**Comment by Odrin** [comment]
Same issue on Windows 7, node 6.3.0, npm 3.10.5 and I'm under corporate proxy.
"npm cache clean" and run cmd as admin hasn't helped.
--no-shrinkwrap worked for me.

**Comment by michaelneale** [comment]
I see this often with empty cache (more often with empty, than with full). Probably 20% of the time running with an empty cache.

**Comment by adamchainz** [comment]
We have had this on node 5.11, 6.6 and 6.7 (plus whichever `npm` is bundled in with them, 3.10.3 is latest). It happens randomly on a full cache with only some dependencies. They seem to be the larger ones of several MiB in size.

One dependency we had this for was `npm` itself, via `npm-check-updates`, which depends on npm 3.10.6, which is 3MiB. We fixed that by removing `npm-check-updates`, however it still recurs for several other dependencies, e.g. `weinre` (2MiB) and `socket.io-parser` (1.2MiB). It's probably around 20% of the time, as noted with a full cache.

**Comment by adamchainz** [comment]
Here's some more log info I have grabbed from a build that failed today:

1. the package that failed was `babel-eslint` with this error message:

```
npm ERR! tar.unpack unzip error /tmp/npm-4374-1f29a898/registry.npmjs.org/babel-eslint/-/babel-eslint-4.0.5.tgz
npm ERR! tar.unpack untar error /tmp/npm-4374-1f29a898/registry.npmjs.org/babel-eslint/-/babel-eslint-4.0.5.tgz
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/yplan/npm_env_portal/npm-debug.log
```

2. The tail of `npm-debug.log`:

```
40949 silly rollbackFailedOptional Starting
40950 silly rollbackFailedOptional Finishing
40951 silly runTopLevelLifecycles Starting
40952 silly runTopLevelLifecycles Finishing
40953 silly install printInstalled
40954 verbose stack Error: unexpected end of file
40954 verbose stack     at Zlib._handle.onerror (zlib.js:370:17)
40955 verbose cwd /opt/yplan/npm_env_portal
40956 error Linux 3.13.0-96-generic
40957 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
40958 error node v6.7.0
40959 error npm  v3.10.3
40960 error code Z_BUF_ERROR
40961 error errno -5
40962 error unexpected end of file
40963 error If you need help, you may report this error at:
40963 error     <https://github.com/npm/npm/issues>
40964 verbose exit [ -5, true ]
```

3. We had 13265 bytes of the `.tgz` file:

```
# ls -al /tmp/npm-4374-1f29a898/registry.npmjs.org/babel-eslint/-/babel-eslint-4.0.5.tgz
-rw-r--r-- 1 backend backend 13265 Oct  3 16:27 /tmp/npm-4374-1f29a898/registry.npmjs.org/babel-eslint/-/babel-eslint-4.0.5.tgz
```

4. The full file is 14440 bytes long:

```
# curl registry.npmjs.org/babel-eslint/-/babel-eslint-4.0.5.tgz | wc -c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14440  100 14440    0     0   407k      0 --:--:-- --:--:-- --:--:--  414k
14440
```

5. The user that runs the build has the exact full file cached:

```
# ls -al /home/backend/.npm/babel-eslint/4.0.5/package.tgz
-rw-r--r-- 1 backend backend 14440 Oct  3 03:43 /home/backend/.npm/babel-eslint/4.0.5/package.tgz
# md5sum /home/backend/.npm/babel-eslint/4.0.5/package.tgz /tmp/babel-eslint-4.0.5.tgz
a365f7d857eac3da5cc2e8cbbde4c64f  /home/backend/.npm/babel-eslint/4.0.5/package.tgz
a365f7d857eac3da5cc2e8cbbde4c64f  /tmp/babel-eslint-4.0.5.tgz
```

6. The broken file does just differ at the tail end. However it doesn't look like a pure concatenation, as it ends with the two bytes 007a which aren't in the original file:

```
# diff --unified <(hexdump /tmp/babel-eslint-4.0.5.tgz) <(hexdump /tmp/npm-4374-1f29a898/registry.npmjs.org/babel-eslint/-/babel-eslint-4.0.5.tgz )
--- /dev/fd/63	2016-10-03 16:43:15.198051310 +0000
+++ /dev/fd/62	2016-10-03 16:43:15.198051310 +0000
@@ -827,78 +827,5 @@
 00033a0 78c9 99bf 780b c5c6 ed53 7896 971e 762c
 00033b0 6e61 d92a b093 77a7 0e65 40f1 570c ef02
 00033c0 6210 f537 4758 f854 e4ac 013c e574 79c5
-00033d0 ab7a b617 fa93 8eab 5837 3864 eab4 9fa8
-00033e0 b3e2 0b20 b741 fbc0 b397 7538 03fa 4598
-00033f0 d0ef f7cc e5f8 9fdd 34be 9fde 2cd9 f017
-0003400 62e3 4c94 ab02 fc62 d0dd 3819 f17e cbeb
-0003410 f222 75bc 9ecd 29dc 081c f2c5 430c 8dc3
-0003420 a4c1 9615 48c0 2758 fb14 ee93 5b9f b8f8
-0003430 11f9 6271 a9c5 7e9e 2b95 d3e0 4856 bc42
-0003440 ef86 a80b 9627 c96a d5c3 f014 4ef7 6241
-0003450 23e6 940a 4f68 c229 75e9 e8a5 3f45 c5af
-0003460 76cf 5e95 b847 5b62 5b5b 68f4 fb05 07e1
-0003470 ad76 557e 15d9 ca7b 4fae 4b97 ba56 8eeb
-0003480 fb92 93b1 72b6 d277 9756 171f 83ed 6315
-0003490 b8d8 4baf ce3d 2775 abb5 4553 ab9d a5d3
-00034a0 7ae2 7140 ef13 5917 c23c 8005 3bae 0dac
-00034b0 1972 b57f d7e9 24fa ff1f 2b9b 9ec8 1424
-00034c0 c9a0 54b4 a82a 6329 72ca 7f8c a770 c610
-00034d0 22aa f93e 7d94 8d86 cd53 8985 f85b 73de
-00034e0 06ba 65ea 211d 5ddd 1924 86d5 7449 cb5a
-00034f0 ec96 97e6 774c 0e95 3218 7021 45ef f19a
-0003500 a09f f304 0b68 0d0b 17ca 0237 1a65 9294
-0003510 ebbe 9789 8c0a b9e1 81bf ca21 f0d4 4b9a
-0003520 4071 13dc a596 1f64 a37f a2a8 2e9a b34b
-0003530 3df7 7212 fdee a252 f497 6aa4 7c0f 22fc
-0003540 7cdf ff3a dc4b dcb7 52cf 6fe3 a0b5 7c82
-0003550 aa0f 2b40 b3d8 fcaa ea0f 8a9d 1519 96ff
-0003560 a9ee 6d92 3aa3 caa3 2894 c72e 55ce fc0c
-0003570 6d6b e38f 7220 70ff 7b6e 77bd 897e c4e4
-0003580 a083 6da7 ef29 547d 53de 1a0f dbfa 6d5f
-0003590 6670 3290 e33d 56fe df00 21cc 529d 5d37
-00035a0 986e 512e 09c9 85cc a7a0 9983 4cb1 b3fc
-00035b0 7365 3b02 e277 e466 1a2c ef35 471b e74c
-00035c0 bc08 47e3 c31e 0de8 10fd 4400 0002 0cbe
-00035d0 9ae1 b592 7cb0 565d 054b fed1 666f b430
-00035e0 002c 793a 9af1 dbff 4bc4 330a eac0 1a76
-00035f0 adc5 a963 0fff 9bc8 6607 4307 a4b6 f515
-0003600 2347 965c 68c5 3586 07b2 d968 c471 b086
-0003610 0dba 2f2d 2915 df10 a1c3 89c0 6ef9 b31c
-0003620 a7ec ec38 b5bc 2df9 18fc 70cd d443 3f9a
-0003630 61a2 03c1 b482 8987 7398 7b65 9ee3 3c63
-0003640 e5d1 fd39 3718 1113 68ec 1eac f27b fcd7
-0003650 e143 5079 420c dcf7 2df5 6f8f 91e6 27c9
-0003660 3c3c 4de6 75df 1ebc 25ec 2fe8 b577 bdb2
-0003670 27c0 ab7b 2b59 a04b 993b e5e6 a6b0 9386
-0003680 ce4c be42 2ca4 adcf 1702 f98f 991e 79bb
-0003690 c16d 6b17 3fa2 d019 a4c5 d1cf f54a a8b6
-00036a0 2b21 60bc e5bc b33b 2f42 57f0 7662 c169
-00036b0 325e 288f 0d92 2516 1cc3 4567 c7b4 59ed
-00036c0 55b1 5274 9194 7d89 f07c 8e88 3241 0ac2
-00036d0 0838 7a9b 93e0 311f 22a1 08b4 4bd0 f478
-00036e0 278c 6c1a e59e cdbb e0cc 8d22 5f8a 2bc4
-00036f0 271d 8a26 932d 6512 4c98 26cd cc3e 5a1e
-0003700 87ae 2c0c 1921 175a 1700 661e 7a30 b52c
-0003710 f90f 9f8c f42d ff2c 73dc c558 2ef2 ebad
-0003720 4ea8 2756 a32c f54b 66b2 9844 507a 1bc1
-0003730 6a03 009d e528 9374 d3e5 1a3c 482e 088a
-0003740 d338 001e 19bc 01c6 b7d4 c615 0703 75c3
-0003750 b40a 661d 8375 8e2f 7b86 b437 a76c c51e
-0003760 00d7 d1ad c908 56f6 cd27 fa61 97a1 3e95
-0003770 99c7 194e abbd 6b0e 71cf 1614 56fa 4d78
-0003780 96af 608d 420b 541c a270 c73f 2404 f5fb
-0003790 ac8f 2dc2 1dd7 df40 128b b1af 9802 b5c9
-00037a0 eeac 7dfa aaf7 8c1e b366 903f 411e fa27
-00037b0 11ca 6d90 15d4 b912 ce27 7550 f0ea 3e53
-00037c0 00e7 15f1 e290 9a8f 07f0 e822 8cf1 e70a
-00037d0 5505 7b22 a7be 0965 1166 a682 9052 f8cd
-00037e0 99e3 a9e2 6ccc 757e 1313 d65f 7ceb b95e
-00037f0 d19c 0488 c0f1 318a 7421 f850 bd39 6c0c
-0003800 3313 3ca5 b7e1 4425 7a42 4450 36b2 822e
-0003810 c9a6 48b8 912a a79c 551f 45fe 2c63 8cfe
-0003820 82e5 b3c3 d4c8 1a2c a295 d121 b9e9 605a
-0003830 ace2 d3a4 61cd 32d1 1d16 ad0f 6aea bd33
-0003840 d5a5 77e7 de75 92d9 9519 4864 78f8 b3d0
-0003850 f0e0 9fff 7dbe 7dbe 7dbe 7dbe fe1e fff3
-0003860 9531 7967 3800 0001
-0003868
+00033d0 007a
+00033d1
```

7. Re-running the `npm install` command works.

It should also be noted our build process runs multiple `npm install`s in parallel in different folders for different `package.json` files 😄 

Hope this helps.

**Comment by mearns** [comment]
I've run into this same issue, happening sporadically when installing our package. The specific error is:

```
npm ERR! tar.unpack unzip error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/core-js/-/core-js-2.4.1.tgz
npm ERR! tar.unpack unzip error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/handlebars/-/handlebars-4.0.5.tgz
npm ERR! tar.unpack untar error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/core-js/-/core-js-2.4.1.tgz
npm ERR! tar.unpack untar error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/handlebars/-/handlebars-4.0.5.tgz
npm ERR! tar.unpack unzip error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/aws-sdk/-/aws-sdk-2.5.2.tgz
npm ERR! tar.unpack untar error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/aws-sdk/-/aws-sdk-2.5.2.tgz
npm ERR! tar.unpack unzip error /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/nodejs-binary-5.6.0/bin/node" "/usr/local/bin/npm" "install" "-global" "--registry" "http://artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/" "http://artifactory.nexus.commercehub.com/artifactory/one-platform-npm/chub-skullkid-web/-/chub-skullkid-web-%5BRELEASE%5D.tgz;env.opint1.current+=true"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

As shown in the error message, I'm using **npm v3.6.0** **node v5.6.0**. We're currently unable to update our versions because of third party dependencies. This is being run by chef on "Linux 3.13.0-24-generic #47-Ubuntu SMP x86_64".

I found the files in question, testing specifically `fsevent-1.0.14.tgz` from `/tmp`, and found that it in fact a corrupt gzip file:

```console
$ whoami
opdeployer
$ ls -l /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz
-rw-rw-r-- 1 root opdeployer 384472 Nov 15 20:23 /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz
$ gunzip -t /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz

gzip: /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz: unexpected end of file
$ echo $?
1
$ 
```

I checked the npm cache and found that fsevents is present there, but the copy in the cache is different than the one listed in the error message, and specifically it is a valid gzip:

```console
$ npm cache ls | grep fsevents
~/.npm/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/
~/.npm/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/.cache.json
~/.npm/fsevents/
~/.npm/fsevents/1.0.14/
~/.npm/fsevents/1.0.14/package.tgz
~/.npm/fsevents/1.0.14/package/
~/.npm/fsevents/1.0.14/package/package.json
$ ls -l ~/.npm/fsevents/1.0.14/package.tgz
-rw-rw-r-- 1 root opdeployer 1249539 Nov 15 19:21 /home/opdeployer/.npm/fsevents/1.0.14/package.tgz
$ gunzip -t ~/.npm/fsevents/1.0.14/package.tgz
$ echo $?
0
$ 
```

For clarity, here is the `ls -l` output for the two files, side by side:

```console
-rw-rw-r-- 1 root opdeployer 384472 Nov 15 20:23 /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz
-rw-rw-r-- 1 root opdeployer 1249539 Nov 15 19:21 /home/opdeployer/.npm/fsevents/1.0.14/package.tgz
```

Notice that the `/tmp` copy (the corrupt one) is only about a third of the size of the cached file, and the `/tmp` copy was also updated more recently than the cached version. I was able to verify that the corrupt copy in `/tmp` is simply the beginning of the cached version:

```console
$ head --bytes 384472 /home/opdeployer/.npm/fsevents/1.0.14/package.tgz | diff --binary - /tmp/npm-15675-395147c8/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/-/fsevents-1.0.14.tgz
$ echo $?
0
$ 
```

(note that 384472 is the filesize of the smaller `/tmp` copy).

I'm attaching a zip containing the npm-debug.log, though it appears to have been cut off at the beginning, I have no idea why, this is how I found it on the box. I'm also including the cached fsevents package (the valid one), and the file `~/.npm/artifactory.nexus.commercehub.com/artifactory/api/npm/npm-virtual/fsevents/.cache.json` (as `fsevents-cache.json`), which I saw in the output of `npm cache ls`, in case it's useful.

[npm-issue-11993-bmearns.zip](https://github.com/npm/npm/files/594894/npm-issue-11993-bmearns.zip)

**Comment by rosen-vladimirov** [comment]
Hey @zkat ,

I've received the same error and I've dig into it. Here are my findings, hopefully this will help you to understand what's going on. 

The issue is reproducible only when ALL of the below requirements are fulfilled:
 - version of npm is 3+ (if npm 2 is used everything works fine, no matter of other requirements)
 - package that you are trying to install has shrinkwrap at it's root level (works fine without it, no matter of other requirements)
 - the dependency that you are trying to install has a lot of dependencies and lots of them depend on a same version of one other dependency (in the example below it's npm 2.15.5)
 - npm is configured to work behind a proxy (in case the proxy configuration is removed, everything works)

` NOTE: Cleaning the cache does not have any effect on the behavior. `

On one of our build machines we are trying to install a fork of plugman (from github tarball). However every time we received errors:
```
npm ERR! tar.unpack unzip error /var/folders/mm/0hb5tnks4sgb1q49fn2197y40000gn/T/npm-33555-4af8b861/registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
npm ERR! tar.unpack untar error /var/folders/mm/0hb5tnks4sgb1q49fn2197y40000gn/T/npm-33555-4af8b861/registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.10.0.tgz
npm ERR! tar.unpack unzip error /var/folders/mm/0hb5tnks4sgb1q49fn2197y40000gn/T/npm-33555-4af8b861/registry.npmjs.org/npm/-/npm-2.15.5.tgz
npm ERR! tar.unpack untar error /var/folders/mm/0hb5tnks4sgb1q49fn2197y40000gn/T/npm-33555-4af8b861/registry.npmjs.org/npm/-/npm-2.15.5.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "--save" "https://github.com/Icenium/cordova-plugman/tarball/0fbac6e8a7826a5c0d91533fe041059778f5fc82"
npm ERR! node v5.5.0
npm ERR! npm  v3.10.9
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
```

Every single time for the same packages - npm 2.15.5 and cordova-app-hello-world-3.10.0.
So I've digged into npm code in order to check what's going on. I've checked the temp files in `/var` and they are not correct - they are just truncated. So I've modified the code in `npm/lib/cache/add-remote-tarball.js` in order to print some information when the tarball is downloaded from npm. I've added some logs on [this line](https://github.com/npm/npm/blob/v3.10.9/lib/cache/add-remote-tarball.js#L101) :
```JavaScript
tarball.on('finish', function () {
        if (u.indexOf("npm-2.15") !== -1) {
                console.log("### download npm 2.15 finish event: ", u, " shasum: ", shasum, "response.headers = ", response.headers);
                console.log("tmp = ", tmp, "ls -l = ");
                console.log(require("child_process").execSync("ls -l " + tmp).toString());
        }
```
So during the execution I received the following result:
```
### download npm 2.15 finish event:  https://registry.npmjs.org/npm/-/npm-2.15.5.tgz  shasum:  null response.headers =  { 'content-length': '2935085',
  'content-type': 'application/octet-stream',
  connection: 'keep-alive',
  'x-cache-hit': 'true',
  date: 'Wed, 16 Nov 2016 23:27:42 GMT' }
tmp =  /var/folders/mm/0hb5tnks4sgb1q49fn2197y40000gn/T/npm-33555-4af8b861/registry.npmjs.org/npm/-/npm-2.15.5.tgz ls -l =
-rw-r--r--  1 bdtest  staff  1163264 Nov 16 23:29 /var/folders/mm/0hb5tnks4sgb1q49fn2197y40000gn/T/npm-33555-4af8b861/registry.npmjs.org/npm/-/npm-2.15.5.tgz
```
As you can see response's content length is totally different from file's length.

It looks like the problem is with `fs-write-stream-atomic` method - it emits `finish` event when the package is not really downloaded.

Do you have any idea what might happen here?

**Comment by rosen-vladimirov** [comment]
ping @iarna as well. Any help on this case 😿

**Comment by Dru89** [comment]
fwiw, I've been struggling with this for a few hours and finally managed to make it work on our end.

For us, it was because we had the following scenarios (most likely do to cached packages):

- package A depends on package B
- package A resolves to the public registry
- package B resolves to the private registry

Even though we're using sinopia (and it should proxy package B back out to `registry.npmjs.org`), it seems that the proxying wasn't working in this case.  I'm not sure how we wound up with this sort of a dependency chain, but it was most likely through some packages already being cached.

I've found that the following scenarios worked:

- privately registered package depends on another privately registered package.
- publicly registered package depends on another publicly registered package.
- privately registered package depends on a publicly registered package.

But the _"publicly registered package depends on a privately registered package"_ case didn't work.  Changing the registries to both be *either* private *or* public worked, though.

**Comment by disujha** [comment]
Seems the issue continues.. `npm cache clean` does nothing... Following is the error code... Not sure if its Ionic or NPM issue
`npm WARN deprecated babili@0.1.2: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sayak\AppData\Roaming\npm-cache\_logs\2017-08-24T15_05_53_996Z-debug.log
`

**Comment by dru89** [comment]
@disujha Since shrinkwrap was overhauled into `package-lock.json` in `npm@5`, do you know if this problem is fixed for you in `npm@5`?

**Comment by grrowl** [comment]
For future reference: Node 8.9.0+ (and 9+) fix an issue where streams are terminated early in some scenarios. If you're getting this error upgrade to 8.9.

https://github.com/nodejs/node/issues/13391

**Comment by OClement** [comment]
I’m having this error a lot, seemingly randomly, but only on Jenkins. Restarting the build a second time will work 99% of the time

Using node 9.x (I don’t recall which exactly) and and npm 3.10.10

The whole build workspace is cleared before each builds, so I don’t think a cache clean would help? (Unless the cache is persisted elsewhere on Jenkins)

Also, we use Nexus as private repo;

Again, we don’t experience those issues *at all* on local dev machines (Mac OS, while Jenkins run on Ubuntu)

I’m pretty much out ideas about what to look for, so if anyone can shed some light on this, it’d be greatly appreciated

**Comment by dru89** [comment]
@OClement: That version of npm is old enough that I'd bet it's not supported.  (The LTS policy is "We don't have an LTS version." https://github.com/npm/npm/wiki/LTS)

You might want to upgrade to the latest 5.x to see if it works for you.

**Comment by OClement** [comment]
Yeah...

The thing is, last time I tried NPM 5 it was breaking our build because of an issue with `npm pack` or `npm publish` (cant recall which; I know the issue is/was logged somewhere as well)

Hopefully that problem has been solved since then
I’ll try 5.x tomorrow

Thanks
