### ISSUE TITLE
Error with npm while trying to install bootstrap

### ISSUE THREAD

**Issue by lgundala** [npm/npm#12013]
[node-debug_log.txt](https://github.com/npm/npm/files/185069/node-debug_log.txt)

**Comment by zkat** [comment]
Hi! It looks like you ran `npm i bootstrap` inside the bootstrap package. More likely, what you want is to change into your own project's directory, and run `npm i bootstrap` from there, as it says in [the documentation for `bootstrap`](https://www.npmjs.com/package/bootstrap#quick-start). Note that the bullet points in those instructions are not a set of instructions, but many different options. You should choose only one of them in order to install bootstrap!
