### ISSUE TITLE
registry.npmjs.org should be append only

### ISSUE THREAD

**Issue by majgis** [npm/npm#12028]
@seldo "This action puts the wider interests of the community of npm users at odds with the wishes of one author; we picked the needs of the many."

The only solution that makes npmjs.org a reliable and stable platform, is for package publishing to be append only.
 
If you wish to provide a courtesy to contributors, provide a short grace period, a week maybe, where they may unpublish.  
If you wish to provide a courtesy to package consumers, provide a method to avoid packages which are within the grace period.

registry.npmjs.org should offer stability over anarchy.  Those who are in favor of anarchy can publish and pull dependencies from github. An unstable platform is already provided by github.  The unique offering of registry.npmjs.org is stability.

**Comment by caseyhoward** [comment]
The unpublish command should be removed completely. There should be a different command that let's you give up ownership of a name but still keeps the tarballs around for all previous versions. How can anybody rely on NPM if you can unpublish modules?

**Comment by rtablada** [comment]
Another thing that may be possible is that things can only be unpublished within X amount of time.

For instance there have been times where I have bumped versions because global packages have had a minor bug when installed vs linked.

But after a few hours I think that the reliability of things being published and versioned is there for good.

**Comment by caseyhoward** [comment]
@rtablada I like that idea too. Maybe instead of being based by time it can be based off of number of installs. Or it could be a function of both.

**Comment by rtablada** [comment]
@caseyhoward I think number of installs would be hard to track and could lead to issues compared to time based. For instance let's say a module is published by a large company that installs it for CI across multiple boxes, that could exceed the threshold in a small amount of time.

**Comment by Fryie** [comment]
What are the legal implications of this? [This page](https://docs.npmjs.com/policies/open-source-terms) would suggest that you're within your rights to revoke npm's access to your code; if unpublish is to be removed, it might be necessary to change the terms and conditions in this matter? That you have to agree that what you upload to NPM will be essentially there forever? (It wouldn't matter in the present case, since the projects involved used a very permissive license, but in general.) But IANAL.
How do other package managers handle this?

**Comment by jamietre** [comment]
Whatever comes of the decision about unpublishing, I think it's a lot more important that once ownership of a package name is established, it can never be released, as the names of about 250 packages have been in the last 24 hours.

If a module becomes unpublished for any reason, the name should be deprecated, to avoid the possibility (indeed, likelihood) of a hostile takeover of the package.  Even a non-hostile takeover of a name with any kind of history will just be endlessly confusing.

I personally think that allowing unpublish for only some limited time period (a week seems reasonable) would solve this problem. There should be a clear channel for handling removal of packages by npm staff for special cases (e.g. copyright infringements), but otherwise, no unpublishing.

**Comment by download13** [comment]
Unpublish should definitely be removed. You can read some of the arguments against it here: #12017.

I didn't find any of them very convincing, but the most significant argument made by an npm maintainer seemed to be:

> @[othiym23](https://github.com/othiym23) That's one of the sources of strength for an open ecosystem like npm's: developers retain control over the things that they create.

On the other hand:
> @[seldo](https://twitter.com/seldo) Un-un-publishing is an unprecedented action that we're taking given the severity and widespread nature of breakage, and isn't done lightly.

What it kind of sounds like is: "unpublish is an important tool to make sure code creators retain control over their code, unless it becomes an inconvenience, then we'll just do whatever we want."

To be clear, I don't have a problem with the un-unpublish. The code is legally redistributable under it's license. My issue is one of priorities. If you want a place where everyone can retain control of their previously published code, make a code-hosting service with built-in DRM. npm is first and foremost a package manager. If it doesn't manage packages reliably people won't use it.

The unpublish command doesn't really seem to have a compelling use-case, whereas an immutable package store would ensure that your dependencies will never break (which should really be a basic feature of any package manager).

@camsaul already mentioned [Rust Cargo](http://doc.crates.io/crates-io.html#cargo-yank) in the other thread, but I think it bears repeating here because it's a great example of how to do things.

> **cargo yank**

> Occasions may arise where you publish a version of a crate that actually ends up being broken for one reason or another (syntax error, forgot to include a file, etc.). For situations such as this, Cargo supports a “yank” of a version of a crate.

> $ cargo yank --vers 1.0.1
> $ cargo yank --vers 1.0.1 --undo
> A yank does not delete any code. This feature is not intended for deleting accidentally uploaded secrets, for example. If that happens, you must reset those secrets immediately.

> The semantics of a yanked version are that no new dependencies can be created against that version, but all existing dependencies continue to work. One of the major goals of crates.io is to act as a permanent archive of crates that does not change over time, and allowing deletion of a version would go against this goal. Essentially a yank means that all projects with a Cargo.lock will not break, while any future Cargo.lock files generated will not list the yanked version.

**Comment by jamietre** [comment]
> If you want a place where everyone can retain control of their previously published code, make a code-hosting service with built-in DRM

We already have such a place - github. It's nearly as convenient to use git dependencies as npm already. A package registry needs to be a place you can have a very high degree of confidence in something you use being available in perpetuity for this ecosystem to function. If you don't like that, as a module author, then you should just not publish it.

Even the word "publish" implies that you've put it out there and can't take it back. If I publish a book, I can't change my mind a year later and go round up all the copies that are out there so nobody can read it again. (To the extent that there are still books, anyway).

**Comment by caseyhoward** [comment]
@rtablada Good point. Also when you first publish a package you get like 30 installs because of crawlers.

@jamietre Yep. That's exactly what "publish" means. Once you publish it, it is publicly available and you have to assume that the whole world has a copy of it. The cat is out of the bag.

If you accidentally committed private keys, oh well, that's what revoking keys is for. If you decide to un-publish it, someone could create a new repo with a new name and publish all the old versions. Now everyone in the world who depends on that module has to update their dependencies. A lot of extra work for no additional value.

Also, crawlers probably have a download a copy of your code anyway. It's dangerous to think that un-publishing eliminates any security issues. In fact, what if I wrote I a program that caches NPM and pointed my package manager to it? It would basically be doing what NPM should already be doing.

Unpublish isn't a word for a reason. The word unpublished exists and it means something has not yet been published. http://english.stackexchange.com/questions/2208/does-the-verb-unpublish-exist

**Comment by zkat** [comment]
Hey all, I know this is a pretty hot topic right now, but I'm going to close this as a duplicate of #12017. I am working under the assumption right now that there may be changes to some of how these bits of npm work.

**Comment by majgis** [comment]
That is fine, I looked for an alternative ticket and didn't find it.

**Comment by majgis** [comment]
...with the assumption that the other ticket is reopened ;-)

**Comment by zkat** [comment]
It won't be, for now. Stand by until then. :)
