### ISSUE TITLE
Unable to unpublish NPM package that we own

### ISSUE THREAD

**Issue by sasidhar** [npm/npm#12040]
When I am trying to unpublish an NPM package that I published (even using --force), it is giving 504 Gateway Timeout error.

Full log is here 

```
> npm ERR! registry error parsing json
> npm ERR! registry error parsing json
> npm ERR! registry error parsing json
> npm ERR! Linux 4.2.0-34-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "package-name@package-version"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> 
> npm ERR! Unexpected token <
> npm ERR! <html><body><h1>504 Gateway Time-out</h1>
> npm ERR! The server didn't respond in time.
> npm ERR! </body></html>
> npm ERR! 
> npm ERR! 
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /path/to/npm/debug/log/file
> 
```

**Comment by zkat** [comment]
Hi @sasidhar! We recently had a brief outage. Could you try now, or in another hour, and see if the problem persists?

If it does: Are you behind a firewall/proxy? Are you sure it's configured properly?

**Comment by sasidhar** [comment]
@zkat Thanks for the quick reply.

I tried just now and still i am facing the same issue.
I was able to unpublish a specific version, but not unpublish entire package.
I am trying with two pcakges. One is public and another one is private. Both having the same issue.
I am sure that I am not behind any Firewall/Proxy. I tried with three different ISPs.

I will try once again after an hour and update you.

**Comment by zkat** [comment]
Heya. I just checked with our registry team, and they're wondering if you could tell us what package(s) this issue involves -- we really shouldn't be returning 504s like this.

For the sake of due diligence:

1. Can you give me the output of `npm config get proxy` and `npm config get https-proxy`?
2. If the above both return null/undefined, could you either comment here again with the package names or, if you're uncomfortable making that public, sending an email to support@npmjs.com so we can move forward with figuring this out for you? :)

**Comment by sasidhar** [comment]
@zkat Both the given commands returning `null` from my machine.

I sent a mail to support@npmjs.com with the packages and the request number I got is : 3977

I just tried once again unpublishing both the packages. But still getting the same issue.

**Comment by zkat** [comment]
Thanks @sasidhar! Support is out for the day (and I shouldn't even be here right now, tbh), but they'll take a look at things for you. Thanks for filing the issue! :)

**Comment by sasidhar** [comment]
Thanks @zkat for the quick reply. I will close this ticket once the packages are deleted.

**Comment by mguella** [comment]
Same issue for me. Unable to completely unpublish a package I own. I get the same response (504 Gateway Time-out).
Both `npm config get proxy` and `npm config get https-proxy`are returning `null`.
I've being trying multiple times in the past 10-15 hours with 2 different ISPs in 2 different locations and no luck.
No proxy or firewall set on my side.

**Comment by sasidhar** [comment]
@zkat, @mguella I just tried and I unpublished my public package successfully.
But I am still getting the same issue while unpublishing our private package.
I will update you if I find any luck after some time.

**Comment by sasidhar** [comment]
@zkat Now I unpublished my private package successfully.
Guess, this issue is resolved now.
@mguella I am closing this ticket. Feel free to re-open this, if you still face issues.

**Comment by mguella** [comment]
yes, seems to work correctly now ;)

**Comment by zkat** [comment]
glad it's all set now! Thanks for pinging us about it! :)

**Comment by mhd-hmd** [comment]
Hi, I believe i'm facing the same issue with a public package i published less than 24hours ago, i was able to publish different versions of a package and unpublish them successfully with exception to the final version, no matter which version it is, i am unable to remove the remaining single version in order to unpublish the package from registry. 
Any help would be greatly appreciated.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\M.Hammed\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'unpublish',
1 verbose cli   'mh_censorify@1.0.3',
1 verbose cli   '-force' ]
2 info using npm@4.4.4
3 info using node@v4.8.1
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] mh_censorify@1.0.3
6 silly unpublish thing Result {
6 silly unpublish   raw: 'mh_censorify@1.0.3',
6 silly unpublish   scope: null,
6 silly unpublish   escapedName: 'mh_censorify',
6 silly unpublish   name: 'mh_censorify',
6 silly unpublish   rawSpec: '1.0.3',
6 silly unpublish   spec: '1.0.3',
6 silly unpublish   type: 'version' }
7 verbose getPublishConfig null
8 silly ls normalized mh_censorify\1.0.3
9 silly gentlyRm C:\Users\M.Hammed\AppData\Roaming\npm-cache\mh_censorify\1.0.3 is being purged
10 verbose gentlyRm don't care about contents; nuking C:\Users\M.Hammed\AppData\Roaming\npm-cache\mh_censorify\1.0.3
11 silly mapToRegistry name mh_censorify
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'mh_censorify',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   escapedName: 'mh_censorify',
14 silly mapToRegistry   name: 'mh_censorify',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/mh_censorify
16 verbose get GET as part of write; not caching result
17 verbose request uri https://registry.npmjs.org/mh_censorify?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 7:45:48 PM
20 verbose request using bearer token for auth
21 verbose request id f536c86b599875b4
22 http request GET https://registry.npmjs.org/mh_censorify?write=true
23 http 200 https://registry.npmjs.org/mh_censorify?write=true
24 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   etag: '"58d7a685-64c"',
24 verbose headers   'content-encoding': 'gzip',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Sun, 26 Mar 2017 11:45:49 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-fjr7922-FJR',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1490528748.767095,VS0,VE1032',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
25 silly get     'content-type': 'application/json',
25 silly get     etag: '"58d7a685-64c"',
25 silly get     'content-encoding': 'gzip',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Sun, 26 Mar 2017 11:45:49 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-fjr7922-FJR',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1490528748.767095,VS0,VE1032',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving mh_censorify to C:\Users\M.Hammed\AppData\Roaming\npm-cache\registry.npmjs.org\mh_censorify_3Fwrite_3Dtrue\.cache.json
27 verbose correctMkdir C:\Users\M.Hammed\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
28 verbose unpublish removing attachments { shasum: 'b7363d4c136141cfc5d90bad55e869fb19473a00',
28 verbose unpublish   tarball: 'https://registry.npmjs.org/mh_censorify/-/mh_censorify-1.0.3.tgz' }
29 info unpublish No versions remain, removing entire package
30 verbose request uri https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 7:45:50 PM
33 verbose request using bearer token for auth
34 http request DELETE https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
35 http 500 https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=0',
36 verbose headers   'content-length': '17',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Sun, 26 Mar 2017 11:45:51 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-fjr7922-FJR',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1490528749.913647,VS0,VE1127' }
37 info retry will retry, error on last attempt: Error: Registry returned 500 for DELETE on https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
38 info attempt registry request try #2 at 7:46:01 PM
39 verbose request using bearer token for auth
40 http request DELETE https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
41 http 500 https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
42 verbose headers { 'content-type': 'application/json',
42 verbose headers   'cache-control': 'max-age=0',
42 verbose headers   'content-length': '17',
42 verbose headers   'accept-ranges': 'bytes',
42 verbose headers   date: 'Sun, 26 Mar 2017 11:46:02 GMT',
42 verbose headers   via: '1.1 varnish',
42 verbose headers   connection: 'keep-alive',
42 verbose headers   'x-served-by': 'cache-fjr7922-FJR',
42 verbose headers   'x-cache': 'MISS',
42 verbose headers   'x-cache-hits': '0',
42 verbose headers   'x-timer': 'S1490528761.639547,VS0,VE1158' }
43 info retry will retry, error on last attempt: Error: Registry returned 500 for DELETE on https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
44 info attempt registry request try #3 at 7:47:02 PM
45 verbose request using bearer token for auth
46 http request DELETE https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
47 http 500 https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
48 verbose headers { 'content-type': 'application/json',
48 verbose headers   'cache-control': 'max-age=0',
48 verbose headers   'content-length': '17',
48 verbose headers   'accept-ranges': 'bytes',
48 verbose headers   date: 'Sun, 26 Mar 2017 11:47:04 GMT',
48 verbose headers   via: '1.1 varnish',
48 verbose headers   connection: 'keep-alive',
48 verbose headers   'x-served-by': 'cache-fjr7922-FJR',
48 verbose headers   'x-cache': 'MISS',
48 verbose headers   'x-cache-hits': '0',
48 verbose headers   'x-timer': 'S1490528822.831490,VS0,VE1225' }
49 verbose request invalidating C:\Users\M.Hammed\AppData\Roaming\npm-cache\registry.npmjs.org\mh_censorify on DELETE
50 verbose stack Error: Registry returned 500 for DELETE on https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
50 verbose stack     at makeError (C:\Users\M.Hammed\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:304:12)
50 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\M.Hammed\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:282:14)
50 verbose stack     at Request._callback (C:\Users\M.Hammed\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:212:14)
50 verbose stack     at Request.self.callback (C:\Users\M.Hammed\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:188:22)
50 verbose stack     at emitTwo (events.js:87:13)
50 verbose stack     at Request.emit (events.js:172:7)
50 verbose stack     at Request.<anonymous> (C:\Users\M.Hammed\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1171:10)
50 verbose stack     at emitOne (events.js:77:13)
50 verbose stack     at Request.emit (events.js:169:7)
50 verbose stack     at IncomingMessage.<anonymous> (C:\Users\M.Hammed\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1091:12)
51 verbose statusCode 500
52 verbose pkgid mh_censorify
53 verbose cwd C:\censorify
54 verbose Windows_NT 6.3.9600
55 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\M.Hammed\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "mh_censorify@1.0.3" "-force"
56 verbose node v4.8.1
57 verbose npm  v4.4.4
58 error code E500
59 error Registry returned 500 for DELETE on https://registry.npmjs.org/mh_censorify/-rev/19-b7fe39a2ca80524e9069504ce0f7366b
60 verbose exit [ 1, true ]

Thanks in advance.
