### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by dshetkar** [npm/npm#12058]
Please my this error

**Comment by zkat** [comment]
Hi! This looks like an SSL-related error, but we usually need the contents of `npm-debug.log` in order to get a better idea of what's up.

Three things:

* Check your proxy settings
* Check with your network admin to make sure the proxy is configured correctly
* Make sure your local SSL certificates are in good condition and there's nothing weird going on there

**Comment by jakhil87** [comment]
Iam also facing same issue. Proxy settings are working fine in my Colleagues m/c. How to check local SSL certificates. If the problem is solved what is the resolution

**Comment by zkat** [comment]
@jakhil87 Could you please post an `npm-debug.log`?

**Comment by jakhil87** [comment]
Please find attached npm-debug.log file. I am in a restricted network and using proxy to connect. It is working fine in other colleagues system.
[npm-debug.txt](https://github.com/npm/npm/files/194887/npm-debug.txt)

**Comment by zkat** [comment]
Could you tell me what you've done so far to configure your proxy?
