### ISSUE TITLE
Call adduser with parameters

### ISSUE THREAD

**Issue by raybooysen** [npm/npm#12111]
Often, for example, on build servers you may want to call adduser specifically with the build agent's credentials.  At the moment this is not possible as `adduser` is interactive and cannot be passed params.

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/9325

**Comment by othiym23** [comment]
This absence is by design. Passing credentials on the command-line is insecure on multi-tenant hosts, and even on single-tenant hosts is frequently an inadvertent credential leak. [This](https://remysharp.com/2015/10/26/using-travis-with-private-npm-deps) is the best way to set up a build host to work with npm when login is needed.

Another reason to be conservative around credentials-handling is https://www.kb.cert.org/vuls/id/319816, which is a long-known consequence of the design of a package manager that runs user-provided code. It's probable that the npm registry will be making some changes to how it handles authentication tokens in response to this, and it's also possible there will be some changes around that that will propagate to the CLI. Until that point, though, this is not something that's going to change.

**Comment by raybooysen** [comment]
Thanks @othiym23

**Comment by sfertman** [comment]
@othiym23, @KenanY, it is hardly secure to use the same token for months and hardly practical to login manually every time you want to publish a package to a registry. If "silent login" were to be implemented, you could invalidate session tokens after some short time for security and in the same time make automation easier for CI.

**Comment by larryboymi** [comment]
@othiym23 what would you do in the case of an internal npm repository which is not utilizing github/travis?

**Comment by likewhatevs** [comment]
@larryboymi this worked for me: https://www.slashroot.in/expect-command-tutorial-linux-example-usage 
Added benefit - build's won't magically start to fail with this approach and it even includes a man page.

**Comment by raoel** [comment]
Ofcourse people are going to hack around this, as written above.

As already said: current method does not allow invalidating tokens if you're doing CI

Or, please, add a recommended way that allows both CI and invalidation of tokens for better security (we're not allowed to have 'forever'-tokens by government regulations).

Thank you :-)

**Comment by holms** [comment]
Can this be solved please? It's violating all possible UNIX standards. You should almost never use prompts at all, or if you do so, parameters should be on the first place when you write a tool. It's stated on so on the first pages of bash RFC
