### ISSUE TITLE
npm-cli error with concat version

### ISSUE THREAD

**Issue by HermineF** [npm/npm#12124]
Hi,
I have a problem on doing a "npm install" on my machine (windows) with npm-cli :

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\_[Users]_\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--force"
npm ERR! node v5.4.1
npm ERR! npm  v3.8.3

npm ERR! No compatible version found: concat@^1.0.0
npm ERR! Valid install targets:
npm ERR! 2.0.0, 0.0.1-security
```

thx in advance for help,

[files.zip](https://github.com/npm/npm/files/193171/files.zip)

**Comment by HermineF** [comment]
seems to be a problem with concat-cli and/or concat-glob-cli

**Comment by aggro80** [comment]
concat-cli doesn't work, because it depends on concat and concat has this problem:

"This package name is not currently in use, but was formerly occupied by a popular package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.", https://www.npmjs.com/package/concat

So it looks like "concat" package has disappeared from the servers. I have no idea how this can be solved. I didn't even know it is possible for versioned packages to disappear from the npm.
