### ISSUE TITLE
Support unpublish workflow for depended on versions

### ISSUE THREAD

**Issue by geek** [npm/npm#12127]
Inspired by @mcollina 

This will likely need to be more than a client change, but there are changes we can make to the client to help.

1. When `npm unpublish` executes, check the modules that are dependent on the module being unpublished, if any of them are pinned to the specific version being unpublished then proceed to step 2, else, continue with the unpublish procedure as usual
2. Inform the user that they will break modules with the unpublish command and list out the modules that will break as a result.  Prompt the user with a yes/no option to continue.  If they type yes, proceed to step 3, otherwise exit
3. Prompt the user for a reason why they need to unpublish the module version.  Email this to support@npmjs.com and inform the user of this action

Ideally, the next step will be for npm support to approve the deletion of the module version and to provide a response to the email.  It will be beneficial if the checks in step 1 occur server side, in the registry.  But, instead of waiting for that work to be done, there is no reason why we can't perform these checks client side.

**Comment by othiym23** [comment]
So, since this went up, npm, Inc. has [come up with a policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) for handling unpublishes, with an associated [discussion thread](https://github.com/npm/policies/issues/44). I'm closing this feature request in favor of that discussion / policy description, if only because these are all changes happening at the registry level, and not in the CLI. Thanks for your time and the clear policy suggestions, Wyatt!
