### ISSUE TITLE
Can't redirect output from npm install to file on Windows

### ISSUE THREAD

**Issue by rmilesson** [npm/npm#12141]
Trying with both `npm install --verbose > ./npm-install.log` and (in Powershell) `npm install --verbose | Out-File ./npm-install.log` and both of them results in the file `npm-install.log` being created, but without any content.

Using
Node v5.5.0
npm v3.3.4

on Windows 7

**Comment by othiym23** [comment]
npm's logging output is printed to `stderr`, so you'll [need to redirect `stderr`](https://support.microsoft.com/en-us/kb/110930) (the instructions are a little different on PowerShell, but should be pretty easy to Google. Since that's all that needs to be done here, and because this isn't an issue with the npm CLI itself, I'm going to close this issue. Thanks for your time!
