### ISSUE TITLE
Installing “script@3.6.3” failed

### ISSUE THREAD

**Issue by quasemsm** [npm/npm#12154]
```
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: Cloning into 'C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: git-upload-pack 'C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541': git-upload-pack: command not found
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: 
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: and the repository exists.
npm ERR! git clone C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea: 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Sadiq\\AppData\\Local\\atom\\app-1.6.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Sadiq\\AppData\\Local\\atom\\app-1.6.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Sadiq\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Sadiq\\.atom\\.apmrc" "install" "C:\\Users\\Sadiq\\AppData\\Local\\Temp\\d-116231-7232-1x24kah\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\Sadiq\AppData\Local\Temp\npm-10620-350f5524\git-cache-b1403ffbfe2a\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! git-upload-pack 'C:\Users\Sadiq\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541': git-upload-pack: command not found
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`
```

I am getting this error trying to install script in my atom. I recently reinstalled atom and this error is happening

**Comment by martindouglasj** [comment]
C:\Users\dmartin>apm install script
Installing script to C:\Users\dmartin\.atom\packages failed

npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\dmartin\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\dmartin\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dmartin\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\dmartin\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\dmartin\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dmartin\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\dmartin\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dmartin\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.129]: errno=Invalid argument
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\dmartin\\AppData\\Local\\atom\\app-1.6.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dmartin\\AppData\\Local\\atom\\app-1.6.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\dmartin\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\dmartin\\.atom\\.apmrc" "install" "C:\\Users\\dmartin\\AppData\\Local\\Temp\\d-11631-8976-wf9kz\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\dmartin\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
