### ISSUE TITLE
Sync LTS license with master

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#12187]
See https://github.com/nodejs/node/issues/3959#issuecomment-205370054 for details.

Is syncing the LTS license possible?

**Comment by othiym23** [comment]
When we were working on putting together the security releases for Node.js 0.10 and 0.12, @rvagg and I discussed the fact that the license updating script didn't exist on those branches. He said that he'd square up the licenses as part of the release, and then with one thing or another, that didn't happen. As it happens, this isn't an issue for npm itself to deal with, because the LICENSE on `npm@2` is correct and up-to-date. It's a matter for the Node.js TSC and the build WG to decide whether getting that synced up justifies the work required to put out new releases. As far as npm is concerned, everything is as it should be.

**Comment by ChALkeR** [comment]
> the LICENSE included in `npm@2` is correct and up-to-date

https://github.com/npm/npm/blob/lts/LICENSE:

> The following additional terms shall apply to use of the npm software, the npm
website, the npm repository and any other services or products offered by npm,
Inc.:
> …
> Additional policies relating to, and restrictions on use of, npm products and
services are available on the npm website.  All such policies and restrictions,
as updated from time to time, are hereby incorporated into this license
agreement.  By using npm, you acknowledge your agreement to all such policies
and restrictions.
> …

That's still present in the `lts` branch and in 2.15.3 release, but not present in recent 3.x releases and in the master branch.

**Comment by ChALkeR** [comment]
That basically means that any user of the `npm` client is meant to agree to the additional terms published on the npm website (and future updates of those), no matter how he or she uses the `npm` client.

**Comment by ChALkeR** [comment]
@othiym23 I don't think that this is a node bug, I really doubt that `deps/npm/LICENSE` could be changed downstream (i.e. in Node.js).

**Comment by ChALkeR** [comment]
https://github.com/npm/npm/blob/lts/LICENSE#L257-L261 — It's still there.

**Comment by ChALkeR** [comment]
Fixed in https://github.com/npm/npm/pull/13892.
