### ISSUE TITLE
express not installed always getting error

### ISSUE THREAD

**Issue by php1webmobtech** [npm/npm#12201]

**Comment by KenanY** [comment]
@php1webmobtech Is there a `npm-debug.log` you can upload to gist.github.com and link here?

**Comment by othiym23** [comment]
Closing due to insufficient information for us to resolve. @php1webmobtech, if you'd like help from the npm CLI team, please include more information when opening a new issue, including the version of npm you're running and (at least) the text of the error you're seeing. As @KenanY says, a [gist](https://gist.github.com/) of the `npm-debug.log` left behind by npm on failure would be even more helpful. Thanks for your time!
