### ISSUE TITLE
npm install azure-iot-hub occurs "npm ERR! TypeError: Cannot read property 'latest' of undefined"

### ISSUE THREAD

**Issue by artyomovs** [npm/npm#12210]
Hi guys. 
I have one issue that I've been working with for 3 weeks. 
I want to send Cloud2Device message to my Raspberry Pi. Im going to do it with Mobile Service API node js script. 
I've copied the script from github azure iot samples. But it crushes IIS Azure. 
I've  created the post about this issue:
[stackoverflow link](http://stackoverflow.com/questions/36270576/azure-mobile-services-an-unhandled-exception-occurred-error-one-of-your-script/36306340)

I was advised to install npm "azure-iot-hub" using Kudu Debug console. But when I'm trying to do it I see another error: 

> D:\home\site\repository\service>npm install azure-iot-hub
> npm WARN package.json id4t@1.0.0 No repository field.
> npm WARN package.json id4t@1.0.0 No readme data.
> npm http GET https://registry.npmjs.org/azure-iot-hub
> npm http 404 https://registry.npmjs.org/azure-iot-hub
> npm ERR! TypeError: Cannot read property 'latest' of undefined
> npm ERR!     at next (c:\Program Files (x86)\npm\1.2.30\node_modules\npm\lib\cache.js:690:35)
> npm ERR!     at c:\Program Files (x86)\npm\1.2.30\node_modules\npm\lib\cache.js:678:5
> npm ERR!     at saved (c:\Program Files (x86)\npm\1.2.30\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
> npm ERR!     at Object.oncomplete (fs.js:302:15)
> npm ERR! If you need help, you may report this log at:
> npm ERR!     <http://github.com/isaacs/npm/issues>
> npm ERR! or email it to:
> npm ERR!     <npm-@googlegroups.com>
> 
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "node" "D:\\Program Files (x86)\\npm\\1.2.30\\node_modules\\npm\\bin\\npm-cli.js" "install" "azure-iot-hub"
> npm ERR! cwd D:\home\site\repository\service
> npm ERR! node -v v0.8.28
> npm ERR! npm -v 1.2.30
> npm ERR! type non_object_property_load
> npm

Seems I need to update node js, but I can't realize which way I am supposed to do it. Guys, maybe you have any idea about this stuff? Any help welcome. 

I apologize for my bad English)

**Comment by othiym23** [comment]
That version of npm is so old (`'1.2.30': '2013-07-12T21:48:13.552Z'`) that it's completely unsupported, as is that version of Node. I think the best way to get help with this is to start with [Microsoft's Azure documentation](https://azure.microsoft.com/en-us/develop/nodejs/), and see if you can find support from there. You may also want to look at [this page on choosing your Node.js version](https://azure.microsoft.com/en-us/documentation/articles/nodejs-specify-node-version-azure-apps/), although I don't know if that will work with the Mobile Service API. This isn't something that the npm CLI team can help you with, beyond telling you that the bug you're seeing is very likely to be fixed in recent versions of `npm@2` and `npm@3`. As such, I'm going to close this issue. Thanks for your time, and good luck!

**Comment by artyomovs** [comment]
@othiym23 Thank you!
