### ISSUE TITLE
Broken Lifecycle Signal Tests

### ISSUE THREAD

**Issue by deckar01** [npm/npm#12220]
The tests in `test/tap/lifecycle-signal.js` are skipped on Windows and Travis, but are failing on Linux.
- Ubuntu 15.04
- node v5.10.0

**lifecycle signal abort**

This test fails because regardless of the signal used to kill the process in `preinstall` the child's exit code is `1` and exit signal is `null`. There seems to be an error handler stripping the signal and changing the code to 1. I tested that `node -e` wasn't eating the error, so it must be somewhere around the install action or the lifecycle.

[test/tap/lifecycle-signal.js#L45](https://github.com/npm/npm/blob/545434766eb3681d3f40b745f9f3187ed63f310a/test/tap/lifecycle-signal.js#L45)

Originally added by @TooTallNate in https://github.com/npm/npm/commit/d885f81ec67c9ac583a830f4dfa7ad8fb0e9c21f

**lifecycle propagate signal term to child**

This test fails, because the test assumes killing a child process kills its subprocess, but that is incorrect.

> I think you have the wrong idea about processes and process groups. On exit, child processes get reparented, they're not forcibly killed by io.js or the kernel.
> https://github.com/nodejs/node/issues/2098#issuecomment-118322915

http://stackoverflow.com/questions/33325301/killing-a-bash-script-does-not-kill-child-processes

[test/tap/lifecycle-signal.js#L67](https://github.com/npm/npm/blob/545434766eb3681d3f40b745f9f3187ed63f310a/test/tap/lifecycle-signal.js#L67)

Originally added by @daniel-pedersen in https://github.com/npm/npm/commit/545434766eb3681d3f40b745f9f3187ed63f310a.

---

```
ubuntu@ubuntu:~/npm$ DEPLOY_VERSION=testing npm run tap -- "test/tap/lifecycle-signal.js" 

> npm@3.8.6 tap /home/ubuntu/npm
> tap --timeout 240 "test/tap/lifecycle-signal.js"

test/tap/lifecycle-signal.js .......................... 5/9 4m
  lifecycle signal abort
  not ok should be equal
    +++ found                                                          
    --- wanted                                                         
    -[null]                                                            
    +1                                                                 
    compare: ===
    at:
      line: 44
      column: 7
      file: test/tap/lifecycle-signal.js
      type: ChildProcess
    stack: |
      ChildProcess.<anonymous> (test/tap/lifecycle-signal.js:44:7)
      Pipe._onclose (net.js:477:12)

  lifecycle signal abort
  not ok should be equal
    +++ found                                                          
    --- wanted                                                         
    -"SIGSEGV"                                                         
    +[null]                                                            
    compare: ===
    at:
      line: 45
      column: 7
      file: test/tap/lifecycle-signal.js
      type: ChildProcess
    stack: |
      ChildProcess.<anonymous> (test/tap/lifecycle-signal.js:45:7)
      Pipe._onclose (net.js:477:12)

  lifecycle propagate signal term to child
  not ok expected to throw
    at:
      line: 68
      column: 7
      file: test/tap/lifecycle-signal.js
      type: ChildProcess
    stack: |
      ChildProcess.<anonymous> (test/tap/lifecycle-signal.js:68:7)

  not ok timeout!
    at:
      line: 3
      column: 11
      file: node_modules/tap/lib/root.js
    signal: SIGTERM
    handles:
      - type: Socket
        events:
          - end
          - finish
          - _socketEnd
          - close
      - type: Socket
        events:
          - end
          - finish
          - _socketEnd
          - close
          - data

total ................................................. 5/9


  5 passing (4m)
  4 failing
```

**Comment by gibfahn** [comment]
@deckar01 @othiym23 @iarna Was a decision reached about making npm use bash instead of sh (ref: https://github.com/npm/npm/pull/12221#issuecomment-215274111) ? 

Is it just a question of changing the shebang in [bin/npm#L1](https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/bin/npm#L1) from `#!/bin/sh` to `#!/bin/bash`?

It'd be nice to get these tests passing in order to run `make test-npm` from node.

**Comment by othiym23** [comment]
> Was a decision reached about making npm use bash instead of sh?

Yes, although the CLI team has been focused on high-priority crashers, and as such hasn't worked in this yet.

> Is it just a question of changing the shebang in bin/npm#L1 from `#!/bin/sh` to `#!/bin/bash`?

Not exactly, because it's not uncommon for bash to be in `/usr/bin` instead. Either the code should just invoke bash assuming that it's on `PATH`, or use [`which`](http://npm.im/which) to find an absolute path to bash. The latter is preferred, given that we're moving npm towards being able to use a configurable shell (overriding, in particular, `cmd.exe` on Windows).

**Comment by gibfahn** [comment]
@othiym23 So would something like [cli.js#L1](https://github.com/npm/npm/blob/master/cli.js#L1) (i.e. using `#!/usr/bin/env bash`) be the way to get it from the `PATH`?

Also would you mind explaining what you mean by being able to use a configurable shell? Do you mean allowing the user to specify which shell they want to use?

**Comment by odinho** [comment]
Bah :(  Wasted time on this, I mistakenly thought I'd broken this test with my code, and didn't first test the rev before mine since I wrongly assumed all tests would normally pass.  I see there was quite a lot of activity on this, but then it all stopped.  I think @gibfahn's suggestion sounds like a good quick fix.

It'd be good to even just disable this test.  Having broken tests is anti pattern :)

**Comment by deckar01** [comment]
As far as I know, this is still an issue. The travis exclusion is still in those tests, and the `shell` config variable is only for the `explore` command. 🤖 

I'm not using Ubuntu or contributing to npm anymore, so I will leave it up to someone else to create a new issue.
