### ISSUE TITLE
postupdate / preupdate hooks

### ISSUE THREAD

**Issue by leegee** [npm/npm#12237]
`npm install` has hooks either side of it, but `npm update` has not.

I often use `npm postinstall` to run `bower install`, I would like to have npm run `bower update` after `npm update`

**Comment by othiym23** [comment]
Bower's update and npm's update do different things; under the hood npm's update calls `npm outdated` followed by `npm install` with the results list of outdated packages. It doesn't make much sense to distinguish between install and update for lifecycle purposes. If you want a way to couple the updating of your npm and bower dependencies, a short script, cmd, or `Makefile` stanza is the most flexible way to get the exact behavior you want. Because this isn't something the CLI team is going to add to npm, I'm going to close this feature request. Thanks for your time, and I hope you find this explanation useful.

**Comment by PMLavigne** [comment]
Sorry for resurrecting this old ticket, but is there still no plan to add pre/post update hooks? I believe I have a more compelling use - running `flow-typed update`.  The flow-typed files are very tightly coupled to the versions of the packages installed (especially the auto-generated stubs) and being able to have them automatically generated whenever `npm update` is run would be incredibly helpful.

**Comment by Gpx** [comment]
@PMLavigne I'm trying to do the exact same thing. Did you find a solution meanwhile?

**Comment by alexkrolick** [comment]
I think this would also be useful for printing out Release Notes and things like that, but maybe only in --dev mode (installing a package from its directory rather than as a dependency).

**Comment by PMLavigne** [comment]
@Gpx unfortunately no, I wound up just doing a much less elegant wrapper script that runs both separately, and using that instead. Still would massively prefer if this functionality were present natively, maybe with a big fat warning if there's concern it could be used incorrectly?

**Comment by gmcdev** [comment]
I'm looking for a way to make a backup of the current package-lock.json ... on a "preupdate" sort of a basis. Since the lifecycle hook idea is out, what is the alternative? Recommendations?

Another challenge I notice is that package-lock.json does not get written until _after_ the "postinstall" hook finishes. What event to use to post-/pre-process package-lock.json??
