### ISSUE TITLE
always log use of Environment Variables

### ISSUE THREAD

**Issue by peterlynch** [npm/npm#12242]
npm currently supports having some environment variables override some config settings. The problem is when these are set, npm does not always log their use.

Users think they have their config or command line correct, yet something may not be working correctly because of an environment variable. Nasty variables include HTTP_PROXY and HTTPS_PROXY.

PLEASE - at least at insane logging levels of -ddd, log the use of these variables and any other environment variables. If these are set wrong http requests can fail in obscure ways...

**Comment by othiym23** [comment]
This is a bit of a yak shave:

- almost all configuration values can be set via the environment
- `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` are passthroughs from npm to `request`, which figures out how to set up the tunneling agent it uses to download
- it's hard to say in advance where and when these settings need to be logged.
- a lot of the environment variable / config file / command-line option processing is handled using a generic framework that doesn't make it easy to say at runtime which source was pulled for a given configuration value. It can be done, but it requires some extra ceremony.

That said, the CLI team would be happy to review, and potentially land, changes to logging intended to make it easier for users to self-diagnose configuration problems involving potentially conflicting settings between environment variables and configuration files. That's why, although I'm closing this request, it has a `patch-welcome` label attached to it – it would be great to have contributions here from people who have a solid grasp of which bits of this config they need more insight into.
