### ISSUE TITLE
npm se console.log directly

### ISSUE THREAD

**Issue by holblin** [npm/npm#12365]
I notice that npm directly use console.log and don't use the stream passed in options for all outputs.
https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/lib/ls.js#L95

**Comment by othiym23** [comment]
This is by design – logging-oriented output goes through [`npmlog`](http://npm.im/npmlog), which prints to stderr. The intended output of commands is printed directly, using `console.log()`. Historically, @isaacs considered that output part of each command's API contract; the CLI team is reassessing that as part of a broader effort to clean up the CLI's user experience. That said, we'll probably still be using `console.log()` to get that output in front of people's eyeballs, as that's the simplest way to get something to standard output. Thanks for your time!
