### ISSUE TITLE
Squash multiple warnings about the same dependency on install.

### ISSUE THREAD

**Issue by lewiscowper** [npm/npm#12378]
![](https://pbs.twimg.com/media/CgBlWaFW4AYl5AF.jpg)

> https://twitter.com/cole_peters/status/720687377572884480/photo/1

In this example, I'd expect there was a way to squash the warnings about `graceful-fs` here to show it once and then not show it any more, even as new dependents pulled it in.

I'm mostly wondering whether there's a possibility to only show warnings about specific dependency once, the first time it's run into. I'd be happy to work on that, but I would need a little nudge in the right direction to figure out where the logic would be best to sit. It definitely looks like somewhere in [this block of lib/install.js](https://github.com/npm/npm/blob/master/lib/install.js#L279-L303) is where it'd end up, so I'll do some digging around in there to see if that's worthwhile.

**Comment by iarna** [comment]
Currently this is done in `lib/utils/depr-check.js`

**Comment by othiym23** [comment]
If you look at this output, it's printing one warning for each `package, version` tuple. What would allow you to DRY up this output would be to group by deprecation message (since there's no way at runtime to figure out what the original deprecation range was, as in the example of `graceful-fs` above). As @iarna discussed in the CLI team meeting (link to come), this would work as a tree validator (which runs at the end of the installation process).

**Comment by iarna** [comment]
Having discussed this as a group, moving the check to [lib/install/validate-tree.js](https://github.com/npm/npm/blob/master/lib/install/validate-tree.js) seems like the best approach.

It iterates over every module in the tree and calls validater functions on them here:

https://github.com/npm/npm/blob/master/lib/install/validate-tree.js#L22-L27

It also does a series of tree level validations here:

https://github.com/npm/npm/blob/master/lib/install/validate-tree.js#L28-L29

This probably needs to be the latter since the goal is to squash warnings based on the message, so you'll need to look at all the modules before adding any warnings.

Please also note the way we adding warnings here:

```
idealTree.warnings.push(errorObj)
```

These should have an `errorObj.code` of `deprecated` to match the existing warnings.
