### ISSUE TITLE
Copyfree license preferred 

### ISSUE THREAD

**Issue by lbmn** [npm/npm#12448]
Why does npm use the restrictive [Artistic License](https://github.com/npm/npm/blob/master/LICENSE)?  This is very unusual for the Node ecosystem, which strongly prefers the perfect MIT license.

Artistic License [does not fit](http://copyfree.org/standard/rejected) the stricter definition of Software Freedom ("Copyfree"). For [pacifist philosophical reasons](http://forum.freestateproject.org/index.php?topic=19771.0), I would never use anything that came with legal threats backed by force.  This position is [increasingly common](https://www.npmjs.com/package/licensing), especially for Node developers.  

Just one example, [quoting a top node module dev](https://qnalist.com/questions/5523655/preferred-license-for-node-modules):

> I have zero dependencies on GPL modules for that reason and won't use any npm modules that are under the GPL licence. If you like collaboration or want people to use your code you should licence it as MIT, because it's virtually the community standard. (Meteor released with GPL a while back and was hitting back by the community and changed to MIT)

Furthermore, [as FreeBSD.org puts it](https://www.freebsd.org/doc/en/articles/bsdl-gpl/article.html#conclusion) (the modern BSD license being nearly identical to MIT):

> Since the BSD license does not come with the legal complexity of the GPL or LGPL licenses, it allows developers and companies to spend their time creating and promoting good code rather than worrying if that code violates licensing.

The Artistic License is less bad than GPL, but it's still restrictive.  Why do this?  You are alienating a significant and growing fraction of Node's potential users and contributors, many of whom have switched to NodeJS exclusively due to licensing.

See [the copyfree.org whitelist](http://copyfree.org/standard/licenses) for a large selection of licenses that are **genuine** Free Software.

No disrespect intended.  Obviously you can do whatever they want with your code.  I hope you won't respond with hostility...

**Comment by othiym23** [comment]
No hostility from me! In part that's because discussion of licenses depends on convictions and other subjective factors that go beyond simple rightness or wrongness. The larger part is because npm's current license is a fact on the ground, and not up to the CLI team (including me) to change. Changing the license of a package with as many contributions as npm has received would require a great deal of time and effort. It would also need to come from a consensus among the stakeholders of the product that it needed to change, including at least @isaacs as the primary author and @kemitchell as npm, Inc.'s counsel. As such, I'm going to close this issue. By pinging them, I've provided an opportunity for them to weigh in here if they wish. Because this is something that's now been established fact for a long time, I wouldn't expect much, though. Thanks for your time!
