### ISSUE TITLE
Cannot `npm i package.json`

### ISSUE THREAD

**Issue by IonicaBizau** [npm/npm#12455]
It looks like `npm install`ing the `package.json` module doesn't work anymore for some reason... Can you check what's going on?

```sh
$ npm i package.json
npm ERR! not a package /home/ionicabizau/Documents/blah/package.json
npm ERR! addLocal Could not install /home/ionicabizau/Documents/blah/package.json
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm" "i" "package.json"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! path /tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionicabizau/Documents/blah/npm-debug.log
```

And here the log file:

```log
0 info it worked if it ends with ok
1 verbose cli [ '/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node',
1 verbose cli   '/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   'package.json' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData package.json
8 silly fetchOtherPackageData package.json
9 silly cache add args [ 'package.json', null ]
10 verbose cache add spec package.json
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'package.json',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'package.json',
11 silly cache add   spec: '/home/ionicabizau/Documents/blah/package.json',
11 silly cache add   type: 'local' }
12 silly addLocalTarball shasum (computed) fc6e253268f438b10a0a0bd8cc58e476cc2e84cc
13 verbose addTmpTarball /home/ionicabizau/Documents/blah/package.json not in flight; adding
14 verbose correctMkdir /home/ionicabizau/.npm correctMkdir not in flight; initializing
15 verbose addTmpTarball validating metadata from /home/ionicabizau/Documents/blah/package.json
16 verbose tar unpack /home/ionicabizau/Documents/blah/package.json
17 verbose tar unpacking to /tmp/npm-25856-5174ab8f/unpack-3c0011b2
18 silly gentlyRm /tmp/npm-25856-5174ab8f/unpack-3c0011b2 is being purged
19 verbose gentlyRm don't care about contents; nuking /tmp/npm-25856-5174ab8f/unpack-3c0011b2
20 silly gunzTarPerm modes [ '775', '664' ]
21 error not a package /home/ionicabizau/Documents/blah/package.json
22 error addLocal Could not install /home/ionicabizau/Documents/blah/package.json
23 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json'
23 silly fetchPackageMetaData     at Error (native)
23 silly fetchPackageMetaData  error for package.json { [Error: ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json']
23 silly fetchPackageMetaData   errno: -2,
23 silly fetchPackageMetaData   code: 'ENOENT',
23 silly fetchPackageMetaData   syscall: 'open',
23 silly fetchPackageMetaData   path: '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json' }
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Starting
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack Error: ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json'
29 verbose stack     at Error (native)
30 verbose cwd /home/ionicabizau/Documents/blah
31 error Linux 4.4.0-21-generic
32 error argv "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm" "i" "package.json"
33 error node v5.9.0
34 error npm  v3.7.3
35 error path /tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json
36 error code ENOENT
37 error errno -2
38 error syscall open
39 error enoent ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json'
40 error enoent ENOENT: no such file or directory, open '/tmp/npm-25856-5174ab8f/unpack-3c0011b2/package.json'
40 error enoent This is most likely not a problem with npm itself
40 error enoent and is related to npm not being able to find a file.
41 verbose exit [ -2, true ]
```

**Comment by weezy93** [comment]
```npm i``` will look for the ```package.json``` file to install what is on that list.  ```npm i package.json``` tells npm to look for a package called package.json, similar to ```npm i gulp```, where gulp is the package to install

**Comment by IonicaBizau** [comment]
@weezy93 Hmm, I don't really understand what you mean.

> npm i will look for the package.json file to install what is on that list. 

Do you mean this will look in the `dependencies` object in the `package.json` file?

> npm i package.json tells npm to look for a package called package.json, similar to npm i gulp, where gulp is the package to install

That's what I actually want to do. I want to install my [`package.json`](https://www.npmjs.com/package/package.json) package. `package.json` in my case *is* a npm package I want to add as dependency:

```sh
$ npm i --save package.json
```

**Comment by KenanY** [comment]
Doing `npm install package.json@latest` works for me, probably because that clarifies to `npm` that we want to install a version from the registry and not a local thing.

**Comment by IonicaBizau** [comment]
@KenanY Thanks! That's a useful workaround! :cake:

Still, I will keep this issue opened since it should work without explicitly specifying the version.

**Comment by othiym23** [comment]
You probably want to change the name of the package, because short of some very kludgy hacks to npm, this behavior isn't going to change.

It's also completely expected: npm primarily is used to install packages from the registry, but it can also be used to install directories and tarballs. While working on `npm@2` and `npm@3`, we discovered that in the case where you were trying to install a package from the local file system when its name already existed on the registry, there was no way to install the local directory. This is pretty suboptimal for a number of common development workflows, so we switched the precedence of local vs the registry.

You probably see the problem already: `package.json` is always going to exist in the current directory if you're working on a package (which is going to be true the vast majority of the time). Checking whether the install target is a directory is something already done to switch between installing directories and tarballs, so that!/ not sufficient. Checking file extensions to verify we're working with tarballs isn't something npm is doing right now, and _seems_ safe, but will probably break somebody somewhere, which makes it at least a semver-major change. The only truly unambiguous way to fix this would be to create an internal blacklist of files to never try to install from the local file system (which would also include `.npmrc`, `.npmignore`, and `.gitignore`). This is a lot of additional complexity to support what is right now only one package, especially given that there's a workaround and that this UX quirk only affects installing via the command line, not from `package.json` itself.

Given the preceding, and considering the large installed base of npm clients that behave this way, I'm going to close this issue as something the CLI team doesn't intend to change. I really do think changing the name of the package will be less confusing all around. Thanks for your time and understanding!

**Comment by IonicaBizau** [comment]
@othiym23 That makes sense. However, the problem is still there: it's crashing and it says to report the issue here. See the following (creating an invalid *package* and trying to install it):

```sh
ionicabizau@notebook:~/Documents/foo/bar$ touch test
ionicabizau@notebook:~/Documents/foo/bar$ ls
test
ionicabizau@notebook:~/Documents/foo/bar$ npm i test 
npm ERR! tar.unpack error reading /home/ionicabizau/Documents/foo/bar/test
npm ERR! addLocal Could not install /home/ionicabizau/Documents/foo/bar/test
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm" "i" "test"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionicabizau/Documents/foo/bar/npm-debug.log
ionicabizau@notebook:~/Documents/foo/bar$ echo 1 > test 
ionicabizau@notebook:~/Documents/foo/bar$ npm i test 
npm ERR! not a package /home/ionicabizau/Documents/foo/bar/test
npm ERR! addLocal Could not install /home/ionicabizau/Documents/foo/bar/test
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/node" "/home/ionicabizau/.nvm/versions/node/v5.9.0/bin/npm" "i" "test"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! path /tmp/npm-25521-20d6f64b/unpack-af7a721c/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-25521-20d6f64b/unpack-af7a721c/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-25521-20d6f64b/unpack-af7a721c/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionicabizau/Documents/foo/bar/npm-debug.log
```

**Comment by IonicaBizau** [comment]
@othiym23 In short, what I mean is that it turns out that the `package.json` was a particular case. The real issue here is the fact that when installing an invalid package from a file, the `npm` process ends with a non-friendly error. Does it make sense?

**Comment by othiym23** [comment]
I suggest you open a new issue for this, because it is a separate issue from what you originally reported (or, even better, put together a patch with better error handling / message!). The only change really necessary is that the caching code should verify earlier that the directory contains a `package.json` including a valid version and name (which is what defines an npm package).

**Comment by IonicaBizau** [comment]
@othiym23 OK, opened #12469.
