### ISSUE TITLE
optionalDependencies as opt-in instead opt-out

### ISSUE THREAD

**Issue by zanona** [npm/npm#12532]
As I read the documentation on `optionalDependencies`, it was clear to me that these are modules that extend the default module behaviour to achieve extra functionality, but that ideally should not cause the bad functioning of a package in general.

Considering this, I am struggling to understand why optional dependencies are installed by default, if those are meant for advance usage in most cases?

I would like to propose that, instead of having:

> The --no-optional argument will prevent optional dependencies from being installed.

having something like:

> The --install-optional argument will install optional dependencies listed in your package.json file.

A simple use case would be a module that achieves basic functionality but let's say also provides image compression for image files found in a project. Whilst this is not vital and necessary for the package to work, installing it by default causes the installation process to take much longer due to installation of heavy modules such as `imagemin` for example.

For me it's clear that advanced functionality should then be an _opt-in_ feature instead of _opt-out_ since the latter requirers simple users to learn about the advanced functionality in order to disabled it with `--no-optional` which otherwise would be installed by default consuming extra bandwidth and disk space without reason.

For advanced users, it makes sense that if they want to install such features, they are the ones responsible for activating it during the installation process. Basically this is how many other UNIX programs work, where it's necessary to add flags to the building phase in order to have those extra features added. But not the opposite.

What do you guys think?

**Comment by sholladay** [comment]
I think the current behavior is designed to cater to the needs of authors, more than users. And that's okay. The most notable example of `optionalDependencies` that I am aware of is [chokidar](https://github.com/paulmillr/chokidar/blob/master/package.json#L41), which abstracts file system watching. There is no One True Way to do this cross-platform, so it uses [fsevents](https://github.com/strongloop/fsevents) on OS X if it can, otherwise it falls back to a lesser solution.

As a user, I don't really want to have to know or think about this. But I also don't want `chokidar` to fall over if `fsevents` couldn't be installed. So it works really well for that use case.

**Comment by zanona** [comment]
@sholladay Thanks for your feedback.

Well, that's another side of the coin where you want to install something extra in order to improve the module performance. But still, for me it's seems this is something that should be opt-in instead. The module will still work without it and for more users who want extra functionality and improvements in this case, installing the module with optional dependencies would also make sense to me?

Also, I am not completely sure I understand how making `optionalDependencies` as opt-in instead of opt-out would take the focus out of the needs of the authors? I believe it would make sense to everyone in this case. Authors that could still rely on `optionalDependencies` to extend the module functionality and users who would always benefit with lighter and faster installs by default? — Considering the point that if it's a optional dependency, the application must work without it, and hence it would make sense to first finalise the functionality without the dependency and the add that as an extra layer. This would also enforce good practice.

I can clearly understand your point about not having to know about `fsevent` in order to install the module, but then you would need to read the documentation either way in order to use it,  and it would probably be listed.

The problem here is that at the moment having `optionalDependencies` as opt-out, will always cause a lot of unnecessary work? In your use case it relies on the OS, but It would be really great to understand how it would behave on other use cases like adding extra functionality to a module that are not really vital?

Anyway, perhaps this might be good for discussion.

Thanks again for your thoughts.

**Comment by sholladay** [comment]
Sounds like you want progressive enhancement, rather than graceful degradation. That is certainly an interesting idea. But consider this.

1. Applications can't easily attempt installations at runtime. npm doesn't even have an officially supported programmatic API, and the workaround is to mess around with child processes. Compared to that, the current `optionalDependencies` behavior is a dream come true ... for authors.
2. Opt-in enhancement modules aren't really dependencies. They are plugins. And the Node ecosystem already has good patterns for this. For example, install [Hapi](https://github.com/hapijs/hapi) and then install [Boom](https://github.com/hapijs/boom). Or [Gulp](https://github.com/gulpjs/gulp) and then [gulp-jshint](https://github.com/spalger/gulp-jshint). These _could_ be packaged together, but since the main package works reasonably well without the plugin, they are shipped separately.
3. If the optional dependency has a big impact on the main package, such as the `fsevents` and `chokidar` scenario, we should optimize for the best experience out of the box. This is what happens today. The `optionalDependencies` list does not convey _you might like these_. Instead, it is to say _you really ought to have these, but I will cope without them_.

As for:

> I am not completely sure I understand how making optionalDependencies as opt-in instead of opt-out would take the focus out of the needs of the authors?

Well the author knows what their application needs to perform well. The user is in a very poor position to predict the outcome of not installing those dependencies. As a user, I would personally end up always running `npm install --install-optional`.

Finally, let's analyze the root problems being solved here. Seems like it is mainly about disk space, speed, and efficiency. My entire `~/Code` directory is a bit over 2GB in size, with many projects and their entire dependency trees. This is uncompressed, without using [npm dedupe](https://docs.npmjs.com/cli/dedupe), etc. I am a heavy Node user, but even if we assume the average developer is using twice this amount of space, that's not very much, even if you are using a small SSD.

As for performance, it is a known problem that npm v3 is slow. #10380, #8826, etc. TL;DR: the situation is improving but use npm v2 if it is really a problem. To me, this is the most legitimate concern, but should be fixed in other ways.

**Comment by zanona** [comment]
@sholladay thanks again for the insightful response.

I believe I am starting to better understand how we should see optional dependencies instead.

> Sounds like you want progressive enhancement, rather than graceful degradation. 
> Opt-in enhancement modules aren't really dependencies. They are plugins

That's exactly how I was looking at it.
After checking about `peerDependencies`, it makes sense to me that it would indeed be a good idea to make it possible for a module to connect to a plugin. Let's say that in order to extend functionality, a plugin could be built, in which case would require creating a separate module for that, but I agree.
So in the use case I have provided, the module would be responsible for performing all necessary adjustments on a project directory, and then connecting to a plugin in order to compress images. — This is a much DRY leaner structure indeed!

>  I am a heavy Node user, but even if we assume the average developer is using twice this amount of space, that's not very much, even if you are using a small SSD.

In regards size and speed, my main concern here wasn't not too much regarding users environment, but more observing this as a CI perspective? And boy, I saw a lot of libraries that literally take about 2–3 minutes to build on an CI environment considering those are not very powerful machines.
In some cases, the entire build process required is not even necessary to only use the part of the library we need. But then again, perhaps this is just a question of module architecting and that perhaps authors should be more mindful when developing modules in a way that efficiency is prioritised and extended functionality sent over to plugins?

Thanks so much for taking the time to discuss about your vision about the optional dependency system. It surely made me see it from a different aspect now.
