### ISSUE TITLE
Packages names

### ISSUE THREAD

**Issue by tamtakoe** [npm/npm#12578]
There are a lot of package with pretty names which relate to frameworks, libraries or particular technologies. F. e.
https://www.npmjs.com/package/mapper relate to SQL
https://www.npmjs.com/package/filters for 1D noise reduction
https://www.npmjs.com/package/stringify - Browserify middleware

These names are more common than these packages. It would be better to name these packages as sql-mapper, 1d-filters, browserify-stringify.

I offer to use npm name convention:
- If package is a plugin, middleware etc. relating with an framework this name must be started with framework name: gulp-plugin, react-plugin, browserify-middleware...
- If package is related to particular technology this name must include technology name: mongodb-sql-converter, amd-parser, html-minifier...

F. e. user has api mapper module which transforms data from one structure to another and he wants  to name it api-mapper, but this name is busy https://www.npmjs.com/package/api-mapper. He sees that current api-mapper package has incorrect name, because it's used for routes and must be called api-routes-mapper.

User writes request to npm support. Npm support checks that specified package has incorrect name (and it is abandoned or not popular), sends warning to api-mapper maintainer to rename module and rename it after month if author didn't do it before.

**Comment by Jokero** [comment]
I agree with @tamtakoe. npm has a lot of modules with inpropriate names. Module can have very simple and easily remembered name but this name does not reflect module functionality correctly. So sometimes as result we have almost not used (not popular, useless) module and there is no way to rename it because there is no required name convention which we can use as an argument in conversation with author of module
