### ISSUE TITLE
npm should never advise users to 'Please try running this command as root/Administrator'

### ISSUE THREAD

**Issue by breathe** [npm/npm#12588]
Its a frequent occurrence that a new-to-node/unix developer will encounter some variety of issue when setting up a new node environment.  In many scenarios where npm cannot complete the requested action, npm will 'advise' the user to 'Please try running this command as root/Administrator'.  

I can think of no scenario where this is good advice.

Experienced developers know never to run npm as root and will know the appropriate usage pattern to never need to.  Its the less experienced developers who are the ones most likely to follow this advice -- and in nearly all cases, following this advice will make it more difficult for them to learn the layout of the node_modules/ directory and become a 'more experienced node developer'.  If a user follows this advice, there's a good chance that they'll need to run npm as sudo in more and more contexts where it normally would not be needed.  If a user has ever run `sudo npm install` in the wrong context (`npm ln`, `npm install` without -g -- and indeed in some cases -- `npm install -g`) then the places to which the requirement to run 'sudo npm install' can spread are surprising and can often require more than beginner knowledge to easily untangle.  Its easy for an experienced dev to cleanup, but those who aren't experienced really have an uphill battle.

Given: 
(1) running npm as root is generally a pretty bad idea from a security perspective
(2) most scenarios where running npm as root seems warranted are usually better solved with other approaches
(3) the need to run as root can spread across npm package environments in subtle ways

I'd like to see:
(1) _ideally_ npm install without -g always refuses to run as sudo 
(2) npm never advises users to run as sudo

**Comment by fr-kshibata** [comment]
I sense some interesting debates coming up!

**Comment by wpccolorblind** [comment]
+1

**Comment by breathe** [comment]
#12928

**Comment by ryankurte** [comment]
Totally concur with @breathe. Since #12928 is dead, what are the options here?

Suggesting NPM be run as root is somewhere between a bad idea and criminally negligent. 
There is no /good/ reason to run an entirely untrusted package manager with root permissions, and suggesting so exposes unwary developers to unnecessary risk.

The suggested replacement of `Please adjust file ownership or permissions -- or run this command again as a different user.` is good, but as was raised in the PR doesn't immediately solve the users problem. Lots or unix-ey things don't, and expect you to go learn, but it is probably nicer to offer a resolution.

So could we:

1. look at what failed and why (and possibly suggest a change). For example, `You tried to install HERE, which is owned by X with permission Y. If you have permission to write to this location, run Z to change permissions`. It's not going to be the right thing to do every time, and may require some filtering for locations in which it is sane to suggest such, but at least it has an action point.

2. ensure the global node_modules is user writable at install, have a `brew doctor` like checkup to find and attempt to resolve any issues. You could then make node refuse to run with sudo as suggested above, perhaps with a mechanism like `--no-preserve-root` if you have some desperate need for superuser.

3. warn in big and angry letters when running npm as a super or root user

4. as in the PR, suggest alternates such as the use of NVM or other methods of vendoring (ie. installing locally)

**Comment by kenichi-shibata** [comment]
I think this issue still has merit. I'm surprised no one is interested, Actually having to use sudo, not only has security issues, But also can break your production code, For once, if you try to  sudo npm -g everything as a privileged user and you use a bot that has no sudo access, then it will be disastrous in production. Granted its idiotic but yeah., Still an issue
