### ISSUE TITLE
Atom Script package - npm WARN addRemoteGit 

### ISSUE THREAD

**Issue by arias3601** [npm/npm#12593]
I got this error when I tried to install the Script Package into Atom. It originally told me I did not have git installed, and after I installed it, it started giving me this error. Anyone know what is wrong? 

npm WARN addRemoteGit git://github.com/monsterkodi/node-simple-plist.git pre-existing cached repo C:\Users\Arias3601.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 points to https://github.com/arias3601/cit261TeamNoProcrastination.git and not git://github.com/monsterkodi/node-simple-plist.git
npm ERR! git clone --template=C:\Users\Arias3601.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Arias3601.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\Arias3601.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\Arias3601.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\Arias3601.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: read error: Invalid argument
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Arias3601\AppData\Local\atom\app-1.7.3\resources\app\apm\bin\node.exe" "C:\Users\Arias3601\AppData\Local\atom\app-1.7.3\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Arias3601\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Arias3601\.atom\.apmrc" "install" "C:\Users\ARIAS3~1\AppData\Local\Temp\d-11645-181992-1hbcsh\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Arias3601.atom.apm_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: read error: Invalid argument
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by alves** [comment]
+1 with slightly different error (proposed solution for use "https" instead of "git" applied, but gave the same error - https://github.com/npm/npm/issues/5257)

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\me\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\me\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\me\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\me\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\me\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\me\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\me\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\alvesso\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\me\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\alvesso\\.atom\\.apmrc" "install" "C:\\Users\\me\\AppData\\Local\\Temp\\d-116419-4408-1k777nu\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\me\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by shawlhar** [comment]
Empty your cache
