### ISSUE TITLE
`npm owner add` not working

### ISSUE THREAD

**Issue by jenius** [npm/npm#12610]
Using `node@6.0.0`, `npm@3.8.9`. To reproduce, try to add an owner to any npm package. I'm getting back the following:

```
npm ERR! registry error parsing json
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
```

I'm running the command `npm owner add someuser somepackage` - I have double checked that the package is published and the user does exist.

The loading bar stalls indefinitely and the command has to be cancelled with `Ctrl-C` in order to exit.

*Update*: let it run for like 10min+ and it finally came up with this:

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! owner mutate Failed to update package metadata
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "add" "kylemac" "rooftop-client"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html><body><h1>504 Gateway Time-out</h1>
npm ERR! The server didn't respond in time.
npm ERR! </body></html>
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeff/Sites/rooftop-client/npm-debug.log
```

**Comment by xdumaine** [comment]
I've been added to a package both online and via cli, and both fail. I'm listed as an owner on the package, but I cannot publish to it. For reference - https://www.npmjs.com/package/webrtc-troubleshooter

**Comment by rmg** [comment]
psst.. @ehsalazar would it surprise you to know I'm seeing the same problem?

**Comment by piscisaureus** [comment]
https://github.com/npm/npm/issues/12521

**Comment by othiym23** [comment]
Hey all, I'm going to close this issue (and #12521 – thanks for the heads up, Bert) and redirect all y'all over to [`npm/registry`](https://github.com/npm/registry/issues), as this is an issue in the npm registry back end. The good news is that the registry team is aware of this issue, but the bad news is that it may not get resolved before the beginning of the week. If you need to escalate, you can also contact <mailto:support@npmjs.com> directly, but since it's the end of the work week for our support and registry teams, the odds are that we still won't get to this until Monday. Thanks for your time, and your patience!

**Comment by othiym23** [comment]
More people encountering this issue: https://twitter.com/davglass/status/728681870628556800

**Comment by othiym23** [comment]
I went ahead and created npm/registry#14 for @npm/registry-team to use for tracking purposes.
