### ISSUE TITLE
Range specifier when installing package below 1.0

### ISSUE THREAD

**Issue by ericandrewlewis** [npm/npm#12635]
The default range specifier when installing package is `^`, meaning "install this version or any minor update after it." e.g. `^1.2.1` will install anything up to `2.0`. This is a good default for packages which are at 1.0 or beyond, as backwards-compatible changes and bug fixes may be added in minor versions, and not incompatible API changes. The main package maintainer must decide explicitly to upgrade a dependency to the next major version.

Below 1.0, anything can change at any time. I wonder if another range specifier would be more useful as a default for packages below 1.0?

**Comment by othiym23** [comment]
Take a look at [the docs for `^`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), which already take into account the iffy semantics of versions < 1.0.0, and try to capture the intent of the [SemVer specification](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase). [`~` has a slightly different flavor](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) for handling versions < 1.0.0. (You can switch which range operator is used by npm by default for you when using `--save{,-dev,-optional,-bundle}` by running `npm config set save-prefix '~'.)

One of those two should handle the vast majority of desired use cases for 0.x versions. My concern about choosing which range operator to use based on the current version of a package is that it introduces potentially confusing new behavior – does npm automatically switch to a different operator once the package moves past 1.0? (Given that people sometimes explicitly set the range for specific packages, this could be, at best, suprising.) Does it warn? As such, I'm deeply reluctant to further complicate npm's semver handling. Because I think the above links should address your concerns, I'm going to close this issue as resolved, but if you still have concerns, let me know.
