### ISSUE TITLE
apm install script generates this error - npm issue

### ISSUE THREAD

**Issue by skyridertk** [npm/npm#12713]
Script is failing to install on Atom text editor. I have attached the log file.
[npm-debug.txt](https://github.com/npm/npm/files/265252/npm-debug.txt)

**Comment by KenanY** [comment]
@skyridertk From the log, it appears as though your connection to `github.com` is consistently timing out. Usually this is caused by a proxy or firewall either blocking the site completely or simply the `git:` protocol. So, are you behind a proxy or firewall? Have you configured `npm`/`git` to use your proxy, or configured your firewall to allow these connections to be made?

**Comment by skyridertk** [comment]
NPM is configured to connect to proxy. Other packages are installing. Script is the only package throwing this error. Im out of options

**Comment by skyridertk** [comment]
Can you please generate a 32bit deb file of SCRIPT if possible?

**Comment by KenanY** [comment]
@skyridertk 

> Can you please generate a 32bit deb file of SCRIPT if possible?

What do you mean by this? Can you explain how this might solve your issue?

**Comment by skyridertk** [comment]
Script is blocked. So im saying you generate a deb file for linux ubuntu 32
bit n share the link 4 e file here.

**Comment by KenanY** [comment]
@skyridertk Sorry, I have no idea what "script" is in this context. If you're saying that it is being blocked, then I would suggest you try to... _un_-block it? That would probably be the most permanent solution that would prevent further issues with any other packages. This issue tracker is for bug reports and feature requests for the `npm` CLI and so far this issue is not looking like either of these.

**Comment by skyridertk** [comment]
Ok i understand :D

**Comment by skyridertk** [comment]
I assumed u read the question
