### ISSUE TITLE
Cannot publish @angular/common@2.0.0-rc.1 to the npm repository. Reference to issue #12670

### ISSUE THREAD

**Issue by jags213** [npm/npm#12749]
Hi Team,

The issue  #12670 was closed by suggesting to upgrade npm , but when the upgraded npm version is used, I still get the same error, please help as this needs to resolve ASAP. Please find the error details below:-
--------------------------------
           Execution
--------------------------------

Running:  /usr/local/node-v4.2.4-linux-x64/bin/npm install @angular/common@2.0.0-rc.1 --registry http://localhost:8080/nexus/content/repositories/npmjs-proxy

npm ERR! registry error parsing json
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node-v4.2.4-linux-x64/bin/node" "/usr/local/node-v4.2.4-linux-x64/bin/npm" "install" "@angular/common@2.0.0-rc.1" "--registry" "http://localhost:8080/nexus/content/repositories/npmjs-proxy"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12

npm ERR! Unexpected token <
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR!
npm ERR!     <link rel="icon" type="image/png" href="http://localhost:8080/nexus/c/favicon.png">
npm ERR!     
npm ERR!
npm ERR!     <link rel="stylesheet" href="http://localhost:8080/nexus/c/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</h1>
npm ERR!     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/npm-debug.log

Exited due to NPM error.

Thank You,
Jag

**Comment by othiym23** [comment]
Hi! You needed to upgrade your CLI because npm before version 2.0.0 didn't understand scopes and would never have successfully published a coped package. The issue you're running into now is new, and due to either how Sonatype Nexus is configured for you, or how Sonatype Nexus is meant to be used as a service for package publishing in general. The CLI team doesn't have much experience working with Nexus, so I suggest you either check its docs, consult whoever set it up for you, or file an issue on Sonatype&/ issue tracker / help forum (I don't know what they use for support). As far as I can tell from the output you've posted, the npm CLI is working as intended.

**Comment by jags213** [comment]
Hi Othiym,

Thank you for the information provided, I'm just curious to know if the way npm command to install the module is right or not. So the npm command is npm install @angular/common@2.0.0-rc.1  , is there any other way i could pass the module name differently than the above mentioned one ?? im skeptical about the way module name is mentioned there - its starting with a special character "@" and also has a "/" in the middle. So want to know if that matters or if there is any other way we can specify this ??

**Comment by othiym23** [comment]
The leading `@` tells the CLI and the registry that the package has a scoped name and isn't a GitHub-hosted dependency (which is what a dependency with a `/` in it would mean otherwise). The `/` separates the scope from the rest of the package name. Because it's all one name, there's no other way to specify the name. All versions of npm newer than 2.0.0 support this syntax. As I said above, the issue here is with your local registry, not the CLI.

**Comment by jags213** [comment]
We decides to install these dependencies locally on the build server - would it be possible with npm install?

**Comment by jags213** [comment]
Im trying to install these @angular/common and related scoped packages on the server itself where the build happens instead of publishing it to the nexus registry.. Do you have any specific process to do that ? I get error as it tries to connect to github and will not install the package.

**Comment by jags213** [comment]
This issue can be closed as we decided to source checking our scoped packages while we parallely working on upgrading nexus to 3.0 ..
