### ISSUE TITLE
How to publish a package with bug fixes in same version?

### ISSUE THREAD

**Issue by mathikp** [npm/npm#12762]
I have published a package with version 1.1.1. I have made some changes in the code and pushed to the repository. Now I need to publish the package with the same version 1.1.1 again. How to do this? There is no info about this in UG.

**Comment by othiym23** [comment]
Because npm is built on [`semver`](https://docs.npmjs.com/getting-started/semantic-versioning), and because the primary npm registry [doesn't support publishing the same package version twice](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f), what you're trying to do isn't possible. Fortunately, it's as easy as running `npm version patch && npm publish` to update `package.json` to update your package's version and publish the new version. If you're using git to manage your package, npm will even tag your source tree with the new version as part of bumping the patch version.

Because this is how the CLI (and registry) are designed, I'm going to close this issue. I hope the above links are useful. Thanks for your time!
