### ISSUE TITLE
getaddrinfo EAI_AGAIN registry.npmjs.eu:80

### ISSUE THREAD

**Issue by vmprashantk** [npm/npm#12798]
error during installation npm install -g cordova ionic
[npm-debug.zip](https://github.com/npm/npm/files/276677/npm-debug.zip)

**Comment by vmprashantk** [comment]
please help me

**Comment by p4ulolol** [comment]
I've got the same problem... And appearently no solutions on the internet. This problem was caused (in my case) by the installation of a proxy software (that I then uninstalled), but I think that everytime it's because of a proxy issue, so check out these parameters.
You can also try these commands :
`npm config rm proxy
npm config rm https-proxy`
