### ISSUE TITLE
Can't install scoped package that has bundledDependencies

### ISSUE THREAD

**Issue by brentonhouse** [npm/npm#12834]
If I have a scoped package that has bundledDependencies, when I try to install that scoped package, I get an error:

```
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/brentonhouse/Documents/bundle-test2/node_modules/.staging/lodash-e5e37c02' -> '/Users/brentonhouse/Documents/bundle-test2/node_modules/@brentonhouse/bundle-test1/node_modules/lodash'
```

If I make the `bundle-test1` package to be non-scoped, it works fine.

This issue seems similar to #9175 but it is the reverse situation.  _(i.e. scoped package bundling non-scoped package vs non-scoped package bundling scoped package)_

**Comment by NodeGuy** [comment]
Me too.

**Comment by einsty** [comment]
I am experiencing the same issue except it occurs for me on node_modules/abbrev instead of node_modules/lodash as it does for @brentonhouse .

```node -v && npm -v
v4.1.2
3.10.5```

**Comment by gagle** [comment]
@isaacs This error prevents us to deploy typescript apps via npm pack. We have modules written in TS that have @types/... as dependencies and we use these TS modules as dependency of other TS modules, so we need to put @types as dependency instead of as devdependency. This breaks our npm packs. npm emits an error when installing modules with @types as dependency.
