### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by saimouli** [npm/npm#12890]
![capture](https://cloud.githubusercontent.com/assets/14081959/15631100/b3953a96-2524-11e6-810a-7267a2a609dd.JPG)

Debug log- 
![capture](https://cloud.githubusercontent.com/assets/14081959/15631106/e2ad1b82-2524-11e6-8488-43ab5c2ff267.JPG)

**Comment by KenanY** [comment]
Hi @saimouli! Do you have a `"start"` script defined in your `package.json`? The error log is saying that you do not. Hence, when you try to run `npm start`, you are getting this error since `npm` has no idea what you would like it to do. The solution is to simply defined a `"start"` script that defines what you would like `npm` to do:

``` json
{
  "scripts": {
    "start": "echo hello"
  }
}
```

**Comment by KenanY** [comment]
@saimouli Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
