### ISSUE TITLE
npm show react version outputs weird character

### ISSUE THREAD

**Issue by SimenB** [npm/npm#12919]
`npm show react versions`

I have no idea why it happens, but `0.13.1` outputs some chars that looks out of place

![image](https://cloud.githubusercontent.com/assets/1404810/15702484/89d3dcc6-27e0-11e6-9413-c127a0ea7c27.png)

**Comment by othiym23** [comment]
This is due to a bug introduced in Node.js 6.0.0 (and fixed in 6.2.0) where a fix to stdio in libuv unintentionally changed how I/O blocks / is buffered on OS X. That output is a consequence of `npmlog` resetting a console line as it turns itself off, which works as expected when stdio is working the traditional way. Because this is a change to Node that's since been reverted, I'm going to close this issue, but a patch that forces stdout and stderr to be blocking under the two affected versions of Node would be welcome. Thanks for your time!
