### ISSUE TITLE
npm ERR! self signed certificate in certificate chain

### ISSUE THREAD

**Issue by kgao8888** [npm/npm#12987]
Hello, trying to install grunt on my local. got following errors. Please help....

C:\Windows\system32>npm install -g grunt-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
tall" "-g" "grunt-cli"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

[npm-debug.log.txt](https://github.com/npm/npm/files/303320/npm-debug.log.txt)

**Comment by suryarjuna** [comment]
Hey @kgao8888,
So I faced the same error while installing npm on my machine. Going through various sources I figured out that the error is due to npm not supporting self signed certificates anymore.
Well, the possible solutions are

1. Upgrade your npm version.
                    
 `npm install npm -g --ca=null`
2. Ask npm to stick to using known registrars.
                    
`npm config set ca=""`

Happy Noding!
