### ISSUE TITLE
Roaming profile UNC path break git clone

### ISSUE THREAD

**Issue by roydukkey** [npm/npm#13026]
I believe the issue is that Roaming Profile paths are breaking git clone. Here is my [npm-debug.log](https://gist.github.com/roydukkey/64ead074f4b0b632411ffa80107efebb#file-npm-debug-log-L621). `node 4.2.2` `npm 3.9.6`

I believe the evidence is on [line 621](https://gist.github.com/roydukkey/64ead074f4b0b632411ffa80107efebb#file-npm-debug-log-L621).

Can this be confirmed?

**Comment by othiym23** [comment]
The path is being passed to Git correctly (which is to say with the correct number of leading backslashes), and for whatever reason Git is interpreting them incorrectly. Since npm is just acting as a wrapper around the locally installed version of Git, there's nothing that the CLI can do to remediate this. Which form of packaging for Git are you using?

**Comment by roydukkey** [comment]
I'm using Git v2.8.3.windows.1 from https://git-for-windows.github.io/.

**Comment by roydukkey** [comment]
Same result with SourceTree embedded Git v2.7.4 (+ git-lfs v1.1.1).
