### ISSUE TITLE
npm publish and pack leaving out files.

### ISSUE THREAD

**Issue by legodude17** [npm/npm#13106]
I published a package (https://npmjs.com/package/node-command) and it was missing a file (cli.js). I have it in my files array. It was also listed in my bin. Publish works fine, but when I try to install it I get: ENOENT: no such file or directory, chmod '/home/jdb/Desktop/Code/tand/node_modules/node-command/cli.js'.
[npm-debug.txt](https://github.com/npm/npm/files/322518/npm-debug.txt)

**Comment by othiym23** [comment]
Closing as duplicate of #5082. Give `npm@next` (`npm@3.10.1` as of today) a shot, and ensure that `npm pack` produces the expected tarball.

**Comment by legodude17** [comment]
`npm@3.10.1` works.

**Comment by factoidforrest** [comment]
For anyone stumbling upon this, npm pack and publish respect any package.json files you have in the directory tree.  In my case, I had a module that templated out another module with ejs, but because npm was treating the package.json like it was reading the `files` from there and not bundling the entire module.
