### ISSUE TITLE
unable to install npm 

### ISSUE THREAD

**Issue by ankitpachori** [npm/npm#13151]
Hi ,
I am not able to install npm through git bash.
[package.txt](https://github.com/npm/npm/files/328237/package.txt)

**Comment by KenanY** [comment]
@ankitpachori The log does not show that you are trying to install `npm` itself. Rather, it just shows that you are running `npm install` in order to install some dependencies you have defined in your `package.json`. Can I see the `package.json`, at leas the `"dependencies"` and `"devDependencies"`?

**Comment by ankitpachori** [comment]
@KenanY 
[package.txt](https://github.com/npm/npm/files/334358/package.txt)
