### ISSUE TITLE
Enforce valid licensing rules

### ISSUE THREAD

**Issue by thomfoolery** [npm/npm#13154]
Prevent the install of packaged dependancies that do not meet the defined license rules.

Example:
```
{
  "name": "my-package",
  "version": "2.0.0",
  "license-whitelist: ["MIT"],
  "license-blacklist: ["GNU"],
  ...
}
```

**Comment by othiym23** [comment]
This sounds like an excellent use case for a tool external to the CLI itself, possibly added as a lifecycle script to `preversion` or `prepublish`. I don't think this makes sense to add to the core CLI, though. The rules around license validation can be complex on larger projects, to the point that a "worse is better" one-size-fits-all solution would actually make things harder for teams maintaining those projects, rather than easier. That said, you should check out http://fossa.io/, which (I think) is a very useful tool to use in license auditing of OSS projects. It might be exactly what you need!

Thanks for your time!
