### ISSUE TITLE
atlas-connect install error

### ISSUE THREAD

**Issue by sonnymyet** [npm/npm#13170]
Hi I'm having error installing atlas-connect tool. Not sure if i'm posting at the right place tho but help would be very much appreciated. 

[npm-debug.txt](https://github.com/npm/npm/files/332213/npm-debug.txt)

**Comment by KenanY** [comment]
@sonnymyet The error indicates a failed connection with `github.com`. More often than not, this is an issue with your internet connection and not with `npm`. Perhaps you are behind a proxy or firewall?

**Comment by sonnymyet** [comment]
@KenanY Thanks. I'll try talking to my network admins. In the mean time, is there a way I could download the atlas-connect tool separately to install rather than going through the command line? Thanks for your help. =)

**Comment by KenanY** [comment]
@sonnymyet One way might be to download the tarball:

``` bash
$ npm info atlas-connect dist.tarball
https://registry.npmjs.org/atlas-connect/-/atlas-connect-0.4.33.tgz
```

then install each dependency manually; if one requires something hosted on github you could download the respective tarball for that repository from the github page itself.

Sorry if I didn't explain it well... it's a very convoluted solution in my opinion since there's no current way to tell `npm` to install-this-module-but-ignore-github-stuff (which would be complicated to do anyhow).

**Comment by KenanY** [comment]
Closing as not an issue with `npm` itself. Can reopen if this is not the case.
