### ISSUE TITLE
npm has a line ending problem

### ISSUE THREAD

**Issue by wayofthefuture** [npm/npm#13203]
I realize this issue has been addressed multiple times in the past, but I am bringing it back up because as it stands, here is what is happening:
- The NPM Package manager repository is becoming littered with cross-platform incompatible packages, severely hindering NPM's viability as a cross-platform solution.

The problem is that the Windows git-scm default install sets the core.autocrlf setting to true. This, by default, replaces the line endings with CRLF when you do a git clone. This means that every time I clone the repository and theN publish it to NPM, I have now published a broken package. Multiply this times a million and you get the idea. Tons of "no such file or directory" errors on a cli !# /usr/bin/env node line.

NPM is the perfect abstraction layer / pipe to have a one in - one out solution for the problem. It should not be left up to the windows user to always have to deal with this problem, or even be aware of how line endings work on windows vs linux. The end user should not have to deal with these kind of technical details. It is this kind of problem that hurts NPM way more than it helps them, and expecting the windows users to continually manage this problem on their own is just unrealistic, as well as continues to hurt NPM.

This is a major problem, and I can't believe I wasted so many hours on it.

**Comment by othiym23** [comment]
You're right that in an ideal world, the CLI would handle this for you transparently. However, the CLI knows very little about the contents of the files that it packs into tarballs and publishes, and there's a decent amount of special-purpose logic in Git to handle this use case for various file types. I'm specifically thinking about the rules that Git uses to separate binary files (like images) from source text, which is at least partially heuristic and requires options when staging files via `git add` to ensure that end users can override the heuristics when Git gets it wrong. Porting that to the CLI is a decent amount of work and poses some distinct UX challenges (because the CLI doesn't have a way to configure how publishing is staged, aside from the `"files"` stanza in `package.json` and `.npmignore`).

Also, the Node.js interpreter doesn't care about line endings. Aside from the annoyances this poses to tooling (i.e. editors), this is only really an issue for scripts interpreted by Unix (i.e. with shebang lines). A fix that wouldn't have to take on the full complexity of Git-style heuristics would be just to ensure that files with shebangs have only LF endings. It's still a decent amount of work, but a patch to that effect would be very helpful.

Until then, a workaround is to configure `core.autocrlf = false` and ensure that repos are cloned with LF line endings. If you're not doing a lot of stuff with VS (or are a fan of Notepad++), it may be possible to configure this globally. If not, it's possible on a per-repo basis. I agree that the current behavior is annoying, but the CLI team is pretty loaded up with work, so it may be quite a while until we get around to addressing this. Thanks for your time!

**Comment by wayofthefuture** [comment]
You are right on so many levels. I like to think about things from the masses though, and I know the masses are usually the same guys who are behind the reasons why xhtml failed and html5 didn't (draconian behavior). Additionally, environments are isolated, and programs run with basic assumptions on that environment. A unix environment is an environment of LF's while windows is an environment of CRLF's. IMO it is up to the abstraction layer above the environment to normalize the code before injecting it into the environment. GIT and Node both unify the platforms, which is huge and brings together all of us with day jobs stuck on windows computers (I'd switch to Linux in a heartbeat if I wasn't bound to the d$#n .Net framework) but in the end GIT and Node are environment injectors and by that statement alone I believe BOTH should be responsible for the normalization before injection into the environment. And even if GIT and NPMshouldn't be responsible, it doesn't change the problem of the packet manager becoming littered with incompatible programs.

The core autocrlf setting to false means that GIT would then became littered with CRLF, which would then just shift the problem to a different place. I have mine set currently to 'input' and that seems to work. In the meantime there are millions of people that aren't thinking about this and publishing to NPM.

It's not as easy as doing a regex replace on npm publish? If windows regex replace /r/n with /n, and if unix leave as is? Thanks.
