### ISSUE TITLE
Delete colresizable-egis from registry - npm

### ISSUE THREAD

**Issue by djhvscf** [npm/npm#13207]
Hi,

Can you delete this package from the registry? It is no longer used nor maintained
https://www.npmjs.com/package/colresizable-egis

Thanks

**Comment by othiym23** [comment]
A few months ago, npm [made some changes](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) to our policy regarding package unpublishes. You'll need to contact <support@npmjs.com> in order to get this package unpublished. Since this is something handled by the support engineers and not the CLI team, I'm going to close this issue. Thanks for your time!

**Comment by djhvscf** [comment]
@othiym23 thanks
