### ISSUE TITLE
Shrinkwrapping locally developed module gives extraneous package error.

### ISSUE THREAD

**Issue by sam1111** [npm/npm#13202]
Hi,

I have 2 components of my application api server and backend. Some modules were of use to both components so I put them in another component named common. Now when for install dependencies we need to do npm install and npm install ../../common. This all works fine and as expected but when I do npm shrinkwrap in either of api server or worker I get this error 

extraneous: backend-common@1.0.0 

Is there a way I can achieve what I am looking to do?

**Comment by sam1111** [comment]
Hey, do you have any timeline for this fix?

**Comment by iarna** [comment]
```
extraneous: backend-common@1.0.0
```

@sam1111 Is `backend-common` in your `package.json`?  If you want to shrinkwrap local modules you need to add them to your `package.json` like any other module. (You can do this with `npm install --save ../../common`)

That said, I think you're trying to do something that we can't promise will always work:

> Some modules were of use to both components so I put them in another component named common.

So what you're saying is that you have two different projects that happen to share a bunch of dependencies. Instead of having them directly depend on things you thought you'd have them instead share a common third package that in turn depends on all of the shared dependencies?

This isn't exactly supported. While it does work _most of the time_, the `npm` cli _may_, at its discretion, choose to install some of those subdependencies INSIDE the common dependency where you won't be able to require them from your top level package.

There's really no facility currently available for what you're trying to do. The best/worst approach I can think of would be to explicitly export those dependencies from your `backend-common` package, eg something like this as your `index.js`:

```
exports.module1 = require('module1')
exports.module2 = require('module2')
// etc
```
Where `module1` & `module2` are your various shared dependencies.

And then require your dependencies with:
```
var module1 = require('backend-common').module1
// instead of: var module1 = require('module1')
```

**Comment by iarna** [comment]
I'm going to close this, but if you run into further issues please feel free to open a new issue or contact support at https://www.npmjs.com/support
