### ISSUE TITLE
npm unpublish react-native-loading-spinner-overlay@0.1.2

### ISSUE THREAD

**Issue by niftylettuce** [npm/npm#13297]
I need to unpublish this version because it affects users on different versions of React Native.

Can you please unpublish version 0.1.2 of the package react-native-loading-spinner-overlay?

Thank you so much

**Comment by othiym23** [comment]
@niftylettuce You should contact support@npmjs.com to request that a package be unpublished, as this repo is meant for handling issues for the npm CLI. npm's support team is dealing with an unusually high volume of tickets due to a production incident (see #13284 for details), so it may take a day or two for them to get back to you, but I promise you they will. Thanks for your time and patience!

**Comment by niftylettuce** [comment]
done
