### ISSUE TITLE
npm@3.x uninstall does not trigger the script from package.json

### ISSUE THREAD

**Issue by all3fox** [npm/npm#13381]
#### What's going wrong?

`npm uninstall path/to/local/module` does not trigger the uninstall script for that module 

#### How can the CLI team reproduce the problem?

First, create a simple local project:

```
mkdir project && cd project && npm init --yes >/dev/null
echo "console.error(\"hello, world\")" > index.js
```

Now open up package.json and add this to the "scripts" section:

```
"scripts": {
    "install": "echo \"INSTALL\"",
    "uninstall": "echo \"UNINSTALL\""
}
```

Now go to some other directory, create a second project and attempt an install/uninstall cycle:

```
cd .. && mkdir project2 && cd project2
npm init ---yes > /dev/null
npm install ../project
npm uninstal ../project
```

The `npm install ../project` does trigger the "install" script from package.json of the first project. However, `npm uninstall ../project` does *not* trigger the "uninstall" script. This seems contrary to what is [promised by the documentation for the uninstall script][1].

This affects me in the real world jzaefferer/commitplease#66

This issue might be relevant here: npm/npm#10379

I am willing to try to solve this if it is confirmed to be a bug.

### supporting information:

 - `npm -v` prints: `3.10.3`
 - `node -v` prints: `v6.3.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X, or Linux?: `ArchLinux`

[1]: https://docs.npmjs.com/misc/scripts

**Comment by othiym23** [comment]
You may be slightly misunderstanding how `npm uninstall` works, and the output you're getting from `npm uninstall ../project` may be misleading enough to be unhelpful. 

This is what I get:

```console
ogd@bauchelain ~/D/p/test-uninstall-target> npm uninstall ../test-uninstall
npm WARN test-uninstall-target@1.0.0 No description
npm WARN test-uninstall-target@1.0.0 No repository field.
```

but!

```console
ogd@bauchelain ~/D/p/test-uninstall-target> ls node_modules/
test-uninstall
```

and:

```console
ogd@bauchelain ~/D/p/test-uninstall-target> npm uninstall test-uninstall

> test-uninstall@1.0.0 uninstall /Users/ogd/Documents/projects/test-uninstall-target/node_modules/test-uninstall
> echo "UNINSTALL"

UNINSTALL
- test-uninstall@1.0.0 node_modules/test-uninstall
npm WARN test-uninstall-target@1.0.0 No description
npm WARN test-uninstall-target@1.0.0 No repository field.
```

That is to say, that running uninstall on the package using the relative path is resulting in a null operation, but uninstalling what's installed in `node_modules` both uninstalls the package _and_ runs the `"uninstall"` lifecycle script as promised.

The CLI team would be happy to land a patch to the documentation for `npm uninstall` to clarify that uninstalling only applies to packages currently in the local `node_modules` (or the global `node_modules` if `--global` / `-g` is used), but otherwise, everything's working as designed, so I'm going to close this issue. Thanks for your time and the repro case!
