### ISSUE TITLE
Still possible to publish case-sensitive packages.

### ISSUE THREAD

**Issue by tolmasky** [npm/npm#13406]
At some point npm stopped allowing uppercase in the package names, this is referenced here: https://github.com/npm/npm/issues/3914#issuecomment-24878907

However, it is still possible to do so by simply changing the name in the package.json yourself. I just published this: https://www.npmjs.com/package/Underscore-1

Had I named it "Underscore" instead of "Underscore-1" it would have successfully overlapped twice and been a potential for people to install the wrong package. I first noticed something was up trying to figure out the Q vs q situation (outlined here: https://tonicdev.com/tolmasky/why-does-require-q-not-work ). I figured Q was a very old package, but then noticed it was actually published just 2 months ago.

I believe this is a security issue because if people had previously gotten it by doing npm install Q, now as long as a version of Q is published with a matching version, on deploys people will mistakenly get the wrong Q (which could be malicious).

I think the server should be disallowing case sensitive packages instead of the client app.

**Comment by othiym23** [comment]
This is something that the CLI code base is agnostic upon, because not all registries disallow mixed-case package names. There's a bit of history around this for the primary npm registry, but you've discovered a genuine lacuna in how it currently works; the registry team knows about it, but for a variety of reasons hasn't gotten around to closing the hole yet. Because this isn't a CLI issue, I'm going to close this, but I encourage you to open an issue for this (if one doesn't already exist) over on [`npm/registry`](https://github.com/npm/registry/issues); we all work together, but we also have enough stuff going on that it's not going to move forward if the issue is open over here. Thanks for the the complete error report, and thanks for your time!
