### ISSUE TITLE
npm install won't upgrade to latest package version with `*` or `x`

### ISSUE THREAD

**Issue by alallier** [npm/npm#13459]
#### I'm opening this issue because:

  - [ ] npm install is not updating to latest on `*`.
  - [ ] npm install is not updating to latest on `x`.

#### What's going wrong?

npm will not upgrade a package to the latest with `*` or `x` specified in `package.json`

### Supporting information:

![demostarnotupgrading](https://cloud.githubusercontent.com/assets/13004518/17065516/3f7c1370-5010-11e6-8b26-dcef3a16668d.gif)

[Semver](https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-consumers) - According to this documentation npm should upgrade major releases with a `*` or `x`.

**Comment by KenanY** [comment]
@alallier `*` means that any non-pre-release version is sufficient. Since you already have `pg@4` installed, and it indeed matches `*`, `npm` is not gonna try and fetch a newer version.

**Comment by alallier** [comment]
Having `^4.4.0` in your package, `4.4.1` currently installed, with an available package of `4.3.2` will upgrade you to `4.3.2` even though `4.4.1` meets the requirement of `^4.4.0` but the same behavior doesn't exist for `*`

```
Patch releases: 1.0 or 1.0.x or ~1.0.4
Minor releases: 1 or 1.x or ^1.0.4
Major releases: * or x
```

**Comment by KenanY** [comment]
@alallier I don't quite understand. `pg@^4.4.0` gets me `pg@4.5.6`. Could you expand on what the issue is? If I install `pg@4.4.0`, having `pg@^4.4.0` in my `package.json`, and then run `npm install`, the dependency is _not_ updated, because the installed version already matches the desired version range. The behavior is exactly like `*` and is 100% intentional and expected.

**Comment by alallier** [comment]
@KenanY You are correct, I just tested your use case. Sorry about that and thank you for the quick replies
