### ISSUE TITLE
how/what to cleanup after npm install?

### ISSUE THREAD

**Issue by xblox** [npm/npm#13486]
Hi,
when using a few standard packages, my node_modules folder contains hundreds of megabytes garbage. I cleaned all modules by hand and came down to 80% less resource waste. 

So after that I did build now file/directory glob patterns (hundreds) to delete all that unneeded files but I am wondering what the official route is to preserve resources? 

Problem is: we can't make "Internet" (poorer people/areas don't have such thing or its very expensive) as a requirement and so we have to ship with everything included. 

Btw., biggest resource wasters are
- build files after compiling native modules (node-gyp)
- well, Node.js it self when it comes to native modules: You have to ship the same npm install for every platform: node_modules_osx, node_modules_windows-x64,... . This can sum up easily to a gigabyte if you don't clean up. 
- all sorts of meta files: editor configs/license files, people leave even pictures in their packages

thanks, I'd appreciate any hint. This isn't only about getting my apps smaller but also implementing some green policies.

**Comment by KenanY** [comment]
> You have to ship the same npm install for every platform: node_modules_osx, node_modules_windows-x64

You mean shipping to like production servers?

> all sorts of meta files

[`"files"` or `.npmignore`](https://docs.npmjs.com/files/package.json#files)

**Comment by gbaumgart** [comment]
KenanY : shipping = yes, sort of. its actually part of a pre-compiled desktop/server application with everything embedded (for all platforms).

not sure about https://docs.npmjs.com/files/package.json#files because reallity shows that node-js developers don't bother much about .npmignore or their waste and so it can be fully ignored in that matter. its as said all that files after node-gyp and many other useless files: *.md, *.txt, *.py, *.s, *.c,.....

**Comment by KenanY** [comment]
ref. https://github.com/npm/npm/issues/5264#issuecomment-233099318
