### ISSUE TITLE
npm escapes slashes in HTTP requests for scoped dependencies

### ISSUE THREAD

**Issue by httpdigest** [npm/npm#13541]
#### I'm opening this issue because:
- npm unexpectedly escapes a slash (/) when trying to install a scoped dependency via `npm install @angular/core`.
#### What's going wrong?

npm unexpectedly escapes a slash (/) when trying to install a scoped dependency via `npm install @angular/core`
#### How can the CLI team reproduce the problem?
- Setup a npm repository (for example via Nexus OSS). We are using Version 3.0.0-03
- make a request for installing a scoped package, such as `@angular/core`
- observe that the log file in Nexus shows `/@angular%252fcore`
- whereas when requesting that same package via a browser (Chrome 52) on the url `<nexus-host>/repository/npm-proxy/@angular/core` nothing is being escaped and the URL which hits Nexus is `/@angular/core`
- when accessing the package via a browser (without escaping) everything works and the correct package meta-data is being returned as JSON
- when accessing via npm, the return is: `Non URL-safe name: @angular%2fcore : nexus3`
  - `npm -v` prints: 3.10.6
  - `node -v` prints: v6.3.1
  - `npm config get registry` prints: <internal nexus 3.0.0-03 repository>
  - Windows, OS X, or Linux?: Windows 7 x64

**Comment by joeskeen** [comment]
I believe that the issue is with Nexus.  I also am having issues with Nexus and scoped packages, and I tried this out using registry.npmjs.org to see how it behaves.

I discovered that doing `npm info @angular/core --registry https://registry.npmjs.org --loglevel info` revealed in the logs an HTTP GET to `https://registry.npmjs.org/@angular%2fcore`.  Visiting this URL in the browser returned the metadata. When I tried `https://registry.npmjs.org/@angular/core`, however, I got this response:

```json
// 20161110154303
// https://registry.npmjs.org/@angular/core

{
  "error": "Not found"
}
```

So it seems that Nexus's implementation of scoped packages isn't working, since they don't accept the URL encoded name of the package.

**Comment by legodude17** [comment]
I agree with @joeskeen, this is an issue with Nexus not matching it's implementation with the `npm` registry. Can this be closed @KenanY?

**Comment by joeskeen** [comment]
See https://issues.sonatype.org/browse/NEXUS-11630

> *Rich Seddon added a comment - 6 hours ago*
> We've had quite a few reports of this come in now, and in every single case so far the issue has been the reverse proxy not encoding "/" characters correctly.
> If you're using Apache, you can fix this by adding this to your configuration:
>
> ```
> AllowEncodedSlashes NoDecode 
> AllowEncodedSlashes On
> ```
