### ISSUE TITLE
How to generate the git urls for all the npm-modules ?

### ISSUE THREAD

**Issue by sandipmgiri** [npm/npm#13574]
#I'm trying to generate the git urls for all the npm-modules but facing some issues.
Is there any solution to fetch git urls for all the npm modules ?

**Comment by simonrenoult** [comment]
Have you thought of iterating over each `node_modules/<package>/package.json` and look at the `repository` key?

Something like:
```js
const fs = require('fs')

fs.readdir('./node_modules', (err, packages) => {
  if (err) console.error(err)
  packages.forEach((pkg) => {
    fs.readdir(`./node_modules/${pkg}`, (err, files) => {
      if (err) console.error(err)
      files.forEach(file => {
        if (file === 'package.json') {
          fs.readFile(`./node_modules/${pkg}/${file}`, (err, data) => {
            console.log(JSON.parse(data).repository.url)
          })
        }
      })
    })
  })
})
```

**Comment by othiym23** [comment]
There isn't in general a way to get Git URLs for all packages, because packages aren't required to be hosted in Git, and also because there's no presumption that there's a one-to-one mapping between a Git repository and packages. As @simonrenault says, the best way to get the repo URLs that are available is to iterate over `package.json`s and see if `repository` is available, maybe using `read-package-json` so those values get normalized into actual URLs instead of the shortcut syntax that presumes GitHub. Thanks for your time!
