### ISSUE TITLE
Problem in Installation

### ISSUE THREAD

**Issue by mahdifani14** [npm/npm#13575]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I cannot install the Asar package.
#### How can the CLI team reproduce the problem?
$ npm install asar

### supporting information:

[npm-debug.txt](https://github.com/npm/npm/files/401605/npm-debug.txt)

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mahdifani14** [comment]
I solved it by the following command:
$ npm install -g asar

**Comment by KenanY** [comment]
@mahdifani14 Closing as resolved then. In the future, if you get this `ENOSELF` error again, make sure that the `"name"` property in your `package.json` is not the same as that of any of your dependencies. For example, don't have it be `"asar"` and then try and run `npm install asar`. because you will get this error. As far as `npm` can tell, you are trying to install `asar` as a dependency of itself so it throws this error.
