### ISSUE TITLE
`update` doesn't seem to update sub-deps

### ISSUE THREAD

**Issue by emirotin** [npm/npm#13594]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other
#### How can the CLI team reproduce the problem?

Let's assume package A depends on B@^x.y.z.
Install package A which also installs B.
Now assume the patch version of B was bumped because of important bugfix.
It looks like running `npm update` will not pick it because B is not a direct dependency.
Even if the version of A is bumped (but the update for B is not explicitly required in A's package.json) update won't pick it as well.
#### Why is it a problem?

Recently I've spent about 2 hours chasing a problem in quite complicated setup (babel, jsx, flow, eslint). When I tried to create a minimal repro for it I wasn't able to.
What happened?
My existing project had a subdependency of babel (babylon, its parser). Babylon used to have a bug that was fixed in a patch version.
With the fresh install the newest version of babylon was installed, and even though the two projects seemed to have the same set of direct dependencies they had the different sets of subdependencies.
It was almost impossible to realize unless I found where the bug was fixed and then checked the version of babylon. Then I've deleted the entire node_modules folder of my original project and did fresh `npm install` which fixed the problem.

While I understand that npm tries to cache as mush as possible to keep the install and update processes faster this seems like a source of the issues that are very tricky to discover.
### supporting information:
- `npm -v` prints: 3.10.5
- `node -v` prints: v4.4.7
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X, or Linux?: OSX

**Comment by doug-wade** [comment]
@emirotin `npm update` only updates direct dependencies.  The [npm documentation](https://docs.npmjs.com/how-npm-works/npm3-nondet#i-want-my-node_modules-directory-to-be-the-same-how-can-i-do-that) recommends deleting and reinstalling node_modules to get the canonical shape, so I suspect that this is "working as expected."  As to whether it _should_ update the transitive dependencies, I'm *personally* inclined to say no, since [`npm update`](https://docs.npmjs.com/cli/update#description) is intended to "update all the packages listed to the latest version (specified by the tag config), respecting semver", not update all transitive dependencies.  Checking all transitive dependencies would make the command prohibitively slow for users that want to check for new top-level dependencies, so I'd really only want to see a change like this behind a flag.

**Comment by emirotin** [comment]
I don't say it doesn't work "as expected" by its creators. But I tried to explain why I think this behavior leads to the mixed state that is very hard to reason about.

**Comment by slvnperron** [comment]
👍
