### ISSUE TITLE
npm start - what did i miss?

### ISSUE THREAD

**Issue by setoxxx** [npm/npm#13602]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 error Error: ENOENT, open '/home/howie/package.json'
5 error If you need help, you may report this log at:
5 error     <http://github.com/isaacs/npm/issues>
5 error or email it to:
5 error     <npm-@googlegroups.com>
6 error System Linux 3.19.0-32-generic
7 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error cwd /home/howie
9 error node -v v0.10.25
10 error npm -v 1.3.10
11 error path /home/howie/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
@setoxxx `npm@1.3` is several years old, please take the time to [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first since you are using an unsupported version of `npm`. In addition, ensure that there is a `package.json` in your current directory and that you have a `"start"` script defined within it before running `npm start`.

**Comment by setoxxx** [comment]
great im gonna check this out now, thanks

**Comment by KenanY** [comment]
Gonna assume this is resolved.
