### ISSUE TITLE
Provide clear separation between lifecycle scripts and non-lifecycle scripts

### ISSUE THREAD

**Issue by garthk** [npm/npm#13773]
#### I'm opening this issue because:

  - [x] `package.json` schema wart

#### What's going wrong?

It's hard to add lifecycle events without clashing with other scripts in the package. See, for example, @balupton's [plea](https://github.com/npm/npm/issues/10074#issuecomment-217737787) on #10074:

> No `prepare` please, it seems like it could be accomplished via a combination of existing hooks and would break all packages that already use that script name — such as most of ours/bevrys/mine, [our usage](https://github.com/search?utf8=✓&q=prepare+filename%3Apackage.json+user%3Abevry&type=Code&ref=searchresults)

Grinding through every `package.json` file in the registry to choose a name for which `name`, `prename`, and `postname` have no clashes will reduce the impact but, obviously, can't take packages not in the registry into account.

I'm sure I could argue the remaining risk is lower than that of making breaking changes to the CLI and `package.json` to separate lifecycle scripts from the others. I figure it's worth raising if only to have it closed in public.

**Comment by legodude17** [comment]
This makes sense to me, but this would be a huge change.

**Comment by balupton** [comment]
Just watched the node interactive europe talk on this, seems prepublish to prepare is actually happening. It seems my concerns over the last years have gone completely unheard. It would have been nice to get at least a response of why breaking all my packages and other peoples who use prepare is a good idea versus the alternative suggestions such as having a different field for lifecycle scripts #13773 (4 months old, no response) or not doing a replacement at all as the current notion can already be accomplished by combining existing lifecycle scripts if the user chooses as noted in https://github.com/npm/npm/issues/6887#issuecomment-89713495 (a year ago, no response)

If prepublish was a bad idea, putting it under a different name, doesn't solve that bad idea, just increases the problem. The message of the prepublish to prepare proposal is instead of getting everyone to make a breaking change that solves the problem (suggestions above) we wish to have them break more modules with the same problem.

I feel unheard. These are the official and correct places to talk about this yes? Right on the issues for them. Why have my concerns been gone unheard, or worse, ignored, for so long?

**Comment by othiym23** [comment]
See https://github.com/npm/npm/issues/10074#issuecomment-247725943 for my update on the topic of `"prepare"`. Either reserving a prefix for use exclusively in lifecycle scripts or separating package scripts and lifecycle scripts in `package.json` are both ideas that make a lot more sense than what the CLI does right now. Which is to say, if we were starting from scratch, and had some idea of how this stuff was going to end up being used, we'd probably have a much more sensible design.

Unfortunately, like a lot of good ideas around package and lifecycle scripts, we have to worry about

1. occasionally making changes that are going to be either breaking for a segment of the user community, as is happening to @balupton,
2. bringing along as much of the package ecosystem as we can without undue disruption or breakage, and
3. doing what we can to keep the tool something that new users can learn to use without too much struggle.

That's a lot to balance! It also results in a lot of uneasy decision-making, because it's nearly impossible to satisfy all three of those criteria in all cases. In this case, getting through the process of introducing the new solution, whatever it was, and getting everybody cut over to using it in a way that addresses the problem you identify, would be a multi-year effort, and probably more work than is justified given the scale and nature of the problem that it's solving.

So yes, while this is a sensible suggestion, it's one that we're not going to implement. Thanks for bringing it up, though, and thanks for your patience.
