### ISSUE TITLE
while installing csv-pair  - [ ] npm is doing something I don't understand.

### ISSUE THREAD

**Issue by kewlcoder** [npm/npm#13775]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

Hi,
    I am trying to install csv-pair and get the error shown in the screenshot.
Also, the npm-debug.log file contains the error  -

`211 verbose cwd /home/aman
212 error Linux 4.4.0-34-generic
213 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "csv-pair"
214 error node v4.2.6
215 error npm  v3.5.2
216 error No compatible version found: csv-load-sync@0.0.3
216 error Valid install targets:
216 error 1.0.0
217 error If you need help, you may report this error at:
217 error     <https://github.com/npm/npm/issues>
218 verbose exit [ 1, true ]`

Thanks in advance
![screenshot from 2016-08-26 20-05-23](https://cloud.githubusercontent.com/assets/4420810/18009107/7bc0e026-6bc8-11e6-8791-57deee816c65.png)

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@kewlcoder This is an issue with `csv-pair`, not with `npm`. That module is [depending on](https://github.com/bahmutov/csv-pair/blob/0.2.0/package.json#L10) a version of `csv-load-sync` which does not exist. Hence the module fails to install. I suggest you prepare a pull request to [the repo](https://github.com/bahmutov/csv-pair) that updates the dependency. Since this is not an issue with `npm`, I'm gonna close. Good luck!
