### ISSUE TITLE
Feature request: analytics about node & OS version

### ISSUE THREAD

**Issue by jimmywarting** [npm/npm#13785]
#### What's the feature?
To provide analytics about what node version & what OS they are using. Both globally and for individual package.

#### What problem is the feature intended to solve?
It helps to judge whether to use ES6 features without Babel or work just with es5. also helps you to know if you can drop obsolete code like polyfills

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
yes

**Comment by othiym23** [comment]
This class of analytic information isn't something that's going to come out of the CLI, so this isn't really the right repo for this request. I think this belongs either on [`npm/public-api`](), or perhaps [`npm/www`](), where information like this may eventually be made available. Because this isn't something for the CLI to work on (aside from reporting the Node and npm versions, which the CLI has already been doing since `npm@~1.4.20`), I'm going to close this request. Thanks for your time, though, and yes, that kind of breakdown would be super useful to have as a developer or maintainer. Thanks for your time!
