### ISSUE TITLE
installation issue on windows

### ISSUE THREAD

**Issue by shahidkarimi** [npm/npm#13810]
`── bower@1.3.12 (abbrev@1.0.9, is-root@1.0.0, junk@1.0.3, stringify-object@1.0.1, which@1.0.9, chmodr@0.1.0, osenv@0.1.0, q@1.0.1, bower-endpoint-parser@0.2.2, opn@1.0.2, archy@0.0.2, bower-logger@0.2.2, lockfile@1.0.1, nopt@3.0.6, rimraf@2.2.8, lru-cache@2.5.2, retry@0.6.0, tmp@0.0.23, semver@2.3.2, request-progress@0.3.0, p-throttler@0.1.0, graceful-fs@3.0.10, shell-quote@1.4.3, chalk@0.5.0, bower-json@0.4.0, fstream@1.0.10, promptly@0.2.0, mkdirp@0.5.0, fstream-ignore@1.0.5, glob@4.0.6, bower-config@0.5.2, request@2.42.0, tar-fs@0.5.2, cardinal@0.4.0, bower-registry-client@0.2.4, decompress-zip@0.0.8, update-notifier@0.2.0, handlebars@2.0.0, mout@0.9.1, inquirer@0.7.1, insight@0.4.3)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program Files (x86)\nodejs\node.exe" "D:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp\www\lets-chat-master\npm-debug.log`

**The npm-debug.log file actually doesnt exist**

**Comment by KenanY** [comment]
@shahidkarimi Does this also occur with `npm@2.15.9`?

**Comment by nstone101** [comment]
Did it with 2.15.8... .9 is out.. .okay, maybe that will help, any others find some solutions? All 3 of my dev machines are screwed when they were perfectly fine until I added in googlecloud to path on my mac. then this machines out of date by .1 -v so we'll see and report back. It was all fine two weeks ago. Its been working just not doing all  the installs that I need or permissions issues that usually i'm able to sudo or workaround and fix perms for. How can I rm node.js and npm and restart lbecause I reinstalled it then it wasn't installing from the correct folder with all my needed globals from the past. given I had a "tech" at work who knew everything and managed to get me to this point while trying to figure out why I already had a package installed....i'm a developer that's why.   Just frustrating..Thanks for letting me know
