### ISSUE TITLE
fetch failed with status code 404

### ISSUE THREAD

**Issue by stopkillingbtc** [npm/npm#13826]
#### I'm opening this issue because:

  - [] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to install ionic@1.3.1.
I always get 
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
I am running OSX and have:

node v 4.5.0
npm v 2.15.9

### supporting information:

 - `npm config get registry` prints:
https://registry.npmjs.org/

OSX

**Comment by KenanY** [comment]
@stopkillingbtc Could you provide a `npm-debug.log` file?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by sandroqz** [comment]
@KenanY same error here.

Here's my npm-debug.log https://gist.github.com/sandroqz/e43c72679974a1805d54839473ef3c88

**Comment by KenanY** [comment]
@sandroqz Try installing a newer version of `ionic`.

**Comment by sandroqz** [comment]
@KenanY well I can install ionic@2.1.1 but I need ionic 1.3.x 

I can't install ionic@1.3.0 also.

And there's another thing that's a bit confusing for me. Why there is an npm package for ionic 2.1.1 while the latest version of ionic is v2.0.0-rc.1 ?

**Comment by KenanY** [comment]
@sandroqz Well, looks like `ionic@1.3` has a dependency on a version of `i` (somewhere down the dependency tree) which has been unpublished from the registry. That's why I suggested installing a newer version of `ionic`, since this issue has since been fixed.

`ionic@2.0.0-rc.1` may simply be [tagged](https://docs.npmjs.com/cli/dist-tag) as `latest`. The "highest" version does not necessarily have to be tagged as `latest`.
