### ISSUE TITLE
extendingDependencies - another type of dependency

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#13869]
#### I'm opening this issue because:

I am trying to figure out how to best write one particular kind package and I struggle find the best way with the current limitations of NPM. I even wrote a [medium post](https://medium.com/@leichtgewicht/good-dev-offers-dependency-234ce6e1fbf2#.bz34glk2w) on it.

#### What's the feature?

Add a new way to specify dependencies that are optional yet not installed by default.

#### What problem is the feature intended to solve?

If you want to write a package like https://github.com/tj/consolidate.js you need to exclude the dependencies from your `package.json` else all the dependencies are installed by default, which would lead to signficant higher install times and bandwidth use. However if you do that all the goodness of semver are lost on the package.

#### How would you solve this?

I would add a new property to the `package.json` called `extendingDependencies` _(not quite happy with the naming yet)_. I will reference to the property as `extDep` from now on.  The notation of the properties are exactly same as with the other `*Dependencies` properties:
```json
{
  "name": "sample-pkg",
  "extendingDependencies": { "js-yaml": "3.6.x"}
}
```

At installation-time of `sample-pkg` if ...

1. ... a matching `js-yaml` **has been** installed before:
     NPM should move/dedupe the `js-yaml` package from the other peer dependency.
2. ... a matching `js-yaml` has **never been** installed:
     NPM should Install a placeholder package in the `sample-pkg/node_modules/js-yaml` folder.  
3. ... a **non-matching** `js-yaml` has been installed in the hierarchy above `sample-pkg`:
     (same like 2.)

##### Placeholder
The Placeholder is a usability feature: If some code in `sample-pkg` were to call `require('js-yaml)` then the placeholder would show a [helpful message](https://www.npmjs.com/package/package-missing) instructing the user on how to install an extending dependency. This should reduce friction between developer and user.

If NPM would simply not install this placeholder then node would bubble up folder hierarchy to look for `js-yaml` and if a non-matching version is found there the code might break. _(in other words: the placeholder is important!)_

Another consideration here is that older versions of `npm` would simply not install those `extDeps` which means would lead to problems but in many cases it would also still work.

##### Specifying the installation of an `extDep`.
For the installation of an `extDep` the user needs to specify possibly the whole hierarchy of packages above, my thought is to add a new "semver-extension" for this case:

`npm i sample-pkg:js-yaml` which would then install `js-yaml` with the highest version matching the specification in `extDeps`.

If `sample-pkg` were to be in a deeper hierarchy the installation could look like:
`npm i other-pkg:sample-pkg:js-yaml`.

##### Saving the `extDep`

If a package depends on `sample-pkg` having `extDep` installed then it would need a way to reference those. I initially thought it might be good to have a semver extension for this: like `"sample-pkg": "1.1.0+js-yaml"` but this would be bad for backwards compatibility. Instead I think it would need to be a separate field `extendedDependencies` _(again, the naming is problematic: extending/extended is too similar)_:

```json
{
  "name": "different-pkg",
  "dependencies": {
    "sample-pkg": "1.1.0"
  },
  "extendedDependencies": {
     "sample-pkg": {
        "js-yaml": "3.6.0"
     }
  }
}
```

It could even support deep-extending like: `"other-pkg:sample-pkg": { "sample-pkg": "3.6.0" }`

**Comment by legodude17** [comment]
This seems like another niche case. I think that there should be a discussion about if npm should try to conform to people niche cases. I think this would be fairly easy to implement, except for the last part. Can you explain it to me?

**Comment by martinheidegger** [comment]
I assume with _"the last part"_ you mean _"saving the extDep"_:

Lets assume an express application uses [`consolidate.js`](https://github.com/tj/consolidate.js). `consolidate.js` doesn't do anything by itself. The developer would also need to install `jade` or `ejs`. The question arises: Which version to install? `npm install jade` should consistently install the latest version as a dependency of the express app, not of `consolidate.js`. 

What if `consolidate.js` doesn't work with the latest version (with `extendingDependencies` it would have a way to specify it)? We could do a `cd node_modules/consolidate.js; npm i jade` to install it in the subfolder of the consolidate.js module. Now that it installs there, `consolidate.js` would work with the specific version. But how does the express developers share his app? Without `extendingDependencies` outlined above he would need to add it in a `postInstall` script or so.

Does that explain the use case?

_(Note: This particular is important to me personally because I think it has the potential to change the way how people write projects and collaborate)_

**Comment by othiym23** [comment]
Based on reading the linked Medium post and the description of the problem in here, I have concerns sufficient to lead me to believe this isn't something likely to be appropriate for the CLI.

1. The feature, as described, requires a certain degree of coördination between the code in the "interface" package, the code in the "implementing" packages, and the package manager itself. This feels out of scope for a package manager.
2. The proposal also feels more like an extension to the JavaScript language (similar in scale, albeit narrower in scope, to ECMAScript modules), rather than a simple package manager. As described, it feels very similar to TypeScript's interfaces. (I'll return to TypeScript in a minute.)
3. npm already supports a confusingly wide variety of different kinds of dependencies, and this proposal wants to add a new kind of dependency that sits (somewhat awkwardly, in my opinion) between the already-extant `peerDependencies` and `optionalDependencies`. Both of those have their confusing aspects (and both have required considerable refinement to make them less likely to be footguns for confused users), and I worry that adding a new class of dependencies would only make the problem worse.
4. It's not clear to me that this is functionality that belongs in npm itself, but it's also not clear to me that this is something that needs to be implemented by the CLI team – this seems like something that could be built, and in fact should be tried out, outside of the current npm CLI.

What you've proposed is analogous to apt's support for alternatives:

```
Depends: libc6 (>= 2.2.1), exim | mail-transport-agent
```

At a distribution or OS level, this makes a certain sort of sense, because when suggesting an array of alternatives, either a human being (the operator) is expected to know how to make everything work together, or the alternatives (as in the case here) are implementing a standard protocol at the level of SMTP. This seems unlikely to be an idea that gets broad traction in a commons like npm's, where the only things coupling packages are relatively loose conventions, and where there is no central integrator for the "distribution" that is the registry . This is a lesson the community has (slowly) learned the hard way with `peerDependencies`, where just dealing with semver seems to be trickier than many (including me) would expect.

However, there's already tooling that supports something much like this! TypeScript and `typings` have exactly this notion of components that satisfy the constraints of defined interfaces, and a collection of classes that implement those interfaces. This only happens at the class level, so it's not quite what you're looking for. However, I think the smaller scope of TypeScript (as well as the fact that it's designed into the language) is part of what makes it workable.

Based on the preceding, I'm going to close this feature request. I hope the preceding makes my reasoning clear. Thanks for your time and the very thorough description!

**Comment by martinheidegger** [comment]
Hello @othiym23 I would like to respond to clear up some possible misunderstandings _(My brain is slightly weird and I am not always good at expressing myself)_:

> The feature, as described, requires a certain degree of coördination between the code in the "interface" package, the code in the "implementing" packages, and the package manager itself. This feels out of scope for a package manager.

I think I didn't layout that part very well. The "meta" package (such as [`consolidate.js`](https://github.com/tj/consolidate.js) actually **contains** all the adapters for the standard interface to specific versions of the actual implementations. The coordination is similar to a dependency upgrade in the `consolidate.js` package. _(In retrospect: I could have layed that out clearly.)_

> The proposal also feels more like an extension to the JavaScript language (similar in scale, albeit narrower in scope, to ECMAScript modules), rather than a simple package manager. As described, it feels very similar to TypeScript's interfaces. (I'll return to TypeScript in a minute.)

Interfaces would solve the communicative part of the problem and would remove the need for formerly mentioned adapters but even if interfaces existed (like they do in typescript) they still run against the compatibility issues of different versions.

> ... in fact should be tried out, outside of the current npm CLI.

I was of the opinion that `consolidate.js` is a good and failing attempt at this?

-- 

Maybe with this you might be able to rethink:

**Comment by othiym23** [comment]
> I think I didn't layout that part very well. The "meta" package (such as [`consolidate.js`](https://github.com/tj/consolidate.js) actually **contains** all the adapters for the standard interface to specific versions of the actual implementations.

Sure, but unless I'm missing something, there's still a need to pick one particular implementation and install it. And in the case where there _isn't_ a need to define the adapting interface, this feels even _more_ like `peerDependencies`, and therefore even more likely to be confusing to users.

> I was of the opinion that `consolidate.js` is a good and failing attempt at this?

Perhaps it was I who wasn't quite clear enough. For these kinds of use cases, where there are specific constraints to be satisfied for e.g. a plugin architecture, it makes sense to me to write a helper, or adjunct installer, that deals with those requirements, which could be stored in `package.json`, and invoked via a lifecycle script. To me, this feels similar to what browserify does.

**Comment by martinheidegger** [comment]
> Sure, but unless I'm missing something, there's still a need to pick one particular implementation and install it. And in the case where there isn't a need to define the adapting interface, this feels even more like peerDependencies, and therefore even more likely to be confusing to users.

Yes, there is a need to pick the implementation but in this proposal it would only offer verifiably working implementations. You couldn't just pick any implementation, just does specified in the adapters. The recommendation in `peerDependencies` basically recommends to work against immutable API or risk incompatibilities.

| which could be stored in package.json, and invoked via a lifecycle script

I know it comes with effort at NPM's cost but the lifecycle script _(testing against an interface)_ seems to solve an issue that simply couldn't exist with this proposal.

**Comment by legodude17** [comment]
I believe one of the best way to not need this is to use something like @martinheidegger wrote on Medium, using a package to attempt to require it and then throw an error when it can't be. Another solution would be to use a tool on install time to insert placeholder packages into the file tree.

**Comment by martinheidegger** [comment]
@legodude17 While writing an answer to your comment I tried to imagine how that tool could look like and it turns out that the usability might maybe not even suck and work as a prototype for the feature in npm. I guess I will tinker on it in the next days.
