### ISSUE TITLE
Have os specific dependencies or maybe dependency list as a function that can run in the node environment and then return the dependencies based on some logic that we build in.

### ISSUE THREAD

**Issue by atishay** [npm/npm#13949]
#### What's the feature?

Have os specific dependencies or maybe dependency list as a function that can run in the node environment and then return the dependencies.
#### What problem is the feature intended to solve?

For electron apps, having dependencies specific to the os is a pain. We need to put extra code in OSes that don't need them, sometimes that includes huge dlls that are not needed in a specific binary.
#### Is the absence of this feature blocking you or your team? If so, how?

It is increasing the install size or requires complicated build scripts to cleanup the output of the package manager as `npm --prune production` is useless for cases like these. Also for modules that don't work and are not needed on windows, it is a pain to request the maintainer or to fork it to turn it into a no-op on windows.

**Comment by isiahmeadows** [comment]
This could also be useful for things like Chokidar, which depends on an FSEvents native module only in macOS/OS X, because `fs.watch` is spectacularly broken on that particular OS.

**Comment by legodude17** [comment]
What do you do currently? Do you have a workaround?

**Comment by isiahmeadows** [comment]
I'm not a contributor to Chokidar, but they list FSEvents as an optional
dependency.

As for the browser side, I do nothing at the moment - I just list
everything with the others.

On Wed, Nov 9, 2016, 14:00 legodude17 <notifications@github.com> wrote:

What do you do currently? Do you have a workaround?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/13949#issuecomment-259495720>, or mute
the thread
