### ISSUE TITLE
inconsistent `npm install` & `npm shrinkwrap` handling of package range ""

### ISSUE THREAD

**Issue by indeyets** [npm/npm#13958]
We have `"sphinxapi"` as a dependency and use `npm shrinkwrap`.

sphinxapi has `"put": ""` in it's [list of dependencies](https://github.com/Inist-CNRS/node-sphinxapi/blob/e1b4e759518cc19319e6184b8837d15196cf2be0/package.json#L37) and while it works fine during initial installation we get the following error if we try to generate `npm-shrinkwrap.json`:

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have put@0.0.6 (expected: ) /path/to/project/node_modules/sphinxapi/node_modules/put
npm ERR! extraneous: put@0.0.6 **/path/to/project/node_modules/sphinxapi/node_modules/put**
```

I [filed a bug](https://github.com/Inist-CNRS/node-sphinxapi/issues/25) to sphinxapi maintainer, but this REALLY looks like an issue with NPM

**Comment by othiym23** [comment]
This is a bug, but it's actually a _different_ bug, so I'm going to retitle the issue – `package.json` should _not_ allow packages with empty versions in the first place. The fact that that currently maps to `<package>@latest` (the CLI team _thinks_) is kinda happenstance, and only works that way due to how the `npm@3` installer works. `npm shrinkwrap` is (semi-)helpfully pointing out that the CLI doesn't know what this means.

So, yeah, this is also a bug on `sphinxapi`, but it's hard to fault them for it, because the CLI isn't telling them so yet. Thanks for bringing this to our attention!

**Comment by othiym23** [comment]
Update: after discussing this further with @isaacs, who is by definition the authority on matters of semver ranges and their interpretation, the _correct_ thing to do here is to replace empty version ranges (which are, in his interpretation, perfectly valid) with `*` for the purposes of both installation and shrinkwrapping. So, issue name retitled to reflect that corrected understanding, and at some point someone should fix this, although because it touches at least one of npm's dependencies ([`npm-package-arg`](http://npm.im/npm-package-arg) and / or [`realize-package-specifier`](http://npm.im/realize-package-specifier)), it may be a little bit.

**Comment by JordanBelford** [comment]
In case anyone is curious, the [npm semver doc](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) contains an example using the empty string.
`"" (empty string) := * := >=0.0.0`
