### ISSUE TITLE
Logging works only one out of four times in windows console

### ISSUE THREAD

**Issue by Luciferius** [npm/npm#13968]
Description copied from issue of in electron [here](https://github.com/electron/electron/issues/7149). Seems to be an issue of the npm command.
- Node.js Version: 6.3.0
- Electron version: 1.3.5
- Operating system: Windows 8.1 Pro

I am using the [electron-quick-start](https://github.com/electron/electron-quick-start) app. I have added logging statements in the main.js as follows:

```
[...]

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

console.log("Test")

function createWindow () {
  // Create the browser window.
[...]
```

I have now started the app four times in a row without changing anything. The result can be seen in the picture below.

[![electron logging](http://i.stack.imgur.com/5oj3f.png)](http://i.stack.imgur.com/5oj3f.png)

Only one of the four times did I get the logging message inside my console.

**Comment by KenanY** [comment]
@Luciferius `npm --version`?

**Comment by Luciferius** [comment]
3.10.3

**Comment by othiym23** [comment]
There are a number of issues open on Node itself related to weird console output timing races on Windows (sorry, don't have the time at the moment to dig up reference). If you look at the output, it's Electron failing to get the message out before the executable exits, which exactly matches the behavior seen in the related Node versions. Is this version of Electron built on Node 6? If so, that's almost assuredly what's going on. I'll let you confirm, though, and close this issue if that's what's happening. (The CLI team may make some changes in a future version of npm that will "fix" this problem by redirecting console output away from the console device, but the underlying bug is in Node, not npm.)

**Comment by Luciferius** [comment]
This electron version is built on Node 6.3.0 There is only one mistake in what you said. Electron is still running as long as I want to when the log message is sent. But I have now a workaround and can wait for a new Node version.
