### ISSUE TITLE
Npm install stuck at fetchMetadata

### ISSUE THREAD

**Issue by marvinhagemeister** [npm/npm#13978]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm install` takes ages because it is stuck at `fetchMetadata`. It has been running for close to an hour now and it is still stuck at the beginning. I'm properly connected to the internet and all network connections work fine (double checked to be sure).

#### How can the CLI team reproduce the problem?

`npm install webpack` or any other package.

Log output: https://gist.github.com/marvinhagemeister/6aeb6139bec71f9c06d8e0d99048431d

### supporting information:

 - `npm -v` prints: npm@3.10.3
 - `node -v` prints: node@v6.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: Cologne, Germany
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rosen-vladimirov** [comment]
Hi, 

We are also encountering a lot of hang connections to `registry.npmjs.org` in the last few days. We are working extensively with npm related packages and we are currently testing the `@angular` packages. However the requests to `registry.npmjs.org` hang and some point (different package every time). We've investigated this issue a lot. It first occurred in the middle of August, after that we've changed our configurations to use `http` instead of `https` and this improved the situation. However in the last few days we encounter tons of hanging requests. It's really strange that the connection is in ESTABLISHED state, but it's just hang (checked with TcpView on Windows). If we kill it, the process continues. 
After a lot of investigations we can confirm it's not a problem in our internal network. However we've noticed some peaks in our requests when the hang occurs. So we kindly ask for information - is there some limitations of the `registry.npmjs.org`. **For example is there a limitation of the number of requests to registry.npmjs.org from a single public IP?**
In case there are not limitations, is there some issue that the registry experience in the last few days?

Thanks in advance for your help!

**Comment by rosen-vladimirov** [comment]
Ping @isaacs , @iarna , @zkat , @othiym23 
Can you help us? Who is responsible for the registry and connection to it? Do you experience any issues in the last days?

**Comment by addaleax** [comment]
> Who is responsible for the registry and connection to it?

https://github.com/npm/registry – the debug log in the original report seems to hint at a problem with the local setup, though.

**Comment by marvinhagemeister** [comment]
@addaleax I highly doubt that. The issue occurred on completely different machines in completely different networks (and cities for that matter). A few of my friends had experienced it as well.

Everything seems back to normal for me again, what about you @rosen-vladimirov ?

**Comment by addaleax** [comment]
@marvinhagemeister Thank you, that seems like helpful information!

> Everything seems back to normal for me again

Let’s hope that, otherwise you might want to open an issue at the registry tracker.

**Comment by marvinhagemeister** [comment]
For reference: The registry repo is here: https://github.com/npm/registry

**Comment by rosen-vladimirov** [comment]
@marvinhagemeister it's still hangs on our side, so I'm going to open a new issue at the registry repo. Thanks for pointing it.

**Comment by rosen-vladimirov** [comment]
Adding the new issue here for reference https://github.com/npm/registry/issues/55

**Comment by x-ji** [comment]
@marvinhagemeister Still hangs a lot for me. I'm currently using China Telecom for my connection. I encountered similar issues with the official registry. @fengmk2 's registry (Alibaba's registry) linked in another issue worked fine for me. I think in my case it's just my local ISP not playing very well with the official registry, which occurs frequently with other package systems as well (e.g. Haskell Stack, Elixir Hex). I had to switch mirror for Hex to work as well.

**Comment by soriyath** [comment]
for some reason, i couldn't reach `registry.npmjs.org` from my docker container.
i added this line `151.101.36.162 registry.npmjs.org` to `/etc/hosts/` and it worked liked a charm.

**Comment by MaduraHerath** [comment]
I have uninstall Nodejs ,and npm cache clean,After doing that i reinstall node and run npm install ,still stuck in the middle of fechMetadata step... if someone going through this issue plz reply ...

**Comment by placha433** [comment]
I tried to temporarily disable my antivirus and now it works !

**Comment by wxsbd2010** [comment]
@placha433 me too, but why?

**Comment by placha433** [comment]
@wxsbd2010 Antivirus (especially what I have, Avast), distrusts terminal apps and runs higher levels of scrutiny on them before letting them launch. (https://www.reddit.com/r/node/comments/4op7ey/npm_is_incredibly_slow_on_windows_10/d4eus2i/)

**Comment by i-Apoorva** [comment]
Use command: npm install npm@latest -g

then try again.
**Worked for me**

**Comment by lukepighetti** [comment]
I had to allow Git port in my firewall
