### ISSUE TITLE
Support npm init <project>

### ISSUE THREAD

**Issue by monolithed** [npm/npm#13987]
#### I'm opening this issue because:

It's just an idea to promote `npm init` as a scaffolding tool to automate package creation.
I like [`grunt-init`](http://gruntjs.com/project-scaffolding), but it's not maintained for a long time and exists just for historical reasons.

#### What's the feature?

```
npm init <project>
```

The `project` is an npm package named as `npm-init-<package>`

A typical scaffold configuration might include:

— Custom templates
— Copying files
— Renaming or excluding template files
— Default prompt answers
— Helpers
— CLI with --help, --init, --join (for existing projects) and other command-specific options

For more information see [`grunt-init`](http://gruntjs.com/project-scaffolding)

#### What problem is the feature intended to solve?

Scaffolding is an evolution of `npm init`.

#### Is the absence of this feature blocking you or your team? If so, how?

`grunt-init` is a great tool, but there are some problems with cloning git repositories and Windows system.

#### Is this feature similar to an existing feature in another tool?

[grunt-init](http://gruntjs.com/project-scaffolding), [yo](https://www.npmjs.com/package/yo), [update](https://www.npmjs.com/package/update), [scaffold](https://www.npmjs.com/package/scaffold), [assemble](https://www.npmjs.com/package/assemble), [boilerplate](https://www.npmjs.com/package/boilerplate), [generate](https://www.npmjs.com/package/generate) and so on.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes

**Comment by othiym23** [comment]
I believe that this is something that's best left to the ecosystem, because there are way too many bikesheds waiting to have their colors argued over sitting on the edges of this particular glade. (See also: the list of similar projects above.) `npm init` is a great way to get up and running with a new project, but larger-scale generators like Yeoman and `ember-cli` are way better for doing larger-scale scaffolding and setup. Thanks for the well-defined proposal, though!
