### ISSUE TITLE
multiple registries with different options

### ISSUE THREAD

**Issue by isaacs** [npm/npm#1401]
1. Extend `registry` config to take a whitespace-separated list.
2. First registry is "write" target (publish, tag, unpublish, etc.)  Override-able in a few different ways anyway, package.json "publishConfig", cli options, etc.
3. Override config options with `registry:<registry url>:<option>`:
    * _auth (and thus also username/_password)
    * always-auth
    * ca
    * https-proxy
    * proxy
    * searchopts
    * searchexclude
    * strict-ssl
    * tag
4. Extend the cache folder structure to include the sanitized registry config, since ETags and such may differ.
5. Merge search results objects from all registries when searching.
6. If multiple registries are present, then `adduser` needs to ask the user which registry they're authorizing against.
7. BONUS POINTS: Add an `npm registry <add, rm, ls, reorder>` command to manage the list.

**Comment by jden** [comment]
This issue is still showing up on my personal "[open issues mentioning you](https://github.com/issues/mentioned)" list, limiting its utility. Could you please consider closing it?

**Comment by othiym23** [comment]
Since we now have at least a somewhat functional per-registry configuration framework (which is currently mostly used for auth, but could be extended for other things), I'm going to call this more or less satisfied. People who want per-registry configuration that's not handled by the current version of npm should open new issues (or, better yet, pull requests) with their specific requests. Thanks for the nudge, @jden.

**Comment by vernak2539** [comment]
@othiym23 is there any docs on how to do this?
