### ISSUE TITLE
NPM inefficient sub module versioning system

### ISSUE THREAD

**Issue by AaronNGray** [npm/npm#14044]
The existing npm module system of hierarchical subdirectories for version of modules is very inefficient both for loading and in disk space. I am proposing that we create a flattened versioning system with paths of the form :-

    ./node_module/<modeule name>/<version>

Can someone look into modifying npm and implementing a solution to this please.

**Comment by othiym23** [comment]
This would require [significant changes to how the Node.js module resolution algorithm works](https://nodejs.org/api/modules.html#modules_all_together), and also isn't super compatible with the current maximally flat installation method used by `npm@3`. That said, you may wish to look at [`ied`](http://npm.im/ied), [`pnpm`](http://npm.im/pnpm), or [`npm-install`](http://npm.im/npm-install), all of which are alternate installers that use a similar layout to that you propose (along with a ton of symbolic links) to speed up installs and cut down on installation times. While the CLI team may end up adopting some or all of these techniques in a future version of npm, we won't be changing how `node_modules` is laid out, because that's not up to npm to decide. Thanks for your time!
