### ISSUE TITLE
Resolve package version smartly with peerDeps

### ISSUE THREAD

**Issue by yunxing** [npm/npm#14061]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's the feature?

When resolving versions of package with peerDeps, prefer the version that can meet its peerDeps.
#### What problem is the feature intended to solve?

Say we have a project X that depends on package A = "0.0.1" and package B = "*". 

B has 2 versions: 
  B = "0.0.1", with peerDep of "A": "0.0.1",
  B = "0.0.2", with peerDep of "A": "0.0.2"

when installing our project X, if we resolve B with version 0.0.2, its peerDep will be unmet since we only have A = 0.0.1 installed. It could be smart and resolve B with version 0.0.1, which has its peerDep installed.
#### Is the absence of this feature blocking you or your team? If so, how?

Yes, we are trying to simulate the behavior of ocaml packages. Some ocaml packages are depending on a specific version of ocaml. 
#### Is this feature similar to an existing feature in another tool?

Yes, in "opam" (https://opam.ocaml.org/doc/Manual.html#opamfield-available), there is a "available" field which is used to represent : "this package is only available on a specific version of ocaml"
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

need support from npm CLI team

**Comment by jordwalke** [comment]
@yunxing I wonder if instead of `"*"`, we used `>=0.0.0`, the bug would no longer occur. I imagine that constraint behaving as "highest possible version that meets all the other constraints".

**Comment by jordwalke** [comment]
To add a bit more context: This is a very important feature. PeerDependencies aren't just about "plugins", they are about stateful modules in general. Any time you must resolve to one specific instance of a module globally because that module stores state that every depender is expected to be able to perceive.
With the constraints given (including the constraint that certain packages be resolved to a single version (peer)), there exists a solution, and `npm` doesn't appear to be discovering that solution.
