### ISSUE TITLE
Unable to run command npm install -g ionic@beta

### ISSUE THREAD

**Issue by srikanth748** [npm/npm#14125]
#### I'm opening this issue because:
[Error log.docx](https://github.com/npm/npm/files/501205/Error.log.docx)
![Uploading commandprompt-image.png…]()
- [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.

**Comment by KenanY** [comment]
@srikanth748 Please upload your `npm-debug.log` as a plaintext file to <https://gist.github.com/> instead of converting it.

**Comment by srikanth748** [comment]
[error.image.pdf](https://github.com/npm/npm/files/503773/error.image.pdf)

**Comment by KenanY** [comment]
@srikanth748 Hmm, maybe try `npm cache clean` first? Perhaps a newer version of `npm` would help as well. If you still see the error, I would appreciate it if you could provide the _full_ `npm-debug.log` file as plaintext (as I requested above) rather than converting it to a `docx`. Screenshots leave out a lot of context and are usually not sufficient for diagnosing complicated issues.

**Comment by KenanY** [comment]
Closing as abandoned.
