### ISSUE TITLE
Improve the output of `$ npm run`

### ISSUE THREAD

**Issue by sindresorhus** [npm/npm#14161]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [x] Other (_see below for feature requests_):
#### What's the feature?

With the following `package.json`:

``` json
{
  "scripts": {
    "start": "foo start",
    "test": "ava",
    "lint": "eslint .",
    "smoke": "node smoke.js",
    "coverage": "nyc ava && nyc report",
    "watch": "ava --watch"
  }
}
```

The output of running `$ npm run` is:

```
Lifecycle scripts included in :
  start
    foo start
  test
    ava

available via `npm run-script`:
  lint
    eslint .
  smoke
    node smoke.js
  coverage
    nyc ava && nyc report
  watch
    ava --watch
```

The output is verbose and it's hard to quickly look up what tasks you can run. Especially when you have long scripts.

I would suggest something simpler like this:

```
$ npm run

start     Lifecycle script
test      Lifecycle script

lint      Lint the app code base
smoke     Run the smoke tests
coverage  Generate coverage
watch     Start watching everything
```
- [ ] Drop showing the script source. That's better left in `package.json`.
- [ ] Format default tasks and custom tasks equally, with the default ones first, like show above.
- [ ] Add support for adding description to tasks.

Suggested format for adding descriptions (needs to be bikeshedded):

```
{
  "scripts": {
    "start": "foo start",
    "//start": "Starts the app"
    "test": "ava",
    "//test": "Runs the tests"
  }
}
```
#### What problem is the feature intended to solve?

`npm run` has become one of the most popular task runners these days, but its UX could be improved. Running `$ npm run` is a great way to see available tasks, but it's hard to quickly see available tasks and what they do with the current output, and the tasks are missing descriptions.

Many [people on Twitter](https://twitter.com/sindresorhus/status/780257903152209920) seemed positive to the idea, including @othiym23.
#### Is the absence of this feature blocking you or your team? If so, how?

No.
#### Is this feature similar to an existing feature in another tool?

Yes, most task runners have this kind of output.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes.

**Comment by SamVerschueren** [comment]
Nice suggestion @sindresorhus! An alternative for adding descriptions could look like this

```json
{
  "scripts": {
    "start": {
        "$": "foo start",
        "description": "Starts the app"
    },
    "test": {
        "$": "ava",
        "description": "Runs the tests"
    },
    "coverage": "nyc ava"
  }
}
```

Just throwing in some ideas :).

**Comment by watilde** [comment]
To keep the backward compatible, I'd suggest using the same key to note the description or the Sindre's idea if we use the script field. On the other hand, possibly we could use the other name of the field in `package.json`.
```
{
  "script": {
    "lint": "Lint the app code base",
    "lint": "eslint ."
  }
}
```

Well, I agreed on the simpler `npm run`, and also I'd like to keep the current style with `--long` option since some developers can't make sure the scripts required the `run` sub command or not.

related discussion: https://github.com/npm/npm/issues/9952

**Comment by timseverien** [comment]
I absolutely love this.

I can imagine users will want to read the actual script before executing. Perhaps a `-v/--verbose` flag could print out the scripts as well.

Also, I prefer @SamVerschueren’s format more, as it more descriptive. For that same reason, I would prefer `script` over `$` for the script property name.

 As @SamVerschueren’s example implied, a script string should still be valid for backwards compatibility. Much like the `author` property, where both a string and object is valid.

**Comment by SamVerschueren** [comment]
@watilde As @timseverien explained, a normal string would still be valid (for backwards compatibility).

**Comment by watilde** [comment]
@SamVerschueren Here is the case that the current version doesn't work:
```json
"scripts": {
  "prepublish": {
    "$": "echo 'should be called when npm install'",
    "description": "should be called when npm install"
  }
},
```

The `prepublish` hook have to be called when users run `npm install`, and it will not be hooked if the npm lifecycle script doesn't support the object style. It means some modules will need to be built even users run `npm install`.  
+ https://docs.npmjs.com/misc/scripts

Since npm@4 will come soon, it's nice to be added into it as one of the feature because of the same reason :)

**Comment by petetnt** [comment]
🚲 🏠 , another format would be just using an array

```
"scripts": {
  "lint": "eslint --fix",
  "smoke": ["Run the smoke tests", "node smoke.js"]
  "coverage": ["nyc ava && nyc report"]
}
```

Would output 

```
lint         eslint --fix
test         Run the smoke tests
coverage     nyc ava && nyc report
```

**Comment by halhenke** [comment]
Would much rather the actual command is the default output rather than the optional description.

I'm not a big fan of the idea that "code should be self-dcoumenting" in terms of being readable (especially when dealing with something like BASH) but still i dont see much value in something like:

```
start: Start the app
```

etc vs seeing the command that accompanies the actual script name. 

This is one case where i feel command names are almost always sufficiently descriptive and their corresponding shell output sufficiently brief and comprehendable. Nothing against the ability to add descriptions as an option but i feel default output should remain as is (though i'm happy to see that prettified also)

**Comment by fregante** [comment]
Among the suggested solutions here, @sindresorhus's with `//name` or `name@` is the easiest to apply at this moment:
- standard JSON
- 90% backwards compatible (10% missing because the text descriptions would not appear in older npm's `npm run` output, but at least it doesn't break completely on old installs)
- if we're changing the syntax of `scripts` in any way please let's just switch to a more readable separate file like [p-s/package-scripts.yml](https://github.com/kentcdodds/p-s/blob/b2a0a2fe9db8f64c9822bbec3e5b195597894ea3/cli-test/fixtures/package-scripts.yml) or a makefile-like format instead.  
  Building onto a cmd-in-json format is a lost battle IMO (think no comments, no newlines, no ...)

@halhenke descriptions will be optional and the output of `$ npm run` would be like

```
lint      Lint the app code base
smoke     Run the smoke tests
watch     npm start -- -w
```

**Comment by kentcdodds** [comment]
Thanks for the shout-out on [p-s](https://github.com/kentcdodds/p-s) @bfred-it 

It's similar to @SamVerschueren's suggestion except instead of `$` it uses the term `script`. Also, `p-s` supports nesting and prefixes (not necessarily something I'd say is a must have, but has sure been nice for me as a user).

I agree with @bfred-it that `//name` is probably the easiest to apply at the moment. Though not what I would say the optimal solution. Seems to work around the limits of JSON.

Just had another idea. What if we are able to specify a separate JavaScript module to use to resolve the scripts. Similar to `p-s`. Something like:


**package.json**

```js
{
  ...
  "scripts": "my-scripts.js"
}
```

** my-scripts.js**

```js
const smokeFile = process.env.CI ? 'smoke-ci.js' : 'smoke.js'
module.exports = {
  scripts: {
    // I can have comments
    start: 'foo start',
    test: {
      default: 'ava', // this could also be an object with `script` and `description` properties if a description is desired
      watch: 'ava --watch' // nested scripts allow for logical grouping and take a common convention and make it part of how things work. In p-s, you can run this with: `nps test.watch` or with prefixes: `nps t.w`
    },
    lint: 'eslint .',
    smoke: `node ${smokeFile}`, // dynamic scripts would be possible and is useful
    coverage: {
      script: 'nyc ava && nyc report',
      description: 'Generate coverage' // objects for descriptions in the output
    },
    someOtherScript: {
      script: 'echo "something else"',
      hiddenFromHelp: true // something we have in p-s so other scripts can use this one though it's not useful when run on its own.
    }
  }
}
```

This would be a fairly significant divergence, but we're brainstorming here, so no idea is bad right ;-) So to sum up, the different proposals in this post:

1. Enable dynamic scripts and inline code comments by adding the ability to specify an external module (perhaps allow it to be YAML too?)
2. Enable specifying descriptions by allowing a script to be an object with `script` and `description` properties.
3. Enable grouping and nesting of scripts which enables a common convention by the way it works rather than simply the name of the script. (Many people group things with `name:subname`, `name:subname2`).
4. Enable adding scripts that are rarely/never run by the user without impacting the length/noise of the help output by allowing people to hide the script from the help output explicitly with a `hiddenFromHelp` property in the script object.

Curious what people think of these proposals: :+1:, :-1: or 😄 (like some of it, not all of it)

**Comment by bevacqua** [comment]
Would love for this to be a menu by the way, kind of like [`terminal-menu`](https://github.com/substack/terminal-menu)

**Comment by zkochan** [comment]
There is this nice package by @srph called [npm-scripts-info](https://github.com/srph/npm-scripts-info). [used by RxJS](https://github.com/ReactiveX/rxjs/blob/master/package.json#L19-L51)

It does what @sindresorhus suggests for `npm run`. It currently has to ways of specifying the descriptions, via a separate property in `package.json` called `scripts-info`. Or my favorite, using the script names prefixed with `?`:

``` json
{
  "name": "my-project",
  "scripts": {
    "?info": "Display information about the scripts.",
    "info": "npm-scripts-info",

    "?watch:build": "Watch codebase, trigger build when source code changes",
    "watch:build": "webpack --watch",

    "?start": "echo Kickstarts the application.",
    "start": "node index"
  }
}
```

**Comment by MattKetmo** [comment]
Hello. What about adding extra (shell) comments at the end of commands?

```
{
  "name": "my-project",
  "scripts": {
    "info": "npm-scripts-info        # Display information about the scripts.",
    "watch:build": "webpack --watch  # Watch codebase, trigger build when source code changes",
    "start": "node index             # Kickstarts the application."
  }
}
```

- it's BC
- no extra lines
- better readability (IMO)
- description is displayed even on old npm version
- cons: need to parse the line instead of just getting the value of a field

My 2 cts.

**Comment by bfred-it** [comment]
@MattKetmo 2 more cents:

- Extra lines are not bad, especially when factoring in readability
- I'm not sure about this, but parsing that `#` out could get hairy and require a shell-script parser (e.g. `echo "\#"  # echoes #`)

**Comment by MattKetmo** [comment]
Yes, the difficulty results in correctly parsing the `#` comment. Maybe a convention could be used like using a double comment `##` (or `#=`, `#:`, …) which may ease the parsing for 99% of the cases. This is heavily inspired by this [Self-Documented Makefile article](http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html) which I'm using in some projects.

For the extra lines I don't say they are bad. However I'll feel more confortable without the weird `?foo`, `#foo` or `//foo` keys (which will also break the "auto alphabetically sort" of my editor :p). I like the separate `scripts-info` section but it may leads to inconsistency if it's not updated in the same time than `scripts`.
