### ISSUE TITLE
progress bar obscures prompt when used in REPL

### ISSUE THREAD

**Issue by boneskull** [npm/npm#14194]
#### Summary

Progress bar ([gauge](http://npmjs.com/package/gauge)) obscures the prompt after call to `npm.load()` within Node.js' REPL.

See [**screencast**](http://screencast.com/t/dCgwnnSEe7).

#### Expected Behavior

The progress bar is hidden (by default) if `npm.load()` is called from within the REPL.

#### Steps to Reproduce

1.  Navigate to whatever `npm get prefix` is.
2.  Open a REPL via `node` executable.
3.  Execute `require('npm').load()`

Sorry about the dumb edge case. 😛 

*Please let me know if this issue should be opened in [gauge's issue tracker](/iarna/gauge/issues) instead. cc @iarna*

**Comment by othiym23** [comment]
The simple solution there is not to call `npm.load()` from the REPL. The use of npm's internal API from outside the CLI itself [has been deprecated since `npm@3.3.3`](https://github.com/npm/npm/blob/master/CHANGELOG.md#api-documentation-has-been-sacrificed-the-api-god), and edge cases like this are a large part of why. With some applied cleverness around how `npmlog` is installed and some API calls, you can probably work around this, but in general, the CLI team isn't going to go to any lengths to ensure that npm plays well with the REPL. As far as we're concerned, the supported and defined interface for the CLI is either via the command line or running the CLI via `child_process`. Thanks for your time!
