### ISSUE TITLE
Store mutilpe version modules in only one repository like maven

### ISSUE THREAD

**Issue by DonaldDu** [npm/npm#14210]
### Store mutilpe version modules in only one repository like maven
I think we should store mutiple version modules in locall center repository like maven, not in project.

**Comment by othiym23** [comment]
npm already does something like this for the cache (which lives under `$HOME/.npm` by default). This is what keeps npm from having to redownload a package each time you install it (although it does do freshness checks). For local installs, the `node_modules` tree is laid out the way it is to work with the Node.js module loader, as I just referred to in #14211.

If you want to save some disk space, you might want to take a look at [`ied`](http://npm.im/ied), [`pnpm`](http://npm.im/pnpm), or [`npm-install`](http://npm.im/npm-install), which are alternative npm installers that do something similar to what you're requesting, although their caching strategy is quite different from the npm CLI's. If you want something that looks more like a Maven-style layout, though, you may be out of luck, because again, module resolution is defined by the Node.js runtime and not npm. Thanks for your time!
