### ISSUE TITLE
Error while installing phonegap via npm

### ISSUE THREAD

**Issue by stevenjos27** [npm/npm#14281]
#### I'm opening this issue because:
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Unable to install phonegap through cmd. Currently using npm behind corporate proxy.Getting following error:

C:\Windows\System32>npm install -g phonegap@latest
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "phonegap@latest"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log
#### How can the CLI team reproduce the problem?

By running the following command on cmd:
npm install -g phonegap@latest

Link to npm-debug log:
https://gist.github.com/stevenjos27/bba3dc24119d7864993b5d0c81a4ae77
### supporting information:
- Network issues:
  I am using npm behind corporate proxy.

**Comment by zkat** [comment]
npm doesn't auto-discover Windows proxy settings, so you need to configure corporate proxies manually. Please look into [configuring npm to use your proxy](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/). You need to be able to access https://registry.npmjs.org in order to use our public registry.

That's pretty much the issue at hand here, so I'm going to close this issue. Feel free to comment if configuring a proxy doesn't help.
