### ISSUE TITLE
Error `uid must be an unsigned int` when running npm install.

### ISSUE THREAD

**Issue by skillzzjesse** [npm/npm#14297]
[npm-debug.pdf](https://github.com/npm/npm/files/531861/npm-debug.pdf)

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.  (no install at al)
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm install -g stream-adventure` returns the following. (about 100 times in a row)

```
npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "stream-adventure"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
```

#### How can the CLI team reproduce the problem?

run `npm install -g stream-adventure`

### supporting information:

 - `npm -v` prints: *3.10.8*
 - `node -v` prints: *v6.7.0*
 - `npm config get registry` prints: *https://registry.npmjs.org/*
 - macOS

**Comment by skillzzjesse** [comment]
I did btw run the command as super user. `sudo `

**Comment by skillzzjesse** [comment]
# update 
I got the same type of error `uid must be an unsigned int` when running 
`sudo npm install -g npm@latest`

The actual error:
```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<user>/npm-debug.log
```

**Comment by skillzzjesse** [comment]
@devMaterial 

Put `sudo` in front of your command to run it as superuser / administrator. 

If you look closely your error isn't quite the same as mine.

**Comment by DevMaterial** [comment]
@skillzzjesse 

Oops, pasted the wrong error.

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/TravisDaGreat/npm-debug.log
````

**Comment by skillzzjesse** [comment]
@devMaterial  Try updating node? Might help.... I'm in the dark on this too.

**Comment by DevMaterial** [comment]
@skillzzjesse I re-installed node and updated npm.

I did a bit of research and found out that apparently the problem is the latest npm version.

https://github.com/npm/npm/issues/13918

@tim545 from Issue #13918 mentioned that:

Node 6.6.0, npm 3.10.3 - ok
Node 6.6.0, npm 3.10.8 - errors

And reinstalling the old npm version wont work because you will get the same error we are having right now.

So yeah, im the dark too

**Comment by skillzzjesse** [comment]
Hmm yes, that does sound familiar.... I Just updated npm today and it has stopped working ever since.

**Comment by superdem** [comment]
Hey guys!
I had a same problem, and I fixed it just using this;

> $ brew install node

It is also help to update node version and It is fixed!

**Comment by DevMaterial** [comment]
@superdem 

Installed homebrew and tried the command, but still didnt work for me 
```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/TravisDaGreat/npm-debug.log
```

**Comment by superdem** [comment]
@DevMaterial 
please try in order;

> $ brew update
> $ brew doctor
> $ brew install node

**Comment by DevMaterial** [comment]
@superdem 

Gah, still didn't work.

I got this if it helps

```
Traviss-MacBook-Air:~ TravisDaGreat$ brew install node
Warning: node-6.8.1 already installed, it's just not linked
```

**Comment by superdem** [comment]
@DevMaterial 
Yes! You already update the node version.
Could you please check npm version like this ?

> npm -v
> 3.10.3

These is my npm version. And I'm using Sierra maybe you have to install MacOS Sierra to proper workspace.

**Comment by DevMaterial** [comment]
@superdem 

I installed macOS Sierra a few days ago.

```
npm -v
3.10.8
```

**Comment by superdem** [comment]
try clear npm cache
`
$ rm -rf ~/.npm
$ npm cache clear
`

**Comment by DevMaterial** [comment]
@superdem 

Still got the same error after attempting to install gulp. :(

**Comment by tim545** [comment]
Hi @DevMaterial, yeah that's right it's a bug in the latest npm version, I took a quick look and it seems the solution I posted in that last thread won't work anymore because the "current" release has been updated and will come packaged with npm@3.10.8, which get's installed with node.

You can't downgrade the npm version using the `npm install -g npm@3.10.3` command because it get's that same error, preventing the install to fix the error.

Chances are the brew repository has updated to the latest version as well which would cause the same errors.

You can however fix it in a couple of ways:

1. Download the LTS version of Node from nodejs.org, this is the stable version which won't get error like this, when you run the package installer it will also install the version of npm which was packaged at the time. The newer version your using is more of an "experimental" version, likely to have errors...

2. You can use `nvm` (node version manager) to install an older version of Node, which will also install the packaged version of npm at the time (AKA not 3.10.8). This is a bit more complicated and I'd try the first option before this because it should just get your code running without problems, but to do it you need to install the nvm tool:

cURL:
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash`

Wget:
`wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash`

brew:
`brew install nvm`

and then install the required version, because the last time I did this 6.6.0 worked and installed npm@3.10.3 with no errors I'll put that here as an example:
`nvm install 6.6.0`

The new version should be activated by nvm automatically and you can check the version of both:

`node --version` (should be 6.6.0)
`npm -v` (should be 3.10.3)

If the versions are wrong you can use nvm to change to the active version:
`nvm use 6.6.0`

**Comment by skillzzjesse** [comment]
Indeed, downloading and installing the LTS version of node seems to fix the issue for me. 
It installs node at `v4.6.0`
and npm at `2.15.9` 

Thanks for the help! @tim545
