### ISSUE TITLE
npm link & docker containers

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#14325]
on latest versions of NPM and Node.

```
npm -v -> 3.10.8
```

when developing projects locally, I use npm link, but when creating Docker containers, modules that are symlinked don't seem to get copied over from node_modules to the docker destination.

Here is the Dockerfile:

```
FROM node:6.7.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD ARG NODE_ENV
ONBUILD ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/
RUN ls -alR /usr/src/app
RUN npm install
COPY . /usr/src/app
EXPOSE 80
```

is this a known problem? I am new to Docker so it's harder to explain what's happening, but definitely has to do with "npm link".

What happens is that the Docker log will say:

```
cannot find ./node_modules/my-symlinked-module
```

so I go back to the project and do:

```
npm unlink my-symlinked-module
npm install -S my-symlinked-module@latest
```

then re-build the Docker image, and it seems to work.

**Comment by iDVB** [comment]
+1

**Comment by ORESoftware** [comment]
@iDVB glad I wasn't imagining things and am not the only one!

**Comment by jesseditson** [comment]
This was the first google result for this problem for me, and I was curious if there was a cleaner way to solve for this than I had found. In case it helps others, here's what I've done when dealing with this situation.

I'll speak from the perspective of MacOS/Docker For Mac because that's my setup, but this happens because your dockerfile doesn't usually (nor should it) copy over information from outside the cwd.

**why this is happening**

When you run `npm link`, what it's doing under the hood is creating a symlink from `.` to `/usr/local/lib/node_modules`.
On the other side, when you `npm link package-name`, it creates a link from `node_modules/package-name` to `/usr/local/lib/node_modules/package-name`.

If you were to run `docker run --rm -it your-image-name:latest ls -al node_modules | grep -e "->"`, you'll likely see something like this:
```
package-name -> ../../../../../../usr/local/lib/node_modules/package-name
```

It's very unlikely that there's anything at all in your docker container at that path, which is why npm is telling you that file doesn't exist - it's right, it doesn't!

**the problem**

Unfortunately AFAIK `npm` doesn't allow you to create non-relative symlinks with `npm link`, which is problematic in that the directory structure of your docker container is pretty much never going to be the same as the directory structure of your local laptop.

In addition, since nothing is copied from `/usr/local` to the image, even _if_ your directory structure were to match, the file still wouldn't exist.

**a complex workaround**

Because `npm link` makes relative symlinks, and because docker doesn't allow using volumes outside of `$HOME` by default, I can't think of a solution that doesn't require modifying your local fs and docker settings.

However, here's one way:

1. Update Docker for Mac settings to include `/usr/local/lib/node_modules` in the shared folders so you can use it as a volume:

![image](https://cloud.githubusercontent.com/assets/370239/23780845/1d563e58-04fe-11e7-9edf-094c6fe36e1e.png)

2. Update any local symlinks to be absolute. Link them using `npm link package-name`, then run this script (or something similar): https://github.com/jesseditson/absolutize-links

3. Add a volume to your docker config:

To run a `docker` command, add a `-v /usr/local/lib/node_modules:/usr/local/lib/node_modules` - this will mount your local npm node_modules on your docker container, which will make them available. You'll unfortunately also need to add a `-v` flag referencing the local linked modules' folder. 

If you're using `docker-compose`, you can add these entries as `volumes` keys in your `docker-compose.yml`, so they'll always be there when you restart your container.

There's quite a lot of nuance when it comes to setting up docker volumes, so I'll leave it at the above for now, but the idea here is that you'll need **both** `/usr/local/lib/node_modules` and `/path/to/the/linked/module` defined as volumes when you run your docker image.

**notes**

At work, I have a script I run that wraps docker-compose commands and adds some guards and guarantees around npm links. I unfortunately can't share that project, but you could implement something similar.

I'd be interested to hear about the thinking behind npm links being relative, as I'm sure that was an intentional design decision (/cc @othiym23 ?).
If that were to be something we could add a flag for, we could solve the npm side of this, but docker would still be unable to see those files unless they were linked in.

My feeling is that this is not really up to either the docker or the npm team to solve, as both tools are working as expected. I could see either team making it easier, but something this specific likely doesn't belong in either tool.

I may implement a solution for this use case I can share, but I have yet to think of a clean way to solve this without an abstraction, which I have little interest in building. I'm following this issue now, and would absolutely love to hear about how others have gotten around this.

**Comment by ORESoftware** [comment]
bump

**Comment by ORESoftware** [comment]
I don't think this issue should have been closed lol

**Comment by gabidi** [comment]
Bumpitybump

**Comment by ORESoftware** [comment]
Bumpity bump bump -  I think this issue belongs on the Docker repo, it's not a problem with NPM.

**Comment by valoricDe** [comment]
If you install global modules in your home directory you could create a volume to sync it right? https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
