### ISSUE TITLE
Update npm2 package on the npm registry

### ISSUE THREAD

**Issue by laggingreflex** [npm/npm#14342]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

[`npm2` package on the npm registry](https://www.npmjs.com/package/npm2) is at version 2.0.0 

It should be updated to the latest version 2.15.11

**Comment by KenanY** [comment]
I don't believe that package is owned by anyone on the `npm` team. As such, there's nothing we can do here. (If I am mistaken, then someone else can reopen.)

**Comment by laggingreflex** [comment]
I tried to email them at the email address listed on the npm page: betterpm-npm@gmail.com but I got an error from gmail saying the email doesn't exist. 

Any other way this can be resolved?

**Comment by KenanY** [comment]
@laggingreflex No idea. How important is its resolution to you?

**Comment by othiym23** [comment]
If you want to get the latest version of `npm@2`, it's far better to depend on `npm@latest-2` (or `npm@lts`), which is maintained by the npm CLI team, rather than using `npm2`, which is an unofficial backport.

**Comment by laggingreflex** [comment]
I don't actually have a dependency on it per se, I just had a particular use case where I thought installing with npm2 seemed faster than npm3 or [even yarn](https://github.com/yarnpkg/yarn/issues/1244).

So I wanted to have both versions, `npm` being the default latest and having an `npm2` on the command line which was better than switching back and forth. 

In fact before I found it I was gonna ask whether you guys would consider officially publishing such versioned packages like npm2, npm3 etc?

**Comment by othiym23** [comment]
> In fact before I found it I was gonna ask whether you guys would consider officially publishing such versioned packages like npm2, npm3 etc?

The CLI team's preference is that everybody run `npm@latest`, as that's the version we know to be closest to bug-free. `npm@2` may install very quickly in some cases, but it does so at the cost of many, many inconsistencies and bugs. Since many of those are aspects of its design that were specifically addressed by `npm@3` (and the upcoming `npm@4`), it doesn't make sense to us, as a team, to support people switching between different versions of npm.

We're not going to get in the way of people producing packages like `npm2`, but at the same time, they're not something to which we're going to give official support.
