### ISSUE TITLE
Include coverage reports on Readme

### ISSUE THREAD

**Issue by cameronroe** [npm/npm#14415]
#### I'm opening this issue because:
- [x] Other
#### What's going wrong?

It's not clear to know how well covered npm is. It also says the build is failing.
#### How can the CLI team reproduce the problem?

Go to the Readme. Look at the shield that says build:failing.
#### What's the feature?

Add support for code coverage [shields](http://shields.io/) using [coveralls](https://coveralls.io/) or [codecov](https://codecov.io)
#### What problem is the feature intended to solve?

Add better visibility and management of code quality.
#### Is the absence of this feature blocking you or your team? If so, how?

No. But it makes me feel sad inside.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Sure, I'd be happy to help add in support for [codecov](https://codecov.io).

**Comment by KenanY** [comment]
Some good news: builds are actually [passing](https://travis-ci.org/npm/npm), but the badge was pointing to the wrong branch. Should be fixed by https://github.com/npm/npm/pull/14426. Also, coverage reports are already available through [coveralls](https://coveralls.io/github/npm/npm), just need to add the badge.
