### ISSUE TITLE
 npm package contains empty file

### ISSUE THREAD

**Issue by baderbuddy** [npm/npm#14428]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

The file at path /test/fixtures/config/package.json is empty, when I'm trying to run a vulnerability scan over npm it breaks because it can't read this file (due to it being empty), should the test folder even be included in the npm package?
#### How can the CLI team reproduce the problem?

Run OWASP Dependency Check over a directory containing an npm tarball.

### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X/macOS, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
tbh, I don't even know what this is used for but it's part of our test suite, which we *do* distribute (for example, node uses the distributed test suite in order to run npm tests itself with its distribution). I see no bug on our end here, but if you remove it and our tests still pass, we'll take a PR to discuss whether to get rid of it -- it might just be used by one of our many tests in some way or another, so I'm hesitant to just do it and I assume there's a reason for it to be there like that.

**Comment by baderbuddy** [comment]
I added a PR, the Travis build succeeded. https://github.com/npm/npm/pull/14435
