### ISSUE TITLE
CI Appveyer build takes 31 minutes. Consider using ava.

### ISSUE THREAD

**Issue by cameronroe** [npm/npm#14431]
#### I'm opening this issue because:
- [x] Other (_see below for feature requests_):
#### What's going wrong?

The CI build on Appveyer currently takes 31 minutes to complete.
#### How can the CLI team reproduce the problem?

Look at [this page](https://ci.appveyor.com/project/npm/npm/build/1344) that changes a simple badge.
#### What's the feature?

Begin migration of test suite to [ava](https://github.com/avajs/ava).
#### What problem is the feature intended to solve?

Runs tests concurrently. Beneficial for IO heavy tests. In addition, test files are run in parallel as separate processes, giving even better performance and an isolated environment for each test file.
#### Is the absence of this feature blocking you or your team? If so, how?

Slow delivery of bug fixes.
#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Happy to contribute to a PR.

**Comment by othiym23** [comment]
```
ogd@bauchelain ~/D/p/n/npm> cloc test
     298 text files.
     298 unique files.
       7 files ignored.

github.com/AlDanial/cloc v 1.70  T=1.03 s (281.3 files/s, 29029.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     291           3473            449          26106
-------------------------------------------------------------------------------
SUM:                           291           3473            449          26106
-------------------------------------------------------------------------------
ogd@bauchelain ~/D/p/n/npm> cloc lib
     164 text files.
     164 unique files.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.70/libexec/bin/cloc line 7327.
       0 files ignored.

github.com/AlDanial/cloc v 1.70  T=0.74 s (221.6 files/s, 22564.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     162           2014           1061          13526
Bourne Shell                     1              2              8             48
Markdown                         1              9              0             28
-------------------------------------------------------------------------------
SUM:                           164           2025           1069          13602
-------------------------------------------------------------------------------
```

There are ~4250 tests, in tap terms (which is to say, a combination of mocha / ava assertions and spec blocks), in the current npm test suite, comprising ~26K lines of JavaScript. A significant fraction of those tests are integration tests that, in turn, run child processes. The vast majority of a test run's time is spent waiting on those child processes, some of which are running pretty complex scenarios to ensure that high-level functions of the CLI (shrinkwrap, installing private packages) continue to work as expected. In short, the test suite is probably about as complicated as the CLI itself.

In addition, at this point it's pretty difficult to tease apart npm and `node-tap`, because the latter has been developed in large part to support the needs of the former. `nyc`, too, on which I know ava depends, was something that was developed by one of our colleagues here at npm to answer a need of the CLI's code base (all those child processes made it very difficult to gather coverage information otherwise). Also, a lot of the tests are written in a fairly idiosyncratic, `node-tap`-specific way, that make it difficult both to isolate the tests (they tend to reuse / share test directories and the local npm cache).

None of these eliminate the possibility of porting the test suite to a different runner, but they help delineate the scale of the task, which is significant. To give you an idea of what this means in practice, when the team decided that it was time for us to clean up test runs under Windows, it took us _several months_ to get all the tests passing (in many cases, for the first time) under Windows, and we're _still_ working on getting the test suite green under AppVeyor.

This is why the idea of moving npm's tests to a different test suite, particularly in a situation where we'd have to be making significant architectural changes to how the tests are run in order to take advantage of the new test framework's possibilities, fills me with nearly existential levels of dread. In my estimation, it's as risky and complex a project as any of the CLI's major releases  so far. In addition, were we to do so, we'd lose access to the considerable advantages we as a team get from having the maintainers of both `node-tap` and `nyc` working alongside us.

Either way, though, thanks for your time, and thanks for the thoughtful suggestion! If there's an area where npm could benefit most, it's improvements to its test suite, both in terms of speed and in terms of coverage (e.g. #14430). It just turns out that doing those things is a big challenge!

**Comment by cameronroe** [comment]
Understandable. Considering ~4250 is a colossal amount of tests. Is there conversation around breaking npm into smaller modules similar to the babel ecosystem? Maybe that would improve coversation around migration/coverage..?

**Comment by othiym23** [comment]
It already is! Large chunks of the CLI have been broken out into separate modules like `npm-registry-client`, `read-package-tree`, and `normalize-package-data`. Not to mention external dependencies like `request`, which does a huge amount of the heavy lifting around things like HTTPS proxy support.

In the future, the team would very much like to see the CLI be a small scaffolding the connects separate packages that manage things like npm's cache, the various pieces of the installer, auth strategies, and the like. Given how tightly coupled a lot of the current architecture is, though, and the complementary need to not disrupt the thousands of users who rely on npm, progress towards that goal is necessarily slow. We continue to plug away at it, though, and `npm@5` should see some significant improvements around npm's internal modularity.

**Comment by cameronroe** [comment]
🙏
