### ISSUE TITLE
Markdown on Github vs markdown on npmjs.org

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#14434]
On latest versions of NPM and Node. However those versions don't matter, because I am talking about `npmjs.org` versus `github.com` when it comes to markdown (syntax highlighting, html etc).

To be blunt, why does my same exact markdown look so bad on npmjs.org, when it looks decent on Github?

https://github.com/ORESoftware/suman
https://www.npmjs.com/package/suman

is it a different markdown parser/interpreter or something?

**Comment by KenanY** [comment]
This probably belongs over here: https://github.com/npm/www

**Comment by ashleygwilliams** [comment]
hello @ORESoftware !

a couple of things:
- firstly, this is an issue with the npm website, which you filed on the npm cli issue tracker. for future issues you have with the npm website, please file them at https://github.com/npm/www
- secondly, yes- the npm website uses a different markdown parser. that parser is called [marky-markdown](https://github.com/npm/marky-markdown) and it strives for github-flavored markdown parity by adding custom plugins to the markdown-it package which follows the [CommonMark spec](http://commonmark.org/). GitHub flavored markdown doesn't have or follow any spec.
- if you have a specific complaint about how the parser is behaving in a way that you don't expect, i.e. is different from GitHub, please file it as an issue. please note that general "why is this so bad" issues will be considered not-constructive and will be closed.

since this issue is filed on the wrong repo and does not have a specific issue i am going to close it.

**Comment by ORESoftware** [comment]
thanks, I wish Github had a transfer issue to other repo feature ;)
