### ISSUE TITLE
Error install express  "ms@0.7.1, http-error" in a polymer's project

### ISSUE THREAD

**Issue by Ingosmar89219** [npm/npm#14533]
I have a problem like this. im trying to install express in my project's polymer BUT i Cant get the carpet node_modules heres my error.
C:\Users\osmarvirux\Documents\messenger>npm install express
express@4.14.0 ..\..\node_modules\express
├── array-flatten@1.1.1
├── escape-html@1.0.3
├── path-to-regexp@0.1.7
├── fresh@0.3.0
├── content-disposition@0.5.1
├── cookie@0.3.1
├── cookie-signature@1.0.6
├── parseurl@1.3.1
├── encodeurl@1.0.1
├── serve-static@1.11.1
├── content-type@1.0.2
├── etag@1.7.0
├── vary@1.1.0
├── methods@1.1.2
├── range-parser@1.2.0
├── utils-merge@1.0.0
├── merge-descriptors@1.0.1
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, mime@1.3.4, ms@0.7.1, http-error
s@1.5.0)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)

I believe the problem is this  "ms@0.7.1, http-error
s@1.5.0)" 
Im using C:\Users\osmarvirux>npm -v
1.4.20
C:\Users\osmarvirux>express --version
3.0.0
C:\Users\osmarvirux>bower --version
1.7.9

**Comment by KenanY** [comment]
@Ingosmar89219 Thanks for opening this issue. As I've mentioned before, I do not see an error in the output you've posted. `npm` is simply printing out a dependency tree in order to summarize what was installed. What you're seeing here:

```
├── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, mime@1.3.4, ms@0.7.1, http-errors@1.5.0)
```

is not an error, but a list of dependencies. `http-errors` is [a module](https://www.npmjs.com/package/http-errors), and should not be taken to mean that an error has occurred. Does this explanation clear things up for you?

**Comment by KenanY** [comment]
Closing due to no response
