### ISSUE TITLE
[feature] [documentation] No require('npm') API description

### ISSUE THREAD

**Issue by polkovnikov-ph** [npm/npm#14599]
#### What's the feature?

Documentation for `require('npm')`. Probably, some work also needed on public API to make the documentation meaningful.

#### What problem is the feature intended to solve?

I needed to work on the result of `npm ls`, and would prefer not to use regexps. There's a lot of possible tooling on top of `npm` that are quite unpleasant to write without any documentation (and. probably, would be hard to support due to breaking changes in the API).

#### Is the absence of this feature blocking you or your team? If so, how?

I have no idea how to set `package.json` with the exact versions of installed libraries otherwise. Even if there already is an existing way to do so, it would be much faster to write several lines that do this thing from scratch instead of searching for a "proper way". I guess, no, this doesn't block me.

#### Is this feature similar to an existing feature in another tool?

Yes, all good CLI tools have programmatic access with a good manual on it. Take a look on `browserify`, for example.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

I'm afraid this requires a lot of architecture work to split internal and public APIs and to keep public API semver-compliant. There's not much I can do.

**Comment by KenanY** [comment]
IIRC, the current API is not supported so I doubt any documentation would be written for it. Plan is to, eventually, [decouple](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-api) some of the internal stuff at which point this might be a bit more feasible.

**Comment by polkovnikov-ph** [comment]
@KenanY There was already a documentation, it just got removed. I think having a NB "0 - Unstable" would be fine while the issues mentioned in wiki get fixed.

BTW wiki was not updated for over a year and not much changed. Could we ask Rebecca to create some real issues?

**Comment by othiym23** [comment]
As @KenanY explained, the CLI team removed the API documentation in `npm@3` because we decided that the internal API is not fit for use by external callers. This is still true, and the work to break npm into more modular, more easily consumable APIs continues,  albeit very slowly. 

As the project is very unlikely to offer programmatic access to npm APIs in the near to medium term, I'm going to close this issue and reiterate the team's strong recommendation that the supported way to use the CLI from within your own software is as a child process, which allows you to use the (maybe even excessively) documented command-line options and configuration. Thanks for your time!

**Comment by polkovnikov-ph** [comment]
@othiym23 You didn't mention that some (all?) APIs support `--json` option. That makes an approach with `child_process` more viable than I've thought initially, even though there's a lot of time lost on printing/parsing and due to synchronous nature of JSON.* APIs. Thanks for a fast answer!
