### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by messense** [npm/npm#14618]
#### I'm opening this issue because:

  - [X] npm is crashing.

#### How can the CLI team reproduce the problem?

https://gist.github.com/messense/cd9eb7d148156827d3e0813c2452f6d7

### supporting information:

 - `npm -v` prints: v6.9.1
 - `node -v` prints: v3.10.8
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Linux: Ubuntu 16.04
 - Container:
   - [X] I develop / deploy using Docker.

**Comment by legodude17** [comment]
Do you have a proxy or VPN?

**Comment by KlemensE** [comment]
I am getting the same error trying to execute the command 

ionic start Test --v2

It trys to install https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip

Running Windows 10 1607

[npm-debug.zip](https://github.com/npm/npm/files/590404/npm-debug.zip)

**Comment by legodude17** [comment]
Does that work for you @messense?

**Comment by messense** [comment]
@legodude17 No, no proxy/VPN used. Also the error seems occurring randomly, sometimes it just works fine. Only seen these errors since yesterday.

**Comment by messense** [comment]
Tried upgrade npm by `npm install -g npm`, still getting these errors randomly.

**Comment by kgryte** [comment]
I am seeing this same error both on AppVeyor and Travis CI. The error occurs randomly (some jobs are fine and others fail) causing builds to fail.

Does not appear to be a proxy/VPN issue; otherwise, jobs should fail consistently. This affects Windows, Linux, and Mac OS build environments.

And `npm install -g npm` does not resolve the issue. My build environment already upgraded `npm` using this command prior to encountering this error.

Other issues seem to be related; e.g., npm/npm#14612.

**Comment by soldair** [comment]
we have released a change to our cdn configuration that will retry requests errored with 400 internally. this should resolve the external issue while we dig in to why these are being sent.

**Comment by messense** [comment]
Didn't see any error recently. Thanks.
