### ISSUE TITLE
C: \ Users \ anny_ \ AppData \ Local \ Temp \ apm-install-dir-1161014-7000-1mzw1cy \ npm-debug.log

### ISSUE THREAD

**Issue by fanycobain** [npm/npm#14628]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
I'm gonna close this issue since it is blank. @fanycobain, please take the time to fill out the support form in your post. Also, uploading the generated `npm-debug.log` file to <https://gist.github.com/> and posting the link here would help as well. Once you've done all that, let me know and I will happily reopen.
