### ISSUE TITLE
Failed PUT 404 error to Artifactory

### ISSUE THREAD

**Issue by daltongriner** [npm/npm#14634]
I am trying to publish a scoped npm package to artifactory.

My .npmrc file is formatted the following way:

registry=http://artifacts.company.com/artifactory/api/npm/npm-local/
_auth="encodedpassword"
always-auth=true
email=d.griner@company.com
@acres:registry=http://artifacts.company.com/artifactory/api/npm/npm-local/
//artifacts.company.com/artifactory/api/npm/npm-local/:_password=endcodedpassword
//artifacts.company.com/artifactory/api/npm/npm-local/:username=myusername
//artifacts.company.com/artifactory/api/npm/npm-local/:email=d.griner@company.com
//artifacts.company.com/artifactory/api/npm/npm-local/:always-auth=true

when I run npm publish I get a failed PUT 404 error.
The debug.log is attched.
[debug.txt](https://github.com/npm/npm/files/592898/debug.txt)

what am I missing?

**Comment by legodude17** [comment]
My guess is that you server is configured the wrong way for scoped packages. Will it accept PUT to `http://artifacts.amirsys-int.com/artifactory/api/npm/npm-local/@acres%2facresmetajs`?

**Comment by daltongriner** [comment]
I was thinking it may be that.  It accepts PUT but I get the same 404 error.

**Comment by legodude17** [comment]
404 means "Not Found". Please check your configuration on the registry.

**Comment by krihelis** [comment]
Hi, 

I assume that you get 404 errors only with scoped packages. 
If your Artifactory is running behind a reverse proxy, make sure to disable URL decoding on the proxy itself in order to work with npm scope packages. 

You can find more info in Artifactory-npm registry [page](https://www.jfrog.com/confluence/display/RTF/Npm+Registry) in the Artifactory user guide. 

Hope that helps.

**Comment by daltongriner** [comment]
krihelis that was the problem. Thank you!

**Comment by KenanY** [comment]
Closing as resolved.
