### ISSUE TITLE
Error 34 NPM

### ISSUE THREAD

**Issue by sthynet** [npm/npm#14648]
System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /usr/local/bin
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! path /usr/local/bin/package.json
npm ERR! code ENOENT
npm ERR! errno 34
[npm-debug.log.zip](https://github.com/npm/npm/files/597737/npm-debug.log.zip)

**Comment by KenanY** [comment]
@sthynet `npm@1.3` is years old and is no longer supported. Nevertheless, I believe your issue is that you are trying to run `npm start` from a directory which contains no `package.json` file. I suggest you both update `npm` and read [the documentation on scripts](https://docs.npmjs.com/misc/scripts).

**Comment by sthynet** [comment]
Thank you for your answers.
