### ISSUE TITLE
npm version doesn't pass the right environment to git

### ISSUE THREAD

**Issue by FredericHeem** [npm/npm#14708]
#### I'm opening this issue because:

On windows 7, `npm version patch` is invoking `git` without the correct environment, resulting in a commit with the wrong author.
#### What's going wrong?
The git commit author is `unknown <windowsusername@machinename.mydomain>`

#### How can the CLI team reproduce the problem?

Check your git username and make sure it's configured properly:
`$ git config user.email`

Run the `version patch` command:
`$ npm version patch`

Now check the git commit author:
`$ git log`

and check whether the author is correct.

### supporting information:

 - `npm -v` prints: 4.0.2
 - `node -v` prints: 4.4.1
 - Windows, OS X/macOS, or Linux?: Windows 7

 Other useful environment variables:
 
```
HOMEDRIVE=H:
USERPROFILE=C:\Users\myusername
```

Note that the `.gitconfig` is on `H:` and the `.npmrc` is on `C:\Users\myusername
`
`npm` is probably invoking `git` without the correct environment but that's just a guess.

Thanks in advance.

**Comment by MicahZoltu** [comment]
I have explicitly set the `GIT_CONFIG` environment variable to point away from the default path.  This results in the provided commands not actually working (`git config --global user.email "you@example.com"`) because `GIT_CONFIG` environment variable is incompatible with `--global` because reasons (I assume).

I checked the environment of the node process that is spawned when I do `npm version patch` and I can see that it is correctly receiving the `GIT_CONFIG` environment variable, but for whatever reason it isn't using it.  Interestingly, I do not see the node process spawn a `git` process... perhaps NPM is using its own internal `git` library rather than the CLI, in which case this is likely a problem with that library not supporting `GIT_CONFIG` environment variable?

**Comment by MicahZoltu** [comment]
Also of note, the same problem occurs on Linux Subsystem for Windows, which is using Linux NPM and Git binaries (Ubuntu distribution specifically).  If you have a `GIT_CONFIG` environment variable set it appears that it is ignored.

While LSfW isn't a smoking gun of "not a Windows specific problem", it is pretty compelling that this problem is more far reaching than just Windows.

Yet another data point:
1. `git config --global user.email "foo@bar.com"`
2. `git config --global user.name "Baz"`
3.
```
cat >/path/to/.gitconfig <<EOL
[user]
	name = Apple
	email = banana@cherry.com

```
3. `export GIT_CONFIG="/path/to/git/config"`
4. `git commit --allow-empty --message "hello"`
--> notice that the commit is authored by `banana@cherry.com`
5. `npm version patch`
--> Notice that the commit was created with the `foo@bar.com` author rather than the `banana@cherry.com` author.

The above further supports that however NPM is calling git, it is completely ignoring the `GIT_CONFIG` environment variable and using the OS default `.gitconfig` path instead.

**Comment by MicahZoltu** [comment]
I checked briefly to see if there was an obvious problem, unfortunately nothing pops out to me.  For those who come after:

This is where npm version calls into git:
https://github.com/npm/npm/blob/latest/lib/version.js#L267

That eventually calls into `exec` with nothing special besides `-c core.longpaths=true` added to the git command:
https://github.com/npm/npm/blob/latest/lib/utils/git.js#L23

`execFile` is documented here (not sure where the source lives):
https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

You can also see in the output the command that was executed doesn't have anything particularly surprising in it.
