### ISSUE TITLE
`$ npm install` halts without completing dependency installation when warnings are thrown

### ISSUE THREAD

**Issue by DinkDonk** [npm/npm#15053]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When I run `$ npm install` it throws warnings, but no errors (as it rightfully should based on my package.json), it creates the `node_modules` directory and then halts without doing the actual dependency install, leaving an empty `node_modules` directory.

Expected outcome is that warnings should not be equal to errors, and the install should complete in spite of warnings thrown.

#### How can the CLI team reproduce the problem?

- Init a npm package.
- Change the `name` property to:
```json
{
  "name": "<template_name_slug>",
  ...
}
```
- Run `$ npm install`

It will output this and not complete installation:

```bash
npm WARN Invalid name: "<template_name_slug>"
```

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 7.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Pinging @zkat, as this seems to be a bug, or at least bad design.

**Comment by withw** [comment]
It happens cause of [read-package-tree](https://github.com/npm/read-package-tree) returns with error and empty packages list, when you have (for example) invalid ``name`` or ``version`` field. And it happens cause [read-package-json](https://github.com/npm/read-package-json) returns error, which happens due to [normalize-package-data](https://github.com/npm/normalize-package-data) throws an error.

So we should look at this issues:
 - https://github.com/npm/normalize-package-data/issues/6
 - https://github.com/npm/read-package-json/issues/3
