### ISSUE TITLE
node-pre-gyp ERR! 

### ISSUE THREAD

**Issue by tahsintahsin** [npm/npm#15104]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I cannot properly run npm install on my windows machine

#### How can the CLI team reproduce the problem?

It happens when fsevents is being installed, the error message is:
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v46-win32-ia32.tar.gz

### supporting information:

 - `npm -v` prints: 
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dunnock** [comment]
Is not it the same issue https://github.com/strongloop/fsevents/issues/157 , if so it should be marked as a bug in npm flow.

**Comment by KenanY** [comment]
My first guess would by that @tahsintahsin's issue is an internet connection one, since the error message says "Tried to download" and presumably it failed.

@tahsintahsin Could you provide the full `npm-debug.log` as plaintext? You can upload it to <https://gist.github.com/> and post a link to it here.

**Comment by springmeyer** [comment]
@dunnock that issue is unrelated. The problem here is that fsevents is not supported on windows. And @tahsintahsin is trying to install it on windows. It looks like https://github.com/strongloop/fsevents/commit/ca07cfdb534f6f85a4a918bc99ef414d191275dc was recently added to fsevents to throw a more obvious error in this situation.

**Comment by es128** [comment]
No, that hasn't landed in master. It shouldn't be installing at all, npm should be skipping it because of the mismatched platform. 

There might be a shrinkwrap file generated on a mac involved in this case throwing things off.

**Comment by es128** [comment]
#2679 tracks the latter concern. If it's not that, we're going to need more details from the op
