### ISSUE TITLE
All-user permissions for global install?

### ISSUE THREAD

**Issue by edemaine** [npm/npm#15107]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

On Linux, when I install a package globally with prefix `/usr`, the created directory in `/usr/lib/node_modules/` (and all files and directories within) have the wrong mode: 700 (readable only by `nobody`) instead of 755 (readable by everyone).  To enable multiuser installations of Node (not in your home directory, and not on a single-user machine as common for Windows and OSX, so you can't just `chown` the directory), setting these permissions right seems like a basic feature we should support (and could support by a recursive `chmod`).  If there's interest, I can work on a PR.

#### How can the CLI team reproduce the problem?

`npm prefix -g /usr`
`sudo npm install -g coffee-script`
`ls -l /usr/lib/node_modules/coffee-script`

Resulting output:

    drwx------ 4 nobody edemaine 4096 Dec  1 17:15 coffee-script

As a result, for example, running `coffee` gives "command not found", because `/usr/bin/coffee` links into this directory.

Desired output:

    drwxr-xr-x 4 nobody edemaine 4096 Dec  1 17:15 coffee-script

(and similarly in all containing files)

### supporting information:

 - `npm -v` prints: 2.15.5
 - `node -v` prints: v4.4.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Cambridge, MA, USA
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by othiym23** [comment]
There are two things happening here, one of which is a longstanding bug / undesirable feature, one of which is a feature-request:

1. `node-tar` uses the ownership as found in the package tarball to set user and group membership on unpacked files. _No_ files should ever be owned by `nobody`, as that's a potential security vulnerability (because `nobody`'s purpose is to have the least privileges possible for exposed services). Probably the CLI should be doing a `chownr` to get individual packages to share the ownership of `$PREFIX/lib/node_modules` when run with superuser privileges.
2. The CLI, by default, uses the umask of the running user when creating new directories or files, which is why this is getting created with perms of `0700`. That can be configured specifically for npm using the [`umask`](https://docs.npmjs.com/misc/config#umask) configuration parameter (I know the documentation says that it defaults to `022`, but I believe that's because that's what macOS defaults to). So what you're proposing would be an override for a configurable behavior that's already supported. Knowing that that property exists, is this still something you'd like to see changed?

**Comment by edemaine** [comment]
Agreed on point 1: when running as root, `chownr` to match `$PREFIX/lib/node_modules`, instead of the tarball, makes sense.  (For reference, on my Debian install, `/usr/lib/node_modules` is owned by `root`, has group `root`, and permissions `0755`, which seems good.  Good point about `nobody`.)

By analogy, for point 2, it seems that the perms of `$PREFIX/lib/node_modules` should serve as the mask on perms in the package tarball, instead of the user's `umask`, when no `umask` configuration parameter exists.  (I was going to say that they should match, but then you'd need special handling of executable bits, so that only files/directories get marked user-executable in the tarball should get executable user/group/other perms.  Luckily, masking takes care of this behavior perfectly.)  In this case, we could change the `umask` configuration parameter documentation to say that it defaults to the permissions of `$PREFIX/lib/node_modules`.

Following the user's `umask` makes some sense for user installs, but to me makes no sense for global (multi-user) installs.  And I can't see a disadvantage to using the perms of `$PREFIX/lib/node_modules` as the mask even for local installs.  If you user wanted some modules readable and others not, the user could still use the `umask` configuration parameter.

Alternatively, we could just make the `umask` configuration parameter actually default to `022`, as in the documentation...
