### ISSUE TITLE
issue with the grunt-cli installation.

### ISSUE THREAD

**Issue by patilharsh555** [npm/npm#15142]
I tried installing npm install -g grunt-cli but got several errors which I'm unable to rectify. The error message is as follows:

C:\POCH>npm install -g grunt-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\POCH\npm-debug.log

Kindly help me resolve this.
Thanks in advance.

**Comment by zkat** [comment]
npm doesn't auto-discover Windows proxy settings, so you need to configure corporate proxies manually. Please look into [configuring npm to use your proxy](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/). You need to be able to access https://registry.npmjs.org in order to use our public registry.

That's pretty much the issue at hand here, so I'm going to close this issue. Feel free to comment if configuring a proxy doesn't help.
