### ISSUE TITLE
npm installation of prod and dev (local) dependency

### ISSUE THREAD

**Issue by tomasAlabes** [npm/npm#15360]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  
#### What's going wrong?
```javascript
"dependencies": {
  "myModule": "1.0.0"
},
"devDependencies": {
  "myModule": "file:../myModule/"
}
```
`npm install` installs the production dependency instead of dev dependency (shows a warning though).

#### How can the CLI team reproduce the problem?
Having a package.json with a prod dependency pointing to a version and a dev dependency pointing to a local dir.
This helps when you are working with a local dependency and you want that dep to be installed when working in development mode.

### supporting information:
 - `npm -v` prints:
4.0.5
 - `node -v` prints:
v7.3.0
 - Windows, OS X/macOS, or Linux?:
macOS

**Comment by legodude17** [comment]
What do you think `npm` should do?

**Comment by tomasAlabes** [comment]
Install the dev dependency, you are running `npm install` after all... without `--production`

**Comment by legodude17** [comment]
Ok. I think this will need to be discussed more.

**Comment by cjbarth** [comment]
What is the rationale behind installing the `dependencies` instead of the `devDependencies` when `npm install` is run without the `--production` flag?

I am under the impression that if a user intentionally and directly runs `npm install` on a package it is because they want to develop and that is why the `devDependencies` are installed in the first place. It would only make sense then that any conflicts would be resolved by choosing the most restrictive set of dependencies, and in this case it would be `devDependencies` because there are scenarios in which those dependencies aren't installed, thereby making them more restrictive in their scope then the always-installed `dependencies`.

**Comment by cjbarth** [comment]
I have a StackOverflow question that inquires about a valid use-case: http://stackoverflow.com/questions/41168413/install-prefer-devdependencies-over-conflicting-dependencies
