### ISSUE TITLE
deterministic failures with `npm ls`

### ISSUE THREAD

**Issue by MylesBorins** [npm/npm#15420]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

we found that `npm` v4.0.5 is consistently making an incorrect install of [uglify-js v2.7.5](https://github.com/mishoo/UglifyJS2/releases/tag/v2.7.5)

#### How can the CLI team reproduce the problem?
```
$ node -v 
v6.x || master
$ npm -v
4.0.5
$ curl -L https://github.com/mishoo/UglifyJS2/archive/v2.7.5.tar.gz | tar zx && cd UglifyJS2-2.7.5/
$ npm install
$ npm ls
npm ERR! extraneous: optionator@0.5.0 /Users/thealphanerd/code/UglifyJS2/node_modules/optionator
npm ERR! missing: yargs@~3.5.4, required by uglify-js@2.4.24
npm ERR! missing: cliui@^2.1.0, required by yargs@3.10.0
```
### supporting information:

 - `npm -v` prints: v6.x or master
 - `node -v` prints: 4.0.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Various Linux and OS X

**Comment by MylesBorins** [comment]
This gist includes the output of `npm install` and `npm ls`

https://gist.github.com/MylesBorins/3b23923c43e1b6bac7c47da1b5e8e235

**Comment by legodude17** [comment]
I think this is a problem with `npm ls` and not `npm install`. What are the contents of the node_modules?

**Comment by MylesBorins** [comment]
@legodude17 the test suite is also failing claiming that `cliui` is not installed

**Comment by legodude17** [comment]
@MylesBorins is `cliui` or `yargs` in your `node_modules` somewhere?

**Comment by MylesBorins** [comment]
@legodude17 they are not, which is why `npm ls` is failing

This was discovered as part of the official nodejs smoke testing suites

**Comment by iarna** [comment]
Ok, so this is due to the `npm-shrinkwrap.json` being out of date with the rest of the module. As of `npm@4` you get exactly what's in the in the shrinkwrap and nothing more. (This is very much THE breaking change in `npm@4`.)

The shrinkwrap has the unused `optionator` in it, it's missing `cliui` for `yargs@3.10.0` and it doesn't provide a `yargs@~3.5.4` for the embedded copy of uglify:

```
uglify-js@2.7.5 /Users/rebecca/code/npmtest/node-15420/UglifyJS2-2.7.5
├─┬ esfuzz@0.3.1
│ └─┬ uglify-js@2.4.24 (git://github.com/mishoo/UglifyJS2.git#2a06c7758e24a64740473c8031eafbb7fefa213f)
│   └── UNMET DEPENDENCY yargs@~3.5.4
└── yargs@3.10.0 
```

They also define a `shrinkwrap` lifecycle that's incompatible with `npm shrinkwrap` in `npm@3`, but removing that from the `package.json` and fixing the shrinkwrap clears it up.

I'll go PR the origin.

**Comment by iarna** [comment]
Uglify actually just removed their shrinkwrap, ¯\_(ツ)_/¯

I also PRed a correct shrinkwrap as https://github.com/mishoo/UglifyJS2/pull/1421

**Comment by MylesBorins** [comment]
Thanks @iarna.
