### ISSUE TITLE
prepublishOnly running after publish?

### ISSUE THREAD

**Issue by ejmurra** [npm/npm#15454]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have a prepublishOnly script that takes my source and transpiles, lints and runs tests before publishing. However I frequently find that I will run `npm publish` which will run the prepublish script, however when I pull the package down the `dist/` directory has not been changed. Currently, I've been working around this by manually running `npm run prepublishOnly` `npm publish`.

#### How can the CLI team reproduce the problem?
Write an prepublishOnly script that does some non-trivial compilation that takes a few seconds. Run npm publish and check the source to see if the script actually finished before the package was published to the registry. It's not super consistent either: sometimes it publishes right away, sometimes it runs the clean script I have set up (which deletes the dist directory entirely) and then publishes without dist; other times it seems to work as intended.

I think this issue on travis may be related to the issue I'm having and the user misattributed the error to travis: https://github.com/travis-ci/travis-ci/issues/6953
He also has a repro there but I have not tried it.
Otherwise, you can try my package as a repro: https://github.com/tbtimes/lede/tree/update

### supporting information:

 - `npm -v` prints: 4.0.3
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX

**Comment by KenanY** [comment]
@ejmurra Are you sure you don't wanna use `"prepare"` instead? `"prepublishOnly"` runs after your package has already been packed up for upload.

**Comment by ejmurra** [comment]
@KenanY Thanks for the reply. I don't want the script to run on install as well so I don't want it to be a prepare script. I want it to run before it publishes because it transpiles, lints, and runs the test suite. If any of those steps fail, I don't want the package to publish. 

I don't want my users to have to download my dev toolchain and run transpilers and linters to use my package when I am perfectly capable of running those tools before publishing. Eventually, I would like to bundle my code with rollup before publishing it so that I deliver the smallest and most useful package to users. 

I assumed prepublishOnly would run before package is packed for upload, and if it's intended behavior for it to run after packaging for distribution it seems a little misleading and it also seems that prepublishOnly is a missed opportunity to support the large community of developers who are transpiling their javascript before distributing it.

**Comment by clayne11** [comment]
The "new" behavior isn't any better than the old one. What most of us want is a hook that runs before creating the tarball for NPM. The new hooks haven't done anything to help with this use case.

**Comment by danez** [comment]
Running into the same. @iarna Can someone of you clarify what the intention is and when `prepublishOnly` is run. I wanted to use it to compile javascript before publish from src/ to lib/. But after the publish was finished the package does not contain lib/. Switching back to `prepublish` solves it.

**Comment by bfreis** [comment]
+1. Spent countless hours with this very same issue in the past few weeks. I ended up working around this bug by publishing my packages twice. I think I'll now start doing what @ejmurra mentioned above, `npm run prepublishOnly && npm publish`. Or possibly just give up on npm lifecycles, because what seems to be designed to be intuitive and logical doesn't really make sense...

I (and a *ton* of other people, apparently) also need a phase that runs *before* the tarball is generated, but that doesn't run on `npm install`. Prepublish is the absolutely logical name for that. PrepublishOnly would be an acceptable alternative, given the whole insanity created by `prepublish` in the first place and the desire to maintain backwards compatibility with the (absolute nonsense, but widely dependend on) behavior of `prepublish`. But then prepublishOnly not running before, err, building the artifact that's gonna be published... that's just more insanity...

**Comment by iarna** [comment]
IIRC our original thinking was this:

"I want to do build steps that are neccessary to use my module." — use `prepare`

"I want to do validation steps that stop me from publishing bad code." — use `prepublishOnly`

Now, it seems some folks want something like:

"I want to do build steps that are neccessary to use my module except NEVER when I'm developing my module"

And that final use case, we don't have anything for. It would be something like `prepack` (but we don't have `pack` lifecycles at this time.)

**Comment by iarna** [comment]
That being said, I'm not opposed to move it to prior to the `pack` step in publication. It's kind of borderline as to if that constitutes a breaking change, but `npm@5` is approaching quickly so if we did this, we'd probably just do it then to be conservative about our semver.

**Comment by bfreis** [comment]
@iarna - that's *precisely* it.

> "I want to do build steps that are necessary to use my module except NEVER when I'm developing my module".

Those are heavy steps, take too much time to run and I have other ways - much faster - of achieving the results of those steps in my development environment. But they need to be ran before other projects, not using my development environment, can use my module.

**Comment by clayne11** [comment]
Prepublish definitely makes a lot more sense to run before `pack` IMO as well.

You can put hooks into a `prepack` step to stop yourself from publishing bad code, but you can't (currently) put code into `prepublishOnly` that allows you to run a build step before publishing. If we have to have one or the other I'd *much* prefer to have a step that runs before pack where I can build *and* validate my code rather than just having one after `pack` where I can't actually build my code.

If you guys want to move `prepublishOnly` to before `pack`, that's fine with me, or you can add another hook called `prepack`. I'm fine with either as long as I'm able to hook into the publishing process to build my code before it gets packed but *not* when another developer installs my package from `npm`.

**Comment by MicahZoltu** [comment]
> "I want to do build steps that are neccessary to use my module except NEVER when I'm developing my module"

@iarna I'm not quite sure this is right.  It is more that the developer shouldn't be relied on to remember to run these steps manually before publishing.  I, for example, write TypeScript and use Wallaby which does in-memory compilation of my TypeScript to JavaScript.  However, when publishing modules to NPM they need to be JavaScript (not TypeScript) so I need a build step that generates the files that will actually go to NPM that is guaranteed to be run when I try to publish.  Many times I have published an update to NPM only to realize after the fact that I forgot to compile the TypeScript so the module is now completely broken on NPM.

Another situation I often find myself in (because I'm a bad developer) is making a minor typo change or something and then clicking publish.  The change in these cases is usually so minor that I don't think to re-run the tests (see: I'm a bad developer).  However, because I'm not re-running the tests it means I'm also not re-building my JavaScript files so the publish ends up publishing just the TypeScript.

I really _need_ a way to protect myself from myself such that I can add a step that executes all the things necessary to validate my package is healthy anytime I _attempt_ to publish something.

I just tried setting up scripts like:
```
  "scripts": {
    "build": "tsc",
    "pretest": "npm run build",
    "test": "mocha output/tests",
    "prepublishOnly": "npm run test"
  },
```

But that doesn't appear to work at all.  `npm publish` doesn't compile or run the tests.  As far as I can tell, `prepublishOnly` doesn't actually do _anything_ (maybe I'm using it wrong though).

**Comment by clayne11** [comment]
`prepublishOnly` currently runs AFTER `pack`, rather than before (as it definitely should). The team has mentioned that they're going to move `prepublishOnly` to before `pack` either in `npm@5` or even potentially before.

**Comment by monolithed** [comment]
Are there any plans to fix that?

**Comment by clayne11** [comment]
Why was this closed? Is it resolved? This is a pretty big issue.

**Comment by caseyWebb** [comment]
This should be reopened. IMO, it's a perfectly logical use case.

My (TypeScript) development workflow is...

- Utilize VS Code's TypeScript support (so no need to run `tsc`/`tsc --watch` during development)
- Run jest in watch mode during development
- Build JS output before publishing <--- this is what a lifecycle hook is needed for
- Publish

I *have* published outdated JS before, a few times, and had to follow it up with another patch version bump immediately because I forgot to compile the TS. I can't imagine I'm the only one. There is a particular risk of this happening with small modules that rely almost (if not) entirely on unit testing where there is no need to use the compiled output during development.
