### ISSUE TITLE
No devDependencies installed using node 7

### ISSUE THREAD

**Issue by MickL** [npm/npm#15912]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Using latest stable node (7.7.0) installing a module will not install any devDependencies. E.g. TypeScript contains ONLY devDependencies and will install none of them.

I also tried using `n` to switch to 6.10.0 -> devDependencies will be installed

Going into the module (e.g. node_modules/typescript/) and running `npm i` will install the devDependencies.

#### How can the CLI team reproduce the problem?
Try `npm install typescript -g` -> None of the devDependencies will be installed. There will be no node_modules folder inside of typescript/

One more example:

Try `npm install express -g` -> None of the devDependencies will be installed (only dependencies).

### supporting information:

 - `npm -v` prints: 4.4.0
 - `node -v` prints: v7.7.0
 - `npm config get registry` prints: https://registry.npmjs.org/
- `npm config get production` prints: false
 - Windows, OS X/macOS, or Linux?: Ubuntu Server 16.04.2 LTS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What is the problem? It is supposed to only install `devDependencies` when you are running `npm install` in the project folder.

**Comment by KenanY** [comment]
Yeah, this sounds like the correct behavior to me.

**Comment by jpap** [comment]
I hit this same issue after installing `pg-promise`, that has a `devDependency` on `@types/node` to complete their own TypeScript definitions also included in the module.

A TypeScript compile of my project failed because the node types `pg-promise` relied on as a `devDependency` were not pulled in by a `npm install`.  I'm on node 7.7.1.

It took me much time and frustration to learn the issue was that npm failed to pull in the dependencies as opposed to incorrect type definitions.  How then could it be correct behavior by `npm`?  (Here, in a non-production environment where `npm config get production` returns `false`.)

Given that @MickL says the `devDependencies` were pulled in correctly on node 6.10.0, @KenanY && @legodude17, wouldn't you say this is a regression? :)

**Comment by KenanY** [comment]
As far as I know, this has been the intended behavior for the last few years. If there is a version (or versions) of `npm` wherein this was not the case, I would appreciate someone investigating into what's the last version of `npm` to have the behavior that @MickL and @jpap are expecting.
