### ISSUE TITLE
Q: reason for using "request" dependency?

### ISSUE THREAD

**Issue by ahmadnassri** [npm/npm#16041]
`request` is rather heavy, a per your own notes on recent improvements to [`startup time`][startup-time].

I looked through and it seems all of the usage is rather trivial: 

- [`/lib/doctor/get-latest-nodejs-version.js#L9`][get-latest-nodejs-version]
- [`/lib/search/esearch.js#L35`][esearch]
- [`/lib/owner.js#L254`][owner]

`npm` doesn't event seem to be using it for JSON parsing, streaming or even handling redirects _(the most common & core functionality useful here that I can think of)_.

am I missing some other parts where a mode deep usage of `request` is needed? otherwise, I can see a quick performance gain / over all improvement in using native `http.request`. would be more than happy to prototype, test and create PR.

#### I'm opening this issue because:

  - [x] Other (_see below for feature requests_):

#### What's going wrong?

- nothing broken
- asking a question to get clarity on dependencies choice. 
- looking to help contribute.

[startup-time]: https://github.com/npm/npm/blob/bc3f24bf95abe45a185848561c7c1edc90f60c5e/CHANGELOG.md#faster-startup-sometimes
[get-latest-nodejs-version]: https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/lib/doctor/get-latest-nodejs-version.js#L9
[esearch]: https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/lib/search/esearch.js#L35
[owner]: https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/lib/owner.js#L254

**Comment by legodude17** [comment]
I am pretty sure that `npm-registry-client` uses `request` much more then `npm`, and `npm` needs `npm-registy-client`.

**Comment by zkat** [comment]
@ahmadnassri like @legodude17 said, it's used by `npm-registry-client`, which means we also use all its streaming capabilities (for search), as well as the parsing. All http networking ultimately goes through `request`, and the main reason for not rolling our own is because `request` supports proxies, and because it would take time for us to write our own npm-specific client.

There's a whole new package-download client being written right now, which includes its own wrapper around `request` and `npm-registry-client`. pacote is intended to replace the entire download infrastructure in npm, and we'll be moving to it soonish. I do have plans to get rid of the request dependency from there once the core features are done, and there's even an issue for it: https://github.com/zkat/pacote/issues/3. You can see an outline of the tests I still have pending for it here: https://github.com/zkat/pacote/blob/latest/test/registry.get.js (note that this is not a complete spec but covers the major points that I want the client to be able to do in order to work as a downloader). I'd say anything that passes **all** of those tests would be at least considering.

That said, because of how core something like this is to our operation, unless the replacement is a widely-used package or somehow proven to be really solid for our needs, it would be hard for us to accept a third-party package for this replacement. This is the sort of thing that has way more gotchas and corner cases than one might expect at first. It's also the sort of thing that the CLI team would want easy access to regularly tweaking in ways meant to benefit npm-style stuff, as needed.

If you care a lot about doing this, and you think you can do it, you're free to write a package according to specs that fit our requirements, and we would evaluate it, but I think it's unfair because I wouldn't be able to guarantee that we'd use it. :( We can move the discussion over to the pacote repo if you wanna talk about it more.

I think this answers your question, so I'm gonna close this issue for now. Thanks a lot! <3

**Comment by ahmadnassri** [comment]
@zkat 🙇 amazing! thank you for the thorough response!

> This is the sort of thing that has way more gotchas and corner cases than one might expect at first.
💯 

> you're free to write a package.

not at all, just looking for paths of optimization, `request` itself has a great story to tell here: https://github.com/request/request/issues/1982

in that context, `pacote` would possibly benefit from a handpicked selection of `request` modules to create it's own streamlined http client!

I'll look through `pacote` and circle back on `request@next` progress, if there is alignment there, I'll initiate a conversation or a PR where applicaple!
