### ISSUE TITLE
Feature request/proposal: Allow arrays in the "scripts" section

### ISSUE THREAD

**Issue by antonshulgin** [npm/npm#16121]
# The Problem

Slightly exaggerated bogus example for demonstration purposes:

```json
{
	"scripts": {
		"clean": "rm -rf ./dist/",
		"create-dist": "mkdir ./dist/",
		"uglify": "uglifyjs --bogus-parameter --another-one",
		"concat": "concat --some-more-bogus-here",
		"build": "npm run clean && npm create-dist && npm run concat && npm run uglify && npm run and-so-on",
		"this-stuff --^": "becomes harder and harder to maintain as the project grows"
	}
}
```

# The Solution

0. Parse through the `scripts` section in `package.json`;
1. If the element is a string, proceed as normal;
2. If the element is an array, automatically prefix each element in said array with `npm run` and run them in order.

```json
{
	"scripts": {
		"clean": "rm -rf ./dist/",
		"create-dist": "mkdir ./dist/",
		"uglify": "uglifyjs --bogus-parameter --another-one",
		"concat": "concat --some-more-bogus-here",
		"build": [
			"clean",
			"create-dist",
			"concat",
			"uglify"
		]
	}
}
```

**Comment by AshlessCinder** [comment]
I think it might be more clear if an object was used instead of an array, with keys as script names and values as the commands. The values would simply be concatenated together with a && separator.

Your example becomes this
``` json
{
	"scripts": {
		"build": {
			"clean": "rm -rf ./dist/",
			"create-dist": "mkdir ./dist/",
			"uglify": "uglifyjs --bogus-parameter --another-one",
			"concat": "concat --some-more-bogus-here",
		}
	}
}
```

Any scripts that are used in multiple other "script lists" could simply be called with npm run like this
``` json
{
	"scripts": {
		"concat": "concat --some-more-bogus-here",
		"dev": {
			"concat": "npm run concat"
		},
		"build": {
			"clean": "rm -rf ./dist/",
			"create-dist": "mkdir ./dist/",
			"uglify": "uglifyjs --bogus-parameter --another-one",
			"concat": "npm run concat"
		}
	}
}
```

If each sub script has a key you could also access them like this `npm run build.clean`

Either way I really like this idea. I would allow much better composition of scripts.
