### ISSUE TITLE
Delete private NPM packages requires an approval of NPM. 

### ISSUE THREAD

**Issue by StarpTech** [npm/npm#16142]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Why I need a approval of NPM to delete my PRIVATE packages? Any private package has to be deleted from NPM itself after I verified my account via Email. There is no option in the dashboard.

**Comment by iarna** [comment]
There's no policy reason for this, I don't think. I believe this is simply because the rules for unpublishing were applied across the board when it was first implemented. It was kind of an emergency patch at the moment that we did it.

If you email this as a feature request to `support@npmjs.com` then they can include it when the bundle up feedback.

**Comment by StarpTech** [comment]
@iarna Hi just want to mention that this is a reason why I don't use paid plans. This "patch" exists since years. Could you delegate it to NPM or is Github the wrong place?

**Comment by iarna** [comment]
@StarpTech Well beyond dropping an email to support, you could add an issue at the [registry](https://github.com/npm/registry) team's issue tracker.

(I work for npm, but this is a product priority decision that's outside of my a responsibilities, which is why I can't be more helpful.)
