### ISSUE TITLE
npm --save[-dev] does not save the version range specified

### ISSUE THREAD

**Issue by jdufresne** [npm/npm#16205]
#### What's going wrong?

My project has a `package.json` file to specify acceptable version ranges for dependencies and a `npm-shrinkwrap.json` file to specify exact versions. Normally, when I install a new dependency, I want to install the latest version, but store the version range `*` in `package.json`. After reading the documentation, I believe the correct invocation is:

```bash
$ npm install 'react@*' --save-dev
```

Even though I specified my preferred version range, this does not add the version range `*` to `package.json`, instead it adds the latest version with the prefix `^`. At the time of writing, this is:

```json
"react": "^15.4.2",
```

As I specified a specific version range, I expect:

```json
"react": "*",
```

#### How can the CLI team reproduce the problem?

Start with a working project that has a `package.json` and correct `npm-shrinkwrap.json`.

```
$ npm install 'react@*' --save-dev
$ jq .devDependencies.react package.json 
```

Expected result:

```
"*"
```

Actual result:

```
"^15.4.2"
```

### supporting information:

```
$ npm -v
4.0.3
$ node -v
v6.10.0
$ npm config get registry
https://registry.npmjs.org/
```

**Comment by andomain** [comment]
My understanding is that specifying `@*` will install the most up to date version, currently `15.4.2`. You can use the wildcard to limit to a specific major/minor version, i.e. `@15.3.*` will install the most up to date patch of `15.3`.
Your package.json must specify a version number so you can guarantee your code will work when somebody runs `npm install`. Imagine the next major release of the react module introduces significant changes that break your code. If the committed version number behaved as you expect then the new version, say `16.0.0` would be installed and your application would not work. Instead, because package.json specifies a known, working version number then `15.4.2` would be installed and your code will continue to work. This allows users to continue using your code while you locally update versions, fix your code and then push the changes when ready.

**Comment by jdufresne** [comment]
I understand your point, however, for my project and use case, I disagree. 

>Your package.json must specify a version number so you can guarantee your code will work when somebody runs npm install. Imagine the next major release of the react module introduces significant changes that break your code. If the committed version number behaved as you expect then the new version, say 16.0.0 would be installed and your application would not work. Instead, because package.json specifies a known, working version number then 15.4.2 would be installed and your code will continue to work.

The `npm-shrinkwrap.json` file solves this. `npm-shrinkwrap.json` guarantees that all uses of `npm install` create an identical environment. For my project, I want to use the `*` version range so when I rebuild `npm-shrinkwrap.json` it is always built from packages' latest version available. I understand that this will sometimes pull in a new version of a library with backwards incompatible changes, but that is very easy to notice and adjust my code for. Without using `*`, the new shrinkwrap will pull the old version and I won't know to update my code to follow an evolving package. Using `*` helps automate this process for me.

> This allows users to continue using your code while you locally update versions, fix your code and then push the changes when ready.

I don't have any users. This is a private project, not a public library.
