### ISSUE TITLE
npm installs the wrong version for the angular-ui-grid  library

### ISSUE THREAD

**Issue by ashwin027** [npm/npm#16203]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
The latest version of the angular ui grid is 4.0.3 but when I do an npm install, it install 3.2.11. The reason might be that the install is picking up the latest release from the ui-grid team which is 3.2.11 which was released after the 4.0.3 release. Shouldnt the install show 4.0.3 as the latest version?

#### How can the CLI team reproduce the problem?
Run npm install angular-ui-grid. This will install 3.2.11. Run npm install angular-ui-grid@4.0.3 --save which is the true latest version.

**Comment by KenanY** [comment]
@ashwin027 `@3.2.11` was published about 4 days after `@4.0.3`, hence by definition it is considered by default to be the "latest" release. If the authors would like to change the `latest` tag to point to a different version, then they can use the [`dist-tag`](https://docs.npmjs.com/cli/dist-tag) command.

Closing since this is intentional `npm` behavior.
