### ISSUE TITLE
npm ERR! Darwin 16.4.0

### ISSUE THREAD

**Issue by PowrSlave** [npm/npm#16242]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm just trying to run the default test that is included in package.json after I cycle through the prompts with 'npm init'

#### How can the CLI team reproduce the problem?

I'm merely running 'npm run test' and getting all these errors. Don't understand why and haven't found anything on stackoverflow that has helped. 

Here is the gist: https://gist.github.com/PowrSlave/64a571a63f132c5aa7a42af297005420

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@PowrSlave The default `"test"` script throws an error code, hence the error that `npm` is catching and displaying to you. Here's the default script:

```
echo "Error: no test specified" && exit 1
```

That last part, `exit 1`, causes the script to exit with a non-zero code which `npm` treats as being an error. Since this is intentional behavior, I'm gonna close this one out, but feel free to let me know of any further questions you may have.
