### ISSUE TITLE
npm incorrectly url encodes forward slashes which can prevent download of package dependencies

### ISSUE THREAD

**Issue by peterlynch** [npm/npm#16380]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Specify a scoped package dependency using this style:

"@angular/common": "^2.1.0",

When you do an npm install, npm will encode the slash in the scoped dependency and the resulting url requested will be of this form ( as seen with debug option -ddd ):

26 silly mapToRegistry uri http://localhost:8081/repository/npm-hosted/@angular%2fcommon

Unfortunately encoding forward slash like this commonly creates problems if the endpoint is a reverse proxy such as Apache httpd as by default [it does not allow encoded slashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes). One needs to configure the reverse proxy to allow these encoded slashes explicitly or else Apache httpd will respond for example with a status message of "400 Non URL-safe name" indicating it is denying such URLs with forward slash encoded with %2f.

Additional options may be needed. For example the [ProxyPass](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass) directive may also need the `nocanon` parameter - from httpd docs:

> The optional `nocanon` keyword suppresses this and passes the URL path "raw" to the backend. Note that this keyword may affect the security of your backend, as it removes the normal limited protection against URL-based attacks provided by the proxy.

```
ProxyPass / http://localhost:8081/ nocanon
```

### Workaround

A workaround exists, but is not very good as it is potentially a security concern to allow encoded non-canonicalized urls like npm sends ( hence the default to block these by servers such as httpd )

Apache httpd can be configured with:

```
AllowEncodedSlashes NoDecode
```

and

```
ProxyPass / http://localhost:8081/ nocanon
```

Reference: 
http://stackoverflow.com/questions/4390436/need-to-allow-encoded-slashes-on-apache/9933890#9933890
https://issues.sonatype.org/browse/NEXUS-10570

Also make sure you are using [httpd newer than 2.2.8](https://bz.apache.org/bugzilla/show_bug.cgi?id=35256).

#### How can the CLI team reproduce the problem?

As described in what's going wrong section above.

#### Expected

npm client should not encode forward slashes in scoped dependency urls ( or in any outbound urls it uses). This will allow default secure settings of httpd to reverse proxy its requests just fine without adjustment.

**Comment by zkat** [comment]
this is something we might be able to pull off for the new registry api, but as far as any current registries and clients go, this is going to pretty much be what it is now -- the main registry, npmE, and literally every other open source and proprietary registry that supports scoped modules, as well as every single version of npm released thus far, all rely on this slash being encoded like that. Nexus included.

So, that's the CLI-side answer: I personally don't think we can do this now or in the foreseeable future without widespread incompatibility, until the CLI starts hitting a different API endpoint for requests (which might be a thing! not too far into the future!). That said, would you consider opening this issue over at the https://github.com/npm/registry repo? That'll reach the registry team. Their answer might be different from mine -- the CLI tends towards being conservative with things like these.

**Comment by peterlynch** [comment]
@zkat I'd like to clarify Nexus Repository Manager for one will interpret both encoded and non-encoded forms of forward slash.

```
127.0.0.1 - admin [26/Apr/2017:12:08:18 -0300] "GET /repository/npm-proxy/@angular%2fcommon HTTP/1.1" 200 84100 892 "curl/7.51.0"
127.0.0.1 - admin [26/Apr/2017:12:08:30 -0300] "GET /repository/npm-proxy/@angular/common HTTP/1.1" 200 84100 11 "curl/7.51.0"
```

The problem comes because companies using npm cli VERY often put a reverse proxy server in between the npm client and the final registry destination - so this feels like the CLI is the correct place to fix this.

I cannot offer an opinion on how changing the cli will impact its source code and dependencies as I am not that familiar enough with the npm cli source base.

**Comment by zkat** [comment]
@peterlynch considering how this has been this way for several years, and the potential backwards incompatibilities, I think the best route to take is to make no changes to the existing API.

BUUUUT.

We should definitely take this into account for the v2 api that's in the works. It'll be documented and specced publicly, and that's a good opportunity for us to do better the second time around. I don't know what the actual timeline would be.

Does that seem reasonable? I feel like it's important to be conservative with something like this, rather than roll the dice and hope we don't break other registries in a different way. I'll pass this on to the registry team myself to double-check my assumptions. You'll have to keep using the workaround for the time being :\

**Comment by peterlynch** [comment]
@zkat I wanted to check - are you waiting on me before action on this issue? Has work already started on this issue elsewhere? Any updates?

**Comment by iarna** [comment]
The unencoded form is explicitly NOT supported by the npm registry and presumably third party ones based on it. So as Kat says, we won't be changing the current APIs. Future APIs are still a long way out, but we'll include a discussion of this topic when we put them out.

As this issue is not currently actionable, I'm going to close it, but do watch our blog/social media/newsletter for our new APIs in the future.
