### ISSUE TITLE
NPM Errors 

### ISSUE THREAD

**Issue by stevomccormack** [npm/npm#16403]
#### I'm opening this issue because:
   - npm is doing something I don't understand.

#### NPM FULL DEBUG OUTPUT:
http://sandspromotions.azurewebsites.net/npm-debug.txt

#### VISUAL STUDIO 2017 OUTPUT:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\npm.CMD" install
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-9508ac6e73bc4e2dd3065e6cd9e6f094 C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-a99f283211ec0090806892e40cf4907a\62323fc55dd080a58ed030c5e9df176bdf551eae: Cloning into 'C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-a99f283211ec0090806892e40cf4907a\62323fc55dd080a58ed030c5e9df176bdf551eae'...
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-9508ac6e73bc4e2dd3065e6cd9e6f094 C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-a99f283211ec0090806892e40cf4907a\62323fc55dd080a58ed030c5e9df176bdf551eae: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-9508ac6e73bc4e2dd3065e6cd9e6f094 C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-a99f283211ec0090806892e40cf4907a\62323fc55dd080a58ed030c5e9df176bdf551eae: fatal: unable to fork
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-9508ac6e73bc4e2dd3065e6cd9e6f094 C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-a99f283211ec0090806892e40cf4907a\62323fc55dd080a58ed030c5e9df176bdf551eae: 
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-gulpjs-gulp-git-513be8c6898f096cd709c414b0ea897d C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-affeb7e69461fbc6fe174b05926519fa\62323fc55dd080a58ed030c5e9df176bdf551eae: Cloning into 'C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-affeb7e69461fbc6fe174b05926519fa\62323fc55dd080a58ed030c5e9df176bdf551eae'...
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-gulpjs-gulp-git-513be8c6898f096cd709c414b0ea897d C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-affeb7e69461fbc6fe174b05926519fa\62323fc55dd080a58ed030c5e9df176bdf551eae: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-gulpjs-gulp-git-513be8c6898f096cd709c414b0ea897d C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-affeb7e69461fbc6fe174b05926519fa\62323fc55dd080a58ed030c5e9df176bdf551eae: fatal: unable to fork
npm ERR! git clone C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-gulpjs-gulp-git-513be8c6898f096cd709c414b0ea897d C:\Users\Steve\AppData\Local\Temp\npm-10636-e7919930\git-cache-affeb7e69461fbc6fe174b05926519fa\62323fc55dd080a58ed030c5e9df176bdf551eae: 
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  gulpjs/gulp resetting remote C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0: Cloning into bare repository 'C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0'...
npm ERR! git clone --template=C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0: error: cannot spawn ssh: No such file or directory
npm ERR! git clone --template=C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0: fatal: unable to fork
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:gulpjs/gulp.git C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0
npm ERR! Cloning into bare repository 'C:\Users\Steve\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-5373df33c46457db34876097eea6acc0'...
npm ERR! error: cannot spawn ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     E:\MWeb Solutions\Development\Websites\Workspaces\SandsPromotions\Apps\Websites\Sands.Website.Dhl\npm-debug.log

**Comment by legodude17** [comment]
Do you have `ssh` installed?

**Comment by vamsi4321** [comment]
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:         tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  silexlabs/silex-templates#2107872 resetting remote C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c: Cloning into bare repository 'C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c'...
npm ERR! git clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c:
npm ERR! git clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c: and the repository exists.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:silexlabs/silex-templates.git C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c
npm ERR! Cloning into bare repository 'C:\Users\innovista\AppData\Roaming\npm-cache\_git-remotes\git-github-com-silexlabs-silex-templates-git-2107872-a989834c'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\innovista\Desktop\Silex\npm-debug.log

**Comment by stevomccormack** [comment]
Do I have ssh installed? 
I have FTP that uses ssh.

Is there a library or download i need to install?
