### ISSUE TITLE
Please help me to solve this problem!

### ISSUE THREAD

**Issue by zihebingwu** [npm/npm#16405]
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose readDependencies loading dependencies from e:\Myproject\package.json
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT: no such file or directory, open 'e:\Myproject\package.json'
6 verbose stack     at Error (native)
7 verbose cwd e:\Myproject
8 error Windows_NT 6.1.7601
9 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
10 error node v4.4.3
11 error npm  v2.15.1
12 error path e:\Myproject\package.json
13 error code ENOPACKAGEJSON
14 error errno -4058
15 error syscall open
16 error package.json ENOENT: no such file or directory, open 'e:\Myproject\package.json'
16 error package.json This is most likely not a problem with npm itself.
16 error package.json npm can't find a package.json file in your current directory.

-->

**Comment by KenanY** [comment]
Looks like you're running `npm install` from within a directory which does not contain a `package.json`. Without such a file. and without passing any arguments to `npm install` itself, `npm` has _no idea_ what you want it to install. Hence, the error you are seeing. Since this is intentional behavior, I'm gonna close this.
