### ISSUE TITLE
Why is `node_modules` not a part of .gitignore?

### ISSUE THREAD

**Issue by abhisheksoni27** [npm/npm#16480]
On a **newly-cloned forked copy of the npm source code repository**, after running `npm install`, I get a ton of untracked folders/files because of the dependency packages, and git goes berserk.

After adding an entry in .gitignore named `node_modules` (It has `/node_modules` already but that doesn't help :thinking: )

Is the .gitignore in good health?

Or maybe I am doing something wrong?

**Comment by rehierl** [comment]
Your post isn't quite clear. If the following doesn't help, try adding more details of what you are trying to do and which problems exactly you encounter.

--

The direct answer to your question of why 'node_modules' is not part of .gitignore would be: Because Node projects are only one type of project for which you can use Git. A Java project for example won't need a 'node_modules' entry.

I hope it will help, if you clearly distinguish what the .npmignore and .gitignore files are used for:

.npmignore is used when you publish to npmjs.com ([see here](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)) and tells what not to add to the package. The .gitignore file will only be used by npm (for the very same purpose!), if there is no .npmignore file in your project folder. Also, 'node_modules' will be ignored by npm automatically, so there should be no reason to add that entry. But it should not cause any troubles if you do.

The actual purpose of .gitignore is to tell Git which parts of your project not to track ([see here](https://help.github.com/articles/ignoring-files/)). With that in mind, if you develop a Node project and use Git for version control, then it does make sense to add 'node_modules' to .gitignore.

**Comment by abhisheksoni27** [comment]
@rehierl I am sorry that was _poorly_ phrased. See the edited question. 

Thanks for answering the unintended question, anyway. It might be useful for someone who stumbles upon this issue later with that doubt.

**Comment by KenanY** [comment]
I believe that the `node_modules/` directory is intentionally checked-in in order to track the exact bundled dependencies that are being shipped with each release. A member of the team can chime in eventually and elaborate/clarify further, I'm sure :)

**Comment by abhisheksoni27** [comment]
But why is there a need of maintaining an `exact bundled dependencies` folder for every release?

Also, why are we not using `package.json` to track/maintain that? You are right. A team member will be able to clarify the doubts better. :hear_no_evil:
