### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by Hayssam79** [npm/npm#16563]
Since some of the NPM packages are only available on our internal repo, i need to login before installation is possible:
```
      npm login --registry=https://maven.zalando.net/content/repositories/npmjs/
```

but when i run command npm install
I get the below error.

```
     npm ERR! registry error parsing json
     npm ERR! registry error parsing json
     npm ERR! registry error parsing json
     npm ERR! Windows_NT 6.1.7601
     npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" 
             "C:\\Users\\hhassan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v7.9.0
    npm ERR! npm  v3.10.8
    
    npm ERR! Unexpected token < in JSON at position 1
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
```
   Any Suggesstions!

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by Hayssam79** [comment]
@legodude17 
thanks but I've resolved it myself

**Comment by bobKasbi** [comment]
@@legodude17: In those cases, it would be helpful for other users if you post what was wrong and what was the fix! Otherwise neither you question nor the answer would make sense.

**Comment by Butterfly** [comment]
@bobKasbi There have been a few of these in last maybe 2 days. It's possibly not directly about end users, might be things going on with repositories, servers, etc, first. Then again, there's always the chance that it could be something that we're doing that triggers it.

`npm` appears to be encountering error message webpages instead of expected `npm` friendly files and directories. That's at least one reason why it's kicking back those "Unexpected token < in JSON at position 1" and similar errors.

In at least some instances, that *appears to be* `npm` trying to process unfamiliar files, hence the "<" reference which is how html coded webpages begin. I've only learned that today while nosing around related to #18626. Depending on how one is working with `npm`, that error could always still be about a similar thing but might need tracked down on one's personal computer and/or personal repositories where the work is all being done in private. :smile:
