### ISSUE TITLE
npm5 : package-lock.json should contain node & npm version information to aid CI services

### ISSUE THREAD

**Issue by christopherstott** [npm/npm#16580]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] Other (_see below for feature requests_):

#### What's going wrong?

The package-lock.json doesn't currently contain the node or npm version that was used to generate the lock file. Having that information is very useful for CI services to be able to infer the environment that should be used. 

### supporting information:

For reference here is an package-lock.json

```json
{
  "name": "npm5test",
  "version": "1.0.0",
  "dependencies": {
    "five": {
      "version": "0.8.0",
      "resolved": "https://registry.npmjs.org/five/-/five-0.8.0.tgz",
      "integrity": "sha1-573pfSEmXHDBReGwn4eeQdktnHU="
    }
  }
}
```

**Comment by legodude17** [comment]
There is one:
https://github.com/npm/npm/pull/16441/files#diff-9195b56603665ac66a71ed45d6e026bdR33
Though the nodejs version might be a good idea.

**Comment by christopherstott** [comment]
@legodude17 It looks like that is the version of the package, not the version of npm itself? Or am I misreading that?

**Comment by legodude17** [comment]
No, `created-with` is the `npm` version.

**Comment by zkat** [comment]
@christopherstott we're adding this to the spec. It should land in the beta ~soon

**Comment by zkat** [comment]
Oops. The problem with this became very obvious, very quickly: This would cause an _immense_ number of git conflict issues. Which might not seem like a big deal to seasoned git users or for people in teams that minimize drift between tool versions, but it's going to be a *huge* problem for open source developers, who not only work on different platforms, but who often want to be able to merge things without dealing with unnecessary package conflicts. It also has the potential to unintentionally leak platform information from those open source users.

So, I wrote the code. I was ready to push it, and then I was like "oh crap". So I've taken it out. And I'm closing this feature request with the best explanation I can give for why.

THAT SAID

You are not entirely out in the cold because of this. You can trivially add a `postshrinkwrap` script to your `package.json` that will reliably run every single time this file is written. You can even have it as a dependency if you want, and invoke it with a single word.

An example postshrinkwrap for this would be something like:
```json
{
  "devDependencies": {
    "//": "this is a nice little CLI util for reading and munging json",
    "json": "^9.0.6"
  },
  "scripts": {
    "//": "this does an in-place edit to add some platform information!",
    "postshrinkwrap": "json -I -f package-lock.json -e 'this.createdWith = { node: process.version, arch: process.arch, platform: process.platform }'"
  }
}
```

That will get you exactly what you want, and you get to put any metadata you want there :) It just means you'll have to use your own conflict handling.

I hope it's not too disappointing that I said we'd put the feature in and then immediately retracted it, but I genuinely think this is the right thing to do.

**Comment by christopherstott** [comment]
@zkat Apologies for the delay. I'm just getting caught up on this.

I don't believe it would cause a great number of git conflicts if done right - only modified when something else in the lock file changes. This is the way yarn.lock & Podfile.lock (from cocoapods) both work.

One option would to be make this the default, but allow for it to be disabled.

The `postshrinkwrap` solution wouldn't work for the problem I'm trying to solve for - which is for CI systems to automatically figure out which version of npm to use, rather than adding that data for a single npm package.

Thanks!
