### ISSUE TITLE
npm exec <program>

### ISSUE THREAD

**Issue by techtonik** [npm/npm#16592]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

and because #12126 was closed as a duplicate of #6053, of which it is not. #6053 is about passing parameters to `scripts` - stuff defined in `package.json` and this ticket is about running installed tools without touching this file.

#### What's going wrong?

Can't use tools installed by `npm` without messing with `package.json`.

```
>npm install netlify-cli
>npm run netlify
npm ERR! Windows_NT 6.0.6002
npm ERR! argv "C:\\Node\\node.exe" "C:\\Node\\node_modules\\npm\\bin\\npm-cli.js" "run" "netlify"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! missing script: netlify
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\grtp.co\npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Node\\node.exe',
1 verbose cli   'C:\\Node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'netlify' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 verbose stack Error: missing script: netlify
4 verbose stack     at run (C:\Node\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Node\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Node\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Node\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Node\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Node\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Node\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
4 verbose stack     at C:\Node\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd E:\grtp.co
6 error Windows_NT 6.0.6002
7 error argv "C:\\Node\\node.exe" "C:\\Node\\node_modules\\npm\\bin\\npm-cli.js" "run" "netlify"
8 error node v5.12.0
9 error npm  v3.8.6
10 error missing script: netlify
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

#### Is the absence of this feature blocking you or your team? If so, how?
Yes. I really don't like installing global tools that are specific to local project only.

#### Is this feature similar to an existing feature in another tool?
python -m <module>

#### Is this a feature you're prepared to implement, with support from the npm CLI team?
I can help, yes, but JavaScript is not my domain.

**Comment by legodude17** [comment]
Related: #15915. Also, #6053 is about `npm-exec` (A seperate binary). I think that is better, because it would be faster.

**Comment by zkat** [comment]
I think you may have misread #6053: the feature you are describing is exactly what that issue is intended to take care of. The thing about `npm-exec` is that it's meant to provide a project-appropriate environment as well. If all you want is to do `npmx <bin>`, that's trivially achievable with a plain old shell alias such as `alias npmx=PATH="$(npm bin)":"$PATH"`. You can drop that right in your `~/.{ba,z}shrc` and then run `npmx grunt` inside an npm project, and it'll Just Work™.

We keep #6053 around because it does actual work that users would have a lot of trouble doing for themselves: npm loads a bunch of environment variables and removes others while running scripts, and `npm-exec` is meant to provide an interactive environment where users can run things they'd usually put in scripts, either as one-off commands, or as part of developing the scripts they'll end up using.

So, I'll be closing this as a duplicate. I think the shell alias should do the trick nicely for your limited use case. We'll get around to npm-exec at some point, hopefully.

**Comment by techtonik** [comment]
@zkat when people read #6053 description - it is a not a proposal to **skip defining every command you want to run upfront in package.json**. Maybe a solution somewhere deep in comments suggests it, but that's not the issue that was being raised. I am okay if people in #6053 do the work that will also close this specific issue, but until this work is not merged, I can not mark this specific issue as closed. You may still decide that you need to limit the scope of #6053 to those script sections.

**Comment by zkat** [comment]
Oh I get what you mean now. Sorry, the thing you're asking for is weird enough that it conflicted with #6053 when I read it. I do think the effect is ultimately the same, since the thing you're asking for here is to have an easy way to invoke binaries for cli tools you've installed. "skip defining every command you want to run upfront in package.json" makes relatively little sense to me taking into account an understanding of what `npm run-scripts` (aka `npm run`) does.

The thing you seem to be asking for here is "I just installed <cli tool> and I want to be able to run the _local_ version instead of having to install it globally". Is that right? Set aside your specific proposed solution here :)

**Comment by techtonik** [comment]
> The thing you seem to be asking for here is "I just installed and I want to be able to run the local version instead of having to install it globally". Is that right?

I am able to do this with long crazy paths I need to dig, so just being able to run local version is not the thing I am asking. I need **an easy and intuitive way** to do this. It took me two years to finally find how it works. I am not a JavaScript developer. I just need to deploy it sometimes and use tools provided by `npm` repositories.

**Comment by legodude17** [comment]
Thing that might help:
https://github.com/legodude17/npm-exec

If you run a script that it doesn't see, then it will look in `./node_modules/.bin` for it. Is that what you wanted?

**Comment by techtonik** [comment]
Yes. If `npm run` or `npm exec` can do this, that will make the issue settled.

**Comment by zkat** [comment]
@techtonik `alias npmx=PATH="$(npm bin)":"$PATH"` will do this, and that's what I recommend you use. That, or legodude's script.

**Comment by techtonik** [comment]
@legodude17 I am on Windows.

**Comment by legodude17** [comment]
@techtonik My script should work on windows

**Comment by techtonik** [comment]
Thanks for the workarounds, but I'd like to see this implemented without additional burden of discovery. If it takes 7 days to discover a solution, it is a poor user experience. Also, I work from pristine containers, and doing those modifications every time is not quite what I'd like to do when I need to run occassional linter or another `npm` packaged tools on the project.

**Comment by legodude17** [comment]
I working to get my script included in `npm`, but the CLI team has a lot of work to get `npm5` out.
