### ISSUE TITLE
getaddrinfo EAI_AGAIN registry.npmjs.org error while npm install 

### ISSUE THREAD

**Issue by RakeshInfy** [npm/npm#16661]
npm install not working when trying to install typescript or angular-cli.
PFB some error logs from npm-debug file

163 verbose request no auth needed
164 info attempt registry request try #1 at 4:52:55 PM
165 http request GET https://registry.npmjs.org/zone.js
166 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
167 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
168 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
169 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443

**Comment by thataustin** [comment]
getting the same error just now when I run `npm install` from a Docker container.  Funny thing is that it's not happening on my local machine (mac) when I run it for the same package.json.

**Comment by legodude17** [comment]
Do you have a stable internet connection? Do you have a proxy or VPN?

**Comment by thataustin** [comment]
Ok, so I walked to a local coffee shop and now it's working.  I think the problem was with the DNS settings at the place I was working.  Talked to the Network admin and he said he changed some stuff recently.  It was right around the time he changed it last night that I started having issues.  I'm going to withdraw my issue here.  I think that whatever he did interfered with my Docker container's network settings.

**Comment by RakeshInfy** [comment]
@legodude17  I am on corporate proxy.pac

**Comment by legodude17** [comment]
Does it work without the proxy?

**Comment by MuhammadTaha** [comment]
try explicitly update the package.json file in dist as well as in the root

**Comment by ackvf** [comment]
Got this error on hyper-v virtual machine. Disabling "IPsec task offloading" in the Network Adapter, Hardware Acceleration tab did the job.

**Comment by blafasel-cc** [comment]
Get still the same here. It turns out to be an issue at fastly.com. `registry.npmjs.org` is only reached through fastly's reverse proxies. Which proxy you get is decided by a geolocation based DNS strategy.

All DNS servers seam to have the same CNAME record for `registry.npmjs.org`: `a.sni.fastly.net`. But for `a.sni.fastly.net` my telco providers DNS server gives me `151.101.12.162` while google's `8.8.8.8` gives me 4 totally different addresses.

If I stick to my telco's server the error occurs reproducibly. If I configure 8.8.8.8 everything works fine. This also makes the influence of proxy settings plausible.

**Comment by spaced-out-mvc** [comment]
I was having the same problem just now, i guess its a dns lookup which is failing.
i added this line to /etc/hosts and it now works perfectly in a split second.

151.101.16.162 registry.npmjs.org

I guess this fixes a major dns issue as now it installs npms blazing fast.
I wonder if this could help with github / composer by adding the github ip address as well.

I think when package installers do so many dns lookups it probaly times out.
so its best to set it manually in /etc/hosts if you have this type of problem happening.

Thanks
Daniel

**Comment by spaced-out-mvc** [comment]
So why stop there i say lol...

151.101.16.162 registry.npmjs.org
192.30.253.113 github.com
104.192.143.1 bitbucket.org
87.98.253.214 packagist.org

p.s. double check the ip address as some sites have regional cloud servers / load balancers

**Comment by Anuj-Raghuvanshi** [comment]
But In my case it is working on node 0.12.7 and not working with latest node i.e. 8.9.4
But problem is that packages which are needed are dependent on node > 4. Any Suggestions.??

**Comment by louisdauvois** [comment]
Restart computer worked for me

**Comment by MatviiStelmakh** [comment]
restarting services (docker engine and docker for windows service) and Docker for Windows itself helped

**Comment by Tweega** [comment]
I spent 2 hours this morning trying to fix this, before stumbling on louisdavois' suggestion of a restart.  I am staggered that this was indeed the technical advice I needed.  Time for a cup of tea to reflect on temps perdu.

**Comment by hussamsindhu** [comment]
i get this error while i m installing npm install -g nativescript
error code EAI_AGAIN
error errno EAI_AGAIN
error request to https://registry.npmjs.org/chalk/-/chalk-1.1.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

**Comment by Vaibhav-Bang** [comment]
I too got this error while I was installing local dependencies via **npm install**. According to me, it is a problem that is occurring due to the combination of both the internet proxy settings and the DNS servers configured with your internet connection.
**I SOLVED IT BY**:
1) Switching my internet connection to some other network.
2) Changing my configured DNS servers (i.e. Automatic, in my case) to manually that I entered (i.e. to Google's DNS servers).

(IPv4) Google DNS server address: 8.8.8.8 & 8.8.4.4
(IPv6) Google DNS server address: 2001:4860:4860::8888 & 2001:4860:4860::8844

**Comment by binarymist** [comment]
If using Docker, this known issue is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/

Simple fix is to create the file `/etc/docker/daemon.json`

and insert:

```
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```
where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

**Comment by COLABORATI** [comment]
I can confirm that this is still an issue and should not be marked as closed as the problem is not yet solved.

I see similar results like described in https://github.com/npm/npm/issues/16661#issuecomment-347655484

The npm registry should be available on all client computers without any need for some special DNS configuration. Please mark this issue as open, thank you! It also appears on top of google searches, why it is important to provide a solution right here.

**Comment by legodude17** [comment]
It appears that this would more be a registry or website issue then.
