### ISSUE TITLE
npm5: prepublish runs for npm install 

### ISSUE THREAD

**Issue by gyandeeps** [npm/npm#16685]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm publish` command gets run when you run `npm install`.

Log message:

```sh
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

* Is this getting fixed?
* I know we can use `prepare` phase that will only run on publish. If that is the solution then the log messages above needs to be corrected. I can send a PR if that what needed to be done.

#### How can the CLI team reproduce the problem?

* Add echo under `prepublish` script tag
* run `npm install`

### supporting information:

 - `npm -v` prints: 5.0.0-beta.57
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
We need to sit down and make a final decision about some aspects of this but: yes, `prepublish` is still being run on `npm install`. It is essentially an alias for `prepare` right now. `prepublishOnly` is what you should use if you want something to run before `npm publish` specifically. Don't worry npm isn't actually publishing on `install`. It's just what we used to call the script used to build your code (which presumably you also wanted to do during development).

**Comment by BurtHarris** [comment]
The messages npm@4 generates warning about `prepublish` have alerted people to the potential change, but haven't offered a solution that's both upward and *downward compatible* to at least npm@3.   

I've been thinking about this, and the apparent lack of best-practices for the transition.   I've put together what I think is a good approach for people who want to update their package.json with transpiler-step compatibility across npm versions.   Please have a look at it https://stackoverflow.com/questions/44037774/best-practice-for-upgrading-npm-prepublish-script-for-npm-4/44136814#44136814

One possible approach I might suggest for the transition to npm@5.   If a package has **both** `prepublish` and `prepare` scripts, treat it as *upgraded* and run just the `prepare` script on `npm install`.   

However, if a package has just a `prepublish` script, but no `prepare`, `npm install` in npm@5 is justified in treating it as hard-deprecated, and should instead of warning like 4 did, display an error and stop.   It would be a good idea if the error pointed to some best-practice document similar to mine above.

**Comment by zkat** [comment]
I'm working on a PR to finalize all this. I think we might start looking more seriously into transitioning away from `prepublish` on install in future releases. For now, we're just going to leave it deprecated and continue to warn about it. It'll be a bit before the ecosystem catches up.

More pressing are issues users have been having about when `prepublishOnly` runs, when the right time to do things to tarballs in various situations is. So, we have new `prepack` and `postpack` scripts that will take care of filling in the last gap in things people want to do -- and we'll also run `prepublishOnly` *before* the tarball is packaged, so folks can add whatever special stuff they need then.

Here's what putting it all together looks like now:

#### npm install

* `preinstall`
* `postinstall`
* `prepublish`
* `prepare`

#### npm publish

* `preinstall`
* `postinstall`
* `prepublish`
* `prepare`
* `prepublishOnly`
* `prepack` - last chance to do edits to the tarball before it's packed!
* `postpack`
* `publish`
* `postpublish`

#### npm pack

* `preinstall`
* `postinstall`
* `prepublish`
* `prepare`
* `prepack`
* `postpack`
* `publish`
* `postpublish`

**Comment by gyandeeps** [comment]
if its going to be part of a major version, i still dont understand why we need to have `prepublish` in `install` phase. I thought we are fixing the confusion point but apparently not. Am i missing something here?

**Comment by zkat** [comment]
@gyandeeps it's been that way since... The Olden Days. It's also the one script that everyone uses right now for "build my app".

Even when we're talking about semver-major changes, we try to be relatively conservative about them.

Those who truly care have an out now. I encourage you to switch to `prepare` and `prepublishOnly` as your app allows you to migrate.

**Comment by gyandeeps** [comment]
I get that and its good to be conservative. But `prepublish` (the word says it all) is so obvious.

I have tried `prepublishOnly` with Node 7 (latest) and it dint work right (dist generated by `prepublishOnly` never gets packed and sent to registry). So I had to use `prepublish` and its so annoying when npm install commands start to run all the things `prepublish` command does.

Again, this is just my thoughts and feedback.

**Comment by zkat** [comment]
@gyandeeps this is what these changes fix. That tarball is packaged up *after* `prepublishOnly`. But I recommend using `prepack` instead, so `npm pack` does the right thing when used by itself.

**Comment by gyandeeps** [comment]
> I encourage you to switch to `prepare` and `prepublishOnly` as your app allows you to migrate.

>  But I recommend using `prepack` instead, so npm pack does the right thing when used by itself.

I think I will always be confused on whats right. Hopefully I will get it right in sometime. Thanks for explaining.

**Comment by jsg2021** [comment]
So npm changed its mind? This warning clearly says as of 5, `prepublish` will not run on `install`

> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.

**Comment by zkat** [comment]
Yes. `prepublish` continues to be deprecated, but we thought it was prudent to change our minds here. It's a tough thing.

**Comment by BurtHarris** [comment]
Changing one's mind is fine, but I think you should consider changing your mind about treating `prepublish` as deprecated.   While the name is perhaps confusing, I think there are too many packages depending on the npm@3 behavior, and that *is* tough.      Instead of continuing to display the deprecation warning, I think its better to make the appearance of `prepublish` in the workflows (as documented above) permanent, rather than continuing to let this hang-fire into another major release.   

In that case the deprecation messages should simply go away, both in npm@4 and npm@5.

**Comment by zkat** [comment]
@BurtHarris The deprecation stays because it continues to be a source of serious confusion. We want people to move to `prepare` either way, we just think they need a little longer. It'll continue warning, but the warning has been reworded a bit.

**Comment by BurtHarris** [comment]
The problem facing people with shifting to `prepare`, is the loss of backwards compatibility.   

Backward compatibility wouldn't be a big issue if there were the proper semantic versioning, but the existing `engines` feature doesn't check versions at the *right time* to make sure at `prepare`/`prepublish`time, it only checks when the package is installed as a dependency.   Without prepare-time a semantic version check, that a `package.json` is compatible with the version of the npm being used, this seems unsafe.     As you say, it's tough.

I'm not saying it can't be done, in fact I wrote-up a [proof-of-concept for versioning at prepare time](https://stackoverflow.com/questions/44037774/best-practice-for-upgrading-npm-prepublish-script-for-npm-4/44136814#44136814).   There hasn't been a lot of meaningful feedback on that yet.

**Comment by zkat** [comment]
@BurtHarris This has much less impact than the usual ecosystem-wide problems of breaking compatibility for _installed_ modules. `prepare`-incompatibility primarily affects developers on the same project. It's much easier to get all your teammates on the same major version, and it's something you have to do anyway in this case, in order to take full advantage of `package-lock.json`.

**Comment by zkat** [comment]
@BurtHarris it's a hard decision -- that's why we didn't do it for a long time. But the same way you're making a case for keeping it, or making it work a particular way, we've had a bunch of folks asking about this, getting bitten by it, and asking for clarification throughout the years.

That's we we figured we'd start the process of deprecating this and moving the community away from it. It's hard to please everyone, but we're trying to undo early npm decisions that turned out to not scale as well as originally thought, or that were done when the community was much smaller and tighter-knit. I think it's stuff like this that will move the CLI forward.

It's easy enough for users doing special-case code to use an escape hatch here: you can easily find the npm version itself in a `prepublish` script, and make a decision about whether to use `prepublish` or `prepare` yourself, during the transition. Most people, though, do not need this level of widespread access to prepare/prepublish.

**Comment by BurtHarris** [comment]
Then write the example a solid escape hatch and include it in the documentation.   The deprecation message should point at it, rather waving hands about  it going away without explaining the "plan" for the process.

**Comment by zkat** [comment]
@BurtHarris The escape hatches are all documented, and I can't foresee every single individual corner case that people come up with. There is already a description of the prepare/prepublish plan in the scripts documentation. I think this falls outside the scope of straight-up docs. They might be worth writing a guide on, but this is really just something very particular to individual needs. I think people should make their own decisions about escape hatches that work for them.

**Comment by BurtHarris** [comment]
@zkat As someone who recently searched for such escape hatch documents, I can tell you that quality on this documents are hard to find.   The few I've found simply abandon either forward or backward compatibility, and the cost this misadventure won't be realized until support for `prepublish` as stands is dropped.  Look at my StackOverflow post asking about the topic.   It got zero attention until I put a bounty on it, and even then the only answer I got only explained why `engine` didn't do what I wanted.

**Comment by Hirse** [comment]
At the very least the message should be adapted, as it currently makes me think I am still running `npm@4` after upgrading to version 5:
![2017-06-01_14-57-47](https://cloud.githubusercontent.com/assets/2564094/26680948/9938f8b6-46db-11e7-8e4b-e61e1a70dea7.png)

**Comment by zkat** [comment]
@Hirse eep! Nice catch. I thought I'd updated that message already, but clearly I didn't. I'll make a note to do so (or, if you wanna PR it, I'll take the PR!). Thank you <3

**Comment by Hirse** [comment]
@zkat Done: #16918

**Comment by mderazon** [comment]
I am confused.

When I run `npm install` in v5.0.3 with `prepublish` in `package.json` I get:
> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.

And I see that the prepublish step is being run.

Also, The docs say
> IMPORTANT:  As  of npm@5, prepublish will only be run for npm publish.


There's obviously a conflict here. So what's the update for npm 5 regarding this change ? Docs need to be updated ? 

@zkat:
> I encourage you to switch to prepare and prepublishOnly as your app allows you to migrate.

Isn't `prepublishOnly` planned to be deprecated in the future ?

**Comment by Hirse** [comment]
The message is correct (after my change 😉). Yes, the docs need updating I think.

**Comment by BurtHarris** [comment]
Semantically the message is *incorrect*, if only slightly.   It misuses the term `deprecated`.   

See Bug #17029 `prepublish` - deprecated or change planned? What about `build`?

**Comment by RinatMullayanov** [comment]
In the console
```sh
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```
The site
https://docs.npmjs.com/misc/scripts#deprecation-note
> IMPORTANT: As of npm@5, prepublish will only be run for npm publish. This will make its behavior identical to prepublishOnly, so npm@6 or later may drop support for the use of prepublishOnly, and then maybe we can all forget this embarrassing thing ever happened.

What in the end is deprecated? `prepublish` or `prepublishOnly`?
