### ISSUE TITLE
Add an option to get rid of resolved field in package-lock.json

### ISSUE THREAD

**Issue by otakustay** [npm/npm#16849]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's the feature?

The story is we have a registry which only serves our internal network so developers outside company cannot access, also out CI machine can only access internal network so the default registry is out of reach

In this case, if a developer runs `npm install` in default registry, a generated `package-lock.json` will lead CI machine to download tarball from npmjs.org and fail

In my point of view, `package-lock.json` currently contains a `integrity` field to check the shasum of a package, so we can leave the install machine to decide where to download tarball and check shasum for integrity, the `resolved` field can be a speed boost but it should be optional

**Comment by zkat** [comment]
@otakustay ok so!

npm5 has a feature that allows it to switch registries: if npm finds a `resolved` field that does not match the current `registry` (or `@scope:registry`) setting, it will simply ignore the `resolved` field, effectively doing what you're talking about.

If this is not working for you, then this is a bug and it would be useful to get more information about what you're doing so I can reproduce and fix it.

**Comment by otakustay** [comment]
Thanks for this hint, I wasn't aware of this previously

**Comment by josmardias** [comment]
@zkat 
My use case is a slight different. Let me start saying that things are working here in the end of the day. But things seems a little weird.

Situation:
I have a Nexus installed on a cloud, and it caches NPM for production build and overall developers usage.
But we have *another Nexus* installed locally on one of our offices, and it caches the "external Nexus" making even faster for that particularly internal network.
I don't see a point here to discuss if it's a good design, it's a fact, it's how things goes here, and I does not seem to be a prohibited architecture.

Said that, the "problem" is:
The `package-lock.json` grows a bit strange. Some installed packages has a `resolved` field pointing to

**Comment by josmardias** [comment]
@zkat 
First of all, congratulations for npm@5, NPM cli team did an amazing work.
Second, sorry for commenting in a closed issue, by I think it's the same topic, so maybe a reopen is the best course of action.

About the `resolved` field, my use case is a slight different. Let me start saying that things are working here in the end of the day, so it's not a problem that the cli team should put before anything else. But things seems a little weird here anyway.

Situation:
I have a Nexus installed on a cloud, and it caches NPM for production build and overall developers usage.
But we have *another Nexus* installed locally on one of our offices, and it caches the "external Nexus" making even faster for that particularly internal network.
I don't see a point here to discuss if it's a good design, it's a fact, it's how things goes here, and I does not seem to be a prohibited architecture.

Said that, the "problem" is:
The `package-lock.json` grows a bit strange. Some installed packages has a `resolved` field pointing to one Nexus, some points to another Nexus. There are some fields pointing to the NPM registry itself (probably someone not using Nexus on it's development environment).

My conclusion:
It works anyway, as I said in the beggining. Because npm@5 (don't know about earlier versions and shrinkwrap, but I guess it's the same behavior) uses `.npmrc registry` field if any instead of the `package.json`.
But still, what's the point of resolved? On npm@4 and earlier it was used by shrinkwrap file as a `single source of truth` I think, because there was no `integrity` field to verify, so it used to believe on the resolved url, something like "if you get from the location, it's the same thing".
It's not true anymore. `package-lock.json` has a integrity field. So I ask again, what's the point about the resolved field?
Should I just ignore this resolved madness on the package-lock.json?

My perception:
1) `.npmrc` registry config seems to be the perfect place to tell npm where to fetch packages from
2) avoiding npmrc registry configuration to "let package-lock.json say different places to fetch different packages" seems to be a bloat feature (sorry if I'm particularly wrong on this sentence, but I really didn't find anyone until now asking for that)
3) "integrity" field tells npm if that tarball can be trusted
4) from 1, 2 and 3, whats the point of `resolved`?

Ps.: any harsh words here were just my bad english :(

**Comment by zkat** [comment]
@josmardias The purpose of `resolved` in `package-lock.json` is to bypass the dependency resolution step (fetching metadata) when you are missing packages. `integrity` is to verify that you're getting the same thing. Without the `resolved` field, uncached installations can break due to metadata changes, and they'll also be significantly slower because we have to do a full metadata fetch before we can actually download anything.

`package-lock.json` is intended to make sure that you get the _exact same thing_, as much as possible, down to the byte.

Note that `package-lock.json` does _not_ allow different packages to be fetched from different registries. Even if you have a package lock with different packages using different `resolved` fields, all of the packages will *always* be fetched from whatever your current `registry=` setting is, in `npmrc`. `resolved` fields that do not match the configured registry will go through the (slower) metadata fetching I mentioned above, but will still be fetched only from the current registry.

There is no facility right now to normalize a `package-lock.json` to a single registry, partly because doing this automatically would mean users will get a lot of big diffs any time they do an install on a different registry. If you want to normalize it, you'll need to do so yourself, by hand. (basically just a `sed`, tbh).

**Comment by josmardias** [comment]
great answer @zkat ! Thanks for your time :balloon:
