### ISSUE TITLE
Symlinking local npm packages ruins the flat dependency tree, causing several problems

### ISSUE THREAD

**Issue by gsanta** [npm/npm#17593]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Installing modules from local file system (e.g having sth. like this in package.json: "file:../moduleB") does not copy the module anymore in npm5, but only creates a symlink.

This behavior seems to conflict with the idea of trying to flatten the dependency tree introduced in npm3. Because now if you symlink a local module all of the dependencies of that local module are going to be part of the dependency tree, even if they would be flattened out when you installed it from npm registry.

I think this can cause problems for existing projects in various ways:
    - there are modules which can have erroneous behavior when multiple instances are present (e.g react, angular)
    - typescript compilation can fail, if duplicate declarations are found 

#### How can the CLI team reproduce the problem?

I found the problem when the same typescript modules were present more then one time in the dependency tree causing 'duplicate identifier' error messages.
(I can assemble an example project if the problem is not clear from my description) 

Is the npm team aware of this behavior, and the consequences of this?

**Comment by zkat** [comment]
This is something we're aware of, yes.

That said, npm is _still_ able to dedupe things in a certain situation: if you have something that looks like a monorepo. So if you have something like this:

```
your-project
\_packages
  \_ some-type-pkg
\_package.json
```

and you do, from the root, `npm i ./packages/some-type-pkg`, the dependencies for `some-type-pkg` will be deduped as usual.

Please keep in mind that npm is not, and has never been intended to be, a "flat installer". While we make a best effort to reduce deduplication and flatten the tree, since `npm@3`, there is no way to guarantee that a tree will be flat, and there is no intention to guarantee this in the foreseeable future. If you want to have a "single-instance" thing, you would need to rely on `peerDependencies` or use techniques like dependency injection to control the number of instances. This is the preferred method.

If you want local package installations during development, you might consider doing `npm i $(npm pack ./path/to/pkgdir)`, which will execute an installation similar in behavior to the old way of doing things -- though you'll need to manage the generated tarball on top of regular directory management -- but directory dependencies were poorly designed to begin with (hint: they weren't designed at all, they were added as a "sure why not", off-the-cuff, many years ago).
