### ISSUE TITLE
Unexpected "not a child of" error

### ISSUE THREAD

**Issue by novemberborn** [npm/npm#17637]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a monorepo with `packages/app` and `packages/frontend`. There is a dependency from `app` to `frontend`. Installation of `app` fails with:

```
npm ERR! /path/frontend/node_modules/webpack-visualizer-plugin/node_modules/react is not a child of /path/app
```

#### How can the CLI team reproduce the problem?

See https://github.com/novemberborn/_npm_not_a_child_repo

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: v8.1.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by novemberborn** [comment]
Installing `frontend` first, and then `app`, seems to solve this issue. This is not ideal though as it requires my build process to be aware of such dependencies between the different packages.

**Comment by novemberborn** [comment]
Thinking about this more, for my use case it feels like npm is doing too much. All I want is a symlink to the file path, but npm adds loads of stuff to the package lock and then gets confused about what to install.

**Comment by sudo-suhas** [comment]
I also faced this issue:
```
λ npm install -g hotel

> hotel@0.7.3 uninstall C:\Program Files\nodejs\node_modules\hotel
> node bin/uninstall.js

C:\Program Files\nodejs\hotel -> C:\Program Files\nodejs\node_modules\hotel\lib\cli\bin.js
npm ERR! C:\Users\suhas.karanth.RB\AppData\Roaming\nvm\v8.1.2\node_modules\hotel\node_modules\fsevents is not a child of C:\Program Files\nodejs
```

I am using [nvm for windows](https://github.com/coreybutler/nvm-windows)
```
λ node --version
v8.1.2
λ npm --version
5.1.0
λ nvm version
1.1.5
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 8 Pro
OS Version:                6.2.9200 N/A Build 9200
```
npm debug log - https://gist.github.com/sudo-suhas/184566aac34ffe04b331d31e8ebfe84f

Installs correctly with npm `v3.10.10` and node `v6.10.3`

**Comment by juliusdavies** [comment]
I'm getting something similar when node_modules is a symlink:

`/home/juliusdavies/node-cache/node-v6.11.0__with__npm-5.2.0/node_modules/karma/node_modules/fsevents is not a child of /opt/central1/mdi/core/modules/com.cucbc.resources.webapp`

This is silly since the "node_modules" symlink is sitting right there in the "com.cucbc.resources.webapp" directory, and so it actually is a child.

Things are fine for me on NPM 5.0.4.   Only breaks on 5.1.0 and 5.2.0.

**Comment by iarna** [comment]
Looking at @sudo-suhas's debug logs and they are fascinating. The error is coming from `fs-vacuum` and that's ultimately being called from a rollback of a finalize. (In this case it's rollbacking `fsevents` on Windows. It shouldn't even try finalize in that scenario so that's another bug.)

It also only happens if the target path for for the rolled back module is a symlink. And that's due to obviously wrong code in the finalize rollback. Fixing that proximate cause is v easy and I'll queue up a PR for the next release.

More deeply, my current theory is that something changed that resulted in it trying to install `fsevents` on Windows, when it should have refused to even try due to arch mismatches. That'll require a bit more digging…

**Comment by garthk** [comment]
@zkat and @iarna, strikes me this is still happening. Consider @novemberborn's repository with npm 5.3.0 on Node 8.2.1 on OS X 10.12.6:
```
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/private/tmp/_npm_not_a_child_repo/frontend/node_modules/jstransform/node_modules/object-assign' -> '/private/tmp/_npm_not_a_child_repo/frontend/node_modules/jstransform/node_modules/.object-assign.DELETE'
```

**Comment by ashubham** [comment]
@zkat @iarna I am seeing the same issue as above with node 8.4.0/6.9.4 and npm 5.3.0. This used to work great with npm v3.10.
