### ISSUE TITLE
I am having an error while installing mysql in npm the error is No compatible version found :myql^5.7.19 but i installed mysql server 5.7

### ISSUE THREAD

**Issue by santhoshk22** [npm/npm#18127]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by nwoltman** [comment]
The `mysql` npm package version is not the same as the MySQL database version. npm is giving you an error because there is no version `5.7.19` for the [`mysql` package on npm](https://www.npmjs.com/package/mysql). The latest `mysql` npm package version is `2.14.1`, so that's the version number you should use in your `package.json`.

**Comment by kenany** [comment]
Right, the driver's versioning is independent of the DB's versioning. Similar to https://github.com/npm/npm/issues/12189.
