### ISSUE TITLE
package-lock.json non-deterministic due to optionalDependencies

### ISSUE THREAD

**Issue by rally25rs** [npm/npm#18135]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

If an `optionalDependency` is installed, then it's entries appear in the `package-lock.json` file.
If you re-npm install the same project on a different OS that uses different optionalDependencies, then the lock file changes.

In other words, the lock file is not deterministic across OS's.

I would think that the "fix" would be to always include all `optionalDepnendecy` entries in the lock file whether they are installed or not.

#### How can the CLI team reproduce the problem?

* Start on OSX and `npm install {package}` where `{package}` is something that uses `fsevents`. For example, `npm install chokidar`.
* Now commit that `package.json` and `package-lock.json` file and move it to a linux or Windows OS.
* Run `npm install`.

The `package-lock.json` file will have changed because `fsevents` is not needed on these OS's so is not installed and is no longer in the lock file

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: All
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by cchamberlain** [comment]
Our lock files are constantly churning. Not sure if its just this as we see a ton of churn on `requires` and `dev` nodes. I'm on `5.3.0` and the rest of my team is on `5.0.3`, I believe all on Windows. It has not been either serializing or restoring correctly. I have to use `--no-optional` because otherwise it fails trying to install `fsevents` on Windows (wish there was a way to set flags at config level).

Related: https://github.com/npm/npm/issues/17671#issuecomment-315913640

I consistently get a duplicate package of `@types/react` pointing at react 16 (~5 others deduped to 15) if I blow away `node_modules` and reinstall (whether or not `package-lock.json` exists), even though the package its transitive of only specifies `"@types/react": ">=16",`.

Related issues: https://github.com/npm/npm/issues/17091#issuecomment-321338767

We have one private scoped package but seems to be affecting a lot of people in general. If we publish a new version of the scoped package with an exact version range, it doesn't install it on others machines on `npm i`.

I hope this all works out to be related to one really annoying bug :pray:.

**Comment by rally25rs** [comment]
> Our lock files are constantly churning.

Yep this is exactly the problem. On a team where people have different OS's there needs to be some discipline to know whether or not you should commit your lock file changes. If a windows user runs `npm i` and commits their lockfile, then there is no more "locked" version of `fsevents`, so the next OSX person to `npm i` might now get a new/different version of `fsevents` than they had last time.

**Comment by cchamberlain** [comment]
@rally25rs makes sense, just curious that my issue is experienced even though my team is all on the same OS (different versions of NPM 5 but they all appear to use lock file version 1).

I was initially under the impression that if a `package-lock.json` exists, `npm install` would not bother to read the `package.json` nor would it have the ability to update the `package-lock.json` but this appears to not be the case at all given the churn. I can't think of a good reason why you'd want to do either of these two things on a package restore. Wonder if this choice was tied to the subject of this issue. If the answer is that we should specify `--no-save` on the CLI for a package restore, that's not a very good one because IDE's automatically run `npm i` on startup and there is no way to set flags via config.

**Comment by rally25rs** [comment]
@cchamberlain could also be related to #17237 if you are on different versions. It seems like there are a lot of things that cause the lockfile to change :( Really hope NPM can get that cleaned up.

**Comment by boennemann** [comment]
This is also happening for [greenkeeper-lockfile](http://npm.im/greenkeeper-lockfile).
It updates the lock file on Travis, removes optionalDependencies, e.g. fsevents, which is then causing churn when running `npm install` locally again.

**Comment by matttrawicki** [comment]
Seeing the same problem here. My team uses Macs, Ubuntu and Windows. When using a package (Swagger) that has a dependency (Chokidar) that has an optional dependency on an OS specific package (fsevents), the package-lock.json is different on the Mac. I'm tried of blowing up my teammates machines. It seems that optional dependencies need to be marked as such further up the JSON chain.

**Comment by greggb** [comment]
We're seeing this behavior if one person on the team installs in Ubuntu and another on MacOS. Between the drifting lockfile and the npm update warnings I've been getting a lot of shade from the back end devs when they start up the environment.

**Comment by gyzerok** [comment]
We have currently the same problem in our project. My team uses macOS, Arch Linux and Windows.

**Comment by gustavnikolaj** [comment]
It seems that this is indeed a bug, because the solution you describe is exactly what they intend it to do: https://docs.npmjs.com/files/package-lock.json#optional

It makes npm@5 unusable for anyone but individuals and small teams where everyone uses compatible platforms. I am very surprised that this issue has gone a month without any sort of reaction when this bug is present in the version of npm that is shipping with the stable version of node.js. 😞

**Comment by timmywil** [comment]
This is a blocker for the jQuery team. We decided to remove `package-lock.json` from the repo until this issue is resolved.

**Comment by boennemann** [comment]
For the record: Adding an `.npmrc` file with the contents `optional=false` next to the `package.json` prevents your `package-lock.json` from being changed all the time.

This is obviously not ideal, because now no one gets the optional dependencies, but at least there are two scenarios to chose from. #tradeoffs

**Comment by timmywil** [comment]
@boennemann Thanks for the workaround. We might do that.

**Comment by matttrawicki** [comment]
@timmywil @boennemann Be careful with that approach. Sometimes *optional* doesn't actually mean optional, but instead means *may be operating system specific*. Bunyan is a real example.

**Comment by boennemann** [comment]
@matttrawicki I agree, `optional=false` is definitely not a general purpose fix for this problem, which I tried to make clear. Thanks for making it even clearer with this additional case, where it's probably going to break completely.

**Comment by felixfbecker** [comment]
This is preventing big cross-platform open source projects like VS Code from updating https://github.com/Microsoft/vscode/issues/30134

**Comment by emkman** [comment]
I just saw major churn with a team mate, and we are both on OS X and both using node v8.6.0. The only difference was npm 5.3.0 vs 5.2.0. Furthermore the diffs aren't just across optionals. Either I don't understand the purpose of the lock file or it's very broken. It seems like probably both 🤔

**Comment by scottsword** [comment]
To be clear about the proposed interim `optional=false` fix. If you do in fact set this to false it doesn't mean that you will always install optional dependencies, but that npm will simply not attempt to install these at _all_. 

From the [docs](https://docs.npmjs.com/misc/config)...
>Attempt to install packages in the optionalDependencies object. Note that if these packages fail to install, the overall installation process is not aborted.

**Comment by mightyiam** [comment]
Seems like a duplicate of #17722.

**Comment by rally25rs** [comment]
Yes this is a duplicate of #17722. I'm going to close this issue then, so that discussion can be focused in that issue thread instead.

**Comment by kleptog** [comment]
For people finding this via Google, this is fixed in [npm 5.6.0](http://blog.npmjs.org/post/167963735925/v560-2017-11-27).
