### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by drothv** [npm/npm#18145]
#### I'm opening this issue because:

  - [ X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
after cloning an Ionic project, I need to run npm install to set it up, and thows errors I can not figure them out. 
#### How can the CLI team reproduce the problem?
Damian@ROTH MINGW64 ~/Desktop/fntech/demo/finance_app (master)
$ npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ETIMEDOUT 93.184.216.34:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Damian\Desktop\fntech\demo\finance_app\npm-debug.log

Log:     <script src="https://gist.github.com/drothv/900e552c807d08327557e8fa94f9937b.js"></script>
-->

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Windows 8.1
 - Network issues:
   - Geographic location where npm was run: La Paz, Bolivia, South America
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by alundiak** [comment]
I see, that we have many issues with `ECONNRESET`, so not to create mnew issues, here is my version of error with bootstrap codebase 


I cloned repo https://github.com/twbs/bootstrap, and `npm install` gives me this:

```
bootstrap git:(v4-dev) npm install
npm WARN bootstrap@4.0.0-beta requires a peer of jquery@3.0.0 - 4.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
domutils@1.6.2 (node_modules/domutils):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: 
request to http://registry.npmjs.org/domutils/-/domutils-1.6.2.tgz failed, 
reason: socket hang up

npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to 
http://registry.npmjs.org/htmllint/-/htmllint-0.6.0.tgz failed, reason: socket hang up

npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

```

Not sure if it'snpm issue or bootstrap, but when I open url `http://registry.npmjs.org/htmllint/-/htmllint-0.6.0.tgz` in browser I can download archive.
And afaik, I don't have any proxy configured.

Moreever, next time `npm install` gives an error regrading this:
- `http://registry.npmjs.org/chokidar/-/chokidar-1.6.1.tgz`

Could someone give me a hint, what is wrong? or how can I debug/check my MacOS.
Because similar happens to me at least with vie-cli and aurelia installations, so I don't know if this global issue or my local. 

## UPD
Setting registry to HTTPS helped me - I could install modules for bootstrap codebase.

Related to:
- #17921 
- https://github.com/npm/npm/issues/15604 + (vuejs/vue-cli#308)
- https://github.com/aurelia/skeleton-navigation/issues/857
