### ISSUE TITLE
npm update unhandled rejection error

### ISSUE THREAD

**Issue by alexandre1985** [npm/npm#18269]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
It get this message when I do:
`sudo npm outdated -g --depth=0`

> Unhandled rejection Error: ENOENT: no such file or directory, stat '/home/daniel/build/npm/src/npm-5.3.0/npm-5.3.0.tgz'
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-22T20_33_50_112Z-debug.log

#### How can the CLI team reproduce the problem?
I'm on Linux Manjaro Deepin x64.
All they have to do is install npm from the package manager then do:
`sudo npm outdated -g --depth=0`

### supporting information:

 - `npm -v` prints:
5.3.0
 - `node -v` prints:
v8.3.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Linux - Manjaro Deepin x64
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Butterfly** [comment]
Hi, @alexandre1985 Are you still experiencing this? There was a similar issue opened earlier, #18398. Their file path looked very similar to yours here AND was not correct. In fact, yours looks like both rolled into one:

> /home/daniel/build/npm/src/

Do either of these two paths exist in your system:

> /home/daniel/build/
> /home/daniel/build/npm/src/

Even if yours is fixed now, knowing that detail might help others solve this faster. This *might* be `npm` pulling something odd from configurations. If something does not look like that in basic configurations, maybe it's a crosswire somewhere nearby. Best wishes if your issue is already fixed! :smile:

**Comment by alexandre1985** [comment]
No, those paths dont exist in my system.
I'm still having this issue. Now it says:

> Unhandled rejection Error: ENOENT: no such file or directory, stat '/build/npm/src/npm-5.3.0/npm-5.3.0.tgz'

And that path also doesn't exist in my system.

**Comment by Butterfly** [comment]
That's now dropped your user out of the loop :smile: I started to think out loud that that's maybe about being relative to what directory we're sitting in with our terminals, but that's not right. It has to be about default configurations otherwise we couldn't [create global directories](https://docs.npmjs.com/getting-started/installing-npm-packages-globally) AND have them work under our users' ~/ directory (with no `sudo` needed).

While playing around, I took a quick peek at my ~/.npmrc file. That reminded me that we can run this:

`npm config get prefix`

That just gets one piece of the information that might point to where `npm` keeps deciding yours should go. This next one presents a more complete list of what `npm` is seeing:

`npm config ls -l`

Maybe something there will jump out as being what points `npm` toward creating both of those, /build and /src, together in one path. Meanwhile they're in separate (and still not correct) paths for someone else.

My brain is "sundowning", but I'm still looking at this overall (for my own learning). I'll type back if I trip over anything else. I haven't run `npm` for a couple weeks. I'm going to find something *simple* and *trustworthy* where I can trigger it to fail the way it's doing for various users. Hands on is how I best see what's going on :smile:

**Comment by alexandre1985** [comment]
my `npm config get prefix` returns: `/home/daniel/.npm-global`  
And `npm config ls -l` returns this:
```
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.4.0 node/v8.4.0 linux x64"

; userconfig /home/daniel/.npmrc
prefix = "/home/daniel/.npm-global"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
auth-type = "legacy"
bin-links = true
browser = null
ca = null
cache = "/home/daniel/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "nano"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/home/daniel/.npm-global/etc/npmrc"
globalignorefile = "/home/daniel/.npm-global/etc/npmignore"
group = 1000
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/home/daniel/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-version = "8.4.0"
offline = false
onload-script = null
only = null
optional = true
package-lock = true
parseable = false
prefer-offline = false
prefer-online = false
; prefix = "/usr" (overridden)
production = false
progress = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "/bin/bash"
shrinkwrap = true
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/tmp"
umask = 18
unicode = true
unsafe-perm = true
usage = false
user = 1000
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/home/daniel/.npmrc"
version = false
versions = false
viewer = "man"
```
I couldn't find anything related to /build or /src...

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (150/150 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:48241 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wbd-000kva-L2
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:50:54 -0600
Date: Thu, 26 Oct 2017 21:50:42 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509079842;
	bh=Go35A7vSOK7cv58BP3qLmdrHjJ4QB8o7r0NEzE+b/wI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VmVHcbHQ/XXzjxfq8saRKH8gUsCQM5pnw9ctmvTcStydr3ivXvBDuPK/L6f4GpzeB
	 Z1PPkdVxvcw0s3GY+PUDE/JQjFbEMBlc9IMPsCJIEgkucNRnCuVbd19GwiSH3mDkOc
	 TCbvXvBjdEqCLWLEs2/XnUDBKn3anq105xX0bD+c=
