### ISSUE TITLE
error when installing newman

### ISSUE THREAD

**Issue by barbottin** [npm/npm#18362]
**I want to install newman on a windows 2012 server. 
I launched the command : > npm install newman --global
but I got errors.**
Please can you help me ?

npm-debug.log file :
 https://gist.github.com/barbottin/0bf712bbf2f217918703cc8bc7906962#file-npm-debug-log
  
### supporting information:
 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - OS : Windows server 2012 R2 standard
 -  The server has no internet access.

**Comment by amosbatista** [comment]
Hi, Barbottin,

I think you got a failure in your internet connection. Try to install it again.
If you can't, open this link in your browser and tell us what it shows:
[https://registry.npmjs.org/newman](https://registry.npmjs.org/newman)

Bye.

**Comment by Butterfly** [comment]
@amosbatista Since you suggested visiting the webpage to see if it displays, I have something I'd been waiting for the right chance to ask users here. I'm a newbie so, while scouring `npm` documentation regularly, I tripped over these:

* `npm ping`
* `npm doctor` (as root)

Does anyone know if they're something pre-existing that could help (possibly further?) diagnose connection errors? For me, `npm ping` doesn't say much. I just get closed brackets (`{}`).

`npm doctor` (as root) takes a little longer, but I really like the extended feedback, e.g.:

`npm ping                            OK`
`npm -v                              v5.3.0`
`node -v                             v8.4.0`
`npm config get registry             https://registry.npmjs.org/`
`which git                           /usr/bin/git`
`Perms check on cached files         ok`
`Perms check on global node_modules  ok`
`Perms check on local node_modules   ok`
`Verify cache contents               verified 2 tarballs`

Does anyone have any opinions yay or nay specifically about all the connection errors? It kind of seems like a nice, already existing, one stop feature to have on call regarding issues. But I'm new around here so what do I know. :smile:

**Comment by barbottin** [comment]
Hi
Thank you for your answer.
The server has no internet connection. I understand now that it is the reason why the installation failed.
Which advice could you give me to achieve the installation of newman offline ? Should I use npmbox ?

**Comment by ChiragR7** [comment]
Hi
I am facing the same issue in installing newman offine.

**Comment by amosbatista** [comment]
Maybe, someone can bring a better solution, but I could try make this:
- Install **npm** into a machine with Internet;
- Install the **newman** package;
- Copy the entire **node_modules** folder to the project folder, in project.
