### ISSUE TITLE
Unhandled rejection Error: ENOENT: no such file or directory - npm ERR! cb() never called!

### ISSUE THREAD

**Issue by darkbasic** [npm/npm#18398]
npm crashes, it says it's "an error with npm itself". Here is the log: [2017-09-04T15_24_59_564Z-debug.log.txt](https://github.com/npm/npm/files/1275084/2017-09-04T15_24_59_564Z-debug.log.txt)

```
$ sudo npm outdated -g
Unhandled rejection Error: ENOENT: no such file or directory, stat '/home/niko/build/semver/src/semver-5.4.1.tgz'

Unhandled rejection Error: ENOENT: no such file or directory, stat '/home/niko/home/src/marked-man-0.2.1.tgz'

Unhandled rejection Error: ENOENT: no such file or directory, stat '/home/niko/home/src/marked-0.3.6.tgz'

Unhandled rejection Error: ENOENT: no such file or directory, stat '/home/niko/build/npm/src/npm-5.3.0/npm-5.3.0.tgz'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-04T15_24_59_564Z-debug.log
```

### supporting information:

```
$ npm -v
5.3.0
```

```
$ node -v
v8.4.0
```

```
$ npm config get registry
https://registry.npmjs.org/
```

ArchLinux

**Comment by Butterfly** [comment]
Hi.. This is coming from a newbie, but I'm decent at catching details sometimes. Your error message printed out a file path called `/home/niko/build` then the next line says `/home/niko/home/src`.

Do you actually have a file path that has "home" referenced two times like the one for /src?

If you do, cool, that's your personal style of file and directory setup. If that file path does **not** exist, though, I'm wondering why `npm` thinks it exists. :smile:

**Comment by darkbasic** [comment]
Hi,
Both `/home/niko/build` and `/home/niko/home` do **not** exist. I really don't know what npm is searching for...

**Comment by Butterfly** [comment]
@darkbasic Well, that's actually "cool" then because it's a place to start. BUT I *am* a newbie, we'll probably only get so far with what I've learned in [`npm` documentation](https://docs.npmjs.com/), GRIN. I do know to run things like:

`npm config list`

`npm config ls -l`

If you find a place where you can tell that's where `npm` is seeing that location, then you can use the "set" command to change that option (that [declaration]). You can see much, if not most, of what config lets you view and change via command line by just running this:

`npm config`

That "fusses" by showing `npm ERR!` error lines that tell what options exist.

**Comment by darkbasic** [comment]
Fixed: https://github.com/npm/npm/issues/17878
I'll reference the other bug report and close it.
