### ISSUE TITLE
npm not including ./lib/node_modules folder

### ISSUE THREAD

**Issue by maikelmclauflin** [npm/npm#18508]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
the ./lib folder with a single folder inside of it: ./lib/node_modules is not being included when a package is being published

#### How can the CLI team reproduce the problem?
create a package with a folder in it and in that folder create a node_modules folder. create a file. File is not included when the package is published

### supporting information:

 - `npm -v` prints:
5.4.1
 - `node -v` prints:
v7.10.0
 - `npm config get registry` prints:
http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
OS X / 10.12.6 (16G29)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rodrigodc** [comment]
Same here, in my case I have a `./src/node_modules` directory, which has nothing to do with the top-level `./node_modules` directory.

It contains application files and is necessary so that I can use paths relative to my `src/` folder in `require(...)` calls and avoid things like `require('../../../bla')` in my code.

That folder has always been included in my npm packages before, and now it is no longer, which **breaks** my code since the packages no longer contain my application files.

I have tried to explictly include it via the `files` section in `package.json`, but had no luck (as expected, since the docs mention that any `node_modules` (not only the top-level one) will always be ignored, regardless of any settings).

Any suggestions?

Thank you.

**Comment by kgryte** [comment]
Possibly related issue: https://github.com/npm/npm/issues/18461

**Comment by kgryte** [comment]
@rodrigodc My temporary workaround was to drop back down to npm `v5.3.0` until this is resolved.

**Comment by maikelmclauflin** [comment]
that's what i did too

**Comment by rodrigodc** [comment]
The [issue](https://github.com/npm/npm-packlist/issues/4) I had opened on npm-packlist is now fixed, so it seems that this one will be automatically fixed by that.
