### ISSUE TITLE
Proposal: `--no-<protocol>` (or at least `--no-git`)

### ISSUE THREAD

**Issue by indexzero** [npm/npm#1852]
So recently we've ditched git submodules in-favor of `git+ssh://git@....` style protocol syntax in our package.json. To avoid the overhead of additional SSH keys for git pulls on our production boxes also add these to `bundleDependencies`.

e.g.

``` js
  {
    "dependencies": {
      "some-dep": "git+ssh://git@github.com:some-user/some-dep.git"
    }
    "bundleDependencies": [
      "some-dep"
    ]
  }
```

_Potential bug_ 
When we untar the package we create and run `npm install` npm throws because there is no valid SSH key for the git dependencies. Shouldn't `npm install` not attempt to install the git dependencies because they are on disk?

_Proposed solution / workaround_
We could work around the larger issue here by simply telling npm to ignore git dependencies which I would image would be something like:

``` bash
  $ npm install --no-git
```

@isaacs What are your thoughts here? I don't know much about how `nopt` works, but if you're parsing this stuff into `npm.config` it seems like a one-line feature:

Replacing this: https://github.com/isaacs/npm/blob/master/lib/cache.js#L229-236 with the code below would do the trick. 

``` js
case "git:":
case "githttp:":
case "githttps:":
case "gitrsync:":
case "gitftp:":
case "gitssh:":
  if (!npm.config.get('no-git')) return addRemoteGit(spec, p, name, cb) 
  return cb() 
```

**Comment by othiym23** [comment]
1. `npm@3` should install `bundledDependencies` from package tarballs without trying to cache them.
2. However, we might want to change the behavior of Git dependencies so that we're regularly updating the cache to pull down user changes without forcing them to nuke and reinstall the local checkout. I believe this behavior (in this case) would be handled by the change I propose in #12368, which is also more generally useful.
3. Making it configurable whether certain installer paths are followed at runtime (at least at this level of granularity, which is neither particularly fine nor coarse) seems likely to be confusing and a source of edge case bugs.

As such, I'm going to close this as something that we're not going to implement directly, and also that's been partially addressed by subsequent changes to npm, but identifying the issue that led to #12368 is super helpful, so thanks to you both for this discussion!
