### ISSUE TITLE
I have win7 64-bit,when I ran NPM install, it reported this mistake. How can I solve this problem?

### ISSUE THREAD

**Issue by DickLicha** [npm/npm#18589]
![image](https://user-images.githubusercontent.com/21870645/30625788-f5b5bae8-9df7-11e7-8866-c3ede0c21326.png)

**Comment by rendall** [comment]
Try installing npm 5.3.0:

`npm i -g npm@5.3.0`

**Comment by DickLicha** [comment]
My npm edition is higher than 5.3.0
![image](https://user-images.githubusercontent.com/21870645/30730668-5084986e-9f9b-11e7-906d-1c16ee65b6e3.png)

**Comment by Butterfly** [comment]
@DickLicha .. @rendall is possibly responding to where your first printscreen/screenshot says:

> npminstall version: 3.1.4

They may also be suggesting that you downgrade. I've been seeing people on npm/npm downgrade and then report they have success after that. I've not done that yet so I have no tips on a how-to. I figure at least this gives an idea of what you could search for.. :)

Where @DickLicha 's printout is referencing 3.1.4, is that an old `npm` version, or is that what a package within `npm` would normally reflect for [their reported 5.4.2 version](https://github.com/npm/npm/issues/18589#issuecomment-331354940)? Am just wondering out loud because maybe there's some kind of conflicting install of the primary packages going on. If that's the case, I wonder how often that has played a part in other posted issues. :smile:

**Comment by rendall** [comment]
@DickLicha Yes, @Butterfly is right.  I suggest you downgrade your npm to 5.3.0 using the command `npm i -g npm@5.3.0`  There is a bug in the 5.4.x that causes that error.  The latest might be okay?
