### ISSUE TITLE
503 responses after npm install in EU

### ISSUE THREAD

**Issue by kujon** [npm/npm#18626]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
npm install
```

The following is happening in the EU region.

```
npm ERR! Unexpected token < in JSON at position 1
npm ERR! 
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 No healthy backends</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 No healthy backends</h1>
npm ERR!     <p>No healthy backends</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-lhr6326-LHR 1506338630 2553879771</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by kenany** [comment]
I think this should be reopened over at <https://github.com/npm/registry>. Also, see: <https://status.npmjs.org/incidents/zm23dpx9gy8t>

**Comment by Butterfly** [comment]
Closed?! Hate when I miss the deadline, grin. I tried to help by doing an Internet search. This pulled up:

* [Common 503 errors (at Fastly's documentation pages)](https://docs.fastly.com/guides/debugging/common-503-errors)

In part, it says:

> Varnish, the software that powers the Fastly CDN, will sometimes return standardized 503 responses due to various issues that can occur when attempting to fetch data from your origin servers. 

They go on to explain several scenarios to give a feel for what might be happening. Sounded pretty good because I've seen Fastly come up with respect to IP addresses when my own `npm` doodling fails. That's why I'm going ahead and attaching here so that it comes up in searches down the road.. :)

Editing this to add:

Found this after commenting. Is from [that same page](https://docs.fastly.com/guides/debugging/common-503-errors):

>  WARNING: If you are seeing 503 errors, do not purge all cached content. Purge all overrides stale-if-error and increases the requests to your origin server, which could result in additional 503 errors.

Thought it might be of important interest because it sounds like something along the lines of what people might try AND it also sounds like something that might create a circle of repeating fails.

That is, *if* that error in this reported issue in fact even belongs to Fastly. That error is very specifically referenced further down on their 503 page there so am feeling... almost confident about that. :smile:
