### ISSUE TITLE
Is npm dead?

### ISSUE THREAD

**Issue by brycedrennan** [npm/npm#18986]
Asking because the official install instructions haven't worked for node 6 for about a month, there are ~900 open issues, and no commits for 23 days.  Seems like its not being maintained.

#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Clean installs of npm don't work on official node images.

#### How can the CLI team reproduce the problem?

```
FROM node:6
RUN npm up -g npm
RUN npm -v
```
See this "closed" issue for further examples:  https://github.com/npm/npm/issues/18667

**Comment by cogitaria-admin** [comment]
Simple pack of a scoped module failed with 5.4 the other day and somebody kindly pointed out that you need to rollback to 5.3.  That you cannot pack a scoped module seems rather alarming is it not? Decided to follow the alternative fix: install yarn.  The question now is why bother returning to using npm? I hope this is not seen as trolling npm or pushing yarn. I think it's clear Facebook's Yarn is trying to muscle into this space, but now NPM is helping with its own demise.

**Comment by iarna** [comment]
@brycedrennan

It's being very actively developed, the commits are in branches and associated libraries. The 900 issues is a lot less than the 2500 we had this time last year. We do not have official install instructions for Docker environments, so I'd be interested to know what you're working from? 

We have a release queued in the [`release-next`](https://github.com/npm/npm/commits/release-next) branch (where commits are queued prior to releases—we don't merge directly to `latest`) that's been delayed by a bug it uncovered in `pacote` and fixing that bug has been delayed by my and @zkat's conference schedules. I'm off for NodeConf EU, but she'll be back next week and we hope to get that release along with bug fixes out very soon. (It's important because it ALSO includes fixes for incompatibilities introduced by Node 9.)

I would love to see more participation from the Docker community, as Docker often has unusual limitations not found elsewhere that npm seems to bump into with some regularity. An easier first step would be to work out how to do CI in Docker environments. I'd love to see some community support there. Would you be interested?

If you want to help out the best way is to join https://package.commmunity and poke your head in the #npm channel.

@cogitaria-admin If you still see issues in 5.5.1, I'd love to see a bug report, but adding comments to this issue is derailing. I can't even reproduce the issue under 5.4.0. Again, I'd love to see a repro.

#18667 had been triaged as support and so was closed due to inactivity. I've reopened it and tagged it as a bug. In light of it being open now, I'm going to close this as a duplicate of it.

Also, due to the uncharitable framing and unproductive discussion in this thread thus far, I'm going to lock the issue. If you'd like to discuss it more, I encourage you to drop by our channel above. Thanks!
