### ISSUE TITLE
npm uninstalls github packages when installing a new package

### ISSUE THREAD

**Issue by vladfrangu** [npm/npm#19478]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a few packages installed that come from git repositories (`github:author/repo#branch`)
Running `npm i` and some package name installs the package but uninstalls all the github packages in the process

#### How can the CLI team reproduce the problem?

- Install a package thats defined in package.json from github (I used `github:hydrabolt/discord.js#voice-rewrite` but it can be reproduced with any github packages)
- Install a normal npm module (`cluster`, `async`, w/e)
- Watch it uninstall packages and install the requested ones, 

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by derikb** [comment]
This is basically ruining my ability to use npm effectively. I can only get one github based package to install at a time. NPM seems to recognize I want the package, because ```npm outdated``` lists the packages as MISSING and they are not removed from package.json, but the files themselves are removed as are any record of the packages in package-lock.json

Only the most recent one I install sticks around.

**Comment by redbugz** [comment]
This just broke us as well. During our build we install an additional package with some files just for the build, and in 5.5.1 it works fine, but in 5.6.0 it uninstalls at least some if not all of our github packages (of which we use many) and breaks everything. I tried using --no-save as well, but it also has the same behavior.

We are deciding if we should force everyone to revert to 5.5.1, or stop installing additional packages during our build and put those somewhere else instead. We'll probably stop installing the additional package since that was probably going to be a problem eventually anyway. But it still seems like the wrong behavior.

org/repo names changed below:
```
$ npm install git+https://github.com/our-github-org/some-project.git --no-save
+ some-project@2.4.0
added 13 packages and removed 1029 packages in 23.686s```

**Comment by G-Rath** [comment]
I think this is a duplicate of my issue: https://github.com/npm/npm/issues/19394
  
It affects any git repo (BitBucket or GitHub), and is *very* annoying :)

**Comment by vladfrangu** [comment]
Oh snap @G-Rath, you're correct. Nice catch about this being a dupe, will close in favor of #19394
