### ISSUE TITLE
can't publish - unauthorized Login and is not in the npm registry

### ISSUE THREAD

**Issue by xiubug** [npm/npm#19735]
when i run ` npm publish `, error occurred：
```
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! 404 unauthorized Login first: very-vu
npm ERR! 404 
npm ERR! 404  'very-vu' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
...
```

And then, I run `npm login or npm adduser`,
At last,  can't publish

**Comment by fralonra** [comment]
I have the same problem. Did you solve the issue?

**Comment by fralonra** [comment]
Solved!

I set npm registry to `https://registry.npm.taobao.org/` some days ago.
But it was on `https://registry.npmjs.org/` I used to log in and publish the package.

So I did the following:
1. `npm config set registry https://registry.npmjs.org/`
2. `npm login`
3. `npm publish`

And it was done! So is there anyone can tell me what the problem is internally? Thanks a lot!
