### ISSUE TITLE
Please issue a CVE and mark 5.7.0 as vulnerable

### ISSUE THREAD

**Issue by brodock** [npm/npm#19890]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

#19883 causes issues to production environment. Also https://github.com/npm/npm/issues/19883#issuecomment-367698802 describes a way the behavior introduced by 5.7.0 can be exploited to do things that are not intended.

I understand that CVEs are usually assigned before a responsible disclosure, fix is delivered, but as this was publicly disclosed, the clock is ticking and people should be aware of.

**Comment by ErikB26** [comment]
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7408

**Comment by zkat** [comment]
(this lock is preemptive. We'll have an actual response once we talk about it, but I'm heading off the trolls that are still circling like sharks)

**Comment by zkat** [comment]
I see that someone else filed a CVE, but we wouldn't have filed one ourselves: After internal discussions and consultation with a security team, we decided that a bug that causes unintended behavior, in a prerelease software version especially, does not really warrant a CVE. Regarding the `setuid` thing, we do not consider that a vulnerability because the `setuid` bit is not preserved on a `chown`, therefore not risking creating world-executable setuid executables.

So, with that comment, plus the fact that OP's original request was done _anyway_, I'm gonna close this.
