### ISSUE TITLE
File Not Included In Package if named 'package'.

### ISSUE THREAD

**Issue by Undistraction** [npm/npm#19899]
#### I'm opening this issue because:

NPM is doing something I don't understand.

#### What's going wrong?

A file is missing from my package when downloaded from npm because it contains `package` in the file name: `package.template.json`.

If I run `npm pack` I can verify the file is present in the generated tarball, however once I publish the package and install it, the file is no longer present in the installed package.

If I change the name of the file to something other than 'package',  it is included as expected.

It seems that there is nothing on the list of [automatically ignored files](https://docs.npmjs.com/misc/developers) that would cause the file to be ignored.

My hunch is that this is caused by a regex that isn't specific enough and matches just on filename and not extension. 

#### How can the CLI team reproduce the problem?

- Clone / Fork https://github.com/Undistraction/default-template
- Rename package
- Run `npm pack` and verify file `package.template.json` is present in `/templates` dir.
- Publish package
- Install package
- Verify file `package.template.json` is not present in `/templates` dir.

### supporting information:

npm: 5.5.1
node: 9.3.0

**Comment by zkat** [comment]
This is working as expected.

This is why you're getting this: https://github.com/Undistraction/default-template/blob/master/.gitignore#L8

Make an empty `.npmignore` file in your root, or make that `package*` ignore a bit more granular (which is what I'd actually recommend tbh)

**Comment by Undistraction** [comment]
@zkat Ah. Well at least my hunch was right ;) 

Sorry for the noise.

**Comment by zkat** [comment]
no worries! Your report was thorough enough and provided the links to the information I needed so it was easy to debug for someone who's used to people getting surprised by the (sometimes surprising) behavior of the file packer.

You can read [the page on Files and Ignores](https://github.com/npm/npm/wiki/Files-and-Ignores) for more details (note: the part at the bottom about implementation is no longer applicable, since we use [`npm-packlist`](https://npm.im/npm-packlist) now). You can also check out [the test suite for file inclusion/exclusion logic](https://github.com/npm/npm/blob/latest/test/tap/files-and-ignores.js) which is both pretty thorough and, imo, fairly easy to read through when you're trying to understand the sharp corners. Hopefully that'll help if you ever run into these issues again.

As a final note, I highly recommend folks using an explicit `files` array in their `package.json`, because it's great at making sure you're only picking up the files you _actually_ wanna publish, and often trumps some of the shenanigans of .gitignore/.npmignore.

Have a good one!

**Comment by Undistraction** [comment]
> As a final note, I highly recommend folks using an explicit files array in their package.json, because it's great at making sure you're only picking up the files you actually wanna publish, and often trumps some of the shenanigans of .gitignore/.npmignore.

Sage advice! Thanks again.
