### ISSUE TITLE
Incompatible with versions of NodeJS under 6.0.0

### ISSUE THREAD

**Issue by RazzM13** [npm/npm#20425]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

Apparently, the `6.0.0` version of npm is incompatible with NodeJS under `6.0.0` and crashes with the following stacktrace:
```
/home/xxx/.envirius/envs/node-5.9.1/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

```

#### How can the CLI team reproduce the problem?

1) Install any version of NodeJS under `6.0.0` and npm at `6.0.0`;
2) Attempt to execute `npm -v`.

#### Context:
OS: `Linux / Archlinux`
Env: `envirius`
NodeJS versions that are failling: `4.1.0`, `4.1.1`, `4.1.2`, `4.2.0`, `4.2.1`, `4.2.2`, `4.2.3`, `4.2.4`, `4.2.5`, `4.2.6`, `4.3.0`, `4.3.1`, `4.3.2`, `4.4.0`, `4.4.1`, `4.4.2`, `4.4.3`, `4.4.4`, `4.4.5`, `4.4.6`, `4.4.7`, `4.5.0`, `4.6.0`, `4.6.1`, `4.6.2`, `4.7.0`, `4.7.1`, `4.7.2`, `4.7.3`, `4.8.0`, `4.8.1`, `4.8.2`, `4.8.3`, `4.8.4`, `4.8.5`, `4.8.6`, `4.8.7`, `4.9.0`, `4.9.1`, `5.0.0`, `5.1.0`, `5.1.1`, `5.2.0`, `5.3.0`, `5.4.0`, `5.4.1`, `5.5.0`, `5.6.0`, `5.7.0`, `5.7.1`, `5.8.0`, `5.9.0`, `5.9.1`, `5.10.0`, `5.10.1`, `5.11.0`, `5.11.1`, `5.12.0`.

**Comment by kenany** [comment]
If intentional, we may need to update the README to reflect that `npm` requires at least Node.js v6 now. Node.js v4 LTS ended this month (April). Also note that Node.js v5 was the unstable release line which became v6 several months ago, so it should probably not be used anymore.

**Comment by zkat** [comment]
We dropped support for `node@4` as part of `npm@6`, as one of its breaking changes (see the release notes). This is as @KenanY says -- because `node@4` has dropped off its maintenance window and is no longer supported by Node Core. We routinely drop support for node versions that are no longer supported by Node Core with the next semver-major npm release after the most recent Node EOL.

**Comment by nfischer** [comment]
@zkat could you update the README? Right now, it [explicitly states](https://github.com/npm/npm/blob/latest/README.md#important) support for node v4.

**Comment by zkat** [comment]
@nfischer: you wanna PR that? :)

**Comment by fabian3087** [comment]
RazzM13, 

I'm working with a Multitech conduit whit module LoRa, I haven't the same problem than you, but I do reload the same firware version and that works  

![image](https://user-images.githubusercontent.com/31227111/40517427-dd76881e-5f7a-11e8-9be1-bea168517e13.png)


![image](https://user-images.githubusercontent.com/31227111/40517443-f5c861e4-5f7a-11e8-8218-b256058a050e.png)


Now I Update the Node-red version  

![image](https://user-images.githubusercontent.com/31227111/40517535-6be88de0-5f7b-11e8-8d21-85e4bdcd2c5a.png)

**Comment by RazzM13** [comment]
Hi @fabian3087, I'm not really sure I understand how the two scenarios are related ... but if I can help you with anything just let me know :)

**Comment by QuietNoise** [comment]
Running:
`npm install -g npm`
(as suggested by npm itself)
on node < 6.0.0 breaks the node installation.

If npm 6 is not compatible with node 5 then generic npm upgrade command shouldn't install it or should install latest compatible version rather than breaking the installation with something that cannot be used.. 
Alternatively some sort of confirmation dialogue would be helpful to let layman know they are entering muddy waters.

**Comment by geethika-zen** [comment]
What's the solution for this? I'm not able to update node nor revert to older version of npm!

**Comment by legodude17** [comment]
Reinstall node from the website (I recommend the latest version).

**Comment by QuietNoise** [comment]
Yup. You have to uninstall the node and install it again. And probably later you will have to catch and install all global packages that were used by your projects. That's how bad this small, ignored bug is.

**Comment by legodude17** [comment]
@QuietNoise How exactly is this a bug?

**Comment by QuietNoise** [comment]
Read my previous comment https://github.com/npm/npm/issues/20425#issuecomment-396092267 and ask yourself how is this not a bug?

A regular command destroys the entire installation and leaves a user without a non destructive way to reverse it.

The bug is in not having a simple version or flag check that would prevent installing a major software component that is incompatible with core platform that is installing it.

To reiterate:
`npm install -g npm`
destroys every perfectly running Node 5.x.x installation out there because from there you are unable to use npm without completely reinstalling Node.

Let me put you into perspective of every Node 5 user:
1. You run your daily Node tasks, install some global packages, run some commands.
2. Every npm command you run displays a very prominent message stating that you are using version x.x.x and there is a new version 6.0.1 available and that you should update it using command **npm install -g npm**.
3. Nowhere it says that the moment you run this command you are effectively going to make npm unusable altogether.
4. As every non-seer regular user - who trusts the software vendor and who wants to have a peace of mind - you run this command as suggested.
5. And boom. You've just destroyed the very component you were updating.

The result of this command is completely against any expectation of every Node 5 user who will run it. 

As a software developer you can’t expect that end user will understand your software internals and predict unexpected destructive behaviour.
It’s like running Windows Update _(or any other software update)_ just to make Windows Update _(or any other software update component)_  unusable.

Hence, I reckon it is a bug.
