### ISSUE TITLE
npm audit - Error 400 - Bad Resquest

### ISSUE THREAD

**Issue by rzorzal** [npm/npm#20661]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

In my project, when I run ```$ npm audit``` it is throwing an error 400: bad request. URL:  https://registry.npmjs.org/-/npm/v1/security/audits

#### How can the CLI team reproduce the problem?
![captura de tela de 2018-05-17 14-20-53](https://user-images.githubusercontent.com/5184573/40193395-9021f5e6-59dd-11e8-8ff0-1e8d2024dbbb.png)

### supporting information:

My Dependencies: 
![captura de tela de 2018-05-17 14-22-09](https://user-images.githubusercontent.com/5184573/40193490-ccf5c7a4-59dd-11e8-9f77-0251cd57595c.png)

OS: Ubuntu 17.10
Node Version: 10.1.0
NPM Version: 6.0.1

**Comment by pedrocarrico** [comment]
I have a similar issue, and I've tracked it down to when I have a dependency that has shared dependency with the current application but in the current application I fetch it from a forked branch in my personal account, in my case `pg` (node-postgres).

In order to reproduce the issue use this package.json:
```
{
  "name": "npm-audit-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "pg-promise": "^8.4.4",
    "pg": "git+ssh://git@github.com/pedrocarrico/node-postgres.git#fd07ab9031cc8319bfbb34f01ed74dd5b0343d33"
  }
}
```

Run `npm install` and `npm audit` and it will fail with the following output:

```
npm ERR! code E400
npm ERR! 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pedrocarrico/.npm/_logs/2018-06-01T16_16_34_815Z-debug.log
```

I used the `pg-promise` as an example, any `pg` dependent package will trigger this.

OS: macOS High Sierra 10.13.4 (17E199)
Node Version: 8.10.0
NPM Version: 6.1.0

**Comment by eli8levit** [comment]
Dublicate of #20604

**Comment by paranoico** [comment]
Why is this issue closed if it still is unresolved???

**Comment by rzorzal** [comment]
It is duplicated. Go to #20604 to see the answer
