### ISSUE TITLE
What is my problem ? (npm insalling)

### ISSUE THREAD

**Issue by owoki** [npm/npm#21044]
I want install steam-user lib but i dont this because i have some problems. Pls Help
![screenshot_1](https://user-images.githubusercontent.com/38614710/41746320-8e2fec3e-75b2-11e8-883e-3d87d0c21077.png)

**Comment by kenany** [comment]
Seems like the installation was successful. I can explain each warning though if it helps:

  1. You don't have a `package.json` in your current directory. This isn't a huge deal, but if you're starting a new project I recommend you have one. Try out `npm init -y`!
  2. `discord.js` has some peer dependencies that you have not yet installed. You can just install each of them individually and you should be good to go.
  3. Your current project is missing a couple of fields. You can fill these out using a `package.json`.

Closing since there is no actual issue here.
