### ISSUE TITLE
Feature Request: npm install Should Only Install Exact Versions Unless Explicitly Overridden

### ISSUE THREAD

**Issue by thefringeninja** [npm/npm#21206]
#### What's the feature?

IMO `npm install` should only install exact packages unless explicitly told not to via a flag e.g. `--allow-package-upgrades`.

#### What problem is the feature intended to solve?

- Would make CI builds repeatable by default
- Would make it impossible to accidentally, silently upgrade to a compromised package e.g. #21202

**Comment by kenany** [comment]
Please open this at <https://npm.community/c/ideas>.

**Comment by zkat** [comment]
Thanks, @KenanY. I'm also going to lock this since it's likely to draw attention from #21202.

As a note: this feature request is covered by `package-lock.json` as of `npm@5`. Please upgrade to the latest npm. The feature, as described, would also not make CI builds repeatable by default, since that would involve all transitive dependencies having been published with this default, and that would likely take an immense amount of time and never be quite done, considering the scale of the registry, so I don't consider it a very good solution.

There are other things in the work to address issues with unintended dependency updates, but now's not the time to talk about them. Have a good one!
