### ISSUE TITLE
"npm install" and require() contradiction

### ISSUE THREAD

**Issue by ghost** [npm/npm#2278]
In my node_modules folder I have different modules under development.

    node_modules/a (b, c, d, e and f as deps)
    node_modules/b (c and d as deps)
    node_modules/c (d and a as deps)
    node_modules/d (e and c as deps)
    node_modules/e (b, c and f as deps)
    node_modules/f (a, b, c as deps)

When I am in node_modules/a and run "npm install" it will install all modules in it's own node_modules.

The problem is that it should be able to find that those packages are in the node_modules/ one folder up and use them instead of installing it from the npm registry. Npm could just find out that those are fetchable for node.js and skip installing those into packageA's local node_modules folder.

I find that npm is contradicting how node.js require() behaves if it installs those libraries even though those are in node's require() path and thus are fetchable.

Also in this way, we save ourselvs from a "npm link" nightmare. It's very time consuming if there are a lot of dependencies between the packages under development.

My suggestion is to make it simple for "npm install" to only install packages that aren't in the require() path thus needs to be installed. In my opinion this is more natural than using "npm link" for each package. The local packages we want to make changes to without having to re-publish we could just put the original or the symlink in node_modules to make it fetchable for node.js.

A flag for "npm install" could be used to just install packages that aren't fetchable thus it won't interfere with the current behavior.

**Comment by othiym23** [comment]
> I find that npm is contradicting how node.js require() behaves if it installs those libraries even though those are in node's require() path and thus are fetchable.

There's not really a contradiction here; npm is treating the presence of a local `package.json` as a declarative statement of where things should be installed that trumps the (simpler) strategy used by Node's module resolution algorithm. I think that npm usage has shifted over the last four or five years; once upon a time, it was common to be working directly within your `node_modules` directory, and this use case would have been far more common. These days, it's much more likely that you'll be operating pretty strictly at a top level, and only operating directly on subdirectories of `node_modules` (or using `npm explore`) when debugging.

With `npm@3`, which installs flat, deduplicated trees, adding functionality like this gets a lot more complex, because the tree is already being manipulated pretty heavily to take advantage of how the Node module resolution algorithm works in practice. The built-in deduplication gets a bunch of the disk and network savings you mention; that said, to take advantage of it, you need to be working at the package's root directory.

This is a sort of roundabout way of saying that this approach points down one path, while in the past few years npm has gone down another. Reconciling the two of them would be a bunch of work that seems pretty superfluous give current usage patterns and how `npm@3` is designed. As such, I'm going to close this. Thanks for your time and the thoughtful problem statement!
