### ISSUE TITLE
feature request: force install from cache.

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#2568]
```
npm install module --cache
```

would behave as if there is not network connection.

this would be very useful when the connection is slow, 
and you know the modules you are installing well.

it would also create the possibility for a background process that tails npm
and keeps your cache up to date. making installs super fast!

**Comment by ipuustin** [comment]
It would be great to get an update to this issue. Problem with `--cache-min 9999999` is that installing dependencies in a tree does not work: it expects packages to be installed in a flat hierarchy. In a perfect world I could add several packages in the cache and then install only one; the rest would be automatically used as dependencies to the top-level package.

**Comment by despairblue** [comment]
Using `--cache-min 999999` will also fail `npm install` whenever you install a package that depends on a newer version of a package you installed in the passed. Took me a while to figure out why that happened:

![screen shot 2015-12-18 at 23 05 38](https://cloud.githubusercontent.com/assets/927609/11908549/5a2b5f92-a5dd-11e5-9b95-a5f54e3fe5be.png)

**Comment by timoxley** [comment]
@despairblue Yep it's painful. Tracking that issue here https://github.com/npm/npm/issues/8581

**Comment by nicgirault** [comment]
Does someone understand what is the main purpose of the npm cache directory if running twice 'npm install package' generate two http requests?

**Comment by othiym23** [comment]
@nicgirault When packages are in the cache, the initial metadata request sends the cached etag for the package, and in the vast majority of cases, the registry will return a 304 and the package tarball won't need to be downloaded again.

**Comment by nicgirault** [comment]
@othiym23 thank you, your answer is clear.

**Comment by zachborboa** [comment]
This may now be relevant.
https://github.com/strongloop/loopback/issues/1079

**Comment by othiym23** [comment]
@zachborboa That's strictly an issue with StrongLoop's packages, and is unrelated to this issue.

**Comment by zachborboa** [comment]
@othiym23 I still think it is related. If the optional dependency were truly cached, they would only ever receive a single (analytics) ping for the specified version.

**Comment by othiym23** [comment]
That's not how the cache works, @zachborboa – it's always going to fire off a request to see if it has the latest version of a resource. Having an "offline" or "use the cache only" mode would prevent those network checks, and, barring what changes would come from making the cache content-addressable / read-through by fetching tarballs from the cache by their shasums, not the default mode for the cache, now or in the planned future. Discussion about how StrongLoop uses `optionalDependencies` belongs over there, and is not a part of this discussion.

**Comment by mriehema** [comment]
Adding `--offline` (=install from cache) would be nice.

**Comment by harish2704** [comment]
Hi, I wrote this simple module (https://github.com/harish2704/npm-offline-registry/blob/master/README.md)[https://github.com/harish2704/npm-offline-registry/blob/master/README.md] to address the same issue. 

Hope it will help some who is checking this thread

**Comment by othiym23** [comment]
See #12061 for some of the nuances about how the caching should allow matching against semver ranges, which I believe it doesn't currently do, due to its dependence on the registry for range matching.

**Comment by kvanrobbroeck** [comment]
In Maven, a download is only attempted if the required dependency version is not already in the cache. This way if you already downloaded an artifact before, it will always come from the cache, not requiring an internet connection at all.

**Comment by serbanghita** [comment]
@kvanrobbroeck IMHO that should be the default expected behavior from `npm`. I personally don't think there is a need to fire a HTTP request since you can check the dependency locally. I think every package manager should have an _offline first_ approach.

**Comment by despairblue** [comment]
This is not really possible because of semver ranges. There could always be
a newer patch release.

On Fri, Apr 22, 2016, 13:04 Serban Ghita <notifications@github.com> wrote:

> @kvanrobbroeck <https://github.com/kvanrobbroeck> IMHO that should be the
> default expected behavior from npm. I personally don't think there is a
> need to fire a HTTP request since you can check the dependency locally. I
> think every package manager should have an *offline first* approach.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/2568#issuecomment-213381167>
>
-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by dominictarr** [comment]
if there has been a newer publish in the semver range, that isn't in the cache, but the one in the cache is valid, then install the one in the cache.

**Comment by despairblue** [comment]
That could lead to security releases never making it to the end users. That's also another thing: deprecating packages. The package in your cache could have been deprecated by the author because it was seriously flawed in some way. You wouldn't know if npm did not check.

**Comment by KidkArolis** [comment]
We use shrinkwrap for all production systems anyways, so pkgs are already
locked to specific versions - you opt into security updates from time to
time. But even with shrinkwrap installations are very slow.

**Comment by dominictarr** [comment]
@despairblue always installing the new package could just as easily _introduce_ a security breakage.

**Comment by despairblue** [comment]
Depends on your semver range and how the project is maintained. Pinning
major and minor and installing the newest patch release should have a lower
chance of introducing a security flaw, though in theory it can, correct.
But this is another discussion.

The main problem is that maintainers can remove vulnerable packages or
deprecate unsupported ones. Npm will tell you that when you install it, but
only if it checks online. The package information is not immutable. That
makes caching hard.

Installing npm onsite can mitigate that, also the number of requests could
be reduced and even an offline switch can be introduced, but not checking
npm.com *by default* seems like a bad choice to me. Rather make it opt-in.

On Tue, Apr 26, 2016, 05:09 Dominic Tarr <notifications@github.com> wrote:

> @despairblue <https://github.com/despairblue> always installing the new
> package could just as easily *introduce* a security breakage.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/2568#issuecomment-214594033>
>
-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by dominictarr** [comment]
@despairblue no one is suggesting to make installs from cache the _default_, it's about making it _possible_ to install from the cache.

This has worked, and then been broken at various times, it's working relatively well right now.

**Comment by dominictarr** [comment]
it's ugly, but `npm install foo --cache-min 999999999` works.

**Comment by despairblue** [comment]
It was suggested just a couple of posts above. And your suggestion has a
minor flaw described on my comment a couple of months ago (when a dep
depends on a version of a package not in your cache). Answering from my
phone so linking is kind of hard.

Anyway, I think this is getting off topic. I didn't mean to suggest that
you wanted install from cache by default. :)

On Tue, Apr 26, 2016, 11:26 Dominic Tarr <notifications@github.com> wrote:

> it's ugly, but npm install foo --cache-min 999999999 works.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/2568#issuecomment-214681980>
>
-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by kvanrobbroeck** [comment]
I was pointing out that Maven does indeed install from the cache by default, and has done so since forever. Maven also supports semver-like negotiation, so I can't imagine that would be a big issue.

I do agree with the point that it should be possible to install purely from cache because it would increase flexibility in cases where you (temporarily) don't have an internet connection (plane, train, transients, ...).

I also think the argument to not make this the default but an opt-in (so unlike Maven), is sensible for a modern package manager in the "age of the internet", because that may indeed be better for security updates and things. If this is not desired you can still play with the semver wildcards i guess.

Finally I think this option should be explicitly named something like `--offline` (as already suggested) rather than the ugly `--cache-min` trick from a usability point of view.

**Comment by timoxley** [comment]
Good news related to this: There's now an open PR that purports to allow the `cache-min` trick to be used reliably https://github.com/npm/npm/pull/12084

**Comment by xealot** [comment]
While this thread has wandered slightly off topic, I think the cache-first approach has merit. I appreciate the desire for everyone to always get upgrades all the time without asking, but it *can* lead to new unexpected breakages. 

Would it be unreasonable to quickly install from the cache and then perhaps display a list of outdated modules on the summary page? **I think installing from cache should definitely be prioritized if there is an exact version specified in `package.json` which also exists in the cache.**

There is a lot of npm install pain in my organization because we typically work on dozens of modules simultaneously that have similar/exact requirements in common. Installing the same version of gulp six times in a row without any caching feels broken.

**Comment by noherczeg** [comment]
How is the progress regarding this issue? Cache priority would be much appreciated. Even a full blown recursive one time install force flag as well.

**Comment by cristian04** [comment]
+1 for this

**Comment by xandris** [comment]
I'm trying to have our build deploy to npm's cache and install from there, but it doesn't seem to work. The files end up in `~/.npm/foo/1.0.0`, but `npm install foo@1.0.0` still tries to contact the registry and fails. Is this use case possible with `npm install --cache-min=Infinity <name>`, or do we have to install from a tarball/directory?

**Comment by danshome** [comment]
This is still an issue.   I have cache-min set to 7200, then I go to packageA and and do an npm cache clean packageA, followed by an npm cache add packageA-0.0.1.tgz. I can see that the right version is in the local cache after the cache add because the timestamp was updated.  Then I go to packageB that has a dependency on packageA@0.0.1, but when I run npm install I can see looking at the cache that it still has the version I added to the cache, yet the version of packageA that packageB pulled down came directly from the registry, not only that, but it didn't even update the cache with what it pulled from the registry.

**Comment by hunterloftis** [comment]
Even with `--cache-min Infinity` npm checks etags on every module. The delta between a fully primed cache and an empty cache is pretty close to negligible (at least in the tests I've been running).

**Comment by danshome** [comment]
I'm so confused here.  What is the point of even having a local cache if you ignore it?  If I have my cache-min set to 7200, then I run the command "npm cache add packageA-0.0.2.tgz" to add version 0.0.2 of a module to my local cache, then if I switch over to build another package (packageB) that has a dependency packageA and build it, then as long as they share the same npm cache I would expect that packageB would have pulled the npm package for packageA from my local cache, but it doesn't, it always grabs it from my npm registry and ignores what's in the cache.

**Comment by MrGrande** [comment]
Hi, i'm struggling since days to create an "offline" usage of npm with the npm enterprise soution. But its not possible to install the packages from the cache. Even if they are cached by npm enterprise with their automatic whitelisting feature.

Background: I am working i a secured environment with limited internet access. Its not allowed to download any executable binary by the developers directly. Instead a developer has to ask for a package which must be checked for security issues (security department in the company) and after that it can be used/installed by the developers.

Does anybody know what could be the best solution in this case?

**Comment by andreineculau** [comment]
@MrGrande in a similar environment, what we do is three-fold

1. use `npm install --global-style xyz` and archive the `node_modules/xyz` artifact in your company's artifact store
2. grab artifacts from the store. you can simplify this by requiring your devs to have their `package.json` use only static version specifications so that known apriori to download e.g. store://xyz@1.2.3
3. since this can create a rather large `node_modules` folder, one can later (in a packaging/deployment step) use `npm dedupe` to restructure the folder and remove duplicates. FWIW we are actually using npm v2 because the newer versions mess things up for us.

YES, it's a mess!
We're looking at switching to yarn, as soon as the above features are implemented https://github.com/yarnpkg/yarn/issues/877 . Thanks in advance if you +1 the issue.

**Comment by MrGrande** [comment]
Hello @andreineculau, thanks for the fast answer. 

What do you mean with artifact store? 
Please, can you describe point 1 and 2 a bit better?
Is it possible to use the cached packages completely offline?

Yapp, yarn would be nice but it takes a while until we can use it in production.

Thanks!

**Comment by andreineculau** [comment]
@MrGrande a bit more in detail, point 1 would be implemented as parse package.json; loop through the dependencies and/or devDependencies and for each package and package version, you would install it in a temp folder with `--global-style`, zip and store the file.
This point 1 would be done whenever the package is vetted as ok bye the compliance team, etc.

point 2 would be implemented as parse once again package.json; loop through the dependencies and/or devDependencies and for each package and package version, check if `node_modules/xyz/package.json` says that the package is already installed; if not you would fetch the zip from wherever you stored it, unzip it inside the node_modules
This point 2 would replace your devs' "npm install" step.

Point 1 and 2 basically shortcircuits npm install altogether, allowing you to use only cached packages.

> "yarn would be nice but it takes a while until we can use it in production."

I have no idea what you just meant there because neither npm, nor yarn, nor any other package manager should be used in production, for anything, less alone installing software.

**Comment by MrGrande** [comment]
@andreineculau.. Thanks...I need to think about your solution, its sounds really complicated.

You're right, i ment yarn is new and needs time to provide all required features to be used instead of npm.

**Comment by MrGrande** [comment]
@andreineculau.. What do you think, is JFrog's Artifactory (https://www.jfrog.com/artifactory) a good solution for my problem? I havent tested it but they offer "Offline access to packages and metadata" in their feature list. I tried npm Enterprise but i am not able to fetch the packages from the cache.

My test case with npm Enterprise: I have a linux server running npme. The registry url is pointing to the npme server and i can see that packages are cached after a "npm install".
After that i removed all node_modules from my project, removed the internet acces for the npme server and tried another time "npm install" but it failed.
My thinking was that the developers can install the packages from the cache too, even if the server has no internet access at that moment.

**Comment by andreineculau** [comment]
@MrGrande I will reframe from more comments on the matter. Any good developer has more than enough info to get something working. On top of that, I don't want to participate in hijacking the thread even more.

**Comment by danshome** [comment]
@kvanrobbroeck @othiym23 @hunterloftis Why not just make the npm global cache work like every other cache--where locally cached assets are used until the asset has "expired". It's also important to note that E-Tag's can't always be depended on because in situations where requests are load-balanced across a cluster of webservers e-tags are often unset, so if npm is depending on e-tags exclusively, then that's probably a bad idea to begin with, E-tags can be used as a tool to improve caching performance, but you can't assume they will always be there, so you must fall back to the old Is-Modified-Since/Last-Modified approach.   

Here's the way it should work in my humble opinion (yes I realize this doesn't cover all the bases, this is just a simple example which today does not work).  Let's say I have --cache-min set to 5 minutes. Then I run the command "npm cache add packageA-0.0.2.tgz" to add version 0.0.2 of a module to my local cache, if I switch over to build another package (packageB) that has a dependency packageA and build it, then the first thing "npm install packageA@0.0.2" should do is simply check the timestamp on packageA in the global cache and if it's timestamp is within the last 5 minutes defined by --cache-min then there is no reason for npm to ever check the registry.  However, if 5 minutes has past, and npm has been requested to install the exact same version (ex. "npm install packageA@0.0.2"), then check the registry, sending If-Modified-Since/ If-Unmodified-Since AND If-Modified/If-None-Modified "IF" you have the E-tag, using the modified date/time of packageA in the global cache. If the server responds with a 304, then npm can proceed to use what's in the global cache, otherwise the server will respond with a 200 if the Last-Modified time on the server is later Is-Modified-Since/If-Unmodified-Since and npm can update the global cache with packageA@0.0.2 from the registry that has a newer modified time and can proceed to install the newer copy of packageA@0.0.2 that was in the registry.  Note the reason I mention both Is-Modified-Since/If-Unmodified-Since is only because I haven't debugged npm communications yet to see if it's doing a POST or GET.

**Comment by zkat** [comment]
npm5 supports this now through the `--offline` flag, which will error if the stuff you were trying to install isn't already in the cache.

You can also use `--prefer-offline` to use the cache as much as possible, and hit the network only when a dependency cannot otherwise be fulfilled.

**Comment by ruyadorno** [comment]
that was a long and crazy ride, thanks for the update @zkat ❤️

**Comment by danshome** [comment]
Question.  So does this now work like maven, where it will compare the
checksum of the cached version found in the local cache against the
checksum in the repository before it wastes any time refreshing the copy in
the cache?  For example, if the version hasn’t changed, yet the checksums
were different then it would download a fresh copy, but if the versions
where the same and the checksums were the same then it would avoid the
download? If the versions were different, then I would expect  This is
important when you are doing remote builds over a slow connection, because
there’s no point in downloading if the checksums match.

--

Thanks,

Dan

**Comment by zkat** [comment]
@danshome if you have a package-lock.json, yes. npm will not touch the network *at all* if you have a `package-lock.json` and a warm cache, unless you have git dependencies (that's coming, too). You don't need to do anything special for this: it'll Just Work™ with no extra settings/flags.

**Comment by javarch** [comment]
Ich werde ab  28.06.2017 nicht im Büro sein. Ich kehre zurück am
04.07.2017.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [npm/npm] feature request: force install from cache. (#2568)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2017 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by vog** [comment]
Could anyone remove the content-less comment of @javarch, please? This is nothing but an out-of-office message from an email auto-responder in German language.

**Comment by tommedema** [comment]
@zkat why is `--prefer-offline` not a default option? seems to make more sense than to redownload something that is already on disk

**Comment by zkat** [comment]
@tommedema because I think you're misunderstanding how `--prefer-offline` works.

Again, if you've previously downloaded the package, and the previously downloaded version is also the latest version, you don't download anything at all.

What `--prefer-offline` does is mainly prevent the 304 checks for the latest versions of a package: that is, if you do `npm i foo`, you want to make sure the latest version of that is what's installed. Those are the semantics people are used to. With `--prefer-offline`, you'll never even check if there's an up to date version, so unless you specify `npm i foo@5.4.3`, you'll never get that version.

Tarballs are only ever downloaded once if they're already cached. We don't even do 304 checks for those if we have integrity information for them. And yes, this is the case even if you don't have a `package-lock.json`.

So to answer your question in bullet points:
* because `--prefer-offline` breaks expected semantics for users by always giving them maximally-stale data.
* because `--prefer-offline` does not have any effect on whether a tarball is re-downloaded.
* because the only network access `--prefer-offline` prevents you from doing consistently is 304 checks **for package medatata** (**NOT** tarballs).
* because the network access `--prefer-offline` limits is relatively negligible, and is only useful when you're in network situations where you have data caps (because the requests are so small, they're unlikely to have much of an effect on **speed** at all). Seriously, the only reason I put the option in is for users in places like Australia, or people using cellular routers.
* because in 99% of cases for users installing with a `package-lock.json`, `--prefer-offline` is a NOOP and will do absolutely nothing whatsoever of value for you. At all. Nada. Zilch. Nothing.

**Comment by zkat** [comment]
And for the sake of it, I want to clarify the point of `--offline` as well:

* `npm@5` will **automatically** install from cache if it doesn't detect network, or if your router lacks external access. So if you want to use npm on a plane, you can just use it. You don't need `--offline`. It'll Just Work™.
* `--offline` will ONLY be useful when you want to **guarantee** that no network access is done, and you want npm to crash when it doesn't have something in cache (this does **not** include git dependencies right now). So, this is what you use if you've hit your data cap and want to make damn sure npm doesn't suck up more data. Or, like, if you're temporarily tethering off your phone.

**Comment by tommedema** [comment]
@zkat that makes perfect sense, thanks for the elaborate explanation. Much appreciated

**Comment by acklenx** [comment]
I love the explanations and the described behavior. I am of course here because it is not what I observe. 

>$ **npm -v** 
>5.6.0
>$ **npm install puppeteer --prefer-offline**
>
> > puppeteer@1.3.0 install /home/acklenx/temp/node_modules/puppeteer
> > node install.js
>
>_Downloading_ Chromium r549031 - **97 Mb** [====================] 100% 0.0s 
>Chromium downloaded to /home/acklenx/temp/node_modules/puppeteer/.local-chromium/linux-549031
>+ puppeteer@1.3.0
>updated 1 package in # **56.38s**



And it does the same big, slow, download when I repeat the command, with or without the --prefer-offline

Is there a setting that I missed to enable this awesome caching behavior that I have desperately wanted for years?

**Comment by jalcine** [comment]
In the case of Puppeteer, you'd have to pass in PUPPETEER_SKIP_CHROMIUM_DOWNLOAD as an environment value (either setting it globally or that particular project).

This is noted in their install.js file here: https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L19
What would be nice is if Puppeteer's installation script had a way of observing / respecting this when it was run.

**Comment by jalcine** [comment]
Just highlighting @ackalker, that's an issue of both Puppeteer not respecting/checking for NPM/Yarn offline checks and you potentially not checking the docs for Puppeteer ;) https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables

**Comment by acklenx** [comment]
:)  Thank you.  I did not check the docs well enough.  I really wanted the npm behavior for all things installed with npm ;) -  ( where puppeteer would check for a new version of chrome and pull it if it's newer than the cached version).  I doesn't look like the environment variable offers that kind of flexibility - it's all or nothing.

Terribly sorry to bother you with my own failure to read (on a closed issue no less).

**Comment by zkat** [comment]
@acklenx puppeteer itself can hook into this behavior by checking for `npm_config_prefer_offline`, `npm_config_prefer_online`, and `npm_config_offline` environment variables (`process.env`), when running this install. That way, they can integrate their install script with npm's own behavior (on npm5 and later).

**Comment by ORESoftware** [comment]
is there a way to configure NPM to use some packages from the cache and some packages from the registry? looking to this for local development instead of `npm link`.
