### ISSUE TITLE
npm search [terms] --last-updated=YYYY-MM-DD

### ISSUE THREAD

**Issue by Zearin** [npm/npm#2844]
# Feature Request
I’d love the ability to filter search results so that über-old packages aren’t displayed.  

## Rationale
I’ve had a lot of bad luck searching for packages with very relevant descriptions, but which don’t work because they are outdated.  Relying on outdated versions of Node.js itself and outdated versions of other popular npm packages are both a problem.

## Suggestions for Invocation
* `npm search [terms] --last-updated=YYYY-MM-DD` 
* `npm search [terms] --last-updated=#y[#m[#d]]`

**Comment by othiym23** [comment]
There are two reasons why we're going to close this issue (and neither of them are because this is a bad idea!):

1. The current search implementation used by the CLI is unacceptable. It's grossly inefficient and, while it's sorta flexible, is hard to extend for feature requests like this one. npm, Inc. intends to provide a search service that is much more flexible, and can be used by both the CLI and the web site.
2. Although npm's engineering team wants to fix this, we're not going to have time to get to it in the next 6-12 months. When we _do_ come back to search, whenever that is, we're basically going to design the interface from the ground up, and features like this will definitely be on the table.

Because we're not going to get to this in the next year, I'm closing this feature request. Thanks for your time!
