### ISSUE TITLE
Cannot install private modules on Solaris

### ISSUE THREAD

**Issue by deepwell** [npm/npm#2961]
Any combination of command line install or package.json install of a private module from github (probably other too) does not work on Solaris. These exact same commands work just fine on Mac OS X.

BTW: I have "private": true  in both project's package.json files.

Example commands:
```
npm install git+ssh://git@github.com:mycompany/module-name.git
npm install https://un:pw@github.com/mycompany/module-name/archive/v0.1.1.tar.gz
```

Output
```
npm http GET https://registry.npmjs.org/module-name/0.1.1
npm http 404 https://registry.npmjs.org/module-name/0.1.1
npm ERR! 404 'module-name' is not in the npm registry.
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.  If you must, redact any confidential information with an obvious mark e.g. **REDACTED**

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.1.66. Can you try updating your node and npm installation?

A good overall guide to upgrading `node` and `npm` can be found here: https://github.com/npm/npm/wiki/Troubleshooting

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by deepwell** [comment]
We don't use Solaris anymore so I cannot confirm or deny if it still exists.

**Comment by othiym23** [comment]
Closing as abandoned.
