### ISSUE TITLE
error message for cache error

### ISSUE THREAD

**Issue by Zearin** [npm/npm#2988]
I recently encountered the issue described at #2773.  That issue page helped me solve the issue (thanks! :smile:).  

It occurred to me that even though the solution is very simple, the solution isn’t necessarily obvious.  When I first encountered the error, it **did** occur to me to `sudo npm cache clean`.  What didn’t occur to me was to remove `~/tmp` as well.  

I wonder if npm could, upon encountering this error:

* check for the existence of `~/tmp`
* check for any permissions issues in npm’s cache
* make some suggestions after the normal error message based on these checks

**Comment by othiym23** [comment]
I've attached `patch-welcome` to this issue, because it would be useful for people who are upgrading from old versions of the npm CLI (which wasn't consistent about how it handled permissions when run under sudo). At the same time, the CLI team isn't going to have time to get to this issue in the next 6-12 months, so I'm closing the feature request. If somebody happens across this and wants to implement it, the CLI team will help them get it merged and included in the release. Thanks for your time!
