### ISSUE TITLE
npm fetch

### ISSUE THREAD

**Issue by kkragenbrink** [npm/npm#3153]
It would be incredibly useful to have a command which can fetch node modules from the registry, but not attempt to compile them.  For example, if my code requires hiredis, and I bundle my code as a tarball on a server that does not have redis installed, it's not reasonable to try and compile hiredis on that server (especially since that server is not meant to deploy the app; only to bundle it).  Then, later, npm rebuild can be used to actually compile the hiredis package on my deployment server (which does have redis).

**Comment by smikes** [comment]
Is this still a problem for you?

I think @robertkowalski pointed out a module that does this: https://github.com/ForbesLindesay/npm-fetch 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by kkragenbrink** [comment]
An NPM module really definitely does not solve the issue, since I have to install it to fetch the rest. So then I have to do npm install npm-fetch to even have access to use it in the first place.   Really kinda ridiculous as a solution.

**Comment by smikes** [comment]
Sorry, I think I misunderstood your use case.  Is it like this:

server A (bundling):
  - does not have all target software on it
  - creates a bundled package

server B (target):
   - does not have access to `npm` registry

In that case, I see that you have no obvious way of bundling a module on A that can be installed on B.

Some possible workarounds include:

1. instead of using `bundleDependencies`, download and include the tarballs in a `faux-bundle` and then locally install them with a `postinstall` script

2. manually install using --ignore-scripts (which will include dependencies, but not run any scripts) and then manually create a tarball containing the contents of the package directory + node_modules, and execute `npm rebuild` after extracting on the target server

And of course
_3. install the missing dependencies on server A

What workarounds are you using now?  What would `npm` have to do in order to provide the functionality you're asking for here?

**Comment by smikes** [comment]
Hey @kkragenbrink, can you tell me more about your use case?  I'm assuming that you have one machine that **can** access the registry (where you would presumably be able to install and use `npm-fetch`) and another machine where you **cannot** access the registry but can compile the necessary modules.  Is that right?

**Comment by othiym23** [comment]
A really simple and dumb way to solve the "download on one host, run `node-gyp` on another" problem is simply to do a full npm install into a Git-tracked repository and then just check in the whole tree. What would `npm fetch` do that's different from that? I can imagine many different ways a `npm fetch` might work, and most of them start getting really complicated when I think about how that all plays out with nested dependency trees.

**Comment by othiym23** [comment]
Closing in favor of #6529, which has a similar discussion of the issues involved. Thanks for your time (and patience)!
