### ISSUE TITLE
The npm global flag seems to be inconsistent on Windows

### ISSUE THREAD

**Issue by MiguelMadero** [npm/npm#3155]
I posted a question on [SO](http://stackoverflow.com/questions/14846111/npm-global-seems-to-be-inconsistent-on-windows), but I wanted to repost here since this might be an issue and not so much a question.

**Comment by smikes** [comment]
This looks like more than just a support issue, but I am not sure whether it's better to call it a `bug` or `feature-request`.  I know we have recently run into APPDATA-related issues with current (0.10.36) node and npm packaging.

If you had complete discretion to set these values up most usefully for the "standard Windows node user" -- i.e., someone who is using Visual Studio, cmd, and msysgit -- how would these variables be set, and what would be the permissions on these directories?

/cc @othiym23 in case you have anything to add?

**Comment by othiym23** [comment]
This issue was addressed in a8da8d6e0cd56d97728c0b76b51604ee06ef6264, and has not been a problem since 2.1.4, so I'm going to go ahead and close this as resolved. At some point, we need to figure out a better way to centrally configure npm on Windows, but all fresh installs of npm should correctly carry this configuration from one install of npm to the next.
