### ISSUE TITLE
dependencies <> peerDependencies, dependencies seems wrong

### ISSUE THREAD

**Issue by quenenni** [npm/npm#3314]
npm 1.2.16
etherpad-lite: 1.2.91

From a discussion here https://github.com/ether/etherpad-lite/issues/1647

A plugin can have "dependencies" and?/or "peerDependencies" in their packages.json in order for them to have other plugins installed.

* "peerDependencies" (already like this)<br>
  - If the dependency plugin is not already installed, npm installs it inside the node_modules dir of the plugin. 
If plugin X needs plugin Y, plugin Y will be installed in node_modules/X/node_modules/Y<br>
In that case, Y won't be list as an installed plugin and won't be seen in the pad (if ie, that Y plugin adds something in the page like a button, .. that's good imo, as devs must know what they are doing)<br>
  - If plugin Y was already installed, npm doesn't install it a second time (well maybe npm updates if the versions aren't the same, I didn't test that).<br>
* "dependencies" (not already like this)<br>
If plugin X depends on plugin Y, then Y should be installed as a plugin of the pad and not as a subplugin of the plugin X<br>
The tests I made show that in this case, Y is installed also inside the node_modules dir of the plugin X (if not already installed itself as a plugin) and is listed as an installed plugin but can not be uninstall<br>
But, more important, in this case, the plugin X won't work.<br>
(I had to manually copy the plugin Y into the node_modules dir of EPL)<br>
Another solution, for now, is to install the plugin Y first, then the plugin X. Then X will work without any further manipulation.

I don't know how it's suppose to work, I understand it's quite a tricky matter, but there should be a difference between "dependencies" and "peerDependencies" that do not really currently exist except that "dependencies" make plugins to not work.

**Comment by othiym23** [comment]
#6565 pressed the reset button on how `peerDependencies` work for `npm@3`, and the new behavior is much simpler: if you want a thing installed, put it in `dependencies`; if a package needs a peer, add it to `peerDependencies`, where it will warn instead of erroring when said `peerDependencies` are missing. This is slightly different from what's discussed here, but the new behavior is sufficiently different that I think it justifies closing this issue as either resolved or rendered irrelevant. Thanks to all for their time and patience!
