### ISSUE TITLE
Canonicalize npm-shrinkwrap.json file contents for easier diffing

### ISSUE THREAD

**Issue by derekcicerone** [npm/npm#3398]
The shrinkwrap.json files currently seem to output modules somewhat randomly.  It would be nice to have them canonicalized somehow (perhaps just by sorting the modules alphabetically by name) so that the file can be easily diffed to prior versions when the dependencies are updated.

**Comment by OliverJAsh** [comment]
I don't seem to have an issue with ordering, but the metadata does appear to change every time someone on the project runs shrinkwrap, making it very difficult to read the diff. This time it was `from` changing from `"serve-static@1.2.3"` to `"https://registry.npmjs.org/serve-static/-/serve-static-1.2.3.tgz"`.

**Comment by pseidemann** [comment]
my npm version is 2.15.1 with node 4.4.2 and if I just run `npm shrinkwrap` twice without changing anything, the file will be different every time.
it seems like the order of the packages is random and need some clear sorting. this makes the whole feature almost useless because it's impossible to follow changes properly in git.
would it be possible to implement some node script which will sanitize the json file after shrinkwrap has run?

**Comment by othiym23** [comment]
As of the most recent version of `npm@3` (going into `npm@next` today), we should have eliminated the last source of nondeterminism in `npm-shrinkwrap.json` across runs. We probably won't ever backport this feature to `npm@2`, because it's merely churn in a generated file and not an actual bug or security flaw; at this point, if you want these kinds of fixes, you need to update to `npm@3`.

That said, there will be some further changes to shrinkwrap soon to incorporate support for shasums, and when we do that we may eliminate one or both of `from` and `version` as redundant if `resolved` and `shasum` are available (not to say that we won't use them if they're there). However, the team believes that with the changes in `npm@3`, this issue is resolved. Thanks to all for your time and patience!
