### ISSUE TITLE
Version range descriptors in dependencies do not allow mixing version identifiers with URLs

### ISSUE THREAD

**Issue by justin-lau** [npm/npm#3416]
Suppose there is a package which has the greatest version of 2.0.0. However there is a bug slipped through the unit tests, and I have to fork it and made a fix. The fix is submitted to the upstream as a pull request, but it is not merged to the upstream repository yet. In my repository, the package.json is updated to version 2.0.1 and a tag v2.0.1 was created to point to this latest commit.

Now I wanted one of my projects to work with this major version because of the nice new features, but it can't live without the bugs being fixed. Whenever I re-install the dependencies, I'd like it to install from the original package as much as possible, while skipping the bugged version of 2.0.0 and fall back to my forked and fixed version.

When trying to implement this dependencies behavior, I tried the following version range descriptors:

```javascript
// Works, installed 2.0.0
"2.0.0"
"2.x.x"

// Expected error: No compatible version found 
">2.0.0"

// Works, install >2.0.0 whenever it is available,
// or fallback to 1.x.x otherwise
">2.0.0 || 1.x.x"

// Works, installed 2.0.1 from my forked repository
"git://github.com/me/project.git#v2.0.1"
"https://github.com/me/project/archive/v2.0.1.tar.gz"

// Error: No compatible version found: package@'>2.0.0'
">2.0.0 || git://github.com/me/project.git#v2.0.1"
">2.0.0 || https://github.com/me/project/archive/v2.0.1.tar.gz"
```

This disallow falling back to URL with incompatible version numbers.

I'm not sure if this is considered a bug, but I guess it'd be a nice-to-have feature if it isn't.

**Comment by othiym23** [comment]
The grammar for what can be put in a dependency isn’t documented this way, but there are three productions that can go in the dependency:

1. a semver range, a la `^2.0.5`, `>=8.0.8`, `*`, or `2.3.x || 3`
2. a URL, either to a remote tarball, or a local package path
3. shorthand syntax for hosted Git repos, a la `othiym23/eliminate-5082`, `bitbucket:cool-org/cool-repo`, or `gist:deadbeeffeed`.

What you’re proposing essentially conflates 1 and 2 into a new kind of expression. You describe the problem you’re trying to solve well, but there are a few reasons why I think this isn’t going to fly:

- There’s an enormous backwards compatibility problem here, which is that packages published using this syntax wouldn’t be installable by the vast majority of extant npm clients, and there’s no way to desugar this kind of expression into a syntax that _would_ work with those clients at publish time. This is, on its own, enough to render this proposal moot.
- It adds a new parser into the mix, because the underlying code the CLI uses to determine what kind of dependency it’s trying to install uses pre-existing parsers and regexps to tease apart 1-3 above.
- It’s not actually a good idea to introduce this kind of mode-switching into the dependency model, because it exposes a new set of edge cases and a new, more complicated model for thinking about how dependencies are resolved for users.

For those reasons, we’re not going to make (or accept) changes along these lines. That said, I appreciate the clarity of your description of the problem, and thanks for that and for your time!
