### ISSUE TITLE
npm doesn't follow "registry" on dependencies

### ISSUE THREAD

**Issue by robey** [npm/npm#3532]
I set up my own NPM registry for a single package, following the CommonJS page, and using static json files. I wanted to redirect all dependencies to the npmjs.org registry, but the "registry" key didn't work on either individual dependencies, or at the top-level. I assume it's just not implemented yet, but here's a bug report claiming that for at least one person, it would be useful. :)

(My current workaround is to have apache generate a redirect to npmjs for any package request other than mine.)

**Comment by othiym23** [comment]
@robey You're right that that paragraph (which is still there today) is misleading with respect to npm's registry being conformant to the CommonJS standard, but I think at this point it's pretty unlikely that that's going to change, given the changes that npm has in mind for the registry (and the CommonJS registry spec being effectively a dead letter). Since our conformance isn't going to change, the docs probably should, so a patch submitted to the [docs page](https://github.com/npm/npm/blob/master/doc/misc/npm-registry.md) would be very much appreciated. (Actually, that whole page should probably be pulled from the CLI's documentation, don't you think, @ashleygwilliams?)

The CLI team isn't going to have time to do this ourselves, so I'm going to close this, but the `patch-welcome` label implies that we'll support anyone who decides to take this on. Thanks for your patience and time, Robey!
