### ISSUE TITLE
--save should create package.json

### ISSUE THREAD

**Issue by felixrabe** [npm/npm#3576]
Verified on 1.2.30.

I'd like `npm install --save` to always create a `package.json` file if it does not exist.

I use the following as a workaround when starting a new project:

```
mkdir new-project
cd new-project
echo '{}' > package.json
npm install some-package --save
```

I would love to be able to skip that `echo` step.

**Comment by ExplodingCabbage** [comment]
> It would be reasonable for --save to issue an error if there were no package.json (and you'd rather not have it create one), but failing silently is weird.

I agree. Bower's current approach seems to be to issue a warning:

<pre><code>$ <i>./bower install angular</i>
bower angular#*                 cached git://github.com/angular/bower-angular.git#1.3.13
bower angular#*               validate 1.3.13 against git://github.com/angular/bower-angular.git#*
bower angular#~1.3.13          install angular#1.3.13

angular#1.3.13 bower_components/angular
$ <i>rm -rf bower_components/</i>
$ <i>./bower install angular --save</i>
bower angular#*                 cached git://github.com/angular/bower-angular.git#1.3.13
bower angular#*               validate 1.3.13 against git://github.com/angular/bower-angular.git#*
bower angular#~1.3.13          install angular#1.3.13
<b>bower                          no-json No bower.json file to save to, use bower init to create one</b>

angular#1.3.13 bower_components/angular</code></pre>

Having the message be an outright error seems better still.

**Comment by SteveALee** [comment]
> What's the point of a save flag if it doesn't save anything?

+1 (even though issue is closed)
As a relative newbie this really confused me

**Comment by b-long** [comment]
+1
At the very least, a warning should be added.  I agree with @felixrabe @ExplodingCabbage @SteveALee and others.  If no `package.json` is found up the hierarchy, why not just implement the as `echo '{}' > package.json` ?

**Comment by othiym23** [comment]
If somebody wants to put together a patch to do the equivalent of running `npm init -y` when `--save` is used in a package tree without a `package.json` file, I'd be happy to review it. The CLI team themselves aren't going to have time to work on this any time soon.

**Comment by peey** [comment]
Creation of a new `package.json` file in current directory when there exists a `package.json` file up the hierarchy may confuse existing users, because their intent would be to save to the package.json that exists up the hierarchy and not in the current directory. 

Instead of changing default behavior of `--save`, how about an explicit `npm install <package> --save --currdir` or some other new flag of a suitable name that makes it explicit that it should be saved to current directory's `package.json`, and if that does not exist then it should be created.

The same flag could also be used in other operations `npm install <package> --currdir` to save to current directory rather than looking for a `node_modules` folder up the hierarchy.

**Comment by felixrabe** [comment]
To clarify, I actually meant generating the `package.json` if it does not exist in the current directory _and_ does not exist in any parent directories.

**Comment by bytenel** [comment]
+1!

**Comment by esd100** [comment]
Is this still an open issue? I just downloaded node for the first time and am very unclear as to why I get a warning about package.json not existing, if I am installing a package. Can anyone advise? It is very unclear how a 1st time user is supposed to know what to do.

**Comment by dotnetCarpenter** [comment]
@esd100 well it depends on what you're trying to do? This issue is about making it convenient to install and save some npm modules without filling out an entire `package.json`, when you don't plan to publish your project as a npm module.

1. If you have an existing project which depends on npm modules, you do `npm install`
2. If you want to start a new project, you can do `npm init` and get a `package.json`
3. If you just need to use node then you do `node [path/name to js file you want to execute]`
4. If you want to start a new project and don't ever want to publish it as a npm module you can use this hack: 
```
echo '{}' > package.json
npm install some-package --save
```

bonus info: `npm i` is a shortcut for `npm install`
`npm i` install all modules defined in your `package.json` under `dependencies: {` and `dev-dependencies: {`

**Comment by csaftoiu** [comment]
I agree, `npm install --save` and `npm install --save-dev` should create a minimal `package.json`. I'm using `bower` to distribute, but I need `npm` to install `grunt`. I don't plan on distributing the package with `npm`. I suggest it creates a minimal file, like e.g. after running `npm install --save-dev grunt` from a dir with no `package.json`, it should output something like "Creating package.json to track dependencies..." and produce a `package.json` like:

```
{
  "name": <the directory name>,
  "private": true,
  "devDependencies": {
    "grunt": "^1.0.1"
  },
  "engines": {},
  "scripts": {},
  "dependencies": {}
}
```

**Comment by bimalpaul** [comment]
:+1:
