### ISSUE TITLE
npm install based on node engine version

### ISSUE THREAD

**Issue by trevnorris** [npm/npm#3662]
Tried posting this to the mailing list, but it was being a bastard.

Because of the complex changes to the v8 API recently I was thinking it would be nice to allow "npm install" to automatically install the latest version of the package based on the latest supported node engine.

This way I could maintain two branches of my project, One could have something like

```
{ "engines": { "node": ">= 0.10.0 <0.11.0" }}
```

and the other

```
{ "engines": { "node": ">= 0.11.0" }}
```

publish each of those to different minor versions, and npm could figure out which minor version to use automatically based on what version of node I'm using to get the package.

Feasibility for a feature like this?

**Comment by othiym23** [comment]
Since there was last serious discussion on this feature request, the CLI team has [removed `engineStrict`](https://github.com/npm/npm/commit/2875ba3) from the CLI because it caused more problems than it solved. That said, this would still be a very useful feature for packages like the ones @trevnorris describes up top – packages that include native modules that are tied closely to the underlying V8 API, or that get out at the mutable edges of what `nan` provides.

To me, this feels like a problem that's external to npm itself, because it moves beyond the SemVer range-matching at the core of the install algorithm, and forces the installer to take into account other factors. The way this is done in practice right now is ad hoc scripts (like those used by the `phantomjs` installer) or using a tool like `node-pre-gyp` to get a prebuilt artifact for a give OS / architecture. This is even more general than that, because potentially you could get a completely different version of a package depending on what version of Node you're running.

I'm not opposed to integrating this functionality on principle, but it brings a set of concerns that are more familiar to me from OS distribution package managers than language-based package managers like npm, and the amount of complexity it adds is somewhat daunting, if you want to avoid `engineStrict`-style footguns / edge cases. Therefore, I've added `needs-discussion` to this, because I'm not sure how best to implement this, and I'm not ready to review changes to npm that do implement it until there's more of a consensus around how to do it. (An excellent way to drive to that consensus would be to write something that puts its data in `package.json` and run outside of npm.)

**Comment by trevnorris** [comment]
@othiym23 There are really only one of two ways I see it working exactly as I'd like. Either devs properly list supported module versions (which has shown not to be the case) or npm runs a giant test farm to test modules against all supported versions of node and catalogs which do/don't. Don't see either happening.

So how about a `maybeEngineStrict` that attempts to do the right thing and if it can't prints out a warning message like "no supported version found. either the module needs an update or the author doesn't know how to properly specify the supported range. please contact them." then installs package that it normally would.

**Comment by 19h** [comment]
That is a very interesting way of increasing issue-resolve KPIs.
