### ISSUE TITLE
Support for implicit symlinks (non-hard!)

### ISSUE THREAD

**Issue by KenanSulayman** [npm/npm#3663]
So we're working on many modules concurrently. And before we publish an open-source module which is used by our commercial product, we're testing it in our commercial product (obviously). It's a hell of a pain to copy files over and over just for the sake of ***good lord, work already*** — thus we'd like to link our open-source module (say it's located at ~/Developer/module) as a module of the commercial product (~/Developer/product/node_modules/module -> ~/Developer/module). 

This fails currently. Namely: 

/Volumes/…/(product)/node_modules/(product):1
(function (exports, require, module, __filename, __dirname) { book
                                                                  ^
SyntaxError: Unexpected token ILLEGAL [(product)]
  => (module.js:439:25)
  => (module.js:474:10)
   => (module.js:356:32)
    => (module.js:312:12)
     => (module.js:364:17)
      => (module.js:380:17)

This is when we try to do: require("(module)") from (product) after node_modules/(module) is a symlink to ~/Developer/(module).

Specifications:
$ node -v
***v0.10.13***
$ npm -v
***1.3.2***
$ uname -v
***Darwin Kernel Version 13.0.0: Tue Jul  2 15:57:48 PDT 2013; root:xnu-2422.1.35~2/RELEASE_X86_64***

**Comment by othiym23** [comment]
Taking another look at this, it seems to me that what you want is something along the lines of [`linklocal`](https://www.npmjs.com/package/linklocal) or [the local dependencies feature](https://docs.npmjs.com/files/package.json#local-paths) introduced in `npm@2`. The former gets rid of the layer of indirection that you dislike (I think – I had a little difficulty parsing your description of "reflection", because the way those arrows are drawn doesn't make sense to me), the latter performs direct installations of packages somewhere else on the current machine, which gives you more control over when those changed dependencies are pulled in.

The CLI team has discussed simplifying / improving how links and / or local dependencies are implemented, but we don't have any plans to address that within the next year. That, in combination with the fact that I think / hope that one of the two aforementioned solutions will simplify your workflow, is leading me to close this issue. Thanks for your time and patience, and I hope you find those tools useful!
