### ISSUE TITLE
npm updated the uglify-js package to an older version 

### ISSUE THREAD

**Issue by mzgol** [npm/npm#3682]
The `uglify-js` npm package has just published version `1.3.5`. This is a maintenance release, I've had the package installed globally in version `2.3.x`. So far. For an unknown reason, npm "updated" my `2.3.x` package to the obsolete `1.3.5`. I had to uninstall and install the package again to get the "old" new version back.

I have `npm` version `1.3.2`, node.js version `0.10.13`.

**Comment by smikes** [comment]
Is this still a problem for you?

It sounds like (based on @donpark 's analysis) that this may have been caused by inconsistent views of the registry.  Have you seen this problem lately?  The registry was rewritten and rehosted early in 2014.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by mzgol** [comment]
I haven't seen this problem lately, I'm closing this one then. Thanks!
