### ISSUE TITLE
update and outdated should be shrinkwrap-aware

### ISSUE THREAD

**Issue by CrabDude** [npm/npm#3816]
We have some necessary fixes to the [request](https://github.com/mikeal/request) module's [forever-agent](https://github.com/mikeal/forever-agent) dependency. These fixes require us to fork forever-agent, but not request. We used `npm-shrinkwrap.json` to use _our_ forever-agent instead:

``` javascript
{
  "name": "foo",
  "version": "0.0.1",
  "dependencies": {
    "request": {
      "version": "2.21.0",
      "from": "request@2.21.0",
      "dependencies": {
        "forever-agent": {
          "version": "0.5.0",
          "from": "git+ssh://git@github.com:Bar/forever-agent.git"
        }
      }
    }
  }
}
```

This approach works when `npm install` is run, but `npm update` fails to update forever-agent to HEAD. 
1. Why?
2. We don't want to have to run a private npm repo for such a simple use case, and ideally don't want to fork request since we're not altering it in any way. Is there another way to accomplish this?

**Comment by othiym23** [comment]
1. As you deduced, `npm update` doesn't pay attention to shrinkwrap. Maybe it should! Unifying the behavior of `install` and `update` more is something the CLI team, or at least I, would like to see happen. To do this would probably require factoring out the shrinkwrap behavior into a separate phase or overlay on the installer process so it could be applied to `outdated` as well, which is a little tricky because of shrinkwrap's design.
2. Also, `npm update` doesn't do anything with Git dependencies in `npm@3`. There is a separate feature request outstanding (#8055) for fixing this, but in this case, it still won't pick up on the values set in `npm-shrinkwrap.json`.
3. With `npm@3`, if the commit sha changes, it _will_ be picked up by the install process when running `npm install`, but it's still not going to get picked up by `npm update`.

That said, making `npm update` and `npm outdated` aware of shrinkwrap files is something that I, at least, would like to see happen, so I'm going to retitle this to match that request, and put it on the docket of things for the CLI team to address when we work on shrinkwrap to make it better fulfill user needs, which is a project on the roadmap to happen within the next 6-12 months. Thanks for your time and the thoughtful problem description!
