### ISSUE TITLE
npm install - Fails uninformatively

### ISSUE THREAD

**Issue by globalcitizen** [npm/npm#3906]
As per https://github.com/joyent/node/issues/6239

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like the `npm` registry was down at the time you were trying to install.  Uptime has been improved quite a bit since 2013, though I'm not sure that the message is any more informative.

Have you seen this problem in the meantime?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
