### ISSUE TITLE
Is `npm build .` a feature or a bug?

### ISSUE THREAD

**Issue by indexzero** [npm/npm#3927]
@isaacs I remember years ago there was an outstanding issue (that was fixed) for the same problem in `npm link`. That is, you decided that the `.` in:

```
npm link .
```

was unnecessary and now we can all run:

```
npm link
```

The same exists now for `npm build` (I need the `.`). Is this intended? Obviously low priority.

**Comment by joaomilho** [comment]
Can you explain why `npm build` "do nothing and have no output"?

**Comment by DullReferenceException** [comment]
This has bit me and teammates multiple times. `npm build` is one of those things you'd expect to just work, like `npm test`. The fact that it does nothing, outputs nothing, and succeeds can cause interesting issues. For example, I recently had this fun thing in my `package.json`:

```
{
  "...": "...",
  "scripts": {
    "build": "babel --out-dir ./lib src",
    "prepublish": "npm build"
  }
}
```

This bug caused me a lot of head-scratching when my code changes weren't reflected after doing an `npm publish` and `npm install`. Since `npm build` does nothing but still succeeds, `prepublish` didn't do anything, and the published lib code was not the latest transpiled code.

Would it be unreasonable to either have `npm build` do the same thing as `npm run build`, or alternatively have it output an error and fail with an exit code?

**Comment by lennym** [comment]
We've just spent "some time" trying to get to the bottom of something similar. It would be good to have a warning if `npm build` is called with no arguments when a `build` script is defined in package.json.

Happy to put together a PR if it helps.
