### ISSUE TITLE
new command, npm add

### ISSUE THREAD

**Issue by tkellen** [npm/npm#3995]
It would be nice if you could wield all the power of `npm install` as it pertains to automatically updating package.json files for `peerDependencies` 

I submitted a PR adding support for `--save-peer` (https://github.com/isaacs/npm/pull/3994) and @domenic rightly pointed out that it doesn't exactly make sense in this context.

What about a new command, `npm add` which does nothing but update the package.json?

**Comment by kevin-smets** [comment]
Any advancements on this? I would like to cut down the manual managing of peer dependencies as well frankly...

**Comment by othiym23** [comment]
With the changes to `peerDependencies` in `npm@3`, since `peerDependencies` aren't implicitly installed any more, this becomes even more useful. It would also be useful to manipulate `bundledDependencies` without having to install anything, so `npm <add> --bundle` would be helpful as well. I'm super not sold on the command name, but we can figure that out later.

Also, this has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
While the CLI team would like to have a general-purpose command-line API for editing `package.json`, this command, as defined, is too narrow in scope and has too many awkward aspects from a usability perspective to make sense. As such, I’m going to close the issue, but with the caveat that we still want the more general feature. Thanks to all for your time and the discussion!
