### ISSUE TITLE
npm and Git URLs

### ISSUE THREAD

**Issue by mhaseebkhan** [npm/npm#4029]
I have some private git repos which I want to use as dependencies in my Node.js app I am working on. Its worth mentioning that I am using GitHub Enterprise.

So my dependency looks like this:

"package-name" : "git://my-github-enterprise-url/user-name/package-name.git"

Now, when I do npm install, I get the error below:

_Could not read from remote repository. Please make sure you have the correct access rights and the repository exists._

However, I can manually clone using git clone command on terminal.

It would have been very easy for me if there was only one package it didn't had further dependencies having the Git URLs in the same pattern, but, unfortunately, thats not the case. There are several dependencies and all use the URL format.

I am working with Mac OSX, NVM, Node 0.8.3, NPM 1.2.18.

**Comment by smikes** [comment]
Is this still a problem for you?

If so, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.2.18. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
