### ISSUE TITLE
npm not installing, Guide me

### ISSUE THREAD

**Issue by naveenbytesflow** [npm/npm#4033]
It shows like this:
```
C:\Users\Naveen>npm install steroids -g
npm http GET https://registry.npmjs.org/steroids
npm http 304 https://registry.npmjs.org/steroids

> steroids@2.7.32 preinstall C:\Users\Naveen\AppData\Roaming\npm\node_modules\s
eroids
> node ./bin/check-node-version && node ./bin/preinstall

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\no
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "steroids" "-g"
npm ERR! cwd C:\Users\Naveen
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Naveen\npm-debug.log
npm ERR! not ok code 0

```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.11. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
