### ISSUE TITLE
npm can't install packages after upgrade to Maverick OS

### ISSUE THREAD

**Issue by kristianmandrup** [npm/npm#4047]
```
npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/kmandrup/private/angular-projects/sails-starter-app
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /Users/kmandrup/private/angular-projects/sails-starter-app/node_modules/sails/node_modules/connect-redis/test.js
npm ERR! fstream_path /Users/kmandrup/private/angular-projects/sails-starter-app/node_modules/sails/node_modules/connect-redis/test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/Users/kmandrup/private/angular-projects/sails-starter-app/node_modules/sails/node_modules/underscore.string/Gemfile'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

I get this error for all packages it tries to install (as defined in my package.json).

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like the race conditions that plagued older `npm` (before 2.1)

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by cdnbacon** [comment]
Unfortunately, I no longer have access to Mavericks to repro, but I cannot repro the issue on Yosemite. I updated `npm` to 2.5.0 using `npm -g install npm@latest` and `npm install` worked well for my project.

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
