### ISSUE TITLE
Someone create (find?) a caching HTTP agent already

### ISSUE THREAD

**Issue by domenic** [npm/npm#4159]
I don't think this is written down in issues, so I wanted to get it here for the record.

Part of @isaacs's grand plan for cleaning up cache.js and all related or dependent behavior is to extract the caching logic entirely to the HTTP level. This is pretty cool actually. Let me explain.

The idea is to create a [http.Agent](http://nodejs.org/docs/latest/api/http.html#http_class_http_agent) which transparently takes care of caching, *in the same way a web browser would*. That is, it maintains a local cache folder, which is not keyed based on package names or versions or anything, but purely on URLs. It uses headers like ETag, If-None-Modified, Cache-Control, Expires, and ideally even Vary, to manage this local cache folder in the face of outgoing HTTP requests. It should maybe also have a cache management policy (i.e. don't get bigger than a GB) or something. Also, it shouldn't use native modules---so no LevelDB!

Once you have this, you can just plug it into npm's HTTP-requester, and caching is taken care of, and rainbows and unicorns will dance for eternity.

Sound like a fun weekend and/or lifetime project to anyone? Anyone seen this hiding somewhere in the Node ecosystem?

Tagging in people who have expressed interest in helping improve or modularize npm in the past (and are not already repo collab): @ForbesLindesay @danielmoore.

**Comment by othiym23** [comment]
The idea of a read-through cache for registry dependencies is a compelling one. However, one of the goals that the CLI team has for the CLI now is to cleanly separate the npm cache from the registry client, whereas this proposal seeks to embed the cache in the registry client. That would make sense, except for the fact that one of our goals is to allow the cache to be used independently of the network code, _and_ to have the registry client do more of the abstraction away from package versions to URLs (i.e. the CLI code base tells the registry client, I want package `<name>` at version `<version>` from registry `<registry>`, instead of working with URLs directly). This is important to make handling the increasingly sophisticated amount of auth and configuration in a straightforward way (curious developers are invited to take a look at [`mapToRegistry`](https://github.com/npm/npm/blob/master/lib/utils/map-to-registry.js) to see the injuries this is doing to The Law of Demeter right now).

We’re also moving in a pretty different direction when it comes to caching strategies – the current plan is to move towards having a content-addressable cache, and rely more on things like the current inventory of shasums rather than HTTP-level metadata like `If-Modified-Since` or `Vary` (although we’re currently using both of those, or at least `Vary-Accepts` for various things in the registry client and the registry itself). While these semantics could continue to be supported (and probably will be, due to third-party registries using `If-Modified-Since` in lieu of ETags), they’ll probably be applied as a layer over the content-addressable core. In short: we’d like to decouple the cache from the registry client, and while the net result may be similar (i.e. basically read-through semantics from the CLI’s point of view), we’ll be pursuing a very different strategy to get there.

As such, I’m going to close this feature request. Thanks to all for their thoughts and discussion (and proofs-of-concept)!
