### ISSUE TITLE
Distribution has no attachment and gives 404

### ISSUE THREAD

**Issue by vojtajina** [npm/npm#4205]
See http://registry.npmjs.org/karma-phantomjs-launcher

There is version "0.1.1" (which has been succesfully pushed to NPM), but it has `"noattachment": true`. What does that mean?

[The link](http://registry.npmjs.org/karma-phantomjs-launcher/-/karma-phantomjs-launcher-0.1.1.tgz) gives 404 (and therefore fails any `npm install` that requires this module.

**Comment by smikes** [comment]
Is this still a problem for you?  It seems that this issue was reported before `npm publish` was atomic and before the `npm` registry was rewritten in early 2014.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since December 2013. Can you try updating your npm installation?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
