### ISSUE TITLE
got below error when run this command C:\> npm install -g phonegap

### ISSUE THREAD

**Issue by kavyabh** [npm/npm#4235]
```
2559 error Error: ENOENT, open 'C:\Users\kavya\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\package.json'
2560 error If you need help, you may report this log at:
2560 error     <http://github.com/isaacs/npm/issues>
2560 error or email it to:
2560 error     <npm-@googlegroups.com>
2561 error System Windows_NT 6.2.9200
2562 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
2563 error cwd C:\Users\kavya
2564 error node -v v0.8.22
2565 error npm -v 1.2.14
2566 error path C:\Users\kavya\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\package.json
2567 error code ENOENT
2568 error errno 34
2569 verbose exit [ 34, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.2.14. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
