### ISSUE TITLE
Issues creating a new user and then npm login

### ISSUE THREAD

**Issue by andreassolberg** [npm/npm#4281]
I've created an user andreassolberg, and I am about to publish my first module. However I am not able to successfully login using npm login.

I am able to login using the web site <https://npmjs.org> with the created user.

To me it seems like the problems lies in the fact that the current URL:

* <https://registry.npmjs.org/-/user/org.couchdb.user:andreassolberg>

is outputting

``{"error":"not_found","reason":"missing"}
``

When I am testing with other users that have successfully published to the registry, they seem to have a data entry in the URL corresponding to the one above.

Also worth mentioning that the following URL:

* <https://npmjs.org/~andreassolberg>

appears to be my publish profile, and it shows **User Not Found: andreassolberg**.

**Comment by smikes** [comment]
@andreassolberg , Is this still a problem for you?

This looks like it might have been a transient problem with the `npm` registry.  It should be fixed by now..

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
