### ISSUE TITLE
windows npm config cache/prefix butchers path + inconsistent path separator

### ISSUE THREAD

**Issue by Cleod9** [npm/npm#4286]
Re-defining the npm cache and global module locations on Windows machines as follows will not work:

`npm config set cache C:\npm-cache`
`npm config set prefix C:\npm`

This results in a  ~/.npmrc that looks like this which is obviously not correct:

`cache = C:npm-cache`
`prefix = C:npm`

The following workaround will work:

`npm config set cache /c/npm-cache`
`npm config set prefix /c/npm`

...However, it results in the following ~/.npmrc which is inconsistent
`cache = c:\npm-cache`
`prefix = c:/npm`
(Note the slashes are different for each value)

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- including better Windows support -- since December 2013. Can you try with a newer npm version?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by gmcleod-buzz** [comment]
I had actually completely forgotten about this. I don't work in the same environment anymore where it required me to change the npm-cache path, but I tested just now in npm 1.4.3 and I even upgraded my system to 1.4.28 and I still see the same occurrence.

Long story short, on Windows when you set the npm path with the backslash character "\" the code appears to be treating it like a special character. The work-around for this is easy enough by just enclosing the path in quotes, or just editing .npmrc manually. But I do still think that if the path parameter is not enclosed in quotes it should treat those backslashes as a path separator on Windows machines.

**Comment by Cleod9** [comment]
I had actually completely forgotten about this. I don't work in the same environment anymore where it required me to change the npm-cache path, but I tested just now in npm 1.4.3 and I even upgraded my system to 1.4.28 and I still see the same occurrence.

Long story short, on Windows when you set the npm path with the backslash character "\" the code appears to be treating it like a special character. The work-around for this is easy enough by just enclosing the path in quotes, or just editing .npmrc manually. But I do still think that if the path parameter is not enclosed in quotes it should treat those backslashes as a path separator on Windows machines.

**Comment by smikes** [comment]
Are you testing this with bash or with cmd.exe? Since bash interprets backslashes as escape characters, if you're not doubling your backslashes it might be bash which is eating them. 

Can you post an example of the command(s) you are running, together with the unexpected contents of .npmrc?

**Comment by Cleod9** [comment]
Looks like it only occurs in bash, I get expected results from cmd.exe. Examples of the full scenario below:

**Git Bash Single Backslash**

`npm config set cache C:\foo\npm-cache`

results in the following *incorrect* output:

`cache = C:foonpm-cache`

**Git Bash Double Backslash**

`npm config set cache C:\\foo\\npm-cache`

results in the following *correct* output:

`cache = C:\foo\npm-cache`

**cmd.exe**

`npm config set cache C:\foo\npm-cache`

results in the following *correct* output

`cache = C:\foo\npm-cache`

----------------------

I understand what you're saying that bash interprets the slash differently, but I just find it odd that git bash on Windows goes through the trouble to handle backslashes differently for other commands such as `cd`. 

Ex.: Both `cd C:\Users` and `cd /c/Users` change to the Users directory on the C drive

All of the above aside, let me just summarize everything for future folks who find this thread. I first encountered this problem when the default npm-cache directory was in a place with limited profile disk space and limited write access. I would constantly  run out of disk space because of the npm-cache and be alerted I need to free disk space. So I decided to change the cache directory through Git bash expecting it to work. I still kept getting alerts about disk space, only to find that the directory written to .npmrc was incorrect. This wasted days of work which was unfortunate, but I am long past that now. I honestly just think this whole thing should be documented somewhere as a side note, and we can close the issue. Maybe even the keywords from this thread would even suffice as documentation.

**Comment by othiym23** [comment]
I'm going to close this as resolved, because while I agree that there are a number of small confusing things happening here that add up to one big confusing / frustrating thing (and I'm sorry you lost so much time to this!), I think this is a "bash on Windows" thing than a "npm on Windows" thing. We could definitely stand to have some better, concept-oriented documentation for using npm on Windows, but I don't really know of a good way to jam this particular tidbit into the docs without it being distracting for most people reading the docs, most of the time.
