### ISSUE TITLE
Repeated ETIMEDOUT

### ISSUE THREAD

**Issue by gregsandell** [npm/npm#4306]
I am installing grunt-cli with the command:

sudo npm install -g grunt-cli

...and every time I try I get this timeout error.  Suggestions?
```
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-cli
npm ERR! Error: connect ETIMEDOUT
npm ERR!     at errnoException (net.js:770:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:761:19)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! cwd /Users/gsandel/Documents/projects/swordfish-gsandell
npm ERR! node -v v0.8.20
npm ERR! npm -v 1.2.11
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/gsandel/Documents/projects/swordfish-gsandell/npm-debug.log
npm ERR! not ok code 0
```
Thank you,
Greg

**Comment by smikes** [comment]
@gregsandell , Is this still a problem for you?

This looks like it might have been a transient problem with the registry from December 2013; since then the registry has become faster and more stable.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.2.11. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
