### ISSUE TITLE
404 https://registry.npmjs.org/cordova/-/cordova-3.3.0-0.1.0.tgz

### ISSUE THREAD

**Issue by mrsubtle** [npm/npm#4311]
Unable to install cordova via CLI using "sudo npm install -g cordova" command.

Receive a 404 (here is console output):
```
npm http GET https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/cordova/-/cordova-3.3.0-0.1.0.tgz
npm http 404 https://registry.npmjs.org/cordova/-/cordova-3.3.0-0.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/cordova/-/cordova-3.3.0-0.1.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! cwd /Users/rich/Work/_mobile/footysprofila.com/v1
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/rich/Work/_mobile/footysprofila.com/v1/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
@mrsubtle , Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.11. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by mrsubtle** [comment]
Looks like it's all good now, thanks!

Richard Bennett
rich@n2d.co   |   http://n2d.co/   |   @mr_subtle   |   Behance   |   Dunked   |   Scoutzie

**Comment by othiym23** [comment]
Closing as resolved!
