### ISSUE TITLE
Add `npm browserify` command

### ISSUE THREAD

**Issue by domenic** [npm/npm#4322]
This has been under discussion for a while, but I wanted to log it as a work item. To make npm the best JavaScript package manager and help it crush all competition, we need to have easier first-class support for browserifying.

I am not sure what exactly the scope of this feature is. Browserify has a pretty big ecosystem; do we want to support all of it? (Transforms, watchify, etc.) How much of a burden do we end up taking on ourselves, which was previously not ours? Maybe we can just delegate entirely to browserify, and tell people to go get involved in that community---we just include it as a convenience? Are we comfortable with the speed and code quality of browserify as-is (e.g. the issue where it pretends to be streaming but instead buffers everything along each step of the way)?

**Comment by othiym23** [comment]
Browserify is _an_ incredibly useful workflow for many developers. However, it's not the _only_ one, and putting it into npm directly was probably never in the cards. Beyond that, having a standard way to do builds for front-end use cases is still a good goal, but it's probably not going to get implemented as a top-level command like this. It's also not clear when the team is going to get to this, but because it's something with wide-ranging implications, and as such is something that will be done with heavy consultation with the user community. As such, I'm going to close this issue, and we'll spin up a new discussion when the team is ready to move on this. Thanks for your time!
