### ISSUE TITLE
Can't install jsdom (or contextify) on Win7 x64

### ISSUE THREAD

**Issue by rasputozen** [npm/npm#4342]
I have Visual C++ 2010 with sdk 7.1.  I uninstalled the x64 version of node I had and installed an x86 version.  My python variable is set.  Before I installed the x86 version the install would be mostly error free except for some yellow text during the middle of it that had to do with contextify not installing.  I no longer get the yellow text but now I get a whole bunch more errors at the end which you can see in the pictures.
![npm_debug_log_1](https://f.cloud.github.com/assets/6169039/1773085/c589bc5e-67df-11e3-9264-b7f5782a0643.png)
![npm_debug_log_2](https://f.cloud.github.com/assets/6169039/1773088/c8bf7076-67df-11e3-865e-456fc5681122.png)
![npm_debug_log_3](https://f.cloud.github.com/assets/6169039/1773089/cb838a86-67df-11e3-9d53-6cbeb7cddae3.png)

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.17. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
