### ISSUE TITLE
ERRORS using grunt

### ISSUE THREAD

**Issue by scazzy** [npm/npm#4376]
http://i.imgur.com/4RHSk4i.png

First grunt run worked fine. later npm install gave error for every package.
Later tried reinstalling grunt and grunt-cli, got the error for the same. nothin working.
Tried deleting npm cache, still no success.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since December 2013. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
