### ISSUE TITLE
Problem installing npm in windows 8/7

### ISSUE THREAD

**Issue by flori2doyohim** [npm/npm#4385]
768 silly lockFile dc43e8fc-ry-npmjs-org-less-less-1-5-1-tgz https://registry.npmjs.org/less/-/less-1.5.1.tgz
769 silly lockFile dc43e8fc-ry-npmjs-org-less-less-1-5-1-tgz https://registry.npmjs.org/less/-/less-1.5.1.tgz
770 silly lockFile 5a0b359d-less-1-5-1 less@1.5.1
771 silly lockFile 5a0b359d-less-1-5-1 less@1.5.1
772 silly lockFile e13833ab-less less@
773 silly lockFile e13833ab-less less@
774 error Error: shasum check failed for C:\Users\kowya\AppData\Local\Temp\npm-4440-yXCpqw4a\1388093416193-0.29394221445545554\tmp.tgz
774 error Expected: 633313130efd12a3b78c56aa799dab3eeffffff4
774 error Actual:   4d3ea0b595da22a74f31233a8a0d1383ecd1ff3a
774 error     at C:\webserver\Kendo\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
774 error     at ReadStream.<anonymous> (C:\webserver\Kendo\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
774 error     at ReadStream.EventEmitter.emit (events.js:117:20)
774 error     at _stream_readable.js:920:16
774 error     at process._tickCallback (node.js:415:13)
775 error If you need help, you may report this *entire* log,
775 error including the npm and node versions, at:
775 error     <http://github.com/isaacs/npm/issues>
776 error System Windows_NT 6.2.9200
777 error command "C:\\webserver\\Kendo\\nodejs\\\\node.exe" "C:\\webserver\\Kendo\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
778 error cwd C:\webserver\Kendo\kendo-bootstrapper
779 error node -v v0.10.24
780 error npm -v 1.3.21
781 verbose exit [ 1, true ]

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like you have an incorrectly-downloaded file in you cache.  Can you try running `npm cache clean` and then retrying your install?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by KenanY** [comment]
Closing as abandoned (no reply). Can reopen if this is still an issue with `npm@>=2`.
