### ISSUE TITLE
log to the console when installing from git repo

### ISSUE THREAD

**Issue by matthewkastor** [npm/npm#4419]
Environment:

Windows 7 64 bit
Node version 0.10.24 32 bit
Npm version 1.3.21

When installing packages that depend on git repositories, there is no indication that npm is fetching the git repository. This can make it appear that `npm install` is hung up and the installation is failing.

When npm fetches packages uploaded to npmjs.org it logs a message to the console when it's fetching the package. I'd like similar behavior when it's grabbing a git repo so that I have some indication that something is happening.

An example is trying to install `atropa-toolbox`. That's mine, I have it depend on a bunch of packages so I can generate a library that I use all the time by running it through browserify. The problem is that I can't publish packages with capital letters in their names, or the package name I want to use is already published to npm. So, I end up depending on git repos all the time. What happens when I'm installing the `atropa-toolbox` is that I see npm grab packages from npmjs.org then, while it's fetching the 13 git repositories there's no output to the console. While npm never fails to work it's magic unless I have connectivity issues, it's still tormenting my inner control freak and tweaking my OCD that I don't have a clue what's going on. I'm just sitting there, staring at the console thinking "ctrl+c?".

Please help. :D

**Comment by othiym23** [comment]
The way that npm communicates progress to users has changed radically since `npm@1`, which renders a bunch of this discussion moot. I'd still be happy to land changes that give more granular updates as to what Git's doing (the `.verbose` and `.silly` log messages in `lib/cache/add-remote-git.js` now get shown by the progress bar), but I think that overall we've addressed this by switching to the `npm@3` progress bar. As such, I'm closing this issue. Thanks to all for the discussion!
