### ISSUE TITLE
How programaticaly execute a npm update on local directory

### ISSUE THREAD

**Issue by sdnetwork** [npm/npm#4431]
hi,

i try to do that by javascipt :

cd c:\mylocalpackage
npm update

by command line it works fine only module in mylocalpackage is updated.

but if i do that by javascript :
```javascript
    npm.load(npm.config, function (er) {
      if (er) {
       console.log(er);
       return 1;
      }
      npm.commands.update([], function (er, data) {
       console.log(er);
      });
     });
```
and i do :
```
cd c:\mylocalpackage
node app.js
```
it seems to update all  modules not only the local that is in mylocalpackage :(

i'm doing something wrong ?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since February, 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned / possibly resolved.
