### ISSUE TITLE
Show parts of HISTORY.md after `npm update`

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#4463]
Yeah, that would be cool. Whenever we update packages we want to know what has changed.

How about making our lives easier and present chapters of HISTORY.md after an update? Probably via an optional parameter?

1. `npm update express -show-history` (or `npm update -show-history` for all packages)
2. Parses HISTORY.md if exists
3. List changes between current and latest version after successful update

**Comment by othiym23** [comment]
For this to be a useful feature, we’d need a couple things:

1. A strong convention for formatting changelogs (and there [are]() a [few]() of them now), with enough momentum behind the convention that it would make sense for npm to bless it.
2. A way of parsing out the most recent changes to display to users.

I’m pretty familiar with this kind of functionality, having been a Debian sysadmin for _mumble_ years now, and it’s pretty cool. Even in the Debian case, though, `apt-listchanges` is implemented as a separate program that runs after packages have been pulled down but before they’re installed, and is implemented as a plugin to APT. I think this should be implemented similarly, which is to say that I don’t think it belongs in npm core. If it turns out it’s impossible to implement without making changes to how the npm lifecycle operates, then maybe that supporting work can be landed in the core CLI, but this sounds like more complexity than we want to add to an already complicated code base for a cool but not exactly necessary function.

As such, I’m going to close this feature request. Thanks for your time and patience!
