### ISSUE TITLE
shrinkwrap prevents devDependencies updates

### ISSUE THREAD

**Issue by vvo** [npm/npm#4516]
tl;dr; When a `npm-shrinkwrap.json` exist, changing a non-shrinkwraped  devDependency version inside package.json does not updates the package when doing `npm install`.

Reproducible example:

`package.son`
```json
{
  "name": "testpkg",
  "description": "bad shrinkwrap is bad",
  "version": "0.0.0",
  "devDependencies": {
    "rimraf": "~2.0.0"
  }
}
```

`npm-shrinkwrap.json`
```json
{}
```

Inside a fresh folder:
```shell
> npm install
# npm WARN package.json testpkg@0.0.0 No repository field.
# npm WARN package.json testpkg@0.0.0 No README data
# npm http GET https://registry.npmjs.org/rimraf
# npm http 304 https://registry.npmjs.org/rimraf
# npm http GET https://registry.npmjs.org/graceful-fs
# npm http 304 https://registry.npmjs.org/graceful-fs
# rimraf@2.0.3 node_modules/rimraf
# └── graceful-fs@1.1.14
```

Looks, good.

Modifying `package.json` to update `rimraf`:

```json
{
  "name": "testpkg",
  "description": "bad shrinkwrap is bad",
  "version": "0.0.0",
  "devDependencies": {
    "rimraf": "~2.2.0"
  }
}
```

In a shell:

```shell
> npm install
npm WARN package.json testpkg@0.0.0 No repository field.
npm WARN package.json testpkg@0.0.0 No README data
```

Nothing gets updated. I expect rimraf to be updated.

Removing `npm-shrinkwrap.json`:

```shell
> rm npm-shrinkwrap.json 
> npm install
npm WARN package.json testpkg@0.0.0 No repository field.
npm WARN package.json testpkg@0.0.0 No README data
npm http GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/rimraf
rimraf@2.2.6 node_modules/rimraf
```

Is this the normal behavior?

```sh
> node -v
v0.10.24
> npm -v
1.3.24
```

**Comment by glenjamin** [comment]
Does anyone have a good workaround for this issue at the moment?

As others have described above, I'm using the shrinkwrap to lock down production dependencies, but would have expected devDependencies to be package.json controlled.

**Comment by MattiSG** [comment]
@glenjamin 
```shell
mv npm-shrinkwrap.json npm-shrinkwrap.json~ &&
npm install &&
mv npm-shrinkwrap.json~ npm-shrinkwrap.json```

**Comment by glenjamin** [comment]
@MattiSG Great tip! thanks

**Comment by searls** [comment]
I just got bitten by this as well. Gisted my adventure here: https://gist.github.com/searls/3dc752e00bbc6e226531

**Comment by searls** [comment]
There are few things in this thread that stand out to me:

1. It's a red herring to suggest this issue is about "hand-editing" the package.json. Even if the developer updating a devDependency uses `npm i --save`, a collaborator on the project can be expected to pull changes, run `npm install` and experience surprise that their devDependencies aren't updated. Because it fails silently, I've seen this lead to very difficult-to-debug build and test issues and it represents a very bad user experience.

2. Re: @othiym23's comments on using shrinkwrap at all [here](https://github.com/npm/npm/issues/4516#issuecomment-49705047), I believe the npm FAQ no longer contains language recommending node_modules be checked in for deployed apps, for whatever that's worth. (I know heroku recommends using shrinkwrap over checking in node_modules)

3. When it comes to surprising behavior (re: @mzgol), the current behavior is incredibly surprising to anyone expecting shrinkwrap to actually make one's dependencies install more consistently. I would not worry from a user-surprise perspective about breaking backwards-compatibility of `npm install` commands when the shrinkwrap and package.json diverge.

In my last 18 months of using shrinkwrap off-and-on with the hope of it bringing consistency of installed modules to teams working on deployed apps (a la Bundler's Gemfile.lock), I've had an absolutely terrible experience every time. From shrinkwrap's inability to generate consistently when run from different machines, to the multiple steps required to upgrade a dependency, it feels like the feature is working against itself by encouraging users to solve problems by blowing away and regenerating their shrinkwrap. 

The fact this thread hasn't been responded to with a sense of extreme urgency makes me suspect that developers working on npm don't use shrinkwrap themselves. At this point, I'd rather that npm just remove the feature entirely than continue to offer it in its current state, encouraging someone else to build their own tool that produced a lockfile and re-implemented their own `npm install` to match.

**Comment by fresheneesz** [comment]
I agree with searls. As a matter of fact, in my project, I have a postinstall script that automatically installs individual dependencies that have had their version changed inside `package.json`, then re-shrinkwraps after its done. So my only step is to change the `package.json` file and `npm install` does the rest. This kind of thing should be there out of the box for npm.

**Comment by gilesbowkett** [comment]
quoting @searls:

> At this point, I'd rather that npm just remove the feature entirely than continue to offer it in its current state, encouraging someone else to build their own tool that produced a lockfile and re-implemented their own `npm install` to match.

I think this is compatible with the very Unix-y, "do one small thing well" philosophy popular in the Node world, and with something @othiym23 said:

> npm is less opinionated about deployment and workflows than Bundler in this respect, and I think that's one of its strengths.

**Comment by jasonkarns** [comment]
> To me, this sounds like an argument in favor of advocating careful use of semver rather than making shrinkwrapping the default. Semver's semantics are designed to support forward-compatibility of dependents by default.

I think we should be careful of attempting to use semver as the One True Scotsman escape clause to fixing shrinkwrap. Scenario:

Application A is using Library L and unknowingly relies on some particular behavior (let's say the library throws an exception when given some certain input). Library L later uncovers this behavior, considers it a bug and fixes it. Library L now returns `undefined` for the given input instead of throwing an exception. Library L dutifully follows semver, releases an update as a patch release, and enjoys their summer. Meanwhile, a new developer joins Application A's team, clones the repo and npm-installs. They get the updated version of Library L, and the app is now broken.

This is not to be taken as an argument against semver. I believe semver has value and should be followed. But the notion that following semver will make our apps completely immune to bitrot is simply not true. Therefore, semver cannot be used as an alternative to having a working form of shrinkwrap that *will indeed* ensure two different installs of the same app get the same dependency tree.

**Comment by amay** [comment]
I completely agree with @searls feedback and have had similar experiences using npm-shrinkwrap over the last several months. Has anyone had any luck finding an alternative to npm-shrinkwrap that works well?

**Comment by wagenet** [comment]
I too have wasted a bunch of time due to this issue. The fact that my package.json and my installed modules can mismatch with no warning being given is a huge problem.

**Comment by vvo** [comment]
I wanted to note that this issue was somehow fixed in npm. I did the same setup and it worked! Good job dear npm bug fixer.

```sh
> node -v
v4.0.0

> npm -v
2.14.2
```

PS: I dunno about all other discussions.
