### ISSUE TITLE
Add support to install non-node packages to another directory; "npm_packages".

### ISSUE THREAD

**Issue by briandipalma** [npm/npm#4524]
I know that issues like this have been raised before and closed but I feel this is different to those.

ES6 modules are soon to be upon us and having a standard mechanism for loading code into JS environments is going to make package managers much more widely used/attractive in the web application/browser world then they have been so far.

There are two realistic choices available, npm and bower, npm can do virtually everything that bower can do and more and yet bower still seems to be winning more browser developer mindshare than npm. I believe it's down to bower making it's position quite clear and calling itself "A package manager for the web" and npm not coming out with a similar statement. People look at it, think "Oh, that's for node." and install bower.

If npm wants to be the best package manager it should clearly state that it's agnostic to what it's being used for. Even that it's agnostic as to the platform that it runs on. I believe a good first step is to drop the `node_modules` directory name installation requirement.

I am not asking for a configurable npm installation directory, it will be a hardcoded value, I suggested `npm_packages`.

I am not asking for anything inside `npm_packages` to be loaded by node, in fact what's inside the `npm_packages` directory will almost by definition not be node modules but other web platform assets.

What I am asking for should be purely an npm concern and not a node one.

This is about npm making a clear statement that it's a generic web package management tool for any platform and for any user.

If the npm team don't want it to be used for anything other then node then please state that as it would help clarify the position to external developers evaluating npm vs bower.

**Comment by othiym23** [comment]
This is a need that has only grown more pressing in the time since this feature request was filed; npm as a product company is still thinking about the best way to improve its handling of front-end workflows. We have a section of the [CLI roadmap](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-browser-dependencies) dedicated to handling front-end asset installation. That said, we’re still trying to figure out how npm fits into the pictures – right now there’s webpack, [`copy-browser-modules`](https://www.npmjs.com/package/copy-browser-modules), Rollup.js, and a whole host of Gulp / Grunt workflows designed to deal with this, and the challenge has been (and remains) to figure out the lightest way that npm can take on some of this without prescribing too opinionated of a workflow. This is something we intend to do!

At the same time, the specifics are still being roughed out, and it’s a whole project that does involve more than just the CLI team, so we’ll probably be tackling it at the product level. As such, I’m going to close this feature request. Thanks for your time!

**Comment by kruncher** [comment]
My reasoning against such a feature:

Npm is my favorite package manager and node.js is one of my favorite tools for automating various things. I use these tools outside of web development.

I use them for managing reusable assets and C# scripts for games that I make using the Unity game engine. I even use them for handling the building process of an editor extension for the Unity game engine.

Initially, the fact that npm forces me to use the `node_modules` directory was frustrating for me because a) the naming of this directory makes little sense for Unity3D-centric projects and b) it's in the wrong place.

I tried various tricks to try and overcome this such as creating a symlink into the Unity project's "Assets/" directory. Then I went to add a regular node module to my build pipeline and BOOM! Unity is trying to compile the `.js` files from the non-Unity package.

This forced me to try a number of other solutions until I eventually settled on creating a node package that synchronizes npm packages that are designed specifically to be used with Unity into the correct place within the Unity project. (For anybody interested: https://github.com/rotorz/unity3d-package-syncer)

Whilst I think `node_modules` isn't a very accurate name for the installation directory (`npm_modules` perhaps may have been more accurate?) I don't think that it's a great idea to allow this path to be customizable.
