### ISSUE TITLE
Shell completion script breaks bash's environment variable assignment filesystem path completion

### ISSUE THREAD

**Issue by aadamowski** [npm/npm#4530]
The shell completion script  `lib/utils/completion.sh` has an unfortunate effect on Bash that it breaks standard TAB completion for setting environment variable values.

As reported on [ServerFault](http://serverfault.com/questions/537460/preventing-bash-tab-completion-of-an-environment-variable-with-a-fs-path-value-f/569081#569081), without npm shell completion the correct expected behaviour is as follows:

1) the user types:

    export SOME_VARIABLE_NAME=/partial/filesystem/path/to/someth

2) the user presses TAB

3) the command line gets completed to:

    export SOME_VARIABLE_NAME=/partial/filesystem/path/to/something_existing

With npm shell completion active, the result is broken - the environment variable name gets removed:

3) the command line gets completed to:

    export /partial/filesystem/path/to/something_existing

**Comment by jasonkarns** [comment]
I ran into this bug recently. Without the equal sign, git completion breaks for any option containing an equal sign.

`git log --date=<TAB>`,  `git commit --reuse-message=<TAB>`, `git branch --set-upstream-to=<TAB>` are all broken because of npm's modification of `COMP_WORDBREAKS`.

**Comment by louisremi** [comment]
This might be solved using the solution proposed in [this stackoverflow thread](http://stackoverflow.com/questions/10528695/how-to-reset-comp-wordbreaks-without-effecting-other-completion-script)
I'm a complete bash noob, I can't make sense of the syntax in the accepted answer, so I won't be able to propose a patch : (

**Comment by whitty** [comment]
I had a go at rewriting the completion script and it seems to work for me - see 7e4d15f

I find firstly that completions with = and @ are no longer broken outside of npm, and npm completion seems to work fairly well.

That being said I'm neither a bash_completion export, nor an npm user so I don't know if I've broken anything.

**Comment by jasonkarns** [comment]
Clearly the original author of this completion script had a use case in mind for ignoring `@` and `=` in the word completions. Do we have an example command that exercises this use case so that we can test @whitty's implementation?

**Comment by jasonkarns** [comment]
Also, this change seems to be working just fine for me (ie, not breaking git's tab completion)

> GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin13.4.0)

**Comment by anthonyfok** [comment]
Hi!  Took me quite a while to discover it was `/etc/bash_complete.d/npm` that broke my filename completion after an equal sign, and finally found this issue.  ;-)

For completeness sake, this bug was also reported against the Debian's npm package, which uses same bash completion script:

* [[Debian Bug#711810] npm: bash completion script clobbers $COMP_WORDBREAKS](https://bugs.debian.org/711810) (https://bugs.debian.org/711810)

**Comment by othiym23** [comment]
There is a fix landed to the completion script in d7271b8226712479cdd339bf85faf7e394923e0d – the `lib/utils/completion.sh` included in the tree at that version (which will be part of the next `npm@2` release, coming out later tonight as `npm@next`) fixes this issue. I'm not sure we can say that _resolves_ this issue, though, because the patched script will need to get pushed to all the downstream distributions bundling it. @anthonyfok, could you do us a favor and update that Debian bug with this information?

I'll leave this open for a little while as a reference point for people discussing this with distros. Thanks for your patience, everybody!

**Comment by jasonkarns** [comment]
Do we need to open a PR to get this into homebrew?

**Comment by jasonkarns** [comment]
Yay! `2.13.5` is now `@latest` !!!

**Comment by anthonyfok** [comment]
> @anthonyfok, could you do us a favor and update that Debian bug with this information?

Hi @othiym23, sorry for the late reply.  I have just sent an update to Debian Bug #711810 (https://bugs.debian.org/711810) accordingly.  Hope we will see npm@2.13.5 in Debian soon!  :-)
(See [Debian Bug #794890: npm: new upstream version](https://bugs.debian.org/794890).)

**Comment by busches** [comment]
Can this issue be closed since the problem itself is resolved? Debian is still including `npm@1` on their repositories, but that should be filed against Debian, not `npm`. https://packages.debian.org/search?searchon=names&keywords=npm

cc\ @KenanY
