### ISSUE TITLE
shasum check failed in npm install node-inspector  

### ISSUE THREAD

**Issue by websailor** [npm/npm#4533]
```
npm ERR! Error: shasum check failed for D:\Temp\npm-540-cjoJJsVk\1390458417255-0.15404863539151847\tmp.tgz
npm ERR! Expected: 4da7515c5e773041d1b423970415bcc430f35fc6
npm ERR! Actual:   ebd461f2407870aaca7b8421800a85f8c56badb4
npm ERR!     at E:\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
npm ERR!     at ReadStream.<anonymous> (E:\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "E:\\nodejs\\\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! cwd E:\nodejs
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like it might be a corrupted file in your cache.  Can you try running `npm cache clean`?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
