### ISSUE TITLE
npm on windows, install with -g flag should go into appdata/local rather than current appdata/roaming?

### ISSUE THREAD

**Issue by mgancarzdsi** [npm/npm#4564]
Hello, I'm not entirely sure if this is an issue as opposed to a design decision, but I'd like to suggest that npm installs with -g flag, when done on Windows 7/8 should go into the appdata/local directory, as opposed to the current appdata/roaming.

Roaming is the part of the user directory that is user-specific and machine agnostic, ie: it moves with the user to other machines. This means that in many corporate environments (such as ours) it is redirect to the network as a long UNC path. This then causes issues when trying to run things installed globally (such as grunt) since UNC paths are not supported in the command line.

I'd suggest installing things into %USERPROFILE%\AppData\Local would be more appropriate, as that is both User-specific and computer-specific application settings and is very unlikely to ever be redirected or anywhere other than on the local machine.

**Comment by jpolo** [comment]
As specified in http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

"local/shared" corresponds to "home data" and "config" to "home config". All user packages and cache should go in "local/shared". Any data concerning user npm login, etc should go in "config" directory.

Doing the parallel with windows, I think it should go to %LOCALAPPDATA% directory.

**Comment by sccolbert** [comment]
+1 on %LOCALAPPDATA% for both `prefix` and `cache`.

Roaming is the wrong place for the default location IMO.

**Comment by Zoltu** [comment]
It sounds like everyone agrees that cache should go into `LOCALAPPDATA`.

As for `npm install -g`, it seems like a couple decision needs to be made and depending on those decisions, the solution becomes apparent.

1. Does `npm install -g` install global to the machine or global to the user?
  1. If global to the user, do `npm install -g` installs follow the user between machines?

If `npm install -g` installs global to the machine, then the correct location is %PROGRAMFILES%`.

If `npm install -g` installs global to the user and does *not* follow the user between machines, then the correct location is `%LOCALAPPDATA%`.

If `npm install -g` installs global to the user and *does* follow the user between machines, then the correct location is `%APPDATA%`.

*Arguments for installing global to machine:*
1. You can author a script leveraging globally installed packages as one user and then execute the script as another user.  This is most meaningful when running a script as an administrator or during startup or in the background.  As a user, I may author a script that does something interesting and then I want to schedule it.  While I can schedule a script to run with my credentials, this is not a common practice and scripts are usually executed from the context of a user that is different from the context of the user who wrote the script.  If global packages are installed per user, then this script will not run as expected because the user executing the script won't see the packages.  In Windows, it is not uncommon for non-desktop applications to execute as different users.  An example of this is IIS which runs its worker processes as a limited access user.  Another common scenario is running a script as admin, which won't see %APPDATA% as the original user's folder.

*Arguments for installing global to user:*
1. No need to be an admin to execute `npm install -g`.  Global to machine will require admin access in order to modify `%ProgramFiles%`.

*Arguments for installing to roaming user:*
1. Your globally installed modules follow you.

*Arguments for installing to local user:*
1. Your globally installed modules don't burn through your roaming quota, you don't have to sync roaming code every time you login to a new machine.

NOTE
--------
`%ALLUSERSPROFILE%` should *not* contain executable code!  `%AllUsersProfile%` is an unsecured location meaning any user can write/modify its contents.  This means if I install some tool onto the machine in that directory, then a malicious user uses the machine, then I come back the next day and run my tool again it is possible that the malicious user modified my executable to do something malicious.  The malicious code is now executing as *me* and has full access to all of my stuff.

Opinion
----------
In order of preference:

1. Make `--global` be per machine and to add a new option `--user` that would install to my user profile.  This gives the user the choice at install time to do what makes sense for their environment.
	1. Put a `packages.config` in roaming user data and store downloaded packages in local user data.  Then provide the user a way to install user packages with a single command like `npm install --user`.  This follows the same pattern as version control where you checkin `packages.config` and do an `npm install` when you clone to a new machine/location for the first time.
	1. Put everything in local user data.  I believe that there is too much room for explosion to allow it to go into roaming user data.  Package authors are/will not care about the size of their package so there aren't any controls to stop packages from being particularly large.
1. Make `--global` be per machine.  This is what I intuitively thought `-global` meant until I saw this thread.  It also allows Node to be leveraged as an OS scripting tool.  If NPM packages don't go into a machine accessible space then I am likely to go use something else (powershell) to do my scripting because getting NPM packages to work across users is too much of a pain.
1. If it is decided that `--global` must be per user (I argue strongly against this) then I believe local user data is the right place.  There is too much opportunity for installed packages to grow large and blow up the user's roaming profile.  Maybe `packages.config` could go into roaming profile and one can do `npm install --global` which would install all packages found in `packages.config` into local user profile.  This way the user controls when the download occurs and quotas aren't negatively impacted.

**Comment by Zoltu** [comment]
For reference: http://windows.microsoft.com/en-us/windows-8/what-appdata-folder

**Comment by sccolbert** [comment]
IMHO, the best option is the one which will work for the most users with the least amount of pain. Installing into local app data should work for everyone, without requiring admin. I'd be okay with this being exposed as a `--user` flag in lieu of `--global`. 

In no case do I think things should installed into roaming app data. I can't think of a case where I would want my npm packages to follow me around, nor do I want to deal with blowing up profile quotas.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by clshortfuse** [comment]
I made a dupe issue on https://github.com/npm/npm/issues/9078 where I stated the issues of local and roaming profiles have write access for any application, while program files requires elevated permissions to change.

Any program can modify local and roaming profile files and literally, if they wanted to, inject/steal code/data through modifying those files.

It's nice that we can change the locations with simple commands. For example, changing to program files would be

    npm config set prefix "%programfiles%\npm"
    npm config set cache "%programfiles%\npm\cache"

What I recommend is something during install time that allows the user to choose. For example, this is what GitHub's UI installation prompts:

![](http://cloud.atechmedia.com/screenshots/Git%20Windows%20Install%20PATH.png) 

Then the user can select

* Local Profiles 
* Roaming Profiles
* Program Files
* Custom Install Folder (ie: c:\npm\)

with all of the pros and cons of each.

**Comment by tracker1** [comment]
I'm pretty sure this best belongs in `%PROGRAMDATA%` not `%PROGRAMFILES%` since modifying the program files paths is increasingly difficult for non-installers in windows, and program data is the common path for data relating to programs, I know this kind of crosses into executable bounds in a data path, but so does the appdata path.

NOTE: if say `%PROGRAMDATA%\npm` used, then the directory needs to be prepped as modifyable by all users, and/or a passthrough request for elevated privileges for writes need to happen when npm install -g occurs.

**Comment by smartmouse** [comment]
I like things to be flexible  Each environment is different but I would like -g to be global to the machine where all users account can access.  If -g is global to only the user account , that will be too much duplication on the machines.  Also windows always have an issue with PATH length restrictions,  I do want the choice of
installing it somewhere else which has a shorter path.

**Comment by yamlfd** [comment]
%LOCALAPPDATA% is no solution as this folders are excluded from roaming and will be deleted everytime a user logoff from this computer!

**Comment by jpolo** [comment]
> %LOCALAPPDATA% is no solution as this folders are excluded from roaming and __will be deleted everytime a user logoff__ from this computer!

I've tested manually, they are not deleted. 
A few inspection to the content of ```%LOCALAPPDATA%``` on my computer shows that it seems to be a common practise to put cache files in this directory (ex: Skype)

**Comment by yamlfd** [comment]
https://github.com/npm/npm/issues/9581 is a dupe.

**Comment by yamlfd** [comment]
@jpolo: You need a domain based environment or enterprise network with domain login and *roaming profiles*. This is best practice in large environments. It is also best practice to redirect APPDATA to a network drive like "\\SERVER\username$\AppData" and to turn the GPO on to exclude local app data from roaming.

This may otherwise cause a upload/download storm in the morning/evening as local app data may contain several GB of files. That is something some software developers seem not understand since several years.

**Comment by jpolo** [comment]
@yamlfd In the other way, if roaming is synced to cloud (DropBox etc), it creates lots of transfers too. Maybe we can both agree that cache __must__ be removed from roaming. 

Behavior should be as close as possible between platforms. For instance, in Ubuntu ```npm -g``` install needs sudo rights (https://docs.npmjs.com/getting-started/installing-npm-packages-globally). This would correspond to a %PROGRAMDATA% installation with an administrator cmd.exe.

For other needs (i.e. installation in roaming), it should be configurable but not the default behavior.

**Comment by yamlfd** [comment]
Yes, cache must be outside of roaming. This would be your example.

[npmrc]
```
prefix=${PROGRAMDATA}\npm
cache=${LOCALAPPDATA}\npm-cache
```

And we need to change

[nodevars.bat]
```
set PATH=%PROGRAMDATA%\npm;%~dp0;%PATH%
```

I'm personally not sure why you suggest %PROGRAMDATA%. Is this really "data"? I think this are programs, isn't it? These should be inside ProgramFiles folder next the the applications. I guess half of the idea is to allow non-admins to install the addons. If we cannot distribute these addons this would add a heavy hurdle on admins. I do not like to install all packages for all my developers. They do not have admin permissions on their computers.

I'm not experienced enough with NPM to say if I can copy the npm folder %PROGRAMDATA%\npm to all computers.

**Comment by yamlfd** [comment]
http://blogs.msdn.com/b/cjacks/archive/2008/12/04/how-to-set-directory-permissions-at-install-time-using-an-msi-created-using-windows-installer-xml-wix.aspx

**Comment by tracker1** [comment]
You shouldn't be writing to `%PROGRAMFILES% outside of an initial installer/updater...  And you certainly shouldn't be doing it outside of an admin role... this has been the case since Vista, you'll be actively prevented from doing it... if you're creating a scripted environment that should be global to multiple users, then the installer creating a path in `%PROGRAMDATA%` that is user modifyable is the most appropriate method... lacking a `sudo` equivalent in windows, you'd have to do an escallation request if you wanted to do otherwise in order to do administrative writes.

Alternatively, keep it like it is, but really this should be under local, not the roaming profile, as global modules are specific to the computer...  binary modules in particular are just not that portable (node version differences, and x86/x64 mostly).

See: http://stackoverflow.com/questions/9518890/what-is-the-significance-of-the-programdata-folder-in-windows

While I like the idea of installing to ProgramFiles, the fact is that the windows environment since vista says your applications really shouldn't be doing this... ProgramData is the correct place... You can create a subdirectory with "modify" access for "Administrators" if you want to restrict `nom i -g` to admin users, without requiring an admin console...  Or you can require privilege escalation which requires an admin console, or a bit more complexity in node/npm to support it.

**Comment by yamlfd** [comment]
My last posting noted programdata not programfiles. 

I have an MST and config cab ready that changes all the required stuff including permissions in programdata. Setting permission in programdata works, but only if there are windows default permussions. Wix is able to alter permission what msi permission table cannot.

Let me know if you are interrested.

**Comment by robertbaker** [comment]
+1 for %programdata%

**Comment by robertbaker** [comment]
@yamlfd please do a PR, they are interested!

**Comment by yamlfd** [comment]
What is a PR?

**Comment by robertbaker** [comment]
@yamlfd You need to made the changes against the repositories by forking the repository, making the changes and submit a pull request.

**Comment by JamesBewley** [comment]
How do I move the global stuff out of the roaming profile?

Does anybody have a workaround for this issue?

**Comment by tracker1** [comment]
@JamesBewley if you're in a newer version of windows, you should really use `%ProgramData%` not `%ProgramFiles%` as your path... you'll have trouble doing `npm install -g ` to `Program Files` path.

**Comment by ederkley** [comment]
I agree that npm-cache belongs in LocalAppData.
However, for my part, I am also for locating the npm folder under Program Files rather than ProgramData.  We use application white-listing and non-admin user accounts.  Anywhere that a normal user account can create, modify or copy files such as ProgramData means we don't want to allow executables to be able to be run from there, including the npm .cmd files.  We will therefore have to run "npm install -g" from an elevated command prompt when installing modules (ideally it would prompt for admin credentials if run from non-elevated command prompt). 
Another way would be to include hashes of the npm .cmd files in the application white-listing policy so they could run from ProgramData as long as they were unchanged but then you need to maintain the application white-listing policy for any new .cmd files or when they are legitimately changed by an upgrade...
I can definitely see a need for options to install to either Program Files or ProgramData depending on local security requirements...

**Comment by Grauenwolf** [comment]
It's been 28 months since this was first reported. Can we get it fixed already?

**Comment by ramreddy26** [comment]
+1 for %programdata%

**Comment by Grauenwolf** [comment]
29 months. That's a long time for what should be a one-line change. Stuff like this is why I don't trust the Node community.

**Comment by yamlfd** [comment]
As things are not moving here I'm attaching an interim solution for all. It could work for newer versions of node JS, but has not tested yet. Copy the MSI to the root folder like node-v4.2.1-x64.mst. NodeJS will be installed to a Programs Group "Development" (custom non-standard).

[nodejs-4.2.1-MST.zip](https://github.com/npm/npm/files/263018/nodejs-4.2.1-MST.zip)

**Comment by Trott** [comment]
@othiym23 wrote:

> This has been moved to the npm roadmap, which we're using instead of the confusing next-* labels now.

I'm looking in the roadmap doc, but I'm not seeing it. The closest I can find is [this](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-windows) but that's not it. Did this maybe fall through the cracks at some point?

**Comment by othiym23** [comment]
It would be really cool to get some guidance from Microsoft, who originally helped determine where things are put on Windows, around the right thing to do here. Keep in mind that there are migration costs to making changes here; we don't want to move where stuff is stored while leaving many megs of stuff in another location. The CLI team has no objections to moving stuff out of roaming profiles and into another location. We just want to minimize confusion and potential support hazards for users.

@jdalton, is there anyone you can connect us to on the Windows team who can give us the definitive word here? This has been open for a while, and it would be nice to convert this into something actionable soonish.

@Trott the road map's a little stale and needs a little of my love; there is a section for [platform integration](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-windows) where this should be filed, but it hasn't gotten there (yet).

**Comment by jdalton** [comment]
@othiym23 Thanks for the ping. I'll find someone to give the word.

**Comment by yamlfd** [comment]
I remember that the lead developer of WiX team (who was a ms developer) had no idea what roaming profiles are, never heard of folders "excluded from roaming" and that a msi setup must never install a software to local app data... He pointed me to technet articles that has not explained this and used it as false arguments to prove his arguments. Maybe MS is not automaticall a reliable source for correct answers... As I know this local app install example still exists in WiX and my case has not fixed yet...

**Comment by Zoltu** [comment]
I imagine if you get in touch with the right people they will give you the right answers.  However, @yamlfd is correct in that these details are not universally known at MS (I don't believe proper Windows folder locations is part of their onboarding process).  Even VSCode currently uses the wrong folder (though they have an issue out to resolve it there as well https://github.com/Microsoft/vscode/issues/7035)

**Comment by jdalton** [comment]
@bitcrazed Do you have any guidance on a Windows 7/8/10 path for the global npm installs?

**Comment by phestermcs** [comment]
I was employed by MSFT for 11 years, as one of their top consultants, that their biggest enterprise customers engaged for months, to a year, or more, to help architect & develop all kinds of solutions in heterogeneous environments, using just about everything MSFT made. If you give me the benefit of the doubt that's true, then maybe my thoughts and recommendations below will help.

1. The purpose of the `AppData` folder is to store application-specific data, on a per-user basis. Ok, so what exactly does that mean? It means any information in any format, _that is not an entry point into execution_, could be stored under `AppData` and is most ideally configuration information set by the user, like the positions of windows in an application, etc. That means `exe's`, `bat` files, `scripts`, etc, should never be stored under `AppData` under any circumstance, period. You could, in theory, store bits that end up getting executed indirectly, but that would be a bad practice, as there are more appropriate places to put such things.
2. `AppData/Roaming` is meant to facilitate sharing application-specific data, on a per-user basis, across multiple machines. This has nothing to do with whether or not some application/executable is actually installed on a given machine. 99.99% of enterprise user's do not use this feature, as they have one machine they use everyday (often with some 'base' suite of applications installed by IT, and a couple additional applications installed by the user). Some IT folks might use this feature in some cases, but that's rare. The most common use case is for situations were a user can access any machine from a pool of machines, where each machine has had the identical set of applications installed by the IT department; i.e. training class rooms, support call centers, etc.
3. `ProgramFiles` is the intended location to store executable/application entry points, that can be launched by any user of the machine, given they have appropriate permissions. However, it's also intended that only signed .msi installers actually copy bits to this location. This is to mitigate risk of executing malicious, virus infected code. It's typically locked down so that normal users can't do anything to it, and Administrator users must give permission anytime the try to make a change. 
4. `ProgramData` is intended to store user agnostic, configuration/cache type data, on a per-application basis. Its typically locked down like the `ProgramFiles` folder.

So, in Windows, where should npm put stuff and look for stuff if it was to be 'fully Windows compliant', or 'correct'?

1. For `npm -g i`, the 'correct' location is under `ProgramFiles`. Any user that has appropriate permissions can run commands that have previously been installed with `-g`. 
2. For `npm built in config`, the hypothetical 'correct' location would be under `ProgramFiles`.
3. For `npm config edit -g` (global config), the 'correct' location would be putting the `npmrc` file under `ProgramData`.
4. For `npm config edit` (user config), the 'correct' location would be to put an `npmrc` under `AppData/Roaming` (i.e. not a `.npmrc` under the user's home directory, contrary to 'nix convention).

Issues with being 'correct':

1. For `npm -g i`, well, I believe it's a best practice that installing anything executable should only be done with Administrative privileges. Yes, it can be irritating to have to `sudo` all the time for that, but given that the frequency of installing things is pretty low, and that it helps mitigate malicious code from being installed by something else, I'm ok with that, but that's me (that, and other practices, have kept my many machine's with various O/S's virus free for almost 30 years!! knock on wood). However, Windows doesn't come with a command comparable to `sudo`, which makes it a bit more irritating to run things with elevated privileges. I have `Command Prompt` pinned to my taskbar, and when I need to run elevated, I right click on the `Command Prompt` icon, then right click again on the menu item `Command Prompt`, and then select `Run as administrator`. There's also a `sudo` like command written in node [here](https://www.npmjs.com/package/windosu). Lastly, if you really don't like having to `sudo` to install, you can go to `ProgramFiles`, and make yourself the owner of the `nodejs` folder, and then give yourself full permissions on that folder (assuming npm continues to install itself there).
2. For `npm config edit -g`, well pretty much the same story as `npm -g i`; except if you don't want to have to `sudo`, you could make yourself the owner of the `ProgramData\nodejs` folder (which doesn't exist today, but would if wanting to be 'fully Windows compliant` and npm stuff still lived under node).
3. For `npm user config`, the 'correct' location would be `AppData\Roaming\npm\npmrc`. This lets the user-specific config move with the user if they were to use another machine, like in a training or classroom setting. However, it's a fairly accepted thing that in Windows, 'nix like commands having user specific config put that under the user's home folder in `.` prefixed files, so if it ain't broke, don't fix it.

**Comment by phestermcs** [comment]
SECURITY UPDATE:

So, it's normally a best practice to only let admins install executables, **_but only if the install is from a trusted source_** (i.e. signed).

Regarding my previous recommendation of running `npm i -g` with elevated permissions, **_I'm now taking that back_**, because anyone can publish anything to the npmjs registry, and npm will happily run any lifecycle scripts, and it's probably not the best idea to let those scripts run with elevated permissions.

Therefore, while `npm` should still be installed to ideally `C:\Program Files\npm`, the npm installer should relax permissions on `npm` so that any user can essentially run `npm i -g`.

This means you wouldn't have to `sudo` to `npm i -g`, which will probably make some of you happier.

I'm writing a little app, `npm-in-win`, that will correctly fixup an npm install on Windows, putting everything in its place, with appropriate permissions. This can eventually be incorporated into `npm`s install lifecycle. For now, whenever you install node, or update npm, you can just run `npm-in-win` and things will be where the belong for Windows (i.e. nothing in AppData).

**Comment by phestermcs** [comment]
I'm about 3/4's through a cmd script that will 'fix' an npm install so that its pieces and parts are put in the most appropriate place for Windows, with permissions set accordingly, and settings, npm-cache, and global installs all 'migrated' correctly.

It would be ideal for anyone who's receiving complaints from their IT departments about the size of their roaming profiles. It might be helpful to those who sometimes have permission issues when running `npm i -g`, and don't really understand why. It also fixes a quirk with how `npm` launches, were it actually runs twice; once to read its `prefix` config setting, and then again to launch itself from the location specified by the `prefix` setting, which just make it seem 'slow'. 

If all you've ever done to install `npm` is to either run the `node` installer, and then maybe run `npm i -g npm` to get the latest version, it will work just great. If you've tried tweaking any config settings, specifically `userconfig`, `globalconfig`, `cache`, `prefix`, it will still work just fine, and will  preserve any other settings you may have changed. If you are running several versions of node and/or npm for some reason, or have a more 'exotic' arrangement, it's probably not an option.

But, my basic question is, are there several of you out there that would actually want this? 

Just kinda double checking before I complete and open myself to resolving issues, etc.

Let me know?

**Comment by mgancarzdsi** [comment]
I would find it useful in the longer term, but in the short term aren't actually using npm for any projects, so would not be able to utilize it right away.

**Comment by yamlfd** [comment]
Highly interrested in this. Maybe I can do a MST with all your changes than.

**Comment by phestermcs** [comment]
There doesn't quite seem to be a flood of demand here, nor interest from any npm member or contributor :(.

@mgancarzdsi, @yamlfd I'm more than happy to help by answering any questions, but for now I'm going to hold off completing something to automate fixing npm installs on Windows.

FWIW, it would only take a couple of minutes to manually do this.

**Comment by yamlfd** [comment]
Can you share your batch, please? There is a high demand on getting all this stuff resolved.

**Comment by robbforce** [comment]
Did you ever receive the script? I've been going through the pains of creating a centralized install of node and npm, since it's hosted on a shared windows server, and I'm very interested in this script.

**Comment by bitcrazed** [comment]
@jdalton Sorry for missing your ping on this thread. My thoughts are as follows and echo @mgancarzdsi's opening point:

%programdata% is for storing program/app data that is not user-specific. This is not somewhere to store a user's packages and/or package config data.

%appdata% is for storing user data that needs to roam across machines. One should take GREAT care to only store the bare minimum data necessary in this location otherwise the user's storage footprint, network bandwidth consumption, and login-times will all suffer. This is generally the wrong place to put packages.

%localappdata% is for storing non-roaming/local user app data. This is generally the right place to put tool configuration data, packages, etc.

FWIW, my %appdata% folder is ~520MB (already too big by my reckoning) and my %localappdata% is ~20GB! Glad it's not the other way around or it'd take aeons to login to my PC ;)

HTH.

**Comment by yamlfd** [comment]
In a propper roaming user profile environment the appdata is redirected to a server. That means data does not roam on logon/logoff. It stays there. But yes, it requires space.

Localappdata get's automatically deleted if properly configured. I just need to logoff and localappdata goes to /dev/nul. You can only safe temp data there or data that has high i/o rates. However - always expect this folder to be deleted on user logoff.

**Comment by MicahZoltu** [comment]
@yamlfd I don't believe those statements are *quite* true.  `%LOCALAPPDATA%` has a lifetime of the machine it is running on, more or less.  In some environments machines are wiped regularly (daily, after each use, etc.) so in these cases the lifetime of the machine is very short.  This is common in school lab environments, public libraries, etc. where one desires the machine to be in a "fresh" state every time a new user uses it (avoids having to deal with keyloggers and such).

`%APPDATA%` is intended to be synchronized across multiple machines in environments that support it.  The default way to do this is to sync on login/logout which is why a large `%APPDATA%` folder will result in long login times as the server has to download the entire thing at startup.  I believe modern versions of Windows have optimized this a bit and do a diff rather than a full copy, though this only works if the machine isn't wiped/cleaned regularly (see school environment above).

For anyone with their own computer (domain or not) `%LOCALAPPDATA%` is unlikely to be wiped regularly.  I would argue that this is the case for most developers.  Many developers however *are* on a domain (work environments) where `%APPDATA%` is synced regularly.  For these two reasons (beyond the general Microsoft recommendations) I would argue that `%LOCALAPPDATA%` is the appropriate place for large things, like NPM caches and NPM installs.  While it is nice to think about your everything following you around in `%APPDATA%` , the realities of the world are that bandwidth is not unlimited/free and sync time is non-trivial.  Since NPM modules are often non-trivially sized, I think a reasonable default is `%LOCALAPPDATA%`.  Of course, I strongly support making this configurable via environment variables, so the user can choose the pattern that makes the most sense for them.

**Comment by yamlfd** [comment]
@MicahZoltu: You gave the examples... Everyone using roaming profiles should have the policy "Delete cached copies of roaming profiles" enabled and also "Exclude directories in roaming profile" - not only school lab environments, public libraries, etc. "Exclude directories in roaming profile" by default excludes %LocalAppData% and should be enabled. This is best practice and will wipe all away on logoff.

You should also redirect APPDATA to a server home drive. Therefore your APPDATA is not copied from / to the server on every logoff for bandwidth reasons. This is also BEST practice.

The software need to expect this. You may not have "Delete cached copies of roaming profiles" enabled or use the new feature that will clean this after 7 days, but it does not change the general allowed situation the software currently does not handle properly.

If computers are used by multiple users and users can sit everywhere you have this issue - LocalAppData get's wiped and this is good.

**Comment by brianary** [comment]
This seems like the relevant best practice document: [Store and retrieve settings and other app data - UWP app developer | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/app-settings/store-and-retrieve-app-data)

**Comment by MicahZoltu** [comment]
@brianary That document is for Windows universal apps, which are different from traditional desktop apps (like npm).

**Comment by brianary** [comment]
@MicahZoltu Is there any reason to expect usage of those directories to differ by the type of app, or is it more likely this is a systemic idiom of the platform?

**Comment by MicahZoltu** [comment]
They use a lot of similar nomenclature in UWP as the legacy filesystem, and in general the advice is sound.  None of the code examples or snippets are relevant though.  I guess on further thought, if you only read the prose text and ignore the specifics of things, the advice is good and generally applies to legacy Windows apps.

**Comment by brianary** [comment]
I probably should've been clearer in suggesting only the descriptive text guidance.

**Comment by obedm503** [comment]
too important to be bot-closed

**Comment by mgancarzdsi** [comment]
Agreed as original reporter. The reality is that different environments will have slightly different uses of %APPDATA% and %LOCALAPPDATA%, some being redirected, some being uploaded/downloaded on logoff/logon and some additionally deleting.

But let's just pick one that doesn't put prefix and cache in %APPDATA% and provide a workaround for the other environments like that one that does delete %LOCALAPPDATA% regularly?

**Comment by MicahZoltu** [comment]
I believe the process is to create a new issue and link back to this one in the issue description.  I suspect the reason for this process is to increase the barrier to entry of re-opening issues closed by the bot.

**Comment by mgancarzdsi** [comment]
The epic goes on in #17325 !
