### ISSUE TITLE
passing unix signals to child rather than dying?

### ISSUE THREAD

**Issue by evantahler** [npm/npm#4603]
Here's some interesting behavior I've seen when running an application which does some slower shutdown operations when receiving a termination signal.  

When running `npm start` in a *nix terminal (tested on ubuntu and OSX), the `SIGINT` (ctrl+c) command is passed from the parent npm process to the child (my running application).  npm instantly exits, and then my application handles the passed-down signal and eventually exits.  However, because the stdout/err of the session was managed by npm, strange things can happen if my application still writes (or `console.out`s).  

At the very least, the terminal which started the application will interpret the npm process' death as a return and draw the next line.  However, the child's stdout is still bound to that session.  This means you can start another application in that same terminal and still get the first app's messages intermingled.   Or, more strangely, if you then close that terminal session, the underlying app which is still running and possibly trying to write to stdout is likely to crash on the next `console.log`.

You can emulate this pretty simply:

**package.json**
```javascript
{
  "name": "test",
  "scripts": {
    "start": "node ./app.js"
  }
}
```
**app.js**
```javascript
process.on('SIGINT',  function(){ console.log("SIGINT");  shutDown() });
process.on('SIGTERM', function(){ console.log("SIGTERM"); shutDown() });

var string = ".";

var shutDown = function(){
  console.log("off-ing...");
  string = "x";

  setTimeout(function(){
    console.log("bye!");
    process.exit();
  }, 1000 * 60);
}

setInterval(function(){
  console.log(string);
}, 500)
```

1) start `app.js` with `npm start`
2) `ctrl+c` in the window you started npm with.  You will see npm exit, but still receive messages from `app.js`.
3) have fun opening vi or some other application in the same window.

I *think* a possible solution to this would to have npm catch (`process.on('x')`) and not actually exit until the child process exits and pass those commands along to the child... but I'm sure that will cause all sorts of other problems.  

Thoughts?

**Comment by stuartpb** [comment]
Okay, this is a fairly significant problem for me, as it means that any apps I'm developing to use `npm start` don't get stopped when they're supposed to (in other words, every deploy I do keeps me waiting for 10 more seconds than it should as it waits for the app to respond to a SIGTERM it never gets, then force-kills the entire process group).

Does Node not provide any mechanism for accessing the process-replacing `exec()` call used by `bash  -c`?

**Comment by kimmobrunfeldt** [comment]
Please fix this issue. Otherwise `npm scripts` is a good way to organize tasks, but this issue makes the usage a bit unexpected.

Concurrently would need this NPM feature. Explained more here: https://github.com/kimmobrunfeldt/concurrently#npm-issue It's still [on-going issue](https://github.com/kimmobrunfeldt/concurrently/issues/4).

**Comment by stuartpb** [comment]
I'd appreciate if everybody affected by this issue on Heroku would back my pull request to fix it by copying `run` from package.json instead of using `npm start`: heroku/heroku-buildpack-nodejs#217

**Comment by ihsw** [comment]
`npm start` is pretty much worthless at this point, particularly when it comes to using it with Docker as the `CMD` instruction.

**Comment by JustinBeckwith** [comment]
+1 to this being a problem.  Google App Engine defaults to using `npm start` to running node processes via docker, as it's been a pretty convenient standard (instead of a procfile):
https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/base/Dockerfile

We'd like to use SIGTERM to propagate a signal down to the node processes running in the container - right now, I can't get it to work and this seems like the culprit.

**Comment by justjake** [comment]
I was just bit by this -- I use some `npm run` scripts to start some mock services as part of my integration tests, but in my CI system, killing the `npm` processes does not terminate the mock services, so they keep running after the end of my tests! Very frustrating.

**Comment by dtryon** [comment]
+1 using node docker images with `npm start` would be nice.

**Comment by jdfreder** [comment]
+1

**Comment by mattfysh** [comment]
+1 - this took a whole day to track down hehe.
Goodbye Tuesday December 22nd 2015, I guess I'll never get those hours back again ;)

**Comment by justjake** [comment]
An easy work-around is to always spawn `npm run` as a process group leader. Then when you want to kill the `npm run` task, you can kill the PGID instead to send your signal to all the processes in the group.

This is Ruby from memory:

```ruby
pid = Process.spawn('npm run build', :pgroup => true)
# pgid is usually the same as pid but better safe than sorry 
pgid = Process.getpgid(pid)

# kill with negative value to send signal to group
Process.kill(-1 * pgid)
```

**Comment by mlegenhausen** [comment]
+1

**Comment by andrenarchy** [comment]
@othiym23 would it be feasible to introduce an option for passing (or not passing) signals to child processes?

Oh, and I just burned 3 hours while dockerizing a node app before finding this.

**Comment by othiym23** [comment]
@andrenarchy Why are you using npm as a task manager within Docker? That's an extra node process per container doing almost nothing. I'm sorry about the lost 3 hours – that would frustrate me as well.

> would it be feasible to introduce an option for passing (or not passing) signals to child processes? 

This isn't behavior that it makes sense to make configurable – if it's going to do this, it should do it all the time. However, there are a couple other considerations I didn't include above, of which the most significant is

> An easy work-around is to always spawn `npm run` as a process group leader.

This is an easy workaround on operating systems that have a concept of a process group leader. Notably, Windows doesn't. It's not a requirement that npm have total parity across the OSes it supports, but it does point to the fact that this isn't as simple to do as it might seem at first.

That said, and taking into account everybody's feedback, I'm going to close this feature request now, because this isn't something that the team is going to have time to get to in the next 6-12 months. `npm start` / `npm stop` / `npm restart` are handy and convenient, but they're not substitutes for a dedicated process manager. If somebody wants to submit a patch that handles this behavior for both UNIXy systems and Windows, we'll land it, but the team isn't going to do it themselves. Thanks to everybody for their feedback!

**Comment by andrenarchy** [comment]
@othiym23 I just used what I've always been using ;). Furthermore, I don't like to repeat information: the `main` property in `package.json` already holds the information about which file should be started. btw: the official [Dockerizing a node app guide](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/) also uses `npm start`.

**Comment by mattfysh** [comment]
Last but not least ;)

**Comment by stuartpb** [comment]
When I complained about this in https://github.com/heroku/heroku-buildpack-nodejs/issues/217, Heroku said they refuse to use anything *but* `npm start` as the task runner for starting an app. This makes it really frustrating to run apps in 12-factor environments, since both sides are passing the buck on who should be responsible for running the server.

**Comment by daniel-pedersen** [comment]
@othiym23 As I see it, dockerized node apps and most general node images run `npm start` since it simplifies configuration, especially in development. In a production image, I would agree that the npm process is redundant and the script that is run by npm can be simply be hard-coded into the image. I also agree that passing all signals to the child would practically mean making npm into a full-fledged task manager.

However, lifecycle orphanizing child processes (i.e. not passing SIGTERM) could be considered a bug, which is why I'm hoping to get it fixed (#10868). This also solves most of the problems that people run into with using npm with docker.

**Comment by jephir** [comment]
If you want *SIGTERM* to work properly in Docker with `npm start`, you can use an init system. See https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-stop

For example, in your **Dockerfile**:

```Dockerfile
RUN wget https://github.com/Yelp/dumb-init/releases/download/v1.0.0/dumb-init_1.0.0_amd64.deb
RUN dpkg --install dumb-init_*.deb

CMD [ "dumb-init", "npm", "start" ]
```

**Comment by daniel-pedersen** [comment]
Great point, and that's what I've been doing. But in my opinion it's an unnecessary extra dependency that's only there to fix npm orphanizing it's child processes.

**Comment by zkat** [comment]
Note: I've decided, after some discussion, to omit the patch in #10868 from the LTS release, and explained my reasoning there, which y'all are welcome to discuss. This does mean that if you need this behavior fixed, you'll have to upgrade to `npm@3`

It's still gonna go into the main release, of course :)

**Comment by elliottsj** [comment]
Using npm@3.10.6 on OS X, I'm experiencing the same issue originally described:

>When running npm start in a *nix terminal (tested on ubuntu and OSX), the SIGINT (ctrl+c) command is passed from the parent npm process to the child (my running application). npm instantly exits, and then my application handles the passed-down signal and eventually exits. However, because the stdout/err of the session was managed by npm, strange things can happen if my application still writes (or console.outs).

However, my use case is running developer tools locally (e.g. `npm run build:watch`), not running `npm start` in a production environment, so using an init system or some other process manager isn't ideal.

**Comment by aoberoi** [comment]
i'm in the same boat regarding running my app in docker and wishing the SIGTERM would be passed down. i really would like my `package.json` to be the source of truth about how to start my app, and I don't want to maintain any changes I make in both that file and my `Dockerfile`.

**Comment by twang2218** [comment]
I think this issue should be reopened, as it's not working in docker now.

**Comment by scriptype** [comment]
Not working in Cygwin either. This causes child processes to stay open after the main process killed by Ctrl-C.

Running
 - a script directly with `node script.js` is able catch SIGINT in every case (iTerm2, cmd.exe, Cygwin).
 - a script through npm scripts like `npm run my-script` is same, except when run in Cywgin.

I have this issue in my project, related to this: https://github.com/scriptype/salinger-basic-boilerplate/issues/5 (turned into a monologue).

```
uname -a # Cygwin version
MINGW64_NT-6.1 ITDEV03 2.6.1(0.306/5/3) 2017-01-20 15:23 x86_64 Msys

npm -v
4.1.2

node -v
v7.5.0
```

My test script:

```js
process.stdin.resume()

process.on('SIGINT', _ => {
  console.log('will be closed in 5s')
  setTimeout(_ => {
    process.exit()
  }, 5000)
})
```

**Comment by sandys** [comment]
@twang2218 are you still having this issue ? im currently seeing this in docker myself. ubuntu 16.04 vm.
node v7.5.0 
npm v4.1.2

**Comment by bsc1780** [comment]
josondata20202020-brandonsapps:jasonagent-go

**Comment by bsc1780** [comment]
josondata20202020.agent-go

**Comment by pfdgithub** [comment]
i have a similar problem  
```
windows 7 x64  
node v6.11.2  
npm 3.10.10  
```
when I use ```npm run xxx```, ```ctrl+c``` can't kill the child process.

**Comment by slavik57** [comment]
Same here on:
windows 10 x64
node v8.4.0
npm v5.3.0

**Comment by Jokero** [comment]
It's a bug :smile:

**Comment by OmgImAlexis** [comment]
@othiym23 can this be reopened?

**Comment by cjoulain** [comment]
The CLI team encourages you to visit #npm via https://package.community for further discussion.

**Comment by willxy** [comment]
I'm experiencing the same problem here.  I'm needing my npm script to receive the INT, not be caught by npm.

**Comment by goldbergyoni** [comment]
For most of Node.JS developer, running "npm start" is an hassle-free way to initiate Node.JS apps. In the era of Docker & K8S, it doesn't make sense that a container/pod won't receive signals and can act before closing. Please fix this
