### ISSUE TITLE
npm publish: suggest name in lowercase

### ISSUE THREAD

**Issue by gr2m** [npm/npm#4627]
I just tried to publish a package with the name `moment.parseFormat`, which errored with

```
forbidden New packages must have all-lowercase names: moment.parseFormat
```

The package.json was created using the `npm command` though, I guess it takes the name of the folder and suggests it as the package name. I'd suggest that it a lowercase name per default (preventing the user to set it to an uppercase name with the error above)

**Comment by zeusdeux** [comment]
:+1:

**Comment by othiym23** [comment]
This would be useful and would remove a footgun that occasionally catches up users. At the same time, since it's a relatively small UX issue, this isn't something that's going to make it to the head of the CLI team's task list anytime soon. As a result, I'm following the team's policy of marking it as `patch-welcome` and closing it – if somebody wanted to put together a patch to `npm-package-init` to do this, we'd be happy to work with them to get it merged. Thanks for your time!
