### ISSUE TITLE
show package size before installing

### ISSUE THREAD

**Issue by anio** [npm/npm#4638]
Can we get size of an package and needs before install?
I think we need to an command like it:
~$ npm size ant
ant size : 8MB

**Comment by othiym23** [comment]
This would require support on the registry side in order to know the installed size of a package before downloading and installing it locally, so I'm going to close this, and point readers at [`npm/registry`](https://npm/registry/issues), which is where this request should be transferred if people are still seeing it implemented. Thanks for your time!
