### ISSUE TITLE
npm ERR! Error ENOTDIR 

### ISSUE THREAD

**Issue by lionelgmc** [npm/npm#4648]
![grunt 5](https://f.cloud.github.com/assets/4058603/2136562/aacfed7e-9314-11e3-9c51-8f36c1c77ebf.gif)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'cache',
1 verbose cli   'clean',
1 verbose cli   '-f' ]
2 info using npm@1.2.2
3 info using node@v0.8.18
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 error Error: ENOTDIR, readdir 'C:\Users\lionel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-marrs-node-findit-git-3daed8d7\objects\pack\pack-def5b56e68db1299f8a656bbdaaeadf12cb667d7.idx'
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Windows_NT 6.2.9200
8 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "cache" "clean" "-f"
9 error cwd C:\Users\lionel
10 error node -v v0.8.18
11 error npm -v 1.2.2
12 error path C:\Users\lionel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-marrs-node-findit-git-3daed8d7\objects\pack\pack-def5b56e68db1299f8a656bbdaaeadf12cb667d7.idx
13 error code ENOTDIR
14 error errno 27
15 verbose exit [ 27, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.2.2. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Hmm... `n` is getting a little long in the tooth, and I don't know how good it is on Windows. If you ever come back to this, @lionelgmc, I suggest seeing if `nodist` works better for you; it's what I use and has been problem-free with npm stuff.

For now, I'm closing this issue as abandoned.
