### ISSUE TITLE
npm install sails-mongo fails

### ISSUE THREAD

**Issue by marcdv** [npm/npm#4683]
Hi

I'm getting an error running the above command on Windows 7 64bit.  My nmp version is 1.3.24 and Nodejs version v0.10.25.  Any help would be greatly appreciated!

The log file ends with:

```
1510 error Error: spawn ENOENT
1510 error     at errnoException (child_process.js:988:11)
1510 error     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
1511 error If you need help, you may report this *entire* log,
1511 error including the npm and node versions, at:
1511 error     <http://github.com/isaacs/npm/issues>
1512 error System Windows_NT 6.1.7601
1513 error command "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sails-mongo"
1514 error cwd D:\IT\Projects\swordfish
1515 error node -v v0.10.25
1516 error npm -v 1.3.24
1517 error syscall spawn
1518 error code ENOENT
1519 error errno ENOENT
1520 verbose exit [ 1, true ]
```
thanks
Marc

**Comment by smikes** [comment]
Is this still a problem for you?

Do you have git, Python 2.x and Visual Studio 2012 (or later) installed and in the path?  `npm` may be trying to build a native module.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
