### ISSUE TITLE
Dependency issue 

### ISSUE THREAD

**Issue by henrytao-me** [npm/npm#4693]
Hi all,

I am using sailjs which depending express@3.4.7. In root sailsjs folder, I used "npm install". All packages were installed pretty well, except express :| which depending cookie@0.1.0.

When I ran server with "grunt server", it fired the error 
"Fatal error: Cannot find module 'express/node_modules/cookie'"

I didn't find cookie module in express/node_modules.

I found that the reason was I just added cookie@0.1.0 in root package.json which I used it for testing sailsjs API.

So, how can I keep depending cookie@0.1.0 in sailsjs (root) package.json and express/node_modules?

Thanks for helping!
Henry

**Comment by smikes** [comment]
@henrytao-me , is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since February 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
