### ISSUE TITLE
suggestion: make npm list use --depth=0 by default

### ISSUE THREAD

**Issue by pgilad** [npm/npm#4747]
I find that I almost never list packages (either global or local) and want to see more than `--depth=0`.

For the rare cases that I do, I can use `--depth=10` (or whatever).

I suggest on making the `list` command use `--depth=0` by default unless otherwise stated

**Comment by chevex** [comment]
+1 for this. The config option works great but it does seem that a default depth of zero would be more intuitive for new installs. The option is still there if you do want to see the tree.

**Comment by othiym23** [comment]
`npm outdated` (and by extension `npm update` / `npm update -g`) now default to `--depth=0`. That makes sense for the common case. Changing `npm ls` to `--depth=0` by default does not, because it breaks the _very useful_ property of allowing you to easily see if there are issues in your dependency tree. This isn't a change that makes sense to make to the defaults. `npm config set depth 0` will do the trick, if that's what you want.

**Comment by twome** [comment]
I think people that are checking issues in their dependency tree by visually scanning through their entire tree, rather than just checking the npm warnings/errors at the bottom of the `npm ls` printout, would be *vastly* outnumbered by the people just looking to see what's installed in their project. To add, I'd wager power users who are doing that kind of thing would be much more likely to know to just change their config.

**Comment by aadrian** [comment]
+1
