### ISSUE TITLE
global installations fail with EPEERINVALID when completely unrelated modules have peer problems

### ISSUE THREAD

**Issue by sam-github** [npm/npm#4749]
Example output below. Note that node-inspector does not depend on or use loopback in any way. I'm still tracking down what the loopback problem is, but I'm sure its unrelated to node-inspector.

Also, node-inspector, despite the dire error, installed fine, and works fine.

```
$ npm install -g node-inspector
[...]
npm http 304 https://registry.npmjs.org/string_decoder
/usr/local/bin/node-inspector -> /usr/local/lib/node_modules/node-inspector/bin/inspector.js
/usr/local/bin/node-debug -> /usr/local/lib/node_modules/node-inspector/bin/node-debug.js
npm ERR! peerinvalid The package loopback-datasource-juggler does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer loopback@1.6.2 wants loopback-datasource-juggler@~1.3.0
npm ERR! peerinvalid Peer loopback-connector-rest@1.1.3 wants loopback-datasource-juggler@1.x.x
npm ERR! peerinvalid Peer loopback-connector-oracle@1.1.5 wants loopback-datasource-juggler@1.x.x
npm ERR! peerinvalid Peer loopback-connector-mongodb@1.1.5 wants loopback-datasource-juggler@1.x.x

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-inspector"
npm ERR! cwd /home/sam/p/wiki
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sam/p/wiki/npm-debug.log
npm ERR! not ok code 0
```

**Comment by kulicuu** [comment]
I am encountering this issue.  I have a repository with a submodule : framework and associated app.  The app/submodule invokes repository/framework via link.  I have a reflector set up in another folder universe which is a clone of same framework -- idea to point to different branches-- and again clone the submodule app.  But we have an `npm link` issue here, because we want these distinct reflected apps to require distinct corresponding dependencies.  Guessing an `npm link` solution not close at hand, figured to just make the reflector app invoke its framework dependency by relative path in `package.json` and `npm install` normally.  But before adding that line to `package.json` running `npm install` and getting OP's error.

**Comment by busches** [comment]
Is this still an issue in the latest `npm`? @KenanY

**Comment by bagadim** [comment]
Yes. Just got it.
![image](https://cloud.githubusercontent.com/assets/10193153/19230845/52c7dbae-8edf-11e6-8a85-97bd45c19d66.png)
