### ISSUE TITLE
could not install packages globally with package.json in global node directories

### ISSUE THREAD

**Issue by trinonsense** [npm/npm#4827]
I created a symlink for a `package.json` in the global `npm` directory, like so:

	/usr/local/lib/package.json -> ~/path/to/my/dotfiles/package.json

Then I ran these commands to install global node packages from the `package.json` symlink:

	cd /usr/local/lib
	npm install -g

...and then I get this error

	npm ERR! System Darwin 13.0.0
	npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "install" "-g"
	npm ERR! cwd /usr/local/lib
	npm ERR! node -v v0.10.26
	npm ERR! npm -v 1.4.3
	npm ERR! path /var/folders/22/9byr5_b10xn9rmxd0y_fnxpw0000gn/T/npm-16102-CRdnP8aI/1393805630684-0.25814521964639425/package/package.json
	npm ERR! code ENOENT
	npm ERR! errno 34

I first tried running `npm install` without the `-g` flag, the packages were downloaded and placed correctly, but the package symlinks for executables and man pages were not properly [set as a global install](https://www.npmjs.org/doc/files/npm-folders.html#Executables)

## Questions

* What is causing that error and what is the solution?
* Is there a better method to achive the same goal?

**Comment by smikes** [comment]
@trinonsense , Is this still a problem for you?

This is an unusual use case -- did you try the approach @isaacs  suggested above, or did you change the way you were using `npm`?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.3. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
