### ISSUE TITLE
Having issues downloading npm modules - CERT_UNTRUSTED

### ISSUE THREAD

**Issue by bkbartonDesign** [npm/npm#4838]
Within the last week I have had issues with loading grunt modules. I read on the npm blog that there was a change to the certificate authority and a few options for fixing the issue were offered. I believe I have attempted all (including installing current version of node) and none have worked.

Here is the edited error log after trying to load grunt-contrib-concat after installing current version:
```
Error: CERT_UNTRUSTED
at SecurePair.<anonymous> (tls.js:1370:32)
at SecurePair.EventEmitter.emit (events.js:92:17)
at SecurePair.maybeInitFinished (tls.js:982:10)
at CleartextStream.read [as _read] (tls.js:469:13)
at CleartextStream.Readable.read (_stream_readable.js:320:10)
at EncryptedStream.write [as _write] (tls.js:366:25)
at doWrite (_stream_writable.js:226:10)
at writeOrBuffer (_stream_writable.js:216:5)
at EncryptedStream.Writable.write (_stream_writable.js:183:11)
at write (_stream_readable.js:583:24)
If you need help, you may report this *entire* log,
 including the npm and node versions, at:
<http://github.com/npm/npm/issues>
System Windows_NT 6.1.7601
command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-contrib-concat" "--save-dev"
cwd C:\<path to folder with gruntfile & package.js>
node -v v0.10.26
npm -v 1.4.3
```
Any ideas? Thanks

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.3. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
