### ISSUE TITLE
Execute 'npm shrinkwrap' ERROR

### ISSUE THREAD

**Issue by MaodiTian** [npm/npm#4843]
This is npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@1.3.24
3 info using node@v0.10.25
4 verbose node symlink D:\nodejs\\node.exe
5 error Error: Problems were encountered
5 error Please correct and try again.
5 error missing: string_decoder@~0.10.x, required by readable-stream@1.1.10
5 error     at shrinkwrap_ (D:\nodejs\node_modules\npm\lib\shrinkwrap.js:29:15)
5 error     at D:\nodejs\node_modules\npm\lib\shrinkwrap.js:23:5
5 error     at D:\nodejs\node_modules\npm\lib\ls.js:43:30
5 error     at D:\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:119:5
5 error     at D:\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:240:14
5 error     at cb (D:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:48:11)
5 error     at D:\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:240:14
5 error     at cb (D:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:48:11)
5 error     at D:\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:240:14
5 error     at cb (D:\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:48:11)
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/isaacs/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
9 error cwd E:\mok-accountserver
10 error node -v v0.10.25
11 error npm -v 1.3.24
12 verbose exit [ 1, true ]

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.  We will also need the `package.json` and `npm-shrinkwrap.json` files in order to reproduce this problem.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.4. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!
