### ISSUE TITLE
mac : "npm install pomole -g" 

### ISSUE THREAD

**Issue by raymanyu** [npm/npm#4921]
```
Error: shasum check failed for /Users/raymanyu/tmp/npm-14243-DwV6LZIb/1395587310679-0.6681261749472469/tmp.tgz
npm ERR! Expected: 43ca8ad9fe3943489693ab62dce0cae22509d272
npm ERR! Actual:   c8db8e0bb8b4d184464e6c4873eac3cdefe2e284
npm ERR! From:     https://registry.npmjs.org/cliff/-/cliff-0.1.8.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks to me like a bug that was common in older versions of `npm` -- it could be a race condition or a similar problem that caused `npm` to store a broken version of a package in its cache.

The solution is generally to clear the cache and then update npm:

```
npm cache clean
sudo npm install -g npm@latest
```

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since March 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
