### ISSUE TITLE
npm link in centos

### ISSUE THREAD

**Issue by hiwanz** [npm/npm#4933]
i've created my private module under windows,and i tested it use `npm link`,everything worked fine until i moved this module to centos 5.8,`npm link` worked fine too,but when i execute this module,it says 'No such file or directory',what is going on.

[root@localhost uechecker-server]# npm link
/usr/local/bin/uechecker-server -> /usr/local/lib/node_modules/uechecker-server/uechecker.js
/usr/local/lib/node_modules/uechecker-server -> /home/ued/uechecker-server
[root@localhost uechecker-server]# uechecker-server
: No such file or directory

**Comment by smikes** [comment]
Is this still a problem for you?

It looks to me like the problem is a stray carriage return character (\r) at the end of the first script. This is causing the OS to fail to find the `node` interpreter; it's looking for "node\r"

Try running `fromdos` on the text files in your module, or check your `git` settings if you have used `git` to check out the code on your linux machine.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by hiwanz** [comment]
I dont know how could this happened,for the first line of `strace`,there is not a `\r` as you can see.


>[root@localhost ~]# npm -g install npm@latest
>/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
>npm@2.4.1 /usr/local/lib/node_modules/npm
>[root@localhost ~]# strace uechecker-server
>execve("/usr/local/bin/uechecker-server", ["uechecker-server"], [/* 33 vars */]) = 0
>brk(0)                                  = 0xfcef000
>.......
>mmap(NULL, 56467728, PROT_READ, MAP_PRIVATE, 3, 0) = 0x2b2ee9290000
>close(3)                                = 0
>execve("/usr/local/bin/node\r", ["node\r", "/usr/local/bin/uechecker-server"], [/* 33 vars */]) = -1 >ENOENT (No such file or directory)
>execve("/opt/17173/jdk/bin/node\r", ["node\r", "/usr/local/bin/uechecker-server"], [/* 33 vars */]) = >-1 ENOENT (No such file or directory)>

**Comment by smikes** [comment]
The \r isn't coming from your command line; it's coming from the file `uechecker-server`.  Try this

```
$ file /usr/local/bin/uechecker-server
$ cat -v /usr/local/bin/uechecker-server | head 
```

**Comment by hiwanz** [comment]
I've solved this by using the following command,and thx for reminding me of that.

>[root@localhost uechecker-server]# dos2unix uechecker.js 
>dos2unix: converting file uechecker.js to UNIX format ...
>[root@localhost uechecker-server]# uechecker-server 
>Analyzing... /home/ued/uechecker-server
