### ISSUE TITLE
sha1 should no longer be considered secure

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#4938]
Recent advances in cryptography have discovered weaknesses in the SHA1 algorithm, and schneier estimates that by 2021 (in 7 years) it will cost only $43k to generate a sha1 collision.

https://www.schneier.com/blog/archives/2012/10/when_will_we_se.html

That isn't really a lot of money, and npm/node will certainly be in even heavier use in 7 years. I for one would like to see our continue to be useful for a long time.

So, I'd like to suggest that we migrate to sha256 (if not sha256d*)
I figure will be much easier to fix now than later - and it should be a relatively simple manta script, correct?

This would mean that when signed packages are added, you are signing something secure (on that note, we should use ecc, and not rsa when we get to that ;)

* sha family hashes have a weakness that allows you to cheaply calculate `y = sha(x + b)` if you know `sha(x)` without knowing `x`. I'm not sure wether this is something that npm is exposed to, but I think it's good to be belt-and-suspenders safe when it comes to crypto.

**Comment by okv** [comment]
How's it going? Any foreseeable plans about using sha256sum for npm tarballs?

**Comment by othiym23** [comment]
There are two separate things under discussion in this issue:

`sha1` is no longer a preferred option for performing security-related operations on files.
npm doesn’t have a strong notion of provenance for files distributed via the registry.

@rlidwka is correct that shasums are used for integrity validation (and, to a certain extent, for content addressability), rather than attestation, provenance, or repudiation. Therefore, the collision resistance (or lack thereof) is less of an issue than it might otherwise be. Also – and this is even more true now than it was two years ago – the migration from one hashing algorithm to another is nontrivial given the scale of the registry and the version distribution of npm clients out there. It wouldn’t be that tough to write a follower to pull down and rehash existing tarballs, and it wouldn’t be a _huge_ deal to update all the package metadata to include that new hash, but it’s work that would touch both the CLI and registry teams, and that fixup follower would need to keep running for a long time due to the fact that many people would be publishing with old clients. It can be done, and maybe should be, but that’s a project that would have to extend beyond just the CLI team, and as such would have to be a defined product initiative within npm, Inc. It could happen, but it’s not on the roadmap right now.

As to the other piece of this, having some kind of signed manifest that attests to the hash values of the package that’s tied to some strongish notion of user identity is an idea that’s been kicking around within the project for roughly as long as I’ve known about npm. I think that that effort should be something _entirely separate_ from the existing shasum mechanism, in part because the current shasums weren’t intended for that use and there’s a number of aspects of their design that would make them difficult to reuse for security-sensitive purposes. @soldair has been doing some work with top-level package signing using ssh keys, and that’s been promising. To be a complete solution, though, would require some kind of _waves hands_ PKI / web-of-trust-like scheme, in addition to adding functionality to create and verify per-package manifests. That is _also_ a project that encompasses far more than the CLI team, and as such is another npm, Inc. product initiative that would need to be quarterbacked at a higher pay grade than anyone on the CLI team.

These are both things that are important longer term. However, I can’t make any guarantees that this is something that we’ll get to in the next year or so, and as such I’m going to close this feature request. Thanks to all for the time and discussion, and I hope the preceding doesn’t sound too much like buck-passing – having a better story around these kinds of integrity checks is something that a number of us take very seriously, it’s just proven to be difficult to find the time and resources to do it properly and solve some of the (significant) human / human factors issues related to making something like this usable.
