### ISSUE TITLE
npm hangs with 100% cpu usage

### ISSUE THREAD

**Issue by mirek** [npm/npm#4955]
Ignoring the fact that those packages are old, `npm install` on this package.json seems to always hang with 100% cpu usage:

    {
      "name": "application-name",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "start": "node app.js"
      },
      "dependencies": {
        "express": "3.3.5",
        "http-proxy": "0.8",
        "jade": "*"
      },
      "devDependencies": {
        "grunt": "~0.4.1",
        "grunt-contrib-coffee": "~0.4.0",
        "grunt-contrib-jade": "*",
        "grunt-contrib-less": "*",
        "grunt-contrib-uglify": "*",
        "grunt-develop": "~0.0.2",
        "grunt-env": "*",
        "grunt-regarde": "~0.1.1",
        "grunt-contrib-jshint": "~0.3.0",
        "matchdep": "~0.1.1",
        "grunt-contrib-livereload": "~0.1.2"
      }
    }

npm --version 1.4.3
node --version v0.10.26
Darwin mirekimac.local 13.1.0 Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014; root:xnu-2422.90.20~2/RELEASE_X86_64 x86_64

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by mirek** [comment]
Tested on npm@2.4.1 with my package.json and @stevewillard's - seems to be fine. Thanks.
