### ISSUE TITLE
Issues installing dependencies from git and `instanceof`

### ISSUE THREAD

**Issue by malandrew** [npm/npm#4966]
Let's say I have a private module "foo" which returns the constructor `Foo` and is defined in `package.json` as:

```
dependencies: {
  "foo": "github-user/foo#master"
}
```

Now assume I have a big project called "bar" with modules "baz" and "qux", both of which rely on module "foo". 

Any instance of "foo" created in "bar" and passed to "qux" will return false for `myFoo instanceof Foo". In this case, the only thing that works is "myFoo.constructor.name === Foo.name".

Now if "baz" pointed to one git ref in its package.json like "0.1.0" and "qux" pointed to another git ref like "0.2.0", this would be totally reasonable behavior. However, when you have the exact same git repo and the exact same git reference, npm should install exactly one copy of that private module at the root of the "bar/node_modules" folder.

Here's another explanation of the problem:
http://www.mattesch.info/blog/the-instanceof-trap-in-node-js/#comment-1195

**Comment by othiym23** [comment]
The fact that Git dependencies don’t get deduplicated / always get reinstalled in the tree even if it’s the same repo and branch is a bug, and was filed separately as #3081.

As for singletons, relying on the CLI’s deduplication for singletons / shared global state via the Node.js module loader is an antipattern. This is because it relies on packages exploiting an underspecified aspect of the module specification around how it caches module instances that works the way it does right now for performance reasons. It’s an indirect route to shared state via the module system, rather than each require returning a fresh instance of the module (which would be significantly slower). The installer determines the smallest and flattest tree that it can install given the semver constraints expressed within the dependency tree; trying to force matches to not be deduplicated (or to be deduplicated) to support this behavior puts constraints on the installer model that add complexity that leads to subtle (and sometimes grave / inexplicable) issues with the install algorithm.

Angular shows one of the right ways to do handle singletons and global state correctly, which is to hang your singletons off `(window || global)` in an in-memory pseudo-registry. Dependency injection is the other right way to do this. Either way, trying to do it via `peerDependencies` or other wiring in `package.json` is going to cause people to have a bad time, and it’s only going to get worse once native ES module loading steps onto the scene. (The npm CLI itself adding a front-end asset installer that does some webpack / Rollup / browserify-y things for front-end code would also be helpful here, but the core install path is probably not going to be able to support this workflow without causing a lot of the dependency hell problems that led to [`peerDependencies` getting nerfed](https://github.com/npm/npm/issues/6565) in `npm@3`.)

Since the bug part of this is a duplicate of #3081, I'm going to close this issue. However, the singleton piece comes up frequently enough that it deserves to be documented more clearly (than I can get into here, even), so I've slapped that on the pile of docs to write for npm. Thanks for your time!
