### ISSUE TITLE
'npm adduser' failure

### ISSUE THREAD

**Issue by ImanimalXI** [npm/npm#5016]
I have not been able to run the 'npm adduser' command, keep getting the same 'registry error parsing json' error. Upgraded to latest node, npm version, platform OS X Mavericks.
```
23 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:imanimalxi/-rev/6-4180ab08b874033ac43660ad1cef0e48
24 http 503 https://registry.npmjs.org/-/user/org.couchdb.user:imanimalxi/-rev/6-4180ab08b874033ac43660ad1cef0e48
25 verbose bad json <?xml version="1.0" encoding="utf-8"?>
25 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
25 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
25 verbose bad json <html>
25 verbose bad json   <head>
25 verbose bad json     <title>503 backend read error</title>
25 verbose bad json   </head>
25 verbose bad json   <body>
25 verbose bad json     <h1>Error 503 backend read error</h1>
25 verbose bad json     <p>backend read error</p>
25 verbose bad json     <h3>Guru Meditation:</h3>
25 verbose bad json     <p>XID: 1415900959</p>
25 verbose bad json     <hr>
25 verbose bad json     <p>Varnish cache server</p>
25 verbose bad json   </body>
25 verbose bad json </html>
26 error registry error parsing json
27 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
```

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since April 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned and almost certainly resolved.
