### ISSUE TITLE
Install on 64MB of RAM

### ISSUE THREAD

**Issue by misiek08** [npm/npm#5021]
Hi!
I have problem. I try to install npm on VPS with 64MB of RAM but it get "Killed" and ret=137. Is it possible to do something to let it use less RAM during install?
On 96MB RAM there is no problem to install...

**Comment by bendulum** [comment]
@othiym23 Would it be possible to create a gulp task or npm package that runs `npm install` in batches? I might look into that if you think it could work.

**Comment by othiym23** [comment]
This is still an issue – even a bigger one under `npm@3`, which uses significantly more memory for the new installer – and not really something that can easily be worked around either through making the CLI do smaller pieces of work at a time or by imposing concurrency limits for installs. Rather, it’s a more fundamental performance issue. Today the core of the installer works on dependency trees that are composed of deserialized `package.json` files. The installer can’t really determine at the outset how many of these largeish data structures are going to be pulled into RAM because the installer doesn’t know at the outset how many dependencies there will be for a given package. Those package objects also can be quite large, because they frequently have things like entire READMEs embedded in them.

The way to fix this is to replace those objects with an abstract data type that contains only the information needed by the installer at a given phase of the installation process, which should considerably reduce the amount of resident memory needed by the installer. That said, this falls under the umbrella of performance improvement, which is the next important sustaining project for the CLI team after we address our current list of `big-bugs`. Because that’s an entire project that’s significantly larger than this issue, I’m going to close this issue.

Until we get around to doing that work, the easiest way to use npm in significantly memory-constrained environments like tiny Docker containers is to install applications on a system that has more resources, tar them up, and then deploy them onto the smaller host and run `npm rebuild`. This isn’t the least labor-intensive way of doing things, but it is relatively simple and guaranteed to use far fewer resources than npm install. Thanks for your time, thanks for your patience, and the team hopes to have a better story around resource consumption soon!

**Comment by misiek08** [comment]
I think of solution, where npm saves unnecessary information temporaily on disk. So going into dependencies deeper and depeer npm should focus on current package and install dependencies one-by-one. Of course is just an idea and I had workaround this issue by using bigger "installer" machine. When I'll find some time I'll dig into install process internals and try to help with memory consumption. It won't happen til October :disappointed: 
Thanks for interest and for great module manager that (even requiring much memory) helps developing and deploying apps.
