### ISSUE TITLE
npm config get user returns 495 (for root account)

### ISSUE THREAD

**Issue by smartmouse** [npm/npm#5034]
Hi I get an error when we do npm install in a root account

The cause is due to npm config get user is returning 495 instead of root.
We  did not configure or set up  any npm config, this is a brand new machine.

this is in the builderror.log
```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: Traceback (most recent call last):
gyp ERR! stack   File "/usr/lib64/python2.7/site.py", line 556, in <module>
gyp ERR! stack     main()
gyp ERR! stack   File "/usr/lib64/python2.7/site.py", line 538, in main
gyp ERR! stack     known_paths = addusersitepackages(known_paths)
gyp ERR! stack   File "/usr/lib64/python2.7/site.py", line 266, in addusersitepackages
gyp ERR! stack     user_site = getusersitepackages()
gyp ERR! stack   File "/usr/lib64/python2.7/site.py", line 241, in getusersitepackages
gyp ERR! stack     user_base = getuserbase() # this will also set USER_BASE
gyp ERR! stack   File "/usr/lib64/python2.7/site.py", line 231, in getuserbase
gyp ERR! stack     USER_BASE = get_config_var('userbase')
gyp ERR! stack   File "/usr/lib64/python2.7/sysconfig.py", line 516, in get_config_var
gyp ERR! stack     return get_config_vars().get(name)
gyp ERR! stack   File "/usr/lib64/python2.7/sysconfig.py", line 473, in get_config_vars
gyp ERR! stack     _CONFIG_VARS['userbase'] = _getuserbase()
gyp ERR! stack   File "/usr/lib64/python2.7/sysconfig.py", line 187, in _getuserbase
gyp ERR! stack     return env_base if env_base else joinuser("~", ".local")
gyp ERR! stack   File "/usr/lib64/python2.7/sysconfig.py", line 173, in joinuser
gyp ERR! stack     return os.path.expanduser(os.path.join(*args))
gyp ERR! stack   File "/usr/lib64/python2.7/posixpath.py", line 269, in expanduser
gyp ERR! stack     userhome = pwd.getpwuid(os.getuid()).pw_dir
gyp ERR! stack KeyError: 'getpwuid(): uid not found: 495'
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:637:15)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:743:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
gyp ERR! System Linux 3.10.0-110.el7.ppc64
gyp ERR! command "node" "/root/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/jsteamrepo/MongoDBTest/reddit/node_modules/mongodb/node_modules/bson
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
```

To fix this , I have to do npm config set user root
and npm config set username root
My question is: is this as default behavior or this is a bug?

Not sure why there is user 495 or where does it pick up ? could it be some random user id assigned if nothing has been setup?

Thank you so much in advance.
I have attached the .config folder images
![config](https://cloud.githubusercontent.com/assets/4519627/2651334/13cbfcfe-bf8a-11e3-964d-c65f68912904.gif)
![directory](https://cloud.githubusercontent.com/assets/4519627/2651335/1493b230-bf8a-11e3-8b80-958a582dc3eb.gif)

**Comment by smikes** [comment]
Is this still a problem for you?

If so could you please upload the result of `npm config ls -l` as a gist <https://gist.github.com>

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since April 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by smartmouse** [comment]
Appreciated your help, we can close this.
