### ISSUE TITLE
programmatic usage: emit events rather than auto-logging

### ISSUE THREAD

**Issue by jescalan** [npm/npm#5051]
I've been tinkering with using npm programmatically, and am wondering if there's any reason why any command run will automatically log the output rather than offering the user control over whether to log it or not. I know that you can set different log levels and surpress output, but what I'm going for here is the ability to get the output through an event and choose whether I log it or not.

I know the `npm` object is an event emitter, and does emit a `log` event as shown in the brief docs that there are, which is wonderful, but in addition to this event it will auto-log everything to the console. If the log messages were simply emitted as events, it would allow the command modules to be better controlled programmatically.

This might exist already and I just don't know it, if so sorry!

**Comment by othiym23** [comment]
Given that the CLI team no longer supports programmatic usage of the CLI's API (because it is a poorly-designed chunk of technical debt the team hasn't yet had the time to pay down), I'm going to close this feature request. That said, even were you to monkeypatch the CLI and disable logging while listening to the `npmlog` instance within the CLI as an event emitter (which is a thing you can do), that still wouldn't give you control over the npm output that isn't printed via `npmlog`, most of which is logged via `console.log()`. The best way to get fine-grained control over npm's output if you _really need it_ is to run the CLI as a child process and to filter the `stdout` and `stderr` belonging to that child process. Kinda gross, I know, but a more systematic fix would require changing a lot of npm's internals and is probably more work than most contributors would want to take on.
