### ISSUE TITLE
logging in

### ISSUE THREAD

**Issue by isaacs** [npm/npm#5068]
Doing a PUT to clobber the `_users` doc every time you auth on a new computer?  Requiring manual config file edits after a password change?  Storing the password in a config file?  One login that is expected to work on all registries?

Clownshoes.  We can do better.

Here's an idea for a next step that'll get us closer to reasonableness.  (Ssh key-based login will come in a later iteration.)

Split up the `adduser` command into three: `adduser`, `login`, and `logout`.

If the `_users` doc exists, then `adduser` doesn't create it, but will instead call `login`.  If it doesn't exist, then `adduser` will create it, and then log in as that user.

`login` will prompt for username and password, POST to `/_session`, and get an AuthToken.  Subsequent requests to the server will send that AuthToken in the cookie header.  Take note of the expiration.  (May require change to `couch-login` module to be smarter about this.)

When the token is expired, stubbornly refuse to use it, and instead require that the user re-login.

`logout` send a `DELETE` request to `/_session` to ensure it's entirely gone, and then delete the token.

If any request ever returns a result indicating that the auth is invalid, then delete the token.

`npm login --force` will provide the option to save your username and password, unencrypted, if you type some kind of `yes i am sure` confirmation or something.

**Comment by smikes** [comment]
1. Doing a PUT to clobber the _users doc every time you auth on a new computer? 
2. Requiring manual config file edits after a password change? 
3. Storing the password in a config file? 
4. One login that is expected to work on all registries?

Items 1,2,4 are fixed: npm-registry-client can't PUT anymore (except for the very first adduser); password changes are done online, adduser handles the local part gracefully enough; logins are segmented by registry.

Item 3 is still true-ish and a bit problematic in that asking users to post `npm c ls -l` results in (obfuscated) password leaks.

Keep this issue, or split off into a new one?  /cc @othiym23

**Comment by othiym23** [comment]
There are some registry-2 changes that will affect this issue, so I'll circle back to this when we get to that (we're finally going to split apart `login` and `adduser`!).

**Comment by smikes** [comment]
Also ref case #6126

**Comment by msimerson** [comment]
> Ssh key-based login will come in a later iteration.

:+1:  Looking forward to this!

**Comment by othiym23** [comment]
1. `npm logout` has been implemented since `npm@2` was released. It behaves largely as described here.
2. splitting apart `npm login` and `npm adduser` is within the scope of the work that @zkat is currently doing on auth
3. same goes for an enriched set of login methods – probably on the docket is OAuth-based 2FA flows in addition to the current username and password-based authentication. Expect to see a proposal shared with the world at large soon.

Most of the security measures described in this issue are already handled by the fact that encoded credentials are no longer stored on local machines, having been replaced by session tokens. Given that the tokens on their own are powerful enough to allow malicious users to impersonate other users and see all the things those users can see (and do all the things those users can do, including publishing), there's additional work to be done to scope tokens to capabilities and to make it less risky to put those tokens on shared environments like cloud CI providers, but that's sort of beyond the scope of this issue anyway. As such, I'm going to close it. Thanks for your time, past @isaacs!
