### ISSUE TITLE
Preflight check to see if the registry and GitHub are available

### ISSUE THREAD

**Issue by domenic** [npm/npm#5105]
This is a proposed solution for proxies and other internet issues (including 503s) hurting the npm experience, given the many cryptic errors they produce.

Before doing anything that will potentially go to the npm registry, hit a designated endpoint, served from the same infrastructure as the rest of the registry, with a `HEAD` request. If the response is 200 OK, proceed. If not, error out as soon as possible with a user-friendly error message. If it's a 503, tell them about npm being down; otherwise tell them about proxy problems.

Note that this should happen up-front, not as-needed. This is important because with a cache in place you might not actually hit the registry until four or five packages have already been installed, which causes a confusing mid-installation failure.

The same thing should be done for GitHub: before doing anything GitHub related, hit a simple endpoint (e.g. npm/github-test) with the simplest Git request possible, and make sure it works.

We should also add a `npm check-internet` to run these before `npm install` happens.

/cc @stefanpenner

**Comment by othiym23** [comment]
Much has changed since this issue was originally opened; `npm@3` largely addresses the need to not leave `node_modules` in an inconsistent state after a failed install because it’s close enough to transactional that either all the dependencies are installed, or none are, for a given operation. Also, the error messaging around failed downloads is much less cryptic than it once was. The main remaining case that isn’t handled particularly well is providing hints to users that they need to configure proxy settings for _both_ Git and npm (sometimes separately, depending on their environment). This is a secondary supportability consideration, at least in my estimation.

As far as hitting endpoints at start time and failing faster in cases where a registry or hosted Git endpoint is unavailable, it’s tougher than it looks. For one thing, the CLI doesn’t know all the endpoints that it’s going to hit at the start of install time, given the fact that it can’t see dependencies’ dependencies until after it’s pulled down their metadata as part of the install process. The CLI could start every process by hitting the ping endpoint the primary registry now exposes, but that’s arguably no faster than just trying to cache a dependency and raising an error if that fails, and is definitely another network round trip, which means it’s probably slower. The preceding also applies to hosted Git endpoints – the CLI could make the assumption that GitHub is the most likely host for Git dependencies, but those dependencies may be deeply buried in transitive dependencies, and in any case the CLI doesn’t like to presume that GitHub is the always and only place for hosting Git-based packages.

I’m not interested in making any strong claims about the robustness of the registry (especially because there are many users who are using registries other than npm’s primary registry network). I agree that there is definitely room for improved communication with users when things go wrong on the network level. That said, I don’t think the approach sketched here pays for the implementation and maintenance cost it brings with it, so I’m going to close this issue. Thanks to all for their time, and I would be delighted to receive suggestions or patches intended to address the supportability concerns raised by `npm@3`’s current error messages resulting from network failures.
