### ISSUE TITLE
"npm publish" should fail on errors in dependencies configuration

### ISSUE THREAD

**Issue by medikoo** [npm/npm#5152]
Currently, npm will install package even if there are obvious errors in package.json dependencies section.

e.g. I had a typo, dependency version was declared as _x0.2.0_, publish was _successful_, but of course install of such package immediately fails. Technically I published dead, unusable version of a package.

Before we allow the publish it'll be great to validate if all versions are semver correct in package.json.

**Comment by othiym23** [comment]
I think the most consistent way to address this would be to add an `npm install` step to `npm publish` – that way we'd know that all of the dependencies were either valid semver or valid `dist-tag`s. It would also help make sure that `npm-shrinkwrap.json` and any `bundledDependencies` are in a good state at publish time.

However, because this add a bunch of lifecycle events to the publish cycle, it's a breaking change that would have to land in a new semver-major version of npm. Not a dealbreaker, but that means we have to make this change with some care.

I think this is a useful enough change (perhaps with some other validations to the package before publish) that the CLI team can commit to landing this, or something like it, within the next year. Thanks for bringing this up, and thanks for your time!

**Comment by othiym23** [comment]
@thomblake says on #5240:
> I published version 1 of jp and then was not able to install it. npm init created a bin entry for "jp": "cmd.js" that should have been "jp": "bin/cmd.js". I got a confusing error at 'cache unpack' time. Probably I should have been warned at publish time that this could not be installed.

This is another thing that would be caught by running install, but maybe making sure the error is informative at publish time would be another good thing to add.
