### ISSUE TITLE
Make shrinkwrap file path configurable

### ISSUE THREAD

**Issue by Raynos** [npm/npm#5158]
I would like to make the file location of shrinkwrap configurable

## Motivation

I want to shrinkwrap dev dependencies seperately. This will allow for deterministic tests on CI without having to shrinkwrap & install dev dependencies in production.

ci flow:

```sh
npm install --shrinkwrap-file='npm-shrinkwrap.json'
npm install --shrinkwrap-file='npm-dev-shrinkwrap.json'
```

I will create and manage this second shrinkwrap file using another tool.

## Question

It looks like the path is encoded here:

 -  https://github.com/npm/npm/blob/a9d9fa5ad3b8c925a589422b7be28d2735f320b0/lib/shrinkwrap.js#L70
 - https://github.com/npm/npm/blob/e3a2ec4c72a41b29c6f4f46e89a5ec5913ee2e96/lib/install.js#L284
 - https://github.com/npm/npm/blob/a9d9fa5ad3b8c925a589422b7be28d2735f320b0/lib/shrinkwrap.js#L75

What is the proper way to implement making this configurable? 
Should I add a PR to `npmconf` for this new config parameter?
Should I use `npm.config.get('shrinkwrap-file') || 'npm-shrinkwrap.json'` ?

What else is needed to get a new config parameter implemented?

I'll happily make a PR for this.

**Comment by othiym23** [comment]
> I want to shrinkwrap dev dependencies seperately. This will allow for deterministic tests on CI without having to shrinkwrap & install dev dependencies in production.

Good news! This is being handled a different way by #10073 and #10265. Those PRs still need a little more help to get merged, but they will allow you to selectively include or ignore `devDependencies` in `npm-shrinkwrap.json`. Since those address the need without including a new (potentially confusing and fragile) bit of configuration around shrinkwrap (which will probably be seeing other changes soon), I'm going to close this feature request in favor of those PRs, which the CLI team fully intends to land as soon as they're ready. (Help welcome!) Thanks for your time, as always, Jake!
