### ISSUE TITLE
Expose `log` on `npm`

### ISSUE THREAD

**Issue by shellscape** [npm/npm#5206]
I'd love to see `log` exposed on the npm export. npmlog documentation states that if we don't want the log writing to stderr, we need to redirect log.stream. Because npm doesn't expose the log object, this is impossible without also including a direct dep to npmlog in whatever project is using npm.

**Comment by othiym23** [comment]
Given that we've removed support for consuming the internal npm API because it's not fit for use outside the CLI itself, this request is a dead letter. That said, if you're doing mad science™ and have already constructed an npm instance using `npm.init()`, you can just `require('npmlog')` from within the same process / `node_modules` root and get the `npmlog` instance used by npm. Obviously a lot of caveats, but this is one among many reasons why that API is no longer supported. Thanks for your time!
