### ISSUE TITLE
HTTP[S]-hosted Git credential management

### ISSUE THREAD

**Issue by csalch** [npm/npm#5227]
I'm working with a couple of custom modules that are installed via git+https urls that are password protected and running into issues.  It looks like there is an interaction between git and npm that leads to git trying to ask for credentials multiple times, at the same time:

```
csalch@Chriss-MacBook-Air ~/code/bestfit/bf-banking/api $ npm install
npm http GET https://registry.npmjs.org/loopback
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/mqtt
npm http GET https://registry.npmjs.org/loopback-connector-mongodb
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/jquery-file-upload-middleware
npm http GET https://registry.npmjs.org/loopback-push-notification
npm http 304 https://registry.npmjs.org/loopback-connector-mongodb
npm http 304 https://registry.npmjs.org/loopback
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/mqtt
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/jquery-file-upload-middleware
npm http 304 https://registry.npmjs.org/loopback-push-notification
Password for 'https://redacted@bitbucket.org': Password for 'https://redacted@bitbucket.org':
```

ssh urls seem to work fine, but that won't work in our environment.  I've tried several different approaches but have found nothing that will let me have more than one git dependency.

**Comment by smikes** [comment]
My statement earlier was incorrect:

> so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and re-open it!)

Since this is marked as "bug" and "feature-request", it will not be closed.

**Comment by csalch** [comment]
No worries.  We've been able to work around it with deployment keys for
now, which in truth is probably a better solution.



*Cell: 512-730-0916*
*Skype: chris.salch*
*LinkedIn <http://www.linkedin.com/pub/chris-salch/4/678/94a>*

**Comment by alvinsight** [comment]
Hi, everyone, It looks like it's impossible to install a dependency from a password-protected git repo, (I'm on windows) so I was wondering if there was any updates on this ?
Thanks, 
Alvin

**Comment by othiym23** [comment]
There are a few elements to this:

1. When installing, npm caches all Git dependencies. Right now, that caching (which requires cloning the repos) happens concurrently, as the dependencies are discovered. This is what causes the stacked login prompts.
2. npm is just using the built-in Git binaries to do the cloning; it passes through stdin and stdout while those Git processes are running, but this frequently interacts with other prompts coming out of npm in visually illegible ways.
3. There isn’t a really good out-of-the-box way to manage credentials for Git remotes separate from the URLs themselves. Making credentials distributable to e.g. CI environments requires that the people do so make some careful choices around sharing credentials without exposing themselves to compromise (hence the `security` label on this issue).

There are some potential remedies to some of these issues:

- npm can serialize cloning Git repos so that they’re never overlapping. This still requires a human to type in a username and / or password, but this will mean you only ever have to do it one at a time, which is at least possible. This would also require the CLI to synchronize all access to standard I/O so that other parts of npm don’t interfere with capturing these credentials.
- A credential manager (which the CLI team doesn’t really have time to build) could handle securely storing these credentials, or we could figure out how to take advantage of provider-specific token auth solutions (like GitHub’s).

We’d happily accept patches to improve some or all of this, but ultimately this is something that touches a lot of the CLI’s internal architecture. It’s a real pain point, so it needs to be fixed, but given the CLI team’s priorities, it’s going to be a little while (longer) until we have time to tackle this. Thanks to all for the discussion and your patience!

**Comment by dpogue** [comment]
Just for the sake of reference material, this is how Ruby's Bundler handles this:
They allow storing per-hostname credentials in their config file (at a project or global level). They also have a general mechanism for providing config values via environment variables, which makes this usable for CI environments.
http://bundler.io/v1.12/bundle_config.html#CREDENTIALS-FOR-GEM-SOURCES
