### ISSUE TITLE
suppress unnecessary npm WARN related to package.json fields

### ISSUE THREAD

**Issue by timoxley** [npm/npm#5253]
Under very few situations are the warnings reported by normalize-package-json actually useful, generally they are just noise, especially in the case that the warnings are for packages that are not under my control.

e.g. during npm's own install procedure, these warnings are generated by 3rd party packages:
```
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm WARN package.json ronn@0.3.8 'repositories' (plural) Not supported. Please pick one as the 'repository' field
```

That is just noise, nobody needs to read that except the owners of those packages.

I'm proposing one or more of the following:

* default log level gets raised above warn
* a config flag to specifically exclude warnings related to package.json
* a config flag to specifically exclude warnings related to any package.json that is not the current package (i.e. `npm root`/../)
* Raise package.json warnings for current package to errors that must be bypassed with --force on `npm publish` (or even during prepublish).

Would be happy if these flags were on by default. Will PR if acceptable.

Related to https://github.com/npm/npm/issues/5213

**Comment by othiym23** [comment]
The general consensus at the npm offices is that these warnings are noisy enough to be annoying for end users, yet not really creating the kinds of peer pressure effects it seems @domenic was envisioning. These warnings are probably going to get nerfed in the near term, especially because there are other, newer warnings we would like users to actually pay attention to. (This only applies to child dependencies – you will still get warned if the top-level package is missing these fields.)

**Comment by millerdev** [comment]
> especially because there are other, newer warnings we would like users to actually pay attention to

Yay @othiym23! You've hit the right reason to silence these warnings. In the most common case they cannot be quickly and easily addressed, and in many (most?) cases they are completely outside the control of the end user. The noise causes people to ignore npm output, which is bad.

**Comment by msimerson** [comment]
> The noise causes people to ignore npm output, which is bad.

:+1:

**Comment by chakrit** [comment]
> The noise causes people to ignore npm output, which is bad.

Second-ing this.

**Comment by redguardtoo** [comment]
Do I have a flag to manually turn off warnings?

**Comment by KenanY** [comment]
@redguardtoo You should be able to do that by configuring your [`loglevel`](https://docs.npmjs.com/misc/config#loglevel).

**Comment by seanmcilvenna** [comment]
I think this should be a parameter passed to "npm install"
Example:
```
npm install MYMODULE --suppess-warnings
```

**Comment by chakrit** [comment]
I don't think allowing suppression of *all* warnings is a good thing to do. They are labelled "warnings" for a reason. It's just that, the warnings are more for the package author and not exactly useful for the package user at the moment.

**Comment by fbacker** [comment]
Trying to use npm with Team Foundation Server to automatically manage builds. When running scripts (VNext) to install npm packages and Warnings appear it will cancel the build. I can continue with errors but the builds will get logged as partially succeeded that will confuse.

So seanmcilvenna idea of suppress isn't bad.
    npm install --supress-warnings

**Comment by akhicks** [comment]
I agree I get the same problem as @fbacker

**Comment by atrotors** [comment]
+1

**Comment by atrotors** [comment]
+1

**Comment by atrotors** [comment]
+1

@fbacker how `--supress-warnings` would be different from `--loglevel=error`?

**Comment by beyti** [comment]
+1 for fbacker, same problem here. Partially succeeded tfs builds for no reason.
Since on cli, no way to differ error from warning, tfs thinks warnings as error.

**Comment by haxwell** [comment]
+1 for the solution proposed by othiym23, millerdev, and timfoxley. 

-1 for the `--suppress-warnings` option. It is indeed the same as setting the `--loglevel` higher.

I want to see warnings for direct dependencies (that I can do something about) and I do not want to see warnings for child dependencies (that I cannot do anything about).

**Comment by Wtower** [comment]
+1 for supressing warning option.

In case somebody uses some automation tool like Ansible, in order to avoid false positives:

```
- name: Install packages
  command: npm install -g {{ packages }}
  register: result
  failed_when: '"ERR!" in result.stderr'
```

**Comment by dcrockwell** [comment]
+1. I'm using npm to build packages remotely so that native/static code can be compiled on specific remote architectures. I'm forced to add bunk `description`, `repository` fields, as well as a bunk `README.md` in order to prevent the remote systems from detecting the word "error" in the *warning* messages.

**Comment by oshalygin** [comment]
-1 for `--suppress-warnings`
+1 for a solution to supress child dependency warnings, there's nothing we can do about them.

**Comment by pvasek** [comment]
@fbacker If you are using powershell in Team Foundation Server builds you can use the following workaround. The idea is to redirect npm install error log to a file and then check for ERROR keyword. If it is included in the file the errors are printed to the error output otherwise they are ignored.

```powershell
&npm install 2>.\npm.errors.txt
$messages = (Get-Content .\npm.errors.txt) 
$errors = $messages | select-string 'ERROR' -AllMatches -CaseSensitive
if ($errors.length -lt 0) {
    Write-Error $messages
}
```

**Comment by antoinne85** [comment]
Let me start by saying that I know very little about NPM. I am ill-equipped to comment on what is or is not appropriate for the project. I can, however, offer up an anecdotal situation around this issue that is affecting me.

I'm charged with invoking several **npm** commands during our (mostly .NET) build process, running through MSBuild.

From my perspective, it would be nice to have finer grained control over what messages get written. It would be great to be able to express notions like, "I want to see errors and info, but not warnings."

Specifically, the challenge with warnings is that they seem to be written to _stderr_ which causes MSBuild to consider them errors, which results in an exit code of -1. This makes it difficult to determine when a real error occurred and when an "ignorable" error occurred (like a warning).

Alternatively, a way to reroute warnings to _stdout_ instead of _stderr_ would also suffice.

**Comment by dcrockwell** [comment]
@antoinne85 +1

**Comment by stevenvachon** [comment]
Such warnings are outputted to StdErr, which throw exceptions in PowerShell, which causes problems for automated tests.

**Comment by JemiloII** [comment]
Is this still an issue that needs a pr or is it a won't patch thing? Kinda about to just fork npm so I can get rid of annoying warnings and other things. Like I don't care if a package fails to build with node-gyp if the package is just going to use a binary. I'd rather just have an option to use the binary honestly. Speed up the install times if you know the binary just works out of the box. Deprecation warnings, I don't care for those in production logs. I just want to have useful warnings and errors, not clutter. Sorry if this post sounds as if its coming off strong, don't mean it to be, just pointing out nuisances in npm logging and lack of disabling some of the logging.

**Comment by haxwell** [comment]
If this "feature" annoys you, help make open source, capitalism, and human self-interest combine to solve your frustration. Find this issue on bountysource, and let's get 'er done. I got the ball rolling. Or I've at least pushed it.

**Comment by othiym23** [comment]
We believe we've found and fixed the original issue in `npm@2` and `npm@3`, so I'm going to close this issue. If you're encountering issues for transitive dependencies at install time that you believe you shouldn't be, please open new issues so the CLI team can handle them on a case-by-case basis – some of them, like deprecation warnings, still make sense to bubble up, because of potential security / critical flaw notification. Thanks to all for their time and discussion!

**Comment by ninja-1** [comment]
Just in case anyone finds this later searching for the Ansible fix, make sure to check if `stderr` is defined before checking for `ERR!`.

```yml
- name: Install packages
  command: npm install -g {{ packages }}
  register: result
  failed_when: "result.stderr is defined and 'ERR!' in result.stderr"
```

Credit goes to this StackOverflow answer: http://stackoverflow.com/questions/39069619/ansible-perform-a-failed-when-on-an-async-task-based-on-a-value-from-stdout

**Comment by aparajita** [comment]
My solution:

**~/bin/npm**
```shell
#!/bin/sh
exec /usr/local/bin/npm $@ 2>/dev/null
```

**shell config**
```shell
alias npm='~/bin/npm'
```

Of course this kills stderr output if your npm scripts call actual system commands.

**Comment by andrewshawcare** [comment]
I feel like this type of problem crops up because `npm install` is really doing _at least two things_, namely installing packages _and_ linting package metadata.

Why not, then, treat this warning like a linter would? Instead of suppressing _all_ warnings, why not allow these specific warnings to be suppressed? Something like:

`npm install --suppress-package-metadata-warnings`

or

`npm install --suppress-warnings 'package-metadata,...'`

That way we don't lose _all_ warnings and can be very explicit and expressive to others about the warnings we are willing to suppress.
