### ISSUE TITLE
Can't force git to use https:// instead of git://

### ISSUE THREAD

**Issue by ceeeKay** [npm/npm#5257]
Git has a simple way to do this in the config file.
```
[url "https://"]
	insteadOf = git://
```

However npm seems to throw out the environment in lib/cache.js
```
var gitEnv_
function gitEnv () {
  // git responds to env vars in some weird ways in post-receive hooks
  // so don't carry those along.
  if (gitEnv_) return gitEnv_
  gitEnv_ = {}
  for (var k in process.env) {
    if (!~['GIT_PROXY_COMMAND','GIT_SSH','GIT_SSL_NO_VERIFY'].indexOf(k) && k.match(/^GIT/)) continue
    gitEnv_[k] = process.env[k]
  }
  return gitEnv_
}
```
So I can't inject a GIT_CONFIG or anything.

I've hand-hacked it into the `addRemoteGit` function in `lib/cache.js` with
```
  u = u.replace(/^git:/, "https:")
```
but this variable should be pulled from a config somewhere

**Comment by age76** [comment]
cheers @LaurentGoderre, worked a charm

**Comment by othiym23** [comment]
After reviewing the patch on #5621 and this issue, I've decided that @LaurentGoderre's approach is actually sufficient, without adding another difficult-to-test (and -debug) code path. Because we do have Laurent's instructions in [the troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting#npm-only-uses-git-and-sshgit-urls-for-github-repos-breaking-proxies), I'm going to call this documented and resolved. If somebody wants to propose a patch that moves this configuration into the official npm documentation, I'm willing to work with them to land it, but keep in mind that the npm docs are meant for npm-specific things, and this is a more general Git configuration issue.

**Comment by LaurentGoderre** [comment]
:+1: I don't think you guys should complicate your code base to accommodate super restrictive network environments if a workaround exists

**Comment by mkozjak** [comment]
For bitbucket you would use:
`git config --global url."https://user:pass@bitbucket.org".insteadOf ssh://git@bitbucket.org`
