### ISSUE TITLE
READMEs should be tied to the "latest" tag

### ISSUE THREAD

**Issue by seldo** [npm/npm#5259]
At the moment the README file is the one that arrived with the most-recently published version, whether or not that version is tagged as "latest". This can lead to confusing situations where documentation refers to an upcoming version (e.g. https://www.npmjs.org/package/joi right now).

We don't store all the READMEs because they took up a ton of space. We should move READMEs out of the database, and make them immutable, like we did with package tarballs. Then when a GET request comes we should slot in the README for the appropriate version.

**Comment by lennym** [comment]
@seldo Has this recently been fixed? I have had some issues with the README for https://www.npmjs.com/package/node-sass showing the information from a pre-release version instead of the `latest`, but when I've run my own tests I have been unable to replicate?

**Comment by seldo** [comment]
This isn't fixed yet, but we are tracking it internally. It's rather more involved than you would imagine :-p

**Comment by othiym23** [comment]
Hello, esteeemed colleague / boss / friend, this is something that the CLI isn't really responsible for. Perhaps it's time to kick it over the wall to @npm/registry-team? In any case, I'm going to close this instance of it, because this isn't something the CLI can do on its own. Thanks for your time, as always!
