### ISSUE TITLE
403 Forbidden fetching tarballs from Riak

### ISSUE THREAD

**Issue by garthk** [npm/npm#5260]
aca48cfb in v1.4.9 breaks private tarchive fetching from Riak, which, [by design](http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-August/009204.html), responds with `403 Forbidden` rather than `200 OK` if `referer` is present but doesn't match scheme, host, and port of the receiving node. 

Riak 2.0 beta 1 exposes the `secure_referer_check` flag so you can disable it. Until then, our best option is slapping a proxy in front of it to strip the header.

**Comment by othiym23** [comment]
npm in general uses the `referer` field as a way to capture user intent from the CLI; it's one of the ways that the npm analytics team stitches together user activity without tying it to specific IPs or accounts. As such, this is a load-bearing feature of how npm makes requests. I'm going to guess that since this issue is over two years old, and the current version of Riak is 2.1.4, I'm going to guess this issue has been overtaken by events anyway. In either case, I'm going to close this issue, but if somebody still needs some way to control / suppress referers, drop a note here and we can talk.
