### ISSUE TITLE
delete an account

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#5361]
i have duplicate accounts for god knows why. how can i delete one?

**Comment by smikes** [comment]
Is this still a problem for you?

I don't see an npm user named `orbit` or `Orbit` anymore, so this may have been fixed by a manual edit to the `npm` registry.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by jonathanong** [comment]
orbit was a typo. either way, this is still a problem for me. if you'd like, can you merge `jonathanong` -> `jongleberry` and delete `jonathanong`? otherwise, i can wait for a website feature

**Comment by smikes** [comment]
Oh sorry, I misunderstood.  

> can you merge jonathanong -> jongleberry and delete jonathanong? 

This sounds like backend magic to me, so I will summon the backend magicians /cc @ceejbot @seldo

**Comment by jonathanong** [comment]
this is not a priority, so take your time!

**Comment by othiym23** [comment]
Our process for actually making this happen is to email support@npmjs.com with the account(s) you'd like to merge, and the account you'd like to keep, and then whomever is dealing with email support that week can do the server-side magic to make this look mostly transparent. I'm going to close this for the simple reason that it's just never going to get acted on if we leave it open here. Thanks for putting up with our semi-fractured process!
