### ISSUE TITLE
NPM on Windows 7 fails install sometimes, but not all

### ISSUE THREAD

**Issue by chrismichaels84** [npm/npm#5432]
I don't even know what to make of this bug. I am running Windows 7 (sorry lol) and Node.js version .10.*. I have been trying to use it to access tools like gulp and bower. I can install packages sometimes (rarely), but not usually. I get a slew of errors. For instance, I tried to install gulpjs globally and it failed. I watched it create the directory and files, but about half-way through the install, it encountered an error and removed most of the files. I tried again with the same results. When I tried to install it locally, I got the same problem. Then, I installed in a third directory and it worked. So, I moved that install into my global directory.

I have encountered the same kind of problem almost every time I install a package. Sometimes it works, sometimes it doesn't.

Most recently, I tried to install bower globally with the same result. I have the log file, but I'm not sure how to attach it here.

**Comment by smikes** [comment]
Is this still a problem for you?

As @othiym23 suspected, there were race conditions that are fixed in new versions of npm.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by chrismichaels84** [comment]
No more trouble. I'll close the issue. Thanks a lot!
