### ISSUE TITLE
npm test Error: spawn ENOENT

### ISSUE THREAD

**Issue by Jiig** [npm/npm#5480]
trying to run my test and I get the following from the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'test' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest voxel-exp@0.1.1
6 info test voxel-exp@0.1.1
7 verbose unsafe-perm in lifecycle true
8 error Error: spawn ENOENT
8 error     at errnoException (child_process.js:998:11)
8 error     at Process.ChildProcess._handle.onexit (child_process.js:789:34)
9 error If you need help, you may report this *entire* log,
9 error including the npm and node versions, at:
9 error     <http://github.com/npm/npm/issues>
10 error System Windows_NT 6.1.7601
11 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test"
12 error cwd E:\prog\voxel-js\voxel-exp
13 error node -v v0.10.28
14 error npm -v 1.4.9
15 error syscall spawn
16 error code ENOENT
17 error errno ENOENT
18 verbose exit [ 1, true ]
```
I searched for this error and could only find issues with npm install, and that works just fine for me. Ive tried clearing the cache, didn't help.

**Comment by smikes** [comment]
Is this still a problem for you?

As @othiym23 suggests, you will get more useful error messages if you can update your installation of `npm`.  It looks like npm is trying to run some commands for you (`npm start` and `npm test` will both run a command) and the command is not found.. but the older version of `npm` does not report what the missing command name is.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since September 2014. Can you try updating your npm installation?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
