### ISSUE TITLE
Unable to download phonegap using npm

### ISSUE THREAD

**Issue by zeeshii** [npm/npm#5566]
```
C:\>npm install -g phonegap
npm ERR! Error: UNKNOWN, open 'C:\Users\Gheiath Ewais\AppData\Roaming\npm-cache\
dep-graph\1.1.0\package\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! cwd C:\
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Gheiath Ewais\AppData\Roaming\npm-cache\dep-graph\1.1.0\p
ackage\package.json
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.14. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by zeeshii** [comment]
Thank you sam for your kind concern. Right now i am not using phonegape
infect not on the mobile development. In future i defiantly want to
experience your efforts through npm. thank you.

**Comment by othiym23** [comment]
Closing as resolved. Let us know if, in the future, you encounter similar issues when working with Phonegap with newer versions of npm.
