### ISSUE TITLE
express

### ISSUE THREAD

**Issue by rogermarkussen** [npm/npm#5575]
Error creating Node.js Express App. Failed command:
```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install
Exit code: -1
Standard error:
npm ERR! Error: UNKNOWN, open 'C:\Users\Kontor-10\AppData\Roaming\npm-cache\type-is\1.1.0\package\package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\ddrr
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path C:\Users\Kontor-10\AppData\Roaming\npm-cache\type-is\1.1.0\package\package.json
npm ERR! code UNKNOWN
npm ERR! errno -1
npm
```

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.14. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 
We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by xirour** [comment]
yes, resolved, thanks guys!
