### ISSUE TITLE
Can't run npm start

### ISSUE THREAD

**Issue by srbjwe** [npm/npm#5633]
This command fails with the error ...
```
http://github.com/npm/npm/issuesnpm ERR! Error: ENOENT, open '/Users/johnedwards/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/johnedwards
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /Users/johnedwards/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/johnedwards/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

As @nathan7 says, the `package.json` is necessary for commands like `npm start` or `npm test` in order to tell `npm` what should be done.  

If you are following a tutorial of some sort, make sure you are in the directory they specify when you run the command `npm start`.

If you are still looking for a way to learn `node`, I recommend <http://nodeschool.io/>

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
