### ISSUE TITLE
Most NPM Installations Break Windows

### ISSUE THREAD

**Issue by mcdonnelldean** [npm/npm#5641]
NPM is pretty much unusable under Windows. This is of course related to the path size limitations. We are now at the stage were most of the larger packages _(gulp, bower, etc)_ are failing due to reasonably big dependency tails. 

My main concern here is that there are no mention of these issues when installing node or npm via the website. Not being able to install prime packages makes npm __fundamentally__ unusable for windows.

My other concern is placing an undeletable (for all intents) directory structure on peoples machines. This is just not cool.

Can we please get some transparency as to what is happening vis a vis this the path issue and could we get some changes made to the Windows Tooling to explain full support is not yet available.

There are a number of packages already trying to flatten their structures to get around this issue. This is not the way this should be solved and could lead to a lot of bad blood from the package authors themselves, trying to fend of a slew of windows related issues!

**Comment by busches** [comment]
@othiym23 can this issue be closed now that `npm3` is the default everywhere and greatly alleviates this situation?

**Comment by othiym23** [comment]
@busches Indeed! The CLI team just got to this in our product triage meeting (where we evaluate all of the outstanding feature requests, in forward chronological order), and realized that with the advent of `npm@3` and its maximally flat trees, along with some of the other changes that Microsoft has been making to Windows recently, this issue is now more or less addressed, at least for Windows. As such, we're going to close it! Thanks to all for the discussion and patience!
