### ISSUE TITLE
can't install bower with npm on mac

### ISSUE THREAD

**Issue by claudiaWoest** [npm/npm#5663]
```
3083 verbose read json /usr/local/share/npm/lib/node_modules/bower/node_modules/bower-config/package.json
3084 error Error: ENOENT, lstat '/usr/local/share/npm/lib/node_modules/bower/node_modules/mout/random.js'
3085 error If you need help, you may report this log at:
3085 error     <http://github.com/isaacs/npm/issues>
3085 error or email it to:
3085 error     <npm-@googlegroups.com>
3086 error System Darwin 13.3.0
3087 error command "/usr/local/Cellar/node/0.10.12/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
3088 error cwd /Users/claudia/Documents/projekte/fricke
3089 error node -v v0.10.12
3090 error npm -v 1.2.32
3091 error path /usr/local/share/npm/lib/node_modules/bower/node_modules/mout/random.js
3092 error fstream_path /usr/local/share/npm/lib/node_modules/bower/node_modules/mout/random.js
3093 error fstream_type File
3094 error fstream_class FileWriter
3095 error code ENOENT
3096 error errno 34
3097 error fstream_stack /usr/local/Cellar/node/0.10.12/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
3097 error fstream_stack Object.oncomplete (fs.js:107:15)
3098 verbose exit [ 34, true ]
```

**Comment by smikes** [comment]
Can this issue be closed?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since August 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

Since you are using `homebrew`, you may not need to use `sudo` for global installs if you have made your `/usr/local` directory writable by your default user.  Some people use this practice on OSX since it tends to be used more as a single-user OS; on a multi-user linux system where `/usr/local` is not user-writable, it would be necessary to use `sudo` to install bower globally.

Another alternative for "global" install is `nvm` - https://github.com/creationix/nvm - which also lets you switch between node versions (and even supports io.js)

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
