### ISSUE TITLE
SPDY support

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#5830]
are there any plans to support spdy? ideally, the client just sends a list of dependencies to the server, and the server returns a resolve dependency tree and spdy pushes all the tarballs to the client.

**Comment by othiym23** [comment]
SPDY or HTTP/2 on their own are a bundle of technologies more than a drop-in solution, but yes, the team is looking at ways to build a new registry API that's less beholden to CouchDB's notions of RESTfulness. This will very likely involve using some sort of sync method to harmonize what's cached on the client with what's on the registry with a minimum of bandwidth overhead and as few round trips as possible. That said, what the registry team comes up with is probably not going to look that much like HTTP/2, at least at first. Just adding SPDY support to the CLI is kinda hard to do and not that beneficial, because it adds a bunch of additional dependencies without bringing along the logic necessary to take advantage of SPDY’s bundling and pipelining features, which need to be added on the server side.

So yeah, we’ll get the effect, but no, it’s probably not going to be via SPDY. As such, I’m going to close this feature request, but keep your ears open. When we get ready to roll out the new registry API, it’s going to be proposed and documented in a much more consultative way than the ad hoc way the original registry API was built out. Thanks for your time, and for the suggestion!
