### ISSUE TITLE
install iOS-deploy

### ISSUE THREAD

**Issue by ck900i** [npm/npm#5890]
```
Apples-MacBook-Pro:~ apple$ npm install -g ios-deploy
npm ERR! Error: Attempt to unlock ios-deploy, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! cwd /Users/apple
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/apple/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

The first issue looked like a cache locking problem, of the sort that were present in `npm`@`1.4`.  The second looks like a permissions problem, of the sort that can sometimes be caused when `npm` is run as root (using `sudo`).

However, it looks like you have successfully worked around the problems.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.23. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by sunny-mittal** [comment]
I can't fully test it yet, but @magusd solution seemed to work for me. It let me install ios-deploy, at least. I, thankfully, don't have an iPhone, but I will see if this remedies my Ionic/Cordova `ionic run ios` issue. Thanks all!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
