### ISSUE TITLE
Need a way to hook into install

### ISSUE THREAD

**Issue by timboudreau** [npm/npm#5896]
This is an odd request, so some background:  I'm the author of the [NetBeans NodeJS plugin](https://github.com/timboudreau/nb-nodejs).  Some of my friends and former colleagues are very excited about [AvatarJS](https://avatar-js.java.net/) as a way to NodeJS code inside a Java VM.  So I thought I'd help them out by adding the ability to run a project in AvatarJS instead of native Node.

Which got me thinking about the fact that, of course, people will think it's a good idea to call out to Java libraries.  And that there should be a way to get npm to download and install them, so that `npm install` is one-stop shopping for libraries.

Let me be perfectly clear that I'm **not** asking for any special Java support from npm.  That would be a bad idea.

Java has Maven, a build tool with online repositories similar to npm.  So it would be easy to add some java-related metadata to `package.json` and just delegate to Maven to do the downloading and put them where the process can find them.

I notice that `~/.npmrc` can include an entry for `onload-script` and will `require` it if present.  So it's pretty easy to add a hook in there.  And I noticed that npm is an `EventEmitter`.  Perfect!

Except that it never emits any events.  My first cut at hooking into npm logs nothing:

```
var path = require('path');
var args = process.argv.slice(2);
if (args.length === 1) {
    switch (args[0]) {
        case 'install' :
            listenForInstallComplete(process.cwd());
    }
}
function listenForInstallComplete(dir) {
    var npmJs = path.join(path.dirname(require.main.filename), '../lib/npm.js');
    npm = require(npmJs);

    var origEmit = npm.emit;
    npm.emit = function () {
        console.log('EMIT ' + require('util').inspect(arguments));
        origEmit.apply(npm, arguments);
    }
}
```

Installing Java libraries should work recursively, just like installing Node libraries does.  So I need my hook to run *after* npm has finished installing modules - either notification one-by-one, or notification after the entire install process has been finished.

Any chance, since the `npm` object is already an `EventEmitter`, that it could actually emit some events, on pre/post install?

If there's another way to solve this, I'm open to suggestions.

**Comment by othiym23** [comment]
This sounds like the use case that npm [package scripts](https://docs.npmjs.com/misc/scripts) were designed to address. From your description of the problem, it doesn’t sound like you need a user-wide hook to run Maven for projects that have JVM dependencies. Instead, you could write a bit of tooling that pulls whatever metadata you want from `package.json` (although it would probably be simpler just to include a `pom.xml` file alongside `package.json`) and run that tooling from a [`postinstall`](https://docs.npmjs.com/misc/scripts#examples) script. If you do this for each one of the projects that has a Maven dependency, it will be called recursively at install time.

Because this is something that I think npm’s current feature set already provides, and because as far as the team can see this addresses your use case, I’m going to close this feature request. Thanks for your time, and for your patience!

(A brief side note: the npm JS API is messy and hard to use properly, so as of `npm@3`, we deprecated it and do not recommend or support that other projects make use of it. In this case, it’s a bit of a moot point, since you probably should use a mechanism that’s built into npm already, but I get a little twitchy when I see code that tries to embed npm, because there are dragons there.)
