### ISSUE TITLE
npm.commands.search fails and dumps 100+ Mb to output log

### ISSUE THREAD

**Issue by outbounder** [npm/npm#6016]
Hi npm team,

I've been playing with the programmatic api of npm, namely `npm.commands.search`.

Yesterday I've left a script based on that api command to run for some time and observed interesting behavior which I though might help:
1. here is the [source code](https://github.com/node-organic/node-organic.com/blob/ecf584c0c66a4c33c77a74de9f5dadeec906b398/plasma/npm-organic-modules.js) which produces the odd behavior/results
2. I've inspected the produced output log and it contains the following content:

```
Error: Unexpected end of input
...
... a very very long json dump 138+Mb ...
...
sm.git"},"author":{"name":"Carsten Nielsen","email":" <-- email intentionally removed -->"},"bugs":{"url":"https://github.com/heycarsten/ember-fsm/issues"},"license":"MIT","readmeFilename":"README.md","time":{"modified":"2014-06-02T19:10:37.452Z"},"versions":{"0.3.0":"latest"}}
        at Object.parse (native)
        at RegClient.<anonymous> (/home/node/node-organic.com/node_modules/npm/node_modules/npm-registry-client/lib/request.js:266:23)
        at Request._callback (/home/node/node-organic.com/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
        at Request.self.callback (/home/node/node-organic.com/node_modules/npm/node_modules/request/request.js:123:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (/home/node/node-organic.com/node_modules/npm/node_modules/request/request.js:893:14)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (/home/node/node-organic.com/node_modules/npm/node_modules/request/request.js:844:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:938:16
```

Here are couple of observational notes of mine in addition :
- the same source code runs on my local workstation without any errors. I guess that is because of cache which seems not present on the remote server :? 
- the source code atm is modified to run `npm.commands.search` only once and the issue is found everytime. However yesterday it was working just fine within reasonable comamnd exeuction time of 8-10s and refresh interval of 5 mins. Today I've disabled the refresh interval as to prevent any further complications in regards to debugging it :)

Having the above said do you think that using `npm.commands.search` to acquire metadata for specific `set` of npm published modules is good idea?

I've introduced myself today to gulpjs plugins website implementation also but sadly I think that running java and elasticsearch for just querying 45 modules in total for the moment seems a little bit too heavy :?

**Comment by examinedliving** [comment]
Just an addendum from #4868 (now closed).  

`npm search ...` works find from command line on my Windows box using Windows OS.  The problem arises when I am running VM in Vagrant or ssh to remote pc.  

Leads me to believe that (at least in my situation), the problem is somehow related to Linux only (various distros), or to ssh, or both.

**Comment by othiym23** [comment]
It's not Linux-specific, it's memory-specific. npm has to load the entire JSON file containing all of the metadata about all of the packages on the registry, and this takes a few hundred megabytes of RAM, which may or may not be available in a vm doing other things.

**Comment by silkentrance** [comment]
Why not use a local sqlite3 db for storing the package index?

**Comment by silkentrance** [comment]
Just noticed while doing a `npm search namespace` and with approx. 1GiG of free memory, it will at first consume around 400MiB rather slowly. After that, memory consumption will grow exponentially.

**Comment by othiym23** [comment]
> Why not use a local sqlite3 db for storing the package index?

Because npm needs to work out of the box on Node / iojs's initial install, and therefore can't have any native dependencies. @smikes has been playing with a [pure-JS solution](https://github.com/smikes/npm-kludge-search) that looks interesting and promising, and longer-term, we have plans to replace / augment the offline npm search (i.e. the current implementation) with online search against the npm search service. This latter bit is why we haven't sunk a ton of time into this bug -- I'm much more interested in solving the search problem once, for users of all npm-related services, than I am in coming up with independent implementations for different pieces of npm. Especially because solving the search problem is an infinite yak shave.

**Comment by othiym23** [comment]
> whenever I try to do a trivial task such as `npm search....` :grin:

"trivial"

**Comment by silkentrance** [comment]
I hate that word, too. My math prof used it a lot.

**Comment by jacobstr** [comment]
Filtering / parsing / mapping json streams? [Considered jq?][(https://github.com/stedolan/jq).

External binary might be an issue. Pipe it through emscripten? ;)

**Comment by duaneking** [comment]
Question: Why can't you just build the cache a file at a time to keep memory usage small?

If every package has it own file as its own record, stored under a set cache directory as its own record,  search can be local and you can then use the file system as if it was a database easily enough as at that point the directory listing becomes the index.  A curl http listing of the directory on a remote server becomes the remote copy of the index (and stream-able, so no memory issues exist.)

I'm just here because this issue is blocking my ability to use npm fully on my new RasberryPiB+ and I'm sure I'm not the only one who wants to use it for this.

**Comment by othiym23** [comment]
@duaneking there are many potential solutions to this problem, but the current implementation suffers from the fact that `npm search` was designed and implemented when @isaacs more or less knew _all_ the authors writing modules. It's always been a quick and dirty approach, and it has clearly scaled past the point where the current approach is scalable. We just haven't had time to design and implement a replacement yet.

**Comment by maxpolk** [comment]
On a 512MB mem, 20GB SSD drive VPS, new Ubuntu install of "nodejs" and "npm", first use of "npm search backbone" failed until I jacked up the swap file size:
(1) command took 20 minutes; (2) about 1000 lines of output; (3) peak swap usage 1.81GB; (4) network bandwidth reasonably small; (5) high CPU usage for the full 20 minutes; (6) high disk I/O averaged 3 to 10 MB/sec continuously probably thrashing; (7) the swapfile expanded to permit "npm search" to complete now takes up 1/7 of the whole drive.
The space and time complexity is enmeshed in finite-space systems when the algorithm exceeds available memory, because swapping begins to occur, which means slow disk I/O, even on the SSD drive.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by iamjochem** [comment]
+1

this broken for me too (I do not currently have a local cache file at `~/.npm/registry.npmjs.org/-/all/.cache.json`) ... my Mac has at least 6 Gigs of free memory (and about 3.5 Gigs of swap space) but `npm search` dies (pretty sure it's just hitting the 1Gig memory limit of node)

**Comment by jdub** [comment]
A fresh `npm search` aborts with a heap allocation failure on my 8GB MacBook Air, and even after manually refreshing the cache, `npm search` aborts with a heap allocation failure.

This problem is only getting worse:

```
$ curl -s https://registry.npmjs.org/-/all > ~/.npm/registry.npmjs.org/-/all/.cache.json
$ ls .npm/registry.npmjs.org/-/all/.cache.json 
-rw-r--r--  1 jdub  staff   179M 29 Jul 19:30 .npm/registry.npmjs.org/-/all/.cache.json
```

**Comment by iamjochem** [comment]
could SQLite be a way out? I hacked together a proof-of-concept which someone might want to take a look at:

>  https://github.com/iamjochem/npm-search-sqlite

it's bare bones but maybe it's something that could be used as a starting point to getting `npm search` working?

**Comment by othiym23** [comment]
> could SQLite be a way out?

Unfortunately, no. The CLI can't add dependencies on any native modules, because otherwise it can't bootstrap itself.

**Comment by silkentrance** [comment]
How about adding a configuration setting that allows the user to use a different search implementation when available, say npm-search-sqlite that then would be used instead of the native npm search command?

**Comment by iamjochem** [comment]
okay so no native modules, what about if you used https://github.com/kripken/sql.js ?

**Comment by ILMostro** [comment]
Two years is an eternity in tech.  NodeJS does not depend on `npm`, by the way.  Any status updates on the "server-side" search implementation?

- The CLI can't add dependencies on any native modules, because otherwise it can't bootstrap itself.  Therefore, **SQLite is a No-Go**!
- The `npm search` function expands RAM usage exponentially while it tries to read in an exponentially-increasing *JSON* file with list of packages
- Some have reported success increasing `swap` file/partition as a workaround
- Some have reported failures on systems with plenty of Available RAM and swap, assuming 1G NodeJS limit to be culprit
- Initial approach to deal with npm search queries has been outdated and problematic for years, now.
- `npm search` seen as "trivial", users expected to search with browser, install with npm
- Additional complexity, perhaps, due to FLOSS/proprietary Licensing of "potential" solution(s).
-  "*there are many potential solutions to this problem*"
as of yet, none have been implemented to "solve" a growing problem
-  This issue is being tracked from the server side at npm/npm-www#911.

**Comment by jpaulin** [comment]
Any similarity in the good old' Internet dawn, when HOSTS file was copied between computers. Then when the number of connected devices grew, this method of "phone book" copying between the mesh would almost choke the net itself, and thus DNS was born?
