### ISSUE TITLE
npm dedupe doesn't work with devDependencies - why?

### ISSUE THREAD

**Issue by donaldpipowitch** [npm/npm#6036]
Hi,

I can't figure out why it seems that `npm dedupe` does nothing. I have a `package.json` with `grunt-karma` and `grunt-jscs` as `devDependencies`. Both modules use `lodash@2.4.1`.
I expected `npm dedupe` would remove all nested copies of `lodash@2.4.1` and place one copy of `lodash@2.4.1` in the first hierarchy level, but instead nothing happens. I tested this with `npm@2.0.0-beta.0` and `npm@1.4.25` and `node@0.10.31`.

**Comment by smikes** [comment]
@iarna will this disappear with multi-stage-install?

**Comment by zxqfox** [comment]
Am... What if we go the current way only with --production flag? I don't understand why it can't use devDeps as well as deps. It also can warn about conflicts or/and left dupes.

**Comment by iclanzan** [comment]
This issue if bugging me right now.

**Comment by lukeapage** [comment]
+1

**Comment by zdychacek** [comment]
+1

**Comment by altano** [comment]
I'm currently trying to deal with the max-path issues between Windows & NPM and this is getting in my way.

**Comment by aldendaniels** [comment]
+1

`npm shrinkwrap` should be used to ensure consistent versions between development and production. `npm dedupe` should (IMO) dedupe everything. At a minimum, `npm dedupe --dev` option would be nice.

**Comment by Rask** [comment]
+1

Having the same issue as @altano, working with Windows and the long pathnames are breaking only with my projects's defined `devDependencies`.

**Comment by CKarper** [comment]
+1 

My windows builds are broken, due to grunt long names and deep dependencies.  Well, due to windows file length limitations, but this workaround is no workaround at all without including dev deps.

**Comment by eggers** [comment]
+1

**Comment by rempatterson** [comment]
unsubscrube

**Comment by tiefling** [comment]
I'm having similar issues to many others here where NPM causes issues with tools like grunt and gulp on windows due to the dev dependencies issue.

Fixing this issue would allow NPM to be used properly across the board. Unless this changes we'll be stuck in a situation where we have to use bower for dev dependencies and npm for production which is nuts.

**Comment by davestewart** [comment]
As a workaround, I set my dev dependencies as normal dependencies, re-ran npm dedupe and then swapped them back. YMMV.

**Comment by tiefling** [comment]
That's fine for a one off (good call) but not too replicable - I was considering moving dev dependencies to bower and using npm for primary dependencies.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Sun, Jul 26, 2015 at 2:56 AM -0700, "Dave Stewart" <notifications@github.com<mailto:notifications@github.com>> wrote:


As a workaround, I set my dev dependencies as normal dependencies, re-ran npm dedupe and then swapped them back. YMMV.

-

**Comment by iarna** [comment]
When I implemented the `npm@3` version of the dedupe command I apparently implemented it in the way that was requested here. That is, devDependencies and production dependencies aren't treated differently when deduping.

Because the `npm@3` version of dedupe won't downgrade a module to get a more thorough deduping, my prior concerns are not an issue.

Thanks for filing this and all the discussion here. I'm closing this as resolved.
