### ISSUE TITLE
standalone npm-exec

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6053]
Add a binary to `npm` called `npm-exec` that does basically what `npm run-script` does, but without the `nopt` / `npmconf` command-line parsing of `npm` itself. Improves the situation described in #3494.

**Comment by garrett-gottlieb** [comment]
+1

**Comment by rajsite** [comment]
+1

**Comment by zkat** [comment]
For the sake of getting people's feelings about it -- do you think instead of something specifically like `npm-exec` (or _only_ having `npm-exec`), that something like `virtualenv`'s `activate` functionality would be desirable in general? Would that fulfill the needs this is meant to fulfill any better?

For those unfamiliar, I would imagine it to work something like this:

```sh
$ cd path/to/proj
$ npm i standard
$ npm activate
(proj)$ standard
(proj)$ npm deactivate
$ standard
command not found: standard
```

**Comment by es128** [comment]
@zkat I don't see how your proposal would help with the type of use cases most people need this feature for. How would anything be accomplished with a single shell command? Something like `npm activate && standard` wouldn't work and is no improvement over the `npm-exec` ideas anyway.

**Comment by zkat** [comment]
There's two workflows you're talking about here: uncommon, quick, one-off commands (that `npm-exec` shines in), and long-term, project-level workflows where it's slightly more verbose (where `activate` might be more helpful).

At least I remember spending quite a bit of time helping people make sure their `grunt`, `webpack`, etc commands were properly installed, globally, because `$(npm bin)/grunt` was kinda verbose and ugly to be typing constantly.

**Comment by es128** [comment]
I was referring to both cases. Don't see how `npm activate` helps any more than (or even as much as) a bundled `npm-exec`. It's kind of a style preference, I guess? Perhaps you can elaborate further on what benefits you see with your idea.

**Comment by bcomnes** [comment]
> npm activate
  npm deactivate

I'm opposed to replicating virtual env because getting away from global dependency hacks is what makes npm totally great!  I know this wouldn't bring global deps, but it would affect global shell state.  It would be better if we can keep things contained inside project folders, including shell command context.  I'm worried this would allow python devs coming to to node to be lazy and not learn why npm scripts, local by default and recursive dependencies are more reliable (and way less annoying) than virtual environments.  E.g. Npm activate then run this series of 5 different commands vs `npm i ; npm run build`

Being able to pass arguments and flags into `npm` scripts would be totally great, even if it requires a dedicated command to do it.  `npm` scripts encourage package maintainers to think about what tools are required to work on their package, and simmer their use down to specific use cases via the defined scripts.

Here is a good compromise I think:

This might lead to naughty dev behavior, but can `npm-exec` also add the relevant `node_modules/.bin` to the search path in its execution scope?  That way you can run one off commands that have been installed as a dependency or devDependency e.g. `npm-exec standard` if standard lives in `node_modules/.bin` in the project folder you are currently cd'd into.   

It would be like `bundle exec` but instead of doing hacky global dependency resolution, it would just stub the `node_modules/.bin` cmds into the execution scopes path just like an npm script has access too.

**Comment by aredridel** [comment]
npm scripts do accept flags -- `npm run scriptname -- args`

**Comment by bcomnes** [comment]
> npm scripts do accept flags -- npm run scriptname -- args
I thought that was the case.  Does `npm-exec` do something else wrt flags?

**Comment by es128** [comment]
it won't require the `--` anymore, it'll just pass through any arbitrary flags to the underlying command

**Comment by bcomnes** [comment]
Updated my comment to reflect a deeper understanding.  Ty

I think a command that allows flags without ` -- ` would be nice, but it would be nicer if it provided access to `node_modules/.bin` as well.  This would make the CLI interface similar to [bundler.io](http://bundler.io/) when accessing one off devDependency commands, which would save me from having to `-g` more modules.

**Comment by es128** [comment]
> if it provided access to node_modules/.bin as well

It does, that's exactly the point of it (both the current `npm run` and the proposed `npm-exec`)

**Comment by bcomnes** [comment]
> It does, that's exactly the point of it (both the current npm run and the proposed npm-exec)

`npm` scripts have access to `node_modules/.bin`, but unless you wire up the script to the command living in `node_modules/.bin`, you can't run the commands directly from `npm run $command name`.

I'm asking for `npm-exec` to provide access to `node_modules/.bin` directly... not just through a script.

**Comment by iarna** [comment]
@zkat That sounds a lot like `npm explore` if it set lifecycle style environment? (speaking of, it probably should muck with PS1/PROMPT)

**Comment by bcomnes** [comment]
Please don't mess with my PS1 :(

**Comment by nfroidure** [comment]
A lil question, why `npm-exec` instead of `npm exec`? That would allow to add pre/post hooks to CLI commands. `npm exec` would be an alias to `npm run exec` like `npm test` is for `npm run test`.

In fact, by just creating the alias, you would be able to run shell commands in the npm run env like that `npm exec -- mocha **/*.js`.

I know i'm a bit late on this issue but later is better than never ;).

**Comment by ljharb** [comment]
@nfroidure that's shell parlance. `npm-exec` means `npm exec` would work as you expect.

**Comment by nfroidure** [comment]
@ljharb nice! Thank for the explanations.

**Comment by othiym23** [comment]
`npm exec` !== `npm-exec`. There is a specific reason to have `npm-exec` be a separate binary and an independent command, which is that npm's configuration and command-line parameter handling is fantastically complex, and there's no way to allow the full ability to pass uninterpreted arguments to installed binaries and run-scripts, even with `--` as an escape. `npm-exec` would have much simpler rules around that than an npm subcommand could.

**Comment by ljharb** [comment]
Ah, I misunderstood then - a `git-foo` binary is typically run with `git foo` even though it's separate.

**Comment by othiym23** [comment]
That's a natural assumption to make! npm is explicitly _not_ following that convention, though (I want npm to have a fixed set of flexible but comprehensible commands, instead of an extensively open set of commands). In this case, that wouldn't solve the underlying problem, either.

**Comment by es128** [comment]
Maybe it's not desirable from an idiomatic point of view (or maybe it is), but wouldn't it theoretically be possible to have `npm exec` call out to `npm-exec` early, short-circuiting all the other stuff going on with the `npm` cli that makes it too complex to fix this for `npm run`?

**Comment by othiym23** [comment]
It would basically amount to completely splitting apart the bootstrapping code for the CLI, which would be a substantial rewrite, and would probably be a major breaking change because of the implications of splitting things up that way. It'd be easy to hack in, but we'd be chasing the fallout for months or even years. Having a separate command (that's bundled and installed alongside the npm binary, so you get it with the npm install) is the cleanest solution.

**Comment by es128** [comment]
Makes sense to me :+1:

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by sindresorhus** [comment]
> I'm asking for npm-exec to provide access to node_modules/.bin directly... not just through a script.

:+1: This would pretty much remove most needs for installing anything globally as I could easily just run local binaries with `npm-exec <bin>`, eg `npm-exec gulp`. I know I could set up a "proxy" run script, but that's annoying when you just want to run the binary.

**Comment by jmm** [comment]
@sindresorhus Totally agree.

@othiym23 Thanks for the link to the roadmap. It doesn't include keywords or issue numbers, so it's pretty hard to find items like this (e.g. I get nothing by searching the page for "exec" or "6053"). I had to dig to find it under:

```
3. Architecture, user experience, and design
   1. Assess npm's usability and overhaul its user experience.
```

How would you feel about the roadmap being annotated with some keywords and issue numbers?

**Comment by nfroidure** [comment]
> I know I could set up a "proxy" run script, but that's annoying when you just want to run the binary.

That's actually what i ended up to do but it would be a great pleasure to remove it. :+1:

**Comment by eush77** [comment]
> I'm asking for `npm-exec` to provide access to `node_modules/.bin` directly... not just through a script.

That's strange. Can't you just append `./node_modules/.bin` to your `$PATH`? Do you really need an npm command for that?

**Comment by ljharb** [comment]
@eush77 no, it's not that trivial, because you might have nested dependencies. You absolutely need an npm command for that, to be reliable for all cases.

**Comment by stevenvachon** [comment]
Is this going anywhere?

**Comment by jods4** [comment]
BTW, **yarn** has that feature. `yarn run xxx` will look into your local `node_modules/.bin` if there is no `xxx` in your `package.json` scripts.

You can pass parameters to the executable after a double-dash: `yarn run gulp -- build`.

**Comment by stevenvachon** [comment]
I'm currently using the double-dash separator, but it looks kinda bad in documentation.

**Comment by legodude17** [comment]
@othiym23 what is the progress on this?

**Comment by zkat** [comment]
@legodude17 See the `patch-welcome` tag. That literally means we're waiting for someone to submit a patch.

For the rest of y'all, I've been using ` alias npmE=PATH="$(npm bin)":"$PATH"` in my `~/.{zsh,bash}rc` to do this (it's also included in the `oh-my-zsh` npm plugin, ootb). It's worked pretty alright. :)

Of course, it doesn't set up all the environment variables that `npm-exec` is meant to, but I suspect what a lot of people want is to be able to run locally-installed binaries from their shell instead of having to install them globally? So hopefully this helps that use-case.

**Comment by legodude17** [comment]
Let me share my progress on `npm-exec`:
![npm-exec](https://cloud.githubusercontent.com/assets/11205096/21032494/9b169bae-bd5e-11e6-8606-40bbe2a7a2a8.png)

**Comment by legodude17** [comment]
I am a little stuck with the passing commands part, because `sh` is being a little dumb:
![image](https://cloud.githubusercontent.com/assets/11205096/21032588/3dc89e88-bd5f-11e6-8269-844d0f6f7314.png)

**Comment by legodude17** [comment]
Nevermind, I got it. :smile: 
With this package.json:
```json
{
  "scripts": {
    "cat": "cat"
  }
}
```
I get this:
![image](https://cloud.githubusercontent.com/assets/11205096/21032976/1a078c90-bd62-11e6-9508-422fbc147e87.png)

**Comment by legodude17** [comment]
@zkat and @othiym23, would a PR be accepted to include [this](https://github.com/legodude17/npm-exec) in `npm`, maybe as a single file?

**Comment by senotrusov** [comment]
In the current documentation on `npm run` it is described that all arguments after the `--` will be passed to the underlying script. Which is indeed happens.

However, if one execute `npm run myScript foo bar:qux`, then `foo` and `bar:qux` will also be passed to the underlying script, even without the `--` part.

If arguments will be prefixed with dash(es) like `--foo` or `-foo` then npm will consume such arguments and will not pass them to the script.

The ability to pass that simple `foo` arguments – is it a bug of a feature? Will that behaviour be supported in future npm versions?

Thank you!

**Comment by jfsiii** [comment]
@senotrusov `npm run myScript -- --foo --bar` will pass `--foo --bar` to `myScript`

**Comment by senotrusov** [comment]
@jfsiii yes, indeed. But if you run `npm run someScript foo bar` then `foo` and  `bar` will also be passed to the script. I was just wondering is it an expected behaviour or not, so I could rely on that in my code.

**Comment by ljharb** [comment]
Yes, this is expected behavior, it follows unix conventions, and you can rely on it.

**Comment by senotrusov** [comment]
@ljharb Thank you Jordan!

**Comment by zkat** [comment]
We're planning on including [`npx`](https://npm.im/npx) in an upcoming npm release. It will be available both as an `npx` binary and through `npm exec`/`npm x`.

It already works, and is getting pretty stable. I encourage y'all to try it out and let us know what you think. It does a few more things than the baseline suggested here, too! You can even access the npm lifecycle script environment using `-c`, like `npx -c 'echo $npm_package_version'`!

**Comment by ljharb** [comment]
@zkat how far back does npx work? like, on which versions of node?

**Comment by ljharb** [comment]
fwiw, per https://github.com/zkat/npx/issues/30, `npx` doesn't solve all the [use cases](https://github.com/npm/npm/issues/6053#issuecomment-60001889) for this issue, because it requires node 4+ :-/

**Comment by stevenvachon** [comment]
@ljharb a comment from 3 years ago, referencing a Node version that's been unsupported for almost 1 year.

**Comment by ljharb** [comment]
@stevenvachon my comment, which is still relevant today, and "unsupported by node" doesn't mean "unsupported by anyone". Thanks for your valuable contribution to the conversation tho.
