### ISSUE TITLE
Reduce `update` time

### ISSUE THREAD

**Issue by zhanzhenzhen** [npm/npm#6060]
Wondering if npm can do something to reduce `npm update` time.

First, client sends the current dependencies tree structure (plus `"dependencies"` fields in all "package.json" files) to the server, in a single request.

Then, server determines which packages needs to be updated, and send the tree structure to the client in the single response.

Then, the client begin to download the missing or outdated packages.

I think in this way the `update` time (if no downloads needed) can be reduced to < 1sec, though it requires additional server-side computing.

**Comment by othiym23** [comment]
As part of a larger, longer-term effort to help npm, Inc. control its bandwidth costs, and also to reduce the resources used by the package installation process, the npm registry team is in the early stages of planning a new registry API. This new registry will, in effect, do exactly what this issue requests, in that it will use a new, much more efficient protocol to sync the state of the local install with what’s available via the registry. This is work that will be happening in the medium term (6-18 months), and there will be plenty of discussion of it, both here and on the [registry issue tracker](https://github.com/npm/registry/issues). Because this is a large project involving the whole company, it doesn’t really make sense to tie this to a single feature request on the CLI, and so I’m going to close this issue, but rest assured, there will be more to read soon. Thanks for your time and patience!
