### ISSUE TITLE
Issue while installing grunt and node. Need urgent help.

### ISSUE THREAD

**Issue by rashmi1988** [npm/npm#6099]
Dear npm Group,

I was using version 0.8.15 of nodejs from below link. npm version is 1.1.16.
  
                 http://blog.nodejs.org/2012/11/26/node-v0-8-15/

Then, I used to install grunt version 0.3.17 using terminal. Also, I used phantomjs 1.8.1 version from below link.

http://code.google.com/p/phantomjs/downloads/detail?name=phantomjs-1.8.1-macosx.zip&can=2&q=

Everything used to work fine while installing everything and during development. Due to some requirements, i uninstalled everything and trying to re-install now.  

Now, while grunt using below command i am getting error. 

            npm install -g grunt@0.3.17  --save-dev

Error:

Error: No compatible version found: minimatch@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.4","0.0.5","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.3.0","0.4.0","1.0.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "grunt@0.3.17" "--save-dev"

I am not able to proceed from here. I need help urgently. Please help me out of here. Thanks in advance.

**Comment by smikes** [comment]
Is this still a problem for you?

It is hard to provide complete and generic **uninstall** instructions because there are many legitimate ways to **install** node, npm, and phantomjs.  For example if you initially installed `node` using `homebrew`, the solution would be to run

```
brew update
brew upgrade node
```

But if you installed using the `.pkg` file from <https://nodejs.org/downloads> then the best way to get a new version is to download the latest pkg file.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
