### ISSUE TITLE
Add support for a "don't show in npm search" package.json option

### ISSUE THREAD

**Issue by iarna** [npm/npm#6107]
This would be a hint to the npm search results to exclude these modules.  (As a hint, we might want to allow searchers to include these modules in their search results if they request it.) These modules would still show on your user account and would still be indexed by external search engines.

This would be intended for modules that would be discoverable in other ways, eg, via collections, tags or other module listings. This would help with scenarios such as: the requirify wrapper modules, and modules that split out every supporting class as a separate package thus taking up several pages on searches for that topic.

**Comment by othiym23** [comment]
There are many things to do to improve npm's search results; the underlying request behind this issue is to help surface the most relevant results for a given query, and to provide hints that submerge less relevant results. This sounds like something to keep in mind as we work on search as a product, but this feature on its own is probably not going to get shipped as described. Thanks for the problem statement, though!
