### ISSUE TITLE
A proposal for peerDependency & something extra

### ISSUE THREAD

**Issue by youssefkefal** [npm/npm#6134]
I have read so much about how peerDependency isn't working and I have started working on something that could help.

I have created a small repo that summarizes my thoughts [Pluggy](https://github.com/youssefkefal/pluggy) and provides a first version of the broker.

### TL;DR;
1. Using an `npm-dedupe` like strategy to flatten the dependency tree to only one `node_modules` folder per app (none of the packages in `node_modules` will have children dependencies)
2. The result is an `npm-cache` like storage for the modules (`node_modules/packageName/Version/`)
3. Introducing a `version broker` in each `node_modules/packageName` to resolve the versionning.
4. Maybe introducing a custom versionning strategy for those who don't like(or don't want) to use `semver`

What I need is feedback from the community about the things that I am unaware of. npm does so many things and I am not sure I have a complete grasp of everything.

@isaacs, @hueniverse (Sorry guys you are the only two references that I know of. Isaac for running npm and Eran for Hapijs that relies on the npm peerDependency for the plugins)

**Comment by othiym23** [comment]
There have been three important developments since this feature request was filed that have a significant impact on this proposal:

1. [How `peerDependencies` work](https://github.com/npm/npm/issues/6565) has been revamped in `npm@3`.
2. `npm@3`’s new installer already performs [maximally flat installs](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat).
3. New Node package installers, like [ied](https://github.com/alexanderGugel/ied) or [pnpm](https://github.com/rstacruz/pnpm), already use a filesystem layout like the one you describe for Pluggy, without altering the mechanics of package resolution, versioning, or loading.

To me, what this says is that there’s a bit of a conflation of concerns going on here:

1. Coming up with a better way to handle plugins within an application.
2. A more “optimal” layout of the install tree on disk.

Either one of those is useful to discuss on its own, but trying to talk about both at the same time is likely to be unproductive. At the same time, quite a bit has happened in the last two years, so it’s a good idea, maybe, to restart the discussion from a fresh basis. As such, I’m going to close this issue, but if you see opportunities to improve npm around either 1 or 2, please do file new issues to discuss those topics. Thanks for your time!
