### ISSUE TITLE
Feature request: Declare modules as "singleton"

### ISSUE THREAD

**Issue by mantoni** [npm/npm#6164]
First of all, I love the fact that npm allows me to have several versions of the same package installed.
However, here's the thing:

I use npm for browser and node packages and run `npm dedupe` after installs to make sure to have as few dupes as possible (my tree has more than 300 modules). Having dupes (especially with major version changes) is fine in most cases, but for some modules this is not acceptable. For example, a module that instantiates a WebSocket connection with the node backend should never be loaded twice. Or on the node side, I never want a module loaded twice that connects to a queue or starts listening on a specific port.

Currently, I have to put horrible hacks into my code to prevent this from happening at runtime, but an "install time" failure could make the CI build fail.

npm already warn about unresolvable dupes, but I want `npm dedupe` to actualy fail if there are dupes for these kind of modules.

My suggestion would be to add a `singleton : true` property to the package.json (or any other flag) and if a package with that property has dupes, `npm dedupe` has an exit code other than `0`.

Thoughts?

**Comment by mischkl** [comment]
Methinks this would generally be useful when wanting to share one version of a library across all modules in a project. for instance, we have one library that bundles all third-party libraries in order to provide centralized version control for all other modules. peerDependencies seems like a solution until you consider that any time you define something as a peerDependency your package is effectively broken if it's not used in the context of a parent package. There are plenty of situations where a module may need to be used independently or as a child module (e.g. component-based web apps, where each component must also be able to execute its tests independently).

In this case being able to share 1 version of our core library would be very helpful, and wouldn't cause the peerDependency problem of not being able to use something standalone.

**Comment by pwmckenna** [comment]
nconf is basically unusable for shared configuration if you can't guarantee that everyone is using the same underlying configuration.

**Comment by saalmaan** [comment]
@mantoni 

> I love the fact that npm allows me to have several versions of the same package installed

what do you mean by that?

**Comment by mantoni** [comment]
@saalmaan npm makes use of the [node package resolution algorithm](https://nodejs.org/dist/latest-v6.x/docs/api/modules.html#modules_loading_from_node_modules_folders) to resolve conflicts. Even if I pull in two libraries (A and B) that both depend on different / incompatible versions of C, npm installs two copies of C (C' and C'') so that A will load C' and B will load C''. There is also a nice explanation [in the npm documentation](https://docs.npmjs.com/how-npm-works/npm3-dupe) on how duplicates are handled.

**Comment by iarna** [comment]
There are two distinct issues being discussed here:

First, front end web development has different constraints around modules and often needs modules to not be loaded more than once (globals, singletons) or not included more than once (size constraints).

Second, singleton patterns are often useful for many of the reasons you’ve outlined, db connection pools, configuration, logging, really any cross-cutting concern.

There are some workarounds for the second scenario in particular. For instance, if you want to enforce a singleton pattern as a **consumer**, you can use modules like [singleton-require](https://www.npmjs.com/package/singleton-require) or [global-singleton](https://www.npmjs.com/package/global-singleton) or even [module-singleton](https://www.npmjs.com/package/module-singleton).

If you want to publish **your own** module that enforces this pattern, you can simply look at those implementations and do it yourself–this is beneficial because you’ll get to choose exactly what happens if something is required twice: you could warn, or error, or simply replace the old version, or ignore any new ones. The number of (perfectly valid) solutions to this also makes it harder for npm itself to make a choice about it.

I’m going to close this issue because the CLI team won’t have time to address these in the next six months.

**Comment by mantoni** [comment]
@iarna Thanks for clarifying and linking some user-land solutions. I ended up working around it with some custom Browserify based logic.

**Comment by anilanar** [comment]
There's only 1 reliable object that one can use to have in-process global state, `global`, when using NPM. 

Hurray, let's go back to days when every library threw its own junk into `window` object.
