### ISSUE TITLE
"no compatible version found" doesn't indicate which dependent caused failure

### ISSUE THREAD

**Issue by dylang** [npm/npm#6180]
I think this is the sort of error a lot of users may see after they upgrade to `npm@2.0.0` with the new version of `semver`.

```
npm ERR! notarget No compatible version found: phantomjs@'>=1.9.0 <1.10.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8",
  "0.0.9","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6",
  "1.8.0-1","1.8.1-1","1.8.1-2","1.8.1-3","1.8.2-0","1.8.2-1","1.8.2-2","1.9.0-0",
  "1.9.0-1","1.9.0-2","1.9.0-3","1.9.0-4","1.9.0-5","1.9.0-6","1.9.1-0","1.9.1-2",
  "1.9.1-3","1.9.1-4","1.9.1-5","1.9.1-6","1.9.1-7","1.9.1-8","1.9.1-9","1.9.2-0",
  "1.9.2-1","1.9.2-2","1.9.2-3","1.9.2-4","1.9.2-5","1.9.2-6","1.9.6-0","1.9.7-1",
  "1.9.7-3","1.9.7-4","1.9.7-5","1.9.7-6","1.9.7-7","1.9.7-8","1.9.7-9","1.9.7-10",
  "1.9.7-11","1.9.7-12","1.9.7-13","1.9.7-14","1.9.7-15","1.8.2-3"]
```

#### Problem 1: Which dependency is requiring this unknown version of `phantomjs`?
We should give the user a tree that shows where this request came from so they know where to find the error-causing `package.json`. 

#### Problem 2: Why don't I see `'>=1.9.0 <1.10.0'` in any `package.json` files?
The `package.json` actually has `"~1.9"`. We should also show the original string so that authors know what the bad value is in their `package.json. 

#### Can we provide a little guidance?
Should we link to some pages to give users a little help? 
* [npm doc/misc/semver](https://www.npmjs.org/doc/misc/semver.html)
* [semver.org](http://semver.org/)
* [node-semver](https://github.com/npm/node-semver)
* offending packages' homepages

**Comment by iarna** [comment]
This is something I’d like to have. Our error messages around failed dependencies don’t always include the context needed to debug them. Currently we annotate failed install errors with a property called `parent` which is the name of the package depending on the failed package. This is often helpful but for transitive dependencies it is still insufficient.

I would approach this by extending that mechanism to include the node from the package tree instead of just the name. You can see where the name is added in [lib/install/and-add-parent-to-errors.js](https://github.com/npm/npm/blob/master/lib/install/and-add-parent-to-errors.js). That, combined with updating [lib/utils/error-message.js](https://github.com/npm/npm/blob/master/lib/utils/error-message.js) to include a full reporting of what required the failing package should resolve this issue.

The CLI team is not going to be able to work on this in the next six to twelve months. As such, I’m going to label this patch-welcome and close the issue. If someone wants to pick this up, we would be happy to help you prepare a pull request. Thank you for reporting this!

**Comment by fdambrosio** [comment]
I have similar problem with 
`No compatible version found: cordova-plugin-streaming-media@~0.1.4`
