### ISSUE TITLE
deprecate `npm install --dev`

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6200]
It's unnecessary, overkill, and probably never the behavior a developer actually wants, unless they're really nostalgic for `hoarders`.

**Comment by christianbundy** [comment]
Any movement on this?

**Comment by lloydde** [comment]
Using npm 2.7.5 I hit the installing devDependencies recursively thing today with a young project that uses gulp which as a n00b also has the confusing sequence of both installing gulp globally and locally and --save-dev , https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md .

**Comment by othiym23** [comment]
We're actually going to fix this a different way -- see #9024 for details.

**Comment by jbeard4** [comment]
Hi,

I understand that `npm install --dev` has been deprecated. Is there an alternative approach to installing transitive devDependencies?

Please consider the following reduced scenario where installing transitive devDependencies is needed.
I have packages A, B, and C. A depends upon B at runtime; and C is used to build a browser-friendly version of B with browserify. Specifically, C is a [browserify transform](https://github.com/browserify/browserify-handbook#browserifytransform-field). I want to build A with browserify, such that the resulting browserify bundle includes B.

The way that I would like to achieve this is to put B in A's dependencies, and put C in B's devDependencies, then run `npm install` on A. However, because C is in B's devDependencies, C is not installed when running `npm install` on A. Then, when browserify is run on A, it results in a message like: `Error: Cannot find module 'C' from 'B'`, because B's devDependency C has not been installed, due to the fact that devDependencies are not installed transitively.

I believe this problem is generalizable to scenarios where you want to build some package A that has a dependency on some package B, that requires a specific package C to be installed in order to build B. Therefore, C is transitively required to build A.

Ideally, I would like to run `npm install --dev` in A in order to install B's devDependencies, so that I could build A against B. As `npm install --dev` has been deprecated in recent versions of npm, here are the alternative solutions I have considered:

  * Clone B manually from git, run `npm install` in B in order to install B's devDependencies locally (including C), and then run `npm link B` inside of A in order to create a symlink to B. The disadvantage of this approach is that it requires a lot of manual configuration in order to create and maintain the package dependency structure; and there is also the possibility of a version mismatch between A and B. Also, running `npm install` in A seems to automatically delete my package symlinks, and install packages from npm in their place. So, this is a brittle solution.
  * move B's devDependencies into B's dependencies. The advantage of this approach is it ensures that C will be installed transitively when A is installed. The disadvantage is that it ensures C will be installed in production, where it is not needed.
  * copy B's devDependencies (C) into A's devDependencies. This will ensure C is available when A is installed. The disadvantage of this approach is that A now needs to know and track all of its transitive dependency's devDependencies, which is an unreasonable maintenance burden.

I have been using the symlink approach, and finding it challenging. I would appreciate any insight as to whether there might be a better approach using the existing npm client. Is there a way to install a package's transitive devDependencies during development?

Thank you.
