### ISSUE TITLE
Should npm fail if git hasn't been installed on a device?

### ISSUE THREAD

**Issue by visualjeff** [npm/npm#6229]
npm on windows 7 and XP devices sometimes fails to detect that Git is not installed.? See below...
```
D:\Users\JGILBER>git
'git' is not recognized as an internal or external command,
operable program or batch file.

D:\Users\JGILBER>npm install -g ember-cli
D:\Users\JGILBER\AppData\Roaming\npm\ember -> D:\Users\JGILBER\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
ember-cli@0.0.46 D:\Users\JGILBER\AppData\Roaming\npm\node_modules\ember-cli
├── abbrev@1.0.5
├── js-string-escape@1.0.0
├── broccoli-writer@0.1.1 (rsvp@3.0.13, quick-temp@0.1.2)
└── yam@0.0.16 (lodash@2.4.1, findup@0.1.5, fs-extra@0.8.1)
```
Shouldn't the npm install be failing???  Git is not installed on this device.

**Comment by othiym23** [comment]
After discussing this again with the CLI team, we've agreed that while the user experience here is suboptimal, it's not something that the CLI needs to handle in the common case. This would indeed be an excellent thing to include in a putative `npm doctor` command, and since this request is linked from #6756, I'm going to close this issue. Whenever somebody has the time and ambition to implment that, this should come along for the ride. Thanks for your time and patience!
