### ISSUE TITLE
`npm link` and `npm unlink` should be mirror operations, and `npm unlink` != `npm uninstall`

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6248]
See #4005 for how the confusion this causes has caused a little forest of forlorn 👍s to sprout up.

**Comment by othiym23** [comment]
Whee.... finally landed this in 7bf85cc372ab5698593b01e139c383fa62c92516.

**Comment by adamski** [comment]
Wish I'd known about this before... just lost a few hours work after realising I was working on my node_modules folder rather than the linked module, did npm link, copied the work over only to realise they are then identical, did npm unlink to remove the link, which then removed the module from my node_modules folder along with all my work... boo hoo :(

**EDIT** saved by AppCode's local history feature, phew!

**Comment by wearhere** [comment]
Follow-up issue: https://github.com/npm/npm/issues/20995 —`npm link` and `npm unlink` are not yet total mirror operations.
