### ISSUE TITLE
Poor npm install node-gyp failure logging

### ISSUE THREAD

**Issue by samccone** [npm/npm#6266]
This is a logging issue that is a problem when trying to debug a failure during an install that utilizes `node-gyp` to build native component(s). 

By default a failed install looks like this as you know

```
 npm install posix-ext

> posix-ext@0.1.1 install C:\cygwin64\home\IEguy\repos\node-posix\node_modules\posix-ext
> node-gyp rebuild


C:\cygwin64\home\IEguy\repos\node-posix\node_modules\posix-ext>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gypnpm ERR! posix-ext@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix-ext@0.1.1 install script.
npm ERR! This is most likely a problem with the posix-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls posix-ext
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "posix-ext"
npm ERR! cwd C:\cygwin64\home\IEguy\repos\node-posix
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
```

So I think to myself, ok so this did not work... I then turn to verbose logging to help me out

buried in the log I then find 

```
gyp info using node-gyp@1.0.1
gyp info using node@0.10.31 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gypnpm verb unsafe-perm in lifecycle true 
npm info posix-ext@0.1.1 Failed to exec install script
```

I think that this is the issue, the real cause of the failure is buried inside of the verbose logging and is pretty hard to grok

I think npm install failures would benefit from a bit better logging when it comes to failures of this nature. Perhaps just output the last line of the command before it tanks... 

Thanks for everything you guys do :heart:

**Comment by othiym23** [comment]
The issue here is that `node-gyp` isn’t particularly communicative when it fails, compounded by the fact that `node-gyp` and npm have fairly similar ways of dumping diagnostic output to stderr when something goes wrong. @samccone, I agree that the results are both noisy and confusing. The noisy part is something that’s generally true of how errors are reported to end users by the CLI, which is a separate issue from this one, and the confusion is something that’s probably best addressed by `node-gyp`’s maintainers, because it really doesn’t give much useful diagnostic output when it bails out.

As such, I’m going to close this feature request as not being particularly actionable by the CLI team. That said, keep an eye on #10491, which at least will ensure that `npm-debug.log` includes `node-gyp`’s output once it’s implemented. Thanks for your time!
