### ISSUE TITLE
Per-registry configuration modifications in a general way

### ISSUE THREAD

**Issue by indexzero** [npm/npm#6270]
Continuation of #6230, #6263, and #6264.

As @isaacs said [here](https://github.com/npm/npm/pull/6264#issuecomment-56420393):
> We are planning to add per-registry configuration modifications in a general way, akin to how you can manage remotes in git. This will involve a major version bump to both npm (ie, it'll be either 3.x or 4.x, depending on whether it lands along with/before multistage-install, or afterwards), and to npmconf.

**Comment by doublerebel** [comment]
:+1:

**Comment by othiym23** [comment]
I still agree with both @isaacs and @indexzero that this would be very useful for users with multiple registries. That said, this isn’t something that the CLI team is going to have the time to land within the next year or so. It would be fantastic if someone wanted to contribute this functionality (maybe as a subcommand to `npm config`?) as a patch, which is why I’ve added the `patch-welcome` label. Because the team itself won’t have the time to implement this, I’m going to close this feature request. Thanks for the clear description of the feature, and your time!
