### ISSUE TITLE
Shrinkwrap and dev dependencies

### ISSUE THREAD

**Issue by tomruggs** [npm/npm#6298]
We have two internal projects one of which includes the other.  I'll refer to them as Stuffing and Turkey.  Stuffing can be used by itself and Turkey includes Stuffing as a dependency.

We use shrinkwrap for both projects and include --dev to ensure that we get a consistent experience for all devs and with CI builds.  The problem is that now with npm 2.0 we have problems building Turkey's shrinkwrap file because npm doesn't like Stuffing's dev dependencies.  

So Stuffing's package.json has Mixing Bowl listed as a dev dependency:
- when I npm shrinkwrap --dev Stuffing it includes Mixing Bowl
- when I npm install Turkey I get Stuffing and Stuffing gets Mixing Bowl (good, expected)
- then I attempt to npm shrinkwrap --dev Turkey

Actual:
- error - extraneous: mixing-bowl@0.0.1 /Users/me/projects/turkey/node_modules/stuffing/node_modules/mixing-bowl 

Expected:
- Turkey's shrinkwrap file should be generated and Mixing Bowl should be listed underneath Stuffing
- this is what npm 1.4.x does

**Comment by tensorproduct** [comment]
I'm running up against this exact problem right now with npm 2.5.1. I have two projects nested within each other, and I would like to shrinkwrap each one.

a depends on b, and b has a devDependency on sinon. The steps I have followed are like so:

    b > npm install
    b > npm shrinkwrap --dev

Then commit the npm-shrinkwrap.json and upload it to git.

From a:

    a > npm install
    a > npm shrinkwrap --dev

But I receive the following error:

    npm ERR! extraneous: sinon@1.14.1 C:\repos\a\node_modules\b\node_modules\sinon npm ERR!

Is there any fix available for this problem? Or a workaround I could follow?

**Comment by tensorproduct** [comment]
> transitive dependencies would end up getting installed according to their package.json files instead of npm-shrinkwrap.json

Maybe I've misunderstood, but wouldn't this defeat the purpose of shrinkwrapping?

I use shrinkwrap so that I can pin all packages in the dependency tree to an exact version. In that way, I can ensure consistency across builds, without worrying that changes to lower-level packages will break my build in some difficult-to-detect way.

It sounds like your proposal would break this functionality. Can you clarify if that's what you mean?

**Comment by othiym23** [comment]
@iarna just carefully examined the behavior of `npm@1`, `npm@2`, and `npm@3`, and discovered that all three had slightly different (and, in some cases, incompatible) behavior when it came to dealing with shrinkwraps here. This led to us doing a little bit of brainstorming over what we consider the _correct_ behavior to be, and then decided that this is what we should correct both `npm@2` and `npm@3` to do:

`package.json` is the single source of truth for npm to use when deciding what should be installed into `node_modules/`. `npm-shrinkwrap.json` enables developers to know, with confidence, that what they tested and built is what they will get later when they deploy that package. There are ways in which end users can manipulate the contents of `npm-shrinkwrap.json` to suit their purposes, but the contents of `npm-shrinkwrap.json` should _never be in conflict_ (i.e. containing packages that wouldn't be in the tree otherwise) with the contents of `package.json`.

In this case, the bad outcome would be if a version of npm were to be too strict about validating the contents of `npm-shrinkwrap.json` and to fail to install dependencies because they don't match `package.json`, so instead the CLI team wants npm to _warn_ when it notices these inconsistencies, probably with a message that indicates that running `npm shrinkwrap` (or `npm install --save` in the presence of a shrinkwrap) will **fail** if what's in `node_modules` doesn't match what's in `package.json`. So in this context, the behavior seen by @tomruggs is actually the expected, desired behavior, although npm should also include in the `extraneous` warning the hint that this can often be cleaned up by running `npm prune` or `npm prune --only=prod`.

How objectionable would this be to everybody? Once we make a call as to whether this is the behavior we want or not, we'll fix up both `npm@2` and `npm@3` to behave identically here.

Thanks to all for their patience, and our apologies for taking so long to get back to this.

**Comment by jpbufe3** [comment]
@othiym23 I'm not sure I understand why you're saying the behavior seen by @tomruggs would be expected. On a new project, you should ALWAYS be able to run:
```npm install
npm shrinkwrap --dev```
and produce a functional `npm-shrinkwrap.json` file without errors or warnings (on the shrinkwrap portion if the install was successful) regardless of whether or not any underlying dependencies have shrinkwrap files also.

Please let me know if I'm misunderstanding your comments.

**Comment by tomruggs** [comment]
+1 to @jpbufe3 jpbufe3.  And with npm 1 and npm 2 you can not.  Example:

```
git clone git@github.com:tomruggs/a.git
cd a 
npm install 
npm shrinkwrap --dev

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: chai@1.9.2 /Users/truggles/work/git/a/node_modules/b/node_modules/chai
```

I see with npm 3 the "npm install" doesn't install b's dev dependencies at all and subsequently "npm shrinkwrap --dev" succeeds.  This is much better and is what I would expect.

But I also expect that the exact versions in b's shrinkwrap file would respected as the source of truth.  It's fine to me if b's dev dependencies aren't installed.  That makes sense.  But if QA testing was done on b based on its npm-shrinkwrap.json file then that's what I want when using it as a dependency.

**Comment by krotscheck** [comment]
FYI: This impacts the version of npm that's packaged with node4 LTS. Even if this is fixed on the npm@2 branch, you'll continue to have users reporting it until Node4 LTS EOL's in a year.

**Comment by NodeGuy** [comment]
This bug is still in npm 4.0.5 and just caused me an hour of confusion.  I agree with @tomruggs and @jpbufe3.  I was very confused when executing the following commands yielded dozens of `npm ERR! extraneous` errors:

```shell
$ rm -rf node_modules
$ npm install
$ npm shrinkwrap --dev
...
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: abbrev@1.0.9 ...
```

If the packages are extraneous, then why were they installed by `npm install`?  If they were correctly installed by `npm install`, then why are they considered extraneous?

**Comment by sebradloff** [comment]
@NodeGuy I'm running this with npm 3.10.9 and seeing the same thing. All the extraneous errors we're seeing are coming from a single npm package with a published npm-shrinkwrap.json file. Did you find any way to fix this?

**Comment by tomruggs** [comment]
I believe we ended up calling the dev dependencies normal dependencies to get around this.  Terrible workaround but we needed to move on.

**Comment by sebradloff** [comment]
Thanks for your reply @tomruggs. That's unfortunately disappointing.

**Comment by NodeGuy** [comment]
I work around it by running `npm prune && npm shrinkwrap --dev`.

**Comment by shanethmoore** [comment]
@NodeGuy That doesn't always work. npm prune will remove some extraneous packages but it is possible for some to be leftover.

**Comment by krotscheck** [comment]
As a note: We've since switched to `yarn`, as its dependency resolution algorithm is deterministic, and it locks all dependencies by default. Also, the `yarn.lock` file is far, far, far more legible than a shrinkwrap document.

**Comment by NodeGuy** [comment]
> @NodeGuy That doesn't always work. npm prune will remove some extraneous packages but it is possible for some to be leftover.

That's a bummer.

I excitedly switched to Yarn too and then dejectedly came back to shrinkwrap after learning that Yarn offers no assurances to the users of a package, only the developers!  😱

https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf#.w4qyn8azv

**Comment by NodeGuy** [comment]
> @NodeGuy That doesn't always work. npm prune will remove some extraneous packages but it is possible for some to be leftover.

You're right, that just failed for me the first time.  Now I'm going to move the `devDependencies` into `dependencies`.  :-(

**Comment by NodeGuy** [comment]
Nope, that just failed for me as well.  I'm giving up on `shrinkwrap`.

**Comment by GCheung55** [comment]
I'm on npm@3.10.3 and seeing this.
