### ISSUE TITLE
scoped packages clobbering executables of same name

### ISSUE THREAD

**Issue by timoxley** [npm/npm#6418]
Scoped packages allow requiring multiple packages of same name, but any executables still clobber each other i.e. dependency hell.

This "problem" already exists in npm, it will currently happily clobber executables, but this hasn't been a practical issue because the global npm namespace guides packages to unique executable names. This isn't the case with scoped packages as they can share the same name, albeit with a different scope.
This is an issue for both local and global installs.

Perhaps npm should namespace executables like `scope-executable` e.g. `npm-ndm` or npm should suggest a best practice for packages to do so manually.  This seems clunky and verbose though.

An alternative is a package.json field which maps executables to scopes or a list which links bins in a particular order.

scopes encourage use of more generic package names thus it is more likely packages will result in conflicts with executables. npm currently has no mechanism for either notifying the user or resolving those conflicts.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
In the discussion of this issue, there’s a lack of examples of conflicts in practice. This is important because it feels to @iarna and me like this is a solution waiting for a problem to solve, and that problem should occur very rarely. Even in `npm@3`, with its flattened installs, conflicts between binary names are one of the things that can trigger a dependency being installed in a nested way.

I’d be happy to see what’s happening here documented in such a way that the potential footgun (and its workarounds) is made explicit. Also, in the case that this becomes a problem in practice, we can reopen this issue and reassess the problem. Until then, I’m going to close this. Thanks, as always, for the patient and thorough discussion, @timoxley!

**Comment by jrwebdev** [comment]
Just came across this issue after figuring out what was happening with a custom scoped `create-react-app` package I have. Given I already had `create-react-app` installed globally, it ran when I attempted to run `@myscope/create-react-app` via `yarn create`. 

With npm now offering free scopes, and the rise of npx to run commands too, I think this is more of an issue now, so thought I'd give a real world example as it was pretty confusing behaviour.
