### ISSUE TITLE
bump version number to next version-pre immediately after publish

### ISSUE THREAD

**Issue by dylang** [npm/npm#6434]
The currently published version is `2.1.3`. This is also the version in `master` which has had several commits since `2.1.3` was published. This makes it difficult to know which build was used when an error occurs. 

My suggestion is to automatically bump the patch version and adding a pre tag on a successful publish.  This way when some projects are using `npm` from `master`, it will give a better idea in the logs of which version was being used.

**Comment by othiym23** [comment]
The CLI team has let this idea marinate for another couple years, and after thinking it over, we don't think this makes a whole lot of sense.

1. Since we've moved to release branches to manage landing and reviewing changes prior to release / getting the commit history merged onto the immutable master branch, running `npm install -g npm/npm` will get you `npm@next` – no more, no less.
2. If you're actively hacking on a branch of npm for PR (or other) purposes, you should probably be pulling it down via git clone and running `npm link`, in which case it's pretty easy to see the history.
3. `npm@next` is the newest version of npm we'd like anybody who's _not_ actively hacking on npm to be running.

Given all that, complicating the release case for what feels like a pretty tiny edge case (given how the development workflow works now) doesn’t make a lot of sense to me, so I’m going to close this feature request. Thanks for your time and the discussion!
