### ISSUE TITLE
npm support for pre-compiled addons

### ISSUE THREAD

**Issue by sam-github** [npm/npm#6437]
npm/node-gyp always puts compiled addons into `build/Release/name.node`. The name is identical for all platforms, but we don't have multi-platform binaries.

To ship pre-compiled addons, then, requires that they be packaged at a different path, and then required from that path. This works fine...

Except that npm/node-gyp will still try to build the addon, causing a stream of errors, that the user should ignore, but don't always realize they can.

This isn't well thought out, but I wonder if npm could start to support an option to node-gyp, particularly useful on Windows (but we find Linux systems without the node-gyp dependencies installed, also).

I think something like this might work:

- standardize a location for pre-built addons, perhaps: `pre-build/<platform>.node`
- npm, when installing on platform `X`, calls the `install` script if it exists, as it does now
- if there is no script, it looks for `pre-build/X.node` and if it sees it, copies that file to  `build/Release/<name>.node` and does NOT call node-gyp (so python not required)
- otherwise, it does what it does now, calls node-gyp

Probably, this would require npm parsing the binding.gyp file, to see what the targets are, and use the names to see if a precompiled addon exists for that target.

This could be done by a not-npm script provided as a dev dependency, and maybe we will write something for that, but we've seen problems on Linux where install scripts cannot be run. When npm is run as sudo, it drops privs before running scripts, as it should, but occaisonally the user `nobody` doesn't have the rights to write to the current working package directory. We mostly recommend never using sudo with npm, to avoid this. I'm not certain, but I think npm doesn't drop privs before calling node-gyp itself.

More to the point, npm would not have to drop privs to do a simple file copy, so the prebuild mechanism would be robust to privilege problems.

Thoughts? Npm must be running into the flood of support calls from windows users, too.

/cc @othiym23  @piscisaureus @bnoordhuis @rmg

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
Closing in favor of nodejs/issues#151 – this would clearly make life easier for teams that distribute packages that depend on native modules, particularly when those deployments will be on Windows. That said, this is something that extends beyond the scope of npm per se, and it's probably not something that npm itself is going to have the time to tackle anytime soon. I still think the service, as defined by @orangemocha, is a good one. The biggest challenge is figuring out who's responsible for getting it up and running and maintaining, because that is definitely a nontrivial task. Thanks for bringing this up, and thanks for your patience!
