### ISSUE TITLE
very intermittent 0-length tarballs returned to CLI

### ISSUE THREAD

**Issue by othiym23** [npm/npm#6451]
Tracking the times users have gotten shasum failures with the failing shasum having the value `da39a3ee5e6b4b0d3255bfef95601890afd80709` (a 0-length file).

Here are a few to start: 
- #6449
- #6440

**Comment by jacouille** [comment]
que faire?

**Comment by mikaelhg** [comment]
Getting a lot of this on client's CI.

**Comment by yofreke** [comment]
From what I can tell this issue ([and the slew of them this morning](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+da39a3ee5e6b4b0d3255bfef95601890afd80709+) lol) are a result of the registry.npmjs.org being slow or broken or whatever and downloading 0 byte files.

Thinking that a reasonable way to fix this would be to use a registry mirror, i tried running `npm install --registry https://registry.npmjs.com/ on-finished` (on-finished was the package failing for me).

Doing this made me realise that `npm install --registry` was not actually using the supplied registry.
sad :(

    npm sill mapToRegistry name on-finished
    npm sill mapToRegistry using default registry
    npm sill mapToRegistry registry https://registry.npmjs.com/
    npm sill mapToRegistry uri https://registry.npmjs.com/on-finished
    npm verb addRemoteTarball http://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz not in flight; adding
    npm verb addRemoteTarball [ 'http://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz',
    npm verb addRemoteTarball   '20f1336481b083cd75337992a16971aa2d906947' ]

Changing lines [193-202 of add-named.js](https://github.com/npm/npm/blame/f18241032f7306ca9bf238c0eb909f65ae4ee58c/lib/cache/add-named.js#L193-L202) to be as follows:

    rp.path = tb.path
    rp.pathname = tb.pathname
    tb = url.format(rp)

Fixed the `npm install --registry` option, allowing me to use an alternate (presumably less visited, since i don't think the --registry option has worked since that blame in October) registry.  Using the less loaded registry fixed the problem of 0 byte files.
