### ISSUE TITLE
multiple git+ssh urls sharing the same repository on different branches/tags

### ISSUE THREAD

**Issue by loadpi** [npm/npm#6469]
We have 1 local git repo containing all our node bits and bobs
since I upgraded to 2.1.4, 'npm install' installs the first one and ignores the subsequent urls that differ
only in the # parts (branches and tags)

```
"dependencies" : {
    "bar": "git+ssh://git@fork.knife.com:anode.git#bar",
    "whipsky": "git+ssh://git@fork.knife.com:anode.git#whipsky"
    "beer": "git+ssh://git@fork.knife.com:anode.git#beer-0.7"
}
```

so I end up only with bar and no whipsky or beer in node_modules
ie unmet dependencies on 'npm ls'

'npm install -d'
after installing the first one politely says:
npm info ok 
and stops

shout if I must do some more digging or testing my side.

**Comment by loadpi** [comment]
The ubuntu ppa for nodejs has upped their npm which basically means we have to build 2.1.2 from source to get our multi branch single repo to install. 
Can you please point me in the right direction on the diff between 2.1.2 and 2.1.3 to see if I can figure out what changed and help patching it?
In the meantime I'll look into creating a test of sorts.

**Comment by othiym23** [comment]
Since all the npm releases are tagged, getting [the diff](https://github.com/npm/npm/compare/v2.1.2...v2.1.3) is pretty simple. There's nothing obvious that jumps out at me, but we did move a bunch of the logic around figuring out what kind of dependency has been passed from the command line into a separate module, and it's possible that the way we integrated that did something weird to how git branches are cached.

**Comment by michaeleekk** [comment]
I'm facing the same issue now. I wonder if there're any ways to work in latest npm?

**Comment by michaeleekk** [comment]
I got another way to workaround this issue, by making the dependencies look like,
```
"dependencies" : {
    "bar": "git+ssh://git@fork.knife.com:anode.git#bar",
    "whipsky": "git+https://git@fork.knife.com:anode.git#whipsky"
    "beer": "git+http://git@fork.knife.com:anode.git#beer-0.7"
}
```
This seems work for the moment, but it will be better if there's a better way.

**Comment by grahamjenson** [comment]
This problem still exists, and now it happens across projects, i.e. two projects, installing two different branches install the same branch.

my work around is to execute 

`npm install -g npm@2.7.3`

then it works for me again

**Comment by othiym23** [comment]
I believe that this has been fixed in both the latest versions of `npm@2` and `npm@3` and am closing accordingly. We've made a bunch of fixes to how hosted git dependencies are cached over the last year (and apologize for the delay in getting back to this issue), and making sure that different branches get different caches were definitely part of that work at least once. If we still don't have this right, either reopen this issue or leave a note here, and we'll reopen it. Thanks for all the details, and for your patience!
