### ISSUE TITLE
npm search probably doesn't need to output every package

### ISSUE THREAD

**Issue by geek** [npm/npm#6477]
If you run `npm search` you get every single package.  Is this necessary to output?

**Comment by smikes** [comment]
This is marked `patch-welcome` but it's not clear what would be an appropriate output.  The top 40 packages? Someone's favorite packages?  A confirmation? (`Really list all 128,499 packages [y/N]? `)

At present `npm-kludge-search` lists no packages if you provide no search criteria.  However, I can still trigger this (pathological?) behavior with `npm-kludge-search '' -r fast | wc`, which takes 70s to write 16MB; output to the terminal or using the default `-r slow` reporter would probably be even slower.

This is partly a problem because `npm search` (and by default, `npm-kludge-search`) use a reporter that wants to analyze the entire set of search results before it writes out the first line (`columnify`).

**Comment by timoxley** [comment]
@smikes So I've thought about setting up columnify to be streaming, but without analysis of the full dataset it's limited its ability to do appropriate resizing of columns. 

Maybe could mitigate this by analysing the first N lines (100?) to gauge appropriate widths then simply use cell wrapping from then on. Now I think about it though, for larger datasets all the widths are likely going to hit the maximum anyway so this is actually a non-problem.

**Comment by smikes** [comment]
Certainly a fallback mode where after 100 rows, it chooses the max widths and does streaming output would be very handy in terms of limiting memory use while doing output.

`npm-kludge-search -r json gulp` uses about 18M for live objects, while `npm-kludge-search gulp` (which uses columnify in the classic way) uses about 36M; both emit a total of 1385 lines.

**Comment by timoxley** [comment]
Is it constantly using ~2x the memory?

**Comment by smikes** [comment]
Similar results with `grunt`.  Note that it's not `columnify` that's taking up the memory, it's the way I'm using it; I collect all the result values into an array before I call `columnify`, and this makes the GC a sad panda.

**Comment by geek** [comment]
In the latest version `npm search` fails without an argument, closing this issue.
