### ISSUE TITLE
npm list is extremely slow

### ISSUE THREAD

**Issue by marcinant** [npm/npm#6507]
List command is very slow. It takes a huge amount of time to query a list of packages to verify if they are installed.

```
time npm -g -json list bower

real    0m1.393s
user    0m1.655s
sys 0m0.159s
```

**Comment by cyberkatze** [comment]
1) after `npm install -g` create `npm-packages-list.json` with full tree
2) after update, recreate  `npm-packages-list.json` with full tree
3) "npm list" wotk only with  `npm-packages-list.json` and return depth if necessary
I think it will be more quickly as now...

**Comment by othiym23** [comment]
@iarna and I just discussed this issue – in order to list a module, the CLI still needs to read all of the packages installed under the prefix. This has always been the case, due to the way that Node.js's module resolution algorithm works, but it's especially true under `npm@<3`, because of the maximally flat install structure that it defaults to. This is a concern because to improve the performance of this would require semi-significant architectural changes (caching the state of the tree doesn't strike me as a super great idea given the way that other programs, like Node installers, mutate that tree without any awareness of that kind of cache file). So, while the CLI team would certainly like to see this snappier, and would be delighted to receive patches that help here, it's probable that making this piece of npm faster will require some significant changes to packages like `read-package-tree` and `read-package-json`. Please do give it a shot if you've got the time and inclination, though! And thanks for your time and patience!

**Comment by legodude17** [comment]
Something that would be much eiseir to implement is something like `npm ls --fast`, which would just scan `package.json` and top level `node_modules`, and then list what packages you have installed, and which ones are missing.

**Comment by helio-frota** [comment]
related:
https://github.com/npm/npm/issues/12402#issuecomment-268045600

**Comment by MattMS** [comment]
Running `npm ls -g --depth=0` with Node 7.3 on Windows 10.

Total Seconds: 9.3807216

**Comment by fabiospampinato** [comment]
I think the `--depth=0` case should be optimized, it's shamefully slow.
