### ISSUE TITLE
Support new separate non-singular npm object with distinct set of cli configs

### ISSUE THREAD

**Issue by jsoref** [npm/npm#6526]

**Comment by othiym23** [comment]
I’m going to close this feature request, because in `npm@3` we removed support for external use of the API that the CLI consumes internally. This is for the simple reason that it’s kind of terrible, and because of the exact kinds of state entanglement issues you describe in this feature request. Eventually, the CLI team would very much like for the CLI’s internal architecture to have exactly the kind of configuration setup you describe, where multiple components can be invoked within a single process, getting only the config they need to do their job.

However, as I mentioned above, this is a major rework of the internals of the CLI, and until the team (or a _very_ enterprising contributor) have the time to break apart the current configuration from the code doing the work, the workaround I also describe above is the best way to get the results you describe. Thanks for your time!
