### ISSUE TITLE
npm update does not honor shrinkwrap file

### ISSUE THREAD

**Issue by hueniverse** [npm/npm#6566]
Calling `npm install` and `npm update` produces different versions of dependencies.

**Comment by smikes** [comment]
I created a PR that implements part of this functionality.  Rather than going the full way with having `npm update --save` ignore and then re-generate the shrinkwrap file, I just added code to make all `npm update` operations fail with an error message if `npm-shrinkwrap.json` is present in the package directory.

Comments and suggestions are very welcome, either here or on the PR, #7423

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by iarna** [comment]
This indeed was done with 3.x! And `npm@3` is `npm@latest` these days. =)
