### ISSUE TITLE
Workflow for forking Node modules and managing their references

### ISSUE THREAD

**Issue by OliverJAsh** [npm/npm#6574]
I'm thinking of ways to improve the workflow around the forking of Node modules. With the current tooling, it is still quite tedious to do:

1. Fork the repo of the package (A)
2. Push your changes to a branch on the fork
3. Open a pull request
4. Whilst waiting for feedback, you want to use your changes in another package (B), so you update the reference in your `package.json` to use your branch on your fork of A, e.g. `"A": "OliverJAsh/A#patch-1"`. For proper version management, you should use the commit SHA, e.g. `"A": "OliverJAsh/A#abcdefgh"`
5. You receive feedback and make more changes on the same branch. You want to update B to use the latest changes to A, so you grab the commit SHA and update the reference in B’s `package.json`.
6. Repeat step 5 until the branch is merged (if ever)

This gets more complicated if you have multiple pending pull requests with different head branches. If you have 2 or more branches you want to [temporarily] use for a dependency in your package, you have to create an additional branch and merge each of these branches in.

These are steps I repeat a lot and it gets quite tiresome. I have one idea of how to improve this, but would love to discuss other ideas if people have them:

`npm install :user/:repo#:branch --save-sha` could resolve the branch name to its corresponding commit SHA. Every time you make a change to the branch, all you need to do to get the latest changes and update your `package.json` is run this single command (instead of manually fetching the commit SHA, manually updating `package.json`, and then running `npm install`).

Any other ideas (or existing tools/commands I am not aware of)?

**Comment by othiym23** [comment]
This request led to a pretty wide-ranging discussion within the CLI team just now about how best to handle the situation where people want to support floating patches or forks of packages when using the CLI. The summary is that the particular workflow you’ve outlined here is more complex and specific to your particular use case for the CLI to take on the additional complexity of supporting it. The way you’ve suggested implementing the functionality makes it seem simple, but the actual implementation would be pretty tricky, given the way the CLI stores references to committishes and treeishes within the installed tree, cache, and `package.json`s.

That said, we do understand the goal, which as we understand it is a way to reduce the work of maintaining floating patches for changed versions of packages. In a sense, this would be trying to get npm to replicate a bunch of behavior that GitHub has already implemented, and it’s tough to think of a way to do that that doesn’t involve using a bunch of assumptions about how Git works that are rooted in GitHub’s particular workflow. Because the CLI tries to be reasonably generic about how it works with Git, this is an obstacle, but if somebody was to write a command-line tool to manage this flow (a la [`quilt`](https://en.wikipedia.org/wiki/Quilt_(software)), but specialized for npm), it would be super useful. Given the time constraints on the CLI team, it’s unlikely to be us. (This is similar to how [`linklocal`](http://npm.im/linklocal) has simplified working with interdependent packages under simultaneous development – something else you might want to look at. In `linklocal`’s case, the functionality has proven to be sufficiently useful to enough npm users that we’d like to integrate it into the CLI directly).

Because the CLI team isn’t going to ship this functionality in the CLI, I’m going to close this issue. Thanks for your time, and the discussion!
