### ISSUE TITLE
warn when both --save and --save-dev are set on install / update

### ISSUE THREAD

**Issue by faiq** [npm/npm#6591]
I was investigating another issue with npm, when I noticed that setting the config for `npm save` and `npm save-dev` don't play nicely. `save-dev` ends up taking priority over save. I'm not sure if this is desired behavior.

here are the commands that I ran

`npm init`
```
$ npm config list
; cli configs
registry = "https://registry.npmjs.org/"
user-agent = "npm/2.1.6 node/v0.10.32 darwin x64"

; userconfig /Users/Faiq/.npmrc
email = "faiqrazarizvi@gmail.com"
loglevel = "http"
spin = false

; node bin location = /usr/local/bin/node
; cwd = /Users/Faiq/Documents/fuck
; HOME = /Users/Faiq
; 'npm config ls -l' to show all defaults.
```

`npm config set save true`

`$ npm config set save-dev true`

```
$ npm config list
; cli configs
registry = "https://registry.npmjs.org/"
user-agent = "npm/2.1.6 node/v0.10.32 darwin x64"

; userconfig /Users/Faiq/.npmrc
email = "faiqrazarizvi@gmail.com"
loglevel = "http"
save = true
save-dev = true
spin = false

; node bin location = /usr/local/bin/node
; cwd = /Users/Faiq/Documents/fuck
; HOME = /Users/Faiq
; 'npm config ls -l' to show all defaults.
```

`npm i tape@1.0`

`npm i request@1.0`

`package.json`

```
{
  "name": "lol",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "request": "^1.0.0",
    "tape": "^1.0.4"
  }
}
```

Maybe there should be a flag that warns you that `-save` isn't going to work?

**Comment by othiym23** [comment]
The CLI team discussed this again today, and we decided that no, there’s never a good reason to have `save-dev = true` in your configuration, and yes, the CLI should warn you when you’ve passed both `--save` and `--save-dev` to install or upgrade, because there’s no reasonable expectation we can assume users to have about what npm should do when both are set. Better just to error! I've retitled the issue to reflect this.

That said, the team isn’t going to have time to get to this in the next 6-12 months, and so we’re going to close this feature request. It would be great to get this warning or error added via a patch, though. Thanks for your time and explanation, @faiq! Also hi!
