### ISSUE TITLE
package.json `files` or `.npmignore` only for production

### ISSUE THREAD

**Issue by zanona** [npm/npm#6609]
Hey guys,
I was wondering if is it somehow possible to currently only include the `files` attribute under `package.json` when it is installed for production?

For example, if my structure is:

```
my-module
├── gulpfile.js
├── index.js
├── lib
│   ├── helpers.js
│   └── other.js
├── node_modules
│   └── …
└── package.json
```

Supposing on my `package.json` file I have

```json
{
    "files": ["my-module-amd.js"],
    "scripts": { "prepublish": "gulp build-amd"}
}
```

which means when running `npm install my-module` I would only get the following structure, which is great:

```
.
├── my-module-amd.js
└── package.json
```

However, I was thinking what if I want to install `my-module` with the `--dev` flag so I can develop further.
How would it be possible to get all the original files as per the first file tree shown?

**Comment by othiym23** [comment]
In practice, people generally want the packages they use (either during development, or in production) to be as small as possible for the package to work as specified. This speeds up installs, reduces the bandwidth used by npm, and generally keeps things tidier. The emerging consensus seems to be settling on using `"files"` in `package.json` to whitelist the files to be included in the package tarball, as it's much simpler than using `.npmignore` and `.gitignore` to blacklist the files to be excluded.

There are those of us in the npm ecosystem (like me) who like to have all of a package's files available at install time, because it simplifies hacking and troubleshooting . Unfortunately, as people use npm for more and more (and more and more complicated) things, npm consumers are looking for whatever performance improvements they can find, and for use cases like containerization, unpacking and writing large numbers of files are the biggest time sink for installation / deployment. So we're kind of in the minority.

I think @KenanY sums up the most practical way to handle this when he suggests
> So, you want to npm install something and then debug and test it? You should git clone its repo then, right?

You can also use `npm repo <packagename>` to find the repo path to a package and `npm install github-org/github-repo` (for now; this loophole will close as the CLI's handling of hosted Git packages is fixed to match registry-hosted packages) to get a more complete copy of the dependency. If you want to know you're working with a hackable version of the source, `git clone repo`, `cd repo && npm link`, and `cd ../path/to/working/tree && npm link package` should do that for you.

This is a sort of longwinded way of saying that the registry is only going to store one version of published packages, and that version be whatever the developer decided to publish. If you want to get the dev version of the package, this is what you'll need to do. As there's nothing for the CLI team to do in this feature request, I'm going to close it, but I hope this was helpful. Thanks for your time!
