### ISSUE TITLE
Error getting fetching morgan and connect registries

### ISSUE THREAD

**Issue by Sukesh-Alluri** [npm/npm#6648]
Log:
```
npm WARN package.json kibana-server@1.0.0 No repository field.
npm WARN package.json kibana-server@1.0.0 No README data
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/forever
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/connect
npm http 200 https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm http 200 https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/serve-static/-/serve-static-1.7.1.tgz
npm http 200 https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm http 200 https://registry.npmjs.org/forever
npm http 200 https://registry.npmjs.org/connect
npm http 200 https://registry.npmjs.org/serve-static/-/serve-static-1.7.1.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-3.3.2.tgz
npm ERR! Error: EIO, close
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-279.2.1.el6.x86_64
npm ERR! command "/tools/node.js/0.10.26/Linux_x86_64/bin/node" "/tools/node.js/0.10.26/Linux_x86_64/bin/npm" "install"
npm ERR! cwd <Use_Path>
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code EIO
npm ERR! errno 55
npm http 200 https://registry.npmjs.org/connect/-/connect-3.3.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/connect/-/connect-3.3.2.tgz
npm http GET https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm http 200 https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/morgan/-/morgan-1.4.1.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-3.3.2.tgz
npm http 200 https://registry.npmjs.org/connect/-/connect-3.3.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/connect/-/connect-3.3.2.tgz
```

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.3. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by tkissing** [comment]
Not the OP, but I am still getting regular EIO errors on our CI system (Bamboo 

error	15-Jan-2015 18:37:57	npm ERR! Linux 2.6.18-371.3.1.el5PAE
error	15-Jan-2015 18:37:57	npm ERR! argv "node" "/usr/local/bin/npm" "install"
error	15-Jan-2015 18:37:57	npm ERR! node v0.10.33
error	15-Jan-2015 18:37:57	npm ERR! npm  v2.1.7
error	15-Jan-2015 18:37:57	npm ERR! code EIO
error	15-Jan-2015 18:37:57	npm ERR! errno 55
error	15-Jan-2015 18:37:57	
error	15-Jan-2015 18:37:57	npm ERR! EIO, read
error	15-Jan-2015 18:37:57	npm ERR! 
error	15-Jan-2015 18:37:57	npm ERR! If you need help, you may report this error at:
error	15-Jan-2015 18:37:57	npm ERR!     <http://github.com/npm/npm/issues>

I get this on at least 50% of my builds, but never on a re-run, which smells like race-condition to me. Something like

	file.create(path);
	file.read(path);

instead of 

	file.create(path, function() {
		file.read(path);
	}

But that's just a guess of course.

**Comment by othiym23** [comment]
@tkissing I'd check to make sure that your CI system's filesystems don't have some kind of bus contention issue. `EIO` is not an error that npm generates itself – it comes out of Node, and generally from somewhere deep inside libuv, rather than being an application error. It's possible that some kind of heavy load induced by npm causes problems with the underlying disks / I/O subsystem, but if you search the npm code base, you'll see that there is literally no case in which `EIO` comes from npm or any of its bundled dependencies.

**Comment by othiym23** [comment]
Closing as resolved.
