### ISSUE TITLE
How to execute different scripts for local / global install for LSB init integration?

### ISSUE THREAD

**Issue by cookiengineer** [npm/npm#6651]
Is there a possibility to determine a global installation using the scripts section in the package.json file?

In my case, I want to auto-deploy a cdn + daemon + lsb init scripts, so they need the installation path of the current environment. For that there's a different behaviour if the package is installed globally or locally (due to available binaries and development vs. live expected behaviour).

In best case scenario, I want to have something like this (or similar):

    {
      "scripts": {
        "install": "node ./tool/configure.js --npm-args=\"$@\""
      }
    }

As previously mentioned, the install script will deploy the LSB init scripts, the startup.conf file or the systemd integration - dependent on the currently executed OS.

My question is now:

a) Is there a way to determine a global install flag (mode) inside the javascript file?
b) If not, how can I pass through the flags of the npm process itself?

~Cheers

**Comment by othiym23** [comment]
If you check the presence of `npm_config_global` from within your deployment / postinstall script, you absolutely will be able to tell whether the install is local or global, and then the script can decide what to do accordingly. This is orthogonal from whether npm is run as root. Since this is behavior that the CLI already supports, as far as I understand your use case, I'm relabeling this as a support issue, and closing it as resolved. Thanks for your time!
