### ISSUE TITLE
shell autocompletion slow

### ISSUE THREAD

**Issue by timoxley** [npm/npm#6671]
IIRC shell autocompletion will hit the remote npm registry for various things, this should probably not happen.

**Comment by chenglou** [comment]
:+1: I use https://github.com/hchbaw/auto-fu.zsh and it insta autocomplete stuff for me (basically presses `tab` automatically at each keypress). Every command beside `npm` is fast.

**Comment by timoxley** [comment]
> If it's not hitting the registry, what is the role of completion?
Maybe it could query local cache.

> Does it make sense to have it at all?
As  blocks the terminal for 5 seconds+ to autocomplete it's more of a bug than a feature.

Though trying with 2.2.0 and I don't seem to get any successful autocompletion anyway, just multiple seconds of a frozen terminal.

**Comment by othiym23** [comment]
@timoxley `npm install` package-name completion (as well as anything else that depended on `http://registry.npmjs.org/-/short`: `bugs`, `docs`, `repo`, `star`, and `view` / `info`) broke when npm/npm-registry-couchapp@e1f643460d4c3ed9d49c5958c3ca7caa7c745b83 was deployed sometime last March. We'll probably need to tackle package-name completion at the same time we handle command-line search, because we'll probably want to reuse search's completion engine for this -- doing it with Couch was slaughtering the CouchDB instances).

My apologies to everyone for not acknowledging that sooner -- I had to do some spelunking to figure out what was going on there.

**Comment by moander** [comment]
Every call to npm is slow. I'm not familiar with auto-complete, but I guess it runs npm on each tab-event?

```
$ time npm >/dev/null

real  0m0.308s
user  0m0.273s
sys   0m0.039s
```

The delay is considerable compared to the 150ms extra time it takes to install a package:
```
$ time npm install q >/dev/null

real  0m0.451s
user  0m0.412s
sys   0m0.057s
```

```
$ time npm version
{ npm: '2.14.3',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.0',
  openssl: '1.0.2d',
  uv: '1.7.4',
  v8: '4.5.103.33',
  zlib: '1.2.8' }

real  0m0.326s
user  0m0.292s
sys   0m0.042s
```

Same results as above using v2.11.3 / node 0.12.7:
```
$ time npm version
{ npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

real  0m0.307s
user  0m0.272s
sys   0m0.042s
```


Hardware:
2.8GHz Quad-core Intel Core i7, Turbo Boost up to 4.0GHz
16GB 1600MHz DDR3L SDRAM
1TB PCIe-based Flash Storage

```
$ uname -v
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; 
root:xnu-2782.40.9~1/RELEASE_X86_64

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)

$ time node -e 'console.log("test")' >/dev/null

real  0m0.083s
user  0m0.067s
sys   0m0.014s
```

**Comment by apjanke** [comment]
Initializing the completion itself, is rather slow too. This is on my recent SSD MacBook Pro; other users are reporting 1-5 seconds (per robbyrussell/oh-my-zsh#3392).

```
$ time npm completion >/dev/null
npm completion > /dev/null  0.43s user 0.05s system 98% cpu 0.490 total
```

If you do a `source <(npm completion)` in your `~/.zshrc` or `~/.bashrc`, then every interactive shell session is going pay that startup lag. That's pretty bad.

I can see where certain individual completions require remote access, but is that needed for just setting up the completion functions?

Just sticking `npm completion >> ~/.zshrc` is a rough solution, too. Then you have the completions for one particular `npm` version baked into your shell startup file, which may be shared between multiple machines and environments.

As a heavy `zsh`/`bash` user, just having static completion definition files that could be located under the `npm` installation, or a fast `npm completion`, would make this more usable.

**Comment by rosshadden** [comment]
:+1: to everything @apjanke said.  Sourcing the npm completion is adding `.5s` to the startup of my shell.

**Comment by apjanke** [comment]
Here's a trick for tracking down completion performance issues in the future.

Set `PS4=$'+ %D{%s.%6.} %N:%i> '`. Then do `set -x`, and try doing an completion. It'll dump a timestamped trace of its activity to the terminal. Copy that out, munge it a bit, stick it in a spreadsheet and diff the timestamps, and you've got elapsed execution times for each statement. Do `set +x` to turn the tracing back off when you're done.

**Comment by othiym23** [comment]
Regarding the original feature / bug, we "solved” this problem by removing package-name completion from the CLI altogether. As has been said in numerous places in numerous contexts, features that were convenient and sensible with a few hundred packages don’t make sense with hundreds of thousands of packages. While we could use the autocompletion used by npm search (which is separate from the actual search that generates search results pages, either on the web site or the CLI) here, it’s still going to be kinda pokey, because the network is involved (and also because the size of the result sets returned is liable to be pretty hefty, given how many packages there are now). As such, I’m going to consider this issue resolved.

If people have issues with other aspects of the CLI’s completion’s performance, filing separate issues and pull requests to address the individual pieces is likely to get much quicker traction than trying to put everything on one big rollup issue. Thanks to all for their time and discussion!
