### ISSUE TITLE
Windows: Global installing a local module doesn't provide an appropriate .cmd file for bin scripts

### ISSUE THREAD

**Issue by dschnare** [npm/npm#6674]
I've recently tried installing a local module I was working on via `npm link` but my bin scripts don't have an appropriate .cmd file created for them. Here's the .cmd file created:

````
"%~dp0\node_modules\newsletter-builder\bin"   %*
````

Here's what installing from the NPM repository yields when installing bower:

````
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\bower\bin\bower" %*
) ELSE (
  node  "%~dp0\node_modules\bower\bin\bower" %*
)
````

Obviously when I attempt to run my command it just don't work. I have to manually edit the .cmd file to look like that created for bower, substituting the path for my JavaScript file.

**NOTE:** This seems to also affect calling `npm install pkg` for a local folder.

**Comment by jinjor** [comment]
Does your script file contain `#!/usr/bin/env node` at the top?
I don't know what does this actually mean. But when I encountered the similar problem, that solved it.

**Comment by basarat** [comment]
I know it sounds irrational. But adding usr/bin/env  does indeed solve it

**Comment by basarat** [comment]
# Workaround

See https://github.com/Microsoft/TypeScript/blob/master/bin/tsc for an example. Basically have a dummy file without the `.js` extension and just require the actual `.js` file. Also point the `bin` in `package.json` to this dummy file. 

In file named `tsc`: 

```
#!/usr/bin/env node
require('./tsc.js')
```

**Comment by erandros** [comment]
I confirm that the workaround provided by basarat works. Thanks. Oh, and thanks for grunt-ts btw.

**Comment by marvinroger** [comment]
@basarat This is not irrational at all. npm uses [cmd-shim](https://github.com/ForbesLindesay/cmd-shim) to create the .cmd and cygwin files. The fact is [it explicitely checks](https://github.com/ForbesLindesay/cmd-shim/blob/acf5e31069a43eb27cefb01fdb8c89995e190a19/index.js#L65) for a shebang. If it's present, it assumes it is a file that needs to be interpreted, so it creates the `@IF EXIST` wrapper that calls the appropriate program, in our case node. If it's not, it assumes deservedly this is a compiled file that can be called directly. The point of this is that you are able to ship with your package an .exe file: if it was called in the context of node, the executable file would not execute.

So your workaround is not really a workaround, it is the way it's supposed to work. I would also add that you don't have to have a file without `.js` extension that calls the main `.js`: you only have to add the `#!/usr/bin/env node` to your binary `.js` and it works.

So this is not really a bug then. The issue is that it's, as far as I am aware of, documented nowhere. I had to dig into the code to find out that!

**Comment by basarat** [comment]
> So your workaround is not really a workaround, it is the way it's supposed to work. I would also add that you don't have to have a file without .js extension that calls the main .js: you only have to add the #!/usr/bin/env node to your binary .js and it works.

cool. But in case one doesn't want the shebang in the .js file they can still use what I recommended :rose: 

That said TypeScript now supports shebang https://github.com/Microsoft/TypeScript/pull/4120 :rose:

**Comment by othiym23** [comment]
I think `cmd-shim`'s behavior here is reasonable, after reading through this whole thread. Remember that package scripts are meant to be written in a way such that they can be used with both Windows and non-Windows systems. For this to work, they really do need the shebang to work properly on Unix, which is what `cmd-shim` looks for to figure out what kind of shim it needs to generate. If you believe this behavior is in error, I think the right way to get it changed is to update `cmd-shim`, and then npm can pull that in as an updated dependency and get the new behavior that way. Thanks for everyone talking this through, and I'm sorry it took us so long to get around to looking at this so closely.
