### ISSUE TITLE
npm init: git remote

### ISSUE THREAD

**Issue by yorkie** [npm/npm#6718]
Just a suggestion for my personal reason:

the `npm init` progress will read git repo url, and then run `git remote` for users, it should be an improvement **UX** for my personal use. of course `git init` should be required by user.

/cc @othiym23

**Comment by smikes** [comment]
It turns out there's already a package that does this:

https://github.com/finnp/create-module

via @maxogden's excellent list of resources: https://github.com/maxogden/maintenance-modules#maintenance-modules

Can this issue now be closed?

Thanks!

**Comment by othiym23** [comment]
@smikes 
> Can this issue now be closed?

I'm not so sure, because

> What i expected is two things in details when running `npm init`:
> 1. if the repo remote(`origin`) has been set, we should directly use it.
> 2. if not yet set, it's new, we should help user running `git remote add origin {repo url}`.

I think 1 is something that's in keeping with the other things `npm init` does. 2 not so much, because that strikes me as more automatic than most developers would expect (translation: than I would expect) and thus could be confusing. It shouldn't error if Git isn't available, and it should just use that to populate the default value for that prompt unless `npm init -y` / `npm init --force` is used.

If somebody wanted to take a stab at a patch adding this, I'd work with them to get it landed.

**Comment by smikes** [comment]
I think 1. Is already implemented cf above:

> npm does offer the git origin as the default for repository URL

**Comment by othiym23** [comment]
Ah, so it is. Thanks for bringing that to my attention, @smikes! I'm going to close this, then, for the reasons I stated above. Sorry, @yorkie, it might be convenient for you, but I think it's important to keep a clean separation of responsibility between tools (it feels kind of weird to me that `npm version` creates a commit for you, and there's also a lot of fairly fragile logic around that -- I don't really see npm doing a lot more of that kind of thing in the future).

**Comment by yorkie** [comment]
Thanks for your patience, @othiym23, and I just do submit a suggestion for this tool and now agree on you, it's unnecessary :)
