### ISSUE TITLE
Error: addLocal could not install - windows 7

### ISSUE THREAD

**Issue by cathy-yun-fu** [npm/npm#6721]
Hi,

I cloned a registry onto my computer and I'm in it's parent folder and I typed
```
npm install -g .\git-it' and I get error:

npm ERR! addLocal Could not install .git-it
npm ERR! Error: ENOENT, stat 'D:\_CData\Users\Cathy\Documents\GitHub\.git-it'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" ".git-it"
npm ERR! cwd D:\_CData\Users\***\Documents\GitHub
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path D:\_CData\Users\****\Documents\GitHub\.git-it
npm ERR! code ENOENT
npm ERR! errno 34
```

I've also tried other commands such as:
```
npm install -g ./git-it
npm install -g git-it
```

from the same parent folder.

**Comment by smikes** [comment]
Is this still a problem for you?

By the way, there have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by Akki09** [comment]
npm install -g git-it worked
