### ISSUE TITLE
Divine package.json details from .bowerrc

### ISSUE THREAD

**Issue by DavidSouther** [npm/npm#6724]
Some Front-end libraries are only published via bower. I'd like to install them via NPM (and yes, I am fully aware of the potential versioning issues, etc, and am prepared to handle those). The only thing preventing me is the lack of published package.json, which for most dependency usages is duplicated with the .bowerrc (`name`, `dependencies`). While it certainly doesn't solve the problems discussed in the [recent blog post](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging), it could be a very useful technique to try package.json first, then .bowerrc, then components.json before failing.

**Comment by othiym23** [comment]
The CLI team would like npm to end up in a place where it solves the same problems as Bower, but we’re not interested in making the two interoperable. There are some key features that differ between the two, and some of those, like custom resolvers, include functionality that would be an awkward fit for npm (they add a lot of complexity and add to the cognitive load of understanding where dependencies are being drawn from).

Also, it’s still pretty early days for npm in figuring out how to properly install front-end code that comes without a manifest. Some of that’s because there are important pieces of the puzzle, like ECMAScript Modules, that are still coming together. Some is because the third-party tooling is still in flux, and the challenge for npm as a project is to figure out the minimum subset of that functionality that we need to implement in order to avoid disrupting people’s existing workflows. It’s likely that we’ll eventually implement something sorta, kinda, like what you’re describing here, but it probably won’t be anything as straightforward as a Bower adaptor.

Since this feature request was filed, much has changed. There’s no [`napa`](https://npm.im/napa) as a lighter-weight tool for installing packages lacking `package.json` files with npm (which works as a package script plugin, but also stores its configuration in the local app’s `package.json`). Also, with the advent of Angular 2, Angular and its plugin ecosystem are all available directly from npm. So, while we’re going to close this feature request as something that we don’t intend to implement in this form, there are some other tools that you can use to solve this problem. Thanks for your time!
