### ISSUE TITLE
when scoped modules are published, the --registry flag is not respected

### ISSUE THREAD

**Issue by bcoe** [npm/npm#6746]
When scoped modules are published, the `--registry` flag is not respected if there's an entry for the scope in `.npmrc`.

https://gist.github.com/bcoe/09bfb133e63036a647ef

**Comment by geek** [comment]
:+1: have experienced this issue.  `--registry` and `--scope` should take precedence over `.npmrc`

**Comment by othiym23** [comment]
This is going to take some futzing, because inside npm, it's not really clear, always, which config information is coming from which source. When I have time to burn on `next-patch` issues, I'll dig into this.

**Comment by othiym23** [comment]
We're no longer using `next-patch` to prioritize issues, but this is attached to the road map as a footgun (section 4.3).

**Comment by othiym23** [comment]
To do this properly requires abstracting the logic that determines whether a piece of configuration is set "on the command line" (which may or may not include via environment variables) and which is set via configuration files. It's not hard, because all of the config sources are named when the `config-chain` instances are created at CLI startup time. It's just thingy enough that it needs to be done in one place. The team agrees that this is something that should be fixed (in particular because it's important to enterprise customers mapping scopes to private registries), but it's also a bug more than a feature request, so I've removed the `feature-request` label and added a `patch-welcome`. The CLI team may or may not have time to get to this soon. Thanks for bringing this up, and thanks for your patience, Ben!
