### ISSUE TITLE
Would love to have a 'deploy' command to unpack an app in a location

### ISSUE THREAD

**Issue by aredridel** [npm/npm#6773]
We have `npm install -g`, which installs things in the $PATH; we have `npm install`, which installs things into a project; I'd love a way to use npm to download an application from the registry, ready to run, but not necessarily install it in the path, since only one version can be done that way.

Maybe a name is `npm deploy` or `npm unpack` or `npm install --something`

**Comment by dominykas** [comment]
Another idea: have something along the lines of `appDependency` in a regular package, e.g. I'd create a `package.json` with `{ "name": "my-blog", "private": true }` and then `npm install ghost --save-app` (or some alternative, e.g. `npm install ghost --save --config-apps`, which would then provide some hooks for ghost to configure an `npm start`, and also maybe ask/auto-set-up for some config options (in `package.json` or otherwise), maybe even suggest entries for `.gitignore` and also have plugins configurable (via `peerDependencies` or some other means)

Some of this can probably be achieved by using generators, but I think it might require too much maintenance, but ultimately, I see an "app" as just another package - and "my app" is just a "specially configured package with appropriate scripts and plugins set up". Ideally, I'd even be able to re-publish an "extended" version of an app, e.g. `ghost-with-discourse` and make THAT `npm install`able into `some-bigger-app`.

And for the MVP, I just want to be able to easily `npm install`, `npm start` and `npm update` multiple instances of ghost and some other apps without having to write start scripts and configs myself :)

**Comment by othiym23** [comment]
This is an interesting design problem, largely because the problem is trickier than it looks. If an `npm unpack` were added, which merely downloaded the package / app tarball and unpacked it into the current directory, the resulting application would be unusable (because it would be missing its dependencies, probably – the results of `npm pack` are intended to be used as part of a full `npm install` lifecycle). Add an `install` to the mix, and it starts to feel closer to fully-fledged, but it probably needs some additional lifecycle hooks specific to preparing an application for use, or a modification of the publishing code specific to applications meant to be used with this tool. Somewhere along this line of thinking, this falls into an uncanny valley between a significant feature for a package manager, and a lightweight, [Capistrano](http://capistranorb.com/)-like deployment / configuration management tool.

On the other hand, were we to look at the deployment process from a more integrated point of view, it might make sense to provide a small set of features within npm that were meant to be used by a more fully-featured deployment / configuration management tool like [Chef](https://www.chef.io/) or [Ansible](https://www.ansible.com/) (or Capistrano, as far as that goes). The problem _there_ is that it’s difficult to get that set of features right in the abstract; without being able to see the whole shape of the solution, whatever gets built is probably going to fit somewhat awkwardly. So I think we need more information about what people need and what they can live with before we’re able to move forward with this.

As a side note, you can actually get your hands on _just_ the package tarball for any installable package today, using `npm pack <package>`. Literally anything that can be passed to `npm install` – registry-hosted packages, hosted Git repositories, even tarball URLs – will produce a tarball containing that package with `packagename-version.tgz` as its name in the current directory. (This is mostly just a side effect of how the CLI’s caching code works, and is one of those weirdly useful porcelain commands that almost nobody knows about.) Until this problem gets mapped out more thoroughly, this may be a useful tool for some or all of you who come across this issue.
