### ISSUE TITLE
issue in installing npm on linux system

### ISSUE THREAD

**Issue by deepi2003** [npm/npm#6794]
Having issue in installting nodejs npm on linux machine:
Log file pasted here:

```
verbose url resolving [ 'https://registry.npmjs.org/', './karma' ]
21 verbose url resolved https://registry.npmjs.org/karma
22 verbose request where is https://registry.npmjs.org/karma
23 info trying registry request attempt 1 at 20:05:24
24 http GET https://registry.npmjs.org/karma
25 info retry will retry, error on last attempt: Error: getaddrinfo EIO
26 info trying registry request attempt 2 at 20:05:34
27 http GET https://registry.npmjs.org/karma
28 info retry will retry, error on last attempt: Error: getaddrinfo EIO
29 info trying registry request attempt 3 at 20:06:34
30 http GET https://registry.npmjs.org/karma
31 silly lockFile cd7961bb-karma karma@
32 silly lockFile cd7961bb-karma karma@
33 error Error: getaddrinfo EIO
33 error     at errnoException (dns.js:37:11)
33 error     at Object.onanswer [as oncomplete] (dns.js:124:16)
34 error If you need help, you may report this *entire* log,
34 error including the npm and node versions, at:
34 error     <http://github.com/npm/npm/issues>
35 error System Linux 2.6.32-431.5.1.el6.x86_64
36 error command "/opt/perforceWorkspace/deIdentification_cr_dev_deepti/node-v0.10.33-linux-x64/bin/node" "/opt/perforceWorkspace/deIdentification_cr_dev_deepti/node-v0.10.33-linux-x64/bin/npm" "install" "karma"
37 error cwd /opt/perforceWorkspace/deIdentification_cr_dev_deepti/node-v0.10.33-linux-x64/bin
38 error node -v v0.10.33
39 error npm -v 1.4.28
40 error syscall getaddrinfo
41 error code EIO
42 error errno EIO
43 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by deepi2003** [comment]
Its not a problem now

**Comment by aetsher** [comment]
Tq all ....

rf149900

**Comment by othiym23** [comment]
Closing as resolved.
