### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by idosch5** [npm/npm#6800]
Hi, how can I fix this error: 
npm ERR! Error: getaddrinfo ENOTFOUND ?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since November 2014. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by idosch5** [comment]
No, I updated my npm and node versions and changed my proxy configurations
and it works well now.
Thanks a lot.

Ido

2015-01-14 14:40 GMT+02:00 Sam Mikes <notifications@github.com>:

**Comment by othiym23** [comment]
Closing as resolved!
