### ISSUE TITLE
Error handling version ranges on peer dependencies

### ISSUE THREAD

**Issue by zoff** [npm/npm#6802]
Having modules with mixed tilde and caret ranges in peer dependencies, as following example:
```
"peerDependencies": {
    "grunt": "~0.4.0"
},
```
and:
```
"peerDependencies": {
    "grunt": "^0.4.0"
},
```
causes an EPEERINVALID error even if current version of grunt (0.4.5) matches both ranges.

Example to replicate the error with existing modules:
```
npm init
npm install grunt-contrib-requirejs
npm install grunt-bower-requirejs
```

EDIT: This is valid for STABLE VERSION (node v0.10.33, npm v1.4.28)

**Comment by smikes** [comment]
Is this still a problem for you?

I believe that `npm@1.4` did not have complete support for the "^" semver operator.  In any case, the current version of `npm` is now 2.2.0 ; do you still see the problem you reported when you upgrade to the latest?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
