### ISSUE TITLE
Error when trying to npm publish

### ISSUE THREAD

**Issue by VDuda** [npm/npm#6836]
I was previously hitting Error: pound_internal server_error. I don't have the log message for this, but that was the Error. 
I thought it was some npm credential issue; stale connection maybe? So, I rerun my npm login. 

I then try to rerun npm publish. And receive a separate error.

```
npm ERR! Error: forbidden Attempting to modify version 2.0.4,
npm ERR! which was previously published on 2014-11-19T19:46:22.435Z.
npm ERR! This is forbidden, to maintain package integrity.
npm ERR! Please update the version number and try again.: myApp/2.0.4/-tag/latest
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:181:12)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:525:16)
npm ERR!     at Request.emit (events.js:67:17)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/main.js:484:14)
npm ERR!     at IncomingMessage.emit (events.js:88:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:137:23)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /myPath/node-myApp/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.5.0-43-generic
npm ERR! command "node" "/usr/bin/npm" "publish" "."
npm ERR! cwd /myPath/node-myApp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message forbidden Attempting to modify version 2.0.4,
npm ERR! message which was previously published on 2014-11-19T19:46:22.435Z.
npm ERR! message This is forbidden, to maintain package integrity.
npm ERR! message Please update the version number and try again.: myApp/2.0.4/-tag/latest
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /myPath/node-myApp/npm-debug.log
npm not ok
Failed to publish node driver to npm
```

I don't understand the error message. This version isn't published/visible; and I'm certain I never ran unpublish for version 2.0.4

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.1.4. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved (`npm publish` will very rarely work with versions of npm earlier than `npm@1.4`, and will almost always fail with `npm@1.1`, so do please upgrade).
