### ISSUE TITLE
Validate installed packages through a checksum

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#6886]
Add a `npm validate` command to ensure locally installed modules are intact. This with a checksum validation between local node modules and npm.

I had a case earlier where I modified a local module but forgot about that weeks later when my code crashed. Been debugging almost whole night like crazy until I remembered that I have tweaked a local module. `npm validate` could have saved me from that, grins.

I bet `npm validate` would be useful for many use cases.

Totally aware that this is nontrivial and requires careful design. So .... thanks!

PS: this is inspired by this thread https://twitter.com/binarykitchen/status/542279808550313985

**Comment by omeid** [comment]
+1 I am struggling with an error that maybe related to bad connection but it is now impossible to find out whatever a package is broken or something else.

**Comment by e-cloud** [comment]
that could be useful. sometimes installation is interrupted for some reason which causes some broken packages but you don't know which it is/they are.

**Comment by pcj** [comment]
I'm researching this and find it extremely surprising that npm does not do this.  

I would have thought something like `npm install foo --sha256=VALUE` would be an option, to say "I expect the sha256 to be VALUE; fail if it looks like someone is messing with me."  

And then publish a list of known sha256 values, so people can cross-check it.  Without this it leaves the entire node ecosystem unprotected against network attacks.  

Am I missing something obvious?

**Comment by othiym23** [comment]
The more general use case of being able to verify the integrity of the contents of a package, at the individual file level, is something that would be useful, both for the use case outlined by @binarykitchen at the top of this issue, and for trust and provenance-related reasons. That said, this isn't something that's on the roadmap for the CLI within the next 6-12 months, so I'm going to close this particular request. There are related features, like getting content addresses into `npm-shrinkwrap.json`, that we _are_ going to ship, and there are other features, like package signing (and building the supporting PKI or web of trust) that npm as a company may or may not get around to building in the next year or so, that would need to happen before implementing something like this would make the most sense.

> I would have thought something like `npm install foo --sha256=VALUE` would be an option, to say "I expect the sha256 to be VALUE; fail if it looks like someone is messing with me."

npm has included validation of the package tarballs, via their SHA-1 digests, since pretty much the beginning. It's worth pointing out, though, that this is intended as a _verification_ measure to ensure that the package tarball has been correctly downloaded from the registry; it's not meant to protect against substitution attacks. That would, as I mentioned previously, require a significant level of additional infrastructure so that provenance can be attested, and is something that hasn't yet become a priority, for a variety of reasons, some good, some related to there only being a set number of hours in the day.

Anyway, thanks for the discussion, all, and thanks for your time!

**Comment by omeid** [comment]
I don't know how the npm tar verification works but with bad network, I have constantly had issues with corrupted cache or local install that requires nuking `~/.npm` and the local `node_modules`.

For those interested, my initial experience with [Yarn](https://github.com/yarnpkg/yarn) have been much consistent and has significantly improved our build times, not sure how, but it is just much faster.

**Comment by pronebird** [comment]
Was this somehow reviewed? Is it documented how NPM uses checksums if uses them at all?
