### ISSUE TITLE
Error in npm install 

### ISSUE THREAD

**Issue by alvarouribe** [npm/npm#6906]
in `/opt/local/apache2/htdocs/pcrApp` I ran

```
> sudo npm install

npm ERR! Error: ENOENT, open '/opt/local/apache2/htdocs/pcrApp/node_modules/grunt-contrib-connect/node_modules/portscanner/node_modules/async/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /opt/local/apache2/htdocs/pcrApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /opt/local/apache2/htdocs/pcrApp/node_modules/grunt-contrib-connect/node_modules/portscanner/node_modules/async/package.json
npm ERR! code ENOENT
npm ERR! errno 34
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
