### ISSUE TITLE
npm scripts properties can be read as arrays

### ISSUE THREAD

**Issue by keithamus** [npm/npm#6943]
Sometimes when writing npm scripts, they can start to get a little bit unwieldy if you try to string multiple commands together. Take for example this: 

```json
"scripts": {
  "build": "npm run build:scripts -s && npm run build:styles -s && npm run build:markup -s",
  "build:scripts": "browserify -d assets/scripts/main.js -p [minifyify --compressPath . --map main.js.map --output dist/main.js.map] | hashmark -n dist/main.js -s -l 8 -m assets.json 'dist/{name}{hash}{ext}'"
}
```

It'd be real swell if npm could read a scripts value as an array, and just run `.join('')` before executing, which in my humble opinion would improve the readability of scripts immensely:

```json
"scripts": {
  "build": [
    "npm run build:scripts -s",
    "&& npm run build:styles -s",
    "&& npm run build:markup -s"
  ],
  "build:scripts": [
    "browserify -d assets/scripts/main.js -p ",
    "[minifyify --compressPath . --map main.js.map --output dist/main.js.map]",
    " | hashmark -n dist/main.js -s -l 8 -m assets.json 'dist/{name}{hash}{ext}'"
  ]
}
```

**Comment by j-san** [comment]
Maybe a solution for "&&" operator in windows shell ?
:)

**Comment by smikes** [comment]
@j-san That would be interesting - it could be an `npm` module that uses forward polish (instead of infix) notation

```
npm install and
...
"scripts": { "build": "and \"npm run build:scripts -s\" \"npm run build:styles -s\" " }
...
> npm run build
```

**Comment by sindresorhus** [comment]
:+1:

**Comment by Qix-** [comment]
Why introduce another parser do to weird, non-standard command linkage using `and` instead of using JSON how people would expect it? And why not make it an optional thing, similar to how `repository` works? If it's a string, it's one command. If it's an array, it's multiple commands that are run in succession so long as they exit with `0`.

I was actually kind of surprised NPM doesn't do this by default; as discussed in sindresorhus/xo-init#6, `&&` has its downfalls. Further, being dogmatic about it, while realistically `&&` is pretty reliable, it shouldn't be expected to work on every platform, always.

As stated in the aforementioned issue, manipulating the `package.json` data automatically now becomes a hassle because we have to *guess* (never good) the format of the command string; does it contain a `;` at the end? Does it already have some weird postfix operator that will cause unintended side-effects with `&&`?

It's a hack at best, and bad design at worst, in my opinion. Array scripts should be *possible*. Maybe unnecessary a lot of the time, but for those who wish to be 100% compatible, the option should still be there - without some weird, intermediate language, the JSON way.

**Comment by Slayer95** [comment]
+1

**Comment by sindresorhus** [comment]
:+1: It's more and more common to use `npm` as a lightweight task runner. Supporting what @Qix- suggested would improve readability.

Example of where it would be useful: https://github.com/sindresorhus/caprine/blob/master/package.json#L18

**Comment by Qix-** [comment]
I have run into many, many situations where this would be useful since I posted last. Still supporting this.

**Comment by uglow** [comment]
+1

**Comment by sebastiandedeyne** [comment]
+1

**Comment by Anahkiasen** [comment]
:+1: for this

**Comment by frickenate** [comment]
Why concatenate at all? Just run the commands in sequence one at a time. A decision would have to be made whether to check the exit code of each command. If the first command exits non-zero, does it execute the second command?

It is extremely unintuitive that an array does not work. It also doesn't generate an error on executing the script. I just started my first venture into nodejs for angular today, and intuitively used an array expecting it to work. I guess I'll create bash scripts in a bin/ directory to handle multiple commands for the time being.

**Comment by mindplay-dk** [comment]
> If it's an array, it's multiple commands that are run in succession so long as they exit with 0.

This! So much this.

> It is extremely unintuitive that an array does not work.

Yes.

This feature would be so incredibly useful.

I think it's completely intuitive to expect this work.

Another small thing that would make this so mch more useful, is if `./node_modules/.bin` would be temporarily added to search paths while executing the list of commands - so that a command like `./node_modules/.bin/rimraf ./build` could more intutively be just `rimraf ./build`.

If we had this, I would never think twice about using a complicated build tool or custom `build.js` script again - this would be so much simpler and more intuitive :-)

**Comment by Anahkiasen** [comment]
Isn't `node_modules` already added to the PATH in node scripts?

**Comment by Qix-** [comment]
@Anahkiasen `node_modules/.bin` is, yes.

**Comment by ryancole** [comment]
I don't think a string concat on the commands in the script array is a good idea. I think it'd be better to run each command, or item in the script array, as its own command and just piggy back on the already-present code that executes scripts. The reason for this? It'd benefit from all the already-existing logic, such as breaking on a fail return code.

**Comment by Qix-** [comment]
> ... because JSON isn't meant to be edited by humans, it's a serialization format, not a config file format.

What? That's the whole point of JSON - to be readable and edited by humans. That's the reason why we don't use MessagePack or some other serialization standard.

**Comment by mindplay-dk** [comment]
[Composer](https://getcomposer.org/doc/articles/scripts.md) has several good ideas about scripts - there's actually more than one feature I'd like to reference from it.

### 1. Multiple Commands

So this does what you'd expect:

```json
"scripts": {
  "build": [
    "foo",
    "bar",
    "baz"
  ]
}
```

That is, it runs each command on the list, checks the return code after each command and aborts if there's an error.

### 2. Referencing Scripts

As [in Composer](https://getcomposer.org/doc/articles/scripts.md#referencing-scripts), the ability to reference other scripts:

```json
{
  "scripts": {
    "build-ts": ["..."],
    "build-sass": ["..."],
    "build": ["@build-ts", "@build-sass"]
  }
}
```

That is, a command starting with `@` is an anchor referencing another script - this would help tremendously with modularity of build scripts.

### 3. Running `npm` Commands

As [in Composer](https://getcomposer.org/doc/articles/scripts.md#calling-composer-commands), the ability to run an `npm` command:

```json
{
  "scripts": {
    "build": [
      "@npm update my-package",
      "..."
    ]
  }
}
```

That is, `@npm` is a reserved script-name that internally dispatches an `npm` command - the advantage is that another instance of `node` doesn't have to launch for each command, which speeds things up a lot compared to e.g. `"npm run-script foo && npm run-script bar"`, which is what you would do today.

I might want to work on one or more of these features, if a PR would be accepted...

**Comment by othiym23** [comment]
People would really enjoy having this capability, but this is a _huge_ break with the existing functionality, because it would break any version of npm older than the one including this feature. Were npm being built now as a greenfield project, there are a number of tweaks to make to package scripts that I think we'd all like to see happen. However, this feature, along with many others that the CLI team will be getting to in the near future, is pretty much a nonstarter because of the commons we have in place. I think the best way to deal with the need to have more flexibility in package and lifecycle scripts is to use an add-on package like [`scripty`](https://www.npmjs.com/package/scripty) or [`p-s`](https://www.npmjs.com/package/p-s), which are designed specifically to be more flexible task-runners.

Since this is something that, from the CLI team's perspective, is a _massive_ amount of work for incremental gain, I'm going to close this issue. Thanks to all, though, for your time and contributions to the conversation!

**Comment by Qix-** [comment]
> People would really enjoy having this capability, but this is a huge break with the existing functionality,

Wat? How would this break anything? That response is silly. There's not _little incremental gain_, this is the _correct_ way to approach this problem, especially since NPM is naively assuming `&&` works on all platforms and that the shell running the commands supports shellscript.

**Comment by othiym23** [comment]
> Wat? How would this break anything? That response is silly.

Every version of npm currently in existence would have no idea what to do with the new format. That kind of widespread break with backwards compatibility in `package.json` is not something the CLI is going to entertain, now or ever.

> especially since NPM is naively assuming `&&` works on all platforms

1. This is an assumption on the part of the people writing package scripts, not npm.
2. At present, npm is hardcoded to use bash on Unix / macOS, and `cmd.exe` on Windows, both of which support `&&`.

**Comment by Qix-** [comment]
> Every version of npm currently in existence would have no idea what to do with the new format

Ah, true; I cede.

As for the other points, it'd be nice if NPM was at least smarter about things...

**Comment by sbuzonas** [comment]
> Every version of npm currently in existence would have no idea what to do with the new format. That kind of widespread break with backwards compatibility in package.json is not something the CLI team is going to entertain, now or ever.

It isn't a break in backwards compatibility, all previous formats will work with the forward version.  Indeed, new formats will fail to function with previous versions. But how do you justify adding new features if it's a no go that previous versions will not implement them?

Would it break functionality other than that of an end user trying to run a script? Isn't it reasonably acceptable to require a user to update their version of NPM to use a new feature?

**Comment by Qix-** [comment]
Another downside to not having this is that, when your `npm` scripts get too big for a single line, people usually resort to adjunct scripts .

So then you have to support both a shell script `foo` and a batch script `foo.cmd` just to do the same things since NPM can't by itself.

Also, since JSON doesn't support line escapes or multi-line strings, this makes package.json files quite messy and hard to maintain (namely because JSON is an interchange format, not a markup language).

This _should_ have gone out with `npm@5` IMO.

Also, not sure what is being used to run commands from scripts, but why wouldn't the following be sufficient as a bugfix backport for older majors?

```javascript
// instead of...
var command = package.script.start;

// ... use
var command = Array.isArray(package.script.start)
    ? package.script.start.join(' && ')
    : package.script.start.toString();
```

**Comment by mindplay-dk** [comment]
@othiym23 please see the all-thumbs-up reply above by @sbuzonas and consider reopening this issue.

**Comment by christopher-francisco** [comment]
Reopen please, this would be a great feature.

**Comment by ryanburnette** [comment]
I'd love to see this feature added. At first glance, it seems like the script object could use its current logic to handle a string and new logic to handle an array. Maybe there's more to it.

**Comment by aclark73** [comment]
Yes to this feature, but please don't run each line as its own command! 

My script lines are really long not just because I'm running multiple commands, but also because the commands may have an enormous number of arguments. Also, as in the example originally posted, there are any number of connectors you might want to run between commands.

Just join the lines with whitespace, or even nothing at all. Anyone who can write a build script is perfectly capable of stringing together multiple commands. All I want is a way to put newlines in the `package.json` file.

**Comment by mindplay-dk** [comment]
@aclark73 I think most who have commented expect individual lines to run as individual commands? @ryancole really [nailed it](https://github.com/npm/npm/issues/6943#issuecomment-237720143), IMO.
