### ISSUE TITLE
I try to install phonegap but...receive Error: ENOENT

### ISSUE THREAD

**Issue by youphoto** [npm/npm#6966]
I past the ending part of logfile with the errors:
```
33294 error If you need help, you may report this log at:
33294 error     <http://github.com/isaacs/npm/issues>
33294 error or email it to:
33294 error     <npm-@googlegroups.com>
33295 error System Windows_NT 5.1.2600
33296 error command "C:\\Programmi\\nodejs\\\\node.exe" "C:\\Programmi\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
33297 error cwd C:\
33298 error node -v v0.10.15
33299 error npm -v 1.3.5
33300 error path C:\Documents and Settings\raffaele\Dati applicazioni\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js
33301 error fstream_path C:\Documents and Settings\raffaele\Dati applicazioni\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js
33302 error fstream_type File
33303 error fstream_class FileWriter
33304 error code ENOENT
33305 error errno 34
33306 error fstream_stack C:\Programmi\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
33306 error fstream_stack Object.oncomplete (fs.js:107:15)
33307 verbose exit [ 34, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like the symptom of a certain kind of race condition that used to be present in `npm` before version 2.1.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.5; the latest is 2.2.0. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
