### ISSUE TITLE
ENOENT, open '/Users/khoinguyen/Desktop/package.json'

### ISSUE THREAD

**Issue by fitbodylife** [npm/npm#6968]
```
npm ERR! Error: ENOENT, open '/Users/khoinguyen/Desktop/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/khoinguyen/Desktop
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /Users/khoinguyen/Desktop/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/khoinguyen/Desktop/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

As KenanY says, you need to provide a `package.json` in order to use `npm start`, with at least the following contents:

```
{
  "scripts": {
    "start": "<command>"
  }
}
````

Then when you run `npm start` whatever is in the package.json as `<command>` will be run.

Sometimes people who run into this problem are following a tutorial that has set up a `package.json` somewhere that will start a server; you just need to `cd` back into that directory and run `npm start`

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
