### ISSUE TITLE
npm publish login error

### ISSUE THREAD

**Issue by Lellansin** [npm/npm#6988]
F:\Github\node-timeout>npm publish
    npm http PUT https://registry.npmjs.org/node-timeout
    npm http 403 https://registry.npmjs.org/node-timeout
    npm ERR! publish Failed PUT undefined
    npm ERR! Error: login error
    npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:82:22)
    npm ERR!     at CouchLogin.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\couch-login\couch-login.js:191:14)
    npm ERR!     at CouchLogin.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\couch-login\couch-login.js:173:46)
    npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:123:22)
    npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
    npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:893:14)
    npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
    npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:844:12)
    npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
    npm ERR!     at _stream_readable.js:920:16
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/isaacs/npm/issues>

    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
    npm ERR! cwd F:\Github\node-timeout
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.3.24
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     F:\Github\node-timeout\npm-debug.log
    npm ERR! not ok code 0

I noticed that npm.org had change its website, is this the reason?

**Comment by smikes** [comment]
Is this still a problem for you?

Publish errors are often related to stale login credentials.  After you upgrade npm (see below) please do all of the following:

```
go to <npmjs.com/password> ; log in and then change your password
npm c del _auth
npm c del //registry.npmjs.org/:_password
npm login
```

This will ensure that the registry has a modern set of credentials for you (the way registry credentials are stored changed at some point in 2014, but I am fuzzy on the details), and that you are logged in.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.24. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by Lellansin** [comment]
I'v fixed this problem via upgrade npm to last version just now, thanks a lot for your attention! =)
