### ISSUE TITLE
globally installing more than one package using "npm install -g" causes "uid must be an unsigned int"

### ISSUE THREAD

**Issue by k-j-kleist** [npm/npm#6995]
This is Windows 7 / PowerShell 3.0
```
PS C:\projects> npm install -g foundation-cli bower gulp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\local\\nodist-0.4.8\\bin\\\\node.exe" "C:\\local\\nodist-0.4.8\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "foundation-cli" "bower" "gulp"
npm ERR! node v0.11.14
npm ERR! npm  v2.1.14

npm ERR! uid must be an unsigned int
```
However, this works fine:
```
npm install -g foundation-cli
npm install -g bower
npm install -g gulp
```

**Comment by othiym23** [comment]
Oh, hey! This is fixed in `npm@2.3.0` -- we made a bad change to how we interacted with the cache that was causing a lot of people to have issues when they cached something new. `npm@2.3.0` will become the newest stable version of npm on Thursday, but if you want to run it today and confirm that it fixes your issue, install `npm@next`.

Sorry about the mess!

**Comment by smikes** [comment]
To upgrade your `npm` on Windows, do this:

```
cd C:\Program Files (x86)\nodejs
npm install npm@next
```

**Comment by techelephant** [comment]
I can confirm that npm@2.3.0 solved the issue - at least in my case :-) I had the exact same problem as described above, including "npm config get user" returning 0 (zero). Upgrading npm to 2.3.0 (not globally but in the node installation directory) fixed the issue.

Thx othiym23 and smikes...
