### ISSUE TITLE
install restify error

### ISSUE THREAD

**Issue by gentlecolder** [npm/npm#7002]
```
npm err! fetch failed http://registry.npmjs.org/csv-generate/-/csv-generate-0.0.4.tgz
504 gateway time-out
     at  Writestream................./fetch.js:57:12
     at  WriteStream.EventEmitter.emit(events.js:117:20)
     at fs.js:1596:14
     at .......
     at object.oncomplete
```
System linux3.10.0-123.e17.x86_64
command 'npm install -g restify'
cwd /root
node -v v0.10.24
npm -v 1.3.21

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like it might have been a networking issue; are you still seeing this problem?

Next time, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by gentlecolder** [comment]
Thank you for your reply, it's ok now. it may be the problem at my side, cos my network is in mailand in china . and i have been installing again and again, and finally it succeeded without doing any other thing. i will keep pay more attentions on nodejs and the restify,that's one of greatest things in web Development historical processing.





At 2015-01-15 05:19:24, "Sam Mikes" <notifications@github.com> wrote:


Is this still a problem for you?

This looks like it might have been a networking issue; are you still seeing this problem?

Next time, could you please upload your npm-debug.log as a gist http://gist.github.com? If possible, run npm with at least one -d flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm, run npm -g install npm@latest

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. Here are instructions from NodeSource on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

¡ª

**Comment by othiym23** [comment]
Closing as resolved.
