### ISSUE TITLE
Distributing binary with npm package

### ISSUE THREAD

**Issue by jviotti** [npm/npm#7029]
I want to know if it's accepted to distribute a binary along with my globally installed NPM package ([dd for windows](http://www.chrysocome.net/dd) in this case).

The problem arises because I have issues to read/write to a block device directly in windows ([see this SO question](http://stackoverflow.com/questions/27365765/nodejs-unable-to-write-to-windows-8-block-device)), so a temporary solution to my problem would be to ship `dd.exe` with my package and make use of it internally.

Looking forward to hear your thoughts.

**Comment by othiym23** [comment]
I believe @smikes has pretty thoroughly addressed the original issue here, so I'm going to close this out. In general, it's fine to include binaries in npm modules, although you should use discretion and care, because large npm packages are time-consuming to download and install, and thorough testing is necessary to make sure that the resulting package actually supports all of the platforms on which people are likely to use your package.
