### ISSUE TITLE
npm install --save and npm shrinkwrap create references to .tgz file on registry.npmjs.org

### ISSUE THREAD

**Issue by pselden** [npm/npm#7031]
Tried using npm 2.1.14 and 1.4.28.

When I started using --save and shrinkwrap, sometimes the package.json will include a reference to the registry .tgz instead of the semver package name.

```
npm install --save debug keymirror express object-assign

// inside of package.json

  "dependencies": {
    "debug": "https://registry.npmjs.org/debug/-/debug-2.1.0.tgz",
    "express": "^4.10.6",
    "keymirror": "https://registry.npmjs.org/keymirror/-/keymirror-0.1.0.tgz",
    "object-assign": "^2.0.0"
  }

```

Also my shinkwrap has been seemingly randomly deciding to use the semver package or the registry as well. After a recent shrinkwrap I ended up with a diff like this:

```
           "dependencies": {
             "htmlparser2": {
               "version": "3.8.2",
-              "from": "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.2.tgz",
+              "from": "htmlparser2@>=3.1.5 <4.0.0",
               "resolved": "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.2.tgz",
               "dependencies": {
                 "domhandler": {
                   "version": "2.3.0",
-                  "from": "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz",
+                  "from": "domhandler@>=2.3.0 <2.4.0",
                   "resolved": "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz"
                 },
                 "domutils": {
                   "version": "1.5.0",
-                  "from": "https://registry.npmjs.org/domutils/-/domutils-1.5.0.tgz",
+                  "from": "domutils@>=1.5.0 <1.6.0",

```

But in other places in the same shrinkwrap, i got this, where it changes from registry to package name!

```
             "request": {
-              "version": "2.49.0",
-              "from": "https://registry.npmjs.org/request/-/request-2.49.0.tgz",
-              "resolved": "https://registry.npmjs.org/request/-/request-2.49.0.tgz",
+              "version": "2.51.0",
+              "from": "request@>=2.0.0 <3.0.0",
               "dependencies": {
                 "bl": {
                   "version": "0.9.3",
-                  "from": "https://registry.npmjs.org/bl/-/bl-0.9.3.tgz",
+                  "from": "bl@>=0.9.0 <0.10.0",
```

Any idea what's going on here?

**Comment by othiym23** [comment]
Regarding your second comment, that is exactly how shrinkwrap is supposed to function -- the version of the dependency specified in the shrinkwrap file overrides the semver range in `package.json`. The workflow with shrinkwrap files is a little cumbersome right now, in that you can't override or update `npm-shrinkwrap.json` directly from `npm install`, but the behavior is correct.

As far as what happens to the metadata within `npm-shrinkwrap.json`, the `from` field is metadata that tells npm how it resolved the dependency. Given the way the npm installer works, it's going to give different results for different runs, both because as of `npm@2` there's no determinism in how the various bits of the install are ordered, and also because depending on what's in your cache, you may get different results on different shrinkwrap runs. In practice, this isn't an issue, because the field the installer cares about is `resolved`, which means that it _always_ installs dependencies from tarballs. This is the other piece of what shrinkwrap does (aside from freezing dependency versions) -- ensures that you're getting the same bits on disk every time.

**Comment by pselden** [comment]
@othiym23 I'm not sure I fully understand -- are you saying that because I have debug already in my shrinkwrap it will cause --save to put the .tgz file into my package.json "dependencies" instead of the latest version, and that's expected? I understand your point about the shrinkwrap possibly containing the .tgz files, but for it to show up in my package.json is what was unexpected.

**Comment by othiym23** [comment]
Now I'm not sure _I_ understand the problem. When do you end up with a `.tgz` in your `package.json`? That's not in either of the excerpts you included above.

**Comment by pselden** [comment]
Sorry, I was not very clear -- the .tgz reference ends up in my package.json. The shrinkwrap thing is tangential to the issue I was raising (I thought it might be related since .tgz references were in the shrinkwrap as well).

The real issue I was trying to point out was that the reference to the .tgz file ends up in my package.json after "npm install debug --save".

     "debug": "https://registry.npmjs.org/debug/-/debug-2.1.0.tgz"

**Comment by kevinohara80** [comment]
+1

**Comment by F1LT3R** [comment]
+1 also seeing this

**Comment by bcherny** [comment]
@Any updates? It's a little annoying to have to manually update my package.json every time after installing a package. It sort of negates the value of `--save`.

**Comment by TimBeyer** [comment]
I've had this randomly happen to me as well and I don't really understand what causes it.
It definitely doesn't happen on all the packages I install, but on some of them in the same project it happens consistently.

**Comment by erezcohen** [comment]
Strangely the issue you describe happens to me as well with npm 4.6.1.
Doing npm i on a an already existing package creates this reference to http://registry.npmjs.org/ in the package.json file. Uninstalling and then re-installing adds the package without this ref.
