### ISSUE TITLE
Is Xcode required?

### ISSUE THREAD

**Issue by DomT4** [npm/npm#7032]
Apologies for the issue here, I did a Github search, and a StackExchange search, and read through the ` npm ` docs but couldn't find anything obvious.

Does ` npm ` have a requirement on ` Xcode ` at all? Or an expectation for it to exist?

Having a curious issue up at Homebrew, which we haven't seen at all recently, with ` npm ` hanging indefinitely on a CLT-only machine: https://github.com/Homebrew/homebrew/issues/35341

You can see a full build log [here](http://hastebin.com/oyamiduruc). Any thoughts? Cheers.

**Comment by DomT4** [comment]
No worries. It was good to finally get the ` node ` package behaving (mostly) consistently on our end as well. Lot of changes over the past year to the formula for ` node ` but I think we've reached a pretty stable point with the last couple of updates. I'm relatively content. Appreciate it's hard to keep up a line of communication between npm and Homebrew, everyone is rushing around constantly doing something, and it's hard to keep communication with external tools near the top of that list. Always happy to work together where we can though.

The user having the difficulty removed the custom Python tool from their ` $PATH ` and used the system Python, but still to no avail, which somewhat exhausts the one big variable where things could be expected to go wrong, frustratingly. He also reports that no dialogue boxes popped up in regards to ` xcode ` or similar.

Strange error this.

**Comment by smikes** [comment]
> Always happy to work together where we can though.

In light of that, by the way, you may want to think about readying a recipe for <http://iojs.org/> since presumably people will want to download it January 13th.

I guess the next thing I'd suggest in troubleshooting the original problem is seeing if installing XCode helps at all.  I don't understand the acronym `CLT` in `CLT-only`, but it seems to entail not having XCode?

**Comment by DomT4** [comment]
> readying a recipe for http://iojs.org/ since presumably people will want to download it January 13th

Thanks, I've been keeping an eye on that. I confess I don't entirely *get* where it came from, is it something Node blessed, or is it a more hostile fork by folks fed up with Node's development process for x,y,z? Will it be able to exist alongside ` node `? And is the ` npm ` relationship formal or just sharing a common platform?

Appreciate those are pretty heavy questions, so no worries if you don't have time to trawl through the history of the fork. From the website it looks like the first release will be an Alpha build, so it'll need to go in the shiny new [Homebrew/Devel-only](https://github.com/Homebrew/homebrew-devel-only) tap, but as soon as it's officially stable we'll look into supporting it from the core. I've already raised the upcoming release with the maintainers at Homebrew/Homebrew and discussed it a wee bit, so folks are aware of the situation coming at least.

> I don't understand the acronym CLT in CLT-only, but it seems to entail not having XCode?

Apologies. It's an Apple acronym for "Command-Line Tools", which is a separate much smaller, much less complete development package for OS X. It is generally advisable if you're doing any kind of heavy dev work to have both ` Xcode ` and the ` CLT ` package installed, but given Xcode is some 6GB and the CLT package is less than 1GB, it's easy to see why people opt for the latter, heh.

**Comment by smikes** [comment]
io.js is a fork more-or-less-blessed by several of the core node maintainers, with the goal of making up-to-date releases that depend on current versions of the underlying libraries, v8 and uv.

Joyent's business model seems to have evolved beyond spending time/effort/salaries on keeping the official `node` binary up to date with its dependencies; at least that's the impression I get.

`io.js` is based on the node 0.11 release line, moving forward to current versions of `uv` and `v8`.  It will probably need to be installed in parallel with node, until one of them definitely wins, which at this point looks like it will be `io.js`, but of course no-one can be sure.

`npm` is committed to supporting the whole javascript ecosystem, including both `node` and `io.js` until they diverge irreconcilably, or until one dies.  Don't know how long that will be..

It is likely that both `io.js` and `node` will continue to bundle `npm`.  It is also likely that binary modules will be mutually incompatible, but javascript modules will be sometimes mututally compatible.  (luckily for bootstrapping, npm is js-only).

Anyway - it'll be a mess.

**Comment by DomT4** [comment]
Thanks for the detailed reply, Appreciate that. Are those up-to-date dependencies going to continue being shipped by ` io.js ` ala how ` node ` does with deps right now or are package managers going to be asked to play a bigger role in chucking those updated deps in? I'd guess the former, purely because it makes life less prone to variable hell for the ` io.js ` team.

Having the two side-by-side on a system for a while could cause some fun, especially if both use an ` npm ` executable named ` npm `, heh, because there'll suddenly be two ` npm `'s that need to have publicly-available trees in the ` $PATH ` to support ` npm install ` modules, as well the conflicting ` npm ` binary name itself.

I suspect, at least early on, until one wins the race, the ` npm ` shipped with ` io.js ` on our end will probably get prefixed with ` i ` or something, as in ` inpm ` or some other suggestion from the team here or at ` io.js `. Could be enormously fun keeping ` node ` and ` io.js ` from bumping head side-by-side. *Gulps nervously*.

> Anyway - it'll be a mess.

Always :grinning:

**Comment by othiym23** [comment]
> Appreciate that. Are those up-to-date dependencies going to continue being shipped by io.js ala how node does with deps right now or are package managers going to be asked to play a bigger role in chucking those updated deps in?

Yes. Node's build and packaging philosophy has always been to make it as close to a one-binary install as possible, and io.js won't be changing that, as far as I know. It's my assumption / fervent hope that io.js will be more forgiving about which versions of npm it chooses to bundle with the distribution (@rvagg may be able to shed light on this, as he's heading up the build work for io.js). From a downstream packaging consumer's point of view, that should be the primary difference between the two distributions, and that may or may not be relevant to how you set up the formula for Homebrew.

**Comment by smikes** [comment]
I believe that `io.js` will ship an up-to-date `npm` and dependencies.

Personally I am planning to use `nvm` to manage the various versions of `node` and `io.js`, since I am expecting to be helping troubleshoot various installation issues across the board.  @othiym23 already found a fun one, a major regression in `node@0.11.15` and `io.js@1.0.0-prealpha`, here - https://github.com/npm/npm/issues/7043

Just so you get a sense of how fun this is going to be, node 0.12/io.js 1.0 will contain code that was pushed more than a year ago but has not actually been really tested in production anywhere.

**Comment by othiym23** [comment]
> I suspect, at least early on, until one wins the race, the npm shipped with io.js on our end will probably get prefixed with i or something, as in inpm or some other suggestion from the team here or at io.js. Could be enormously fun keeping node and io.js from bumping head side-by-side.

I would gently discourage this. It's the exact same program under the hood, and npm has no official relationship with either project -- we just provide packages they can bundle in the install, following their own muses for how that bundling should be accomplished. As far as I know, they don't make any changes to npm when bundling it, so you've created two binaries from one. At the very least, this is likely to cause some confusion, especially because there are scripts hardcoded to call `npm`.

**Comment by DomT4** [comment]
> I would gently discourage this. It's the exact same program under the hood, and npm has no official relationship with either project -- we just provide packages they can bundle in the install, following their own muses for how that bundling should be accomplished.

Appreciate this entirely. If I can find a way to get it to play nicely alongside each other, I will, but I fear they'll both want to share the ` blah/blah/bin ` prefix for symlinking their executables into, which is perfectly rational and understandable, but will utterly break or start overwriting each other if someone installs two of the same modules in both ` Node ` and ` io.js `, heh. My worry is that someone is bound to install the same two modules in each Node fork, and then both us and you will get drowned in confused complaints.

In truth, I'm not sure how best to handle the forking. It is still a bit of a nightmare to support the two big Python variants side-by-side, and package managers have had years of fun trying to find new ways or better ways to do that.

Theoretically, we could solve the problem by appending or prepending the ` npm ` executable for one install with another letter, and then every subsequent install would need to be renamed as well, which would be, ah, complete anarchy for us all, heh.

The other approach would be to shove ` Node ` and ` io.js ` out of the main ` $PATH ` and into their own little paths, such as ` /usr/local/opt/node/libexec ` and then encourage users to add those paths back into ` /etc/paths ` or similar in the preference they would like to find ` npm ` modules, but this is a tiny and relatively frustrating bandage over a much wider problem.

And then we could go down the route of making ` io.js ` formally conflict with ` node ` so you couldn't install both at once, but that would irritate the hell out of people.

Lastly, I guess, we could ship a recommended dependency for ` io.js ` on ` nvm ` and instruct people to use ` nvm ` to switch between ` node ` and ` io.js ` and presumably, that would allow the same modules to exist in both pieces of software, in relative harmony. Asking people to get to grips with a new tool is always fun though. Shipping ` nvm ` as a recommended dep on our end would seem to be the path of least pain, but given it's not technically a dependency I don't know how Homebrew/Homebrew maintainers will feel about it.

Thoughts on all/any of that?

> Just so you get a sense of how fun this is going to be, node 0.12/io.js 1.0 will contain code that was pushed more than a year ago but has not actually been really tested in production anywhere.

This sounds like it could be quite the ride.

**Comment by smikes** [comment]
> thoughts

This is personal preference stuff, unfortunately.

From my perspective, Joyent's `node` and `io.js` are different incompatible versions of the same interpreter; for the sake of this discussion, I'll call them "node variants".  If only Joyent's `node` is installed, no changes are needed.  If only `io.js` is installed, then unprefixed `node` should be a symlink to it.  If both are installed, then only one should be "active" and `node` should be a symlink to the one which is "active" and `node` should be installed as `nodejs` or `node.js` or some such thing.

So I guess that means I think that Joyent's node should *also* be installed as `nodejs` unconditionally even if io.js is not present.

`npm` is so tightly bundled with the node ecosystem that I think that it should not be possible to have implicit access to the `npm` of the non-"active" variant.  That is, if `io.js` is active, then `$ npm` will invoke the io.js `npm` and in order to get the one from Joyent `node` I would have to run `/usr/local/bin/node /usr/local/lib/node/node_modules/npm/cli.js`

That's my suggestion re how I would handle it if I was managing the recipes for node and io.js; YMMV.

**Comment by smikes** [comment]
Can this issue now be closed?

I don't think we ever resolved the issue of whether `node` modules require a "Full XCode" vs "CLT-only" toolchain.  Is this something that we (or someone else) should document?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we'd like to close this issue.

Thanks!

**Comment by DomT4** [comment]
Yes, Absolutely. Apparently ` Node ` fixed their ` gyp ` element to not require the full Xcode about a year ago, so there's no reason why either Node or ` npm ` should require a full Xcode installation. Why it was failing for a small minority of users I'm still not quite sure, to be honest. We ended up bottling the ` npm ` process as a way to get around any compile-time errors, which is working nicely to date.

**Comment by smikes** [comment]
No problem.  Thanks for the work you do on `brew`.  It's definitely my go-to package manager for everything non-node on OSX. :+1:

**Comment by sajt** [comment]
I removed the `xcodebuild` and now working
