### ISSUE TITLE
Issue on installing -g phonegap 

### ISSUE THREAD

**Issue by myworkforce** [npm/npm#7045]
```
$ sudo npm install -g phonegap
Password:
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
npm ERR! not a package /tmp/npm-44801-NIkukxsB/github.com/component/emitter/archive/1.0.1.tar.gz
 
> ws@0.4.31 install /usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! Error: ENOENT, open '/tmp/npm-44801-NIkukxsB/github.com/component/emitter/archive/1.0.1.tar.gz-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "phonegap"
npm ERR! cwd /Users/shivanshpandey
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/npm-44801-NIkukxsB/github.com/component/emitter/archive/1.0.1.tar.gz-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0
```

I am using mac Please anyone help me on this..

**Comment by smikes** [comment]
So.. are you still having a problem installing `phonegap`?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

**Comment by Leg3nd** [comment]
Hi Smikes, I have a similar issue and have created a gist for my npm-debug.log.

Are you able to help at all? I have an idea of where I'm going wrong but I'm a bit of a newbie to terminal, node.js, npm and hopefully phonegap soon too

https://gist.github.com/Leg3nd/f329735039cc7efa8782

**Comment by smikes** [comment]
@Leg3nd that's a permissions error, you don't have privileges when running as `Andrew` to write to your own `.npm` cache directory.  It looks like you managed to get a root-owned `.npm`.

You can probably fix this with

`sudo chown -R Andrew ~/.npm`

which will return ownership of all those files back to you.

**Comment by Leg3nd** [comment]
Thanks. I ran that and tried to reinstall `<phonegap>` but to no avail.

My fear was that I shouldn't be installing phonegap under `<Andrew>` in the first place. Even though the first item in my path is `</usr/local/bin>` it seems like it's installing under my profile.

I did use the macintosh installer to install node.js so that may be why it's installed there instead of globally?

(although I could be going off on a tangent) appreciate the help though!

**Comment by smikes** [comment]
That's a separate issue -- when you are installing `phonegap` globally, you will wind up writing to `/usr/local/lib/node/node_modules` and you will either need root privileges for that or you will need to change `/usr/local` so that you can write to it without being `root`.

However, the cache directory under `/users/Andrew/.npm` is not where the files will be installed.  That's just where `npm` keeps temporary copies of the package files while it's staging an install.

Try this:

```
sudo -s
npm install -g npm@latest
npm install -g phonegap
exit
```

At that point, you should be able to run `phonegap` on the command line.

**Comment by Leg3nd** [comment]
Thanks for that, I still have errors on installing though.

When testing `<phonegap --version>` I get `<command not found>`

Here's my terminal error:
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
 
> ws@0.4.31 install /usr/local/bin/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /usr/local/bin/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/usr/local/bin/bin/phonegap -> /usr/local/bin/lib/node_modules/phonegap/bin/phonegap.js
phonegap@4.1.2-0.22.11 /usr/local/bin/lib/node_modules/phonegap
├── pluralize@0.0.4
├── colors@0.6.0-1
├── semver@1.1.0
├── minimist@0.1.0
├── qrcode-terminal@0.9.4
├── shelljs@0.1.4
├── phonegap-build@0.9.1 (qrcode-terminal@0.8.0, shelljs@0.0.9, phonegap-build-api@0.3.3, optimist@0.3.7)
├── prompt@0.2.11 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, utile@0.2.1, winston@0.6.2)
├── cordova@4.1.2 (underscore@1.7.0, q@1.0.1, nopt@3.0.1, cordova-lib@4.1.2)
└── connect-phonegap@0.14.5 (home-dir@0.1.2, connect-inject@0.3.2, ip@0.3.1, ncp@0.6.0, findit@2.0.0, request-progress@0.3.1, shelljs@0.2.6, http-proxy@1.8.1, tar@0.1.19, request@2.33.0, gaze@0.4.3, node-static@0.7.0, archiver@0.10.1, localtunnel@1.3.0, useragent@2.0.8, connect@2.12.0, socket.io@1.0.4)

**Comment by smikes** [comment]
try

`/usr/local/bin/phonegap`

If that works then you need to put /usr/local/bin in your PATH, like this (for example)

```
PATH=/usr/local/bin:${PATH}
```

**Comment by Leg3nd** [comment]
OK, 
`</usr/local/bin/phonegap>` 
doesn't exist - No such file or directory

My path is currently:
`</usr/local/bin:/Users/Andrew/.rbenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Andrew/.rvm/bin:/usr/local/share/npm/bin:/Users/Andrew/Library/Android/sdk/tools:/Users/Andrew/Library/Android/sdk/platform-tools>`

I would have thought that because `</usr/local/bin>` is first in my path, I should be on the right direction?

Sorry for the confused questions

**Comment by smikes** [comment]
That's what I get for not reading the log you reported carefully enough.

You wrote (above)

>/usr/local/bin/bin/phonegap -> /usr/local/bin/lib/node_modules/phonegap/bin/phonegap.js

There's two "bin" directories there.  For some reason, your global prefix is `/usr/local/bin` instead of `/usr/local`.

Look at `npm config ls -l` to see if some path is being set to `/usr/local/bin`

In the meantime, try

`/usr/local/bin/bin/phonegap`

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by Leg3nd** [comment]
Hi, I do still have issues but I'm not sure it's specifically an NPM issue so feel free to close it. I'm going to look for some professional help (based in London) to get me up and running but thanks for all your comments in the meantime!

**Comment by othiym23** [comment]
Closing as resolved / abandoned by OP.
