### ISSUE TITLE
A stupid question, should I npm update -g npm ?

### ISSUE THREAD

**Issue by benpptung** [npm/npm#7050]
I do love npm, and I found it is very convenient to install npm via node package on mac, because npm is in it. However, I've noticed that the npm version is 1.4.28 on my mac, and the current version on github is 2.1.18

Should I upgrade my npm though npm command?
I am wondering if I do so, next time when nodejs upgrade, my npm will be downgraded to the npm bundled in nodejs package. Or some funny things happened?

Appreciated if any advice how do you manage your npm on your mac?

**Comment by linclark** [comment]
You'll want to run `npm install npm -g` (or `sudo npm install npm -g` if your permissions haven't been fixed). You want to use the `install` command instead of `update`.

As far as updating Node, it depends on how you update. If you update using the installer from nodejs.org, then it will overwrite it with the older version. If you use something like the [n package](https://www.npmjs.com/package/n) (which I'm not sure is recommended or not), then npm will not be overwritten.

**Comment by benpptung** [comment]
Hi , Thanks a lot for sharing :)
It might be two years ago, when I was new to nodejs. I am using n package to update nodejs. Don't know why, it happened someday that my nodejs didn't work.  I fixed it using the official nodejs package installer. After that, I am afraid of using n package to manage nodejs. I should give it another try again!!
