### ISSUE TITLE
npm installation on cygwin - windows 7- node.0.4.12 environment getting error.

### ISSUE THREAD

**Issue by kumarsivam** [npm/npm#7058]
shiva@shiva-PC ~
$ npm install -g express
-bash: npm: command not found

shiva@shiva-PC ~
$ node --version
v0.4.12

shiva@shiva-PC ~
$ npm --version
-bash: npm: command not found

please help me to install npm

**Comment by KenanY** [comment]
@kumarsivam Node.js v0.4 is, like, **4 years old**. You definitely _need_ to install the latest stable version of Node.js from http://nodejs.org/ before asking for any support on `npm`, not just because `npm` only supports `>= 0.8`, but also because you are literally years behind the rest of the Node.js world.

**Comment by othiym23** [comment]
npm explicitly [does not support cygwin](https://github.com/npm/npm#installing-on-cygwin), in addition to not working with versions of Node older than 0.8.0. If you want to use Node with a Unix-like command-line experience on Windows, take a look at using it with Git Bash or a full install of mingw. Closing as unsupportable.

**Comment by joncard1** [comment]
Thank you for the robust explanation of why you aren't supporting Cygwin, both here and on the linked-to page.
