### ISSUE TITLE
npm fails to install compiled module with karma present.

### ISSUE THREAD

**Issue by badboy** [npm/npm#7062]
The following Gist actually shows the problem:
https://gist.github.com/badboy/648ee78f344f6a87059d

When having both karma-requirejs and bcrypt as dependencies, which karma-requirejs using a load of other dependencies, including atleast one that gets compiled, npm silently fails to also compile the bcrypt module.
It throws no error and does not try to reinstall bcrypt on further `npm install` invocations.
Explicit/manual `npm install bcrypt` or removing the karma dependency fix this.

This bug bit me on automated deployments, where npm seemed to run just fine but the application could not start because of the broken bcrypt module.

I tested this on 3 different Linux machines and also got reply that the same bug is present on OS X.
I could not find a similar reported issue so far

**Comment by faiq** [comment]
Hey what version of `npm` are you on? Can you let us know if the bug still exists when you try running the command on the latest version of npm? You can install it by running the command: 

```npm i -g npm@latest```  (using sudo if your permissions are not set properly) 

cc: @othiym23 because this seems like some sort of strange race condition e

**Comment by badboy** [comment]
Local machine: 

```
[/tmp/1]% node --version; npm --version
v0.10.35
2.1.18
```

Development VM, before upgrade:
```
vagrant@vagrant-ubuntu-trusty-64:/tmp/1$ node --version; npm --version
v0.10.25
1.3.10
```

After upgrade:
```
vagrant@vagrant-ubuntu-trusty-64:~$ node --version; npm --version
v0.10.25
2.1.17
```

Error still present.

**Comment by othiym23** [comment]
My guess is that this is a race condition in the installer, but I don't know for sure. I'll try to dig into this relatively soon, but it may take a little while to resolve, given the trickiness of dealing with races.

**Comment by badboy** [comment]
Any updates by now?

**Comment by othiym23** [comment]
Nope! We are generally pretty conscientious about updating issues when we're dealing with them, so if you don't see any updates, that means we haven't had time to work on the issue. Sorry, but the npm team are all very busy!

**Comment by badboy** [comment]
Hm, looks like this is fixed in npm 2.13.2? Atleast with my above steps, I can't reproduce it right now.

**Comment by othiym23** [comment]
A few things could have happened:

1. We could have somehow fixed the underlying issue.
2. The nature of the interdependencies between `karma-requirejs` and `bcrypt` could have changed in such a way that it no longer triggers the problem.
3. You're just not hitting it, for whatever reason.

The thing about race conditions is that they're almost always nondeterministic. If you're confident that this issue has been addressed, go ahead and close this issue, but if you're in any doubt about it at all, go ahead and leave it open. Race conditions are extremely annoying precisely because they _are_ unpredictable and intermittent, so I take them pretty seriously, and would prefer to either have a reliable repro case to use in a test, or evidence that the underlying problem has actually been fixed.

**Comment by badboy** [comment]
1. Probably 
2. Hard to really track down
3. That may be the case. But before it definitely happened on each and every install across several machines.

As I don't have this problem anymore, I will close this for now.
