### ISSUE TITLE
.npmrc file format has changed ?

### ISSUE THREAD

**Issue by thaiat** [npm/npm#7064]
Hi,

I just upgraded to the latest npm version (2.1.17).
I realized that the form of the `~/.npmrc` file generated after a `npm login` is different.
In particular it does not hold anymore the _auth value.

Is this a documented change ?
How can i give travis the `_auth` key for doing CI publishing on npm ?

Cheers

**Comment by thaiat** [comment]
Also the new format looks like :
```bash
//registry.npmjs.org/:_password=fksdfnSJFN
//registry.npmjs.org/:username=xxx
//registry.npmjs.org/:email=xxx@xxx.com
//registry.npmjs.org/:always-auth=false
```

The weird thing is that `_password` is simply your base64 password...
No sure it is the more secure

**Comment by linclark** [comment]
There does actually seem to be a problem with Travis at the moment. I was testing it and found that with an `.npmrc` I created with an npm in the `2.x` range, it wasn't working. When I created an `.npmrc` with `1.4.28`, travis deploy worked when using the `_auth` key's value.

**Comment by othiym23** [comment]
@linclark This is a problem that @travis-ci has created, and while I could be persuaded that we should document its behavior or put information in a knowledge base article somewhere and then prominently link to it, I believe it's the Travis team's problem to solve. They _invented _the concept of an "npm API key", which is not actually a thing that exists (yet). The `_auth` field in `.npmrc` was never meant to be consumed outside the CLI's internals, which is why its name has a leading underscore. For that reason, I felt free to break up the authentication credentials further when making changes to support bearer-token authorization (which is, in the not-too-distant future, how all users of the npm, Inc. registry will auth themselves to the registry, and which will also break Travis's npm "integration"). Until Travis improves the user experience around this, the instructions @smikes links to are the best way to generate credentials that will work with Travis if you're using `npm@2` or greater.

@smikes's response resolves this issue, so I'm closing it as such. Leading underscores are on those fields for a reason.

**Comment by linclark** [comment]
I agree that we should have the Travis folks update their docs rather than duplicating their docs almost exactly.

It wasn't clear to me from the response whether we've ever told Travis that their docs need that extra line now, so I've emailed their support team to see if I can get that change made.
