### ISSUE TITLE
Error in installing express using npm

### ISSUE THREAD

**Issue by ThilagaRam** [npm/npm#7071]
Request to  help me to resolve the below issue
```
$ npm install express
npm ERR! Error: getaddrinfo EAGAIN
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! cwd D:\Apphonics\WSO2\Assets\Semantic Serach\WSO2_API_Capture
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! syscall getaddrinfo
npm ERR! code EAGAIN
npm ERR! errno EAGAIN
```

**Comment by smikes** [comment]
This looks like it's a problem with your network or proxy settings: `npm` is trying to look up a host name (`getaddrinfo`) and the OS is telling it to try again later (`EAGAIN`).  You may need to tell `npm` about your proxy settings, with a command like:

```
npm config set http_proxy http://proxy.host.name:port
```

Are you able to install any packages at all?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.23. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
