### ISSUE TITLE
Short help (usage) is specified in multiple places, inconsistent

### ISSUE THREAD

**Issue by smikes** [npm/npm#7082]
`npm --help publish` yields

> npm publish &lt;tarball>
> npm publish &lt;folder>
>
> Publishes '.' if no argument supplied

from <https://github.com/npm/npm/blob/master/lib/publish.js#L16>

while the online docs and `npm help publish` give

>npm publish &lt;tarball> [--tag &lt;tag>]
> npm publish &lt;folder> [--tag &lt;tag>]

from <https://github.com/npm/npm/blob/master/doc/cli/npm-publish.md> (interesting github bug: can't link to line number in markdown document.)

There should be a single place where this is specified, so they don't have to be kept in sync.

I propose adding a script to the build process that extracts the `SYNOPSIS` section of the docs into a file containing a json object, and modifying all subcommands to draw their usage information from this json object.

Edited to add - in the process of doing this I would reconcile the current `usage` with the markdown `SYNOPSIS` section.

/bikeshed should be green

/cc  @linclark @othiym23 (others?)

**Comment by linclark** [comment]
I'm not sure whether the difference is in there for a reason, but if not, I do like the idea of consolidating. 

Would it make sense for it to go the other direction... for the module file to be the source of truth? That way, we could take the usage property which is already exported for each and split it on `\n`, then inject it as the synopsis. I think this might be easier to implement, and it would also keep the synopsis closer to the code so it's more obvious that it needs to be updated if code changes.

**Comment by smikes** [comment]
I agree source of truth should be closer to code .. I am surprised that the docs were updated to include the --tag argument but not the usage, I would have expected it to be the other way.

It's easier for me to imagine writing code that parses markdown and generates JSON than the other way, but I have no commitment either way. :cat2:

**Comment by othiym23** [comment]
I agree with @linclark that keeping the source of truth closer to the code is likelier to yield up-to-date usage docs, and I agree with @smikes that coming up with a way to generate that stuff automatically is a lot easier coming from the `.md` files than the other way around. I don't think those two goals are necessarily in conflict, given that lots of things that npm does aren't particularly easy. We should have a (quick) discussion about how the docs-building process works that also involves npm's web site team (@zeke seems to have the most interest in this) so we can come up with something that is relatively painless for everyone to use once we've built it out. Maybe exporting `.usage` on the exported function for each command offering it?

**Comment by smikes** [comment]
While we're bikeshedding, are we going to enforce one-to-one correspondence between subcommand, usage, cli/npm-foo.md ?

I was just poking at the docs-building process (https://github.com/npm/docs.npmjs.com/pull/103); it uses the checked-in markdown files to build docs.npmjs.com pages.  If that continues unchanged, then we either want the markdown files to be the source of truth OR we want to run a script to update the markdown files from the `usage` and then commit them (now we're checking in build artefacts, yuck). 

I'd be most comfortable giving the markdown files a blank SYNOPSIS section; that will cut down on pull requests to update the documentation in "the wrong place"  But I think I am playing into my cognitive biases here because I am only finding more reasons to do it "my way" i.e., with SOT in the markdown.

**Comment by iarna** [comment]
My inclination would be to have cli read from the markdown when they need to share information, rather than the other way around.

**Comment by othiym23** [comment]
@iarna why?

**Comment by iarna** [comment]
To have a single point of documentation that doesn't have any magic template markers in it or anything. Having "part of the explanation here" and "part of it there" seems like a recipe for divergence. But also it just makes it harder to directly edit the documentation.

**Comment by othiym23** [comment]
> While we're bikeshedding, are we going to enforce one-to-one correspondence between subcommand, usage, cli/npm-foo.md ?

For all of the [core commands](https://github.com/npm/npm/blob/master/lib/npm.js#L92-L141), this seems like a good idea. Several of those commands are aliases for other commands (e.g. `start`, `stop`, `restart`, and `test` are shortcuts for `run-script x`), so maybe it makes sense to put a bunch of them together. If we decide to do this, it should be verified by a test, so the test can accommodate and document any exceptions, much as we do for configuration options.

> I was just poking at the docs-building process...

We have control over the build process for docs, so we shouldn't feel constrained by the way it works now. The more moving parts there are, though, the more likely something is to slip out of sync or break.

@smikes
> I am only finding more reasons to do it "my way" i.e., with SOT in the markdown.

@iarna 
> Having "part of the explanation here" and "part of it there" seems like a recipe for divergence. But also it just makes it harder to directly edit the documentation.

These are both solid arguments in favor of putting usage in the Markdown and then pulling it into the CLI in some way. But how?

1. Build a little utility module (or package -- always more room for small packages!) to read and extract the necessary bits of the docs at runtime.
2. At build time, scan the docs and inject the synopses into the source, so it's visible to maintainers when they're in the code.

The first option seems self-evidently superior to me because it creates a single source of truth for documentation, but the second does a better job of at least reminding contributors and other maintainers that there are docs for that functionality that need to be updated. We get a steady stream of PRs that are nothing but people noticing anachronisms, typos, and infelicitous wording in the documentation, and I'd like to see if we can set up a process that minimizes this kind of error. That said, it sounds like the consensus right now is: Everything goes in the Markdown files, and the CLI uses some *handwaves* mechanism to pull the necessary information out.

@linclark How does this grab you? Do you have any suggestions on how to mitigate the documentation liveness problem?

**Comment by linclark** [comment]
My inclination would still be to keep it in the source, close to where changes to code are made, just because that's been so ingrained in my thinking by past projects... but that's not a good reason to choose one way over the other, so I defer to those who will actually have to deal with making these kinds of edits more frequently.

**Comment by smikes** [comment]
The problem (in the past) was not that there were **no** doc updates, but that docs were only updated in one location.  So I feel pretty confident that @othiym23 and @iarna will ensure that PRs update the docs, but we now need to ensure that the docs are not duplicated and spread between files. 

If we make the `.md` files be the authoritative location for documentation, we can add unit tests that assert that (for all subcommands) `npm $SUBCOMMAND --help` outputs something that matches the `SYNOPSIS` section of the md files; that should insure against someone editing the usage text in code in a way that conflicts with the external docs.

**Comment by iarna** [comment]
@othiym23:
> 1. Build a little utility module (or package -- always more room for small packages!) to read and extract the necessary bits of the docs at runtime.

This is what I was imagining.

> 2. At build time, scan the docs and inject the synopses into the source, so it's visible to maintainers when they're in the code.

I don't disagree with this either, and having minimal docs in the source code also helps act as documentation for the source code.

Still, I tend to prefer the former.

@smikes:
> but we now need to ensure that the docs are not duplicated and spread between files.
and
> that should insure against someone editing the usage text in code in a way that conflicts with the external docs.

If we went with 1 this wouldn't be an issue, as the commands wouldn't include any --help output at all.

While we're bike shedding, let me throw out one more thing-- if we were to move to more declarative handling of arguments then we could move toward generating or verifying documentation from the argument declaration.

**Comment by smikes** [comment]
> If we went with 1 this wouldn't be an issue, as the commands wouldn't include any --help output at all.

Sounds good.  I will give this a shot.

>While we're bike shedding, let me throw out one more thing-- if we were to move to more declarative handling of arguments then we could move toward generating or verifying documentation from the argument declaration.

+1000 to this.  One thing that's currently hard to document/communicate/support is that lots of config parameters (and by extension options) affect the various subcommands, but these effects are not documented on the subcommand help or usage pages.

**Comment by linclark** [comment]
Agreed, I like the idea of generating the doc from the argument declaration.

**Comment by othiym23** [comment]
Any change that requires significant changes to command-line argument handling is wrapped in acid-dipped razor wire, as much as I'd like to change it. If some superhero wanted to rework all the config handling to work in a more declarative, per-command argument handling system that coupled documentation to the arguments for each individual command, and was able to do it in a backwards-compatible way, I would worship the ground they walked upon. I'd do it myself, except it would take a very long time and would be almost unspeakably arduous and @seldo would probably kill and / or fire me.

**Comment by smikes** [comment]
OK, sounds like the declarative options feature should get its very own special bikeshed separate from this one.

I will look at extracting the usage from the MD, probably next week.

**Comment by smikes** [comment]
I am starting on the first stage of this work: bringing `--help` usage messages and `SYNOPSIS` sections into synchrony.  The PR is https://github.com/npm/npm/pull/7535 and I have not CC'd anyone into it to limit notification spam, but everyone is welcome to comment.

This work is targeted for `npm@3` or later, and is based against `multi-stage`

**Comment by othiym23** [comment]
Now that #7535 is landed, would it make sense to close this issue and open another one to tackle the transclusion work?

**Comment by smikes** [comment]
Yes.
