### ISSUE TITLE
Tabular output only for npm search.

### ISSUE THREAD

**Issue by rektide** [npm/npm#7090]
`npm search` adds a lot of whitespace to tabularize the results. i'd like to see an $IFS separated, data-formatted output mode for npm search, such that the result doesn't come back table-ized.

This would be a partial workaround to #7089, redirected output being batshit huge, but there's a lot of people who like table-ized output, they just don't like trailing whitespace and haven't macro'ed/haven't mastered banging out `sed --in-place 's/[[:space:]]\+$//'` a couple times a day whenever they want a non-brutalist redirected npm search.

**Comment by othiym23** [comment]
There is very little about `npm search` that _isn't_ brutalist at this point, so this is a pretty tall ask. :smirk: I agree that friendlier search output, whether it's formatted using $IFS or as JSON, would be handy. I think `npm outdated` proffers a good model here -- you can format the output via either `--parseable` or `--json`. Since the output of search is more freely formatted, there would probably need to be some kind of quoting or escaping for `--parseable` to make sure that the description field doesn't get parsed as multiple fields when using `--parseable`.

We have vague plans to tackle search more comprehensively (probably by replacing the current approach, which involves pulling and then parsing a massive JSON object containing metadata for every package on the registry with an online query against npm's search service) sometime in the second quarter of this year. The list of things the team has to do between now and then is very long, and so we probably won't get to this. It would be great if somebody felt like contributing this, though!

**Comment by smikes** [comment]
I am actively working on a better local search via a pure-js full text search engine (since using `sqlite` was vetoed)

**Comment by othiym23** [comment]
@smikes keep in mind that @seldo's preferred approach looking forward is to have all search going through the same search service, and probably deprecating offline search altogether. I'm in strong agreement with him on that; concentrating all our efforts on one search service with a consistent user experience across both the CLI and the web seems like a much better match for a small team with a lot to do than two disparate search mechanisms.

That said, the npm roadmap is looking pretty full, and we probably won't get to this until the second half of this year. So what I'm saying is that if you're having fun hacking on your search index, go nuts, but keep in mind that we do have long-term plans that may supersede it. :elephant:

**Comment by smikes** [comment]
What do you think about a PR that would make `npm search` require confirmation?

E.g.,

```
$ npm search
npm ERR! The `npm search` command is presently slow and broken.
npm ERR! Please use the online search at https://npmjs.org/
npm ERR!
npm ERR! If you want to use `npm search` on the command-line anyway,
npm ERR! you can enable it by setting the 'cli-search' config variable to 'true':
npm ERR!
npm ERR!    npm config set cli-search true
npm ERR!
npm ERR! ETOOSLOWANDBROKEN
```

**Comment by othiym23** [comment]
Short answer: no.

Less short answer: no.

Helpful answer: either we fix it or we nuke it. It may lessen support to document brokenness in-place, but that is an antipattern in mile-tall flaming letters, especially in this case. This probably goes for other sources of brokenness (e.g. `npm -g update`).

**Comment by smikes** [comment]
Currently I have it working with a 12MB archive file that support searches; takes 32s to build and 4s to search.  I believe I can get that down to <0.1s to search for all reasonable searches (name, author, FTS).  Still not interested, even in the short term?

**Comment by othiym23** [comment]
I'm totes interested, I'm just saying don't get too attached to the little critters. Their lives are so short!

**Comment by smikes** [comment]
6MB archive file, 12s to build, 2s to search.

**Comment by othiym23** [comment]
Open a PR and we can continue this discussion there. ;)

**Comment by smikes** [comment]
@rektide Can this issue be closed?

I have already implemented a JSON reporter for <https://github.com/smikes/npm-kludge-search>.  What sort of a tabular reporter were you thinking of?  CSV, perhaps?  Pull requests or issues are very welcome!

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by aredridel** [comment]
server search joins search terms with "or"; command line with "and". Finding things in large ecosystems is painful on the site.

**Comment by othiym23** [comment]
@smikes I think this is a reasonable description of a problem (how search results ought to be presented) that exists independently of any particular implementation, and as such, until we address the underlying problem, this should stay open.

@aredridel Part of the reason I favor pushing everything onto one online search service is the economy of scale afforded by having only one place where we need to get the behavior right. I don't think the expectations of users searching via the web site and the CLI are fundamentally different: both are trying to solve tactical problems or explore the possibilities available to them. I freely acknowledge that search is equally horrible in both cases, but in different ways. I just think we're likely to get to a solution that works much faster if we consolidate efforts rather than dealing with them separately.

**Comment by zkat** [comment]
https://github.com/npm/npm/pull/13746 includes `tab-separated` and `json` output, as well as output streaming. I'll close this once it's merged, which should be soonish.
