### ISSUE TITLE
npm 2.1.18 seems to delete committed node_modules directories (1.4.8 leaves it alone)

### ISSUE THREAD

**Issue by Pomax** [npm/npm#7106]
As test case, I'm using this:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "npm 1 vs 2 testcase",
  "dependencies": {
  	"list.fuzzysearch.js": "git://github.com/brianloveswords/list.fuzzysearch.js#v0.1.0-commonjs"
  }
}
```
The dependency points to a [not-on-npm package](https://github.com/brianloveswords/list.fuzzysearch.js/tree/v0.1.0-commonjs) that has a node_modules directory committed to the repo. Doing a checkout pulls down all the files, and the require() calls that the list.fuzzysearch.js module has succeed without needing a deeper npm install.

Despite this being potentially an antipattern, npm 1.4.8 doesn't touch these files - they came down the wire, so they get to stay. Running an npm install with the newer 2.1.18, the node_modules dir in list.fuzzysearch.js somehow disappears when the code is downloaded.

Where 1.4.8 shows the following dir layout after 'npm install`:

![screenshot 6](https://cloud.githubusercontent.com/assets/177243/5689513/1c29fc24-981b-11e4-9120-34e9e0d5fe10.png)

npm 2.1.18 instead generates this:

![screenshot 7](https://cloud.githubusercontent.com/assets/177243/5689522/3c5ab4fc-981b-11e4-993c-656ac5de7b26.png)

This feels like a bug, in that npm shouldn't be deleting files on checkout (maybe during dedupe or some other explicit cleaning instruction? but not during plain install)

**Comment by isaacs** [comment]
The correct behavior is in npm 2, not npm 1.4.8.

The issue is that github.com/brianloveswords/list.fuzzysearch.js#v0.1.0-commonjs doesn't bundle any dependencies.  And, since it doesn't *have* any dependencies, the result is that none are installed.

**Comment by Pomax** [comment]
they don't need to be installed - the install should grab all the files on that repo, including the commited node_modules. What it then further installs in there is up to npm (no dependencies? nothing to install) but in this case it **deletes** the node_modules dir. That is not "correct behaviour", that's downloading a dir, and then deleting it O_o

**Comment by othiym23** [comment]
When npm pulls in a Git dependency, it packs it up into a tarball that is cached like any other cached package, following all of the same rules that are run when you run `npm publish` on the package. By default, `node_modules` is omitted from published packages. It's entirely correct behavior for npm to not include `node_modules` in packages unless they've been included in `bundledDependencies` or maybe the `files` array.

**Comment by Pomax** [comment]
When did that "by default" change, and is that new behaviour clearly documented somewhere outside of a changelog? Because while probably handy for caching, that's extremely counter intuitive in terms of what people thing npm does, which is "check the local node_modules dir, if there's nothing there, check one dir up", not "pack up for caching, discard files unless told not to, then regenerate dir from cache instead".

There's going to be a fair number of projects at the very least that I know of that are going to break horrendously when 2.* becomes the Node.js-bundled version (We ran into this because Heroku upgraded their npm from 1.4.8 to 2.1.18 and it caused about half a day of "what the fuck is going on, why are our deploys breaking everywhere when on every dev machine we're testing, things just work")

**Comment by othiym23** [comment]
> No one even imagined npm might be causing deploys to break, because it doesn't delete files

And npm still doesn't delete files, although it has changed what it _includes_ to work more consistently across plain `npm publish`es and Git dependencies. npm is a package manager, not a component installer like Bower or Duo. It does more than fetching files somewhere from the network and writing them somewhere on disk - each package has a lifecycle associated with it, and inasmuch as packages are handled consistently regardless of their origins, npm is enforcing a kind of consistency that simplifies things for users and developers.

This change between npm 1 and npm 2 isn't documented anywhere because the behavior you were relying upon was literally undefined. I had no idea that npm used to silently bring unbundled `node_modules` in Git dependencies along for the ride. The fact that it worked the way it did in `npm@< 2` was an accident, and arguably a (useful, it turns out) bug.

> There's going to be a fair number of projects at the very least that I know of that are going to break horrendously when 2.* becomes the Node.js-bundled version

I'm not making light of your deploy issues (and I'm sorry you ran into them, because they sound like a total pain and would have frustrated me as well), but from what I've seen, I don't think this is the case. A fairly large percentage of the npm user base has made the switch over to `npm@2`, which has been out since September, and you're the first person to have issues with this change. We have been consistently urging people to upgrade to the latest version of npm, because `npm@2` has fixes for a vast number of problems in `npm@1`, and now that most of the underlying race conditions are extinguished, we get very few cases of people being adversely affected by the transition from `npm@1` to `npm@2`.

As I mentioned in my last response, ensuring that `npm@2` and `npm@1` handle these dependencies consistently is as simple as adding a `bundledDependencies` to the `package.json` for each package bundled this way. Is there anything else you need to be able to get this fixed in your deploys?

**Comment by Pomax** [comment]
Well, the first to report it, at least. For every bug report, there's bound to be a multitude of people won don't report it =)

It might be worth having this "how npm does its thing" documented, if only so that people can link to the docs and go "what you've done is actually an antipattern, given how npm works, see: ..." with a nice link. Worth doing?

As for fixing the deploys, I guess the only "true" fix is filing issues on all the modules we rely on that make use of this undocumented 1.* behaviour, though having docs to point to when filing issues on each (I'll be pointing to this issue since it covers it fairly comprehensively now until then) would be quite useful.

**Comment by othiym23** [comment]
It's hard to decide where to put this information where the most people will see it, but either `doc/cli/pack.md` or `doc/misc/developers` would be the logical place. It would _definitely_ be worthwhile to have a terse, narrative writeup of what exactly happens when you cache / pack / publish a packages, including the fact that pretty much all kinds of dependencies are forced through the same funnel. If you wanted to start such a thing, I'd work with you (and maybe @linclark would help)  to get it in good enough shape to become a permanent part of the docs.

**Comment by Pomax** [comment]
I wouldn't mind starting that up, but I'll put out there up front that I have, clearly, no knowledge of how npm actually does its thing =)
