### ISSUE TITLE
Allow partial npm-shrinkwrap.json to only force *some* dependencies

### ISSUE THREAD

**Issue by bfred-it** [npm/npm#7108]
## What'd I'm doing

I'm using `npm shrinkwrap` to [update a sub-dependency to a later version](http://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) because of a bug.

My dependency: `gulp-jade-inheritance`
Sub-sub-dependency: `jade`, it should install 1.8.2 instead of 0.34.1 ([made a PR for that too](https://github.com/paulyoung/jade-inheritance/pull/10))

## How I solved it

If I create the shrinkwrap for the project and only leave the updated `gulp-jade-inheritance` tree in `npm-shrinkwrap.json` it works perfectly:
```javascript
{
  "dependencies": {
    // other project dependencies removed from file
    "gulp-jade-inheritance": {
      "version": "0.5.0",
      "from": "gulp-jade-inheritance@^0.5.0",
      "dependencies": {
        "dep1": …,
        "dep2": …,
        "jade-inheritance": {
          "version": "0.1.0",
          "from": "jade-inheritance@^0.1.0",
          "dependencies": {
            "depA": …,
            "depB": …,
            "jade": {
              "version": "1.8.2",
              "from": "jade@~0.34.1"
              // jade dependencies removed from file
            }
          }
        }
      }
    }
  }
}
```

## Feature request

I wish I could omit `dep1`, `dep2`, `depA`, `depB` from the file, because I don't need to shrinkwrap them too. I wish this would work:

```json
{
  "dependencies": {
    "gulp-jade-inheritance": {
      "version": "0.5.0",
      "from": "gulp-jade-inheritance@^0.5.0",
      "dependencies": {
        "jade-inheritance": {
          "version": "0.1.0",
          "from": "jade-inheritance@^0.1.0",
          "dependencies": {
            "jade": {
              "version": "1.8.2",
              "from": "jade@~0.34.1"
            }
          }
        }
      }
    }
  }
}
```

Currently, this file causes `npm i` to install exclusively what's listed in it (so for `gulp-jade-inheritance`, only `jade-inheritance` is installed as the dependency), rather than using its content to _extend_ the current dependency tree.

What do you think?

**Comment by smikes** [comment]
I am fairly confident that such a complicated scheme for overriding one project's dependency will not make it past @othiym23 ; as a work-around you might be able to use something like the following in a post-install script:

```
find node_modules -type d -name jade | xargs rm -fr
npm install jade@1.8.2
```

**Comment by othiym23** [comment]
Let's focus on the problem you're trying to solve: pinning a transitive dependency to work around bugs. That's a common task, and it has a few important characteristics:

1. It should be temporary, in that either the transitive dependency or its dependent should have a bug filed on them and get fixed relatively quickly. If not, it's probably time to fork the dependency or switch to another package that does the same thing.
2. It should never result in a dependency tree with subtrees that are in an inconsistent state with respect to semver.
3. It affects an isolated part of your project.

There are also a couple good ways to work around the problem. One @smikes's method, which is more or less how npm deals with this issue itself when we're in the middle of developing features that require changes to multiple dependencies along with the work in npm itself. One problem with this approach is that it adds manual steps if you want to deploy the application with this style of manual override. Not impossible, but definitely more difficult.

Another is to `cd` all the way down to the `node_modules` in which the dependency is located and override it there directly, and when you're done, shrinkwrap the entire application. This is deployable, and the shrinkwrap can be regenerated when needed if you want to refresh other dependencies. This would be my preferred solution, especially because it will prevent you from breaking the semver contracts of the dependencies (if you want to do that, you should carefully test everything, and then maybe locally update dependencies in transitive `package.json` files, and also maybe check your customized `node_modules` hierarchy into version control directly.

So that's the problem, some of its salient aspects, and a couple workarounds. I would argue that the workarounds are good enough. `npm shrinkwrap`'s specific purpose is to lock down the state of an application, so you can deploy the same bits you had on disk while you were developing when you put the application into production. It doesn't really make sense for a deployment tool to be used in a piecemeal way -- `npm shrinkwrap` is and should remain applicable at a global level. I hope this doesn't seem too unreasonable!

**Comment by bfred-it** [comment]
I already did what you suggested, though, I shrinkwrapped the entire application… and then removed parts of the shrinkwrap to make the change _isolated_ as per point 3.

> 1. it should be temporary

It's a sub-sub-dependency: I'm not going to fork 3 projects just to change a package.json. Plus, if I did, my project won't benefit from possible updates in those forks (unless I start maintaining them).

The main dependency works well and the alternatives don't, I can't change it nor build another one.

Definitely your solution (shrinkwrap) or @smikes' are better then what's suggested above as they have the _possible_ benefit of being temporary (the author comes around and clicks "pull" and I remove the shrinkwrap), while the above are definitive.

> 2. It should never result in a dependency tree with subtrees that are in an inconsistent state with respect to semver.

Both your solution and @smikes' change the dependency tree, so either I didn't understand what you said or you're contradicting yourself.

> 3. It affects an isolated part of your project.

Exactly! @smikes' does indeed affect an isolated part of the project but shrinkwrapping the entire application does not. 

My partial shrinkwrap (which already works) does exactly that: it affects only the **one dependency**'s tree, not all of the dependencies.

My suggested addition would allow me to affect an even smaller part of the project by leaving out the sub-dependencies `dep1`, `dep2`, `depA`, `depB`.

---

To be clear, I'm not asking to have `npm shrinkwrap` to generate the minimal json I posted above, but to have `npm install` allow me to omit those sub-dependencies in the json. Really, `npm i` is already allowing me to omit the project's dependencies but not the project's sub-dependencies.

**Comment by kennethlynne** [comment]
+1

**Comment by iarna** [comment]
npm@3 actually does allow this.

**Comment by bfred-it** [comment]
I'm not on npm3 yet but that's good to know :)

**Comment by alfaproject** [comment]
@iarna how come? o:

**Comment by iarna** [comment]
@alfaproject I don't follow?

**Comment by alfaproject** [comment]
@iarna how exactly do I override a sub-sub-dependency on npm3?

**Comment by iarna** [comment]
@alfaproject Literally what was described in the feature request at the opening of this issue, under `Feature request` should work.

**Comment by alfaproject** [comment]
Oh alright, was hoping for a more clean solution. ):
Guess I'll just fork anyway.

**Comment by copygirl** [comment]
The shrinkwrap behavior has apparently changed with NPM 4, and `npm install` (once again?) installs **only** the packages in `npm-shrinkwrap.json`. Is there a replacement for forcing one package to use a specific version of another package it depends on?

**Comment by henrahmagix** [comment]
I had to fork multiple repos to accomplish what I hoped to do with shrinkwrap: https://github.com/sasstools/sass-lint/issues/1084#issuecomment-320698184

Please can we return the ability to alter the dependency tree? It would be so, so useful

**Comment by elektronik2k5** [comment]
This is a very useful feature. So useful in fact, that Yarn has it: https://yarnpkg.com/en/docs/selective-version-resolutions. Are there any plans to implement this in npm?
