### ISSUE TITLE
naive question, torrent as a storage backend for npm packages ? 

### ISSUE THREAD

**Issue by maboiteaspam** [npm/npm#7113]
Hi,

For a while i ve been wondering if it does not exist a npm manager relaying on torrent technology to expose and share package content.
so far i have not found aything else than torrent implementation in nodejs /whch is great, btw/.

I m leaving in china, and it s kind of difficult to use npm there. Even with the local initiaitive like cnpm i m having problems.

On the other hand i see the torrent are always working.

Have any thoughts i'd be pleased to read about them.

Bye

**Comment by KenanY** [comment]
I know that [npmd](https://github.com/dominictarr/npmd) wants to go fully p2p eventually (https://github.com/dominictarr/npmd/issues/47).

**Comment by smikes** [comment]
I think the answer to this question is "no".  `npm` does not currently support any kind of distributed/p2p backend.

It is possible to selectively mirror/aggressively cache the npm repository, using a variety of tools such as  `npmd` or https://github.com/rlidwka/sinopia.

/cc @othiym23 comments?

**Comment by othiym23** [comment]
No, npm doesn't have any plans to do this itself. We've chosen a different scalability strategy than p2p or federation; we pay a decent amount of money for a geodistributed CDN backed by a set of CouchDB instances using Couch's fabulous replication to stay in sync. This is relatively simple operationally, which is good, because it allows us as a team to concentrate on shipping new features rather than spending most of our time troubleshooting our distribution system.

We also offer a pretty good (if I do say so myself) private registry product, and have gradually been adding features that otherwise support private registries.

I'm sorry to hear that even cnpmjs and the other registry mirrors within China aren't working well for you. We don't have very good visibility into the Chinese Node community from here, and as I'm sure you know it's hard for outsiders to do things directly to fix inconsistencies in access to our own resources. For a bunch of reasons, many of them political, I don't think that BitTorrent is necessarily going to solve the distribution problem in China longer-term, but I'm always interested in hearing suggestions on how we can improve the quality of the npm experience in China.

I think it's great that @dominictarr, @feross, and others are playing around with making it possible to build a p2p layer on top of the npm registry, and we've got some feature requests in our backlog that would make it easier for people to use technologies like webtorrents to replicate directly from our registry network. But it's extremely unlikely that we're ever going to make that switch ourselves.

**Comment by dominictarr** [comment]
@maboiteaspam it would be quite hard to build a backwards compatible p2p layer on top of npm,
but I have done a lot of research about how to build database/replication/security systems that could be suitable for package managers (as well as other applications)

have a look at this project https://github.com/ssbc/

Bit torrent wouldn't actually be that useful for an npm, since most packages are actually very small (only a few kb) and also torrents have no way to manage the mutable side of npm - updates to package metadata. This is the main problem that secure-scuttlebutt addresses.

**Comment by maboiteaspam** [comment]
Thank you all @othiym23 i really was no critizising the setup you ve all realized. Sorry if you ve feel attacked.

@dominictarr Thank you ! Yes i see your point. How about we only use bittorrent to detect certain type of node on the network, that would for example, expose a service like sinopia.
Building a network of wild nodes with fast http support, in fact, direct entire download.
Does replication require a unique master ? Or could any one be the master of anyone else ?
I don t know much yet about how the replication system works.
I ll check all your repos very soon, thanks !

Thanks everyone !

**Comment by maboiteaspam** [comment]
holy.... ssbc/phoenix seems to be exactly kind of things i m looking for months now.

**Comment by othiym23** [comment]
@maboiteaspam no worries! I just wanted to make clear why we have the architecture we do, and make clear that we do understand the difficulties Chinese npm users face (and that we're interested in helping!).

**Comment by dominictarr** [comment]
@maboiteaspam if you would like to learn more, I'd recommend hanging out in #scuttlebutt on irc.freenode.net and reading and posting issues on the ssbc repos

**Comment by aaronshaf** [comment]
Would love to see this reconsidered someday. Imagine:

{
  "dependencies": {
    "foo": "ipfs://...",
    "bar": "dat://..."
  }
}

Completely host-agnostic.

See:

- https://datproject.org/
- https://ipfs.io/
