### ISSUE TITLE
If you change a `package.json`'s `version` property during `prepublish` npm ignores those changes

### ISSUE THREAD

**Issue by matthew-andrews** [npm/npm#7118]
Example `package.json` file:-
```json
{
  "name": "npm-test-in-time-version-test",
  "version": "0.0.0",
  "scripts": {
    "prepublish": "echo '{\"name\": \"npm-test-in-time-version-test\", \"version\": \"1.0.0\"}' > package.json"
  }
}
```

Steps to reproduce:-
```sh
git clone git@github.com:matthew-andrews/npm-test-in-time-version-test.git
cd npm-test-in-time-version-test
// edit package.json to change the name to a package that does not already exist*
npm publish
```

Expected:-
```
+ npm-test-in-time-version-test@1.0.0
```

Actual:-
```
> npm-test-in-time-version-test@0.0.0 prepublish /Users/mandrews/sandboxes/npm-bug-test
> echo '{"name": "npm-test-in-time-version-test", "version": "1.0.0"}' > package.json

npm ERR! publish Failed PUT 403
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/opt/boxen/nodenv/versions/v0.10/bin/npm" "publish"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.14
npm ERR! code E403

npm ERR! forbidden Attempting to modify version 0.0.0,
npm ERR! which was previously published on 2015-01-12T21:57:04.822Z.
npm ERR! This is forbidden, to maintain package integrity.
npm ERR! Please update the version number and try again.: npm-test-in-time-version-test
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mandrews/sandboxes/npm-bug-test/npm-debug.log
```

\* and therefore you have permission to publish

**Comment by matthew-andrews** [comment]
[output log updated, original one was incorrect]

**Comment by othiym23** [comment]
Although you don't explicitly say so, it seems that your expectation is that you can bump the version of a package as part of the publish step. This isn't an unreasonable expectation on its face, but it's not something that npm supports. I can go into the implementation details if you want me to, but first thing that happens when you publish a package is that npm reads its `package.json`, and then uses that metadata for the rest of the publish process. This is why your example script doesn't work -- the version may be changed on disk, but npm has already loaded the package metadata.

This is an implementation detail, but there are a lot of solid reasons why it's best to consider the operational details of most npm commands a black box. We need the freedom to rework this stuff when we make changes to npm's architecture, reading package metadata more than once is a great recipe for introducing subtle race conditions, and so on.

Fortunately, your particular problem is easy to solve:

```json
{
  "name": "sample",
  "version": "0.0.0",
  "scripts": {
    "publish-patch": "npm version patch && npm run push",
    "publish-minor": "npm version minor && npm run push",
    "publish-major": "npm version major && npm run push",
    "push": "git push origin master --follow-tags && npm publish",
    "prepublish": "echo \"do whatever\""
  }
}
```

Also, if you're feeling frisky, you can automate a lot of this stuff with a `Makefile` (which is what npm does itself).

**Comment by matthew-andrews** [comment]
Thanks for your explanation and considering my request.

**Comment by boennemann** [comment]
Hello @othiym23,

thanks for your explanation.
Do you think that it's technically possible (in a reasonable way) to make the publish command reload package.json/version and to make it complain about a missing version field only after prepublish ran?
If so, do you see any side effects or other things why we couldn't change that?

I'm asking because I have a pretty good use-case for this, but I don't want to start dreaming/reasoning about this, if it might not be possible in the first place.

Your example scripts are pretty nifty, but they don't fit my use-case.

Thank you very much :heartpulse: 
Stephan
