### ISSUE TITLE
Should unpublish be allowed?

### ISSUE THREAD

**Issue by mattdesl** [npm/npm#7122]
I was under the impression unpublishing from the *registry* was not allowed, but I just did a test and `--force unpublish` removed my code entirely from npm. Shouldn't this be in line with [`--force publish`](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f), so that unpublishing will tombstone the version and flag a warning when a user tries to install it (`WARN: blah@x.y.z has been unpublished`), but still allow them to use the version as per usual? 

Of course, the reasoning for this would be to avoid [software and modules breaking](https://www.kickstarter.com/projects/2066438441/haunts-the-manse-macabre/posts/373466) over time -- e.g. a couple years down the road, after the module author has given up programming in order to seek a higher purpose in a remote Buddhist temple, or deep in the Canadian wilderness.

**Comment by isaacs** [comment]
You cannot publish the same name and version combo ever again.  I'm sorry for the inconvenience there.  It causes too much production headaches with the many caches and workers and syncs and feeds happening all over the place.  `name@version` should be considered a unique key.

If you unpublish -f, then the code goes away.  To do otherwise would be a violation of the contract.  But those versions *still* can't be re-used.  Anyone can come along and publish *new* versions with that name.

**Comment by mattdesl** [comment]
I understand the benefits of restricting force publish and was hoping the same would be applied to *un*publish. Why is it a violation of contract?

An example of this happening in practice is angular-bootstrap which unpublished all versions, breaking a lot of builds for a long time. If for example something like xtend was ever to be unpublished from npm, it would have disastrous consequences on dozens of modules and applications.

**Comment by mattdesl** [comment]
Yesterday I had this issue bite me pretty hard. A project I had been working on was no longer possible to install on any computer because a module, [esprima-six](https://www.npmjs.com/package/esprima-six), was deleted from the registry. 

Various modules, mostly older versions, had come to depend on it, such as [astw@0.1.0](https://www.npmjs.com/package/astw) and [sleuth@0.0.0](https://www.npmjs.com/package/sleuth), an older version of `glslify`, an dozens of modules and projects that in turn depended on that, and so forth. Suddenly, all of these modules, and any that depended on them, are unusable. A small list of affected packages:

```
shader-school
gl-line-plot
gl-scatter-plot
gl-axes
three-shader-fxaa
gl-vignette-background
```

It frightens me to think that such a small and unknown module, with probably only a couple of direct dependents, could cause such a disaster across so many projects and modules. I can't imagine what would happen if a more popular module such as `xtend` or `chalk` was removed from the registry. Almost every decent sized project in existence would suddenly fail to install, since all of them would probably have that module in one form or another somewhere across its dependency tree.

It might seem like this will never happen, or that it happens rarely, but the sheer fact that its *possible* with a single command is what concerns me. It is a command that has the potential to bring npm and its ecosystem to its knees. Ideally, packages should *not* be able to be removed from the ecosystem at all.

Related:
https://github.com/stackgl/shader-school/issues/145

**Comment by cheapsteak** [comment]
Had the same problem reopening an old project to do a very simple edit. 

Problem was the module it was depending on `gulp-svgo` no longer existed and I had to deal with this completely unrelated issue before I could get to work.

Very frustrating

**Comment by teebolt** [comment]
prescient

**Comment by substack** [comment]
This feature is a nuclear weapon that allows any of tens of thousands of obscure developers embedded somewhere in the dependency graph to bring down existing, functional packages. This creates a huge amount of work for everyone upstream to migrate immediately away from the package, since nothing works until they do and mostly nobody is getting paid to be on call for this kind of thing.

Plus, anybody with maintainer rights can unpublish a package, even if there are other maintainers. One of my packages got unpublished. Unpublishing puts efforts like open open source on shaky ground and makes people feel rightly worried about adding extra dependencies.

**Comment by indrora** [comment]
I'm going to chime in some pennies:

As a preservationist, *unpublish* is one of the few things that I wish didn't exist. I'm okay with orphaned packages, but the idea that a thing that (potentially) much of the Node infrastructure depends on (*cough*left-pad*cough*) can just vanish in an instant is a bit scary.

As a sysadmin: This makes me now instantly distrust *any* application written in Node. I can't guarantee that the software will be *around* in the future due to the shaky infrastructure that is npm.

IMO, Node lost legitimacy because of npm. It's not safe to use in anything that needs to be around in the future.

Unpublish should tombstone the last version and all previous versions, orphaning the package from a maintainer. 

As a developer: I feel uncomfortable using Node and npm for anything and I fail to see how the unstable house of cards that has been built around Node is sustainable.
