### ISSUE TITLE
`npm version` puts wrong version to the commit message if previously you tried to set an existing version

### ISSUE THREAD

**Issue by lolmaus** [npm/npm#7126]
# Steps to reproduce

1. Init an npm project and set up version control.

2. Set a version: 

        npm version 0.1.0

3. Push tags to Github:

        git push origin --tags

4. Set a version again, making a mistake and setting an existing version:

        npm version 0.1.0

  npm will correctly warn you of the mistake.

5. Set a different version and push:

        npm version 0.2.0
        git push origin --tags

# What i expect

I expect the last commit message to be "0.2.0".

# What actually happens

The last commit message is "0.1.0", duplicating that of the previous commit.

**Comment by smikes** [comment]
Thanks for the bug report!  Was this with the latest version of `npm` (2.2.0) or with an older version?

/cc @othiym23

**Comment by lolmaus** [comment]
$ npm --version
2.1.2

**Comment by othiym23** [comment]
This issue has been filed before (I just tried and failed to find one of the previous issues, so I'm not surprised you didn't either), and while your expectations are reasonable, this is a surprisingly hard thing to do properly because we need to:

1. bump the version in `package.json`
2. commit the change to the updated `package.json`
3. tag that commit
4. publish the package to the registry

It would be nice to be able to do this transactionally, but npm has to outsource steps 2 and 3 to Git, and if you think about it, you'll see why the order needs to be as it's listed. When this has come up before, the request has been to roll back the commit if publishing fails, but that seems really dangerous to me if something else has gone wrong -- you might end up losing a commit that you care about, and most developers aren't comfortable fishing commits out of the reflog.

Something that *could* be done is check to ensure that the tag you want to add doesn't exist before you bump the `package.json` / commit the changed file. I'm assuming there are some missing steps in the repro case you list above, because npm will barf if you use the same version twice in a row before it gets to the commit step. But it would be helpful if npm did more validation so this happened less often. I would be happy to take a patch that adds that!

**Comment by othiym23** [comment]
Following from my last message in this thread, I'm going to leave the `patch-welcome` label on this issue, but close it. This is because, while it would be nice if `npm version` were more transactional, this isn't something urgent enough that the CLI team is going to make it a priority within the next 6-12 months. If someone feels like taking a whack at this, we're glad to provide help. Thanks for your time!
