### ISSUE TITLE
Current open PRs and open issues

### ISSUE THREAD

**Issue by smikes** [npm/npm#7138]
just a quick Q before tomorrow when the next version comes out- do I have any PRs that need work from me before they can be merged?

And there are 50 or so stale support cases on the spreadsheet as OkToClose. Happy Wednesday.

**Comment by othiym23** [comment]
Can we not use the issue tracker to do this kind of process management, please? It clutters things up and messes with my workflow.

To answer your question, I don't know, because I've been focused on npm-internal stuff this week, so I haven't had time to review PRs yet, which I was planning on doing tomorrow. I might close some stale bugs today, but I also am still trying to get to the work I planned to do on Monday, so I might not. There's a lot going on. ;)

**Comment by smikes** [comment]
No problem. What's a better way to communicate project planning stuff? Twitter? Email?
