### ISSUE TITLE
`npm install -g json-schema-generator` fails with `npm ERR! cb() never called!`

### ISSUE THREAD

**Issue by iki** [npm/npm#7146]
```
...
npm http fetch GET http://npm-registry01.prd.nytimes.com/wordwrap/-/wordwrap-0.0.2.tgz
npm ERR! cb() never called!
```

btw, any idea why npm tries to get wordwrap from npm-registry01.prd.nytimes.com, instead of registry.npmjs.org like all other pkgs?

**Comment by smikes** [comment]
Can you upload your package.json and npm-debug.log as gists? <https://gist.github.com>

**Comment by iki** [comment]
There's no `package.json`, I'm installing the package globally. And `npm-debug.log` is not generated.

Other colleagues in team are able to reproduce it on different systems (win8, mac, arch linux).

Can you reproduce it by running `npm install -g json-schema-generator`?

**Comment by KenanY** [comment]
@iki Yeah, I was able to reproduce this but I do not believe it is the fault of `npm`. Running with a `loglevel` of `"silly"`, I got a little more info on the error:

```
npm info attempt registry request try #2 at 07:53:38
npm http fetch GET http://npm-registry01.prd.nytimes.com/wordwrap/-/wordwrap-0.0.2.tgz
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
npm info attempt registry request try #3 at 07:54:38
npm http fetch GET http://npm-registry01.prd.nytimes.com/wordwrap/-/wordwrap-0.0.2.tgz
npm ERR! cb() never called!
```

Looks like json-schema-generator has an `npm-shrinkwrap.json` which [specifies a dependency](https://github.com/krg7880/json-schema-generator/blob/dc632a1a3395b542d07357183ff9a5d4ad996794/npm-shrinkwrap.json#L36) as coming from a registry mirror hosted by nytimes. This doesn't seem to be up and online at the moment, hence `npm` freezes up and indeed a callback is never called somewhere.

**Comment by othiym23** [comment]
It is *always* an internal error / a bug when you see `cb() never called!`. In this case, npm should fail with a better error message after the request to the NYT internal registry times out. In this case, though, it doesn't matter quite as much, because the install is going to fail either way. We'll fix our side of this, but probably not right away, because this is mostly a small problem with usability.

@KenanY is right, though, somebody should file a bug on `json-schema-generator` telling them to either ditch their `npm-shrinkwrap.json` from the published package, or to make sure that it's not pointing to their private registry when they publish the package to the public registry.

**Comment by iki** [comment]
thanks @othiym23, reported
