### ISSUE TITLE
report test success/fail to a db

### ISSUE THREAD

**Issue by isaacs** [npm/npm#715]
Two configs:

* `npats` A base url to report tests to.
* `report-npats` Boolean, default `false`. If not set explicitly, and `test-on-install` is set, and stdin and stdout are both ttys, then prompts the user at the start of the "install" command.

**Comment by othiym23** [comment]
Readdressing a year and a half later, the Node and npm communities have gone one way, and this pointed the other. We're starting to look at the idea of global hooks to do things like this, and there are features under discussion for the npm web site and primary registry that also point at the same idea of tracking quality metrics over time. That said, the sense of the team right now is that `npat` is effectively deprecated, and should be actually deprecated at some point, because it's at least a little at odds with current packaging conventions (i.e. people using `files` to strip tests out of published packages). As such, this fine idea has finally met its end. 🍻 out for `npat-report`. It was a good idea.
