### ISSUE TITLE
Revamp npm search / local index caching etc.

### ISSUE THREAD

**Issue by silkentrance** [npm/npm#7153]
Since npm search is rather memory hungry on the client as it first downloads the whole package index into memory and from there instantiates the JSON object, I think that there is a need for redoing both the client side and the server side handling of the package index.

I guess that on the server side there is a single couchdb view that will generate the package index. This needs to be changed. Each package index needs to be associated with a timestamp. So whenever one publishes or otherwise causes an update to the index, a new index will be written with a different timestamp.

Or something similar to that.

Next, on the client side, whenever building an index for the first time, the index downloaded from the server will have a timestamp and of course the actual data. This index will be streamed directly to the filesystem instead of streaming it into memory. In case of the download being aborted, the system can then call upon the service, requesting the parts of the index that have not been downloaded yet for the timestamp that the index was registered with the service and which is also known to the client.

That timestamp could also be the filename of the file to which the index (update) is being streamed to, e.g. ~/.npm/update/1234567890.part etc.

The client on the other hand will store the index data in a local sqlite3 database by reading the cached JSON index file using a streaming/event based parser to cut down on overall memory usage.

The rationale for using sqlite3 instead of couchdb would be that it can be embedded more easily and is readily available for a multitude of platforms. And, looking at `npm-search`, it uses a Google inspired key-value store, which may or may not be as well supported as sqlite3.

The sql schema for that database would be so that it allows npm to quickly search through that index and also update that index incrementally with new data received from the service, e.g.

```
table system
   last_update int

table package
   name text

   unique name

table version
   package text
   version text
   summary text
   description text

   unique package, version

and so on
```

Feel free to comment on this in order to make npm a better experience for everyone.

**Comment by silkentrance** [comment]
The current format returned by npm when querying for /-/all is

```json
"0": {
  "name":"0",
  "dist-tags": {"latest":"0.0.0"},
  "maintainers: [{
     "name":"zolmeister","email":"zolikahan@gmail.com"
  }],
  "readmeFilename":"",
  "license":"BSD-2-Clause",
  "users": {"zolmeister":true},
  "time": {"modified":"2014-06-17T06:38:43.495Z"},
  "versions":{"0.0.0":"latest"}}
```

which includes redundant, and, for the purpose of the index file, unwanted information. Getting rid of maintainers and users will cut down the overall size of the index file. Also leaving out the readmeFilename will reduce the overall size of the index. The latter can always be restored from the actual package json once that file has been downloaded from the server.

**Comment by timoxley** [comment]
Note the current search output includes maintainers in the list of =users.

https://github.com/npm/npm/blob/master/lib/search.js#L113

**Comment by timoxley** [comment]
> I think that there is a need for redoing both the client side and the server side handling of the package index.

Search in general needs redoing, should just perform search on the server-side using the same api that powers npmjs.com. Any potential speed gains from performing client-side search are entirely lost by having to constantly re-download the search index.

**Comment by silkentrance** [comment]
@timoxley of course, yet, keeping a local index of the data in your local cache and also a presumably stale index of the packages available on the server will speed things up on the client and will also dumb down the server and the overall infrastructure and logic required on the server.

See for example `apt` or `maven` and other such tools which all will keep local copies of the server indexes.

**Comment by othiym23** [comment]
> Search in general needs redoing, should just perform search on the server-side using the same api that powers npmjs.com.

[That's the plan](https://github.com/npm/npm/issues/6016#issuecomment-70162066)!

**Comment by timoxley** [comment]
> dumb down the server and the overall infrastructure and logic required on the server.

Note all that infrastructure and logic is already implemented for https://www.npmjs.com/.

**Comment by othiym23** [comment]
> See for example `apt` or `maven` and other such tools which all will keep local copies of the server indexes.

It's sort of an accident of history that `apt-cache search` and `apt-get install` use the same metadata stores to do their thing, and npm follows a fundamentally different approach from maven / APT / rubygems when it comes to how it uses its registry. For most package managers, the source of truth about the state of the packages available is the local cache, but with npm, it's always online. Having search data available for offline querying is certainly *convenient* (which is why I'd like to still have it available as a fallback option), but it makes sense to have both search and the registry being treated as online query engines.

**Comment by timoxley** [comment]
@othiym23 offline search could be an entirely separate project.

**Comment by othiym23** [comment]
@timoxley Yup, @smikes is [on it](https://github.com/smikes/npm-kludge-search)!

**Comment by timoxley** [comment]
as in, an offline search/registry would work better if it kept itself up to date in the background rather than when you actually want to perform actions on it, would require some kind of helper daemon or cron job which seems out of place in the npm client.

**Comment by silkentrance** [comment]
Since using npm offline does not actually make any sense unless when installing directly from the local cache and searching what is available in the local cache or the locally cache index, the only reason for having the local cache and the index is to offload processing power from the server to the client, IMO.

As for the daemon I would strongly advise against it or make it optional, if you will.

**Comment by othiym23** [comment]
> As for the daemon I would strongly advise against it or make it optional, if you will.

The force multiplication npm gets as a team by building one shared search service for all of our components (the command-line, the web site, API exposed to other services) pretty much ensures that an online search service is going to be the primary way to search npm by the end of 2015. Being able to build one tuned Elastic Search cluster (or whatever) that can handle fancy search syntax and do things like filtering and sorting will allow us to make huge improvements to the user experience for search that would be incredibly laborious if we had to do it in multiple places.

Language package managers and distribution package managers are very different things. When I first started using npm, I was constantly comparing it (unfavorably) to APT, but I've since realized that the kinds of things that APT prioritizes (a smooth, integrated experience for operational staff; robustness across an entire distribution; packager control over upstream dependencies) are very different than what the npm community prioritizes. I still really admire APT's balance of flexibility and simplicity, but operationally it's just _different_, and its needs are different from npm's.

**Comment by othiym23** [comment]
As far as @smikes's approach, it's just a strawman approach for now, and is unlikely to be integrated into mainline npm without a bunch of refinement and bikeshedding. I like it because it offers the possibility of a _much_ faster search per query without imposing unacceptable costs on users, as well as not causing npm to explode when you use one of its documented features, which is the most important goal.

**Comment by othiym23** [comment]
> Each package index needs to be associated with a timestamp. So whenever one publishes or otherwise causes an update to the index, a new index will be written with a different timestamp.

This is already how the `/-/all` endpoint works -- if you look at the [search code](https://github.com/npm/npm/blob/master/lib/search.js#L60-L75), you'll see that it's sending a timestamp with the request, so that it only gets the data it needs.

> Next, on the client side, whenever building an index for the first time, the index downloaded from the server will have a timestamp and of course the actual data. This index will be streamed directly to the filesystem instead of streaming it into memory.

Making the client side consume the data as a JSON stream is perhaps the one incremental improvement to the current search system that makes the most sense, but if you look at how search works right now, there is a point at which it needs to have the whole JSON blob in memory to do the entire search, because it's consuming the search data as a single, cached object. Instead of doing a gigantic linear scan every time we want to do a search (which is what would happen were we to start treating the cached search index as a JSON stream), I'd much rather use an actual search engine. It will produce higher-quality results and be vastly more efficient. This is part of the impetus behind wanting to converge on a centralized service.

> The client on the other hand will store the index data in a local sqlite3 database by reading the cached JSON index file using a streaming/event based parser to cut down on overall memory usage.

npm can't afford to add a dependency on anything native, for the reasons I outlined previously.

I really think this discussion is better framed in terms of the work @smikes has been doing on `npm-kludge-search`, with the caveat that npm is pretty much committed towards building and supporting a server-side search endpoint in the medium term (just not immediately). I share your goal of creating a better search experience for everyone, and I believe that this is an area where having a multi-layered solution, where there's an offline index for (optional?) fallback use in addition to online search, but this proposal is skewed too much towards the client side.

**Comment by smikes** [comment]
I think the most bikesheddable (and possibly most valuable, or at least value-explorable) region would be developing comparison metrics that could be used to rank various query results.  I'm pretty sure @seldo is working on that, at least part of the time.  I really hope my contribution (name) is accepted, but really the whole subproblem looks interesting.

I have discovered that hashing names and having 100 different data files is actually **worse** performance than just reading the whole damn JSON file into memory.  So I have to revert `pure-fts` one step.

 I might experiment with streaming each object independently instead of streaming them as a single object; I also want to do some thinking about `rsync`-able compression, whether that's done by hand (I've done that before, it's not fun, but do-able) or by a pure-js rsync-friendly algorithm (not `zip` or `gz` unfortunately; maybe `xz`?)

**Comment by othiym23** [comment]
> I have discovered that hashing names and having 100 different data files is actually **worse** performance than just reading the whole damn JSON file into memory.  So I have to revert `pure-fts` one step.

Remember that one of the sad-clown.gif aspects of the current search story is that it's pretty much impossible to use `npm search` in memory-constrained environments like the Raspberry Pi or mobile. I think some query time loss is acceptable if it keeps the runtime memory consumption of the search process under, say, 128MiB.

> I also want to do some thinking about `rsync`-able compression, whether that's done by hand (I've done that before, it's not fun, but do-able) or by a pure-js rsync-friendly algorithm (not `zip` or `gz` unfortunately; maybe `xz`?)

The last time I played around with these things, I found [`xdelta`](http://en.wikipedia.org/wiki/Xdelta) pretty easy to implement. Granted, I was doing it in OCaml, but still.

**Comment by smikes** [comment]
And downloading a 6MB compressed search index is much much better than a 100MB JSON object and then indexing it on the client machine. ;-)

**Comment by smikes** [comment]
> one of the sad-clown.gif aspects of the current search story is that it's pretty much impossible to use npm search in memory-constrained environments like the Raspberry Pi or mobile. I think some query time loss is acceptable if it keeps the runtime memory consumption of the search process under, say, 128MiB.

Oh, that's a good thing to keep in mind - thank you.  I will probably ultimately aim for 64kib uncompressed blocks compressed and padded to 1kib  boundaries, where as many (stripped) objects as can fit are packed into each block.  Then the fts index will just specify block hits and we will assume we still have to scan each block.

**Comment by silkentrance** [comment]
@othiym23 @smikes I think that this discussion is fruitful and should be continued.

I for my part would like the npm query /-/all... to return something like this for a single package descriptor

```
{
  name : ...,
  version: <last version published, not necessarily the latest>.
  versions : {
     latest : <pointer to version, e.g. '1.0.0'>,
     '1.0.0' : { published: <datetime the version was published>, unpublished: <datetime the version was unpublished> }
      ...
  },
  summary : <package summary>,
  keywords : <list of keywords from package.json of the last version published>
}
```

Plus additional other information, for example the author and maybe also the repository and issues URL.
In think that for a local search the list of available version is rather important, as is the list of keywords.

**Comment by silkentrance** [comment]
@othiym23 as for the not depending on natives - sqlite3 is readily available on a multitude of platforms, especially those based on Linux, including Android. While Windows is a special case here, OSX includes it as a required part of its core data framework.

**Comment by silkentrance** [comment]
@othiym23 with daemon I meant the comment made by timoxley about having a local daemon that periodically updates the local package index.

As for APT and NPM being totally different, I do not see why this should be so. NPM, as a company, could provide a similar service for NPM clients without it losing its primary business goals, whatever these might be. See for example the company behind the Nexus maven repository, or other similar solutions.

I especially like the sort of distributed nature of the maven or APT repository infrastructure. Here, you can add multiple repositories to your sources/maven pom and maven or apt will utilize all of the configured repositories.

**Comment by othiym23** [comment]
> @othiym23 as for the not depending on natives - sqlite3 is readily available on a multitude of platforms, especially those based on Linux, including Android.

I don't think I expressed myself clearly enough there -- npm is itself distributed via npm as 100% pure JavaScript, and it _needs_ to stay that way. While it's typically installed alongside Node in a distribution-specific package, that's far from the only way to install it, and the only thing it should expect to be there at install time is node / iojs itself. Until it is up and running, there's no way to build native dependencies. It's possible that npm could use something like `node-pre-gyp` to get precompiled versions of things like sqlite, but the npm needs to have access to the internet at install time. Because of the way npm bundles all its dependencies within its distribution package, this is currently not necessary, which makes all kinds of offline installation scripts and workflows possible. What I'm saying is that the install process is pretty finely optimized at this point, I'm disinclined to fool around with that without a very good reason, and adding this much complication for something I think is better handled elsewhere is _definitely_ not a good enough reason.

**Comment by smikes** [comment]
@silkentrance I don't disagree with the goals you're putting forward, but for the moment I have chosen to try to work around the parts of the `npm` ecosystem that are hard to route around.  That means **not** expecting changes the format of the `/-/all` endpoint, **not** using any form of native/precompiled code, etc.  (I did have an sqlite3 backend in the original proof-of-concept implementation, though.)

If you have concrete suggestions, issues, or PRs with `npm-kludge-search`, please open them there.  There's a lot here to take in, and I can't narrow it down to an actionable item for https://github.com/smikes/npm-kludge-search/issues/2
