### ISSUE TITLE
Allow to exec 'npm uninstall' without parameters

### ISSUE THREAD

**Issue by piranna** [npm/npm#7162]
If you exec ```npm uninstall```, since you are not givingit a package name it try to uninstall itself from its dependencies, that doesn't make sense. Worse than this, it also doesn't try to exec the script defined in package.json for ```scripts/uninstall```.

I propose to add support to exec ```npm uninstall``` without a package name to make it symetry with ```npm install```, so it should remove from node_modules all the packages defined as dependencies and devDependencies. In the case of bundleDependencies, it should exec ```npm uninstall``` without a package name on them.

My use case is that in NodeOS I'm using ```npm install``` as a sort of ```make``` execution to download all the binaries and compile them, so ```npm uninstall``` would be similar to ```make clean```.

**Comment by othiym23** [comment]
`npm uninstall` already [has a function](https://github.com/npm/npm/blob/master/lib/uninstall.js#L20-L38), which is the same as `npm unlink .`, which is basically to make it the complement of `npm link` (with no parameters): remove the global link to this package. Unfortunately, unless I'm reading the code wrong, it's _always_ had a bug that makes it do the wrong thing – it should be uninstalling the package from the global `node_modules`, instead of the local one. @isaacs, can you double-check my reasoning there?

> Worse than this, it also doesn't try to exec the script defined in package.json for `scripts/uninstall`.

Sure it does, because that's part of what `npm.commands.unbuild` does. It's probably not making it far enough to run the script because of the issue I mentioned above.

Either way, the time-honored way to uninstall everything in your application is either to run `rm -r node_modules` or `git clean -fd node_modules` (or whatever moral equivalent your VCS offers). It makes sense to fix the bug that's there right now; it doesn't make sense to radically change the behavior of the command for what seems like a pretty marginal use case for most users.

**Comment by piranna** [comment]
> npm uninstall already has a function, which is the same as npm unlink ., which is basically to make it the complement of npm link (with no parameters): remove the global link to this package. Unfortunately, unless I'm reading the code wrong, it's always had a bug that makes it do the wrong thing – it should be uninstalling the package from the global node_modules, instead of the local one. @isaacs, can you double-check my reasoning there?

I've seen the code and seems the bug you are saying is in the line
https://github.com/npm/npm/blob/dbea6b2f3b236dc130764e9df31a5b97936bc4f2/lib/uninstall.js#L31,
since it doesn't allow to uninstall packages globally. I think
definitely is a bug too, but don't know why it hasn't surfaced...


> Worse than this, it also doesn't try to exec the script defined in package.json for scripts/uninstall.
>
> Sure it does, because that's part of what npm.commands.unbuild does. It's probably not making it far enough to run the script because of the issue I mentioned above.

Yes, it's true, it's part of npm.commands.unbuild, sorry for say that.


> Either way, the time-honored way to uninstall everything in your application is either to run rm -r node_modules or git clean -fd node_modules (or whatever moral equivalent your VCS offers). It makes sense to fix the bug that's there right now; it doesn't make sense to radically change the behavior of the command for what seems like a pretty marginal use case for most users.

I've been checking again and the error that it give me is

npm WARN uninstall not installed in
/home/piranna/Proyectos/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/node_modules:
"nodeos-cross-toolchain"

that correspond to line
https://github.com/npm/npm/blob/dbea6b2f3b236dc130764e9df31a5b97936bc4f2/lib/uninstall.js#L61.
I think the problem is related to line
https://github.com/npm/npm/blob/dbea6b2f3b236dc130764e9df31a5b97936bc4f2/lib/uninstall.js#L54,
since it's only taking in account the case for uninstalling global
packages and that's why it tries to uninstall itself as one of it's
dependencies (and also it's a very ugly line, by the way :-P ), so
it's not needed to change the behaviour of the function but only take
in account that untested corner case (as you've said, people use to
exec 'rm -rf node_modules' instead of doing 'npm uninstall' as they
should...). Seems to be an easy to fix bug, I can be able to do a
quick pull-request for it :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
As said on https://github.com/npm/npm/issues/7279#issuecomment-77840901, both issues are similar and although the solution proposed there is a valid one, seems hacky and I think that should be the behaviour of ```npm uninstall``` to make it symetric with ```npm install``` when both are executed at the root of a npm package.
