### ISSUE TITLE
Npm publish makes statistics spike on L10ns package

### ISSUE THREAD

**Issue by tinganho** [npm/npm#7164]
Every time I published on this L10ns package. The statistics spikes. Right now I know I don't get a lot of downloads though somehow the day after I publish I get like over 200 downloads per publish. I know for sure that this can't be true.

http://npm-stat.com/charts.html?package=l10ns on Jan 11th this year we can see such a spike. And all the spikes that is over 100 downloads also represents fake downloads.

**Comment by othiym23** [comment]
As @seldo has [explained a few times now](http://blog.npmjs.org/post/92574016600/numeric-precision-matters-how-npm-download-counts), any new publish activity is going to see a flurry of downloads as various (non-npm) mirrors, private registries, and other robots grab copies of your package for themselves. The absolute numbers of downloads aren't an entirely accurate metric (and realistically speaking, there's no way for us to make them accurate, ever), but the trends over time are a useful indicator of a package's popularity.

Also, this issue is not something that has anything to do with the npm command-line interface. There are separate repos for npm's [web site](https://github.com/npm/newww) as well as the [downloads API](https://github.com/npm/download-counts); you may want to raise your concerns there.

**Comment by tinganho** [comment]
Can't you just instead of counting all http 200:s - Why not let npm CLI append a unique key in the query parameter to the download URI? And only count those with the unique key?

**Comment by othiym23** [comment]
The CLI already uses its own User-Agent string when making requests; there's nothing stopping people from modifying their bots to make them look just like the CLI (and they do, and will continue to do so). We may add more additional metrics as we figure out how to capture them. The current download counts are a rough proxy for package activity, and have never been sold as anything but. Why do you need them to be accurate?

**Comment by tinganho** [comment]
No, I just think it is better to have more accurate statistics than less
accurate.

Mon Jan 19 2015 at 10:05:30 AM skrev Forrest L Norvell <
notifications@github.com>:
