### ISSUE TITLE
Error: fetch failed with status code 406

### ISSUE THREAD

**Issue by rochal** [npm/npm#7174]
Hi,

I'm trying to install package that has been tarballed and uploaded to an instance of Nexus which is playing a role of private npm repo but I'm getting http error 406 when I try to pull that tarball:

$ npm install "http://nexus.**.com/nodejs/my-module-0.0.3.tgz"
npm ERR! fetch failed http://nexus.**.com/nodejs/my-module-0.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406

I can see that file is coming back as "application/x-compressed" for tgz or "application/x-gzip" for tar.gz which is different to "application/octet-stream" returned by tarballs from npmjs.org.

I can't see why MIME type should matter here considering .tar.gz/.tgz are returned in the wild as anything from  "application/x-gtar", "application/x-tar", "application/x-compressed" to finally "application/octet-stream".

*Edit:*
I just created new tarball but saved it under "my-module-0.0.3.test" which comes back from Nexus as "application/octet-stream" however I am _still_ getting the same 406 issue.

**Comment by rochal** [comment]
As usual updating npm with `npm install npm -g` has helped the issue. Oops.

**Comment by bentaber** [comment]
I had the same issue and found that my http server was returning application/gzip.  Switching to application/x-tar resolved the 406 error.

**Comment by yorch** [comment]
Same problem here (also using a private Nexus instance), tried the `npm install npm -g --ca=null` but didn't go through. If using `npm@1.4.28`, it works just fine, but not with `npm@2.5.1`.

**Comment by rochal** [comment]
@yorch - that's right, this is still a problem for `npm@2.5.1`.

**Comment by othiym23** [comment]
This is not an issue with npm – Nexus is the application returning the status code of 406. For some reason it doesn't like the [`accept` header](https://github.com/npm/npm-registry-client/blob/master/lib/fetch.js#L86) set by `npm-registry-client`. It's possible that Nexus doesn't like the `application/vnd.github+json; q=0.1` portion of the header, but that is unfortunately required in order to fetch tarballs from GitHub, and since it's an alternate (with low quality / priority) content type, it shouldn't have an affect anyway. It sounds like your issue is with Nexus, not npm.
