### ISSUE TITLE
Better config documentation: definitive information about what config params affect which subcommands

### ISSUE THREAD

**Issue by smikes** [npm/npm#7185]
> If somebody wanted to rework all the config handling to work in a more declarative, per-command argument handling system that coupled documentation to the arguments for each individual command, and was able to do it in a backwards-compatible way,

No prob, just instrument `npm` for coverage and examine every possible code path that touches `config.get` (and config.set and subprocesses, oh my!) and then build a table (might need a tree, might not even be acyclic (!)) of `npm` subcommands and all the config variables that can affect their behavior, and then come up with a declarative syntax for asserting these claims , and then instrument `config` so that violations of the declarative syntax are logged and recorded and **not** logged to the user, but passed back to some shadowy `npmjs.org` endpoint and used to adjust the declarative syntax, so that it can be improved.

Then write a documentation generator based on that.

Ref #7082

**Comment by othiym23** [comment]
That's awesome! When will you have a PR for us to review? :dancer:

**Comment by smikes** [comment]
There aren't enough emoji in the world for the face I'm making at you right now. Start with :japanese_demon: and downhill from there. 

First npm-kludge-search, then doctor. So maybe April? :-P

**Comment by othiym23** [comment]
\o/

**Comment by othiym23** [comment]
This is a very important issue for the team – the way that configuration, usage, and other documentation is handled for the CLI right now is really oriented towards the developers and maintainers of the tool. npm is very configurable. Trying to keep the configuration documentation up to date is a difficult task, which is why it's centralized in a single config doc. At the same time, a lot of that configuration is context-sensitive (i.e. `--dev` means different things with different commands – sometimes very bad things). It's past time to pull that information out of where it is, and put it closer to where it's most likely to be useful for a confused user.

However! This is a pretty big task! To really be effective, it requires something like the static analysis @smikes describes above, followed by some careful auditing of the source by somebody who has some time and patience. To me, this sounds like something that could be divided up between a team of interested collaborators. Which is to say, this sounds like a more-or-less freestanding project of interest to heavy npm users, or people who'd like an entrée into being more involved with npm's development. To do this properly requires some support from the CLI team so that it doesn't devolve into chaos, and our docket is full for the next couple months, as we get `npm@4` out and plan out what we want to incorporate into `npm@5`, which is likely to be a more significant release than `npm@4` (and might be a good place to include this and other broad improvements to the CLI's user experience for newer users).

As such, I'm leaving this open, without a solid sense of when we're going to get to it, because I think improving the documentation in this way is important. If this is a project you feel interested in contributing to, let us know, and maybe we can start a PR to coördinate the work. Big thanks to @smikes for getting this started!
