### ISSUE TITLE
npm install -g node-inspector error

### ISSUE THREAD

**Issue by kuangcaibao** [npm/npm#7192]
```
C:\Users\Administrator>npm install -g node-inspector
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\3rdProgram\\node.js.0.10.35\\\\node.exe" "C:\\3rdProgram\\node.js.0.10.35\\node_modules\\npm-2.3.0\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-3980-7a7a8540\registry.npmjs.org\node-inspector\-\node-inspector-0.8.3.tgz
npm ERR! Expected: 2eac57771973c6eb49100ef4c9caa6ae0bcd8911
npm ERR! Actual:   9031b8a0624450f2a0017022f1a253ef6023d54c
npm ERR! From:     http://registry.npmjs.org/node-inspector/-/node-inspector-0.8.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
```

**Comment by kuangcaibao** [comment]
The npm package manager fetch the file node-inspector-0.8.3.tgz
the expected md5(?or something else) value does not match the real md5 value.
hoping your answer,thanks a lot

**Comment by smikes** [comment]
Is this still a problem for you?

Could you try clearing the bad download out of your cache and re-downloading?

```
npm cache clean node-inspector
npm i -g node-inspector
```

There have been a lot of improvements to npm since 2.3.0. Can you try updating your npm installation?  `npm@latest` is 2.5.1

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by kuangcaibao** [comment]
Thanks

**Comment by kikaendeavor** [comment]
bingo～it works，3Q
