### ISSUE TITLE
npm on RedHat 6.6 with vagrant on Windows/CygWin

### ISSUE THREAD

**Issue by johandry** [npm/npm#7228]
I'm creating an AngularJS application with yeoman using generator-angular in a RedHat 6.6 on VirtualBox using Vagrant on Windows with CygWin. When I create the scaffolding in a File System of RH (/home/vagrant/) everything run all right. When I create the scaffolding in a File System sync with Vagrant to the Windows/CygWin FS (/home/vagrant/workspace/), the 'npm install' does not work.

I get a lot of errors like this one, for several npm modules:
```bash
    npm ERR! Error: EPERM, open '/home/vagrant/workspace/sandbox/mytodo/node_modules/grunt-google-cdn/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/argparse/node_modules/underscore.string/lib/underscore.string.js'
    npm ERR!  { [Error: EPERM, open '/home/vagrant/workspace/sandbox/mytodo/node_modules/grunt-google-cdn/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/argparse/node_modules/underscore.string/lib/underscore.string.js']
    npm ERR!   errno: 50,
    npm ERR!   code: 'EPERM',
    npm ERR!   path: '/home/vagrant/workspace/sandbox/mytodo/node_modules/grunt-google-cdn/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/argparse/node_modules/underscore.string/lib/underscore.string.js' }
    npm ERR!
    npm ERR! Please try running this command again as root/Administrator.
    npm ERR! tar.unpack untar error /home/vagrant/.npm/es6-iterator/0.1.2/package.tgz
    npm ERR! tar.unpack untar error /home/vagrant/.npm/es6-symbol/0.1.1/package.tgz
    npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
    npm ERR! argv "node" "/home/vagrant/.npm-packages/bin/npm" "install"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.3.0
    npm ERR! path /home/vagrant/workspace/sandbox/mytodo/node_modules/grunt-google-cdn/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/memoizee/node_modules/es6-weak-map/node_modules/es6-symbol/test/is-native-implemented.js
    npm ERR! code EPERM
    npm ERR! errno 50
```
Looks like npm is not friend with Vagrant or VirtualBox folder sharing.

Please, let me know if you need more information, log or configuration file or if there is something I should do to fix this.

Thanks,
Johandry

**Comment by smikes** [comment]
/cc @othiym23 Windows bug report

I believe your paths are getting too long for the underlying Windows/Cygwin filesystem.  See for example <https://msdn.microsoft.com/en-ca/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath> which documents the 260 character limit.  The path that is failing is

```
'/home/vagrant/workspace/sandbox/mytodo/node_modules/grunt-google-cdn/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/argparse/node_modules/underscore.string/lib/underscore.string.js'
```

which happens to have 240 characters; the other 20 characters could easily be eaten up by `C:\cygwin\home\username` or whatever the mount point of your virtualbox filesystem is.

When `npm` is used on natively on Windows, it does some fiddling to mitigate these problems.  When `npm` is used on Linux with a native Linux filesystem, this is not a problem.  Is it possible for you to change your host/guest setup to work around this?

**Comment by johandry** [comment]
Thanks smikes, I have tried some workarounds to reduce length of the path but I haven't make it work yet. However, I found it is a well known issue with Vagrant/VirtualBox/Windows to manage long paths and npm for creating them.

I also read there are a fix pending in Vagrant for this and a workaround meanwhile it is fixed. Here they are, in case someone get here with the same problem: 
https://github.com/mitchellh/vagrant/issues/1953
https://github.com/mitchellh/vagrant/issues/4815

Thanks for point me in the right direction :)

**Comment by drmyersii** [comment]
I've spent about 16 hours working on this today (I wish I was exaggerating), and I finally have a solution to the Vagrant/Windows issue at hand. I have been working on a Node.js development environment built on Vagrant, and I have been relentlessly determined to get this working. 

[This is the commit that I implemented it in](https://github.com/renobit/vagrant-node-env/commit/bdf15f2f301e2b1660b839875e34f172ea8be227), but I'll go ahead and post the main snippet of code here:

```ruby
config.vm.provider "virtualbox" do |v|
    v.customize ["sharedfolder", "add", :id, "--name", "www", "--hostpath", (("//?/" + File.dirname(__FILE__) + "/www").gsub("/","\\"))]
end

config.vm.provision :shell, inline: "mkdir /home/vagrant/www"
config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` www /home/vagrant/www", run: "always"
```

In the code above, I am appending ```\\?\``` to the current directory absolute path. This will actually force the Windows API to allow an increase in the MAX_PATH variable (normally capped at 260). Read more about [max path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath). This is happening during the sharedfolder creation which is intentionally handled by VBoxManage and not Vagrant's "synced_folder" method. The last bit is pretty self-explanatory; we create the new shared folder and then make sure it's mounted each time the machine is accessed or touched since Vagrant likes to reload its mounts/shared folders on each load.

I absolutely hope this helps everyone that was struggling with this like I was!

**Comment by Ditchfuuu** [comment]
drmyersii, this has just worked perfectly for me - thanks for saving me many hours!

**Comment by liboyue** [comment]
I met this problem when I'm excuting `npm install mongodb` in the shared folder. I solved it by installing mongodb globally
```
npm install mongodb -g
```

**Comment by rpepato** [comment]
Thanks for your solution @drmyersii! I had already spent 6 hours untill I finally get to your message.
