### ISSUE TITLE
NPM Shashum check failed issue

### ISSUE THREAD

**Issue by muthukumarts** [npm/npm#7231]
```
Error: shasum check failed for C:\Users\467034\AppData\Local\Temp\npm-6568-DjmIIceX\registry.npmjs.org\uglify-js\-\uglify-js-2.4.16.tgz
Expected: 84143487eb480efd7d0789c7ecfbd48a695839f9
Actual:   e0fa858e4a8ff5c7a4e2b09c6e04b97fd7f7a577
From:     http://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
    at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
    at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
    at ReadStream.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
If you need help, you may report this *entire* log,
including the npm and node versions, at:

NPM Version:1.4.28
Node:node-v0.10.35-x86

```

**Comment by smikes** [comment]
This looks like a bug that was present in older versions of `npm` - sometimes corrupted packages would be cached.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
