### ISSUE TITLE
Better version of update (bikeshed)

### ISSUE THREAD

**Issue by smikes** [npm/npm#7234]
Since `update` is widely regarded as broken, how about this as a replacement:

`npm update -g`: 
for every package installed globally, run npm install -g `<pkg>@latest`

`npm update`:
```
for every dependency in `package.json`, enter the following interactive loop:
   npm test
   npm install <pkg>@<version>
   npm test
   if tests succeed, update package.json with "^<version>"
   if tests succeed, offer to drop user into directory to make necessary fixes

git add package.json
git commit
```

How to choose `version`?  Several options: `--conservative` would do latest-respecting-semver ; `--latest` would do `latest`; and `--dist-tag foo` would use the named dist-tag, in the weird case that all dependencies of a particular package all had the same dist-tag system.

Thoughts? /cc @othiym23

**Comment by nathan7** [comment]
That's ambitious, and interactivity and automatic test running here is very much out of line with anything npm does currently. But I can probably be convinced that this should be in npm, and not in an external tool.

**Comment by nathan7** [comment]
In particular, I'm not convinced at all that `npm update` should touch package.json — it should simply install the latest version allowed by the `package.json`. Maybe `npm update --save`?

**Comment by smikes** [comment]
Fair point about `--save` being required to do the write back.  Even if not updating `package.json`, the new configuration could be saved with `npm shrinkwrap`.

I'm just trying to follow the spirit of what was wanted with `npm update` originally, where the goal was to make it a command useful to package maintainers updating dependencies.  Brazenly updating everything at every depth in `node_modules` to `@ latest` has not been a good feature, but there's a kernel of an important idea in there.

Maybe the `update` name is tarnished for this, and it would be better called `npm modernize`?

Or maybe it should be an external module.  Perfectly reasonable suggestion too.  (PS try <https://github.com/smikes/npm-kludge-search>)

**Comment by jtara** [comment]
AFAIC npm is now completely broken for it's intended purpose. Restoring it to usefulness is hardly "ambitious".

I now just periodically uninstall everything, clean the cache and reinstall everything, while seeking alternative installation options. Since I mostly work in Ruby, I usually seek RubyGems that have the necessary Javascript bits built-in to the Gem.

It would be nice if there were some resolution soon.

**Comment by smikes** [comment]
@jtara I hope at least you are on `npm@2.3.0`.  The 1.4 series had a lot of race conditions.

**Comment by jtara** [comment]
Yes, 2.3.0, installed with brew on OSX.

**Comment by nathan7** [comment]
@smikes So, even given `--save`, there is no precedent for `--save` doing git stuff. Afaik `npm version` is the only command that interacts with git, so far. I'm open to a `modernise` / `modernize` command that does that separately, specifically as a package maintainer thingy. Maybe `dist-upgrade` even? q=

**Comment by smikes** [comment]
The git stuff is icing, but I will work on it as a a separate module anyway.  But first I want to fix completion in npm-kludge-search

**Comment by othiym23** [comment]
I'd hold off on doing any work on this until `npm@3` lands. @iarna has straightened a lot of this out as part of multi-stage install. What she and I have spec'd out is not nearly as exciting and featureful as what @smikes describes, but that's kind of the point. `npm update` should be boring and predictable, just like `npm install`.

Also, I have to walk back an erroneous statement I have made many times: it's not true that `npm update` just says "YOLO" and updates everything to `latest` regardless of the semver in `package.json`; what happens instead is that `npm update` updates every dependency to the latest matching version in semver _simultaneously_, which is its own boiling cauldron of nondeterministic weirdness, especially when you're running `-g` and one of the things being updated is npm itself. 

I agree with @nathan7 that having such a high degree of interactivity in a top-level npm command is unprecedented (aside from `npm init`), and I also am not super excited about the idea of `npm update` updating `package.json` by default. One of the things that `npm@3` brings is tighter integration of `npm-shrinkwrap.json` into the ordinary flow of using npm commands; it makes sense to me to have `npm-shrinkwrap.json` updated automatically by `npm update`, but not `package.json` (is that the current plan, @iarna?).

`--save` is not the best name for this, either, because it slightly changes the meaning from `npm install`, where there's `--save`, `--save-dev`, and `--save-optional`. If we can't come up with anything better, though, it'll do.

**Comment by smikes** [comment]
Every dependency of every subdependency at once, to the latest version.  Awesome.

This is not going to get attention before other things I have committed to — notably, search, the small version of usage/short help (#7082 NOT #7185), and doctor.  

I've been thinking about "maintenance mode" and what sort of a tool/workflow I'd like to have for managing the dependencies of my own projects.

I will tentatively call this `npm-modernize` then, since `update` will remain a core verb with the well-known behavior.

**Comment by smikes** [comment]
It turns out that `npm --depth=0 update` and `npm --depth=0 update <package>` already support the update functionality I was imagining.  I will close this issue now.

@jtara if you are still running into problems, please let us know!
