### ISSUE TITLE
`npm pack`/`publish` option to not rename or keep a copy of `.gitignore` files

### ISSUE THREAD

**Issue by UltCombo** [npm/npm#7252]
This is a feature request to implement a flag to `npm pack` (and perhaps `publish`) to keep `.gitignore` files in the tarball. Right now they seem to be renamed to `.npmignore` by `npm pack`.

The use case for this is described at #3763

I'd be fine with it either not renaming the file, or keeping both `.gitignore` and `.npmignore` in case `.npmignore` is actually necessary for internal functions.

Would this feature be welcome?

**Comment by UltCombo** [comment]
Looks even if a tarball contains a `.gitignore` file, `npm install` will also rename it to `.npmignore`. So it looks like there's no way around this besides a postinstall script.

**Comment by iarna** [comment]
Or creating an empty `.npmignore`. Does that not meet your needs?

**Comment by UltCombo** [comment]
@iarna thanks for the input, but that doesn't actually solve the issue. As commented in the [linked issue](https://github.com/npm/npm/issues/3763#issuecomment-34715556):

> I tried using an empty .npmignore, but my .gitignore is still getting removed.

If I have both `.gitignore` and an empty `.npmignore` in the same directory, the generated tarball only contains the empty `.npmignore` -- the `.gitignore` is being discarded.

Could this be considered a bug? Or status by design that could be improved?

**Comment by UltCombo** [comment]
FWIW I've implemented a simple hack around: https://github.com/es6rocks/slush-es6/commit/10e9bf4b6920ef28b64c00ea800866328aae92b6
More in-depth reasoning at [this issue](https://github.com/es6rocks/slush-es6/issues/7)'s 3rd bullet point.

**Comment by iarna** [comment]
So it does, how unexpected. In fairness, I guess that is more consistent than only sometimes moving it away.

I'd like to understand more what you're trying to do that requires a .gitignore at install time? I read #3763 but it wasn't clear to me why they needed a git ignore at, again, install time.  I take it that you're doing some code generating at postinstall time? But why can't that be done at prepublish time?

**Comment by UltCombo** [comment]
@iarna The use case is generator packages (think [yeoman](http://yeoman.io/generators/) / [slush](http://slushjs.github.io/generators/#/) generators).

That is, a package whose main purpose is to generate new packages, by providing the appropriate templates/boilerplates to bootstrap new projects. Often, `.gitignore` files are part of these templates/boilerplates.

I believe it would be nice to have an option to tell npm to not process any package.json/.npmignore/.gitignore files inside a given directory, that should suffice for the generators use case.

**Comment by iarna** [comment]
Ahhh, ok, that makes sense. So, in this case you have a tool that creates a new project for the end user or installs a set of templates, right? Why can't that step do the gitignore -> .gitignore rename? Wouldn't that be a clearer work around than trying to do something at the install/postinstall step?

**Comment by UltCombo** [comment]
> Why can't that step do the gitignore -> .gitignore rename? Wouldn't that be a clearer work around than trying to do something at the install/postinstall step?

That could be a solution, indeed. Whether is cleaner is rather subjective:

- Your suggested solution must be executed on every generator run and adds complexity to the main package (the generator) code.

- Install/postinstall is only ran once and keeps the main package code clean. IMO it makes more sense to workaround a npm limitation/bug using npm mechanics (install script) than polluting my package's main code with npm workarounds, as well.

**Comment by UltCombo** [comment]
I'm aware that (post)install scripts are deprecated, but are they scheduled to be removed anytime soon? If so I'll be forced to add one extra step in the generator logic then.

**Comment by iarna** [comment]
To my knowledge there's no plan to actually remove them. Let's just say that they're discouraged.

**Comment by iarna** [comment]
Thank you for the clarification! One of the problems with trying to preserve .gitignore files is forward compatibility. It's easy enough to update `npm pack` to leave them in place. But any older versions of npm will then thwart this because untaring the package implicitly renames or ignores .gitignore files.

**Comment by UltCombo** [comment]
> To my knowledge there's no plan to actually remove them. Let's just say that they're discouraged.

Oh ok, thanks. That makes sense as it would likely break many published packages.

> But any older versions of npm will then thwart this because untaring the package implicitly renames or ignores .gitignore files.

Yes, I edited `fstream-npm` to preserve `.gitignore` files in the tarball but then I noticed it was no use as `npm install` also renames any `.gitignore` in the tarball to `.npmignore`.

Another alternative I've thought is zipping the templates directory prior to publishing, but that would also requires a (post)install script.

I'm not sure what would be the best approach here... Perhaps this is too subjective.

**Comment by iarna** [comment]
How files are chosen for packing is poorly documented. 😕

**Comment by UltCombo** [comment]
> How files are chosen for packing is poorly documented. :confused:

Yep, I also noticed that if a subdirectory contains a `package.json` containing (valid JSON and) a `files` array, then files from that subdirectory are also filtered according to the given `package.json`'s files array.

**Comment by iarna** [comment]
Yeah, that makes sense given the code, but is insane from a user perspective. 😒

**Comment by UltCombo** [comment]
I'm struggling to find a better/canonical way for publishing generators to npm, but it seems like the standard approach is to just apply workarounds when necessary.

Guess I'll just stay with the "it works" approach until there's a better approach.

**Comment by UltCombo** [comment]
Updating the `npm pack`/`publish` would at least be useful for people to know what workarounds they have to apply though. :smiley:

**Comment by UltCombo** [comment]
Oh, I found the reasoning about why `.gitignore` is always excluded: #1862

I wonder if it would be possible to improve the the generators use case, perhaps a `bundleFiles` property in the package.json for future-compatibility. My idea of `bundleFiles` is to just include them in the tarball without any processing (.gitignore/.npmignore/package.json), as well as when unpacking.

**Comment by smikes** [comment]
How about this as a workaround: store the template in a .tgz file during packing.

So while you are working on the template module, you have the template expanded:
```
template1/.gitignore
template1/file1
...
```

Then at the time of publication, you write a custom `npm` script that compresses the template, so package.json would contain something like:

```
"scripts": {
   "my-publish": "tar czf template1.tar.gz template1/ ; npm publish"
}
```

Now you can either extract the `tgz` file when running your generator or (if you want it to lie on the filesystem extracted) extract it in an `install` script.

The advantage to using a this approach is that `npm` will not look inside your `template1.tgz` file or manipulate its contents in any way.

**Comment by UltCombo** [comment]
@smikes I've considered that approach a [couple](https://github.com/es6rocks/slush-es20xx/issues/7) [times](https://github.com/npm/npm/issues/7252#issuecomment-72350900), in the end that would increase complexity unnecessarily so I preferred simpler approaches for the time being.

Compressing the templates directory before publishing is the most bullet-proof way, I'll start doing it if I run into any other problem.

**Comment by smikes** [comment]
Fair enough. For the reasons you've found in the other case, npm is likely to keep assuming it is allowed to read, honor, and manipulate files like .gitignore, .npmignore, package.json in the directory being packed. 

Essentially what we are discussing is, what is an appropriate protocol for escaping these files so npm treats them as data, not code.  :-)

**Comment by dcrockwell** [comment]
This probably isn't worth actually changing `npm` over at this point, especially since there are several workarounds for the problem in fringe cases.

**Comment by wparad** [comment]
Workarounds just means that everyone will keep running into this.  The common assumption is that `npm pack` will just create the tarball, why would anyone think that the `.gitignore` file would be renamed and excluded.  The fact that new people keep on finding this means that a real solution is definitely what is needed.

**Comment by UltCombo** [comment]
@wparad Several people check-in their `node_modules` into version control systems (whether that is a good practice is another topic). If npm started including `.gitignore` files in the installed packages by default it would be a breaking change for these people—authors often git-ignore compiled files that are published to npm via `package.json`'s `files` field or setting a `.npmignore` in the same level as the `.gitignore`.

I agree this would be a nice feature, but it needs to be opt-in behavior IMO.

Furthermore, note that even if you manage to publish a tarball containing a `.gitignore` file, older and current npm client versions will rename `.gitignore` to `.npmignore` when installing packages or unpacking tarballs, so not only the package author(s) would need to have a very recent npm client version installed but also all the consumers of your package as well. Unfortunately, a good part of the community uses just the npm version that came with their Node.js installation and don't know how to check or update it, so even if such a feature is implemented you may want to keep using workarounds in order to maintain compatibility with older npm versions and avoid overcomplicating your package's install instructions and dealing with bug reports about bad installations.

**Comment by wparad** [comment]
I'll ceed your first point (although your second holds no weight for me) as a reason for the opt-in behavior.   Then I think the request would be two-fold:
* Update [npm pack documentation](https://docs.npmjs.com/cli/pack) to call out this behavior, along with the solution. (Being a non-standard thing to do, I think the functionality should be clear for users)
* Update `npm pack` and `npm install`.  My suggestion here would be a `package.json` property `allow_gitignore: true`, and then look for this property in the cli command at execution to exclude this behavior.

**Comment by UltCombo** [comment]
Yeah, that seems good. 😄 

My second point above was mostly a comment from my own view point as a package author. Whether package authors will opt to or not to use such feature is up to each one of them, that's no reason to prevent the feature from being implemented.

Though, my comment is also supposed to be a warning to package authors—it seems several authors think that implementing such an option would magically fix the issue at hand, but even if they publish packages with an up-to-date npm version that supports this feature, the problem will persist for consumers that will have older npm client versions. I felt this implication was not quite clear until now, hence my comment above. Authors must understand this and properly document the npm version requirement, as well as setting the `package.json`'s [`engines` field](https://docs.npmjs.com/files/package.json#engines) appropriately.

**Comment by wparad** [comment]
Ahhh.  I just meant that package authors assuming that this change will allow them to implement the functionality without all their clients gaining the benefit isn't a reason to not make this change.  Mostly that is a point of education, although we probably should investigate why both the pack and install commands attempt to alter the `.gitignore` file.  That may be the main blocker...should `npm pack` or `npm install` convert the `.gitignore` to `.npmignore`, why are both doing it?  Which means `npm install` could have different expected results when authors manually package instead of using `npm pack`.

Possible progress could be, stop `npm install` from changing files, leave `npm pack` alone.  Then add the cli switch (either commandline, package.json, or both) to leave the `.gitignore` in place.

**Comment by othiym23** [comment]
The CLI team had to review enough of this to get to #1862, which is indeed a solid rationale for why npm does this. It's otherwise very puzzling behavior, and has been the source of a lot of discussion within the team.

It's late in the game for npm to make changes that affect how people deploy their Node applications, and as such the bar to making changes around that functionality is set very high. This limitation does affect people who want to build generators and sample packages, and in general the behavior around [`"files"` and ignores is confusing](https://github.com/npm/npm/wiki/Files-and-Ignores). It's been that way for a while!

That said, if you read that wiki page, you'll see that there's a whole bunch of things going on, and it's a delicate process to change one aspect of it without causing a host of complications elsewhere. As such, we're not going to change it unless and until we redo how npm's package packing and unpacking code works, and even then I don't feel comfortable making guarantees that we'll go any particular direction around how `.gitignore` and `.npmignore` are handled. The most reliable way to work around this, that will work with all versions of npm, is to have your generator either copy a file or generate one at install or creation time.

We'd be happy to review documentation patches. A patch to make clear that `.gitignore` is renamed to `.npmignore` (and that `.gitignore` is never included in the package tarball) would definitely reduce confusion among everybody. There actually is [pretty OK](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) documentation around what the CLI is doing during the publishing process, but our docs can always use improvement.

Because we're not going to change the behavior, I'm going to close this issue. Thanks to all for the discussion and ideas, and thanks for your time!
