### ISSUE TITLE
Warn at install about PATH lookup issues in global installs

### ISSUE THREAD

**Issue by isaacs** [npm/npm#7255]
So, if you install a package that has a bin named something like "ruby" or "shutdown", it'll drop it by default into `/usr/local/bin/...`, which takes precedence on most unix systems over `/usr/bin/...`.

npm is smart enough to not *clobber* a bin it doesn't own.  So that's good.  But still, it's confusing and weird, and can ruin someone's day.

1. If a bin is *not* going to be the thing found in the PATH, we should warn about that.  (The package isn't actually doing what it says, perhaps.)
2. If a bin *is* going to be found in the PATH, but something else is being shadowed, then we should warn about that as well.

Not sure the best way to accomplish this, probably just some `which()` logic.  We should probably still actually proceed with the install, though.

**Comment by buschtoens** [comment]
While I haven't yet found a package which *intentionally* tries to take precedence over a OS bin, it could very well be the case that those exist. It would also make sense in some edge cases. So packages should retain this ability.

##### 1. The package is shadowed by an OS bin

Warning seems reasonable as no potential damage can be done. But how should the user actually go about resolving the conflict?

There are four possible cases:

a. The package installs multiple bins and the bin in question is not needed by the user.
  - Do nothing.

b. Only the npm bin is needed.
  - Somehow *do* shadow the OS bin. Ideas?
  - Symlink or rename the npm bin, e.g. `ln -s /usr/local/bin/foo /usr/local/bin/node-foo`.  
    This could be done automatically.
  - Ask the package maintainer to change the bin name, as this could be an accidental naming conflict.

c. The npm bin intentionally tries to "overwrite" a OS bin for whatever reason.
  - Somehow *do* shadow the OS bin. Ideas?

d. Both bins (OS and npm) are needed.
  - This is most likely an accidental name conflict, so asking the package maintainer to change the bin name would be the best reolution.
  - Symlink or rename the npm bin, e.g. `ln -s /usr/local/bin/foo /usr/local/bin/node-foo`.  
    This could be done automatically.

However, npm can't automatically discriminate between those cases and can't read the users mind. So automatic conflict resolution is impossible.  
For now, I'd recommend warning and creating an automatic symlink à la `node-foo`. We can start thinking about point 1.c, when someone actually runs into this.

If you happen to know a happy path for this, adding it to the docs and referencing them in the warning would be great.

##### 2. The package shadows a OS bin.

We should throw a warning at the very least. Preferably at the very end of the install process, so it doesn't slip the users attention.  
However I am still pro erroring and making the user use the `--force` flag, as we can potentially deal a lot of damage in contrast to case 1.

Besides making a system instable and / or unbootable by accident, this also poses an attack vector to gain root rights without the user knowing. Imagine proxying a OS bin that is executed with root rights during boot time. The user wouldn't notice anything, but you could run your own scripts with root rights and run whatever malware you want.

I know that the user should always check and audit the packages he installs, but who seriously does that? You also get a quick summary during the install, but that won't help either. Users are stupid. At least I am.  
I intentionally installed [`reload`](https://www.npmjs.com/package/reload), fully aware that it will create the `reload` bin. I also know about Ubuntu's `reload` bin and use it on a regular basis, but I didn't think about that at all during the installation.

You seemed to be concerned about erroring, because it would over-complicate the installation process for users. However, I think this is a quite rare case. At least I don't know any popular packages which collide with OS bins.

I would rather be forced to think at very rare occasions to prevent possible damage.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now. Also this is a good thing to do, just gotta get it right.

**Comment by othiym23** [comment]
This is the kind of novel, useful, and interesting suggestion I would expect from my CEO, and I'm not just saying that to suck up. I'm not aware of a package or distribution manager that does something like this at install time, even though it removes (or reduces) a large class of potential footguns. I think this, as described in the original post, is a fantastic idea.

However! It's also not incredibly high urgency for the team. There is a security dimension to this (in that bad actors could shadow important system binaries for nefarious purposes), but that falls into the category of "high impact, low probability" threats, and is something that would best be handled by taking down a package doing anything obviously ill-intended. That leaves unintentional surprises, and while warning people that they're either not going to be able to use a newly-installed package, or that they're going to be supplanting a system utility, is a good idea, it's not obviously more important than much of the other work on the team's plate. Therefore I'm going to close this feature request, because the CLI team isn't going to get to this in the near to medium term.

However again! Because this is a self-evidently useful bit of functionality (and because, while it has a few subtleties, it's not that complicated to write), the CLI team would be delighted to get this submitted to the project as a patch. If you're interested in implementing this, I think there's enough information here to put together a patch, so just go ahead and put together a PR. Thanks to all for their time!
