### ISSUE TITLE
Handle 410 responses from packages that are available due to unpublishing

### ISSUE THREAD

**Issue by seldo** [npm/npm#7261]
The current registry serves 404 responses for any package name that is available, either because nobody has ever published to it or because it was previously unpublished. Registry 2.0 will be able to distinguish better between those states by serving a 410 for unpublished packages, but the CLI currently doesn't handle 410s well.

npm should handle a 410 when looking up a package and indicate it is available, having previously existed.

**Comment by isaacs** [comment]
We should not be using 410 for this.  410 means "Gone", as in, "Gone and never coming back, please don't bother ever checking again, your cache is the last copy, and I want you to delete it".

But a deleted package isn't a dead url.  If someone else publishes at that location, it'll return.  A 404 is most appropriate there.

One place where we probably *should* use a 410 is a package tarball file for a deleted version.  If you unpublish `foo@1.2.3`, then there is no way that another `foo@1.2.3` could ever exist.  So, any assets tied to that, like the tarball, can never return once they are deleted.  There, we should serve a 410.  (And, in that case, I suspect that the cli behavior is fine, since it's a bona fide error to even be checking that.)

**Comment by othiym23** [comment]
@seldo, @isaacs: What is the actual problem this change is meant to address? I'm not seeing what would drive the registry to return 410 in the first place. If we follow @isaacs's guidance, we'd need to change `npm-registry-client` to handle unpublished packages across commands, which sounds like something for the error handler. If not, I'm cornfused. :corn:
