### ISSUE TITLE
Strange peerinvalid behavior

### ISSUE THREAD

**Issue by gsklee** [npm/npm#7265]
I have `react` v0.13.0-beta.1 installed and was trying to install `react-chartist` v0.2.1 which has specified the following:

```
"peerDependencies": {
    "react": ">=0.10.0"
}
```

It failed with the following output:

```
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-chartist@0.2.1 wants react@>=0.10.0
```

How come?

**Comment by smikes** [comment]
I believe this is due to a special case in semantic versioning.  Pre-release versions do not satisfy `>=` constraints unless the pre-release is present in the constraint.  If you can fall back to `0.12.2`, that will work; alternatively, you could modify `react-chartist` to depend on `>=0.13.0-a`, which would accept all `0.13.0` pre-release versions.

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!
