### ISSUE TITLE
Unmet dependencies after updating a dependency

### ISSUE THREAD

**Issue by AgentME** [npm/npm#7268]
I have a project that had a dependency on "lodash": "^2.4.1" and "whacko": "^0.17.2". Whacko has a dependency on lodash ~2.4.1. When I ran `npm install` in my project's folder, lodash was installed under node_modules, and as expected, whacko used my project's lodash instance instead of having another installed under node_modules/whacko/node_modules.

Now I've updated my project to use lodash 3.1.0. I edited my project's package.json to depend on lodash version 3.1.0, and then I ran `npm install`. Lodash was updated, but whacko wasn't fixed to have its own version of lodash, I got this output from npm:

```
npm WARN unmet dependency /Users/chris/Coding/npm-test/node_modules/whacko requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /Users/chris/Coding/npm-test/node_modules/lodash,
npm WARN unmet dependency which is version 3.1.0
lodash@3.1.0 node_modules/lodash
```

and npm exited with status 0 despite things not being so great.

Is `npm install` the wrong command for this situation? I next ran `npm update` in case that was the correct command, which gave me this output:

```
npm WARN unmet dependency /Users/chris/Coding/npm-test/node_modules/whacko/node_modules/CSSselect requires domutils@'1.4' but will load
npm WARN unmet dependency /Users/chris/Coding/npm-test/node_modules/whacko/node_modules/domutils,
npm WARN unmet dependency which is version 1.5.1
lodash@2.4.1 node_modules/whacko/node_modules/lodash
CSSselect@0.4.1 node_modules/whacko/node_modules/CSSselect
├── domutils@1.4.3 (domelementtype@1.1.3)
└── CSSwhat@0.4.7
```

It looks like it fixed the lodash issue, but created a new separate issue at the same time.

Using npm version 2.3.0

**Comment by smikes** [comment]
I would suggest (provided there's nothing unrecoverable currently living in your `node_modules`) trying the following:

```
$ rm -rf node_modules
$ npm install
```

This should cause `npm` to see that the two dependencies on `lodash` cannot be met by the same installation, and `whacko` should then get its own copy of `lodash`.

This is an edge case, since `npm` currently does not re-inspect dependency requirements when doing an install.

An upcoming version of `npm` (planned for `npm@3`, milestone `multi-stage-install`) will probably not be vulnerable to this bug, since it will compute the full required dependency tree before realizing it.

**Comment by AgentME** [comment]
This is part of a server build and deploy script that gets used many times a day. Removing the node_modules folder every single time for it to be fully recreated would make it take ridiculously longer.

I considered doing something like this in the code:
```
if grep -q 'npm WARN unmet dependency' < <(npm install 2>&1)
then
  rm -rf node_modules
  npm install
fi
```

but needing to handhold a dependency manager to manage dependencies like this is madness.

**Comment by smikes** [comment]
@AgentME  Madness?  This! Is! npm!

But yes, I agree with you, the full rm and install is only reasonable for development, not for production..

Are you using shrinkwrap?  That might help in the meantime; the complete fix will be shipping "soon" since I believe this is exactly the kind of problem that's addressed in `npm@3.0`

**Comment by AgentME** [comment]
Shrinkwrap suffers from similar issues. I wasn't sure if it was worth filing a separate bug or not.

```
npm init
npm i --save whacko
npm shrinkwrap
# Notice that node_modules/whacko/package.json requires parse5 ^1.3.0
# Notice that node_modules/whacko/node_modules/parse5 is at 1.3.2
nano npm-shrinkwrap.json # edit parse5 version to be 1.3.0
npm i
# Notice that node_modules/whacko/node_modules/parse5 is still at 1.3.2
rm -rf node_modules
npm i
# Notice that node_modules/whacko/node_modules/parse5 is correctly at 1.3.0
```

**Comment by smikes** [comment]
Right, it's just that when you're using shrinkwrap you can get  exactly the
node_modules graph you want, so if you discover and manually fix a
dependency issue, rebuild your shrinkwrap file and commit it, then you
don't  have to do  `rm -rf node_modules && npm install` to get a correct
dependency graph, you just need `npm install`.

As I said above, the real fix is coming in an upcoming `npm` release.

**Comment by AgentME** [comment]
>Right, it's just that when you're using shrinkwrap you can get exactly the node_modules graph you want, so if you discover and manually fix a dependency issue, rebuild your shrinkwrap file and commit it, then you don't have to do `rm -rf node_modules && npm install` to get a correct dependency graph, you just need `npm install`.

I just demonstrated that doesn't work. `rm -rf node_modules && npm install` was necessary to fix the dependency graph.

**Comment by smikes** [comment]
Ah, sorry.  Responding via email.

/cc @othiym23 any suggestions here?

**Comment by othiym23** [comment]
As @smikes says, `npm install` not noticing that transitive (second-level and deeper) dependencies have changed and fixing issues that it is otherwise aware of is a problem that npm has had for a long time. In fact, it's one of the primary reasons for the multi-stage install rework that @iarna has been doing for the last few months. If this behavior continues under `npm@3`, it is a major bug and will be fixed immediately. It probably won't be fixed until then, because the changes go deep enough that they can't realistically be backported without turning `npm@2` into `npm@3` anyway.

As far as shrinkwrapping goes, it's best to think of `npm-shrinkwrap.json` as an opaque artifact and only manipulate it via the CLI. There are a lot of fairly subtle dependencies between the data in the file and the behavior of the installer, and I think it's pretty common for changes made when hand-editing the shrinkwrap file to lead to unexepected results. In general, the best way to change shrinkwrapped dependencies is to remove the shrinkwrap file, make all the necessary changes to your dependencies, and then shrinkwrap the application again. Shrinkwrapping is a final finishing step before you ship your package.

The user experience around shrinkwrap files is still more awkward than it should be, which is why @iarna has made a number of tweaks that make for a much more pleasant user experience. Again, these changes are happening on the `multi-stage` branch of npm, and will be included in `npm@3`. It's still not ready for production use, but if you want to play with it to see if it better addresses your uses cases, @AgentME, it's still a little crash-happy but mostly feature-complete.

tl;dr these are problems which have our attention, work is substantially complete on addressing some or all of the pain points around these two issues, and there will be a released version of npm that addresses them in the not too distant future. Thanks for your patience!

**Comment by AgentME** [comment]
>As far as shrinkwrapping goes, it's best to think of `npm-shrinkwrap.json` as an opaque artifact and only manipulate it via the CLI.

I don't normally edit it manually. That was just for example here. I think this overlaps with the other issues described in this thread, but for completeness, here's a recent series of events that affected me:

1. A git repo cloned by two people has a `package.json` listing dependencies. Each user cloned and ran `npm i` at different times, so each user had a few (sub)dependencies of different versions installed.

2. One user ran `npm shrinkwrap`, checked in the shrink wrap, and pushed it to the repo.

3. The other user pulled the repo, ran `npm i`, but their node_modules folder still had sub-dependencies that did not match the shrinkwrap.

I've since changed our deploy script to parse the shrinkwrap and walk through the entire node_modules tree to make sure the versions match the shrinkwrap, because `npm install` doesn't do the trick, and this is much faster than removing the node_modules folder and re-installing it every time.

If npm@3 addresses these issues, I'll be very happy!

**Comment by iarna** [comment]
npm@3 does indeed do what you want here. (The `multi-stage` branch has a bug at this moment in updating modules that makes this break, but that'll be fixed later today.)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
