### ISSUE TITLE
Module superagent-proxy cannot be installed using npm install command

### ISSUE THREAD

**Issue by Perchut** [npm/npm#7277]
I do not have problem to install other npm modules like "superagent" for example.
Please find the error message below:
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/ariya/esprima.git)
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare reposito
ry 'C:\Users\m_da\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ariya-es
prima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: unable to connect t
o github.com:
npm ERR! git clone git://github.com/ariya/esprima.git github.com[0: 192.30.252.1
28]: errno=No error
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\m_da\AppD
ata\Roaming\npm-cache\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...

npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "superagent-proxy
"
npm ERR! cwd C:\Users\m_da\Documents\Angular\cine\cine_angular
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

**Comment by smikes** [comment]
This looks like a networking problem.  

> npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error

Are you perhaps behind a firewall that blocks your access to the `git://` protocol?
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by Perchut** [comment]
Hi,
I finally found the solution to my problem.
I did correctly set up the proxy parameter in my .github file. So I thought git was supported through the proxy.
But I had to put:
[url "http://"]
    insteadOf = git://
Because git:// was not supported and I did not think of that earlier.
Thank your for your comment it put me on the right path of search.

Thanks!
