### ISSUE TITLE
Cannot login - No credentials to set

### ISSUE THREAD

**Issue by gsklee** [npm/npm#7285]
So I have registered on NPM already on my old devbox and would like to do `npm adduser` on a new devbox. I've made sure that `init.author.name`, `init.author.email`, and `init.author.url` have been set identical to my existing `.npmrc` on the old devbox, and I can login without any issue on https://www.npmjs.com/, but when I tried to do `npm adduser` on the new box I always get this following error:

```
Username: gsklee
Password: 
Email: (this IS public) balancetraveller+npm@gmail.com
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/home/kaylee/.nvm/v0.11.15/bin/node" "/home/kaylee/.nvm/v0.11.15/bin/npm" "adduser"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6

npm ERR! No credentials to set.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
-
npm ERR! Please include the following file with any support request:
npm ERR!     /home/kaylee/npm-debug.log
```

Help?

**Comment by smikes** [comment]
I have a few suggestions here:

1. First update your `npm` to the latest; the versions shipped with older `node` packages are obsolete and buggy.  Since you are using `nvm` this will be easy:

```
npm install -g npm@latest
```

Second, if you've had your `npm` credentials for a while, you may need to regenerate them.  I'm not sure exactly why this happens, but it seems to have been caused by the registry migration midway through 2014.  The full instructions are here <https://github.com/npm/npm/wiki/Troubleshooting#npm-login-errors> and the short version is:

```
1. change password at https://npmjs.com/password

2. clear login-related fields from ~/.npmrc -- e.g., by running 
$ sed -ie '/registry.npmjs.org/d'  ~/.npmrc

3. npm login
```

I know it sounds silly to recommend changing your password when you are able to log in from your old dev box, but several people have reported that the above three-step process worked, so all I can do is suggest the same thing. :-(

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
