### ISSUE TITLE
npm install always fails on raspberry pi 2 using node v0.10.36 

### ISSUE THREAD

**Issue by gepatto** [npm/npm#7291]
I have a fresh install of raspbian 2015-01-31 on the (new) raspberry pi 2.
I grabbed the source code http://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz
extracted, did configure , make, and sudo make install (this all went just fine, just takes a while)
made a new dir and did
`npm install express --save`
this spits out a lot of lines, and ends with Unhandled prefetch abort: ...

I have tried the modules: forever, underscore express [ see https://db.tt/bK9gMXvr for logs ]
they all fail.
I have also tried:
`sudo npm -g install npm@latest`
but I still get the errors.

I have tried the same with unstable branch v0.11.16
And there is no problems there.

**Comment by othiym23** [comment]
I am sorry to inform you that that is actually a [kernel exception in ARM Linux](https://www.google.com/webhp?ie=UTF-8#q=unhandled+prefetch+abort), and therefore something to do with the way that one or both of Raspbian or Node are built. Since npm is pure JavaScript, there's no way for us to work around faults in the runtime or OS. On the other hand, I know that npm should work just fine with Node 0.11.16 and the ARM builds of io.js. So maybe just stick with one of those?

**Comment by gepatto** [comment]
Ok, thanks for looking into this.
I'll stick to 0.11.x
