### ISSUE TITLE
Interpret non-zero exit code of `scripts`

### ISSUE THREAD

**Issue by boennemann** [npm/npm#7304]
I want to use scripts like `"preinstall"`, or `"prepublish"` to automate things, but also to abort commands if a validation fails.

Currently I get a giant, scary and dangerous-looking error message that scrolls away my actual logs that would help to solve the problem.

It would be nice if not all exit codes >0 would be treated the same way. For example if I exit with `23` (or whatever really) `npm` stops the lifecycle, but doesn't print its own error.

**Comment by smikes** [comment]
This feature would be tricky to implement, since the official use of the lifecycle scripts is to automate tasks around the package's installation, start/stop, etc., and generally we want those tasks to leave a great big hairy stacktrace when they fail.

One way to work around this would be to write your scripts in bash or node and have them take an early exit, with code 0, but write your own error message.

Notwithstanding all the above, I believe this should be tagged as a feature-request, /cc @othiym23

**Comment by othiym23** [comment]
I'm going to tag this as a feature request, but I'm also going to close it, for the simple reason that you already have a certain amount of control over this in your lifecycle scripts:

```
"postinstall": "build-thing && do-other-thing && do-third-thing"
```

if you don't care about supporting Windows (but you should!), you can use `||` or `|| true` to prevent error exit codes from propagating.

In general, if you want to have finer-grained control about what happens with your build scripts, you should move that error-handling logic into the build scripts themselves. @smikes is right in that supporting this would add complexity (and potential sources of confusion) to lifecycle scripts, and as it can be worked around, the benefits don't outweigh the costs.

**Comment by boennemann** [comment]
Thanks for you explanation @othiym23,

I understand that this unnecessary complexity. It was just an idea and I wanted to hear what you think.

Just to clarify though, I don't want to abort other build scripts, but the actual npm command.
So e.g. I have a `prepublish` script that runs some validations whether i'm okay to publish a new version, and I want to prevent `publish` from happening if not.

Just so you have some more context here is my use case: https://github.com/boennemann/semantic-release

**Comment by othiym23** [comment]
There's a bug that (sometimes?) prevents npm from exiting with a nonzero exit code when lifecycle scripts barf. Were that to get fixed (and a patch to fix that would be very welcome), you could write something like `"prepublish": "npm run ready-to-publish --silent || do-other-thing"`, which I think will do what you want.

Also take a look at the output when you run `npm -q run <script>` and `npm --silent run <script>` -- maybe one of those is closer to what you want. In general, the big scary error message is most useful, because it helps let new users know where to look for help. It creates (a lot) more work for those of us supporting the CLI, but it's really helpful for users.

`semantic-release` looks really cool, by the way!
