### ISSUE TITLE
how to detect whether the npm module contains js addon(xxx.node)

### ISSUE THREAD

**Issue by ddnionio** [npm/npm#7307]
is there a command or general method to detect whether one module contains addon?

**Comment by smikes** [comment]
No, there is not.

Can you tell me a bit more about your use case?  What would you do with this information?

**Comment by ddnionio** [comment]
Thanks

nodejs require 3 types of modules: js json and addon
I just want to survey the proportion of each types.

**Comment by othiym23** [comment]
There isn't a way to tell without downloading the packages and unpacking them, but if a package tarball contains a `binding.gyp` file, then that file has an add-on associated with it. That is probably the best way to figure out what the balance is.

Since this is just a question and not an actionable issue, I'm going to close it now. Good luck figuring this out, and you might think about asking the folks working on the web site (@rockbot, @zeke) if there might be some way that we could expose this information there.

**Comment by zeke** [comment]
This would be a good thing to display on the site. One day we'll have a CDN that serves up package file contents, and we can just ask, "hey is there a binding.gyp in this package?"

See http://npm-cdn.herokuapp.com/hiredis@0.2.0?json
