### ISSUE TITLE
Error: shasum check failed

### ISSUE THREAD

**Issue by codervetri** [npm/npm#7325]
Hi guys,
I believe the following content is an issue, Please let me know if i am wrong.

The error "Error: shasum check failed" is gotten whenever the checksum fails. It also comes when the file is not received at the client. But there is nowhere in the error log that says about the file download. 
![image](https://cloud.githubusercontent.com/assets/6542274/6123478/3fc2e55c-b129-11e4-96e1-fe0774743f9e.png)

For the end user, It would be better if that is also mentioned in the error log.

Eg: File.tgz downloaded succesfully / failed.

Sincerely,
Vetri

**Comment by liitokala** [comment]
Hi,
under Linux I update 'npm' to version 2.5.0, and change 'https' to 'http', it works for me minutes ago.
Good Luck

**Comment by codervetri** [comment]
Hi liitokala, 

I am a new user in github, could you help me on how can i provide suggestions to an existing project? Because i have minor suggestion that could be made to errorlog to help user troubleshoot problems easier.

**Comment by smikes** [comment]
@codervetri, can you try updating your npm to the latest version -- 2.5.0 -- by following the instructions here: <https://github.com/npm/npm/wiki/Troubleshooting>

You are looking for "upgrading npm on windows"

If you have a bug report or feature request for npm , you are already in the right place -- this is the main issue tracker.

**Comment by othiym23** [comment]
@codervetri 
> It also comes when the file is not received at the client. 

This is not true. The shasum failure _is_ the message saying that the download failed -- the file has finished downloading, but it was corrupted. Had the file not finished downloading, you would have gotten an error message to that effect.

In general, there's no need to explicitly indicate when a fetch finishes, because the install process can't proceed until each download is done. If you want to see the completion of the individual files as they download, adding `--loglevel=http` to your npm command will give you pretty much exactly that.
