### ISSUE TITLE
Install Karma 

### ISSUE THREAD

**Issue by JosephRodriguez** [npm/npm#7335]
Installing Karma with npm install karma I have the following error, my NodeJS version is x64.

npm ERR! Error: No compatible version found: anymatch@'^1.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.2.0","1.0.0","1.1.0"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:709:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:631:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "karma"
npm ERR! cwd C:\users\jose
npm ERR! node -v v0.10.9
npm ERR! npm -v 1.2.24

**Comment by KenanY** [comment]
@JosephRodriguez Your version of `npm` is so old (years!) that it doesn't support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: anymatch@'^1.1.0'
```

Hence, `npm` fails to find a version of `anymatch` the meets the desired semver range. [Updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) will definitely fix this issue.

Alternatively, you could update your equally-old Node.js version. There have been several security patches and bug fixes since 0.10.9; and to top it all of 0.12 just came out! You can find the latest stable release at http://nodejs.org/

**Comment by JosephRodriguez** [comment]
@KenanY I solve this problem with your advice, upgrading npm from 1.2.24 to 2.5.0 everything works great!!!!, I thought the error message was for node version, not that of npm. I can install Karma with node 0.12.0?, because Karma Installatino page say:
 Karma works on the two latest stable versions. That is 0.8.x and 0.10.x at this point. 
Thanks.

**Comment by KenanY** [comment]
@JosephRodriguez Hmm, maybe they haven't updated that webpage to reflect the fact that the two latest versions are 0.10 and 0.12 now. I would bet that karma works on 0.12, but I personally cannot confirm; that would be a question for them. If anything, you can stick to 0.10 for the time being until you're sure you can upgrade.

**Comment by JosephRodriguez** [comment]
Thanks, @KenanY I will try later, install Karma with 0.12.0, one more time thank you so much.
