### ISSUE TITLE
ERR Installing grunt-contrib-cssmin

### ISSUE THREAD

**Issue by lamujeresponja** [npm/npm#7344]
```
npm ERR! Error: ENOENT, open '$APP_directory/node_modules/grunt-contrib-cssmin/node_modules/clean-css/node_modules/commander/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-39-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-cssmin"
npm ERR! cwd $APP_directory
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path $APP_directory/node_modules/grunt-contrib-cssmin/node_modules/clean-css/node_modules/commander/package.json
npm ERR! code ENOENT
npm ERR! errno 34
```

**Comment by KenanY** [comment]
@lamujeresponja Could you try [updating your `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc)? `1.4.3`'s 1-year birthday is in a few days actually :) and the latest version is `2.5.0` now.

**Comment by smikes** [comment]
It looks like you have a directory named `$APP_directory`, but this is confusing the system's command-line interpreter, which generally thinks that things that have `$` characters in them are variables that should be expanded.

Can you try using a different name for your directory, perhaps `test_app` or `project1` or something that doesn't contain a `$`.

Also, as @KenanY says, you should update your `npm` if you can -- there have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.3. 

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
