### ISSUE TITLE
npm install flag to install dependencies within git repos/submodules

### ISSUE THREAD

**Issue by appsforartists** [npm/npm#7347]
Presently, if you have a git-backed module inside `node_modules`, `npm install` will throw this error:

    Appears to be a git repo or submodule
    Refusing to remove it. Update manually,
    or move it out of the way first.

I appreciate npm's conservatism, but this can lead to a frustrating workflow, because now I have to manage that package's dependencies by hand.  I could `npm explore; npm install`, but then I'd end up with duplicated packages if both the parent and the child had similar dependencies.

Consider this example:

    my-app/
      dependencies:
        my-shared-module
        react@0.12
        react-router@0.11

      node_modules/
        my-shared-module/ (git repo)
          dependencies:
            react@0.12
            respimage@1.1.3
        
        react/

I don't want to end up with two copies of `react`, but that's precisely what would happen if I ran `npm explore my-shared-module; npm install` currently.

I'd like to be able to be able to run `npm install --include-git-dependencies` inside `my-app` with this result:

 - `react-router` is installed in `my-app`, because it is missing.
 - `respimage` is installed in `my-shared-module/node_modules/`.

   I understand that putting new files inside a git repo is something that must be done with care.  `--include-git-dependencies` could assert that the resulting package would be ignored by git before continuing.  Alternatively, `respimage` could be installed in `my-app`, though that raises the potential edge case of version conflicts.

 - `react` is not installed, because `my-app` already has a copy that satisfies the version constraints.

What are your thoughts on such a feature?  Would you be amenable to this PR?

**Comment by appsforartists** [comment]
If you're wondering why I'm not just using `npm link`, look here: #5875

**Comment by othiym23** [comment]
I don't think it makes sense to make this behavior configurable in the way you describe. The basic convention that npm follows is that it controls `node_modules` and its children. It provides some affordances to support checking `node_modules` in to version control, or hacking on what's currently in `node_modules` directly, but the basic idea is that you're working on subsidiary packages elsewhere rather than in `node_modules`.

`npm link` is indeed the suggested way to support this kind of live editing workflow. If #5875 is blocking you from using `npm link`, the right thing to do is to get #5875 fixed. It's possible that this is addressed by what is shaping up to be `npm@3`, but either way, it doesn't make sense to me to add new features to work around existing bugs that we've already agreed need to be resolved.

Thanks for taking the time to put together a thoughtful problem statement.

**Comment by appsforartists** [comment]
If npm3 installs all dependencies in the root node_modules, I think that will fix this issue.

Can #5875 be fixed?  It seems to be a bug in `require`, [which is locked](https://iojs.org/api/modules.html#modules_modules)

**Comment by othiym23** [comment]
#5875 can definitely be fixed, by some enterprising and clever developer who is probably not me, given my list of things to do and the CLI team's priorities.

`npm@3` will _mostly_ install dependencies in a flat way, but in order to preserve the ability to deal with nested dependencies, there will be occasions on which things get pushed down the tree. Put another way, if various dependencies assume that their peers or parents are at a given point in the tree, they're going to have a bad time.

**Comment by appsforartists** [comment]
Thanks Forrest.

npm 3 won't automatically ignore a packages dependencies just because it's back by git, right?  So as long as there are no conflicts, if I have a node_module backed by git, its dependencies will be installed in the root module?

**Comment by othiym23** [comment]
I think @iarna is the best person to answer that question, and I say that because I'm not sure what happens in the `multi-stage` branch when the installer hits a package that contains a `.git` directory.

**Comment by tuhoojabotti** [comment]
@othiym23 Another issue is that if I'm running my app in a Docker container I cannot use npm link directly.

I need to add a volume to provide the files and then inside the container run npm link which complicates everything a lot. If I just make a Docker volume `~/path/to/repo:/home/node/app/node_modules/my-module` I can use the module as if it was linked, but npm refuses to work with this arrangement.

**Comment by storjarn** [comment]
Using 'npm link' for a 3-level nested private module setup is way more cumbersome than using a git repo url in my package.json for a private package.  There's no way our IT are letting us publish these packages to npmjs.org, even with the private flag.  NodeJS is great!  This is a step backwards.
