### ISSUE TITLE
npm proxy authentication

### ISSUE THREAD

**Issue by rmillo** [npm/npm#7363]
When I'm  trying to install any package using npm, I get the following error:

```
npm ERR! registry error parsing json
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "express"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
....
```

Then a proxy page.
I'm connecting to internet through a proxy with digest authentication. npm support digest authentication for the proxy?? I have configured the proxy setting with
npm config set proxy ...
Regards

**Comment by smikes** [comment]
Your proxy setting needs to be in the form of a URL: `http://user:pass@proxy.hostname:port` ; sometimes leaving off the `http://` or using an incomplete hostname causes problems.

If you are able to use `curl` or `wget` from the command line, the same `proxy` or `http_proxy` settings as you use for those commands should work with `npm`.

Can you tell me more about the proxy you need to use?  Is it an NTLM-based proxy, or squid, or... ?

**Comment by rmillo** [comment]
I'm using a Digest-based proxy. Setting the variables proxy and http_proxy, i can use the curl command adding de --proxy-digest parameters, but wget don't work for me. I'm using wget 1.13 from Debian 7, but have downloaded and compiled wget 1.16, but don't work.
Any idea??

**Comment by smikes** [comment]
I don't know anything about digest-based proxies, but they are allegedly supported by request <https://github.com/request/request/blob/5764559937c5204ff1e4315542453cd9d8510b34/README.md#http-authentication>

> Digest authentication is supported, but it only works with sendImmediately set to false; otherwise request will send basic authentication on the initial request, which will probably cause the request to fail.

/cc @othiym23 for `npm-registry-client`, it looks like might need to set `sendImmedately` to `false` for digest authentication

**Comment by othiym23** [comment]
I think the safe answer, for now, is that npm doesn't support digest authentication for proxies. We might in the future, but for now you might want to look at workarounds, like installing a proxy on your local machine that does work with digest-based auth and pointing npm at it.

@smikes I took a look at the relevant code in request, and it's not just a matter of setting an option, because that configuration also assumes that you're passing in the proxy host, port, and credentials at the same time. Also, as you probably know by now, the proxy handling is a very delicate piece of the npm code base, and I'm pretty conservative about making changes to that code due to the likelihood of regressions. It would be good to handle this case, but I really don't want to break anything else in the process.
