### ISSUE TITLE
npm unmet dependencies

### ISSUE THREAD

**Issue by ollers** [npm/npm#7368]
below is logfile. Unable to install nprm

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'generator-webapp' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'generator-webapp', null ]
5 verbose cache add spec generator-webapp
6 silly cache add parsed spec { raw: 'generator-webapp',
6 silly cache add   scope: null,
6 silly cache add   name: 'generator-webapp',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed generator-webapp@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'generator-webapp', range: '*', hasData: false }
11 silly mapToRegistry name generator-webapp
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/generator-webapp
15 verbose addNameRange registry:https://registry.npmjs.org/generator-webapp not in flight; fetching
16 verbose request uri https://registry.npmjs.org/generator-webapp
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:40:38 PM
19 verbose request id 053ae889e188d004
20 http request GET https://registry.npmjs.org/generator-webapp
21 http 200 https://registry.npmjs.org/generator-webapp
22 silly get cb [ 200,
22 silly get   { date: 'Sun, 15 Feb 2015 23:40:39 GMT',
22 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly get     etag: '"94FDJG2O8132GD7K8BWLGWM1O"',
22 silly get     'content-type': 'application/json',
22 silly get     'cache-control': 'max-age=60',
22 silly get     'content-length': '46580',
22 silly get     'accept-ranges': 'bytes',
22 silly get     via: '1.1 varnish',
22 silly get     age: '0',
22 silly get     'x-served-by': 'cache-ams4140-AMS',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1424043639.294501,VS0,VE659',
22 silly get     vary: 'Accept',
22 silly get     'keep-alive': 'timeout=10, max=50',
22 silly get     connection: 'Keep-Alive' } ]
23 verbose get saving generator-webapp to /Users/olwynlee/.npm/registry.npmjs.org/generator-webapp/.cache.json
24 silly addNameRange number 2 { name: 'generator-webapp', range: '*', hasData: true }
25 silly addNameRange versions [ 'generator-webapp',
25 silly addNameRange   [ '0.1.0',
25 silly addNameRange     '0.1.1',
25 silly addNameRange     '0.1.2',
25 silly addNameRange     '0.1.3',
25 silly addNameRange     '0.1.4',
25 silly addNameRange     '0.1.5',
25 silly addNameRange     '0.1.6',
25 silly addNameRange     '0.1.7',
25 silly addNameRange     '0.2.0',
25 silly addNameRange     '0.2.1',
25 silly addNameRange     '0.2.2',
25 silly addNameRange     '0.2.3',
25 silly addNameRange     '0.2.4',
25 silly addNameRange     '0.2.5',
25 silly addNameRange     '0.2.6',
25 silly addNameRange     '0.2.7',
25 silly addNameRange     '0.3.0',
25 silly addNameRange     '0.3.1',
25 silly addNameRange     '0.4.0',
25 silly addNameRange     '0.4.1',
25 silly addNameRange     '0.4.2',
25 silly addNameRange     '0.4.3',
25 silly addNameRange     '0.4.4',
25 silly addNameRange     '0.4.5',
25 silly addNameRange     '0.4.6',
25 silly addNameRange     '0.4.7',
25 silly addNameRange     '0.4.8',
25 silly addNameRange     '0.4.9',
25 silly addNameRange     '0.5.0-1',
25 silly addNameRange     '0.5.0-rc.1',
25 silly addNameRange     '0.5.0-2',
25 silly addNameRange     '0.5.0',
25 silly addNameRange     '0.5.1' ] ]
26 verbose addNamed generator-webapp@0.5.1
27 silly addNamed semver.valid 0.5.1
28 silly addNamed semver.validRange 0.5.1
29 silly mapToRegistry name generator-webapp
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/generator-webapp
33 verbose addRemoteTarball https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz not in flight; adding
34 verbose addRemoteTarball [ 'https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz',
34 verbose addRemoteTarball   '4581cd69d5d0010be777863fb4a887b4a9ddb173' ]
35 info retry fetch attempt 1 at 11:40:40 PM
36 info attempt registry request try #1 at 11:40:40 PM
37 http fetch GET https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz
38 http fetch 200 https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz
39 silly fetchAndShaCheck shasum 4581cd69d5d0010be777863fb4a887b4a9ddb173
40 verbose addTmpTarball /var/folders/nz/215t74nj3sj4gcvx5wytnfvc0000gn/T/npm-29275-27dfd7ab/registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz not in flight; adding
41 verbose addTmpTarball already have metadata; skipping unpack for generator-webapp@0.5.1
42 silly cache afterAdd generator-webapp@0.5.1
43 verbose afterAdd /Users/olwynlee/.npm/generator-webapp/0.5.1/package/package.json not in flight; writing
44 verbose afterAdd /Users/olwynlee/.npm/generator-webapp/0.5.1/package/package.json written
45 silly install resolved [ { name: 'generator-webapp',
45 silly install resolved     version: '0.5.1',
45 silly install resolved     description: 'Scaffold out a front-end web app',
45 silly install resolved     license: 'BSD',
45 silly install resolved     repository:
45 silly install resolved      { type: 'git',
45 silly install resolved        url: 'https://github.com/yeoman/generator-webapp' },
45 silly install resolved     author: { name: 'The Yeoman Team' },
45 silly install resolved     main: 'app/index.js',
45 silly install resolved     engines: { node: '>=0.10.0', npm: '>=1.2.10' },
45 silly install resolved     scripts: { test: 'mocha --reporter spec' },
45 silly install resolved     files: [ 'app' ],
45 silly install resolved     keywords:
45 silly install resolved      [ 'yeoman-generator',
45 silly install resolved        'web',
45 silly install resolved        'app',
45 silly install resolved        'front-end',
45 silly install resolved        'h5bp',
45 silly install resolved        'modernizr',
45 silly install resolved        'jquery',
45 silly install resolved        'grunt' ],
45 silly install resolved     dependencies:
45 silly install resolved      { chalk: '^0.5.1',
45 silly install resolved        cheerio: '^0.17.0',
45 silly install resolved        'yeoman-generator': '~0.17.3',
45 silly install resolved        yosay: '~1.0.0' },
45 silly install resolved     devDependencies: { mocha: '*', underscore: '^1.6.0' },
45 silly install resolved     peerDependencies: { yo: '>=1.2.0', 'generator-mocha': '>=0.1.0' },
45 silly install resolved     gitHead: 'ddbc163f38f6313fb368419340e3c42df7d21f06',
45 silly install resolved     bugs: { url: 'https://github.com/yeoman/generator-webapp/issues' },
45 silly install resolved     homepage: 'https://github.com/yeoman/generator-webapp',
45 silly install resolved     _id: 'generator-webapp@0.5.1',
45 silly install resolved     _shasum: '4581cd69d5d0010be777863fb4a887b4a9ddb173',
45 silly install resolved     _from: 'generator-webapp@*',
45 silly install resolved     _npmVersion: '2.1.2',
45 silly install resolved     _nodeVersion: '0.10.32',
45 silly install resolved     _npmUser: { name: 'eddiemonge', email: 'eddie+npm@eddiemonge.com' },
45 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
45 silly install resolved     dist:
45 silly install resolved      { shasum: '4581cd69d5d0010be777863fb4a887b4a9ddb173',
45 silly install resolved        tarball: 'http://registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz' },
45 silly install resolved     directories: {},
45 silly install resolved     _resolved: 'https://registry.npmjs.org/generator-webapp/-/generator-webapp-0.5.1.tgz' } ]
46 info install generator-webapp@0.5.1 into /usr/local/lib
47 info installOne generator-webapp@0.5.1
48 verbose installOne of generator-webapp to /usr/local/lib not in flight; installing
49 warn locking Error: EACCES, open '/Users/olwynlee/.npm/_locks/generator-webapp-9b485c3ef99446bb.lock'
49 warn locking     at Error (native)
49 warn locking  /Users/olwynlee/.npm/_locks/generator-webapp-9b485c3ef99446bb.lock failed { [Error: EACCES, open '/Users/olwynlee/.npm/_locks/generator-webapp-9b485c3ef99446bb.lock']
49 warn locking   errno: -13,
49 warn locking   code: 'EACCES',
49 warn locking   path: '/Users/olwynlee/.npm/_locks/generator-webapp-9b485c3ef99446bb.lock' }
50 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/generator-webapp, which hasn't been locked
50 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
50 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
50 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
50 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
50 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
50 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
50 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
51 verbose cwd /Users/olwynlee
52 error Darwin 13.4.0
53 error argv "node" "/usr/local/bin/npm" "install" "-g" "generator-webapp"
54 error node v0.12.0
55 error npm  v2.5.1
56 error Attempt to unlock /usr/local/lib/node_modules/generator-webapp, which hasn't been locked
57 error If you need help, you may report this error at:
57 error     <http://github.com/npm/npm/issues>
58 verbose exit [ 1, true ]
 ```

**Comment by KenanY** [comment]
@ollers Looks like you don't have permission to delete files in your `~/.npm/_locks` directory. Could you try taking ownership back?:

``` sh
$ sudo chown -R $(whoami) ~/.npm/_locks
```

**Comment by ollers** [comment]
thanks for your prompt response.

I did  try that. I’m on a mac….that option was disabled when I tried to do that. 

thanks,
Olwyn

**Comment by ollers** [comment]
Hi again,

I checked the path and I got this back

Last login: Mon Feb 16 00:06:34 on ttys000
Olwyns-MacBook-Pro:~ olwynlee$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
Olwyns-MacBook-Pro:~ olwynlee$ 

I don’t usually work from the terminal but the above path looks wrong? Can you confirm this and if so how would I update it.

best,
Olwyn

**Comment by ollers** [comment]
..hi I just realised that those colons are delimiters for a list of paths…and the /usr/local/bin path is listed so that’s not the prob.

I opened a new terminal as root user. I’m actually trying to install Yeoman but below are the errors I get..screenshot below. It says everything is alright then the blurb follows. Don’t know if that helps!




best,
Olwyn

**Comment by metasean** [comment]
@KenanY - I've been plagued by "unmet dependency" errors for longer than I care to admit and every other solution was only temporary.  Your suggested ` sudo chown -R $(whoami) ~/.npm/_locks` has solved my issues.  Thank ya, thank ya, thank ya!

**Comment by ollers** [comment]
thanks but unfortunately that’s not working. Same issue/errors.

Olwyn

**Comment by ollers** [comment]
hi….they all pertain to the phonegap module. Does this help?

olwyn

**Comment by metasean** [comment]
@Olwyn - I didn't mean to imply that your problem was resolved.  I just wanted to thank KenanY for slowing down the greying of my hair.

When I ran `echo $PATH` the beginning of the returned value was `/Users/metasean/.nvm/v0.10.36/bin:`  (I also had lots of other stuff in there that probably isn't relevant.)  That should have been installed automatically when node or npm was installed.  For what it's worth, I've started using nvm (https://github.com/creationix/nvm).  I made the switch in part because of the stupid "unmet dependency" problem, and I highly recommend it.

When KenanY suggested you `sudo chown -R $(whoami) ~/.npm/_locks` you responded with "I did try that. I’m on a mac….that option was disabled when I tried to do that. "  What do you mean the "option was disabled"?  If you meant it asked you for a password, that is the expected behavior (that's the `sudo` part of the command - https://en.wikipedia.org/wiki/Sudo) and you just enter your regular OS X user password.

**Comment by ollers** [comment]
sorry I hope I wasn’t curt….it’s really late here!! I really appreciate your help. i was just sending on what ever info I thought might help.

Re when I said the option was disabled. I actually accessed it from the Mac UI…so I right clicked on the folder and selected info…permissions and ownership can be set there…but as I mentioned while I could see this option it was greyed out. I’m set up now as a root user at the terminal so I think that access issues should be circumvented…at least I hope so. 

I noticed as said in prev mail that phone gap appeared to be the problem. I deleted phone gap and dependency messages stopped, which is to be expected as all messages were pertaining to it. How can I reinstall phone gap? I tried using command line but then got other errors. What are the dependency files for phone gap? 

thanks again for your help.

Olwyn

**Comment by ollers** [comment]
…meant to ask…what is phone gap? 

thks,
Ol

**Comment by metasean** [comment]
First, Cordova, PhoneGap, and Ionic all rock!  Hopefully you have fun with them once you're up and running.

PhoneGap (and Ionic) are modules that simplify converting a single-page application into a mobile application (typically Android and iOS applications).  They both require Cordova, which is actually what interacts with the different hardware.  For example, when you want to use a camera in a mobile application, Cordova makes it possible to treat 'camera' as a generic object, even though the camera in my Android phone is a very different camera than in my sister's iPhone.   While PhoneGap and Ionic make it a little bit easier, and a whole lot more graphically consistent to develop cross-platform applications.  

In addition, Cordova requires you work from the command line (cli) and have the development environments for different platforms on your machine.  PhoneGap and Ionic both have cli approaches, but they also have cloud-based methods to do the actual conversion to an application; and let me tell you, from painful personal experience, those cloud-based approaches are WAY, WAY, WAY better than the local approaches!

So back to your npm issues.  npm (aka Node Package Manager [1]) installs packages (aka modules).  When you tell it to "npm install phonegap -g" you're telling it to install the phonegap module globally.  As part of that process, npm will look at the `package.json` file in the phonegap module.  If there are any other npm modules required by phonegap (and there are), it will install them (and look at their package.json and install their required modules, all the way down).  So when you see the "unmet dependency" message, it means one of the npm packages that your parent package wants or needs hasn't been installed.  Sometimes it's just a desirable addition (e.g. it might color your terminal's output to make it more readable) and while you'll loose some functionality, your module will still work.  However, most of the time it really needs the subordinate module and your module won't work without it.

When you see lots of uninstalled dependencies, odds are there is a system-wide problem (e.g. my having the wrong permissions on an important directory).  So, you can't simply avoid phonegap, because the next time you need to install something with npm, you'll likely run into the same problem.

Likewise, if you're doing stuff with npm, then you should get comfortable on the cli (i.e. the 'Terminal" in OS X).  Don't try to manage permissions from the GUI.  It will just frustrate you and waste time (talking from personal experience here - it wasn't worth it, and I wish I had understood that sooner).

So have you tried `$ sudo chown -R $(whoami) ~/.npm/_locks` again, from the cli?  If so, what was the result?

[1]  Long geeky story, but technically it's just "npm" and can mean whatever you want it to mean.  Right now I want it mean Node Package Manager, because that should help explain what's going on under the hood.  For other possible meanings, check out the upper-left corner of https://www.npmjs.com/

**Comment by ollers** [comment]
thank you so much…trying to figure all this stuff out on my ownie here and I just know little bits…this is all very new to me. Thanks for your incredibly patient and generous response. I get what you’re saying and will look further into this but it will have to be tomorrow as my peepers are pulling down the velvet curtains….it’s the wee hours of the night here.

thanks for helping me…it can get quite frustrating until someone…like you…explains stuff. Really appreciate it.

will let you know how I get on. I don’t feel as in the dark as I did. :o)
Olwyn

**Comment by metasean** [comment]
I'm glad to be able to provide some assistance!

Anybody who hasn't been where you are, also hasn't made it any further than you (i.e. programming is full of potholes, speed bumps, detours, and other unmapped regions, if you don't navigate around them, then you won't make it any further down the road).  When you run into an issue, and you can't find the documentation you need, the best thing you can do is ask!  As you progress, just make sure you help others when you can. :wink:

**Comment by ehsalazar** [comment]
We haven’t heard back in a while and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
