### ISSUE TITLE
npm publish - cannot avoid .npmignore in subfolder

### ISSUE THREAD

**Issue by robertdunaway** [npm/npm#7371]
I have a solution where I have 2 .npmignore files. One packages only the bare essentials for creating a project. The second is one directory higher and is intended to include everything beneath it.

What appears to be happening is when publishing at the higher level the lower level .npmignore settings are used. This gives me the wrong package.

Is it possible to specify which .npmignore file to use or at least tell npm to ignore any .npmignore file not in the root directory of where the publish is occurring?

Thanks,
Bob

**Comment by smikes** [comment]
`npm publish` will always go up until it finds a `package.json` file, and then start descending from there; it will honor the `.npmignore` in each directory it descends into.  So if your structure looks like this:

```
A/
   package.json
   .npmignore
   B/
      .npmignore
      files
```

Then when you publish from `A`, it will include `B`, but the files in `B` will be filtered according to `B`'s `.npmignore`.

It sounds like you want to have two different packages which share some files.. can you tell me more about your use case?

**Comment by robertdunaway** [comment]
smikes, thanks...

Yes, that's exactly what's going on and I agree with the functionality of package A respecting package B.  That's obviously a great feature.

In my case I want package A to ignore package B.  My package B has html/js/css that is generic for anyone on any platform to use.  My package A, at the higher level, contains my implementation but using Visual Studio.  So if you aren't a MS guy then you can just use package B.  My buddies are all MS guys using Visual Studio so package A has the Visual Studio solution file and under that the project file.  

I'd like package B to exclude all the Visual Studio files it might run into.  The .npmignore file does this gracefully.

I'd like package A, in the directory above, to include all the Visual Studio files.  The problem is package A only works if I rename package B's .npmignore.

For now I'm just supporting the Visual Studio version but if I figure out how to support both, IE: allow package A to ignore package B's npmignore then I'll support the more generic version of my file.

I hope that makes sense.  I do agree that how things work are how they should work.  NPM is amazing.  I just wish there was a way to override this default behavior in my specific case.

**Comment by smikes** [comment]
Sounds interesting.. I have used MSFT tools, but for C++ usually, not for javascript / web development.

Are you publishing this package to `npm`'s registry, or to a private registry, or are you just packing them up with `npm pack`?

**Comment by robertdunaway** [comment]
Public.  Right now at mashupjs

 

https://www.npmjs.com/package/mashupjs

**Comment by othiym23** [comment]
The key thing to remember about `.npmignore` is that it basically is `.gitignore` for npm packages. The hierarchical behavior @smikes describes is part of git's behavior. There's not really a way to do exactly what you want, because while `.npmignore` files support [overriding excludes with `!`](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) (again like `.gitignore`), they don't allow parent directories to override ignore patterns in child directories. I think the simplest solution to your problem is to split this apart into two packages, or maybe have the VS users clone your GitHub repo and do something clever involving having separate `.gitignore` and `.npmignore` files that do what you want.

Since ignore behavior is a pretty tightly specified corner of `npm` and `fstream-ignore`'s behavior, I'm going to close this issue as something we're not going to change, but I'm happy to help you, if I can, figure out a way to hack around this. Good luck!
