### ISSUE TITLE
equivalent of Composer's --prefer-source

### ISSUE THREAD

**Issue by motin** [npm/npm#7375]
From [Composer's documentation](https://getcomposer.org/doc/03-cli.md#install):

> --prefer-source: If --prefer-source is enabled, composer will install from source if there is one. **This is useful if you want to make a bugfix to a project and get a local git clone of the dependency directly**.

The current workflow to fix bugs in dependencies is to check out your own fork and use npm link, which requires manual tracking of external git repositories (submodules?) and extra hassle for every dependency you'd like to extend/fork/contribute to. 

This option is a huge timesaver for those that regularly extend or fix bugs in existing modules, and by lowering the "cost" of contributing to modules, the npm community can expect to receive more pull requests with smaller bug fixes.

Support for a similar feature appears to be missing in npm according to https://github.com/npm/npm/issues/6700#issuecomment-71302066

Related Stackoverflow question: http://stackoverflow.com/questions/23527393/can-npm-install-the-git-folder-for-dependencies/28559920

**Comment by othiym23** [comment]
This isn't something that makes sense for npm, for the same reasons I outlined in https://github.com/npm/npm/issues/6700#issuecomment-74788010.

Another solution to this problem is to fork to a repository on your personal organization in GitHub, and then depend on that from your package. You still have to `npm link` the modules locally if you want to be editing all of them live simultaneously, but my experience with npm (which has more than a few dependencies like this) is that editing many of the pieces simultaneously ends up being somewhat error-prone. It's a lot easier (for me, at least) to fix something, publish it (or, if you're using GitHub dependencies, to push to your branch), and then `npm install` again into the consuming application.

In general, though, drawing a clear distinction between npm and git's responsibilities makes things simpler over the long term, if not always easier in the short term.

Thanks for the thoughtful problem statement!

**Comment by motin** [comment]
Please consider re-opening, since there seems to be some misunderstandings going on. 

First of all, of course npm is not meant to be a layer on top of (or a replacement for) Git. Neither is Composer. The --prefer-source option has nothing to do with git submodules or executing any new git commands, nor is it git-specific in any other way (Composer and npm support many version control systems)

**The only difference to the ordinary package installation routine would be not to delete the .git (or corresponding for other version control systems) folder.**

> Another solution to this problem is to fork to a repository on your personal organization in GitHub, and then depend on that from your package. You still have to npm link the modules locally if you want to be editing all of them live simultaneously, but my experience with npm (which has more than a few dependencies like this) is that editing many of the pieces simultaneously ends up being somewhat error-prone. It's a lot easier (for me, at least) to fix something, publish it (or, if you're using GitHub dependencies, to push to your branch), and then npm install again into the consuming application.

I'd say I'm diametrically opposed to everything in this paragraph :)

Depending on a repository in your package.json is of course part of a workflow, but only done AFTER the fix has been identified and pushed to one's fork. The --prefer-source helps out in the process BEFORE this. Linking each module that one wants to fiddle with is not a solution, it is a workaround to cope with the face that --prefer-source is missing. 

Editing them all live (locally) simultaneously is the most efficient and least error-prone way of debugging and fixing tough bugs, since:

1. Editing the live actual files that are used when executing module code logic allows one to run and verify that all issues are resolved
2. When editing files in non-versioned folders, it is hard to revert to a pristine state. 
3. Also, when you find the bug and verified that the fix works, you need to do the following before being able to commit the fix: A. find the source git repository, B. clone the source git repository, C. find the exact commit matching the code you had installed in node_modules, D. copy the fix manually over to the versioned directory, E. npm link the versioned directory, F. try again running the code to see that it still works. In comparison, if the .git folder was already there and the local live directory in node_modules then one could immediately push the fix to a fork

Furthermore, there is also the scenario where your project is written in a module fashion and thus your team manages many npm modules actively for the sake of the project. All the developers on the team needs to resort to something similar to git submodules for each npm module and manually having to npm link these submodules upon each project checkout. Sure, that can be automated with shell scripts, but there is extra hassle every time when adding new dependencies that your team needs to contribute to. 

With --prefer-source, the project's developers simply install the dependencies and are directly available to work on the modules that the project depend on.

**Comment by othiym23** [comment]
It's not a matter of _removing_ version control metadata, though, because by the time the package gets put into `node_modules`, the `.git` directory is already gone. If you use `npm install` to put a git repository into your application, what's being installed is a package pulled from the local npm cache. Cached packages coming from git repos look pretty much the same as packages pulled down from a registry, and have been run through the same packing and filtering process as registry packages. So while there is also a git remote for each dependency that lives inside the npm cache, that clone is never used directly for installation. Having every dependency being run through the same packing, caching, and installation process is important for ensuring a consistent developer experience.

Thank you for taking the time to more thoroughly explain how you want to use this feature, and you're right that I didn't completely understand your use case before. Given the preceding paragraph, though, I hope it's a little clearer why this is a difficult feature to add. If npm were doing a simple `git clone` and then pruning extra files, this would be easy enough to change. However, the options that are open now are:

1. Special-case installing git dependencies so they bypass the cache and are just plain clones. This seems to be the most direct implementation of what you're asking for, but it's also the one I like the least from an implementer's point of view, because it introduces edge cases and additional conditional logic into the installer code.
2. Use git submodules. There was once an `npm submodule` command to assist in this process, but it never worked properly and nobody used it, so we got rid of it. Git submodules are unwieldy and error-prone, and you've already enumerated some of their other problems.
3. Put everything into one big repository and just publish the individual packages directly from that tree. This is more or less how Google does things, and while it's not very flexible, it can be made to work.
4. Use `npm link` a lot. This already works, but is also sort of difficult to set up and maintain.
5. Have all your modules checked out separately and independently manage them, periodically publishing and installing them where you're depending on them. This also already works, and is actually (believe it or not) how we manage the npm CLI's own development.

So the latter 4 are approaches that already work without making any changes to npm, necessarily and one that would require significant changes and would make maitaining npm more complex. Have I overlooked anything? Am I being obtuse about what it is you're trying to do?

**Comment by motin** [comment]
@othiym23 Great response! Thanks!

What about:

6. Install all packages as usually first, then (post-install) check if "--prefer-source" is present. If so: enumerate the package.json looking for clonable dependencies, clone them to a temporary directory and then move the version control metadata to the existing directories under node_modules.

This would:
A. have zero impact on any npm command that does not have "--prefer-source" present
B. ensure that the files under node_modules are identical to the ones produced by an ordinary npm install
C. be a minor addition to npm's codebase
D. achieve the objectives of this feature request

**Comment by othiym23** [comment]
That doesn't look like a minor amount of work to me, and conflicts directly with other features of npm (like npm's refusal to stomp on packages that _do_ have `.git` directories in them when running un/installs. It sounds like a significant amount of effort to support an edge case that is arguably (literally, as in we've been arguing about it) not a good idea.

I've been thinking about this discussion a lot, and am increasingly coming down on the side of having multiple `.git` dependencies under `node_modules` being a bad idea on its own merits. I know it's convenient, but the convenience brings with a lot of complications and sources of confusion.

**Comment by schmunk42** [comment]
:+1: I'd also like to see an equivalent of `--prefer-source` btw.

**Comment by joshribakoff** [comment]
+1 This seems really simple, not sure whats so complicated. If I pass this flag thats being proposed, npm should just do a git checkout of the repo instead of pulling from it's regular cache, if possible for each package.

This allows me to fix a bug in my "library" repository within the context of the depending project. This is also true of "npm link" as suggested above, with the one caveat that I'm stuck with a global repo. The way composer does it, its not global. In some situations a developer may want it to be global, in other situations a developer will want it not global.

> Have all your modules checked out separately and independently manage them, periodically publishing and installing them where you're depending on them. 

I've tried this, and it can become cumbersome to make a change to the library repo, commit & push it, then switch back over to the depending project & pull those changes in with npm to test them. If you find that the changes did not work within the context of the depending project, you have to repeat this making multiple commits. Not all projects have extensive automated tests making this process tenable..

**Comment by flancer64** [comment]
This is my PHP project in PhpStorm IDE. `.../vendor/...` folder for composer is like a `.../node_modules/...` folder for npm. All my modules are under `.../vendor/praxigento/`. **mobi_app_santegra** is a head module, it contains `composer.json` (deployment descriptor) and it is mounted twice:

- (dark green) as root folder for the project (with composer.json and other deployment scripts);
- (green) as project's module (with PHP sources)

I have about 10 submodules in my project and I can commit all changes in all sub-modules at once using PhpStorm. Because all sub-modules are mounted with `.git` folder inside. Because composer has `--prefer-source` option.

![image](https://cloud.githubusercontent.com/assets/5052385/23787005/977ba946-0578-11e7-8c39-c7e0fe4cdb2d.png)
