### ISSUE TITLE
New version of git (2.3.0) allows terminal prompts to be suppressed

### ISSUE THREAD

**Issue by smikes** [npm/npm#7377]
Ref the github analysis of the git announcement: <https://github.com/blog/1957-git-2-3-has-been-released>

> When Git needs a password (e.g., to connect to a remote repository over http), it uses the credential subsystem to query any helpers (like the OS X Keychain helper), and then finally prompts the user on the terminal. When Git is run from an automated process like a cron job, there is usually no terminal available and Git will skip the prompt. However, if there is a terminal available, Git may hang forever, waiting for the user to type something. Scripts which do not expect user input can now set GIT_TERMINAL_PROMPT=0 in the environment to avoid this behavior.

`npm` can set `GIT_TERMINAL_PROMPT=0` in the environment of git processes, which will help address racy prompting for `git` credentials, as seen in <https://github.com/npm/npm/issues/5227> 

Patch desired?  It would be a slow fix, since it requires the user to have an updated `git`; and the race conflicts may be solved by `npm@3` independently, so feel free to close if this is not useful.

**Comment by othiym23** [comment]
> `npm` can set `GIT_TERMINAL_PROMPT=0` in the environment of git processes, which will help address racy prompting for `git` credentials, as seen in npm/npm#5227

It doesn't so much address the problem as eliminate the ability for people to answer the prompts altogether. This might be helpful in some circumstances, but would probably also be confounding to anyone who's been using npm for a while and is _expecting_ to be prompted for credentials.

> the race conflicts may be solved by `npm@3` independently

Regardless of whether `npm@3` fixes the race conditions, if there are bugs around dealing with git, they _must_ be addressed independently of the version of git installed, because it's simply not tenable to prescribe what version of git npm users must run. The latest supported version of git for Windows is 1.9, for instance. I doubt most Linux distributions are going to bundle a version of git that new anytime soon. That mostly leaves Homebrew users, and while there are a lot of us, I think relatively few production environments (where this issue is likeliest to be severe) are going to have access to new git for a while. 

Viewed from that perspective, that says that 1. we need to nail down / fix those race conditions and 2. there's not a super compelling use case for using this feature left over. I leave to your judgment whether you think this leaves room for creating a patch, but right now it seems like a decent amount of work for a relatively marginal improvement.
