### ISSUE TITLE
Feature Request: setting a start directory

### ISSUE THREAD

**Issue by andrepadez** [npm/npm#7379]
I want to have a library, with the following structure:

```
- library
   - package.json
   - src
       - feature1
          - index.js
       - feature 2
          - index.js
```

and require feature1 with 
```javascript
var feature1 = require('library/feature1');
```
Is there a way, or could it be implemented, to define in package.json, something like:
```
{
   "main": "./src/"
}
```
because, right now, i have my features directories all in the root of the package, which i think is not ideal for organization.

Thanks

**Comment by othiym23** [comment]
There is a [`main`](https://docs.npmjs.com/files/package.json#main) field in `package.json`, but as you can see if you follow that link, it does something slightly different from what you want – it only points to the main entry point for a package when calling `require('<package>'), rather than a relative root. Unfortunately, the functionality you describe is not something that npm itself can provide, as npm doesn't define the details of the Node module loader, and the module loader has a frozen API. As such, I'm going to close this issue, because this isn't something that npm could change even if it wanted to.
