### ISSUE TITLE
install -g failures don't clean up after themselves

### ISSUE THREAD

**Issue by scurry** [npm/npm#7380]
Here is the issue:

When npm install -g is run several things happen (filtering out not relevant steps):
1) If the package is not in cache it is downloaded from the 'net and cached
2) Lock file is generated until install completes
3) package is installed
4) lock file is removed and it is done.

The issue is if step 3 fails (for whatever reason), then the lock file is not removed nor is the cache cleaned up for the package that fails to install.   This leads to issues on a shared instance (CI server), because that lock file still exists and future builds will fail until it is cleaned up.

Here is my take on the 'bug':
* I think npm install should treat each step in the process as part of a "transaction" that should be rolled back if there is a failure.   Primarily, I think the lock file should be cleaned up after the install process ends in failure so that it can be retried and possibly succeed.

I did try to find a solution to our dilemma such as suggestions in this good discussion(https://github.com/npm/npm/issues/6043) related to this but to no avail.

Please advise on any plans to address this type of issue with the latest npm.

**Comment by othiym23** [comment]
Good news! You have pretty much exactly described the motivation and process to be followed by the multi-stage installer that is to be the core of `npm@3`, currently under development on the `multi-stage` branch. Because this work has its [own milestone](https://github.com/npm/npm/milestones/multi-stage%20install), I'm going to close this issue as a duplicate, but keep an eye out for the first beta release (`npm@3.0.0`), which will be happening soon.

With that said, lockfiles are advisory, and npm will eventually override stale locks and the build will succeed, admittedly maybe not without timing out and failing a few times first. And it doesn't really make sense to roll back caching, as the metadata and tarballs are already written to the cache atomically in newer versions (`npm@2.1` and up) of npm.

But overall, the `multi-stage` install is a big step towards having transactional installs, and it is our (eventual) goal to make the install process fully transactional.
