### ISSUE TITLE
Error attempting to install spark-cli

### ISSUE THREAD

**Issue by Voltezk** [npm/npm#7387]
Hi all,

I've been trying to download this package for quite a while, been looking everywhere for answers of problems of problems, trying to resolve this issue bit by bit, but I just couldn't get it to work in the end.

when I run :

npm install -g spark-cli

in the command prompt, I get :

![image](https://cloud.githubusercontent.com/assets/11069639/6261834/62d15a86-b85b-11e4-97b0-6525799347cf.png)

![image](https://cloud.githubusercontent.com/assets/11069639/6261842/8ec25a50-b85b-11e4-9e7c-1f3deae75712.png)

![image](https://cloud.githubusercontent.com/assets/11069639/6261846/a19c8c0e-b85b-11e4-922c-c5826a28018d.png)

I have also tried running: 

node-gyp configure
node-gyp build

but both gave me errors.. Maybe thats part of the issue?

Any help would be greatly appreciated!

**Comment by othiym23** [comment]
There are a couple of things going on here:

1. `npm@1.4.9` is pretty old. The version bundled with Node 0.12 is `npm@2.5.1`, and it has a large number of fixes pertinent to Windows support. I'm not sure how you upgraded to Node 0.12, but if you use the official installer, and make sure that the version of npm bundled with it is the first on your `%PATH%`, you should automatically get an upgrade to the latest stable npm. 
2. Because `node-serialport` has a native component, you should be using version 1.5.0, which includes fixes to support the version of V8 bundled with Node 0.12. See also spark/spark-cli#136 for details on using spark-cli on Windows (and maybe point out that this is something you need to).

Closing as resolved (and also not really due to a problem with npm, although it's sort of tough to tell that from the error output). Good luck!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
