### ISSUE TITLE
npm ERR! Error: ENOENT, open '/home/...

### ISSUE THREAD

**Issue by bcbarad** [npm/npm#7388]
when i am running the npm run protactor conf.js i am getting this error

**Comment by smikes** [comment]
It looks like you were planning to attach an error log, but didn't.

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28, the version shipped with many older versions of `node`. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
