### ISSUE TITLE
publish with force option ignores prepublish script exit code

### ISSUE THREAD

**Issue by nfleury** [npm/npm#7394]
With version of npm: 1.4.28

package.json:
```json
  "scripts": {
    "prepublish":"exit 1;",
  },
```
Running:
- npm publish : exits 
- npm publish -f: ignores the exit code and does publish the package, is this a normal behaviour ?

**Comment by othiym23** [comment]
It is absolutely expected behavior. `-f` takes no prisoners. That's why it says, "I hope you know what you're doing," when you use it.

**Comment by nfleury** [comment]
Thanks for the quick answer, but just to clarify:

I'm using the npm publish -f option just to deal with "snapshot versions" for packages that are not yet released

I am aware that using this option is a bad thing for released projects.

The thing is that I use the prepublish script to execute some tests and if something goes wrong: I expect it to stop.

You are telling me that the -f also means "ignore the script exit code" ?

In the scripts documentation https://docs.npmjs.com/misc/scripts, it is mentionned that:

 "If the script exits with a code other than 0, then this will abort the process."

If this is a wanted behaviour, maybe it should mention that too.

**Comment by othiym23** [comment]
`-f` / `--force` is a 12-pound sledgehammer of an option. It is inherently unsafe, and its consequences are pervasive and frequently dire. Documenting everywhere it has an impact would be quite a job, and would mostly just serve to reinforce that it should never, ever be used for production tasks. I am curious as to how it became part of your prepublish workflow, though.

**Comment by nfleury** [comment]
As I mentionned, I don't use this option to publish released packages for production.

It's for sure an unsafe option for production but its a useful one (and the only way I found) to share packages that are not yet released in a development iteration ...

I have the following development workflow:

Let say that I have a project still in development, then I publish it as 0.0.1-dev in a private repository. Every change for this development iteration will be published with npm publish -f (to force override the previous snapshot) in the same version: 0.0.1-dev . 

When this development iteration is complete, then I would publish a 0.0.1 version (only once with npm publish)

If someone wants to use this 0.0.1-dev development version he just have to include it in his package.json has a normal dependecy.

Otherwise how would one do ? He would have to:

- git checkout the project
- npm install it
- npm link 
- then use it

npm publish -f for development versions allows to simplify this process.

The prepublish script is used to ensure that it is ok to publish by executing some tests before.

But with this behaviour I cannot ensure I am publishing a working package in my development phase ... 

I want to force the publication itself without ignoring the prepublish exit code ... 

Maybe I am misusing this option, and should rather do a feature request to deal with this workflow with npm :)

Anyway, thanks  !

**Comment by othiym23** [comment]
What's the advantage of publishing to one prerelease version rather than using `npm version pre`? I get that it's easier for people to include as a dependency, but it seems kind of fraught to me.

What about using private GitHub repositories as dependencies? Then people can just depend on a branch until it's time for release.

From a workflow point of view, these aren't necessarily superior to what you're trying to do, but neither approach requires you to use `-f`, which feels very much like overkill.

On the CLI team, we just publish using regular semver, and put out new patch releases as needed when we run into issues while testing. We tried to use a prerelease workflow for a while, but found it awkward and unwieldy in practice. YMMV, but it is definitely possible to do things very much like what you're doing without resorting to `npm -f`.
