### ISSUE TITLE
Node Error in Untrusted Sources

### ISSUE THREAD

**Issue by ArcanaMagus** [npm/npm#7403]
Once I run npm within the node runtime in Kali Linux( intendedd for security testing purposes) I find this error :-1: 
http GET https://registry.npmjs.org/learnyournode
ERR! Error: SSL Error: CERT_UNTRUSTED
ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_mod$
ERR!     at ClientRequest.g (events.js:156:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:$
ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1288:20)
ERR!     at CleartextStream._push (tls.js:375:27)
ERR!     at SecurePair.cycle (tls.js:734:20)
ERR!     at EncryptedStream.write (tls.js:130:13)
ERR!     at Socket.ondata (stream.js:38:26)
ERR! You may report this log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR!
ERR! System Linux 3.14-kali1-amd64

Could this be the the operating system blocking excessively?

**Comment by othiym23** [comment]
I'm going to guess that this is because, as in #7401, you are running an obsolete version of npm (even though you cut off the piece of the error output that includes the Node and npm versions). Versions of npm prior to 1.4 used a self-signed certificate to talk to the registry. In 1.4 and higher, npm moved to using a certificate using a trusted root global cert, and so old versions of the CLI can no longer establish a secure connection. Once you upgrade to a recent Node / npm, this error will go away.

Sorry for the inconvenience, but it sounds like you may need to either build a newer Node from source or find a source for packages for your distribution that has a supported version of the runtime. There's not a lot we can do about it otherwise.
