### ISSUE TITLE
ERR! cb() never called! bower install fails

### ISSUE THREAD

**Issue by cliren** [npm/npm#7409]
I followed various issue threads on this, tried different versions of node and npm and still get the same issue. I am using OSX 10.10.2. This halted my dev work, any help appreciated!

npm info linkStuff source-map@0.1.43
npm info install source-map@0.1.43
npm info postinstall source-map@0.1.43
npm info build /Users/me/.node/lib/node_modules/bower/node_modules/handlebars/node_modules/uglify-js
npm info linkStuff uglify-js@2.3.6
npm info install uglify-js@2.3.6
npm info postinstall uglify-js@2.3.6
npm info build /Users/me/.node/lib/node_modules/bower/node_modules/handlebars
npm info linkStuff handlebars@2.0.0
npm info install handlebars@2.0.0
npm info postinstall handlebars@2.0.0
npm ERR! cb() never called!

**Comment by othiym23** [comment]
Because `cb() never called` is a generic notice that something *didn't* happen (as in, something somewhere in npm's internals did not call a function), context is key in figuring out what's going on. Things like what version of Node you're running, what version of npm you were running, what you were trying to do, and things like any relevant `package.json` and `npm-shrinkwrap.json` files (if they're safe to share). As it is, right now I want to help, but I don't know enough about what's going on with your install to help.

**Comment by cliren** [comment]
Node - v0.10.32
npm - 1.4.28

solve the issue by upgrading to the following versions:

Node - v1.3.0
npm - 2.5.1

@othiym23 Thanks for looking into it!

**Comment by othiym23** [comment]
Closing as resolved.
