### ISSUE TITLE
Mixed up file permissions of cache folder when using sudo

### ISSUE THREAD

**Issue by akloeber** [npm/npm#7427]
I try to install a module globally via sudo invoked as user `deploy`:

    deploy$ sudo -i npm install -g some-module

This populates the cache directory at `/root/.npm` but with owner deploy/deploy instead of root/root. Contradictorily inside there is a `_locks` subfolder with owner root/root.

Content of `/root/.npmrc`:

    prefix=/usr/local
    cache=/root/.npm
    user=root
    group=root

__Environment__:
npm v2.6.0
node v0.10.25
Ubuntu 14.04.1 LTS

**Comment by smikes** [comment]
Can you tell me more about the problem?  `npm` is trying to avoid running package scripts as `root`, and tries to make cache objects be owned by the non-sudo user, which is probably how you wind up with cache entries owned by `deploy`.

What happens if you run `npm` from a root shell?

```
sudo -s
npm install -g some-module
```

Alternatively, can you make the install target (/usr/local/node_modules) writable by your user `deploy`?

**Comment by othiym23** [comment]
@akloeber You have at least a couple options here:

1. Look at [`--unsafe-perm`](https://docs.npmjs.com/misc/config#unsafe-perm). It may be exactly what you're looking for, but since I haven't played around with `sudo -i <command> <user>` for a while, it may run counter to our assumptions about how people use npm and sudo together.
2. Create a `deploy` user and deploy from that user's home directory. npm assumes that if you're using sudo, you're going to have an effective userid of `root` and not some other user. This may or may not be what you want.

If neither of those work for you, come back and let us know, and we'll see if we can create a bug that encapsulates the problem, or maybe come up with a solution that works better with your constraints and npm's expected workflows.

**Comment by akloeber** [comment]
@smikes If I run it from a root shell the way you suggested the result is similar. `/home/deploy/.npm`  gets created (instead of `/root/.npm`) with user `deploy:deploy` and the `/root/.npm/_locks` folder inside with `root:root`. The only difference is the location and that the module itself is installed at `/usr/lib/node_modules` instead of `/usr/local/lib/node_modules`. So `/root/.npmrc` is ignored which I think is because after `sudo -s` `HOME` is still `/home/deploy`. When using `sudo -i` as I do `HOME` changes to `/root`.

On Ubuntu `/usr/local/lib/node_modules` is the directory where global modules should be stored (not only for node, but also for python or ruby) and it is only writable by root which should not be changed for security reasons.

@othiym23 Just to clarify: I do not use `sudo` to run npm as user `deploy` but the other way around: I use it when logged in as user `deploy` (who has sudo rights) to get `root` privileges that I need in order to install global modules at `/usr/local/lib/node_modules` which works fine despite the confusing and mixed-up file permissions beneath `root/.npm`.

I do not exactly understand what `--unsafe-perm` is for but if I run `deploy$ sudo -i npm install -g lodash --unsafe-perm` instead the result is the same as without this option.

**Comment by othiym23** [comment]
OK. I understand what you're trying to do better. npm tries to work with sudo most of the time, by reading the original user and group IDs from `SUDO_UID` and `SUDO_GID` and using those values to create the initial cache directory and configuration file, which is *not* what you want in this case. To get around this, you want to reset the environment completely, by using this incantation beloved by sysadmins since sudo got standardized in the mid-90s:

```
sudo su - sh -c "npm install -g some-module"
```

Once you delete `/root/.npm` and `/root/.npmrc` (if the latter exists), and start using the above command, npm will create a new `/root/.npm` owned by root, and everything in that cache will be owned by root.

An alternative (that is arguably safer) is to ensure you're using the latest npm (`npm@2.6.0`, and `npm@2.6.1` in a few hourse), and stop using `-i` when invoking sudo to run npm. Then npm will use `deploy`'s cache, but will set the permissions there appropriately such that the `deploy` user owns everything under that root. Any time something under `$HOME/.npm` ends up being owned by root after running `sudo npm`, that's a bug, and should be filed as such so we can make npm not do that.

Let me know what you end up doing. I'm going to close this as resolved now, but we can reopen if it turns out there's some wrinkle in here I've overlooked. Good luck!

**Comment by akloeber** [comment]
Well unfortunately `deploy$ sudo su - sh -c "npm install -g lodash"` gives `No passwd entry for user 'sh'`.

If I use `sudo npm install -g lodash` with npm@2.6.0 the result is still similar: The cache gets populated at `/home/deploy/.npm` with files owned by `deploy:deploy` which is fine but the `_locks` folder inside is still owned by `root:root`. Everything would be correct if `_locks` would be owned by `deploy:deploy` too.
