### ISSUE TITLE
`reset package` affordance on npm website (spin off of #4701)

### ISSUE THREAD

**Issue by smikes** [npm/npm#7428]
https://github.com/npm/npm/issues/4701#issuecomment-35455502

> i keep having problems when unpublishing packages.... i was wondering if it would be possible to add some kind of removal tool on npmjs.org... some way of reseting a repository to version 0.0.0 or some way of patching packages without bumping versions... that would be really nice... 

This sounds to me like a feature request that would allow a logged-in user to remove a package they own from the `npm` registry, is that right?  

I think that probably would need to be a feature request against `npm-registry-couchapp`, but I also suspect that it's a feature that would not be implemented, since one of the goals of the `npm` registry is that `package@version` is in one of these states { never-published, valid, unpublished }, and that you can't go from "unpublished" back to "valid". 

The reasoning, I believe, is that once a package is published, then others are free to depend on it.  If a version remains, then new installs of its dependents succeed.  If a version is unpublished, then new installs of its dependents fail noisily.  But if a new version is put in place, it may have different behavior than the previous one, and new installs of packages that depend on it will appear to succeed but be silently incorrect.

In the worst case scenario, a package could be replaced by an attacker seeking to inject a vulnerability into a particular application.

That's based on my incomplete understanding of the registry's goals, but I will involve some other people who actually make decisions around here.   /cc @seldo  ;-)

**Comment by othiym23** [comment]
Over time, the registry is moving in the direction of immutability, with changes to data after it's been published being very rare exceptional situations. It is absolutely intentional that a package can never have its version number be reset, or a new version of a package published over an old version, even if that package has been completely unpublished. There are two reasons for this behavior that I belieave are sufficient to justify this restriction:

1. For clients, if somebody has an ancient package that depends on something that's been unpublished, and suddenly it can be satisfied with a new, probably completely unrelated package with a matching version, just about anything could happen, and most of those things would be very undesirable.
2. Being able to assume that the underlying source of truth for the registry is immutable greatly simplifies the whole registry architecture. It's no longer necessary to deal with cache invalidation on packages, so the CDN can have very long TTLs set on packages, limiting bandwidth on the package servers, and liveness checks on the back end need to be run much less frequently (i.e. never).

There are many other reasons, large and small, behind this design decision. It's occasionally inconvenient for developers, but the tradeoff is that it makes for a much more robust registry for everyone.
