### ISSUE TITLE
npm install --lookup

### ISSUE THREAD

**Issue by StreetStrider** [npm/npm#7434]
Hello. Here's the idea. To implement option `--lookup` for `npm install` which will check deps accessibility and do not install its if deps is already accessible (from outer `node_modules`).

**Why this can be helpful?** This is good for developers. Every developer has it's own list of preferenced packages so they can just put them in `~/node_modules` (or globally) and use `npm install --lookup` in every local project. npm partially solves this problem by caching, but it copies packages to local `node_modules` anyway.

For now I'm using this technique manually: I put deps in `package.json` but do not install them if I remember they in `~/node_modules`. I also do not install my own packages to have bleeding edge of them. This approach is not perfect, because when I've just clone some project, I can't do it with just one `npm install`, I need to either manually select what I'm going to install, or run single `npm install` which will install all, including what I want to keep «nonlocal».

**npm link?** I think the closest analogue for this request is npm link, but `npm link` has only two levels: local and global. By design `npm install --lookup` should look for every outside `node_modules` to follow hierarchical logic of `require`-ing. This is also similar to `npm dedupe` but on installing phase.

**caveats** The only caveat I can see is `--lookup` will create not fully-sealed package. So if depencency from higher level will be removed the package will stop working. But I think this is out of `--lookup` scope: it's for devs use. Maybe `npm install --lookup --production` should fail with some warning.

I've searched by some keywords related to this request, but found nothing. Maybe this idea have already been discussed, but with another keyword. In this case, sorry for duplicate.

**Comment by othiym23** [comment]
Thanks for putting this together!

Let me see if I can recast the thrust of your feature request in terms of the problem it's trying to solve: you want to minimize the amount of disk space occupied by your npm workspace, and so want to reduce the number of superfluous package installs.

This is one of the problems that `npm link` is intended to solve. If I'm reading your objection correctly, you  don't like this approach because it requires manual tracking of which things can be linked. This is true, and in doing so it preserves one of npm's important design principles: every package or application should be self-contained.

It's true that the Node module resolution algorithm makes it easy to set up a hierarchy of `node_modules` folders, but _npm_ treats the directory containing the `package.json` file as the top of the module tree. This is important, because it helps ensure that the local version of the code will remain deployable. Adding the ability to have npm-managed packages depend on modules outside the scope of the current package would either break or require significant changes be made to `npm ls`, `npm shrinkwrap`, and other commands.

However, it's pretty easy to write something that would let you do this yourself. Here's a start at something that you could build into a CLI of your own to make dealing with this stuff easier:

```javascript
var assert = require("assert")

var toCheck = process.argv[2]
assert(process.argv[2], "must include module name to check")

try {
  var pkg = require("./package.json")
  if (pkg.sharedDependencies && !pkg.sharedDependencies[toCheck]) {
    console.error("WARN:", toCheck, "not found in shared dependencies")
  }
}
catch (e) {
  console.error("WARN: not checking sharedDependencies because package.json not found")
}

try {
  console.log(require.resolve(toCheck))
}
catch (e) {
  console.error("package not found")
}
```

That just sees if it can find the package in the shared environment, and optionally checks to see if the package is already in a hypothetical `sharedDependencies` section in `package.json`, but it could be extended to only call `npm install` when the module isn't found, or isn't in `sharedDependencies`.

However, because this introduces a new complication and chunk of management overhead to npm itself, and because npm is intended to be a **package** manager, and not a general-purpose code manager, I don't think it makes sense to put in npm proper. It seems entirely appropriate to put in a third-party utility, though. Thanks again for your time!

**Comment by StreetStrider** [comment]
Thanks for the answer. And more, I'm agree with your argumentation. This task can really be solved in 3rd-party solution, it will be better if I build it for my own needs.
