### ISSUE TITLE
Documentation bug in `npm run-script`

### ISSUE THREAD

**Issue by smikes** [npm/npm#7440]
See <https://stackoverflow.com/questions/28690793/how-can-i-run-a-script-from-an-already-installed-npm-package>

Current documentation:
>DESCRIPTION
     This  runs an arbitrary command from a package's "scripts" object.  If no package name is provided, it will search for a package.json in the current folder
       and use its "scripts" object.

Current code for run-script no longer supports the 4-argument version (`npm run-script <package> <script>`)

Some possible approaches:
1. fix doc bug by removing reference to package name

2. restore `npm run <pkg> <script>` as alternative to `npm run <script>`  Downsides: probably creates problems with passing args to scripts, other `npm run` functionality

3. alternatives?

**Comment by KenanY** [comment]
:+1: to fixing the docs. I think the `npm explore` method is good enough for whomever might have been relying on the old `npm run-script` behavior, and if anything it adds another use-case for `npm explore` (which I've never used).

From https://github.com/npm/npm/pull/5518#issuecomment-46787930, bringing back the old syntax seems non-trivial to me.

**Comment by othiym23** [comment]
The wording in there was pretty confusing, so I reworked the whole thing and landed it as df1bbd9. The new behavior is the primary reason for the npm-semver bump, because we decided the new behavior was overall more useful than the old. I do think there's probably some scope to make `npm explore` slightly more generic, and I also think that this is yet another use case for `npm-exec`, should that ever come into existence. Either way, the proximate problem, the bad docs, have been fixed. Thanks for filing this, Sam!
