### ISSUE TITLE
Peer dependencies of namespaced packages installed wrong

### ISSUE THREAD

**Issue by myndzi** [npm/npm#7454]
When installing a package with a namespace, e.g. @foo/mymodule, if it has a peer dependency that doesn't exist, that dependency is installed automatically. However, it is installed into ./node_modules/node_modules/package instead of ./node_modules/package, giving a directory tree like this:

    package.json
    node_modules
        @foo
            mymodule
                package.json
        node_modules
            peer
                package.json

**Comment by smikes** [comment]
Thanks for the bug report.

**Comment by othiym23** [comment]
This is an important bug to fix, because scopes are going to get much more important in the near future due to the advent of the npm registry's support for private modules (which all must be scoped), but `npm@3` is also coming very soon, and it brings with it a change where `peerDependencies` are never automatically installed. Still, this needs to be fixed for `npm@2` due to the fact that `npm@2` and `npm@3` are going to coexist for a while.
