### ISSUE TITLE
Installed nodeJS and then trying to install Karma It is showing some error

### ISSUE THREAD

**Issue by kparida** [npm/npm#7466]
```
C:\user\kaprida>cd\Demo\angular-seed-master
C:\Demo\angular-seed-master>npm install –g karma
npm ERR! Window_NT 6.1.7601
npm ERR argv”C:\\Program Filed\\node.js\\\\node.exe” “C:\\Program Files\\node.js
\\node_modules\\npm\\bin\\npm-cli.js” ”installs” “-g” “karma”
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code CERT_UNTRUSTED

npm ERR! certificate not trusted
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!    <http://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@kparida Are you behind a proxy by any chance?

**Comment by kparida** [comment]
No proxy is there...

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
