### ISSUE TITLE
Error: Failed to replace env in config: ${APPDATA}

### ISSUE THREAD

**Issue by songotan** [npm/npm#7468]
```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\nodejs\\\\node.exe',
1 verbose cli   'E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink E:\nodejs\\node.exe
5 verbose stack Error: Failed to replace env in config: ${APPDATA}
5 verbose stack     at E:\nodejs\node_modules\npm\lib\config\core.js:419:13
5 verbose stack     at String.replace (native)
5 verbose stack     at envReplace (E:\nodejs\node_modules\npm\lib\config\core.js:414:12)
5 verbose stack     at parseField (E:\nodejs\node_modules\npm\lib\config\core.js:390:7)
5 verbose stack     at E:\nodejs\node_modules\npm\lib\config\core.js:328:17
5 verbose stack     at Array.forEach (native)
5 verbose stack     at Conf.add (E:\nodejs\node_modules\npm\lib\config\core.js:327:23)
5 verbose stack     at ConfigChain.addString (E:\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
5 verbose stack     at Conf.<anonymous> (E:\nodejs\node_modules\npm\lib\config\core.js:315:10)
5 verbose stack     at fs.js:336:14
6 verbose cwd C:\Users\yylc099
7 error Windows_NT 6.1.7601
8 error argv "E:\\nodejs\\\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
9 error node v0.12.0
10 error npm  v2.5.1
11 error Failed to replace env in config: ${APPDATA}
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like you are following a tutorial of some sort that has instructed you to put `${APPDATA}` in your npm config.  This tells `npm` to look for the environment variable `APPDATA`; when `npm` can't find it, it reports an error.

You may need to define the environment variable `APPDATA` (consult your operating system documentation for how to do this).

Also I note that you are trying to run `npm` without giving it a subcommand such as `npm install` or `npm ls`.  You can find documentation on how to use `npm` here: https://docs.npmjs.com/getting-started/what-is-npm

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by DedrickEnc** [comment]
I just created a environment variable called APPDATA with the value like this : 

variable : APPDATA
value : C:\Users\my_user_name\AppData\Roaming\npm;npm

**Comment by AlastairTaft** [comment]
I'm seeing this issue when I run `sudo npm link` on my Mac. I have the NPM_TOKEN set in my .bash_profile file though. And even after I run `export NPM_TOKEN=********` it still errors. Oh and my local project .npmrc file looks liked this

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```
npm version is 2.14.4

**Comment by darthtrevino** [comment]
@AlastairTaft I was able to get around this by changing my .npmrc to `//registry.npmjs.org/:_authToken=$NPM_TOKEN`

**Comment by kevinSuttle** [comment]
This causes problems from time to time. 
https://github.com/npm/npm/blob/master/lib/config/core.js#L408

**Comment by deadlyicon** [comment]
I have this problem on `v6.2.2`

**Comment by Scoutski** [comment]
+1

**Comment by jakeNiemiec** [comment]
`rm -f ./.npmrc` worked for me.
