### ISSUE TITLE
npm ERR! code EBADF

### ISSUE THREAD

**Issue by DavidA2014** [npm/npm#7472]
I got this error when attempting to download the project-manager package, using Atom 0.184 on Windows 8.1. I am behind a company proxy.

Installing “project-manager@1.15.5” failed.Hide output…

npm ERR! tar.unpack error reading C:\Users\<snip>\.atom\.apm\es6-symbol\0.1.1\package.tgz
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\<snip>\\AppData\\Local\\atom\\app-0.184.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\<snip>\\AppData\\Local\\atom\\app-0.184.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\<snip>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\<snip>\\.atom\\.apmrc" "install" "C:\\Users\\<snip>\\AppData\\Local\\Temp\\d-115126-6348-1oqt5tv\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code EBADF
npm ERR! errno 9

npm ERR! EBADF, fstat
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by smikes** [comment]
EBADF is a bad file descriptor; and this error is coming from `node` without going through a javascript stack trace.  So my first suggestion would just be to reboot and try again, on the possibility that there's something weird with your filesystem.

If the error persists, I'm not sure what to tell you.  Normally I'd suggest trying different versions of `node` and `npm`, but since yours are installed by the Atom editor, I hesitate to suggest replacing them because "upgrading" those dependencies might break other parts of the editor.  Can you update `Atom`?

**Comment by DavidA2014** [comment]
I did a clean install of Atom and this issue appears to be fixed. Thanks for your help.

**Comment by othiym23** [comment]
Closing as resolved.
