### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by engyash** [npm/npm#7473]
some issue with npm install
http://prntscr.com/6a1u8h
may be something wrong with path
http://prntscr.com/6a1w9s

**Comment by smikes** [comment]
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by sacpr01** [comment]
Hi Smith,
I am using npm version 2.9.1. While running command npm install i am getting error. This is my log file.


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.9.1
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: missing script: start
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
5 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:318:20)
5 verbose stack     at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:226:19)
6 verbose cwd C:\Program Files\nodejs
7 error Windows_NT 6.1.7600
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 error node v0.12.2
10 error npm  v2.9.1
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by smikes** [comment]
@sacpr01 From the `npm-debug.log` it looks like you're trying to run `npm start` without defining a script in the `package.json`.  `npm start` is just a shorthand for `npm run-script start`, and you can read about the `run-script` subcommand here: https://docs.npmjs.com/cli/run-script

Can you please provide the `npm-debug.log` from your failed `npm install` run?  Since these files are often large, it's best to upload it as a gist <https://gist.github.com> or to pastebin, and then add a link to this issue.

Thanks!

**Comment by sacpr01** [comment]
Hi Smikes ,

I have upload log file here: https://gist.github.com/sacpr01/d95c3a4ae39106c39165.
I executed npm install after adding "start": "node index" to package.json

Thanks.

**Comment by othiym23** [comment]
Closing as abandoned.
