### ISSUE TITLE
Multiple runs of `npm pack` include the previous pack output

### ISSUE THREAD

**Issue by brianjmiller** [npm/npm#7478]
If I run `npm pack` and then run it again without deleting the tar file, on the subsequent run the original tar file will be embedded in the output. For example:

1st run: tar -tzf my-package-1.0.0.tar.gz
```package/package.json
package/.npmignore
package/README.md
package/LICENSE
package/1.0.1.json
package/NOTICE
package/formats.json
```

2nd run: tar -tzf my-package-1.0.0.tar.gz
```package/package.json
package/.npmignore
package/README.md
package/LICENSE
package/1.0.1.json
package/NOTICE
package/formats.json
package/my-package-1.0.0.tgz
```

node `v0.10.35`
npm `2.6.0`

**Comment by othiym23** [comment]
This is exactly how `npm pack` and `npm publish` work. In the absence of a populated `.npmignore` or `.gitignore` file, npm will also include logfiles, databases, and other bits of detritus in your package's file. If you want tighter control over what gets included in your package, look into `.npmignore` or the `files` array in `package.json`.

**Comment by brianjmiller** [comment]
I have a `.npmignore` file with the "correct" contents. What is the use case for a previous package produced to be included in the one being produced? Don't know of any other package manager that would include previous packaging of the contents into the currently being created package. It seems like at least a warning is warranted for overwriting the contents or the file already existing letting the user know it will end up in their new package.

**Comment by othiym23** [comment]
By default, npm includes everything that's not inside `node_modules` or included in `.npmignore` in the packed tarball (unless dependencies are `bundledDependencies`, of course). Are you saying that the `<package>-<version>.tgz` is in `.npmignore` and still being included? That would be a bug worth addressing. Otherwise, this is just how npm works.

The reason more people don't run into this issue is that it's comparatively rare that people run `npm pack` instead of `npm publish`. If you want to do a dry-run before packing / publishing your package, check out [`irish-pub`](https://www.npmjs.com/package/irish-pub) or [`pkgfiles`](https://www.npmjs.com/package/pkgfiles), which will generate a list of all the files to be included in the package without actually building it.

**Comment by brianjmiller** [comment]
Fair enough, I was doing a dry run to make sure the package had the correct contents. Figured worse case someone else hits this issue and finds this discussion. Thanks!
