### ISSUE TITLE
failed to fetch from registry: crconsole

### ISSUE THREAD

**Issue by madhavpai2000** [npm/npm#7480]
```
C:\Users\madhav.rp>npm install crconsole
npm http GET https://registry.npmjs.org/crconsole
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modules\npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\ProgramData\chocolatey\lib\npm.1.4.9\tools\node_modules\npm\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "node" "C:\\ProgramData\\chocolatey\\lib\\npm.1.4.9\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "crconsole"
npm ERR! cwd C:\Users\madhav.rp
npm ERR! node -v v0.12.0
npm ERR! npm -v 1.4.9
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\madhav.rp\npm-debug.log
npm ERR! not ok code 0
```

Can someone help me resolve this error>?

**Comment by smikes** [comment]
> Request path contains unescaped characters.

This looks like a problem either with your proxy URL or with the package you are requesting.

It looks like you're using `chocolatey` to manage your `npm` installation.  Is it possible to update that to a later version of `npm`? 1.4.9 is quite old and has some known bugs; the latest version is 2.6.1 and works much better.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
