### ISSUE TITLE
The error when restoring packages in Visual Studio 2015

### ISSUE THREAD

**Issue by JimDaddy** [npm/npm#7496]
====Executing command 'npm install grunt@"0.4.5"  '====

```
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1367:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:979:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:471:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:340:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:368:25)
npm ERR!     at doWrite (_stream_writable.js:225:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:215:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
npm ERR!     at write (_stream_readable.js:601:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt@0.4.5"
npm ERR! cwd C:\Users\xzhang\documents\visual studio 2015\Projects\MovieAngularJSApp\src\MovieAngularJSApp
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
```
====npm command completed with exit code 1====

**Comment by smikes** [comment]
It looks like you are running quite an old version of `npm` and also having trouble with the `https` protocol during install.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.9. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by JimDaddy** [comment]
@smikes 
Thank you for your reply.
I upgrade nodejs by install the latest version again on my Windows machine. And copy node and npm files from the installation directory(on my machine, it is C:\Program Files\nodejs) to visual studio 2015 external tools directory. VS shows the correct version and the error is the same as before.
Then I run the following command from Node.js command prompt console.
C:\Program Files\nodejs>npm set strict-ssl false
And it works.

I guess it is not a good solution. 
Is there any better solution for it?

**Comment by smikes** [comment]
@JimDaddy Sorry for not getting back to you before.  Using `set strict-ssl false` is not ideal, since it means that your packages can be intercepted and tampered with while downloading, which used to be a theoretical attack but is now known to be practical.  So it depends on how important that kind of integrity is, in your development environment.  Many people find it practical for development, as long as they can use SLL in a deployment environment.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
