### ISSUE TITLE
problem with npm show error when install something semver version

### ISSUE THREAD

**Issue by Widrogo** [npm/npm#7500]
hi, always have this problem I was look for a solution, but yet not find nothing:
![selection_501](https://cloud.githubusercontent.com/assets/3698485/6427103/99263de8-bf4c-11e4-84e6-b5b94c8a92ea.png)
and when I try to install the version:
![selection_502](https://cloud.githubusercontent.com/assets/3698485/6427107/b08244d2-bf4c-11e4-8da1-11fe5d6a48a1.png)

**Comment by KenanY** [comment]
@Widrogo `semver@2.4.0` does not exist:

``` sh
$ npm info semver versions
[ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.4',
  '1.0.5',
  '1.0.6',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.0.10',
  '1.0.11',
  '1.0.12',
  '1.0.13',
  '1.0.14',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.1.3',
  '1.1.4',
  '2.0.0-alpha',
  '2.0.0-beta',
  '2.0.1',
  '2.0.2',
  '2.0.3',
  '2.0.4',
  '2.0.5',
  '2.0.6',
  '2.0.7',
  '2.0.8',
  '2.0.9',
  '2.0.10',
  '2.0.11',
  '2.1.0',
  '2.2.0',
  '2.2.1',
  '2.3.0',
  '2.3.1',
  '2.3.2',
  '3.0.0',
  '3.0.1',
  '4.0.0',
  '4.0.2',
  '4.0.3',
  '4.1.0',
  '4.1.1',
  '4.2.0',
  '4.2.1',
  '4.2.2',
  '4.3.0',
  '4.3.1' ]
```

**Comment by Widrogo** [comment]
I try with other version 2.3 same error

**Comment by KenanY** [comment]
@Widrogo `npm install -g semver@2.3` is throwing an error? Could you upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by Widrogo** [comment]
I wanted to get the result before, but doesn't show nothing and console only shows me this WARN every time I install something with npm:

npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/npm-package-arg requires semver@'4' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/npm-package-arg requires semver@'4' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires graceful-fs@'^3.0.4' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.2

**Comment by smikes** [comment]
I would definitely recommend upgrading your `npm`.  There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by Widrogo** [comment]
yeah change the version of node and npm and this work for me thanks. node v0.10.37 and npm 1.4.28
