### ISSUE TITLE
`files` is ignored with tarball dependency

### ISSUE THREAD

**Issue by silverwind** [npm/npm#7501]
Defining a dependency like

``` js
   "vtt.js": "git+https://github.com/gkatsev/vtt.js.git#shim-build"
```

does result in a stripped down dependency installation on `npm install` (according to dependency's `files` and `.npmignore`), while

``` js
 "vtt.js": "https://github.com/gkatsev/vtt.js/archive/shim-build.tar.gz"
```

does not seem to remove the extra files. ref: https://github.com/videojs/video.js/pull/1911

**Comment by smikes** [comment]
So.. here's what I think is happening.

`npm` uses the `files` from `package.json` only when performing its `pack` operation.  It does not check `files` during the install.

When you tell `npm` to use a git repository as a source, `npm` does the following steps:
1. make a local clone of the git repository to `/tmp`
2. clone repository from `/tmp` to npm's cache
3. check out specified `commit-ish`
4. run `npm pack` to build a tarball
5. install the tarball

Whereas when you tell `npm` to install from a tarball by providing a URL that resolves to a .tar.gz file, `npm` only perfoms the last step, "install the tarball".  Thus the `npm pack` operation is never performed, and from your perspective, extraneous files are left in the installed directory.

Does this explanation help?  

If it's important that these files not be present, then I would probably recommend either referring to the git URL (which causes problems on Cygwin, so that's not an option for you) or using an npm registry (either the public registry or your own private registry), to ensure that the `npm pack` operation is run and the files are correctly excluded.  You'll also have the benefits of `semver` and caching if you use a registry.

**Comment by silverwind** [comment]
Makes sense. The `pack` step after `clone` in the git case seems a bit unnecessary to me though.

The files are already there in unpacked form, and could probably just be copied to the installation directory after the cleanup step, saving a few CPU cycles if this step could be decoupled from `pack`, and be applied after `clone` (git case) / `get` (tarball case).

**Comment by smikes** [comment]
Possibly so.  I don't think we can change that now without it being a breaking change, though.  

A lot of `npm`'s design is driven by making these steps reproducible, but unfortunately they're not always easy to identify or reason about.

Can I ask you, which parts of the `npm` documentation did you look at (obviously you read the docs about `files`), and is there anything we could add to those docs that would make this behavior easier to discover?

**Comment by silverwind** [comment]
If you want to keep it doc-only, I'd add a note to [this](https://docs.npmjs.com/files/package.json#urls-as-dependencies) section, with something like this:

> Note that the tarball dependencies will be installed as-is, without pruning optional files defined by `files` and `.npmignore`.
