### ISSUE TITLE
`npm update` should ignore linked packages

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7504]
Linking a package, either locally or globally, feels like an opt-out from automated updates, because presumably you're working on the package if you've linked it. What does everybody else think?

**Comment by smikes** [comment]
Although **I** agree with this behavior, I am an `npm` insider now.  I only use linking for developing interconnected packages.

However, lots of `npm` consumers use linking for all sorts of stuff, including deployment.  I'd hate to break someone's deployment because we did something weird to their `npm link` dependencies.

What does `npm update` do now for a link? I guess it would blow it away and replace it with `@latest` from the registry?

/needs-bikeshedding

**Comment by othiym23** [comment]
> What does `npm update` do now for a link? I guess it would blow it away and replace it with `@latest` from the registry?

Empirical experience with `npm@2.7.0` says that it nukes the link and "upgrades" to `latest`, yeah.

See https://github.com/npm/npm/issues/7530 for another example of how npm interacts strangely with `npm link`ed modules.

**Comment by RichardLitt** [comment]
I would expect this to opt out of upgrades.

**Comment by smikes** [comment]
I agree with changing this behavior.  

I think it should issue a warning on every package that's not touched.  E.g.,

```
$ npm update
WARN npm won't try to update foo -- link to /usr/local/bin/node_modules/foo
WARN npm won't try to update bar -- git module references git://github.com/bar/bar#commit-ish
baz@4.4.1 node_modules/baz
$
```

**Comment by othiym23** [comment]
Warning is a good idea. I would like to get this behavior added relatively soon, but we will probably wait to land it until after `npm@3`, because it makes changes to the installer.

**Comment by othiym23** [comment]
This is how `npm@3` was implemented, so we can call this done! YAY DONE! :tada: This was enough of an architectural shift that I don't really think it makes sense to backport to `npm@2`, but I could be persuaded otherwise.

**Comment by RichardLitt** [comment]
:tada: Woo.
