### ISSUE TITLE
npm errors trying to install module

### ISSUE THREAD

**Issue by Konstantinos76** [npm/npm#7505]
I am trying to install module on intel galileo running windows.
Node version 0.11.9
Npm version 1.4.9

![capture](https://cloud.githubusercontent.com/assets/11249775/6428473/676a9ec8-bf58-11e4-9735-593c22da21f3.PNG)

**Comment by smikes** [comment]
It looks like your installation has succeeded.  Are you able to use the module?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.9. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by Konstantinos76** [comment]
I can't use the module.
On an other attempt, it seems that the first error is a fetch failed error:
npm ERR! fetch failed http://registry.npmjs.org.....
Other errors follow after this.
I have downloaded npm folder and node.exe (binary) separately because I am trying to install on an intel galileo (installer is not an option in this case).
![capture](https://cloud.githubusercontent.com/assets/11249775/6429987/79d60c9a-bfa9-11e4-8493-0040ad2f10ec.PNG)

**Comment by Konstantinos76** [comment]
No luck with 1.4.12 either.
![capture](https://cloud.githubusercontent.com/assets/11249775/6430578/0f28b5c0-bfc5-11e4-813f-339d1eb29dbb.PNG)

**Comment by Konstantinos76** [comment]
@smikes Well, yes. You were right. The installation has succeeded,
Thank you.
