### ISSUE TITLE
semver.js:262 throw new TypeError('Invalid Version: ' + version);

### ISSUE THREAD

**Issue by Robert-Janagap** [npm/npm#7506]
```
$ gulp
c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:262
throw new TypeError('Invalid Version: ' + version);
^
TypeError: Invalid Version: undefined
at new SemVer (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:262:11)
at SemVer.compare (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:312:13)
at compare (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:535:31)
at Function.gt (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:564:10)
at Liftoff.handleArguments (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:99:14)
at Liftoff.<anonymous> (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:181:16)
at module.exports (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
at Liftoff.<anonymous> (c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:174:9)
at c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:148:9
at c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:13:7
```

**Comment by smikes** [comment]
Thanks for the bug report.  Can you tell us more about your system (version of node, npm, and gulp) , and what you're trying to do?

Are you sure that this is a problem with `npm` and not with `gulp`?  Although I can see that `npm` is in the module path, this is true for all globally-installed `npm` modules on Windows, because those are installed under `c:\Users\USERNAME\AppData\Roaming\npm\node_modules\` by default.  You may also want to look at the `gulp` issue tracker here <https://github.com/gulpjs/gulp/issues>

**Comment by Robert-Janagap** [comment]
node: v0.12.0, npm: 2.6.1 ,gulp: 3.8.11
i'm relatively new in npm, gulp and node. I'm trying to run my gulp packages like gulp-connect and gulp-sass.
thanks for the link in gulp issue tracker

**Comment by othiym23** [comment]
Looking at the stack trace, this looks to be a gulp issue that found its way into the npm issue tracker (that's OK, _plenty_ of npm issues end up over there as well – it's hard to figure out where to file issues!). Since a. @smikes has pointed you at gulp's issue tracker and b. I have no idea what's going on here, except that it's not coming out of npm, I'm going to close this. Good luck getting everything sorted out!

**Comment by andrei-ivanovici** [comment]
@Robert-Janagap  I don't know if this   is still available but I came across your exact issue and came with a  solution. In my case , I had the gulp-cli module  installed globally and forgot to install gulp in my  project. I copied and pasted the gulp dependencies from another project's 'package.js' and missed out gulp itself.
When  I ran "npm install" to bring down all my gulp dependencies, it brought down everything except gulp. It turns out that  the cli module compares itself withe the gulp module installed in the project , and if the gulp module is missing an  blank object is created which has  no property 'version'. Semver falls over when an  invalid version is passed to it's  compare (gt) method. The solution was to install gulp with npm install --save-dev gulp. 
I hope this helps :)

**Comment by patrickmichalina** [comment]
@andrei-ivanovici I am unable to fix this on Azure. I have tried so many things. Has there been an issue logged elsewhere?

**Comment by andrei-ivanovici** [comment]
@patrickmichalina . I'm afraid  I haven't seen this issue logged elsewhere.  As far as i can tell, semver will throw an error if you use it with 'undefined' objects. In gulp's case if  the main gulp module is missing, the cli crashes with this error because it tries to do a comparison between it's version(gulp-cli) and the main module version(gulp which doesn't exists, and therfore has an 'undefined' version).  You should try and pinpoint where semver is used and what arguments are passed in. Then you can backtrack the offending code 

Good luck!

**Comment by albertjan** [comment]
I ran into this aswell on azure and found a work around see https://github.com/projectkudu/kudu/issues/1573

**Comment by bennekrouf** [comment]
Installing gulp localy solved the problem for me.

**Comment by gowthambalashanmugam** [comment]
Please do npm update. Its solves my problem

**Comment by aliaksandr-master** [comment]
I solved it only after removing the package-lock.json and tried to reinstall dependencies. (bug was with gulp package too). In my case It everytime happens in CI and I add line `rm ./package-lock.json` it help for me. but I think it not right solution. but it works

**Comment by tom10271** [comment]
I am using npm 5.0.4. When I run gulp it returns this error too. I have tried to reinstall gulp already.

**Comment by ghost** [comment]
The purpose of `package-lock.json` is to guarantee that npm will install the same version of every dependency and child dependency, no matter the environment, as quoted from one of my colleagues.  If removing before the install, it can lead to a set of broken dependencies, which can lead to nasty, hard-to-find bugs (which has happened to us in the past).  I too have removed the `package-lock.json` file to get around the issue addressed in this ticket.  However, like @aliaksandr-master I don't think that is the ultimate solution.  Has anyone found a solution to the "Semver" problem since June?
