### ISSUE TITLE
flag for prune to ignore symlinked packages

### ISSUE THREAD

**Issue by RichardLitt** [npm/npm#7530]
I use a symlink workflow to enable me to develop on multiple packages without needing to publish for trivial changes. For instance, I have a main package, `main`, and then another package (let's say it is a style package only), `main-css`. In `main`, I don't include `main-css` in the package.json - I don't need to, for my build, as I use browserify for everything that the end user might see. So, after I run a normal `npm install`, I have a shell script that makes a symlink to wherever the `main-css` package is locally, so that I can require it in `main`. Since it might be relevant, here is a [link to that shell script](https://github.com/BeagleLab/beagle/blob/master/symlink.sh).

This is all pretty cool, but I occasionally need to run `npm prune`. When I do, it appropriately destroys my symlinked folders. However, it should be able to recognize them as such - it would be great if there could be a flag that would ignore symlinks, so I don't need to recreate them after each `npm prune`.

**Comment by othiym23** [comment]
Does it need to be a flag, or would it make sense to just change the default behavior of npm such that it always behaves this way with linked modules? `npm link`ing a module into the current project seems like a clear expression of intent that you want npm to leave it alone until you `npm rm` it (although it will still show up as `extraneous` if it's not in `package.json`).

See also #7504 for another version of this same idea.

**Comment by RichardLitt** [comment]
Default behavior for linked modules sounds better. Did not know about `npm link`, thanks! That should save me some amount of time. Given that it exists, it makes a lot more sense for npm to leave it alone. Perhaps there should be an `npm prune links` option to remove links.

**Comment by othiym23** [comment]
> Perhaps there should be an `npm prune links` option to remove links.

IMO that's a cowpath too far, but I could be persuaded otherwise.

**Comment by RichardLitt** [comment]
Depends on the amount of links a user has. I only have two at the moment, and I don't think that the canonical case has more than a few - it's not like you should be actively developing multiple packages, anyway (one thing done well in Unix philosophy). I say don't implement it at the moment, but ignoring linked modules in `prune` sounds good.

**Comment by jbmusso** [comment]
Greetings. I'm also using a couple symlinks in `node_modules` in order to avoid the `'../../../../'` issue with browserify, which is especially useful when developing an application (not a library).
I just google'd for this and I was thinking that a `npm prune --no-symlink` option (or something) might be helpful. As discussed here, I'm unsure yet if ignoring symlinks should be the default behavior of `npm prune`.

**Comment by othiym23** [comment]
I think `npm@3` handles this already, but I'll leave it to @iarna to confirm.

**Comment by zkat** [comment]
Hi!

Something that would protect symlinks from `prune` turns out to be unnecessary because we already have a mechanism to support this use case: `npm link` combined with (local?) devDependencies (for the case of not-published-yet modules).

So, if your `main-css` package is only ever used during build, what I would recommend is:

1. `npm install --save-dev ../main-css` (or `RichardLitt/main-css` if it's a github dep, and so on)
2. Use `npm link` to locally link `main-css` -- Your symlink will be protected because it's a devDependency
3. Develop on either one simultaneously, and all is good!

**Comment by RichardLitt** [comment]
Hey @zkat: cool. I wasn't aware that devDeps weren't pruned. 

I'm curious: What if I need to prune those, too? Would `--production` remove all of them?

**Comment by zkat** [comment]
`npm prune --production` would do that, yes. :)

**Comment by AndreiShostik** [comment]
now under the hood `npm prune --production` breaks all symlinks which is not desirable
