### ISSUE TITLE
Is it possible to clone the git repositories when installing NPM packages from git?

### ISSUE THREAD

**Issue by IonicaBizau** [npm/npm#7542]
I have a `package.json` like this:

```js
{
    "name": "test",
     "version": "1.0.0",
     "description": "",
     "main": "index.js",
     "scripts": {
       "test": "echo \"Error: no test specified\" && exit 1"
     },
     "dependencies": {
         "some-module": "git+ssh://git@github.com/IonicaBizau/some-module.git"
     },
     "author": "",
     "license": "ISC"
}
```

When I do `npm install` everything is installed correctly, but I would like to install the package from my repository by cloning the repository too, so in `node_modules/some-module` I will have a git repository cloned from GitHub.

How can I do that? Is there a built-in option for that or should I build my own tools?

**Comment by othiym23** [comment]
Take a look at [`npm link`](https://docs.npmjs.com/cli/link), which is the supported way to have a module installed while working on it at the same time. Because of how the npm cache works (and because trying to support nested git checkouts leads to all kinds of havoc), part of installing git dependencies is exporting the package from git. `npm link` gets around this by using symbolic links to bypass the cache.

**Comment by IonicaBizau** [comment]
Thanks! :+1:
