### ISSUE TITLE
Requiring 'browser' packages on the server

### ISSUE THREAD

**Issue by zol** [npm/npm#7545]
We're writing isomorphic code for rendering views on the server. We're using webpack to build the client off of the same codebase used to render on the server. To prevent `require` from throwing exceptions on the server when loading modules designed for the browser, we're finding ourselves writing code like:

``` js
var PictureFill;
var FastClick;

try {
  PictureFill = require('picturefill');
  FastClick = require('fastclick');
} catch (e) {
  if (! e instanceof ReferenceError)
    throw e;
}
```

Is there a more idiomatic approach we should be using?

**Comment by KenanY** [comment]
This doesn't look like an `npm` issue to me, but anyways I myself would probably keep client-side code and server-side code separated. I don't see why the client-side code is being built off of the server-side view-rendering code.

**Comment by zol** [comment]
@KenanY we use React to render UI components on the server. On the client, event handling code accesses modules provided by npm intended for the browser. This code will never run on the server, but should be load without errors. Given npm's claim on [](npm.com) that it's the 'package manager for the browser', I thought this would be a good place to start with my question. Where else would you suggest?

**Comment by smikes** [comment]
npm is the package manager; `browserify` is the module loader, or maybe `require.js`.  Since how modules get loaded in the browser is a somewhat charged topic, and people tend to have strong opinions, we generally try not to get in the middle of that.

What is it that you're hoping to do? When your code runs on the server, if the absence of those modules is acceptable, it might make more sense to separate the code further so that the isomorphic bit doesn't need to know about browser-only modules.

If I am misunderstanding your problem, please let me know.

**Comment by zol** [comment]
Thanks for the reply @smikes, if this is the way people structure their apps that's good to know. In our case I think it's neater to have our isomorphic components defined in one place. The user of the components can assume they will work either in the browser or node environments. I'll give an example:

``` js
'use strict';
var $ = require('jquery);
var React = require('react');

var autosize;

try {
  autosize = require('autosize');
} catch (e) {
  if (! e instanceof ReferenceError)
    throw e;
}

var Field = React.createClass({
  // will only be called in a browser environment
  componentDidMount: function() {
    autosize($(this.refs.about.getDOMNode()));
  },

  render: function() {
    return (
      <textarea ref="about" />
    )
  }
});

module.exports = Field;
```

If I require and render `Field` on the server, it will simply render a textarea. If I do the same on the client, it will render a text area as well as invoke the autosize library to automatically size it. I'd like to keep the code as compact without putting additional machinery around separating the server and client components. Ideally, I wouldn't have to wrap the require in a try/catch to achieve this. Whether people have a better pattern to do this is the thrust of my question.

**Comment by smikes** [comment]
That's a great question, and unfortunately not one that I'm going to be able to answer, because I am almost entirely on the server side and don't know much about browser issues.

If I was in your shoes, I would probably wrap the ugliness by making a little module, something like this:

```
function browser_require(name) {
  try {
    return require(name);
  } catch (e) {
    if (! e instanceof ReferenceError)
      throw e;
    if (inBrowser())
      throw new Error("expected require('" + name + "') to work: in browser!")
  }
}
```

But I literally have no idea what's a "known good" way to do it.  Perhaps someone who's more familiar with `react` + browserify + server issues will turn up.

**Comment by zol** [comment]
Thanks @smikes - Thats exactly the kind of wrapper we've written. Curious to hear whether others do the same or there is a more standard approach.

**Comment by iarna** [comment]
I'm gonna close this as off topic and hopefully resolved! =)
