### ISSUE TITLE
Warn users when they try to publish packages without .npmignore nor "files" property in the package.json

### ISSUE THREAD

**Issue by rubennorte** [npm/npm#7553]
Right now I'm finding a huge number of packages that aren't ignoring things like tests, fixtures, benchmarks, etc. You can see examples in [reqwest](https://github.com/ded/reqwest) (9.1 MB), [esprima](https://github.com/ariya/esprima) (8 MB), [useragent](https://github.com/3rd-Eden/useragent) (2 MB) and [grunt-browserify](https://github.com/jmreidy/grunt-browserify) (2.6 MB). We end up having a node_modules directory taking a lot of space because of files we don't actually need.

I think it'd be a good idea to warn users (or ask for confirmation) when they're trying to publish packages without .npmignore or a "files" entry in the package.json, or perhaps combine this with a verification of the size of the package or if some directories are being ignored or not (directories like test, tests and spec are good candidates).

Any idea on this?

**Comment by sindresorhus** [comment]
:+1: I think warning if both .npmignore and `files` is missing would be a good first step.

**Comment by drkibitz** [comment]
:+1: :+1: :+1: :+1: 

I believe this is a huge issue, and thank @rubennorte for bringing it up.

Over the past few years, after being in contact and working with a particular and rather large part of the npm community, there's one thing I disagree with. This is how the majority of these people treat the registry, internal or public. Many people I have come in contact with think of npm as nearly the same thing as a git repo, something like "I don't have read privileges on that repo, oh I'll just get the latest on npm!" I'm not making this up, this is very common. Optimizing npm packages for distribution is usually the last thing on this type of maintainer's mind before distributing it. Then, even through the course of optimizing the package at say version 22.0.0 give or take, now you've got 22+ (most likely many more for that many major versions) of unoptimized versions filled with unnecessary cruft.

My take on this, is that the meaning of software packaged for distribution is a lot different than the method of distributing software. It's pretty simple, if you want to use the software, install it, if you want to contribute to it, clone the source repo. With that in mind, what really needs to go into the package? This is what I've tried to explain to people, why it's important, and how it usually coincides with pain points of using npm (keep in mind this has been over the course of years):

- Installing/updating takes too long
   - This would be a lot faster if there were simply less files to deal with per package, tarballs are smaller, and there is simply less filesystem meddling
   - It would reduce many things, the amount of local caching, bandwidth, errors, time, etc., etc..
- Something went wrong, uuuuhh... `rm -fR ./node_modules && npm install`
   - Revolves back around to previous point unfortunately
   - Although this is horrible practice, it happens, and optimized packages equate to a more simplified file tree, which would most likely result in more inclined developers to solve these issues than take the blind approach
- The replicator stopped working again
- We're running out of disk space again

Npm has always been good at warning when files are missing. With that in mind, I have to agree with what I think the core of this issue is, and that is giving the same attention to files being preset. Personally, I would go one further. I would love it if npm would take the opposite approach to VCS and only use opt-in rather than opt-out for package inclusion. Yes, basically deprecating .npmignore altogether, and just use `files`. Then eventually develop heuristics around what warnings to show regarding the possible values of `files`.

I know these are pretty drastic changes, but I figured this would be as good a time as any to bring up these thoughts.

**Comment by sindresorhus** [comment]
I agree with everything @drkibitz said, but I know the npm maintainers do not. A first easy first step could be warning about not having .npmignore/files.

Related https://github.com/npm/npm/issues/5264

**Comment by drkibitz** [comment]
@sindresorhus Thank you, that long-lived thread was a good read, as well as the other one you linked to #5436. There's a lot of links in there @getify and others posted that I still want to look through. I definitely think there's similarities to all of these issues, just commented here because I only recently started watching the npm repo. Honestly didn't realize I wasn't watching it for all this time :flushed:.

Based on all of the progress and development, pending npm 3, I definitely maintain a lot of optimism for this software and community, so I apologize if I was mistaken for a downer :smiley_cat:.

**Comment by iarna** [comment]
Some of us still hold quixotic hopes for `npat` to usefully be a thing.

https://docs.npmjs.com/api/test
> To run tests as a condition of installation, set the npat config to true.

**Comment by ChALkeR** [comment]
Also keep this list in mind: https://github.com/npm/npm/issues/8339#issuecomment-113603911 =)

**Comment by grahamaj** [comment]
Perhaps one approach would be to allow the client more control.  This might be done in the `.npmrc` file where one could supply file/directory patterns for ignoring. As an example, the following in an `.npmrc` file would ignore all directories that are labeled as `test`, `tests`, or `examples`:
```
{
  ignore: [
    "tests/",
    "test/",
    "examples/"
  ]
}
```
This has the potential to be dangerous in that one might accidentally ignore core pieces of a package.  This could be mitigated by having `npm` output a warning when the option is used. There would also need to be a warning in the documentation.  If a client ran into a problem, they could simply be more specific in the file pattern (i.e `<specific package>/tests/`)

This approach would allow clients the flexibility to carefully optimize the node_modules directory without having to rely on the package publishers to do the right thing with an `.npmignore` file.

**Comment by beaugunderson** [comment]
This can also be a [security issue](https://twitter.com/beaugunderson/status/688544393918156801).

**Comment by raphaelokon** [comment]
I am just wondering if ignoring everything explicitly would work – kind of:

```bash
# Blacklist all
*

# Whitelist only files your users need or use `files` in package.json
!dist/*
!bin/*

# …
```

Any ideas?

**Comment by joebowbeerxealth** [comment]
Related to security risk: [For the love of god, don’t use .npmignore](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d)

> there isn’t an issue using .npmignore if you’re also whitelisting with files in package.json
