### ISSUE TITLE
Disable color codes when in non-tty's

### ISSUE THREAD

**Issue by mcandre** [npm/npm#7568]
As a Unix user, I want npm to disable color coded output when run in a non-tty context, so that npm's output isn't mangled when piped to `less` or npm is run in an Emacs dumb terminal.

**Comment by iarna** [comment]
It's already supposed to. Can you elaborate on the command(s) that you've run that it didn't do this for?

Also, please check the output of `npm config get color`– if it's set to `true`, npm will detect color support by looking at `process.stdout.isTTY`. If it's set to `always`, then it ignores the tty status of its output.

**Comment by mcandre** [comment]
Thanks for the tip. Unfortunately, even with color `true`, something is still not behaving correctly.

```
$ npm config get color
true
$ npm test | less
> regenboog@0.0.2 test /Users/andrew/Desktop/src/regenboog
> mocha


ESC[0mESC[0m
ESC[0m  regenboogESC[0m
ESC[0m    dbESC[0m
^M    ESC[32m  ✓ESC[0mESC[90m store and retrieve password ESC[0m


ESC[92m ESC[0mESC[32m 1 passingESC[0mESC[90m (19ms)ESC[0m

$ npm run exec ls | less
> regenboog@0.0.2 exec /Users/andrew/Desktop/src/regenboog
> exec ls

Gemfile
Gemfile.lock
Gruntfile.js
Guardfile
Guardfile-cucumber
Guardfile-lint
README.md
bin
bower.json
features
hooks
lib
node_modules
package.json
passwords.txt
public
test
upstart.conf

$ specs npm:mocha node brew os
Specs:

specs 0.12
https://github.com/mcandre/specs#readme

npm list mocha
regenboog@0.0.2 /Users/andrew/Desktop/src/regenboog
└── mocha@1.21.4 


npm --version
2.6.0

node --version
v0.10.36

brew --version
0.9.5

system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.10.2 (14C109)
```

Do you think mocha is the problem?

**Comment by rlidwka** [comment]
Maybe take into account env variables like `TERM=dumb` or `NODE_DISABLE_COLORS`.

**Comment by kmanion** [comment]
Hi @mcandre , it looks like you've gotten some help with this issue. We're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com

Kiera, npm technical support

**Comment by mcandre** [comment]
this has been an open bug on multiple platforms (windows and mac) for several years

**Comment by wasamasa** [comment]
Additionally to color sequences, I would expect npm to omit sending positioning escapes when in a dumb terminal.  This has been reported several times for Emacs' `M-x shell`:

- http://stackoverflow.com/questions/35573063/shell-mode-emacs-showing-npm-install-characters-weirdly
- http://emacs.stackexchange.com/questions/18457/stripping-stray-ansi-escape-sequences-from-eshell
- http://emacs.stackexchange.com/questions/27218/why-is-there-so-often-ugly-output-in-node-js-compilation-buffers

**Comment by othiym23** [comment]
@wasamasa, your response to http://emacs.stackexchange.com/questions/27218/why-is-there-so-often-ugly-output-in-node-js-compilation-buffers is only partially correct – there are some control characters being emitted by npm (which it may not be able to turn off if the shell minor mode is attached to a pty – it's been a while since I used that), but much of the display cruft is coming from mocha, which has its own responsibility for deciding whether it's printing to a terminal or not.

For http://emacs.stackexchange.com/questions/18457/stripping-stray-ansi-escape-sequences-from-eshell, it almost certainly _is_ related to encoding issues, because the output in that case is using Unicode box-drawing characters, encoded (I believe) as UTF-8. The control characters are for colors rather than for positions.

http://stackoverflow.com/questions/35573063/shell-mode-emacs-showing-npm-install-characters-weirdly _is_ an issue for npm not detecting the shell mode correctly, as that's almost certainly the progress bar being displayed and not working in npm. A patch that effectively detects when npm is being run in shell mode would be gratefully accepted, as long as it didn't over-aggressively disable the progress bar in other cases.

**Comment by iarna** [comment]
Yeah, as I said before we currently just trust ttyness. Editor shell modes _are_ tty's but have no terminal capabilities.

Ideally we'd be deciding what to emit based on termcap or terminfo, but I'm not aware of any pure-js implementation of these. =/

But what we _can_ do is look and see if `TERM=dumb`, which work for catch 99% of users.

**Comment by iarna** [comment]
Ok, color me surprised but `blessed` does actually implement full termcap and terminfo support. I wish it were available distinct from `blessed` though. It's 16k of code, which is a lot for the tiny fragment we actually need.

**Comment by wasamasa** [comment]
@othiym23 Alright, if it's another dependency printing these escapes, there isn't much npm can do about it.  `ESC[<x>G` however is the ECMA-48 CHA sequence (see `man console_codes`).

@iarna From what I've seen elsewhere, the preferred method for colors and basic movement is to check for `TERM` and whether it matches an unsupported one.  See the list of linenoise for an example: https://github.com/antirez/linenoise/blob/master/linenoise.c#L122

**Comment by iarna** [comment]
@wasamasa I'm aware of that convention, I just don't like it much. =p I prefer the blacklist to the whitelist approach, because terminal names are arbitrary and I've seen many a unix system with weird terminal names that ultimately just meant vt100 + some weird capability.

OTOH, I've not seen a wide variety of aliases for `dumb`. And non-dumb, non-vt terminals... I'm not aware of any still in use.

I believe what @othiym23 was saying that it isn't even a dependency of npm. If `mocha` is producing codes then you'll need to talk to the `mocha` folks about it, even when you run it via lifecycle scripts. (Sorry if that sounds uh, tautalogical, but yeah.)

Regarding `ESC[<x>G`, which is the horizontal absolute positioning code, that was used with earlier versions of the progress bar (module: `gauge`). It's use was eliminated as of v3.10.0.

Regardless, disabling the progress bar `--no-progress` will eliminate any use of non-color vt codes. (`--no-color` Doesn't disable the progress bar–it would still send erase-to-end-of-line codes– but it would avoid sending color codes.)

As with color I would be happy to see the default value for the progress bar be limited based on what terminal you're using. If you appear to be on a dumb terminal then I'd like it to default to off.

**Comment by kc0a** [comment]
Very annoying, and still broken 18 month later. I'm amazed we still have this half-baked terminal-code graphics in any application in 2018.

**Comment by tadmuck** [comment]
What a pain... is there a new bug report for this or a workaround?

**Comment by legodude17** [comment]
@tadmuck What exactly is the problem? If you have an issue with this then file a new issue.

**Comment by tadmuck** [comment]
@legodude17 - why are you asking "What exactly is the problem?"  That makes me think you haven't read the issue, because @mcandre nailed it clearly and simply. In case you haven't read it, here's a link:  https://github.com/npm/npm/issues/7568#issue-60240259 ;-)

But I'm following up here because I came up with a couple of workarounds that might prove useful to others. The real solution is for "npm" to use eiher use "tput", but that's probably not happening any time soon, so here's what I found:

(1) To clean up the mangling when using less, you can try "**less -r**" or "**less -R**". It's not perfect, but at least this makes less pass the color codes through to the terminal.

(2) To clean up the mangling when using a dumb terminal (TERM=dumb), you can try piping the output through "**col -b**"
