### ISSUE TITLE
How I can install git url from command

### ISSUE THREAD

**Issue by bolasblack** [npm/npm#7573]
npm version `2.5.1`

For example I want install underscore, if I execute command

    npm install git+ssh://git@github.com:jashkenas/underscore.git --save

then `package.json` will become:

    "underscore": "file:../../../../var/folders/82/vycf4nvx5vjd6x1kksbp4tnw0000gn/T/npm-89014-f6f48a39/git-cache-792fde59ccd7/cb08fdc339cdb8295de7e118474fe46fd1deaab3"

I known I can edit `package.json` and add line

    "underscore": "git://github.com/jashkenas/underscore"

 manually, but is there any way to do it with command line?

**Comment by othiym23** [comment]
This was a regression introduced somewhere around `npm@2.4`. It was just fixed in `npm@2.7.1`, which is currently in testing. If you want to verify that it fixes this bug for you, run `npm -g install npm@2.7.1`, including `sudo` if you need to be root to put things wherever npm installs your global packages.

**Comment by bolasblack** [comment]
@othiym23 OK, thanks

**Comment by bolasblack** [comment]
@othiym23 Awesome! It's fixed, thanks for your reply!

**Comment by lxe** [comment]
Yes!
