### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by malavikavsbca** [npm/npm#7576]
```
$ npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! missing script: start
```

**Comment by Saturate** [comment]
Do you have a ``start`` script in your ``package.json``?

Look here: https://docs.npmjs.com/cli/start and here https://docs.npmjs.com/misc/scripts for information.

**Comment by smikes** [comment]
Is this still a problem for you?

The advice @Saturate gave above is good -- `npm start` is a convenient shorthand for `npm run-script start` -- which is to say, it will run the user-defined script named `start` from your `package.json` file.  However, you need to define what that script means, since it will be different for different projects / use cases.  See https://docs.npmjs.com/misc/scripts or this section of the documentation for `package.json`: https://docs.npmjs.com/files/package.json#scripts

```
scripts

The "scripts" property is a dictionary containing script commands that are run at various times in the lifecycle of your package. The key is the lifecycle event, and the value is the command to run at that point.

See npm-scripts(7) to find out more about writing package scripts.
```

By the way, there is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
