### ISSUE TITLE
npm install error? and global install stop for 24%

### ISSUE THREAD

**Issue by yyman001** [npm/npm#7577]
```
C:\webapp>npm install gulp-uncss --save-dev
npm ERR! tar.unpack error reading C:\Documents and Settings\Administrator\Applic
ation Data\npm-cache\wrappy\1.0.1\package.tgz
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "D:\\software\\nodejs\\\\node.exe" "D:\\software\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "install" "gulp-uncss" "--save-dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EBADF
npm ERR! errno -4083

npm ERR! EBADF, fstat
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\webapp\npm-debug.log
-------------------global install 
C:\Documents and Settings\Administrator>npm install -g gulp-uncss
\
> phantomjs@1.9.16 install C:\Documents and Settings\Administrator\Application D
ata\npm\node_modules\gulp-uncss\node_modules\uncss\node_modules\phridge\node_mod
ules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\phantomjs\phantomjs-1.9.8-windows.z
ip
Receiving...
  [==========------------------------------] 24% 0.0s
```

**Comment by KenanY** [comment]
@yyman001 Perhaps https://github.com/npm/npm/issues/7472#issuecomment-76510381 by @smikes could help?:

> `EBADF` is a bad file descriptor; and this error is coming from node without going through a javascript stack trace. So my first suggestion would just be to reboot and try again, on the possibility that there's something weird with your filesystem.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
