### ISSUE TITLE
link: can't relatively link another module multiple times

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#7579]
ex. if i link to the same module multiple times with `npm link ../standardberry`, i'll get the following error:

```
npm ERR! Refusing to delete: /Users/jong/.nvm/versions/io.js/v1.5.0/bin/standardberry not in /Users/jong/Workspace/collect/collector
File exists: /Users/jong/.nvm/versions/io.js/v1.5.0/bin/standardberry
Move it away, and try again. 
```

thing is... it's the same file. i really should be doing `npm link standardberry` at this point, but sometimes i don't remember if i've linked a module or not.

solution would be to check whether the binaries point to the same location before actually erroring.

**Comment by smikes** [comment]
Thanks for the bug report.  

This is a relatively new bug that was probably introduced when @othiym23 fixed a horrific problem where `npm` would sometimes vacuum up directories above the current `node_modules`.  Anyway, `npm` is perhaps a little too conservative right now in what it deletes.

**Comment by othiym23** [comment]
This is a real and super annoying bug that bit me several times this weekend alone. It will get fixed soon. Thanks for filling the issue, @jonathanong!

**Comment by othiym23** [comment]
The bug had been around for a while. I think it was more that most people weren't encountering it because the situations in which it bit were fairly specific. I gave `gently-rm.js` another thorough overhaul, and this time made sure that @iarna and I both understood the code before merging the changes. It's possible that we've overlooked some corner cases (`gentlyRm` relies on heuristics tied to assumptions about how people work with their packages that may not hold up in all cases), but it turns out that when it's overly cautious, it's been worth investigating why. Thanks for filing this, @jonathanong!
