### ISSUE TITLE
error I've got when i use mup deploy. How can I resolve this?

### ISSUE THREAD

**Issue by jamesfermanejo** [npm/npm#7587]
```
232 error Error: No compatible version found: tap@'^0.7.1'
232 error Valid install targets:
232 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.4.5","0.4.6","0.4.7","0.4.8","0.4.9","0.4.11","0.4.12","0.4.13","0.5.0","0.6.0","0.7.0","0.7.1"]
232 error     at installTargetsError (/opt/nodejs/lib/node_modules/npm/lib/cache.js:685:10)
232 error     at /opt/nodejs/lib/node_modules/npm/lib/cache.js:607:10
232 error     at saved (/opt/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
232 error     at Object.oncomplete (fs.js:107:15)
233 error If you need help, you may report this log at:
233 error     <http://github.com/isaacs/npm/issues>
233 error or email it to:
233 error     <npm-@googlegroups.com>
234 error System Linux 3.13.0-43-generic
235 error command "/usr/bin/node" "/usr/bin/npm" "install"
236 error cwd /opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
237 error node -v v0.10.3
238 error npm -v 1.2.17
239 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@jamesfermanejo Your version of `npm` is so old, it does not support the `^` semver operator you see here:

```
232 error Error: No compatible version found: tap@'^0.7.1'
```

As such, `npm` fails to find a valid version of `tap` that matches the range (because it does not understand what the `^` means). The solution is simple: [update](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc)!

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
