### ISSUE TITLE
Issue while using NPM on Amazon EB

### ISSUE THREAD

**Issue by VikramTiwari** [npm/npm#7595]
npm-debug log

```
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.14.20-20.44.amzn1.x86_64
npm ERR! command "/opt/elasticbeanstalk/node-install/node-v0.10.31-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v0.10.31-linux-x64/bin/npm" "start"
npm ERR! cwd /var/app/current
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! path /var/app/current/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/app/current/npm-debug.log
npm ERR! not ok code 0
npm ERR! Error: ENOENT, open '/var/app/current/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

```

**Comment by KenanY** [comment]
@VikramTiwari It appears as though you are trying to run `npm start` in a directory that does not contain a `package.json`. `npm` has absolutely no idea what you want it to do unless you define the `"start"` script in your `package.json` (what are you _expecting_ to happen?). Please see the documentation on [`npm start`](https://docs.npmjs.com/cli/start) and [scripts](https://docs.npmjs.com/misc/scripts).

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by dannyng198811** [comment]
I got the same problem when I deploy the project on AWS Beanstack
