### ISSUE TITLE
Intalling ANYTHING with NPM 

### ISSUE THREAD

**Issue by mireyarod23** [npm/npm#7602]
I'm working on a PC I cannot install anything with NPM because http from github gets loaded WHY?

![untitled](https://cloud.githubusercontent.com/assets/11428258/6603624/dc1ad90c-c7e8-11e4-8a39-e07e5b390aac.jpg)

**Comment by smikes** [comment]
It looks like your the `registry` setting in one of your `npm` config files has been set strangely.  According to the log, your registry is `http://github.com/expressjs/body-parser`.  It should be `https://registry.npmjs.org`

Can you try running the command as

```
> npm --registry=https://registry.npmjs.org/ install express@latest
```

If that command fails, please upload your npm-debug.log as a  gist <http://gist.github.com> and post a link to the gist here.

There have been a lot of improvements to npm since 2.5.1. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by mireyarod23** [comment]
Updating the registry work! 

The registry had the http://github.com/expressjs that is the reason why in the command was loading it's html.

Thank you!
