### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by dreamhs** [npm/npm#7606]
I used 

      C:\Windows\System32>npm install -g phantomjs

to install phantomjs with node js command prompt , and ran the prompt with  admin permission. but failed, the version I am using is the latest. Error like below 

```
npm ERR! addLocal Could not install C:\Windows\System32\-g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\v-shuhe\\AppData\\Roaming\\npm\\node_modules\\n
pm\\bin\\npm-cli.js" "install" "-g" "phantomjs"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! path C:\Windows\System32\-g
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Windows\System32\-g'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log
```

**Comment by smikes** [comment]
For some reason `npm` is interpreting the `-g` flag a file/directory name.  Can you try the following:

```
> cd C:\TEMP
> npm install --global phantomjs
```

And once that finishes, upload your `npm-debug.log` to https://gist.github.com and post a link to the gist here.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
