### ISSUE TITLE
Attempt to unlock /home/spare2/n/node_modules/meanio, which hasn't been locked

### ISSUE THREAD

**Issue by SibuStephen** [npm/npm#7607]
when i tried running my server i'm getting this error  -" Attempt to unlock /home/spare2/n/node_modules/meanio, which hasn't been locked ". i'm not aware of as to how to handle this scenario.

**Comment by smikes** [comment]
Thanks for reporting this.  It sounds like an error that was common in older versions of `npm` (<2.5) where a race condition sometimes caused errors like this.

One option that you can try right away is `npm install -g npm@latest` ; this should get you the latest npm version.  If that doesn't fix the issue for you, could you please upload your `npm-debug.log` as a gist <https://gist.github.com/> and post the link here?  The full log often helps to diagnose the problem.

**Comment by SibuStephen** [comment]
yes , will do it right away.

**Comment by SibuStephen** [comment]
MEAN Status
    -----------

    MEAN VERSION: 0.4.3

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.9.20
    meanio at latest version: 0.7.1

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by SibuStephen** [comment]
Yes this issue is resolved.
