### ISSUE TITLE
Could not install /tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz

### ISSUE THREAD

**Issue by k92ankita** [npm/npm#7609]
we are running make fetch-pkgs-dev and getting below error logs.. Please help

```
1758 silly lockFile 56ce089a-12246-0-2283567637205124-package /home/contrail/tmp/npm-28859/1426238912246-0.2283567637205124/package
1759 silly lockFile b0c29792-rd-party-requirejs-2-1-15-tar-gz /tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz
1760 error addLocal Could not install /tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz
1761 error Error: No 'name' field
1761 error     at validName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:512:40)
1761 error     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:27)
1761 error     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:119:33
1761 error     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
1761 error     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:249:40
1761 error     at fs.readFile (fs.js:176:14)
1761 error     at fs.close (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
1761 error     at Object.oncomplete (fs.js:297:15)
1762 error If you need help, you may report this log at:
1762 error     <http://github.com/isaacs/npm/issues>
1762 error or email it to:
1762 error     <npm-@googlegroups.com>
1763 error System Linux 3.8.0-29-generic
1764 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "/tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz" "--prefix" "/tmp/cache/contrail/webui_third_party"
1765 error cwd /home/contrail/contrail-webui-third-party
1766 error node -v v0.8.15
1767 error npm -v 1.1.66
1768 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like the tarball that you are trying to install ("/tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz" ) does not contain a valid package.json file.  Is there a reason you must install this package from a tarball, or can you try using the `npm` registry's version:

```
npm install --prefix /tmp/cache/contrail/webui_third_party requirejs@2.1.15
```

Your versions of `node` and `npm` are both quite old; if you can, I'd recommend updating them.

Specifically, here have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.1.66. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by smikes** [comment]
It looks like the tarball that you are trying to install ("/tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz" ) does not contain a valid package.json file.  Is there a reason you must install this package from a tarball, or can you try using the `npm` registry's version:

```
npm install --prefix /tmp/cache/contrail/webui_third_party requirejs@2.1.15
```

Your versions of `node` and `npm` are both quite old; if you can, I'd recommend updating them.

Specifically, here have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.1.66. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by smikes** [comment]
It looks like the tarball that you are trying to install ("/tmp/cache/contrail/webui_third_party/requirejs-2.1.15.tar.gz" ) does not contain a valid package.json file.  Is there a reason you must install this package from a tarball, or can you try using the `npm` registry's version:

```
npm install --prefix /tmp/cache/contrail/webui_third_party requirejs@2.1.15
```

Your versions of `node` and `npm` are both quite old; if you can, I'd recommend updating them.

Specifically, here have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.1.66. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
