### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by uz5m** [npm/npm#7610]
```
npm ERR! Error: EBUSY, unlink 'C:\Users\xuke\AppData\Roaming\npm\node_modules\sh
ader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas
-browserify'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2013" "-g" "s
hader-school"
npm ERR! cwd D:\source\js\javascripting
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\xuke\AppData\Roaming\npm\node_modules\shader-school\node_
modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify
npm ERR! code EBUSY
npm ERR! errno 10
```

**Comment by smikes** [comment]
This error usually means that you are running into a race condition.  There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by kevva** [comment]
Yeah, I would also recommend updating npm.

```sh
$ npm install --global npm@latest
```

**Comment by uz5m** [comment]
I've retried several times, then finally solved it, it's not the updating problem, just because I opened one directory which the npm want to delete during the installing...

**Comment by kevva** [comment]
Hence:

> EBUSY means that the file is in use somwhere.

**Comment by iarna** [comment]
Closing as resolved
