### ISSUE TITLE
readme.md is wrong for windows

### ISSUE THREAD

**Issue by rickdog** [npm/npm#7636]
readme.md says:
[quote]
You can download a zip file from <https://npmjs.org/dist/>, and unpack it in the same folder where node.exe lives.
[/quote]

Not true, must unpack to subfolder node_modules\npm where node.exe lives.
(npm 1.4.28, probably others too)

**Comment by msikma** [comment]
I think the reference to 1.4.28 in the readme is not needed anymore, anyway—unless I'm missing something, all versions still come in a zip file with binary. But the note about the path seems to be correct. On a side note, you seem to have an old version, since the readme now links to https://github.com/npm/npm/releases

**Comment by othiym23** [comment]
I just landed @msikma's tweak to the wording as 402f52ab201efa348feb87cad753fc4b91e8a3fb, which is close enough to call this resolved. As @msikma said, if you're seeing a message about `npmjs.org/dist`, you have a version of npm old enough that you really ought to think about upgrading anyway. There's not a lot we can do about changing the wording in the documentation in old versions.
