### ISSUE TITLE
sudo npm install -g once not working

### ISSUE THREAD

**Issue by mikesol** [npm/npm#7638]
Hey!
I'm getting the error below repeatedly.  Any help would be appreciated!

```
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/once
npm ERR! Error: ENOENT, open '/usr/local/lib/node_modules/once/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "once"
npm ERR! cwd /Users/mikesolomon/Documents/cordova_workspace/testng
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path /usr/local/lib/node_modules/once/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mikesolomon/Documents/cordova_workspace/testng/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@mikesol `npm@1.3.2` is very old and no longer supported. Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc)?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
