### ISSUE TITLE
Error creating Jasmine config file

### ISSUE THREAD

**Issue by anabellchan** [npm/npm#7639]
My goal is to create unit tests for AngularJS.  The AngularJS team recommends using Karma and Jasmine for testing.

Here is what I've taken so far:
1.  Installed Git v1.9.5.
2.  Installed Node.js v.0.12.0
3.  Installed Karma module:  npm install -g karma

By now, my file directory will now have “C:\Program Files\nodejs\node_modules\karma” , and the “C:\Program Files\nodejs\node_modules\karma\bin” .  I also have a karma file in the bin folder.

4.  To create a jasmine configuration file, in the bin folder, I ran:

karma init

However, I get this error message:

C:\Program Files\nodejs\node_modules\karma\bin>karma init
'karma' is not recognized as an internal or external command,
operable program or batch file.

Any clue what's going on?  Thanks!

**Comment by smikes** [comment]
Hm.. sometimes Windows path problems can happen when the system PATH environment variable is updated, but the update is not reflected in already-running CMD shells.  Does the problem persist if you open a new `node for Windows` shell?  (Sorry if I have the terminology wrong, I don't have access to a Windows machine right now.)

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
