### ISSUE TITLE
Error on installing Harp Webserver on Windows

### ISSUE THREAD

**Issue by MakiMark** [npm/npm#7642]
I have everything installed on my windows maschine: (ruby, compass and nodejs) and now I wanted to install the local webserver harp but i get the following errors (Please see pic below) . Can please someone help. Thanks a lot.

![error](https://cloud.githubusercontent.com/assets/11501730/6665561/359a5138-cbdb-11e4-9b11-472a6721e7f1.png)

**Comment by KenanY** [comment]
@MakiMark This looks like an issue with your internet connection. `git` is having difficulties connecting to `github.com`. Are you behind a proxy by any chance?

**Comment by MakiMark** [comment]
@KenanY thanks for the quick reply! Internet is fine. But i am on a office computer. So i guess it runs behind a proxy. Is there any way to install it behind a proxy server? Thanks.

**Comment by MetaMemoryT** [comment]
This is related to:

https://github.com/npm/npm/issues/7623

https://github.com/npm/npm/issues/7456

**Comment by KenanY** [comment]
@MetaMemoryT Is it? Those issues are regarding "not a repository" errors whilst this one is an "unable to connect" error.

**Comment by MetaMemoryT** [comment]
good point, I just thought it was failing because the path was being rendered wrong, which is the problem the other bugs are having.

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
