### ISSUE TITLE
I just installed Nodejs on my Computerwhile installing i got this error message

### ISSUE THREAD

**Issue by konthamkarthik** [npm/npm#7650]
```
error Error: ENOENT, stat 'C:\Users\admin\AppData\Roaming\npm'
```

**Comment by KenanY** [comment]
@konthamkarthik This sounds like a consequence of https://github.com/joyent/node/issues/8141, and is an issue with the Node installer for Windows. The workaround is to ensure that `C:\Users\admin\AppData\Roaming\npm` exists and is writable with your normal user account.

If that doesn't solve your issue, then please upload the full `npm-debug.log` as a [gist](https://gist.github.com). Posting **one line** of an entire log eliminates literally all context.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
