### ISSUE TITLE
installing bower with npm causing error

### ISSUE THREAD

**Issue by dhirus1** [npm/npm#7651]
installing bower with command line npm causes below error on windows 7, 32 bit machine..
below is the npm error log..
=====
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'bower', null ]
6 verbose cache add spec bower
7 silly cache add parsed spec { raw: 'bower',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'bower',
7 silly cache add   spec: 'C:\\Users\\dhkumar\\Documents\\nextgen-automation_old\\bower',
7 silly cache add   type: 'local' }
8 silly addLocalTarball shasum (computed) da39a3ee5e6b4b0d3255bfef95601890afd80709
9 verbose addTmpTarball C:\Users\dhkumar\Documents\nextgen-automation_old\bower not in flight; adding
10 verbose addTmpTarball validating metadata from C:\Users\dhkumar\Documents\nextgen-automation_old\bower
11 verbose tar unpack C:\Users\dhkumar\Documents\nextgen-automation_old\bower
12 verbose tar unpacking to C:\Users\dhkumar\AppData\Local\Temp\npm-7460-e194cef9\unpack-979798928068
13 verbose gentlyRm vacuuming C:\Users\dhkumar\AppData\Local\Temp\npm-7460-e194cef9\unpack-979798928068
14 silly gunzTarPerm modes [ '777', '666' ]
15 error tar.unpack error reading C:\Users\dhkumar\Documents\nextgen-automation_old\bower
16 error addLocal Could not install C:\Users\dhkumar\Documents\nextgen-automation_old\bower
17 verbose stack Error: 0-byte tarball
17 verbose stack Please run `npm cache clean`
17 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\tar.js:126:14
17 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
18 verbose cwd C:\Users\dhkumar\Documents\nextgen-automation_old
19 error Windows_NT 6.1.7601
20 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
21 error node v0.12.0
22 error npm  v2.5.1
23 error 0-byte tarball
23 error Please run `npm cache clean`
24 error If you need help, you may report this error at:
24 error     <http://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@dhirus1 Have you tried the advice of the error message?

> 23 error 0-byte tarball
> 23 error Please run `npm cache clean`

**Comment by dhirus1** [comment]
yes, tried with 'npm cache clean' but did not help..

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned. I think part of the problem might have been that there was an empty directory named `bower` in the directory from which npm was being run, which was confusing it, as it was trying to treat that directory like a local package.

**Comment by imbubble** [comment]
@othiym23 +1, it works for me. thanks!!
