### ISSUE TITLE
Changing arch w/ dirty tree causes native bindings not to be recompiled

### ISSUE THREAD

**Issue by haf** [npm/npm#7678]
Repro:

 1. Create a project that depends on node-sass
 2. Compile it on OS X
 3. Create a dockerfile that runs `npm install`.
 4. Use the docker client to send the build context through the TCP socket to a linux flavor that's running the docker daemon (`docker build -t tmp .`)
 5. Watch [it crash](https://github.com/sass/node-sass/issues/753#issuecomment-78512751)

Anti-repro: Remove step 2. No error because no darwin-binary is built and sent to the linux.

Possible problem: the logic for checking "is this library's native bindings already built" doesn't take architecture into account properly.

**Comment by othiym23** [comment]
It sounds like what you want is [`npm rebuild`](https://docs.npmjs.com/cli/rebuild), which is what you should run on a prebuilt tree when moving it between architectures.

**Comment by haf** [comment]
I think it's a bug that npm install doesn't care about what architecture it's on. It means npm says it's successful, when it's really not.

The theme should be this: "`npm install` is all you need to compile"

**Comment by othiym23** [comment]
So, let's walk through this a bit. I think it's generally agreed that the npm's current approach of saying, "welp, this package already has a directory in `node_modules`, so I don't have to do anything," is unhelpful in many cases (previous install crashed halfway through, weird dependency snafu in its transitive dependencies – that kind of thing). That was one of the major reasons why we started working on the `multi-stage` branch that is currently shaping up to be `npm@3`. With `npm@3`, the installer will look at `node_modules`, and as much as is possible, figure out if modules are out of sync with `package.json` or `npm-shrinkwrap.json` and clean them up. That takes care of JavaScript.

However, npm itself doesn't know anything about native modules. It knows to look for a `binding.gyp` file, and if one exists, to invoke `node-gyp` so it can do whatever it does (npm doesn't know or care). Given that building native modules is often the most heavyweight part of the installation process (particularly on Windows), you don't want to rebuild the modules unless you have to. This is a key point, and one to which I'll return in just a minute.

`node-gyp` more or less has its hands full just figuring out how to turn `binding.gyp` into a built product for all of the platforms it supports, and doesn't really do much in the way of dependency analysis. I would suggest, though, that in the case you describe, this is something that `node-gyp` (or just plain `gyp`) should handle, and not npm itself, because, again, npm doesn't know anything about native modules.

But there's yet another complication – you tar up or rsync the built tree from one host onto another host with a different architecture. As far as all the timestamps on the file are concerned, the built objects are up to date with their sources, so unless the build system is smart enough to look inside the object files and determine that they're the wrong architecture (which is something that no build system I'm aware of does on its own), none of the platform-native build system, `node-gyp`, or npm knows that these files are the wrong architecture.

So the only way to fulfill your theme would be for _every_ npm install involving packages with native modules to run the _complete_ native build process. That would make the install process dramatically slower in the common case, and is completely unnecessary the vast majority of the time. The reason `npm rebuild` exists is pretty much this exact use case, because npm is designed to make it relatively straightforward to move packages with native dependencies across architectures, but it also exists because in the general case, npm is designed to save time in the long run at the cost of introducing some additional up-front complexity.

I'm sorry if this all seems unnecessarily complex to you, but I hope it at least makes sense now why things work the way they do.
