### ISSUE TITLE
'command not found' when installing package

### ISSUE THREAD

**Issue by jjg1914** [npm/npm#7722]
Brief rundown of the issue, as far as I can debug:

I have two dependencies I'm trying to install: bower and gulp-ngdocs. The package gulp-ngdocs  also has bower as a dependency, and does a `bower install` as part of its install script. When I install them side-by-side bower is NOT installed into gulp-ngdocs node_modules. The result is, when installing, that the bower command isn't found during gulp-ngdocs's install script.

I think this is because bower's package.json sets "preferGlobal" to true, but I could easily be mistaken. I also noticed that when running `npm install` a second time, after bower has successfully installed, that gulp-ngdocs installs fine.

Here's a link to the [failing output](http://paste.ubuntu.com/10664144/). npm is version 2.7.1, node version is 0.10.26.

Thanks in advance for any help!

NOTE: This problem doesn't occur if bower is installed globally. But this break's a continuous build environment where bower is not globally installed.

```
# This package.json installs fine
{
  "name": "example-package",
  "dependencies": {
    "gulp-ngdocs": "*"
  }
}

# This one fails
{
  "name": "example-package",
  "dependencies": {
    "bower": "*",
    "gulp-ngdocs": "*"
  }
}
```

**Comment by smikes** [comment]
Thanks for bringing this up.

I think the problem is that `npm` tries to parallelize the installation of `bower` and `gulp-ngdocs`, which can result in `gulp-ngdocs` deciding not to install its own copy of `bower`, but then finishing first and trying to run its install script before `bower` is done installing.

You might be able to work around this by putting `npm install bower` in your **own** package's `preinstall` script, but that's just fixing one anti-pattern with another application of the same anti-pattern -- in general, preinstall and postinstall scripts cause trouble (as you have discovered).  Can you give this workaround a try?

I believe the preferGlobal is a red herring.

**Comment by jjg1914** [comment]
Thanks @smikes, this worked for me! I'll opening an issue on the ```gulp-ngdocs``` repository to get this fixed the right way.

**Comment by smikes** [comment]
Good luck, but it may not be fixable under npm 2.x – you may need to work around it for now.
