### ISSUE TITLE
npm run removes quotes from given parameters

### ISSUE THREAD

**Issue by mantoni** [npm/npm#7743]
I'm [using npm as a build tool](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) and ran into the following issue with `npm run` and quoted parameters.

This is the interesting part of the "scripts" section in my package.json:

```
"scripts": {
  "test": "mochify",
  "cover": "npm run test -- --plugin [ mochify-istanbul --report cobertura --exclude '**/*.mustache' ]"
}
```

Running `npm run cover` prints this:

```
> npm run test -- --plugin [ mochify-istanbul --report cobertura --exclude '**/*.mustache' ]
...
> mochify --plugin [ mochify-istanbul --report cobertura --exclude **/*.mustache ]
```

You can see that  `**/*.mustache` is quoted on the first line, but the quotes are removed on the second line. This causes the script to fail because I have to pass the glob expression as a plain string.

If I change the cover script to this:

```
"cover": "mochify --plugin [ mochify-istanbul --report cobertura --exclude '**/*.mustache' ]"
```

... calling `npm run cover` works fine and npm prints the quotes as expected:

```
> mochify --plugin [ mochify-istanbul --report cobertura --exclude '**/*.mustache' ]
```

Thanks for looking into it!

**Comment by smikes** [comment]
Thanks for reporting this.

This is known behavior, though I don't know if there's another issue for it already.  It happens because `npm run` retrieves the args after `--` from the command line after the shell has unescaped them, and concatenates them without quotes.  

I'm not sure there's a general way to solve the problem, though, as the quotes are gone by the time `npm run` can see the arguments, and it's not obvious to me that there's a safe way to re-quote them since an argument may have quotes in it due to escaping, or glob expansion, etc.

**Comment by mantoni** [comment]
Well, the workaround is to not use the feature if I have command parameters that need to be quoted :)

I had a look and as a quick and dirty hack I replaced [this line](https://github.com/npm/npm/blob/master/lib/run-script.js#L193) with this:

```js
joinedArgs += " '" + arg + "'"
```

It fixes this specific issue, but I'm not sure whether this works as a valid solution in general or whether it will introduce other issues.

Thoughts?

**Comment by smikes** [comment]
Just off the top of my head, It will cause an error in the shell if the arg before shell expansion is `*` and the directory contains a file containing single-quote (eg., named `Don't read me.md`)

So that's probably not a viable long-term fix.

Another workaround would be to denormalize the commands, repeating `mochify` in your `cover` command: 
```
"scripts": {
  "test": "mochify",
  "cover": "mochify --plugin [ mochify-istanbul --report cobertura --exclude '**/*.mustache' ]"
}
```

That way the arguments don't get passed through `npm run` twice.

**Comment by KenanY** [comment]
Oddly enough, this results in no quotes being removed:

``` json
{
  "scripts": {
    "test": "mochify",
    "cover": "mochify --plugin [ mochify-istanbul --report cobertura --exclude \"'**/*.mustache'\" ]"
  }
}
```

``` sh
$ npm run cover

> @ cover
> npm run test -- --plugin [ mochify-istanbul --report cobertura --exclude "'**/*.mustache'" ]


> @ test
> mochify --plugin [ mochify-istanbul --report cobertura --exclude "'**/*.mustache'" ]
```

**Comment by mantoni** [comment]
@KenanY You're just doing the escaping for npm ;-)

@smikes Good point. If an argument contains `'` it should be escaped with `\'`, just like `"` is [escaped here](https://github.com/npm/npm/blob/master/lib/run-script.js#L192). I'll make that a PR and see whether I can come up with some tests for that.
