### ISSUE TITLE
npm publish merges dependencies and optionalDepedencies

### ISSUE THREAD

**Issue by abbakym** [npm/npm#7759]
Tried with `npm@2.6.0` and `2.7.3`: if `package.json` have both `dependencies` and `optionalDependencies`, latter are added to the former when publishing.

E.g. if we have (assume proper JSON):
````
{
  version: '1.0',
  dependencies: {
    a: '1'
  },
  optionalDependencies: {
    b: '1',
    c: '1'
  }
}
````

then published is:
```
{
  version: '1.0',
  dependencies: {
    a: '1',
    b: '1',
    c: '1'
  },
  optionalDependencies: {
    b: '1',
    c: '1'
  }
}
```

Full log example: https://docs.npmjs.com/files/package.json#optionaldependencies

With this `npm install --no-optional` still works, because "Entries in optionalDependencies will override entries of the same name in dependencies" (https://docs.npmjs.com/files/package.json#optionaldependencies), but it kind of contradicts the "it's usually best to only put in one place" (same place). It's also surprising that my (carefully handcrafted :)) `package.json` is modified.

If it is done on purpose, probably this should be documented... Or at least explained here :-)

Thanks!

**Comment by smikes** [comment]
Thanks for bringing this up.

This is intentional, and it is documented, but not in `npm`'s documentation.  This is done by normalize-package-data, and documented here <https://www.npmjs.com/package/normalize-package-data#what-normalization-currently-entails>

> The values in optionalDependencies get added to dependencies. The optionalDependencies array is left untouched.

I think the underlying problem is that `npm` uses the `package.json` of an installed dependency as a place to store metadata, record information about how dependencies were resolved, etc.  This is frequently surprising, especially when package authors expect that their package will be installed exactly as packed.

I believe some of these issues may be addressed in a later version of `npm` - probably `npm@4` which will involve changes to the cache algorithm.  If `npm` switches to using a content-addressible store, then it will no longer be possible to store metadata inside the package, so `npm` will no longer modify the `package.json`.

I'm not very familiar with this part of the code, so if you have questions you can raise them on the IRC channel or here -- and I will forward them to the people who actually know this stuff.

Thanks!

**Comment by abbakym** [comment]
Thank you @smikes for the links and explanations.

I don't think I really want to know why it is done though. And you're right that `npm`'s decision to use `package.json` as metadata storage is (one of those numerous `npm` decisions that are) quite surprising. Thing is that `npm` looks quite simple on the outside - unless you start using it and bumping into issues like this one.

On the other hand, I think issues like this one are experienced by those who need to use `npm` in internal production environments - where you need to track multiple registries, approve used dependencies etc. Taking into account that `npm` was initially designed for open source, it is quite understandable that it takes time to mature in other areas. So - looking forward for `npm@?` ;-)

**Comment by iarna** [comment]
Closing this as answered– if I misunderstood and you're requesting a concrete change, please open a new ticket.
