### ISSUE TITLE
error message when trying to install unpublished package could be improved

### ISSUE THREAD

**Issue by tkissing** [npm/npm#7760]
I upgraded to `chai-as-promised@4.3.2` on multiple machines yesterday. Today I checked my project out on a different computer and when running `npm install` got a failure because that version does not exist. Turned out that is correct, @domenic unpublished it intentionally, see https://github.com/domenic/chai-as-promised/issues/96 
However, the npm error message is the same as if I had tried to install a version that never existed, leading me down some rabbit holes I'd rather had avoided.

Given that npm knows the version had been published (see the "time" property in `npm info chai-as-promised` output), it would be nice if `npm install` gave me a more concrete error message, eg. "version has been unpublished: chai-as-promised@4.3.2" instead of the current "version not found: chai-as-promised@4.3.2"

**Comment by smikes** [comment]
Thanks!  This is a good feature request.

It will probably get put in the queue for after the next major version of npm (`npm@3.0.0` is nearing release).

**Comment by othiym23** [comment]
A thing to keep in mind is that the underlying data that npm relies upon to detect that a package has been unpublished is only available on registries built around the `npm-registry-couchapp` code base – there's no requirement that any kind of tombstone be left upon package unpublishing, and it's probably not safe to assume that the current behavior is always going to be there. That's fine, because the npm registry team has no plans to change this, but at the same time, I doubt they have strong feelings about _preserving_ it.

That said, this would be a handy, small affordance, and as such, is something that the team would welcome as a patch. The CLI team itself isn't going to have time to work on this in the next 6-12 months, though, and so we're going to close this feature request (and marking it as `patch-welcome`, in case a developer in the npm community wants to contribute it). Thanks for your time!
