### ISSUE TITLE
Fail to install NativeScript

### ISSUE THREAD

**Issue by yt7589** [npm/npm#7767]
When I try to install the NativeScript( a platform allow us to write program in javascript then convert it to native IOS and android native application) on my windows 7 x64 machine it prompt these messages:
```
npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0
npm WARN excluding symbolic link docs\stylesheets\hightlight.css -> ../../node_modules/highlight.js/src/styles/solarized_light.css
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\software\\nodejs_0_12\\\\node.exe" "E:\\software\\nodejs_0_12\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
-
```

**Comment by othiym23** [comment]
Did npm leave behind an `npm-debug.log` file when it crashed? The absence of a stacktrace leads me to believe this may be some kind of bug in Node itself, but I would need to look at a debug log to be able to say more.

**Comment by yt7589** [comment]
Where to find the debug log of npm?

**Comment by othiym23** [comment]
@yt7589 It should be in the same directory from which you were running npm. If it doesn't exist, could you try running `npm -ddd install -g nativescript`? You may need to increase the size of the `cmd.exe` buffer by a significant amount in order to capture enough of the scrollback to find anything interesting.

**Comment by yt7589** [comment]
I found npm-debug.log file. How to upload this file?

**Comment by othiym23** [comment]
The easiest thing to do is to upload it to gist.github.com.

**Comment by yt7589** [comment]
Hi. This is my npm-debug.log. http://119.57.160.206/npm-debug.log

**Comment by smikes** [comment]
@yt7589  This looks like it might be a bug in node 0.12 -

```
3808 silly gunzTarPerm modified mode [ 'test/variadic.js', 436, 438 ]
3809 verbose stack TypeError: Cannot read property 'emit' of null
3809 verbose stack     at TLSSocket.connectionErrorHandler (E:\software\nodejs_0_12\node_modules\npm\node_modules\request\request.js:210:24)
3809 verbose stack     at TLSSocket.g (events.js:199:16)
3809 verbose stack     at TLSSocket.emit (events.js:129:20)
3809 verbose stack     at net.js:451:14
3809 verbose stack     at process._tickCallback (node.js:355:11)
3810 verbose cwd E:\software\nodejs_0_12
3811 error Windows_NT 6.1.7601
3812 error argv "E:\\software\\nodejs_0_12\\\\node.exe" "E:\\software\\nodejs_0_12\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript"
3813 error node v0.12.0
3814 error npm  v2.5.1
3815 error Cannot read property 'emit' of null
3816 error If you need help, you may report this error at:
3816 error     <http://github.com/npm/npm/issues>
3817 verbose exit [ 1, true ]
```

For the moment, can you try upgrading to 0.12.1 or  downgrading to 0.10.38 and see if that fixes the problem?

**Comment by othiym23** [comment]
The node issue is not fixed in Node.js 0.12.1, unfortunately. That only includes fixes for the recently disclosed OpenSSL vulnerabilities. It _will_ be fixed in Node.js 0.12.2, which will be coming within the next week or two, pretty much exactly for this bug and a few others. If you need it addressed sooner, either roll back to Node.js 0.10.38, or give io.js 1.6.2 a shot.

Closing as resolved.
