### ISSUE TITLE
Make lib/completion.js an external, generic node module

### ISSUE THREAD

**Issue by louisremi** [npm/npm#7769]
A great amount of work has been put in creating the completion module used internally by npm. People have tried to extract it as an independent and generic module (see [node-tabtab](https://github.com/mklabs/node-tabtab)), but their versions are lagging (far) behind and keeping up with upstream changes is anything but easy.

It would be a great addition to the ecosystem if npm exported this lib to an official external generic node module. If we agree on usefulness and feasibility, I'm willing to give this task a try.

**Comment by smikes** [comment]
What would be the goal?  To provide a framework for adding custom completion for other commands into various shells?

**Comment by louisremi** [comment]
Yes!

**Comment by iarna** [comment]
I would be more inclined to take a patch moving npm’s completion to an existing widely used and well supported completion module then to try to bootstrap one from npm’s code. If you are still interested in working on this, I think your time would be better spent getting something else as complete as npm’s and providing a PR to switch npm to using them. The first step in getting that kind of PR into npm would be to improve test coverage for the completion code. Right now, I don’t have confidence that we could swap out the code and maintain existing behavior because the coverage is so minimal.

I’m going to close this issue because the CLI team isn’t going to be working on it. Thank you for bringing this up!
