### ISSUE TITLE
`npm config set` always modifies ~/.npmrc

### ISSUE THREAD

**Issue by givankin** [npm/npm#7771]
There are actually multiple issues with that.

First, it can lead to conflicts in shared environments (e.g. a build server within a company). This is an easy way to shoot each other's legs.

Second, if local (project-level) `.npmrc` exisits, `npm set`/`npm config set` still modifies the global one. If it would modify the project-level config, that would allow to partially solve the first issue.

Third, it is kind of surprising. E.g. I had a few registries and other parameters commented in my `~/.npmrc`, thinking (naive!) that I could use it to quickly switch between configurations instead of using artillery like [npmrc library](https://www.npmjs.com/package/npmrc). And then someone else's postinstall script erroneously does `npm config set ...`, and all my comments are dead and gone.

**Comment by smikes** [comment]
Thanks for the bug report.

I believe that `npm config set` will always write the user-config, and that `npm` believes it has the right to rewrite that file at need. :-(

Modern versions of `npm` (post-2.1) should support multiple registry configurations, which may alleviate the need to keep multiple commented-out registry settings.

**Comment by rlidwka** [comment]
> E.g. I had a few registries and other parameters commented in my ~/.npmrc

maybe npm shouldn't remove comments when doing `npm set`

**Comment by smikes** [comment]
> maybe npm shouldn't remove comments when doing npm set

Sounds reasonable to me.

OP (@abbakym) should we treat this as a bug report (running `npm set` removes comments from `.npmrc`)?

**Comment by othiym23** [comment]
This is a feature request.

While I agree that it's a reasonable request, it's also far trickier than it looks, because the current configuration framework has no knowledge of the original configuration file by the time it saves updated configuration information, and a third-party module (`ini`) is used to serialize the configuration to disk. 

Most of the arguments that apply to npm's rewriting of `package.json` apply here – this is _really_ a file that's not meant to be maintained by a person, and isn't even really meant to be _read_ by humans (the syntax we use for saving multi-registry information is a good example of this). I know there are tools out there that allow you to have multiple `.npmrc` files (along with the `--userconfig` command-line option), and those are probably better to use in the vast majority of cases when it might seem tempting to just comment stuff out.

**Comment by othiym23** [comment]
> And then someone else's postinstall script erroneously does npm config set ..., and all my comments are dead and gone.

That sort of behavior is pretty hostile to downstream users and should be filed as bugs against the packages that do it. I get how that might seem handy to package maintainers, but it's the sort of thing that should be documented in readmes rather than automatically applied via scripts.

**Comment by othiym23** [comment]
There's even more going on in this issue than there appears at first:

1. There are actually _four_ different kinds of `.npmrc` files evaluated by npm's configuration framework: a per-package `.npmrc` at `”$(pwd)/.npmrc”`, a per-user file at `”$HOME/.npmrc”` (what @givankin calls “the global config”), a global file installed at `”$(npm -g prefix)/etc/npmrc”`, and a special “`npmrc`” bundled into the CLI package itself (used to ensure that things stay installed in the correct places on Windows). `npm config set` and `npm config set -g` only allow you to edit two of those four kinds of files; I agree that if npm is going to support per-package configuration, it should be configurable via the CLI. The CLI would need a new option to tell `npm config` to modify the per-package configuration, but beyond that, the existing code should make it pretty clear how to add the new type of editing.
2. It’s not _easy_ to make it so that editing the config preserves the existing formatting and comments in the config files, but that doesn’t mean it shouldn’t be done. Config file parsing and storing is handled by a dependency, and making it preserve comments is tricky, but given that the file format supports comments (unlike the JSON used by our friend `package.json`), the CLI shouldn’t be stomping on those values. A change to make that non-destructive (and maybe to handle #10782, which is another symptom of how the config serialization currently works) would be _extremely welcome_).
3. It’s out of scope for npm to pull in the behavior of something like [`npmrc`](http://npm.im/npmrc), but do be aware that the command-line option [`--userconfig`](https://docs.npmjs.com/misc/config#userconfig) is available and can be used in aliases and shell scripts to switch between multiple npmrc files at runtime. Not as elegant, but still relatively straightforward. I think the need for this is reduced somewhat by careful use of scopes and modifying npm to not remove comments from config files.

All of the above is most likely going to remain out of scope for the CLI team for the next 6-12 months, so I’m going to close this feature request. That said, if anyone is interested in making the changes described in 1 or 2 above, open up a pull request and the team can provide support as needed. Thanks to everyone for their time, discussion, and patience!
