### ISSUE TITLE
How to prevent  recursively install dependencies using npm install

### ISSUE THREAD

**Issue by vgupta** [npm/npm#7778]
Hi,

I am installing depdendency using npm install 'module name'. Then this is installing all dependency but this is creating too much long path like (`\trunk\desktop\app\node_modules\html-pdf\node_modules\phantomjs\node_modules\fs-extra\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\test`). 

This is creating problem in window (A file copy operation fails when files or folders have long paths in Windows or linux). 

is there any alternative way to install all dependency in top root of local module path?

**Comment by smikes** [comment]
Unfortunately there is no simple solution to this well-known problem.  The next major version of `npm` (`npm`@3.0.0), which will be released soon, addresses this by putting more dependencies in the root `node_modules` folder.

If you have a successful install, you can try running `npm dedupe` to decrease the depth of your tree.  

You can also install specific versions of a package subdependency directly (e.g., for `glob` --  `npm install glob@5.0.0` into your app.  `npm` should detect this during `npm install` and use it instead of installing the full glob dependency tree twice.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by ukriseq** [comment]
Yes it sure is a problem - Can it be fixed please?

Thanks a mil

**Comment by iarna** [comment]
@ukriseq Good news, `npm@3` is the latest version of npm now, so updating your npm will get it and its new maximally flat `node_modules` folder. It's also included with node 5 and up.
