### ISSUE TITLE
npm publish of module that includes ios framework is corrupted on npm install

### ISSUE THREAD

**Issue by ldeluca** [npm/npm#7825]
I opened a stackoverflow question about this issue yesterday, details here: http://stackoverflow.com/questions/29377635/npm-publish-module-includes-ios-framework-when-npm-install-of-that-module-the 

But basically I have an npm module that includes an ios framework.  When I publish this module to npm I don't see any errors.  When I go to install the module the ios framework is corrupt.  It doesn't happen for all ios frameworks, just this one in particular.  I'm publishing to a private npm repo.  Any advice on how to debug this would be greatly appreciated.

**Comment by samjarman** [comment]
+1

**Comment by knight9999** [comment]
+1

**Comment by othiym23** [comment]
For security reasons, npm has to be very careful about how it handles symlinks, and it appears that the way that XCode sets up those symlinks is incompatible with the way that `node-tar` (the tar library used by npm) safely packs tarballs. This is kind of an edge case that I don't think rises to the level of a bug, because npm's doing what it's supposed to do in the general case, but it does make it tough to package third-party frameworks into npm packages. My suggestion is to hand pack the framework into an archive (zipfile? tarball?), and then write a postinstall script to unpack that archive at install time.

Because this is an edge case more than a bug, I'm going to close this issue, but if somebody runs across this and wants to take a shot at putting together a patch that passes `node-tar`'s tests while also not mangling symlink-heavy trees like iOS and OS X frameworks, the CLI team would be happy to review it. Thanks for your time!
