### ISSUE TITLE
`npm install, `npm ls` lies: wrong version number is displayed

### ISSUE THREAD

**Issue by mardiros** [npm/npm#7832]
Here is an example of npm install:

  $ npm install engine.io-client
  engine.io-client@1.5.1 node_modules/engine.io-client
  ...
  ├── xmlhttprequest@1.5.0
  ...

But, take a look here:

  https://registry.npmjs.org/engine.io-client/ 
  line 28:
  https://github.com/Automattic/engine.io-client/blob/master/package.json#L28

It's not the true,
it install a tarball from github, which is

  https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz  

but xmlhttprequest@1.5.0 is from the registry point of view ( https://registry.npmjs.org/xmlhttprequest/ )

  http://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.5.0.tgz

If you download both file, they are really not the same.

    diff node-XMLHttpRequest-a6b6f296e0a8278165c2d0270d9840b54d5eeadd/lib/XMLHttpRequest.js package/lib/XMLHttpRequest.js | tail
    ---
    >       syncProc = spawn(process.argv[0], ["-e", execString]);
    >       while((self.responseText = fs.readFileSync(syncFile, 'utf8')) == "") {
    >         // Wait while the file is empty
    531d452
    <       self.responseText = fs.readFileSync(contentFile, 'utf8');
    535c456
    <       fs.unlinkSync(contentFile);
    ---
    >       fs.unlinkSync(syncFile);

npm should inform of the correct source of the package.

And to me it's sound like a security issue, I can lie on a dependency to introduce malicious code)

**Comment by othiym23** [comment]
```
$ cat node_modules/engine.io-client/node_modules/xmlhttprequest/package.json | json version
1.5.0
$ cat node_modules/engine.io-client/package.json | json dependencies.xmlhttprequest
https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
$ curl -L https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz | tar xfz - node-XMLHttpRequest-a6b6f296e0a8278165c2d0270d9840b54d5eeadd/package.json && json -f node-XMLHttpRequest-a6b6f296e0a8278165c2d0270d9840b54d5eeadd/package.json version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167    0   167    0     0    291      0 --:--:-- --:--:-- --:--:--   291
100  9735  100  9735    0     0   8257      0  0:00:01  0:00:01 --:--:-- 49166
1.5.0
```

npm isn't getting `xmlhttprequest`'s version from the registry -- it's what's in the tarball that `engine.io-client` depends on. This is no more nor less a security issue than any other package using tarball or git dependencies – as long as `package.json` is present and valid (i.e. is well-formed JSON and contains the fields npm requires) in the tarball or repository, npm will install the package without complaint. The only way to uniquely identify a package is by its tarball's shasum, which is why packages installed from the registry have shasum validation. If this way of packaging `xmlhttprequest` makes you uncomfortable, take it up with the `engine.io-client` maintainers. npm is working as designed here.
