### ISSUE TITLE
404 Error after installing script

### ISSUE THREAD

**Issue by Abd3lk4d3r** [npm/npm#7837]
Hello All ,
I just build a script with npm and get 404 error when running it with npm run serve 
Any help please ?

**Comment by KenanY** [comment]
@Abd3lk4d3r `404` error sounds like you might be trying to download a package that does not exist... hard to tell without an error log. Is a `npm-debug.log` file generated in your current folder? If so, can you upload it as a [gist](https://gist.github.com/) and post the link here so that I can take a look?

**Comment by Abd3lk4d3r** [comment]
I saw 404 error not in npm log , I saw it after installing all , in localhost:8080 can't access anything 
without seeing 404 error .

Thanks .

**Comment by KenanY** [comment]
@Abd3lk4d3r How is this an `npm` issue if `npm` is not producing the error?
