### ISSUE TITLE
Per directory tree .npmrc file.

### ISSUE THREAD

**Issue by chevex** [npm/npm#7848]
Related: https://github.com/npm/npm/issues/4751

I love that you can specify a per-project `.npmrc` by placing the file in the root of the project. However, it sucks having to add an identical `.npmrc` to a set of projects. For example, here is my current setup:

I work for a company that has their own private registry. It is configured to pass requests through to the public registry when the module isn't in the private one, so it is effectively transparent for installing both private or public modules.

In order to authenticate with this private registry I need to supply an auth key that my company gave me.

```
registry = https://companyname.artifactoryonline.com/companyname/api/npm/npm-virtual
_auth = ***OMITTED***
always-auth = true
email = api@companyname.com
```

This works great except I also manage modules on the public registry with a different account. Is it possible to be authenticated as two different accounts to two different registries? How can I publish modules to both our private registry and my public registry account? Until I discovered project-centric .npmrc files I was simply commenting out the above auth options and uncommenting my public ones, and vice versa. Now I'm trying to use the project .npmrc files to override in those specific projects.

The project-specific config files work fine but it would be even better if I could create a single `.npmrc` file one directory higher than the project. I have about 12 different repositories on my machine for work and they are all in a `~/companyname` directory. If I could drop that config file right there, I believe that would solve the problem of me needing to copy that file into every new repo I clone, and add that file to the .gitignore for each one as well.

Maybe there's an easier way to accomplish this already. Feel free to educate me if I'm missing something :)

PS - I wish my company was using scopes since I see you can associate a scope with a specific registry. But they are not and I don't have control over the private registry  :(

**Comment by othiym23** [comment]
> Is it possible to be authenticated as two different accounts to two different registries?

Sure! Just run 

```
npm login --registry=https://companyname.artifactoryonline.com/companyname/api/npm/npm-virtual --always-auth=true
```

and then put the per-project registry information in each project's `.npmrc` or `package.json` (not the credentials, just the `registry` configuration). `npm@2` stores your credentials mapped so a simplified ("nerfed") version of the registry URL, so it will use the correct credentials for each registry, as well as allowing you to be logged into multiple registries simultaneously.

If Artifactory doesn't support actually running the `login` or `adduser` commands against their npm emulation endpoints, things are a little trickier, but not impossible. Here's how to do it:

```
$ cd $(npm -g root)/npm
$ node -pe 'require("./lib/config/nerf-dart.js")("https://companyname.artifactoryonline.com/companyname/api/npm/npm-virtual")'
//companyname.artifactoryonline.com/companyname/api/npm/
```

That gets you the nerfed version of the registry URL, and then you need to edit `$(HOME)/.npmrc` to include the various bits and bobs you had above:

```ini
; you don't actually need to put this here – it can go in each project's .npmrc or package.json
registry = https://companyname.artifactoryonline.com/companyname/api/npm/npm-virtual
//companyname.artifactoryonline.com/companyname/api/npm/:_auth = ***OMITTED***
//companyname.artifactoryonline.com/companyname/api/npm/:always-auth = true
; email isn't needed once you've logged in
```

That's kind of onerous, which is why eventually we'll add a new command, `npm registry`, to take the rough edges off that process, but I haven't had the available cycles to put it together yet. Anyway! Try that `npm login` command I included above and maybe you'll be lucky and won't have to do any of the above. Either way, npm is indeed meant to be used with multiple registries simultaneously, and we're working on making that a more robust and pleasant experience.

Good luck!

**Comment by chevex** [comment]
Thanks for this! Sorry for the late reply, but this was really helpful.

**Comment by chevex** [comment]
Thanks so much for this!

I do have one question. I don't have a password, only an auth key that is supplied to `_auth=` in `.npmrc`. What do I do when the `npm login` command asks for a password?

**Comment by othiym23** [comment]
If you have an `.npmrc` with the auth information in it, you don't need to run `npm login`, as `_auth` already contains the username and password needed by npm (separated by a colon and Base64-encoded) to do write operations and publishes.

**Comment by ghengeveld** [comment]
Just FYI, Artifactory has a [note on authenticating](https://www.jfrog.com/confluence/display/RTF/Npm+Repositories#NpmRepositories-UsingLoginCredentials) in their documentation.
Basically you can run this command to get the right contents for your .npmrc file:

```curl -uUSERNAME:PASSWORD "https://COMPANYNAME.artifactoryonline.com/COMPANYNAME/api/npm/REPOSITORY/auth/SCOPE"```

It will return something like:

```
@my-scope:registry=https://my-company.artifactoryonline.com/my-company/api/npm/my-registry/
//my-company.artifactoryonline.com/my-company/api/npm/my-registry/:_password=base64-encoded-password
//my-company.artifactoryonline.com/my-company/api/npm/my-registry/:username=my-username
//my-company.artifactoryonline.com/my-company/api/npm/my-registry/:email=my-email@address.com
//my-company.artifactoryonline.com/my-company/api/npm/my-registry/:always-auth=true
```

Which you can save to .npmrc in your project.
