### ISSUE TITLE
Update package.json without triggering the downloading of artifacts

### ISSUE THREAD

**Issue by alfonso-presa** [npm/npm#7865]
To ease the development of tooling around npm, it would be nice to have a way to add dependencies to package.json without triggering the downloading of artifacts. This is specially useful to chain different scaffolding processes on a single project without triggering several parallel instalation processes (that leads to issues like the ones reported here: https://github.com/npm/npm/issues/5948).

Some background (little bit oftopic, I know):
* Yeoman's 'generator-angular' has issues because it uses another generator called 'generator-karma' behind the scenes and at the end it triggers two different install processes for both generators.
* One way of solving the issue (I'm not saying is the only one :) ) right now is to modify the package.json file from generator-karma with out triggering the npm instalation process.
* This can't be done consistently (keeping npm features like save-bundle or safe-prefix) without duplicating npm's code.
* So.... it would be nice to be able to invoke programmatically npm (even via API or command line) so it modifies the package.json without downloading anything (at least nothing more than the required meta-data). Something like "npm add-dependency karma".

Thanks!

**Comment by othiym23** [comment]
The proper way to deal with this is for Yeoman and its associated generators to figure out the dependencies they want installed and then write `package.json` once themselves. Since `package.json` is JSON itself, it's pretty easy to write utilities to manipulate its contents, and it feels, for want of a more precise phrase, _weird_ to have the npm CLI adding and removing dependencies from its single source of truth without bringing the state of the installed dependencies in line with what's in `package.json`. I think this is something best done outside of npm.
