### ISSUE TITLE
How can I know my package is installed in local or global

### ISSUE THREAD

**Issue by qiu8310** [npm/npm#7866]
I add a preinstall script in `package.json`, like this:

```
"scripts": {
    "preinstall": "node ./scripts/install.js",
}
```

In `./scripts/install.js`, how can I figure out this package is installed in local or in global ?

**Comment by smikes** [comment]
Can you tell us a bit more about your use case, and what you are trying to accomplish?  In general the use of `install` and `preinstall` scripts is discouraged, except for packages that need to use the system compiler to compile a native module (typically some C/C++ code).

**Comment by qiu8310** [comment]
Oh，I just want to check the global environment, or backup some files when user install my package in global.

e.g: I write a package called [smart-npm](https://github.com/qiu8310/smart-npm), when user global install this package, it will replace the original npm file with a new one, when global uninstall this, it will recover the original npm file；but I don't want to replace the original npm file when user install this package in local.

After I post this question, I figured out a method: Use `preinstall` to replace the original npm file, and use `postinstall` to check if the new npm file is install in global, if not, recover the original one.

I don't know if I am doing this in the right way ?

**Comment by smikes** [comment]
Hm, well, I would advise you against renaming global files such as `npm` even when your package is installed globally  -- maybe you could work around it by encouraging your users to define an alias or shell function, if you want to catch calls to the `npm` program.

But if you are committed to doing it this way, I would probably use a `postinstall` script, yes.  Be careful when writing to `npm` from a lifecycle script, because `npm` is already running, but not all parts have been loaded yet, so you may wind up with some very hard-to-isolate bugs and race conditions.

**Comment by qiu8310** [comment]
@smikes, thank you very much, I did have came cross some problems you mentioned, maybe I should not redefine the npm command. Anyway, you can close this issue now. Thanks again.
