### ISSUE TITLE
npm adduser : "Unknown error while authenticating"

### ISSUE THREAD

**Issue by tolokoban** [npm/npm#7876]
I can't add a new user for "npm publish". I get this error:
```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:tolokoban
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:tolokoban
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:tolokoban
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "adduser"
npm ERR! cwd /home/tolokoban/Code/github/ToloFrameWork/src
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
```

**Comment by othiym23** [comment]
Unfortunately, publishing no longer works with versions of npm older than `npm@1.4.0` (also, the latest stable version of npm is `npm@2.7.5`, so you're a ways behind). [Update to a newer npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and this problem should go away (at the very least, you should get a more informative error message – you may need to go onto the npm web site and change your password, if it's been a while since you did so).

**Comment by psinghsp** [comment]
I am getting this error on npm 2.10.1 on Ubuntu.

singh@pawandell:~/websocket/ws/lib$ npm adduser
Username: xxxx
Password: 
Email: (this IS public) xxxx@silver-peak.com
npm ERR! Linux 3.19.0-20-generic
npm ERR! argv "/home/xxxx/nodejs/bin/node" "/home/xxxx/nodejs/bin/npm" "adduser"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:xxxx
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/psingh/websocket/ws/lib/npm-debug.log
psingh@pawandell:~/websocket/ws/lib$ npm --version
2.10.1

**Comment by designeng** [comment]
I have the same problem with 
npm --version 
2.14.7
OS X Yosmite

**Comment by powerumc** [comment]
I have it problem, too..

ubuntu 14.04 LTS
1.3.10

You should be the upgrade npm.
type in command line.

npm install -g npm

**Comment by shivangsanghi** [comment]
othiym23 is correct.. I have successfully published my package.

Unfortunately, publishing no longer works with versions of npm older than npm@1.4.0 (also, the latest stable version of npm is npm@2.7.5, so you're a ways behind). Update to a newer npm and this problem should go away (at the very least, you should get a more informative error message – you may need to go onto the npm web site and change your password, if it's been a while since you did so).

**Comment by Kurtz1993** [comment]
Happened to me today.
npm -v
3.8.6

OS X El Capitan 10.11.4

**Comment by ChuckkNorris** [comment]
Happened to me as well with version 3.8.6.
Oddly enough after pressing return, it shows the password dialog twice:
Username: xxxx
Password:
Password: xxxx
Email: (this IS public) xxxx@mymail.com

**Comment by TJMoats** [comment]
There is currently some problems with an npm deployment that may be causing the 500 issues.

>Identified - We have identified a configuration problem in a deploy and engineers are correcting it. 
Apr 26, 00:22 UTC

>Investigating - We are investigating an elevated rate of 500 responses returned during private package installation.
Apr 26, 00:12 UTC

http://status.npmjs.org/

**Comment by ChuckkNorris** [comment]
Looks to be working now. Thanks @TJMoats !
