### ISSUE TITLE
Warning "root" does not have permission to access the dev dir #454

### ISSUE THREAD

**Issue by cliveb** [npm/npm#7888]
tjwebb opened this issue on Jun 7, 2014 - still open April 7, 2015
https://github.com/TooTallNate/node-gyp/issues/454

**Comment by othiym23** [comment]
That's because this is an issue with `node-gyp`, not npm. Until it's fixed in `node-gyp`, there's not a lot we can do about it here. The workarounds on TooTallNate/node-gyp#454 that involve using `--unsafe-perm=true` are working around the issue by running the `nod-gyp` rebuild as root. We update to new versions of `node-gyp` as soon as they're released, but it's not a dependency the npm team maintains.

**Comment by cliveb** [comment]
Thanks for the update. NodeSchool makes use of node-gyp, I've added an issue to.  https://github.com/TooTallNate/node-gyp/issues  

Install the core workshops with these commands:
npm install -g learnyounode
npm install -g javascripting
npm install -g git-it
npm install -g how-to-npm
npm install -g stream-adventure
