### ISSUE TITLE
failures in optionalDependencies should be silenceable

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#7892]
if an optionalDependency fails to install due to some node-gyp issue, the user is still presented a sub-optimal experience.

For example: https://github.com/ember-cli/ember-cli/issues/3857

As you can see, the user believes the installation was a failure, but it in-fact it appears only to been an "Acceptable failure" in an optionalDependency.

In the past, it was possible to silence npm + node-gyp, which prevented these details from leaking.
Now, short of sub-process exec, there is no reasonable way to control the output of node-gyp, and remedy these UX issues.

**Comment by othiym23** [comment]
(Side note: the code that handles how output is presented when lifecycle scripts is run (which is how `node-gyp rebuild` ends up getting called) hasn't been changed since 2013, so I'm pretty sure that the fact that `node-gyp` wasn't displaying output was an inadvertent side effect or bug, not how it was supposed to work.)

The way things are now, running a lifecycle script causes `npmlog` to suspend printing and to internally buffer log messages while lifecycle scripts run (and then dump the enqueued `npmlog` output once the lifecycle script completes). The `node-gyp` child process is just handed the parent process's stdio file descriptors, so `stdout` and `stderr` are passed straight through the npm process to the user untouched. This is true regardless of what kind of dependency is being installed (the lifecycle script runner doesn't know or care about the dependency's context, it just runs scripts for lifecycle phases in places).

Were this to be changed, the right way to do it would be to gather up output and then display it after the fact if `--silent` isn't set / it's not an `optionalDependency`. This would require changes to `lib/utils/lifecycle.js` and probably both of `lib/{install,build}.js`. It also assumes that the lifecycle scripts are never going to prompt users for input, which is not always true. This is one of those things that looks simple at the outset, but gets very sticky as soon as you step into it.

**Comment by stefanpenner** [comment]
sounds reasonable.

I believe further control over per install output would be needed to really nail this.
A good default for optionalDependencies would be to be pretty quiet, and only nicely inform `X optionalDep failed to install, for more info`.
Obviously, when someone wants to debug an optionalDependency it should be easy to re-run with more details (or read from some /var/log ilfe)

non optional dependencies, should likely be verbose by default.

Ultimately, more control for cli users and lib consumers would be lovely. This is likely one of the many use-cases that will need bikeshedding before a good solution is reached.

**Comment by es128** [comment]
:+1: (again, not the first time this has been discussed) and thanks @othiym23 for pointing out some technical direction for pursuing this.

Anyone know of an example of a node-gyp module that prompts for user input during install?

Perhaps it is possible to capture the `stdio` and employ timers to make a reasonably good guess about whether the child process is waiting for user input before exposing it's `stdout`. In the typical problematic use cases that I've seen, gyp is writes to `stdout` regularly enough before exiting that this should be good enough to suppress the ugly error messages *most* of the time.

**Comment by stefanpenner** [comment]
Blocking install for user input seems like a poor idea.  Also, I can't imagine the frustration of multiple modules interrupting install.

I believe an improved ux is key. We have to remember that the more confused a user is by these errors the less likely they are to be confident in their judgement On how to proceed. 



The current flood of information is information overload.

 more actionable and concise ui. A clear info message saying optional x failed, but fell back to y. Run again with -v to see full trace, would satisfy

**Comment by es128** [comment]
> Blocking install for user input seems like a poor idea.

Of course, and it doesn't happen with any extension I've seen. But @othiym23 raised the concern that some module out there is doing this - complicating the possibility of resolving the issue. I'm interested to see an example.

**Comment by es128** [comment]
A short term solution may be for npm to print clearer messages before and after ceding control to node-gyp providing context to new users regarding what they are (or may be) seeing there.

iirc something is already there, but it gets drowned out by all the ugly gyp error stuff. The "after" message in particular perhaps could be worked on to provide a better explanation of what happened and what to do next.

**Comment by stefanpenner** [comment]
Ah, I sure am glad I have not encountered one of these. The bower style choose your own adventure interaction session is a great way to pwn yourself.

It might be interesting to have these extensions attempt, but gracefully fall back on failure with an actionable warning that instructs them to run some subsequent command.

For example. npm doctor module-name which could provide further information/ resolution

**Comment by othiym23** [comment]
The CLI team intends to address how script output and logging are handled in a more comprehensive way as soon as we have the cycles to do our much-delayed UX audit. The team's current guess is that we'll do some of this work (including this piece, because it's a clear usability improvement) before the end of 2016. (We make no promises, on account of Stuff Happens.)

In the meantime, #9567 is the current tracking issue for a lot of this logging-based UX, so I'm going to close this issue in favor of it. Thanks for the discussion, and for your patience, @stefanpenner!
