### ISSUE TITLE
Error installing build dependencies

### ISSUE THREAD

**Issue by najela** [npm/npm#7903]
I had the following error while installing the build dependencies for [this github repository](https://github.com/jquery/learn.jquery.com). 

https://gist.github.com/najela/051399f9c85e333a73ff

**Comment by KenanY** [comment]
@najela 

``` sh
$ git show v1.2.30
tag v1.2.30
Tagger: isaacs <i@izs.me>
Date:   Wed Jun 12 10:51:07 2013 -0700
```

`npm@1.2.30` is over a year old and no longer supported. I am willing to bet that [upgrading `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) will solve your issue, seeing as how the `^` semver operator is newer than your version of `npm`, hence the error.

As an aside, I would also recommend [upgrading Node.js](https://github.com/npm/npm/wiki/Troubleshooting#see-what-version-of-node-youre-running) as well, since v0.8 is just as old.

**Comment by najela** [comment]
@KenanY  Thanks a million. Updating fixed the problem. I wonder why this virtual boxes always ship with old stuff  :P
