### ISSUE TITLE
npm ERR! UNKNOWN, symlink '../coffee-script/bin/coffee'

### ISSUE THREAD

**Issue by xiongsenlin** [npm/npm#7908]
```
npm WARN package.json edx@0.1.0 No repository field.
-\|/--\|/-\|/--\|/-\-\|/npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.5
npm ERR! path ../coffee-script/bin/coffee
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../coffee-script/bin/coffee'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.5
npm ERR! path npm-debug.log.c7049d41324fc5b551f59c904d0a4f25
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.c7049d41324fc5b551f59c904d0a4f25'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log


Captured Task Output:
---------------------

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "http://registry.npmjs.org/" || (echo setting registry; npm config set registry http://registry.npmjs.org/)
npm install

Build failed running pavelib.servers.devstack: Subprocess return code: 255
```

**Comment by smikes** [comment]
It looks like `npm` tried to make a symbolic link while installing the package, but ran into an error.  Is it possible that your filesystem doesn't support symbolic links?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest` .  You can even put this in your Travis configuration -- see here for an example .travis.yml file that runs with the latest `npm`: https://github.com/reid/node-jslint/blob/master/.travis.yml

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
