### ISSUE TITLE
Run "npm adduser" silent?

### ISSUE THREAD

**Issue by Z3roCoder** [npm/npm#7910]
Hello. I currently have a huge problem
I have an automatic publishing-process for my npm packages. Now I have one problem - On every build, a new version of npm gets installed.

Before I can publish something, I have always to use "npm adduser" - Can I somehow pass the username, pass and email as parameters? Because my build-script cannot pass values for those prompts or can it?

**Comment by thriqon** [comment]
Could you copy the `~/.npmrc` file containing the authentication information to the build system, thusly bypassing `adduser` totally.

**Comment by Z3roCoder** [comment]
Sadly, this is not possible for me.

**Comment by smikes** [comment]
Is this still a problem for you?

This is achievable on some build systems (Travis, for example) by creating environment variables that will pass the user, password etc. to `npm`, and encrypting them so that only the build system can read them.  However, this varies between build systems.

Instead of using `npm adduser` you can use `npm config set` or set the environment variables that also affect the `npm` config -- see https://docs.npmjs.com/misc/config for a complete list of the ways to pass configuration information to `npm`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
