### ISSUE TITLE
Check peerDependencies before installing

### ISSUE THREAD

**Issue by piranna** [npm/npm#7917]
On npm v2.7.4, peerDependencies are checked as a last step only as a sanity-check. I think they should be check as soon as possible on npm@3 and give them precedence on the install process at least on the preinstall and install steps, so if they fails their dependents don't get installed.

**Comment by othiym23** [comment]
`peerDependencies` will [never be implicitly installed](https://github.com/npm/npm/issues/6565#issuecomment-74971689) as of `npm@3`, and will only trigger a warning instead of an error when they're not satisfied. They work much better as an advisory notice than a compulsory part of the installation process, especially given that one of the overall goals of npm is to help developers avoid dependency hell. Closing this in favor of #6565.

**Comment by piranna** [comment]
I know they will not be implicitly installed and don't want it, what I want is that when installing them, they have a higher precedence in the dependencies resolution algorythm and the packages that defined them don't get installed until their peerDependencies do it. This would not only prevent to install things that later could be useless because their peerDependencies are not meet, but also could help to solve dependency problems at install time (at this moment the packages install order is somewhat random and you can't be able to define it...).
