### ISSUE TITLE
Case sensitive dependencies?

### ISSUE THREAD

**Issue by taktran** [npm/npm#7933]
I've tried installing `node-hue-api`, which has a dependency on [parseUri](https://www.npmjs.com/package/parseUri) (https://github.com/peter-murray/node-hue-api/blob/master/package.json#L43), however, it seems my npm tries to find [parseuri](https://www.npmjs.com/package/parseuri) (note the lowercase `u`).

I get this error when `node-hue-api` is installed from the `package.json`. However, doing a `npm install node-hue-api` manually does work.

Error:

```
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.7.6

npm ERR! version not found: parseuri@0.0.4
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../nodejs/npm-debug.log
```

**Comment by KenanY** [comment]
I cannot reproduce this on `npm@2.7.6` nor `npm@2.8.1`

``` sh
$ git clone https://github.com/peter-murray/node-hue-api.git
$ cd node-hue-api/
$ npm install
parseUri@1.2.3-2 node_modules/parseUri

traits@0.4.0 node_modules/traits

q@1.0.1 node_modules/q

semver@4.3.3 node_modules/semver

xml2js@0.2.8 node_modules/xml2js
└── sax@0.5.8

chai@1.9.2 node_modules/chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

request-util@0.1.0 node_modules/request-util
└── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.3, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, form-data@0.2.0, tough-cookie@0.12.1, bl@0.9.4, hawk@1.1.1)

mocha@1.20.1 node_modules/mocha
├── diff@1.0.7
├── growl@1.7.0
├── commander@2.0.0
├── mkdirp@0.3.5
├── debug@2.1.3 (ms@0.7.0)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
```

**Comment by taktran** [comment]
It seems like a `package.json` issue when you include `node-hue-api` as a dependency - installing it separately works fine.

I'll try and isolate the problem when I get some time.

**Comment by taktran** [comment]
I've created a repo that shows the problem: https://github.com/taktran/npm-case-bug

> Basically, `node-hue-api` has `"parseUri": "~1.2.3-2"` as a dependency, and `socket.io-client` has `"parseuri": "0.0.2"` as a dependency. `parseUri` vs `parseuri`.

**Comment by smikes** [comment]
This looks like it is a problem in some of the modules.  `require` is case-insensitive, but some filesystems are case-insensitive (Windows and surprisingly OSX) and some are case-sensitive (Linux).

On top of that, somehow you managed to hit the jackpot by getting dependencies on two case-distinct modules, `parseuri` and `parseUri` in the same dependency tree.  I'm going to call for help on this one.  Stay tuned...

**Comment by othiym23** [comment]
This is pretty much a perfect example of why npm no longer supports upper-case letters in package names – this is a problem due to the fact that Node itself is going to end up loading the wrong thing half the time on OS X and Windows filesystems with the default settings (you can make HFS+ filesystems (and I believe NTFS filesystems) case-sensitive, but that's not the default).

You're kinda stuck in a corner right now – somebody's going to need to rework something until only one of `parseuri` and `parseUri` is depended upon by the package. I would say "at a given level in the dependency tree", but when `npm@3` comes out (hopefully soon), it's going to do flatter / deduped installs by default, which will only exacerbate this problem.

I'm sorry I don't have better news. I'll update this issue if I think of a clever way to work around your problem. You can try adding a new dependency that itself depends on one of `parseUri` or `parseuri` and pushes one of them further down the dependency tree so they don't clash, but that feels pretty hacky to me.

**Comment by taktran** [comment]
We've solved it by using [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) =)

**Comment by smikes** [comment]
@taktran I'm glad you've found a way to work around it.  Should we keep this issue open, or can we close it?

**Comment by taktran** [comment]
I think it works for now
