### ISSUE TITLE
Locking Error? 

### ISSUE THREAD

**Issue by courtlandthomas** [npm/npm#7939]
Trying to install npm (via npm install), but getting error:

npm WARN locking Error: EACCES, open '/Users/courtlandthomas/.npm/_locks/express-63a19a0269bff533.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/courtlandthomas/.npm/_locks/express-63a19a0269bff533.lock failed { [Error: EACCES, open '/Users/courtlandthomas/.npm/_locks/express-63a19a0269bff533.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/courtlandthomas/.npm/_locks/express-63a19a0269bff533.lock' }
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

**Comment by othiym23** [comment]
`sudo chown -R $(whoami) "$HOME/.npm"` should take care of that for you – at some point in the past the npm cache's ownership got taken over by root, and you need to reset that. You shouldn't need to do this again, because new versions of npm are more careful about how they deal with permissions. Let us know if the problem comes back, though.
