### ISSUE TITLE
npm install of yeoman failed

### ISSUE THREAD

**Issue by kloyl** [npm/npm#7940]
On windows 8.1 in cmd entered : npm install -g yeoman

I got numerous fetch failed msgs. Contacted the Yeoman support on github, there response follows:
---------------------------
http fetch 406 http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm is trying to fetch that url (which doesn't exist). My guess is you're pointing to a github tarball instead of a version.
-------------------

Installs for Bower and Angular-Generator also failed. Other installs including Grunt worked fine. Any help will be appreciated.

best regards,
kenneth lea
lea.kenneth@gmail

**Comment by sindresorhus** [comment]
The `yeoman` module was deprecated 2 years ago. The install output clearly says so...

You want `npm install -g yo`.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by kloyl** [comment]
Sam,

Thanks for the followup. I changed my python version from a 3.x to 2.x and
did a successful install of yo.

thanks,
k.

**Comment by smikes** [comment]
Awesome!  Glad you got it fixed!

**Comment by othiym23** [comment]
Closing as resolved!
