### ISSUE TITLE
not able to install phonegap

### ISSUE THREAD

**Issue by dilipsingh1982** [npm/npm#7944]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'phonegap' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'phonegap', null ]
6 verbose cache add spec phonegap
7 silly cache add parsed spec { raw: 'phonegap',
7 silly cache add   scope: null,
7 silly cache add   name: 'phonegap',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed phonegap@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'phonegap', range: '*', hasData: false }
12 silly mapToRegistry name phonegap
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/phonegap
16 verbose addNameRange registry:https://registry.npmjs.org/phonegap not in flight; fetching
17 verbose request uri https://registry.npmjs.org/phonegap
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:58:12 PM
20 verbose request id fea4319a23a9226d
21 http request GET https://registry.npmjs.org/phonegap
22 info retry will retry, error on last attempt: Error: certificate not trusted
23 info attempt registry request try #2 at 4:58:22 PM
24 http request GET https://registry.npmjs.org/phonegap
25 info retry will retry, error on last attempt: Error: certificate not trusted
26 info attempt registry request try #3 at 4:59:23 PM
27 http request GET https://registry.npmjs.org/phonegap
28 verbose stack Error: certificate not trusted
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd C:\
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
32 error node v0.12.2
33 error npm  v2.7.4
34 error code CERT_UNTRUSTED
35 error certificate not trusted
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like you might still have the old (pre-2.0) npm self-signed certificate.  Can you try running `npm` with `--ca=null` -- this will tell `npm` to use only your computer's certificate store, not `npm`'s additions.

Another possibility that we sometimes see on Windows is that a program has installed its own self-signed certificate in order to intercept and monitor https traffic (for example, Kaspersky Antivirus HTTPS). For more information, check out https://github.com/npm/npm/wiki/Troubleshooting#ssl-error

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
