### ISSUE TITLE
it's happen when I want to launch a linux package generated by nodewebkit

### ISSUE THREAD

**Issue by radjivC** [npm/npm#7954]
Hi everyone,

I working on a nodewebkit project with a grunt file which build my package for linux, windows and mac, when I launch my app on mac and windows everything is fine but with the linux version I have this error message:

```
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/tmp/linux64/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /tmp/linux64
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /tmp/linux64/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/linux64/npm-debug.log
npm ERR! not ok code 0
```

Thanks for your help

**Comment by KenanY** [comment]
@radjivC `npm@1.3.10` is quite old and no longer supported. You should first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm), although I'm not too sure it'll completely solve your issue here. Something somewhere is running `npm install` in the directory that does not contain a `package.json`: ` /tmp/linux64`, hence the error.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
