### ISSUE TITLE
Error installing generator-angular

### ISSUE THREAD

**Issue by NancyPaul** [npm/npm#7962]
```
C:\>npm install -g generator-angular
npm WARN peerDependencies The peer dependency generator-karma@>=0.9.0 included f
rom generator-angular will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator
-angular will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-angular"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.6

npm ERR! shasum check failed for C:\Users\PATRIC~1\AppData\Local\Temp\npm-12116-
978b5028\registry.npmjs.org\tar\-\tar-0.1.20.tgz
npm ERR! Expected: 42940bae5b5f22c74483699126f9f3f27449cb13
npm ERR! Actual:   d5b61a47bdde9b88fcdd1113418d0f1f8f55923e
npm ERR! From:     http://registry.npmjs.org/tar/-/tar-0.1.20.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log
```
i get this error and i am not able to clear it. Can anyone help me??

**Comment by smikes** [comment]
It looks like you have a corrupt version of the tar package in your local npm cache.  Usually you can fix this by running

```
> npm cache clean tar
```

on your command line.  Can you try that and let us know if it worked or not?

**Comment by damianozaccaria** [comment]
I have the same problem. I try to fix it by running @smikes solution, but don't work.

**Comment by smikes** [comment]
@damianozaccaria , could you please create a new issue and upload the `npm-debug.log` to https://gist.github.com ?

@NancyPaul , were you able to solve the problem by clearing your cache?

I notice you're running `npm@2.7.6`, which is a few weeks old at this point.  The latest `npm` is 2.8.4, with 2.9.0 slated to come out this week.  There are several bug fixes in the new version, though unfortunately I don't think any of them address this issue in particular.

In order to update `npm` on Windows, please follow the guide here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
