### ISSUE TITLE
Installed node.js, getting error

### ISSUE THREAD

**Issue by jaytyo** [npm/npm#7963]
Got the following npm-debug log file.  No idea what to do about it.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'config',
1 verbose cli   'get',
1 verbose cli   'prefix' ]
2 info using npm@1.4.28
3 info using node@v0.10.37
4 error Error: ENOENT, stat 'C:\Users\tyojl\AppData\Roaming\npm'
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Windows_NT 6.1.7601
7 error command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "config" "get" "prefix"
8 error cwd C:\Users\tyojl\Desktop
9 error node -v v0.10.37
10 error npm -v 1.4.28
11 error path C:\Users\tyojl\AppData\Roaming\npm
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]
```
Any help would be appreciated.

**Comment by KenanY** [comment]
@jaytyo This is a consequence of https://github.com/joyent/node/issues/8141, and is an issue with the Node installer for Windows. The workaround is to ensure that `C:\Users\tyojl\AppData\Roaming\npm` exists and is writable with your normal user account.

**Comment by smikes** [comment]
Is this still a problem for you?

The advice @KenanY gives above is good -- you can check out the full writeup here: https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by jaytyo** [comment]
I just installed node.js on my machine and it worked fine.

Thanks for the reply,

Jay Tyo
843-797-9028 (W)
843-709-6303 (C)

**Comment by othiym23** [comment]
Closing as resolved!
