### ISSUE TITLE
install hangs when installing multiple ssh packages when ssh ControlMaster is enabled.

### ISSUE THREAD

**Issue by lxe** [npm/npm#7979]
When npm clones 2 (or more) repos from the same SSH host when [SSH ControlMaster](http://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing) is enabled, it does so in parallel. Git invokes the ssh client for both repos at the same time. 

Let's say we have:

```
  "dependencies": {
    "test-repo-one": "git+ssh://git@github.com/lxe/test-repo-one.git#master",
    "test-repo-two": "git+ssh://git@github.com/lxe/test-repo-two.git#master"
  }
```

When ControlMaster is enabled, the ssh client attempts to create a `.ssh/{whatever}` file that serves as an open descriptor for multiple connections.

There's a race condition here however, when cloning `repo-1`, the socket file is created, but the connection is not yet established by the time repo-2 is being cloned.

The ssh session responsible for `repo-2` sees the existing socket file, attempts to use the connection associated with it, fails (since repo-1 hasn't finished creating it yet), and hangs indefinitely.

This is an OpenSSH bug more than anything, I think.

I've reproduced this generically here:

https://github.com/lxe/npm-ssh-controlmaster-bug

**Comment by malandrew** [comment]
+1

The `npm install` code relies on the `npm cache` code to do anything git related. The cache code only relies on the `git.whichAndExec` function from https://github.com/npm/npm/blob/master/lib/utils/git.js

The other two functions exported by that file `spawn` and `chainableExec` are only used by tests (except `chainableExec` which used three times in `lib/version.js`.

This means that all you need to do is wrap `whichAndExec` in a way that it can timeout and try again if two calls to git to the same host try to start up as master.

**Comment by lxe** [comment]
ref: https://github.com/fschulze/mr.developer/issues/145

**Comment by othiym23** [comment]
Adding a retry to `git clone` operations will solve this specific issue, but at the cost of making the code more brittle, slowing down npm, and exposing more edge cases overall. Adding more edge cases to address an edge case seems like a poor tradeoff to me.

I agree with @lxe that this is something that should be dealt with at the OpenSSH layer (or perhaps even git – I know from painful experience that getting stuff through git to ssh is surprisingly hard). Looking into `ControlMaster`, it looks like all of the controls have to be passed as `-o` options on the command line to which, which can really only be worked around inside npm by writing an ssh wrapper and setting `GIT_SSH` to point at it (which is actually something you could do to work around this problem yourselves). I really, really don't want to do that, because Windows / cross-platform support.

I'd be happy to add a note or land a patch to the documentation warning people that this can happen, as well as pointers to the documentation on how to work around it. I don't think this is a bug in npm, though.

**Comment by lxe** [comment]
> Adding a retry to git clone operations will solve this specific issue, but at the cost of making the code more brittle, slowing down npm, and exposing more edge cases overall. Adding more edge cases to address an edge case seems like a poor tradeoff to me.

It is a bad idea to add retries! I'm trying to come up with a way to utilize `inflight` to wait for the first callback from the clone operation when cloning from `git+ssh://` URIs before spawning the rest of them.

Ideally I would ALSO love to somehow detect whether controlMaster is enabled without sacrificing the time to make some sort of exec call, so this `inflight` delay would happen IFF ControlMaster is enabled. So far this is just a thought....

**Comment by lxe** [comment]
@othiym23 don't close it just yet... I can use this to track the tasks to add the add the documentation about the issue. 

It's still an open bug, since the ControlMaster race case is rather common, yet difficult to track down.

**Comment by othiym23** [comment]
@lxe I closed the issue because this isn't a bug in npm. As I said, I'm happy to land patches to the docs. Inflighting clones at the git host layer sounds like a nightmare factory to me, but if you can make it work without tanking the CLI's performance, I'm happy to look at those changes as well.

That said, you can leave notes on a closed issue as well as an open one. I just want to be really clear about where I see the responsibility for dealing with this, because one of the problems with the existing git support is that it's acquired way too many of these workarounds for oddities and special cases already.

**Comment by malandrew** [comment]
>  I don't think this is a bug in npm, though

It's not a bug in npm, but the likelihood that this will get patched in OpenSSH and make it to all hosts is low. This is especially true of those using OS X, since ssh is a system utility you don't really want to mess with for that operating system.

The GIT_SSH is a good approach to investigate. That said, it would be nice to at least brainstorm and entertain alternative solutions that don't have the drawbacks you mentioned. 

Another simple approach (besides the one aleksey suggested) which should introduce no new edge cases is to make git+ssh calls to the same host serial, by adding them to an async queue with a limit of 1.

**Comment by lxe** [comment]
> Another simple approach (besides the one aleksey suggested) which should introduce no new edge cases is to make git+ssh calls to the same host serial, by adding them to an async queue with a limit of 1.

Just delaying the 1st call actually... the rest of the calls will still be fast and parallel.

**Comment by othiym23** [comment]
> Just delaying the 1st call actually... the rest of the calls will still be fast and parallel.

That's only a partial mitigation – unless npm can positively confirm that the multiplexed connection is up and functional, we're just adding a heuristic to duct tape over the race condition (source of my paranoia: slow continuous integration vms, which have "found" a very large percentage of the recent race conditions in npm). I would actually rather serialize _all_ git operations than try to wait until just after the first one, because it's more operationally consistent. 

> That said, it would be nice to at least brainstorm and entertain alternative solutions that don't have the drawbacks you mentioned.

Sure. I'm not stopping any of that (see also: this conversation).

**Comment by lxe** [comment]
ref https://github.com/puppetlabs/r10k/issues/169
