### ISSUE TITLE
Support sortable for search result?

### ISSUE THREAD

**Issue by lichenhao** [npm/npm#7981]
RT
Can the npm support sort for search result list?

**Comment by KenanY** [comment]
@lichenhao How might this looks like? https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-feature-request-contains

**Comment by othiym23** [comment]
npm's search is in need of improvement, and it's one of those projects that's tricky to schedule because it involves a number of different teams within npm. We're probably not going to sink a lot more time into improving the current search mechanism (except to make it less likely to crash everything), because everyone connected to the CLI team agrees that the current implementation just needs to be replaced.

That said, a more concrete proposal, maybe in the form of a pull request to show what the sort syntax might look like, is going to be necessary before the CLI team can really prioritize landing this. Thanks for your time, and if you want to submit a more detailed proposal for how this might work, please do!
