### ISSUE TITLE
package.tgz is corrupt/truncated in cache and causes "cb() never called!" on npm install

### ISSUE THREAD

**Issue by mastercactapus** [npm/npm#7983]
For some yet unknown reason, the npm cache seems to get a truncated tgz file in for one or more packages. (seen on build servers in the past week or two)

When this happens jobs start failing during npm install giving the "cb() never called!" error.

It seems to stem from the `tar` module not emitting an `error` or `close` event when a tar is truncated.

There is an issue (https://github.com/npm/node-tar/issues/24) and pull request (https://github.com/npm/node-tar/pull/58) for the `tar` module that should resolve the "cb() not called!"  portion of this. How a corrupt tgz makes it's way into the cache (maybe inturrupted during transfer?) is still up in the air, but deleting the file reported by npm (with the patched `tar` module) is the current workaround.

This issue can be demonstrated with: `npm install cb-never-called`

**Comment by mastercactapus** [comment]
pending callback trace for those interested: https://gist.github.com/mastercactapus/ba7074f1fd11a713f512

**Comment by othiym23** [comment]
This is fixed by ee2bd77f3c64d38735d1d31028224a5c40422a9b, so I'm going to resolve this issue. If you figure out what's corrupting your build system's caches, please report back. If it's something in npm, go ahead and file a new issue, but even if it's something specific to how you're using your build system, leave a note here, because I'm sure that will be useful for other developers running complicated build systems with npm.
