### ISSUE TITLE
Patch node 0.10.x version of npm with `fs write stream usage atomic` bug

### ISSUE THREAD

**Issue by ankurp** [npm/npm#8017]
This bug about `npm ERR! cb() never called!` was fixed with this patch https://github.com/npm/npm/pull/6242 in npm 2.0.2 which requires developers to upgrade to node v0.12.x to get this change. Can we patch 1.4.x of npm so that node v0.10.x can easily upgrade and get this patch.

**Comment by smikes** [comment]
Is there a reason you cannot update `npm` to `npm@latest` when running node@0.10?

**Comment by ankurp** [comment]
@smikes in corporate environment it is hard to just upgrade and would prefer a bundled dependency.

**Comment by smikes** [comment]
If you want an updated version of npm to come bundled  with node 0.10, that's a request you'd have to make to  the node maintainers. 

npm 1.4 has many bugs other than that one, and I think it's very unlikely that any fixes would be back patched into 1.x versions of npm, especially since npm@3 is about to be released.

**Comment by othiym23** [comment]
The project will not be releasing a new version of `npm@1.4`. It's been 7 months since `npm@1.4.28` was released, and the number of bug fixes for other race conditions, problems with git, permissions issues, and proxy support is quite substantial, not to mention that there are a large variety of new features in `npm@2`, including support for both scoped / private packages and local packages.

Even were we to land a fix for the specific issue you're seeing, it wouldn't address many of these other issues, which are at least as severe and as likely to become impediments to running complex builds with `npm@1.4`. For instance, the fix in #6242 is only partially complete, and all the necessary changes necessary to fix the underlying bug weren't made until `npm@2.1.5`.

The npm CLI team simply doesn't have the resources to support multiple lines of development or LTS branches. We made, and make, a best effort to ensure that the last version of a semver major release series is as defect-free as possible, but barring major security flaws, we won't release new versions once we switch over to a new semver-major release series.

As @smikes says, the best way to get a new npm available with a Node 0.10 installer is to lobby the Node.js maintainers. I wish you luck, as I didn't have much myself.
