### ISSUE TITLE
Can't install assertions on Windows X64

### ISSUE THREAD

**Issue by eltismerino** [npm/npm#8027]
Nodejs: 0.12.2, npm: 2.7.4

```
C:\Users\panni>npm install assertions
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "assertions"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Users\panni\node_modules\assertions\"false"
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\panni\node_modules\assertions\"false"'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\panni\npm-debug.log
```

**Comment by KenanY** [comment]
I'm curious as to why `assertions` contains [a file named `"false"`](https://github.com/dominictarr/assertions/blob/e061f332aeb9d6e454e04005f3cec15df0dfa0c1/%22false%22).

**Comment by eltismerino** [comment]
Perhaps an echo or a command went wrong and the file was accidentally added to the repo?

**Comment by KenanY** [comment]
@eltismerino That might be why this issue is occurring. File names cannot contains quotation marks (I just tried to create one myself on Windows).

**Comment by jorrit** [comment]
Perhaps npm can skip files that contain invalid characters on Windows before creating them and issue an error/warn instead? Would a patch for such a change be acceptable?

**Comment by KenanY** [comment]
@jorrit As far as I know, `npm` does not create these files; it merely unpacks them from the published tarball.

**Comment by jorrit** [comment]
That is what I meant, npm could filter those files on win32. npm/npm/blob/master/lib/utils/tar.js already contains filter when extracting archives.

**Comment by othiym23** [comment]
This is an issue in the `assertions` package, not npm itself. I'm a little surprised that it's taken this long for someone to hit this problem, since that file's been in the package since 2011, so there's a small possibility the problem may have been exacerbated due to recent changes to `node-tar`, but I don't think this file ever would have extracted correctly on Windows.

I can see a case to be made to have `node-tar` filter out (or at least munge in some safe way) files with invalid names, but I don't think that would have helped in this case, because the failure was when something was trying to read the extracted file (which wasn't there), not when trying to write the file to disk. Ultimately, this is an issue in one of npm's dependencies and not npm itself, and I'm closing it as such.
