### ISSUE TITLE
Cannot specific prefix in current directory .npmrc

### ISSUE THREAD

**Issue by pauldraper** [npm/npm#8036]
Create .npmrc in the current (non-home) directory

```
prefix = foo
```

But `npm config get prefix` shows `/usr/local`.

This doesn't follow the documentation on [npmrc](https://docs.npmjs.com/files/npmrc):

> Each of these files is loaded, and config options are resolved in priority order. For example, a setting in the userconfig file would override the setting in the globalconfig file.

**Comment by iarna** [comment]
I'm not actually sure if this behavior has ever been supported as described, which is why I'm a bit ambiguous on the bug/feature-req thing.

**Comment by espadrine** [comment]
Given the documentation, I too believe it is a bug.

However, things might have improved since April: `npm config get prefix` yields the value from npmrc. Unfortunately, it doesn't install things there.

In fact, I believe the [cause](https://github.com/npm/npm/commit/b50be6aff34a739ca43de65f546e743d1a9975b9) of that is [this commit](https://github.com/npm/npm/commit/1707fcedb7503251eb77719aba7ac52931721205#diff-0274417318d45b56e7adc8820b6a76b3R110). I believe the `!conf.get('global')` check was made in the following spirit: “If the user specified `global = true`, they always want to install files globally, and so local configuration won't affect the global install”. If that is true, it was a misguided optimization, as `conf.get('global')` is also set when performing `npm i -g`. As a result, it cannot read the file, and so cannot notice the prefix change.

**Comment by iarna** [comment]
I would not expect this issue to apply to global installs. Not reading the file with global installs seems like appropriate behavior to me.

**Comment by espadrine** [comment]
I am curious to understand why. It does read the local user-specific .npmrc file. The documentation definitely [does not specify](https://docs.npmjs.com/files/npmrc#per-project-config-file) that it should not be read, and it not being read breaks the principle of least surprise. I ran into this issue specifically while trying to change prefix project-wise.

(Out of curiosity, why would one change prefix on the project .npmrc if not to change the behaviour of `npm i -g`?)

**Comment by iarna** [comment]
When I run commands that act globally on my computer, I do not expect them to care about my current working directory. I do not expect them to even acknowledge that my current working directory exists. I expect the same behavior from them if I'm sitting in my home directory or a temp directory or a project directory.  Current working directory is not context I expect to have to consider when I take actions globally.

**Comment by iarna** [comment]
@espadrine: _(To your parenthetical aside, no, you're quite right, that probably is the only reason, and that probably _is_ the reason this isn't supported. When I first was answering this ticket I wasn't thinking about what it actually _did_.)_

**Comment by espadrine** [comment]
I understand where you're coming from. In my case, I am on a fairly large project which already requires running a script to import many utilities into your $PATH to ease development, and people already expect directory-based magic to be happening on the command line.

I feel like the documentation should specify that project .npmrc are not read for global commands, however, to avoid having to swift through issues and npm code to figure out the problem.
