### ISSUE TITLE
npm installs packages that aren't actually the latest if the author publishes a new patch version after a new minor version.

### ISSUE THREAD

**Issue by chevex** [npm/npm#8042]
[![](http://i.imgur.com/VuKjacX.gif)](http://i.imgur.com/VuKjacX.gif)

`node-webkit-builder` is a good example. If you do `npm info node-webkit-builder` you can see the list of versions that have been published. You'll notice that v1.0.11 was published *after* v1.1.0. One would assume that, if the author is following semver, the fix in 1.0.11 would also be present in 1.1.0, with 1.1.0 being the latest and 1.0.11 being a courtesy patch to those who can't yet upgrade to the new minor version. However, it seems that npm only looks at the most recently published version rather than actually determining which version is the latest using the rules of semver.

Am I missing something about how versions should work or is this a bug?

**Comment by boennemann** [comment]
`npm install` doesn't install the highest version, but the version with the `latest` tag. If you run `npm publish` the published version gets the `latest` tag. So this is expected behavior.

**Comment by othiym23** [comment]
@boennemann is correct – the `latest` dist-tag is set to 1.0.11 on the registry, so that's the version npm will treat as the latest version and install unless you explicitly request otherwise. This is npm doing what it's documented to do. That GIF screencast is pretty cool, though. Thanks for putting it together!
