### ISSUE TITLE
Lock versions of all dependencies for globally installed packages

### ISSUE THREAD

**Issue by markjbyrne81** [npm/npm#8046]
When installing a package globally npm-shinkwrap.json files are not used.

Yeoman generators must be installed globally and locking down the versions a generators dependencies is important when shipping to production.

Is it feasible to add the ability to globally install packages with shrink wrapped dependencies?

**Comment by othiym23** [comment]
For deployment purposes, the easiest thing to do is to write an installer script that will install the exact versions you need:

```bash
#!/bin/bash

set -e

npm install -g yo@1.4.6
npm install -g generator-karma@1.0.0
npm install -g generator-angular@0.11.1
# etc
```

Another (simpler, and more deterministic, if a little harder to figure out from the docs) alternative is to build the deploy target to install yo and its generators as local dependencies, drive them via [`npm run-script`](https://docs.npmjs.com/misc/scripts), and then shrinkwrap that.

It's hard to see how to make this work in a consistent and straightforward way given the current expectations of the CLI as far as where a `package.json` or `npm-shrinkwrap.json` should be in order to use them for global installs, but I'm open to discussing what the ideal version of this feature might look like. I think that in practice the second approach I outline above will handle most deployment scenarios, so I'm not convinced that this feature is a blocker for the deployment use case, either. Before bikeshedding a number of fairly significant changes to the installer, we should establish that this really needs to happen.

**Comment by markjbyrne81** [comment]
Thanks for the reply @othiym23, I appreciate it. I am new to node and npm so I will need to play around a bit in order to figure out your alternative.

I find it hard to believe that this hasn't been a problem before.  I am raising the request as changes to modules that my dependencies depend on are causing issues in my generator and the obvious solution is to lock down the version of all dependencies.  Shrinkwrapping seemed like the best solution until I discovered it didn't work for global modules.  

Hopefully I can figure out your suggested alternative and the problem will disappear :)

**Comment by othiym23** [comment]
This triggered a long and interesting discussion within the team about how generators like Yeoman (and `ember-cli`) solve the problem of having a shared framework that specific instances of generators (like `generator-angular`, say) can use.

First off, 

> Yeoman generators must be installed globally and locking down the versions a generators dependencies is important when shipping to production.

This raises a pretty basic question: why do you want to ship generators to production? By the point you're shipping your app, it should already be completely generated. Is this a production environment for developers? If so, the script approach I show above is a good one.

This issue has actually sort of been forced by `npm@3`, because it no longer implicitly installs `peerDependencies`. That means that installing a specific generator no longer will cause `yo` and / or `bower` to be installed globally. Now, users of the generator are required to install any other prerequisites first, which leads us back to the script approach I described above. Also worth taking a look at in this context is `ember-cli`, which packages all of the pieces necessary to generate the scaffolding for a new Ember app into a single package.

This design goes more with the grain of how npm thinks about global packages, which is to say that global installs are really for binaries that are general-purpose tools, and local installs are for managing dependencies. They're different kinds of things. Because they're different, things that make sense for one really don't for the other, and in this context, trying to apply something like a shrinkwrap to the global install is to create a situation where developers can inadvertently put themselves into dependency hell, which is the exact thing that npm is designed to avoid.

As such, the CLI team isn’t not going to allow the global prefix to be shrinkwrapped. I hope this more detailed explanation of our reasoning makes sense and is useful. Thanks for your time, and thanks for bearing with us as we sort through these old feature requests.
