### ISSUE TITLE
npm update git dependencies broken

### ISSUE THREAD

**Issue by Raynos** [npm/npm#8055]
In `npm@1.4.28` I could run `npm update thing-in-my-package.json` that is pointing to a `git+ssh` link.

And it would install the latest thing as per the ssh link.

Today in `npm@2.7.4` and `npm@2.8.3` it will not install that dependency. It will just do nothing

```
raynos at raynos-MacBookPro  ~/uber/autobahn on master*
$ npm update playdoh --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/raynos/projects/nvm/v0.10.26/bin/npm',
npm verb cli   'update',
npm verb cli   'playdoh',
npm verb cli   '--verbose' ]
npm info using npm@2.8.3
npm info using node@v0.10.26
npm verb exit [ 0, true ]
npm info ok 
```

**Comment by othiym23** [comment]
See also #4191. There are also other outstanding issues where people want git actions to happen either _all_ the time or _none_ of the time or _only when necessary_. Of the three, I prefer the third, but it's proving to be a difficult target to hit because right now all of the checking and updating of git remotes happens exclusively through the cache, which `npm outdated` and `npm update` don't necessarily touch. The way this worked in older npm was by _always_ recloning everything every time, which made it very slow to use git dependencies. The current state of things is a regression, but it's a regression we don't have any tests for right now, which makes it hard to fix. Still, getting this behavior right is important, so we'll keep working on it.

**Comment by Raynos** [comment]
The `npm update` work flow is quite important; I preferred the always recloning feature. Because it's correct. 

Especially when branches and tags can be mutated and you can only avoid recloning if you depend on actual commits.

**Comment by jonathanong** [comment]
any update on this?

**Comment by alundiak** [comment]
I've read docs and `npm update` should update my project modules to latest.

> npm update updates all packages in the node_modules directory and their dependencies.

But it doesn't work for me.
I checked `npm outdated` and I have many of them. So I have to go by 
- either

```
npm uninstall modulename --save-dev 
npm install modulename --save-dev
```

which is silly when we have such powerful `update`.
- or create shell script by looping all modules and call 

```
for i in $( ls `npm root` ); do
    npm update "$i"@latest --save-dev
done
```

Tested with `node v.0.12.5` and `npm v2.11.2` on MacOS v`10.10.4`.

@isaacs @othiym23 @iarna Any updates on this?

PS. btw, `npm update -g` also kinda buggy: https://github.com/npm/npm/issues/8549

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
There's a whole bunch of things related to `npm outdated` and `npm update` with respect to Git dependencies that need to be cleaned up, and this is one of those things. The CLI team will be spending some time on npm's Git support later this year, but if somebody else wants to take a stab at making this work the same as it did in `npm@1`, that would be awesome and helpful. Thanks for everyone's patience!

**Comment by jwulf** [comment]
`yarn upgrade` does this.
