### ISSUE TITLE
Global Installs with Sudo Bork the .npm Permissions

### ISSUE THREAD

**Issue by theflimflam** [npm/npm#8056]
As an npm user, I would like to install npm modules with the `-g` flag for all users of the system without creating root owned files in my `.npm` directory so that I do not get `Error: EACCES` messages when I run localised `npm install` commands.

Current workarounds are described in a stack overflow question "[NPM throws error without sudo][1]". Generally, a user would need to do something like:

```
sudo npm install -g babel
sudo chown -R $USER:$USER $HOME/.npm
```

It would be much nicer if running npm with sudo did not break permissions in the user's home dir.

  [1]: http://stackoverflow.com/questions/16151018

**Comment by othiym23** [comment]
Upgrade to a new version of npm. As far as I know, `npm@2.8.3` (and many versions before it) don't cause any permissions problems when run with `sudo` – all of the relevant commands are coupled with bits of code that will fix up the permissions. After updating to the newest version of npm, you'll need to run `sudo chown -R $(whoami) "$HOME/.npm"` once to clean up any existing permissions snafus, but after that, everything should remained owned correctly. If not, please open issues on the specific incidences you see, because I haven't seen any that were due to npm for at least 15 releases of npm.
