### ISSUE TITLE
"npm publish" fails for some packages in private npm

### ISSUE THREAD

**Issue by wojciak** [npm/npm#8077]
Hi,

I'm publishing some packages to private repos on npm. I've managed to publish 8 packages but 3 keep failing with the error:

```
npm verb request using bearer token for auth
npm http request PUT https://registry.npmjs.org/@thelittlehog%2ftlh-dust.plugins.publisherapi.publishers.dummy
npm http 500 https://registry.npmjs.org/@thelittlehog%2ftlh-dust.plugins.publisherapi.publishers.dummy
npm info retry will retry, error on last attempt: Error: unexpected status code: 400 : @thelittlehog%2ftlh-dust.plugins.publisherapi.publishers.dummy
```

is there any way I can debug or fix this?

**Comment by smikes** [comment]
Thanks for reporting this.  Can you please run the publish command with additional logging (eg : `npm -ddd publish`) and upload the resulting `npm-debug.log` file as a gist to https://gist.github.com/ , and then post a link to the gist here?  That will help us debug what is going wrong (and it might require a response from the registry team, who might have further questions.)

Thanks!

**Comment by wojciak** [comment]
I've managed to fix it by changing the package name to something shorter, didn't know there was a limit though :)

**Comment by smikes** [comment]
I didn't realize there was a limit either, since there are modules like

https://www.npmjs.com/package/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou

**Comment by wojciak** [comment]
Seems to be an issue with private modules or with too many "." In the Name - I'll give an exact test case tomorrow

**Comment by othiym23** [comment]
See npm/validate-npm-package-name#4 for me transferring this question to the responsible party. ;)

**Comment by zeke** [comment]
```
validate-npm-package-name master » node 
> require("./")("ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou")
{ validForNewPackages: false,
  validForOldPackages: true,
  warnings: [ 'name can no longer contain more than 50 characters' ] }
```

I commented on https://github.com/npm/validate-npm-package-name/issues/4

**Comment by othiym23** [comment]
This turned out to be a bit of a voyage of exploration for the npm team, but we've determined that the previous maximum length for packages (including scopes) was too short at 50 characters, and have bumped it up to 214 characters (as that was the longest package name previously in existence). If you try to publish your package now, it should succeed, and we're going to try to be clearer in the future about the restrictions on package names so this is less confusing. Thanks for bringing this to our attention!
