### ISSUE TITLE
Have run scripts pass on arguments

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#8121]
Just realized that

```
npm run dosomething
```

or

```
npm run dosomething --debug
```

won't make any difference. Internally npm does not seem to pass on arguments if any exist. In `process.argv` that `debug` flag is missing.

Any chance npm could transfer these into the `process.argv` array before execution?

**Comment by othiym23** [comment]
The syntax you're looking for is `npm run dosomething -- --debug`, as documented in [`npm-run-script`](https://docs.npmjs.com/cli/run-script). There are some limitations to the feature (see the docs for details), which is why at some point we want to add an [`npm-exec`](https://github.com/npm/npm/issues/6053) helper script.

**Comment by binarykitchen** [comment]
hmmm, tell me, why do we need `--` here? is there a reason for it or can it be removed? doesn't it complicate things?

**Comment by KenanY** [comment]
@binarykitchen Yeah, it is needed. See https://github.com/npm/npm/pull/5518. Today, if you do:

``` sh
$ npm run dosomething --arg
```

`npm` will interpret `--arg` as a flag to `npm` itself (like all command-line tools I know). There is no way for `nopt` to tell what you want as an argument for `npm` versus an argument for your script, hence the `--` to separate the two.

**Comment by binarykitchen** [comment]
ah, right, i see now ... thanks for explaining @KenanY ... looks like that's one of the pitfalls when using npm to run another script.
