### ISSUE TITLE
npm install failing in windows --

### ISSUE THREAD

**Issue by vipulpunia** [npm/npm#8122]
Hi All,
        Downloaded latest node from nodejs.org. Installed it in C:\Program Files\nodejs\.
        Environment "path" variable also set.
        I have also created new workspace using angular-seed.
       Now when i am running npm install in the angular-seed directory that is
         C:\AngularJs-Workspace\Angular-seed its failing.
     Please help reg this .
![image](https://cloud.githubusercontent.com/assets/6697664/7386348/644dacac-ee70-11e4-84c9-56bad5725062.png)

**Comment by smikes** [comment]
Thanks for reporting this.  Can you try updating your `npm` to the latest version?  Node 0.12.2 ships with a slightly older version, and several windows bugs have been fixed since then.  To update `npm` on Windows, see our guide here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

If the problem persists, can you please upload the `npm-debug.log` file to https://gist.github.com/ and add a link to the gist in this issue?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
