### ISSUE TITLE
npm publish fails with status code 400

### ISSUE THREAD

**Issue by markbertoglio** [npm/npm#8136]
I'm unable to publish a public module. I did see there was a similar issue where names couldn't be too long but mine is very short. Can you help? Thanks

https://gist.github.com/markbertoglio/b31db294d4c20da0a1d8

**Comment by othiym23** [comment]
```
50 error Error: unexpected status code: 400 : mongoSn
```

This isn't adequately documented, but package names can't include uppercase letters. Republish as `mongo-sn`, `mongo.sn`, or `mongosn`, and it should succeed.

**Comment by markbertoglio** [comment]
I should have known better since I've run into this before. A descriptive error would be handy. Thanks for the super fast response!

**Comment by othiym23** [comment]
>  A descriptive error would be handy.

Agreed! This is one of the consequences of switching over to the new registry code that supports scoped and private packages – some of the new error-reporting code is a little on the sparse side, because a lot of things have changed and we haven't had time to make all the new messaging consistent and actionable. We're in the process of doing this, and the error messages should be more useful again soon.

Speaking of which, you should probably upgrade your npm, as `npm@1` can't handle scoped packages, which will soon start to be an issue for you (and everyone else running stock Node 0.10 installs).

See #8137 for my writeup of the problem with the `package.json` docs. I'm going to close this as resolved, with #8137 left open until we actually close this documentation hole.
