### ISSUE TITLE
npm install replaces / with %2f for scoped packages

### ISSUE THREAD

**Issue by rynclark** [npm/npm#8141]
Trying to install a scoped package, but `npm install` replaces a slash with %2f

Running
```bash
npm install @package/name
```
Results in

```bash
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "@package/name"
npm ERR! node v0.10.35
npm ERR! npm  v2.8.4
npm ERR! code E404

npm ERR! 404 Not found : @package%2fname
npm ERR! 404
npm ERR! 404 '@package%2fname' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
```

(omitted the actual package name as it's a private module)

**Comment by othiym23** [comment]
That's a cosmetic error in the error-reporting code, which is fixed in `npm@2.9.0`. For operational reasons, scoped packages map `/` to its URLEncoded equivalent in the registry back end, so that error message is actually telling you that you've either requested a nonexistent package, lack the access rights to use an existing package, or have mistyped the package's name. Assuming the package exists and should be accessible by you, have you tried logging out and logging back in again?
