### ISSUE TITLE
Error: git fetch -a origin

### ISSUE THREAD

**Issue by heathere1071** [npm/npm#8142]
When trying to do an npm install for the adapt-cli, I received this error message.  Any ideas?
```
$ npm install adapt-cli -g
npm ERR! git fetch -a origin (git://github.com/SpongeUK/download.git) fatal: una
ble to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/SpongeUK/download.git) github.com
[0: 192.30.252.129]: errno=No error
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=No error
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "adapt-cli" "-g"
npm ERR! cwd I:\
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
```
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
```

To me, this looks like the connection to `github.com` failed, so maybe this is an issue with your internet connection. Are you behind a proxy or firewall, perhaps?

**Comment by heathere1071** [comment]
I was trying this on an amazon ubuntu server, so perhaps there is a setting
I'm supposed to use that I'm not.

**Comment by smikes** [comment]
@heathere1071 It sounds like you are new to `node` and `npm` development - if so, welcome!  Feel free to ask questions here on the issue tracker, or in the #npm irc channel ( https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23npm )

I believe that Amazon instances block the git protocol by default -- because they block everything other than ports 80 and 443 (http, https).  

There are a few workaround you can try, but the one I would recommend is updating to a newer version of `node` and `npm`:

For some Linux distributions (including Amazon Linux), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Once you have a new `node` (0.10.38 or so) you can update `npm` by running:

```
sudo npm install -g npm@latest
```

The latest version of `npm` (in addition to a lot of other improvements) handles git:// dependencies by trying the git:// protocol, and then falling back to the https:// protocol.  That should solve your problem.

**Comment by heathere1071** [comment]
Hi Sam!  I figured out what I was doing wrong.  First, I set up my user
information and then tried again.  This time, it worked.

BTW - I'm totally new to all of this; you were absolutely correct there.
 :)

**Comment by smikes** [comment]
I'm really glad you got it working!

Welcome to the node / npm community, and I hope you have a good time while you're here.  Feel free to come back with *any* questions you have - helping new people get comfortable with node is an important value for our community.

Have you connected with other node users near to you?  There are a lot of meetups around ( http://nodejs.meetup.com/ ) and many people find they're helpful.  My local community (Edmonton, Alberta, Canada - Exchange Js) is great, I just found a new gig through it. ;-)

**Comment by heathere1071** [comment]
Thanks, Sam!  I am in Pennsylvania.  I'll have to see if there are any
meetups around.  :)

**Comment by othiym23** [comment]
It looks like this is resolved, so I'm closing it as such. Let me know if I've misjudged things!
