### ISSUE TITLE
Unable to npm publish

### ISSUE THREAD

**Issue by darkoverlordofdata** [npm/npm#8143]
This is the first time I've published an update since the switch to .com, and I'm getting an authorization error. I've reset my password on the website, but that didn't help.
I get this error:
```
npm ERR! need auth auth and email required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```
then when I npm adduser, I get this:
```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:darkoverlordofdata
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:darkoverlordofdata
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:darkoverlordofdata
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "adduser"
npm ERR! cwd /home/bruce/Git/liquid.coffee
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bruce/Git/liquid.coffee/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
```
npm ERR! npm -v 1.3.10
```

Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc) first? I'm pretty sure publishing is impossible with `npm@1.3` since it doesn't support atomic publishing (introduced somewhere in `npm@1.4`).

**Comment by smikes** [comment]
In your case, there might be an additional issue -- you might have an old-style authentication token.  After you update `npm` (see below) you may need to follow the "password reset to same password" protocol described here: https://github.com/npm/npm/wiki/Troubleshooting#npm-login-errors

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by darkoverlordofdata** [comment]
Thanks, but I'm not into manually updating my distro - followed too many rabbit holes that way ;) Mint get's up to date pretty quickly, I can wait for a short time before I upgrade.

**Comment by darkoverlordofdata** [comment]
I got a chance to upgrade npm this weekend. I ran
sudo npm install npm -g

I was upgraded to 1.3.10, and now publishing works.
