### ISSUE TITLE
`make release` does not work without globally installed rimraf

### ISSUE THREAD

**Issue by Fishrock123** [npm/npm#8148]
Error logs: https://gist.github.com/Fishrock123/4c3b5917bea544261d5b

npm 2.7.1 fails for me without a globally installed rimraf. 2.7.0 is fine.

Commit in question appears to be ad53d0f

This is effectively holding up being able to upgrade npm in io.js with only a tool.

/cc @othiym23

**Comment by smikes** [comment]
Ha!  This is a great one, because of course this change came in for Windows support.  Not sure what the fix should be..  Forrest?

**Comment by Fishrock123** [comment]
Even then, doesn't it still require rimraf to be globally installed on windows?

**Comment by smikes** [comment]
Well it's definitely a bug, but I think it's a bug in the environment that `npm` sets up for lifecycle scripts.

We should be adding `path.resolve('.node_modules', '.bin')` to the front of the Path environment variable, which **should** allow even `cmd.exe` to find the `rimraf` that's shipped with `npm`.

Because that's not being done, it's instead looking for a globally-installed rimraf, so you can work around it by installing one.  But again, I'm just speculating here.

**Comment by othiym23** [comment]
I think I'm probably fine with requiring that `rimraf` be globally installed when building / testing npm. This does require that Node and an npm be installed to bootstrap npm, but this is something that I think the build team can work around, and doesn't require us to break the install process for Windows _or_ ship a cluttered version of the npm release tarball.

What's going on is that when you're trying to bootstrap this from a bare io.js tarball, the `node_modules/.bin` directory doesn't exist with the links to binaries, so there's no `rimraf` executable to run. `rimraf` needs to be installed elsewhere at that point so that `npm install` can run, but after that it will have built out the links locally (which, as we've discussed elsewhere, will need to be cleaned up before the dist gets repacked, although it would probably be simpler to bundle the release _before_ running the tests, rather than after.

**Comment by Fishrock123** [comment]
> `node_modules/.bin` directory doesn't exist with the links to binaries, so there's no rimraf executable to run.

Is that just not possible to do, or is that what you mean by "cluttered version of the npm release tarball."?

**Comment by smikes** [comment]
What if we just create that *one* symlink?  It's literally the only binary that's needed pre-install, at least right now. (slippery slope?)

**Comment by othiym23** [comment]
The latter.

**Comment by othiym23** [comment]
> What if we just create that one symlink? It's literally the only binary that's needed pre-install, at least right now. (slippery slope?)

I'd be interested in hearing why having a global rimraf installed beforehand is infeasible before discussing workarounds.

**Comment by othiym23** [comment]
I'm sorry, that sounds more curt / terse than I intended. I'm just saying that it would be nice to continue to ship a clean distribution if at all possible, even if there's some additional overhead on the CI / packaging side. Spend maintainer time to save user time.

**Comment by Fishrock123** [comment]
> I'd be interested in hearing why having a global rimraf installed beforehand is infeasible before discussing workarounds.

Perhaps there isn't.

1. I'd rather not have to have io.js collaborators install another dep to upgrade a specific dep if possible. (this won't be done on the build-end for the forseeable future, I think.)
2. Some people installations require sudo for global modules and are a pain to fix. (including mine, good lord I need to fix it though..)

Maybe it would be better if io.js did something specific to link it first? Could that work?

**Comment by othiym23** [comment]
> Maybe it would be better if io.js did something specific to link it first? Could that work?

Sure, although I think we're approaching the point where it would make sense to write a script to handle all of the stuff related to running the tests for io.js (in fact, we probably crossed that point a while ago – the current Makefile stanza is not particularly easy to read or modify).

Is this a discussion for this repo, or for iojs/io.js?

**Comment by Fishrock123** [comment]
> Is this a discussion for this repo, or for iojs/io.js?

Looks like this is curving back around to io.js.

However I still find it weird that npm can't install? itself without having something that you'd normally install with npm.

**Comment by othiym23** [comment]
In the conventional case (i.e. if you'd installed npm using npm), the links would all be there because the installer creates them, so it would use its own `rimraf`. This is a special case caused by how the release is built for io.js / Node.js.

**Comment by Fishrock123** [comment]
I'd bring up that users may have a version installed where they chose not to install npm (currently supported on windows, maybe more in the future), however I realize this is an edge-case. Closing, I'll try to sort this out in io.js then.
