### ISSUE TITLE
How to publish isomorphic binary distributed packages for cross-compiling-targeted platforms?

### ISSUE THREAD

**Issue by cookiengineer** [npm/npm#8155]
I'm currently thinking of using npm as a distribution / package manager for our cross-compiler chain behind lycheejs. But I realized that it's in fact not a dependency resolver among different architectures nor has it support for isomorphic libraries.

I'm talking about shipped runtime bindings (platform adapters) for a set of runtimes (iojs / nwjs / node-sdl2 / cordova) for a set of operating systems (osx / windows / android / ios / wphone / bberry / debian / ubuntu / fedora) for a set of architectures (armv7 / armv6 / x86 / x86_64). There might be more platforms in future, this is the current state of support.

Note that the listed platforms are cross-compiling targets, which means a host OS can be OSX or Linux (well, or Windows with win-bash and lycheeOS, a busybox virtual linux) at the moment and targets any of the listed platforms. If the compiler setup sucks (looking at you, gcc from brew or apple!) we simply use lazy-built prebuilt binaries that we ship in our runtimes. So the packaging stuff takes over and simple modifies config files and replaces the high-level JS content (like the App / Game).

Now, is there any way to achieve this with npm or do we have to ship our own package manager?

So, my questions are the following:

- Are there plans to support multi-arch flags in packages?
- Are there plans to support prebuilt binaries (bindings) for nodejs/iojs/nwjs inside a package?
- Are there any plans to support backfixes for legacy versions (e.g. lycheejs-0.8.6~13ubuntu3.deb)?
- How should a maintainer fix a security issue in an already published library? Unpublish and republish won't work.

**Comment by smikes** [comment]
There is limited support for downloading architecture-specific precompiled binaries (see the external module `node-pre-gyp` — https://www.npmjs.com/package/node-pre-gyp)

To fix a security issue in an already published library, the best practice is to deprecate the library and publish a new patchlevel of it, so something like this:

latest is 2.4.1
previous is 1.3.8
bug discovered in 1.3.8
fix bug
npm deprecate pkg@1.3.8
npm publish --tag previous pkg@1.3.9

I think you would be continually disappointed by `npm` if you tried to make it work for your use case.  It's not really targeted at multi-platform binary support.

**Comment by othiym23** [comment]
`node-pre-gyp` is indeed the best place to start with this, in part because there would need to be pretty broad changes made to `node-gyp` to get it to support shipping multiple native builds in the package tarball. npm is mostly hands off in this process, because all it's really doing is invoking `node-gyp rebuild` at install time. This may not sound like a lot of work, but it does require coördination across several sets of stakeholders, and the work required needs to start outside the bounds of the npm CLI project.

For a discussion of a more comprehensive solution to this problem (that I am _way_ overdue to weigh in on), see the proposal by @orangemocha over at https://github.com/nodejs/build/issues/151 to create a full-on distributed native build service for Node as an ecosystem. For now, since this is something that isn't immediately actionable by the CLI team, and since it's not in scope for us for the next 6-12 months, I'm going to close this issue. Thanks for your time, and for your patience!
