### ISSUE TITLE
`"private": false` for public scoped modules

### ISSUE THREAD

**Issue by shannonmoeller** [npm/npm#8158]
Why do I have to use `npm publish --access=public` for scoped modules when `package.json` already has a `private` field that could be used?

```json
{
  "name": "@shannonmoeller/some-module",
  "private": false,
  ...
}
```

**Comment by othiym23** [comment]
Because `"private": true` tells npm to _not publish_ the package, and changing the meaning of that field unilaterally would be a very dramatic change. In addition, the access field will probably be serving more purposes in the future than just handling `private` and `public` access levels. "Private" as a term is a little overloaded right now, it's true, but the `package.json` field and the access specifier serve different purposes.
