### ISSUE TITLE
Weird entry in package.json when running "npm i -S git://..."

### ISSUE THREAD

**Issue by bcherny** [npm/npm#8160]
I ran the following command:

`npm i -S git://github.com/bcherny/tracery.git`

And NPM added the following entry to my package.json:

```json
{
"dependencies": {
    "tracery": "file:../../../../../var/folders/m4/sbz1g6754qj92rljg2d4s8n8hl5gw5/T/npm-52698-4b51b135/git-cache-b1c4dded8bd4/ee6f78171e9e763e3781f3fed0cf7909796e3d99"
  }
}
```

**Comment by othiym23** [comment]
My guess is that you're running an old version of npm (perhaps `npm@2.7.4`, the version bundled with Node 0.12.2?). There was a bug in the git repo handling for a few versions there that saved the path of the temporary clone of the repository, rather than the repository URL. If you upgrade to `npm@latest` (currently `npm@2.9.0`), this should be fixed.

**Comment by bcherny** [comment]
@othiym23 i was indeed running 2.3.0. Upgrading did the trick. Thanks!
