### ISSUE TITLE
npm keeps downloading like forever...

### ISSUE THREAD

**Issue by ihopepeace** [npm/npm#8174]
I am trying to install ionic with npm(2.8.4) with `sudo npm install -g ionic` on Mac 10.9.5. It just keeps downloading and downloading (the 'l' keeps rotating). This UI gives no idea what is happening behind the scenes. It's really making my head ache. This happened with cordova & yeoman too. But, after re-running install command a few times they installed. Is there anyway i can install ionic without npm.

**Comment by smikes** [comment]
I'm sorry to hear that you're experiencing poor download/install performance.  Without knowing more about your location (physically and networkologically) I can't offer you any specific steps that you can take to improve it, but here are some suggestions --

You can turn off the spinner and increase the default logging level to get more information about what's going on during an `npm install`:

```
$ npm set spin false
$ npm set loglevel http
```

If you are seeing a lot of timeouts and retries, you may benefit from running a local cache of the `npm` registry, or even just a cache of the modules you use.

If you are seeing errors such as ECONNRESET you may be running into problems at a lower level than `npm` -- possibly even bugs in the http or https implementation in node.  What version of `node` or `iojs` are you using?

**Comment by ihopepeace** [comment]
Thanks @smikes 
I am using v0.12.2 of node.js. I managed to download ionic... By running install & unistall commands a lot of times like this...
`$ sudo npm install -g ionic
 //After half an hour
 $ sudo npm uninstall -g ionic'
until ionic was installed.
PS: I live in India. Also, I was using VMWare to run Mac

**Comment by mshiltonj** [comment]
Usually, if it spins for more than a minute, I just ctrl-c, rerun the command, and it works as expected on the next attempt. But I've had this problem enough times that I searched for and found this issue.  

I've turned off spinner and turned up the log level as requested, but I can't reproduce the problem again just now.

If and when it happens again, I should be able to post more info.

**Comment by othiym23** [comment]
Ionic, Phonegap, and Cordova are particularly tricky to install because they're large, complex packages, and until recently, some or all of them were distributing themselves as shrinkwrapped packages, which meant they bypassed the local npm cache and a single component failing to download or install would cause the entire installation to fail. I do think they've updated their packaging process to be more forgiving, and also this issue is pretty stale (and it looks like @ihopepeace was eventually able to complete his install), so I'm going to close it. Thanks to all for their patience!
