### ISSUE TITLE
--save with -g

### ISSUE THREAD

**Issue by feus4177** [npm/npm#8177]
It would be nice if packages installed with the `-g` flag were also saved to package.json and npm kept track of whether certain dependencies need the `-g` flag or not. That way, all you need to run is `npm install` and it takes care of *all* the dependencies including the global ones. This is really useful when working on a team.

**Comment by othiym23** [comment]
There's no unambiguous way to track global installations from a single `package.json` file. Even were npm to drop a `package.json` file into the global prefix, you'd very quickly run into situations where there are conflicts, especially if people started trying to share / apply those `package.json` files across environments. The purpose of the global prefix is to have a shared location to put commonly-used binaries, and is closer to being like an OS distribution's package manager than an application dependency manager, like npm is when run in a non-global mode. This isn't an unreasonable request, but it's not something that it makes sense for npm to do, because it would end up putting users into the exact situation of dependency hell that npm is designed to remedy. As such, I'm going to close this. Thanks for your time!
