### ISSUE TITLE
npm install express

### ISSUE THREAD

**Issue by wrj913** [npm/npm#8182]
```
[vagrant@hxdev lesson1]$ npm install express
npm ERR! Error: UNKNOWN, symlink '../mime/cli.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "/home/vagrant/.nvm/v0.10.36/bin/node" "/home/vagrant/.nvm/v0.10.36/bin/npm" "install" "express"
npm ERR! cwd /vagrant/node-lessons/lesson1
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path ../mime/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
It looks like you are using `vagrant` to run a Linux instance on another host filesystem - are you using Windows as the host?  That might cause a problem if the underlying filesystem doesn't support symbolic links.

Can you try running `npm install --no-bin-links` to see if the installation succeeds?

If you get more errors, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by wrj913** [comment]
Thank you very much for your help, I use ```npm install --no-bin-links ```   executed successfully,but do not know what causes```npm install ```  can not

**Comment by othiym23** [comment]
@wrj913 This is because the shared folder created by Vagrant doesn't support symbolic links, which npm uses to link from `node_modules/.bin` to the executable binaries installed by the package. To work around this limitation, install your npm packages somewhere other than the shared folder used by Vagrant, or just use plain Windows or a full Linux vm.

Closing as resolved.

**Comment by wrj913** [comment]
Thank you for your answer

**Comment by cristianvuolo** [comment]
Thank you!!!

**Comment by wpm** [comment]
I hit this same issue trying to do an `npm install` on an Ubuntu image running on an OS X host machine. After a lot of experimenting I found the following version combinations:

* Vagrant 1.7.4, Virtual Box 5.0...has this bug
* Vagrant 1.7.2, Virtual Box 4.3.24...does not have this bug

Since the host was OS X, the ability to create softlinks in the shared folder did not appear to be the issue, though just to be sure I did verify that I could do this.

I didn't dig into the problem any deeper than that, but going back to earlier versions was a workaround for me.
