### ISSUE TITLE
npm doesn't correctly respect .npmrc

### ISSUE THREAD

**Issue by HaykoKoryun** [npm/npm#8186]
`npm -v` `2.9.0` `node -v` `v0.12.2`

I've created an .npmrc file in my test project directory with this single line:
`prefix=./app`

running the following command, you get the expected output:
```shell
λ npm config get prefix
Z:\test\app
```

However when I run `npm install colors` for example, it get's dropped into `Z:\test\node_modules\` as opposed to `Z:\test\app\node_modules\`

Giving the `prefix` switch from the `cli` however gives the expected result:
```shell
λ npm install colors --prefix ./app
colors@1.1.0 app\node_modules\colors
```

Interestingly, without the `prefix` switch from the `cli`, npm creates an `app` folder if it doesn't exist, and drops an empty `etc` folder inside.

**Comment by kkragenbrink** [comment]
For some reason, ```npm.localPrefix``` is not getting the ```prefix``` from config, but is using the default.  This is somewhere in either ```lib/npm.js``` or ```lib/config```.  I'm still digging; hopefully I'll have a PR to fix this today.

**Comment by kkragenbrink** [comment]
So there's really a fundamental problem in how ```npm.prefix``` is defined.  
:```npm.localPrefix``` is defined as the top-level directory of the project.
:```npm.globalPrefix``` is defined as the prefix defined in .npmrc (as found in ```localPrefix```, or your ~/.npm directory), or else one of a few locations that could be considered global.

Then, ```npm.prefix``` is equal to ```npm.globalPrefix``` if the ```global``` config option is set to true, or else to ```npm.localPrefix```.  

I feel like the name of these variables has gotten very muddy, over time.  ```npm.localPrefix``` is probably actually better defined as the "projectRootPrefix", and ```npm.globalPrefix``` is more likely considered the "localPrefix".   And then there's the real globalPrefix which has no real bearing on npm.prefix because it seems like anywhere it's used, we check whether npm.global is set anyways and use an entirely different variable.

Unfortunately, with as muddy as this code is, a fix has the potential to break a lot of things.  I am going to write some test cases in and around some other things I'm doing today, but it will not be as quick and easy as I had originally hoped.

**Comment by kkragenbrink** [comment]
@othiym23 Need some insight from you, here.  With the exception of this ```npm install``` using ```npm.prefix``` to determine where to install packages, every other use case for ```npm.prefix``` is to find package.json.  

Given this, I feel like ```npm.prefix``` is the wrong variable for ```npm install``` to be using.  If you agree, I'd like to add an ```npm.installPrefix``` variable which can be used to find the correct path for installing packages.

**Comment by othiym23** [comment]
The way `prefix` is used is overloaded and therefore confusing, and could probably be documented more clearly, but it is behaving as expected, and the issue @HaykoKoryun is running into is a mismatch between their expectations of how the tool works and npm's design.

Just to make sure we all understand how this stuff is supposed to work, let's include a few relevant snippets from the documentation:

For [how the folders work](https://docs.npmjs.com/files/folders#prefix-configuration):
> ### prefix Configuration
> 
> The `prefix` config defaults to the location where node is installed. On most systems, this is `/usr/local`, and most of the time is the same as node's `process.installPrefix`.
> 
> On windows, this is the exact location of the node.exe binary.  On Unix systems, it's one level up, since node is typically installed at `{prefix}/bin/node` rather than `{prefix}/node.exe`.
> 
> When the `global` flag is set, npm installs things into this prefix. When it is not set, it uses the root of the current package, or the current working directory if not in a package already.

...for [`prefix` as config](https://docs.npmjs.com/misc/config#prefix):
> ### prefix
> 
> * Default: see npm-folders(5)
> * Type: path
> 
> The location to install global items.  If set on the command line, then it forces non-global commands to run in the specified folder.

...and, as a side note, [`global` and how it affects `prefix`](https://docs.npmjs.com/misc/config#global)
> ### global
> 
> * Default: false
> * Type: Boolean
> 
> Operates in "global" mode, so that packages are installed into the `prefix` folder instead of the current working directory.  See `npm-folders(5)` for more on the differences in behavior.
> 
> * packages are installed into the `{prefix}/lib/node_modules` folder, instead of the current working directory.
> * bin files are linked to `{prefix}/bin`
> * man pages are linked to `{prefix}/share/man`

Given that background, `prefix` has two meanings:

1. When set in a configuration file, it's where all _global_ packages get installed. It will never alter where local installs are performed, which will always be the `node_modules` folder beneath the nearest `package.json` file, or the current directory if there's no `node_module` or `package.json` in the current chain of directories back to the root (and `--prefix` isn't used as a parameter to npm; see below).
2. When used as a command-line parameter, it's analogous to `make -C` (which is why `npm -C` is shorthand for `npm --prefix`): change the working directory (that is, the prefix) to the passed directory, and use the `package.json` or `node_modules` relative to that path for whatever npm operation is invoked.

`npm.localPrefix` and `npm.globalPrefix` are accessors set by the npm bootstrap code and used internally to npm to keep track of these two different kinds of use of the `prefix` configuration; they're not meant to be set outside of npm, nor are they meant to be overridden. That's why they're undocumented.

@HaykoKoryun I'd be interested to see your use case, but I suspect that what you're trying to do is something that is explicitly not supported by npm, which is to install modules somewhere other than the `node_modules` folder in the same directory as your `package.json` file. There are a host of reasons why this isn't possible, starting with (and, to be honest, more or less ending with, because this is sufficient all on its own) it being tied to how the Node module resolution algorithm finds the main entry point for a module.

**Comment by HaykoKoryun** [comment]
Thanks for the in depth explanation, however I think it still doesn't even work as it was intended to.

I just did a clean installation of `node.js` on my Windows 7 machine, and upgraded `npm` to `2.9.0` as per the instructions [here](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) (the third option of updating `npm`).

My test setup is as follows (`.npmrc` has the single line `prefix=./app`):
```
F:\__temp\prefix_test\
+-- app
+-- .npmrc
+-- package.json
```

Running `npm install --prefix=./app colors` installs into `app\node_modules\colors` as expected.

However running `npm install -g colors` installs it into `C:\Users\user\AppData\Local\npm\node_modules\colors` which is not as intended.

I tried changing `prefix` in `.npmrc` to `prefix=${APPDATA}/npm` and it made no difference.

So there's something definitely wrong there.

However, I do have one question with the implementation of the `prefix` logic, and I am not being intentionally obtuse.
What is the use case of allowing a package to affect where other global packages get installed if you do an `npm install -g` whilst in the folder?
For example, I have my global `.npmrc` setup to install global packages in `...\AppData\Local\npm\node_modules\` instead of `Roaming` and wouldn't want to allow any package to alter that config, so why would you allow a local package to override that preference?

**Comment by othiym23** [comment]
You wouldn't, which is why the local `.npmrc` doesn't apply when you run `npm install -g` -- the `-g` tells npm to only look at your global configuration, and not anything project-specific. There's no point in setting `prefix` in a project's `.npmrc`, because it won't be used. I apologize for not making that clearer. Only a subset of configuration values apply for per-project config files.
