### ISSUE TITLE
publish fails with 500 error

### ISSUE THREAD

**Issue by surdu** [npm/npm#8199]
I try to publish from Windows 7 Professional SP1 running node v0.10.35 and npm 1.4.28

Here is the full error log:
https://gist.github.com/surdu/3bcf47feee707a4e5945

When running `npm config ls` it appears to me that I'm correctly logged in (I see the username and email fields as set) .

**Comment by KenanY** [comment]
@surdu Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`?

Actually, looks to me like you are trying to publish a module name `Formless`, but capital letters are no longer allowed in package names.

**Comment by surdu** [comment]
Hmm... Didn't knew about this limitation. Sorry !

**Comment by KenanY** [comment]
@surdu Sounds like a great idea! What we currently have is not _too_ bad but could be more descriptive:

```
50 error Error: unexpected status code: 400 : Formless
```

HTTP status code 400 is "[t]he request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.", and the error even points to what's wrong (just a coincidence here, I think) :)

Newer versions of `npm` may behave differently though, but I cannot test at the moment.
