### ISSUE TITLE
Extend package.json to indicate a binary compile step.

### ISSUE THREAD

**Issue by tracker1** [npm/npm#8208]
Some thoughts on supporting binary packages...

Many packages now have install/preinstall scripts that will download build binaries for various platforms.  It would be nice if there could be a separate section to support "compile" directives/scripts, even platform specific ones...  Even if this started as a simple indicator to use `node-gyp` for said build.

Why separate this out?  As a first step to supporting pre-built modules... for now, this section should run automatically run `pre/compile` scripts prior to the `pre/install` scripts...  as part of the installation process.  Once this structure is in place, a build system could be added to npm's hosting (even if limited to paid accounts in the public npm) that would allow for pre-built binaries for the most common targets to exist.  These could then be checked before/instead of `pre/compile` scripts run during install leaving the `pre/install` scripts to still run on the target platform.

**Comment by othiym23** [comment]
This is something that needs to be happen at some point, but its scope is big enough that it needs to be managed as a full-scale effort. I say, with some trepidation, that it's premature for the CLI team to even start bikeshedding making this a part of npm yet, because people have lots of very strong opinions about how native builds should work and be integrated with npm, and I'm afraid that opening up the discussion when we're not ready to act on it will generate more heat than light. The current setup with `node-gyp` is functional (and extremely widely deployed) and people are still experimenting with pieces of a larger build solution (`node-pre-gyp` being the most prominent example).

Realistically speaking, this is a big enough ask that it's going to need to land on the roadmap as a full product or feature release all on its own, and the CLI team's pipeline is full for at least the rest of 2015. If you want to start playing around with this now, feel free to build something that runs outside of npm but uses properties in `package.json`, but I don't think we have the time to devote to specifying how something like this might work for the foreseeable future.
