### ISSUE TITLE
Can't install packets in a virtual machine that runs on Windows because of path size limitation in windows

### ISSUE THREAD

**Issue by ovidiubadita** [npm/npm#8226]
Hello,
if I try to install this in my virtual machine, it will fail but it will work on windows directly. The problem is that I need it to work on my virtual machine. Is there a way to make npm install packages without using such large paths?
```
npm ERR! Error: ENAMETOOLONG, open '/home/vagrant/Code/razvan/node_modules/laravel-elixir/node_modules/main-bower-files/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es6-iterator/node_modules/es6-symbol/test/is-native-implemented.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/vagrant/Code/razvan
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/Code/razvan/node_modules/laravel-elixir/node_modules/main-bower-files/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es6-iterator/node_modules/es6-symbol/test/is-native-implemented.js
npm ERR! code ENAMETOOLONG
npm ERR! errno 49
npm WARN optional dep failed, continuing mime@1.3.4
npm WARN optional dep failed, continuing image-size@0.3.5
npm WARN optional dep failed, continuing errno@0.1.2
npm WARN optional dep failed, continuing mkdirp@0.5.0
npm WARN optional dep failed, continuing request@2.55.0
```

**Comment by smikes** [comment]
Thanks for reporting this.

Unfortunately, this is a longstanding problem on Windows in general and especially with virtual machines.  You may also encounter problems with symbolic links -- the virtual machine may not support them, even though the underlying filesystem does.

The next version of npm -- `npm@3` will automatically flatten and deduplicate dependencies, which will mitigate this problem somewhat.  `npm@3` is feature-complete, and is currently being tested.

In the meantime, I notice that you are running `npm@1.4.28`.  There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ovidiubadita** [comment]
Thank you for your answer. I will wait for the new npm#3 to come along. Until then, I will survive as I do now, and have npm installed on windows, in the shared folder that exists in the VM. It works like this, but sadly, I can't run my unit tests in VM. But maybe is for the better, because I still need to learn some more things before I go into TDD. 
I am happy  to hear that this is a problem that will be solved soon.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  Although it's still in beta, have you had an opportunity to give npm@3 a try? If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
