### ISSUE TITLE
Error encountered while installing gulp imagemin

### ISSUE THREAD

**Issue by ThekhoN** [npm/npm#8230]
```
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "gulp-imagemin" "--save-dev"
npm ERR! cwd C:\Users\thekho.ngaosathe\Desktop\image_OPT
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
```

**Comment by KenanY** [comment]
@ThekhoN Could you please upload the _entire_ `npm-debug.log` as a [gist](https://gist.github.com/)? Posting just 5 lines of an entire log is not sufficient to deduce the issue here. Furthermore, if possible, please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`.

https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains

**Comment by othiym23** [comment]
Closing as abandoned.
