### ISSUE TITLE
deprecated versions should not be preferred when another version is in range

### ISSUE THREAD

**Issue by Prestaul** [npm/npm#8232]
If version 1.1.* of a package (let's call it `foo`) is deprecated and I `npm install foo@^1.0.0`, npm will install a deprecated version if it is the latest. Also, the deprecated warning will be suppressed if I `npm install` and `foo@^1.0.0` is specified in my package.json.

When installing, the latest version in range AND NOT DEPRECATED should be preferred unless there is not a non-deprecated in range.

**Comment by smartmouse** [comment]
+1

**Comment by othiym23** [comment]
I think I see what you're getting at here, but were we to do this, we'd be nullifying the value of deprecation as a thing that exists independent of unpublishing. Deprecation isn't saying, "these versions are bad and you shouldn't use them", but instead, "this package isn't a good idea anymore; use something else". Unpublishing already handles the case where you have specific versions of a package that you think are no longer fit for purpose, and it behaves pretty much exactly as you describe.

Thanks for taking the time to make this proposal, though!

**Comment by Prestaul** [comment]
@othiym23:

> Deprecation isn't saying, "these versions are bad and you shouldn't use them", but instead, "this package isn't a good idea anymore; use something else". 

So how do I say "these versions aren't recommended, I suggest you use another version". I thought that was why I could deprecate a specific version or range of versions. I don't want to unpublish and possibly break my consumers, but I do want them to be informed that there are reasons they might like to choose a newer (or older) version and, in the case that they specified a range of versions in which non-deprecated options exist, I'd like them to get a non-deprecated version by default.

I won't harp on this beyond this second comment. I appreciate the quick response.

**Comment by othiym23** [comment]
It seems like the best thing to do in that case is to leave the deprecated versions in place to catch people who are using tight semver ranges and version pinning in `package.json` (deprecation bypasses shrinkwrap users, because they download the package tarballs directly) and then publish a new, un-deprecated patch release that's fixed (assuming this isn't a breaking change) that new users will get by default.

The whole point of deprecating a package is to put a message somewhere where users will see it. I appreciate that your use case falls between the cracks of what `npm unpublish` and `npm deprecate` are meant to handle, but the solution is probably more communication, rather than complicating the installation algorithm yet more.

**Comment by Prestaul** [comment]
@othiym23 :+1: thanks for the detailed response.
