### ISSUE TITLE
do you recommend native windows for npm or cgywin when we tried the test?

### ISSUE THREAD

**Issue by smartmouse** [npm/npm#8233]
HI, I am trying out the packaged test that come with npm.

I find that running it on a native windows command prompt
vs running on a cgywin environment gives me different results.

native cmd prompt windows run results
```
ok test/tap/version-update-shrinkwrap.js .............. 18/18
ok test/tap/view.js ................................... 39/39
ok test/tap/whoami.js ................................. 11/11
ok test/tap/zz-cleanup.js ............................... 1/1
total ............................................. 2212/2229
```

cgywin
```
--
  1..18
    # tests 18
    # pass  16
    # fail  2

ok test/tap/view.js ................................... 39/39
ok test/tap/whoami.js ................................. 11/11
ok test/tap/zz-cleanup.js ............................... 1/1
total ............................................. 2076/2159
```

1. which environment do you recommend?
npm version - 2.7.4
node.js  0.12.0.2
Thanks in advance for your help.

**Comment by othiym23** [comment]
Cygwin is completely unsupported (it's [anti-supported](https://github.com/npm/npm#installing-on-cygwin), if that's a thing, because it falls in the cracks between native Windows and Linux – npm supports both, but the weird intersection created by Cygwin is nearly impossible to support), so I'd suggest sticking with vanilla Windows, filing issues where you find Windows-specific failures.

**Comment by SteveALee** [comment]
OK if this is the official line I will not spend any time on #9420. It's not just cygwin as mentioned there.

I've been using *nix shells on Windows for years (since MKS for MS-DOS) and while it is usually very usable there are problems (usually with commands that make assumptions about paths and shell). 

As a developer I completely understand the reluctance to add more complexity in supporting a minority requirement.
