### ISSUE TITLE
npm search filtering scoped package

### ISSUE THREAD

**Issue by watilde** [npm/npm#8244]
Hi.

I'd like to search filtering scoped package for getting only some packages in my registry. Any way to do that? Also how about to add `[--registry=url]` or `[--scope=@orgname]` to `npm search`.

Thanks.

**Comment by othiym23** [comment]
Right now, scoped packages are omitted from search results entirely. This is because we need to make sure that we **never** leak private packages into the results. It's on the roadmap (along with replacing the current CLI search altogether, because it's terrible), but I don't know when it's going to be ready for use.

**Comment by superkhau** [comment]
+1

**Comment by Tyriar** [comment]
+1, I'd really like to use scoped packages more extensively to reduce the clutter in the global scope and to enable picking good names. Not being visible in search is a pretty big negative though.

**Comment by thasmo** [comment]
Does someone know the state of this?

**Comment by othiym23** [comment]
There's a couple different pieces here:

1. The primary registry should return results for packages with scoped names. Most of the server-side work is already done on this. It just needs to be tested and rolled out.
2. `--registry=URL` should work for every command that touches the registry, because all of npm's internal code just pulls the currently-configured value for `registry` at runtime. Setting this parameter on the command line will override any value in config files. There's an outstanding task to document that this parameter can be used over at #11490.
3. `--scope` would be an interesting search modifier, but I think the more likely solution will be to use an actual query syntax against whatever search backend ends up being used instead of the current brute-force JSON search. I would say that we'd accept a patch to add support for this to the current search (once scoped packages are in the search results at all), but I will say that I think this is probably wasted effort, since the current search is going to be replaced, so use your best judgment before taking that on.

The bug parts of this are in train and covered elsewhere, and the feature requests here are not things the CLI team is going to ship in the next 6-12 months, so I'm going to close this issue. Thanks for your time, and thanks for your patience!

**Comment by slavafomin** [comment]
Hello, is there a way to search for scoped packages now? For example I want to list all packages of `@angular`. How do I do that? Thanks.
