### ISSUE TITLE
npm login error

### ISSUE THREAD

**Issue by 6sco** [npm/npm#8251]
hi,
i want push my npm package and i have a problem when i try to type npm login on Ubuntu.
See stack trace:
```
mathieu@MATHIEU-UBUNTU:~/Documents/Git/nodejs$ npm login
Username: 6sco
Password: 
Email: mathieu.melis@orange.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:6sco
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:6sco
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:6sco
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "login"
npm ERR! cwd /home/mathieu/Documents/Git/nodejs
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mathieu/Documents/Git/nodejs/npm-debug.log
npm ERR! not ok code 0
```
I have previously created and validated my account on https://www.npmjs.com
Same issue if i try as root user.
Thanks for help me.

Mathieu

**Comment by KenanY** [comment]
@6sco `npm@1.3.10` is extremely old and has not been supported for months. It is impossible to publish with the `1.3` series because it does not support atomic pushing, which was introduced in `1.4`. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

Also your Node.js version is over a year old; might be best to [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-linux) that too for bug fixes and security patches.

**Comment by othiym23** [comment]
One note, in addition to @KenanY's response: the reason for this is that Linux distributions generally lag pretty far behind Node and npm, which move relatively quickly in comparison. [NodeSource](https://github.com/nodesource/distributions) offers packages for many popular distributions (including Ubuntu) that have much newer versions of Node / npm, although you'll still need to run `sudo npm install -g npm` after you upgrade to get the latest stable npm (which I recommend – many many bugs are fixed in newer npm).

Closing as resolved.
