### ISSUE TITLE
`npm view .` uses published package instead of local package.

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#8256]
I would expect that 
```
npm view .
```
to show the current package json, instead it does something weird: It shows the package information for the published package with the same name ?!

**Comment by KenanY** [comment]
@martinheidegger The heading of the [documentation](https://docs.npmjs.com/cli/view) is "View registry info". This is intended behavior.

**Comment by martinheidegger** [comment]
@KenanY The documentation (as far as I didn't over-read anything - if so please point it out) does not specify what happens when you define `.`. Even if it would specify that case as it is working right now: the current output is counter intuitive. Any require/fs-lookup statements starting with `.` references to files in relation to the current working directory. Say my package's name is `express` then

```
npm view express
```

should show the content of express package as is in package manager while

```
npm view .
```

is expected in contrast to show the package content of `.` folder.

Another question: Is there a way how i can get the same functionality for the current page? (i.e. show the version of the current package?)

**Comment by othiym23** [comment]
Yep, @KenanY said. npm is reasonably consistent about using `.` as shorthand for "the package on the registry with the name identified by the nearest `package.json`" for most of the commands that interact with the registry. It's possible that we could add something like `npm view --local` (maybe not with that name), but `npm view` is functioning as intended.

**Comment by othiym23** [comment]
> Is there a way how i can get the same functionality for the current page? (i.e. show the version of the current package?)

```
bauchelain% cd Documents/projects/npm/npm-registry-client
bauchelain% npm version
{ 'npm-registry-client': '6.3.3',
  npm: '2.9.1',
  ares: '1.10.0-DEV',
  http_parser: '2.3.0',
  modules: '43',
  node: '1.8.1',
  openssl: '1.0.2a',
  uv: '1.4.2',
  v8: '4.1.0.27',
  zlib: '1.2.8' }
bauchelain% npm version --json
{
  "npm-registry-client": "6.3.3",
  "npm": "2.9.1",
  "ares": "1.10.0-DEV",
  "http_parser": "2.3.0",
  "modules": "43",
  "node": "1.8.1",
  "openssl": "1.0.2a",
  "uv": "1.4.2",
  "v8": "4.1.0.27",
  "zlib": "1.2.8"
}
```

**Comment by martinheidegger** [comment]
@othiym23 And the other package.json properties? (I have a script that needs name, version and git repository)

**Comment by othiym23** [comment]
The easiest way to do that is to write a little Node script that runs something like:

```javascript
#!/usr/bin/env node
// basic-info.js
var pkg = require('package.json')
console.log('npm_package_name="%s"', pkg.name)
console.log(`npm_package_version="%s"', pkg.version)
if (pkg.repository) console.log('npm_package_repository="%s"', pkg.repository)
```

and then something like `eval $(node ./basic-info.js)` in your calling script, assuming it's a bash script. If you want something that has all the rules applied within npm instead of the bare package data, take a look at [`read-package-json`](http://npm.im/read-package-json).

**Comment by othiym23** [comment]
or you could just install [`json`](http://npm.im/json) and then use it instead:

```
bauchelain% json -f package.json name
npm-registry-client
bauchelain% json -f package.json version
6.3.3
bauchelain% json -f package.json repository.url
git://github.com/isaacs/npm-registry-client
```

**Comment by martinheidegger** [comment]
So: in other words: its fixable if I don't use npm ...

**Comment by othiym23** [comment]
Yep! You don't need npm to do everything!

**Comment by martinheidegger** [comment]
True. I guess I will restrain myself from trying to improve npm then.

**Comment by othiym23** [comment]
I don't really understand why what I've said merits that response. If you feel that I've dismissed your concerns, then I've expressed myself poorly, and I apologize. Kenan and I have explained that the current behavior is by design, as well as the underlying symmetry that `npm view` is preserving with its behavior, and provided a potential avenue for changing its behavior that's backwards-compatible and might give you what you want. I also provided two examples of how to address the use case you described with simple, existing tools.

npm doesn't address every use case around package management, and I don't think that it can. It's already a very complex, hard to master tool, and as much as possible, I want its behavior to remain internally consistent, even in cases where that consistency may lead to behavior that's surprising to some of its users some of the time. I think that the current behavior is what most users would expect, even though it's inconvenient for the particular situation you found yourself in.

**Comment by martinheidegger** [comment]
Here is how the problem I reported looks like from my point of view: 
`npm view` is a very helpful tool for dealing with the package json. Conceptually all it does is `[Resolve package.json]` and `[Give tools to access data from that package.json]` I have a problem with the fact that I can not use `npm` as-is to deal with the most obvious `package.json` file (the one lying in the current directory).

My Process: Instead of trying to reinvent the wheel and use a different tool for that (like the solution you provided with the small script or by using `json`) I thought it could benefit the community by contributing here (in form of an issue).

Your response was:

 - NPM is not designed like that (_of course it isn't: I mentioned in the issue report that I have a problem with the intended behaviour_)
 - We could add a feature like `--local` (_good start but might introduce new issues_)
 - If something works like intended its not broken (_so: if i have a problem with how it works its my problem not yours?_)
 - Solve it without using npm (_why did I put a question here in the first place again?_)

I see this very same response pattern applicable to many if not most of the problems I have with `npm`. So instead of me being able to improve my situation for me (where `npm view` would have a use-case that would come actually handy in) I am left with a closed issue and some wise cracking (for the lack of a better english phrase that comes to mind - not a native speaker). Only the `--local` suggestion was helpful and it was actually the smallest part of the conversation. It seems like my time will be better spent trying to solve problems without the help from npm (aka. write a package) than posting an issue here, wouldn't you agree (another phrase that sounds surely quite a bit more cynical that I intend to).
