### ISSUE TITLE
npm search is broken

### ISSUE THREAD

**Issue by JohnMcLear** [npm/npm#8268]
https://github.com/ether/etherpad-lite/issues/2664

TLDR STR;

```npm cache clean && npm search etherpad```

This will return the expected results..
Then

```npm search etherpad```

Will return

```npm ERR! registry error parsing json```

Tested in Node 10.33 and 12.2 on various boxes.

I emailed @isaacs to try get eyes on this ASAP

**Comment by JohnMcLear** [comment]
I got an update via twitter: 

From @seldo @ 3:42pm --> We're looking into this.

**Comment by seldo** [comment]
Aaaaand fixed.

Our apologies; we have a new search service in rotation that is actually a lot faster. Unfortunately it has a bug that cropped up overnight and our monitoring was insufficient to alert ops to the problem (because it served the full search index correctly, but was failing only on the deltas).

We'll dig further into the bug and update when we have a cause, and we're also going to be extending the health checks on this service this morning. Thanks for your patience.

**Comment by JohnMcLear** [comment]
No drama tropicana.  Thanks for the fix hombre's!

**Comment by JohnMcLear** [comment]
Oh if you want to leave this open feel free to go-ahead and do that..  My bad if I closed prematurely =)
