### ISSUE TITLE
Install, dedupe and shrinkwrap fail to resolve all dependencies

### ISSUE THREAD

**Issue by Dignifiedquire** [npm/npm#8278]
First of all I'm sorry if this is a duplicate, or just a combination of multiple known bugs, but I'm running into the following problems, with a system of:

- `npm@2.10.0`
- fresh npm cache
- `node@0.10.38`
- [gist of `package.json` dependencies](https://gist.github.com/Dignifiedquire/56ab1e17ca31646d4fb1) (no dev or peer dependencies)

```bash
$ rm -rf node_modules
$ npm install
# Output in Gist1
$ npm ls
# Output in Gist2
$ npm dedupe
# Output in Gist3 
$ npm dedupe
# Output in Gist4 and log in Log1
$ npm shrinkwrap
# Output in Gist5 and debug log in Log2
```

The gist of these logs is that it seems that not all dependencies get installed, which results in issues with subsequent calls to `dedupe` and `shrinkwrap`. (The main goal here was to shrinkwrap everything, which I can't do because it always fails)

* [Gist1](https://gist.github.com/Dignifiedquire/db280a48d2f8ec770e5b)
* [Gist2](https://gist.github.com/Dignifiedquire/e9301df7c1cde5fde9a7)
* [Gist3](https://gist.github.com/Dignifiedquire/b75e92babf45a8ae70b9)
* [Gist4](https://gist.github.com/Dignifiedquire/6661f4e2b167780114e2)
* [Gist5](https://gist.github.com/Dignifiedquire/711ba9bed6cc30a1b7fc)
* [Log1](https://gist.github.com/Dignifiedquire/7ebcb37dd933652ab426)
* [Log2](https://gist.github.com/Dignifiedquire/d304d1b99a14bd10a821)

**Comment by smikes** [comment]
Thanks for reporting this!  There are several interacting problems here, I think.

One of them (and the easiest to fix) is the error EMFILE.  It looks like you are using OSX Yosemite, which by default limits each process to only 256 open file handles.  

The simplest (but probably not the most correct) way to fix this is to raise the file limits (see https://github.com/gruntjs/grunt-contrib-copy/issues/21 for more of a discussion.)
```
$ launchctl limit maxfiles 2048 2048 && ulimit -n 2048
```

As far as the unmet dependencies, I don't have a lot of experience with this, but I believe that you have to decide how to handle these manually; `npm` is complaining because it is unable to resolve them automatically.  You may have to selectively upgrade/downgrade packages until you are using a consistent set of dependent modules, or else (after deduping) manually install working versions in the subdirectories, and then shrinkwrap.

> npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/eslint/node_modules/escope requires estraverse@'^3.1.0' but will load
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/eslint/node_modules/estraverse,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/gulp-fingerprint/node_modules/gulp-util requires chalk@'^0.5.0' but will load
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/gulp-fingerprint/node_modules/chalk,
npm WARN unmet dependency which is version 0.4.0
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/gulp-fingerprint/node_modules/gulp-util requires through2@'^0.5.0' but will load
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/gulp-fingerprint/node_modules/through2,
npm WARN unmet dependency which is version 0.4.2
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/babel-core/node_modules/source-map-support requires source-map@'0.1.32' but will load
npm WARN unmet dependency /Users/dignifiedquire/work/codio/dashboard/node_modules/babel-core/node_modules/source-map,
npm WARN unmet dependency which is version 0.4.2

**Comment by Dignifiedquire** [comment]
> I believe that you have to decide how to handle these manually;

Then where is the point of using npm? When I run `npm install` the point is that it goes and installs all dependencies, which it doesn't because there seems to be a bug in the deduping algorithm.

**Comment by Dignifiedquire** [comment]
So interestingly enough, after a few days I retried the same steps and things seem to have resolved themselves for the most part, so that I can use `shrinkwrap` :)
