### ISSUE TITLE
question: build dependencies without active internet

### ISSUE THREAD

**Issue by yorkie** [npm/npm#8296]
Is there a way to build npm dependencies offline.

I don't wanna fetch dependencies source again at my deployment but I used so many native modules, so that when I copied the node_modules from my osx machine to ubuntu, it doesn't work.

Hence, I'm looking for a way to only build those `.node` executables without fetching sources from npm cloud.

Thanks

**Comment by smikes** [comment]
If the ubuntu machine has a compiler + python 2.x , then you should be able to rebuild all the dependencies on the target machine without hitting the network.  However, this is not an explicitly supported use case so I can't give you a prescription for how to do that.  Maybe something like this:

```
npm ls --parseable | while read x ; do (cd ${x}; npm rebuild ) ; done 
```

**Comment by othiym23** [comment]
Rebuilding a native module using npm and `node-gyp` has 2 parts: the part everybody knows about, and a part that almost nobody seems to know about. The first is that you need to have all the necessary pieces for that package directly available on the local machine. This is pretty easy to copy over, and I think this is what most people think is the only requirement for rebuilding native modules.

Unfortunately, there’s also _another_ required piece: `node-gyp` needs the header files for the installed version of Node to be located in `$HOME/.node-gyp`, and will download them if they’re not available. `node-gyp` will download those header files itself if it doesn’t find them, so in order to build completely free from the internet, you’ll need to ensure that that download has happened before you take the machine off the network or finish baking the image you’re going to install later.

There’s work underway on the `node-gyp` side to streamline this process, including work to bundle the header files with the Node binary in the official installers, and to modify `node-gyp` to use those header files if they’re available without downloading them again. See nodejs/node-gyp#665. As such, I’m going to close this issue, but the CLI team would also really like to see this process simplified and made easier to understand. Thanks for your time and patience!
