### ISSUE TITLE
outdated/update and gist-hosted dependencies

### ISSUE THREAD

**Issue by claycarpenter** [npm/npm#8300]
npm (v2.10.0) seems to be treating GitHub Gist dependencies as though they're modules registered in the npm registry. This causes `outdated` and `update` to fail to update the module with the Gist reference, even if the Gist host has an updated package.json version attribute.

I created a basic test installation that includes references to GitHub- and Gist-hosted modules. This is the package.json:

```
{
  "name": "git-urls-test",
  "version": "1.0.0",
  "dependencies": {
    "gist-minimum-module": "git+https://gist.github.com/15b5e6c8762342a8ce38.git",
    "github-minimum-module": "git+https://github.com/claycarpenter/github-minimum-module.git"
  },
  "license": "ISC"
}
```

That basic installation is held in this Gist: https://gist.github.com/claycarpenter/0c81f039f729de587092

Both referenced modules are nothing more than package.json files contain the bare minimum to test that version updates are picked up by `outdated` and `update`.

I tested the behavior on platforms running npm v1.4/node v0.10 and npm v2.10/node v0.12 by installing the dependencies (`npm install`) and then executing a npm outdated command with verbose debug logging (`npm outdated -dd`). Here are the results:

**NPM 1.4 / Node 0.10**

```
npm outdate -dd
npm info it worked if it ends with ok
npm verb cli [ '/home/ubuntu/.nvm/v0.10.35/bin/node',
npm verb cli   '/home/ubuntu/.nvm/v0.10.35/bin/npm',
npm verb cli   'outdate',
npm verb cli   '-dd' ]
npm info using npm@1.4.28
npm info using node@v0.10.35
Package                Current  Wanted  Latest  Location
gist-minimum-module      0.0.7     git     git  gist-minimum-module
github-minimum-module    0.0.5     git     git  github-minimum-module
npm verb exit [ 0, true ]
npm info ok
```

Note that outdated listed both the Git and Gist dependencies.

**NPM 2.10 / Node 0.12**

```
npm outdated -dd
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'outdated', '-dd' ]
npm info using npm@2.10.0
npm info using node@v0.12.3
npm verb request uri https://registry.npmjs.org/gist-minimum-module
npm verb request no auth needed
npm info attempt registry request try #1 at 9:49:05 PM
npm verb request id ff33c9acaf477a31
npm http request GET https://registry.npmjs.org/gist-minimum-module
npm http 404 https://registry.npmjs.org/gist-minimum-module
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers   'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   'content-length': '51',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Tue, 19 May 2015 01:49:05 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2144-IAD',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1432000145.689779,VS0,VE56' }
Package                Current  Wanted  Latest  Location
github-minimum-module    0.0.5     git     git  github-minimum-module
npm verb exit [ 0, true ]
npm info ok
```

Note that here outdated lists only the Git dependency, while failing to find the Gist dependency because it looks for the module in the npm registry.

This seems like a regression, but perhaps I'm missing something. Is there some other way to indicate to npm that it should treat the Gist dependency reference as a Gist/Git repo and not look to the npm registry for resolution?

**Comment by smikes** [comment]
Thanks for reporting this!  As you say, this looks like a regression.

**Comment by othiym23** [comment]
There’s a bug here, and a potentially useful change to how `npm outdated` works, in both `npm@2` and `npm@3`. The bug is that `npm outdated` shouldn’t be treating hosted Git dependencies as registry packages, and while `npm@2` is now crashing in a slightly different way on this, it’s still totally incorrect. It should be handling things the way `npm@3` handles git dependencies, and just printing out that it’s a hosted Git dependency and not trying to pull data from the registry. A patch to that effect would be extremely useful.

The useful change would be to actually update the cached copy of the hosted Git dependency, and then see if the commitish in `package.json` now maps to a different commit hash after a fetch & update. That’s a bit more work, and also has some sort of gnarly performance implications, especially if the package you’re checking for outdated dependencies has more than a few hosted Git dependencies. I think the fact that it actually makes `npm outdated` useful for Git dependencies outweighs the performance hit, so that’s something the CLI team will add if nobody else gets to it first. Thanks for bringing this up, and thanks for your patience!

**Comment by goloroden** [comment]
I have created a [PR](https://github.com/npm/npm/pull/12833) to add support for detecting outdated git packages. The PR may not be perfect, but I hope that it suits as a starting point for a discussion.

It contains some tests and has been squashed. Looking forward to your feedback :-)
