### ISSUE TITLE
`npm login` creates accounts without warning

### ISSUE THREAD

**Issue by UltCombo** [npm/npm#8337]
I tried to `npm login` but mistyped my name. npm did not warn anything and instead created a new account. And now I have two accounts, one of them being completely useless.

Can we have some kind of warning when entering an unregistered name in `npm login`?
And is there any way to actually delete a npm user from the npm registry?

**Comment by robsongajunior** [comment]
me too, I wish delete robsonaraujojunior account, i'm using just robsongajunior

**Comment by UltCombo** [comment]
I've accidentally created [ultcombo](https://npmjs.org/~ultcombo) when trying to login to [ult_combo](https://www.npmjs.com/~ult_combo).

**Comment by othiym23** [comment]
I think splitting user creation and user login into separate commands will address the underlying need here. Let us know if you don't think that's sufficient! We're probably going to need to split apart `npm login` and `npm adduser` anyway in order to make some changes we're starting to plan around npm's auth (we intend to make it possible to support other auth providers for enterprise environments and private registries), so this is something the team will probably get to before the end of the year. 

In the meantime, if you came across this because you inadvertently created a new user while trying to log in, please send an email to support@npmjs.com, and one of our excellent support engineers will help you get that extraneous account removed. No, there isn't a way to remove a user via the CLI, and yeah, there probably should be, but that's something the team's probably not going to have time to get to anytime soon, especially because it requires some coördination with the registry team. Either way, it’s pretty easy for npm support to get this sorted out for now. Thanks for your time!

**Comment by UltCombo** [comment]
> I think splitting user creation and user login into separate commands will address the underlying need here. Let us know if you don't think that's sufficient!

That looks perfect, IMHO. :smiley:

> In the meantime, if you came across this because you inadvertently created a new user while trying to log in, please send an email to support@npmjs.com, and one of our excellent support engineers will help you get that extraneous account removed.

Excellent, thanks.

**Comment by finnp** [comment]
I created a pull request on the registry client that would be needed to add a login command here: https://github.com/npm/npm-registry-client/pull/136. If that PR is reviewed and merged I'm happy to also send a PR to the CLI.

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/4151.

**Comment by busches** [comment]
Looks like `npm login` is now an alias for `npm adduser` according to the documentation: https://docs.npmjs.com/cli/adduser. Can this issue be closed?

**Comment by KenanY** [comment]
@busches I wouldn't close this issue yet, since `login` being an alias for `adduser` is the issue here.
