### ISSUE TITLE
Network problem: Can’t reach certain endpoint on Fast.ly

### ISSUE THREAD

**Issue by sbruchmann** [npm/npm#8340]
Hello folks

I have trouble installing [babel] [1], respectively [babel-core] [2]. Installing other packages works as expected.

Running `npm --verbose --save install babel-core` yields [this output] [3], where the last line is repeated indefinitely. One thing to note is, that it is not predictable at which dependency installation the HTTP request will time out; mostly [chalk] [4], [ast-types] [5] and [to-fast-properties] [6].

### General Info

  - there’s no proxy/firewall
  - no flaky network connection
  - pinging `registry.npmjs.org` works fine

### Things I tried to resolve this issue on my own:

  - clearing the npm cache
  - using older versions of node/npm via nvm
  - using the non-secure registry
  - using a different network
  - reinstalling node / npm

### System Setup
  - OS X 10.9.5
  - node 0.12.3
  - npm 2.9.1

[1]: https://npmjs.org/package/babel
[2]: https://npmjs.org/package/babel-core
[3]: https://gist.github.com/sbruchmann/ba4302b75515ed857add
[4]: https://npmjs.org/package/chalk
[5]: https://npmjs.org/package/ast-types
[6]: https://npmjs.org/package/to-fast-properties

**Comment by sbruchmann** [comment]
**Update**: Just tried a different ISP via a friend and it works as expected. After further investigation, it occurred to me, that my machine can’t reach certain IP’s that belong to [fastly] [1]. Any ideas on how to solve that?

[1] http://fastly.com

**Comment by othiym23** [comment]
Not in general, no. Where are you? Do you have to do anything special to connect to the internet via your ISP? (i.e. might there be a way to configure some proxy settings to make the connection to Fastly more reliable?)

**Comment by isaacs** [comment]
Are you using your ISP's default DNS settings?

Have you tried explicitly setting your DNS to some known-good provider like OpenDNS or Google?

I have my laptop permanently set to use `8.8.8.8` and `8.8.4.4` as DNS providers because Comcast is terrible.  It means that I can't log into some public WiFi hotspots without turning it off, because they use DNS routing for login, so it's kind of a pain.  (Hotels and airports are the worst with this.)

I'm guessing Comcast isn't your problem, since your profile says you're in Germany rather than the Bay Area.  But it could be the issue.  Most fast.ly users CNAME to their endpoint, so your ISP might just have it mistakenly pointed at Facebook or something.  (If only this was a hypothetical example and not a real thing that happens in my home on a daily basis you have no idea.)

You might also try restarting your home router.  Some consumer routers leak memory over time, and can start behaving badly for specific DNS lookups if things fail to fall out of cache properly.

**Comment by ehsalazar** [comment]
@sbruchmann Good to hear that switching ISP worked. Were you able to beyond your machine not reach certain fastly IPs? I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
