### ISSUE TITLE
npm init: empty test command, set as error string

### ISSUE THREAD

**Issue by Strat-** [npm/npm#8347]
When running `npm init`, if you leave `test command` blank, it will set it as `"echo \"Error: no test specified\" && exit 1"` in the package.json

```
[ivan@sq10 test]$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (test) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /home/ivan/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes)
```

**Comment by KenanY** [comment]
@Strat- This is completely intentional, although I do not think it is documented anywhere.

  - [relevant code](https://github.com/npm/npm/blob/5abfc9c9017da714e47a3aece750836b4f9af6a9/lib/run-script.js#L130)
  - [a test](https://github.com/npm/npm/blob/5fa61ce412543d3730c0e3fda39fb167c819bd5a/test/tap/link.js#L29)
  - [another test](https://github.com/npm/npm/blob/448efd0eaa6f97af0889bf47efc543a1ea2f8d7e/test/tap/sorted-package-json.js#L79)

**Comment by Strat-** [comment]
@KenanY Alright, gotcha. Thanks for clearing it up.
