### ISSUE TITLE
Semver precedence should take over the publish order

### ISSUE THREAD

**Issue by domotenko** [npm/npm#8355]
If you publish two versions (A) & (B) where SemVer(A) < SemVer(B) in reverse order, then sometimes the version A is installed instead of B.
### Example:

Let's publish version 4.0.1 and 4.0.2 in reverse order, so the json will looks like
https://registry.npmjs.org/test-smeshariki

``` json
time: {
   "modified": "2015-05-25T12:36:22.635Z",
   "created": "2015-05-25T12:00:56.322Z",
   "4.0.2": "2015-05-25T12:36:12.044Z",
   "4.0.1": "2015-05-25T12:36:22.635Z"
}
```

Then run the command:

```
>npm install test-smeshariki@~4.0.0
```

now we expect to see

```
test-smeshariki@4.0.2 node_modules\test-smeshariki
```

but the observer result is

```
test-smeshariki@4.0.1 node_modules\test-smeshariki
```

```
node version   0.12.4
npm version    2.10.1
```

**Comment by Artazor** [comment]
Hmmm... Can confirm this. Very strange. @isaacs ?

**Comment by KenanY** [comment]
I believe this is because `npm` installs the version tagged as `latest` by default, and since `latest` here, `4.0.1`, satisfies the version range `~4.0.0`, that is the version that ends up being installed. I _think_ this is intentional behavior but it would be best to hear from a core dev to verify.

**Comment by Artazor** [comment]
@KenanY it looks like weird implicit rollback feature...
