### ISSUE TITLE
NPM_TOKEN does not work

### ISSUE THREAD

**Issue by jasonkuhrt** [npm/npm#8356]
I have not had success using `NPM_TOKEN` in continuous integration (`CCI`) or `Dockerfile`s. The only place where I've seen `NPM_TOKEN` token to be known to work is `Heroku`.

Given that a search for `NPM_TOKEN` [turns up nothing in the code base](https://github.com/npm/npm/search?utf8=%E2%9C%93&q=NPM_TOKEN) I'm inclined to believe that there is some magic on the `heroku` side. I think `NPM_TOKEN` should be supported natively by `NPM` as it would help us in numerous instances just like it helps `heroku` users.

Thanks.

**Comment by Starefossen** [comment]
I wasted 4 hours of my life debugging why npm did not recognise the `NPM_TOKEN` environment variable which is mentioned in [this blog post on the npm blog](http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules)!

**Comment by homerjam** [comment]
+1

**Comment by pkyeck** [comment]
if it only works for `heroku` the blogpost is very misleading - I thought I could just do

    NPM_TOKEN=00000000-0000-00000-0000-00000000000 npm whoami

everywhere.

**Comment by kurttheviking** [comment]
+1 would welcome a standard env param everywhere

**Comment by philostler** [comment]
I'm in a very similair situation to @kurttheviking and really would like the ability to pick up `NPM_TOKEN` from the env. TBH without this ability it going to make my build process a bit of a hack

**Comment by drinchev** [comment]
:+1: 

To make my comment useful I paste my CircleCI configuration rows that fix the issue :

```
dependencies:
  pre:
    - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
```

**Comment by dublx** [comment]
+1 for recognising NPM_TOKEN
Whats the point in paying for private repo if it's not going to work in a CI pipeline?
Or at least allow `npm login` to accept input in a scripted way?

**Comment by iarna** [comment]
npm supports using more than one registry at a time. Because of this, supporting a single `NPM_TOKEN` environment variable is untenable. We might be interested in a more general solution in the future, but the cli team doesn’t have this scheduled for the coming year. 

That said, it's something that pops up often enough that it might be pretty beneficial to have it documented somewhere clear and accessible, which @ashleygwilliams might be interested in knowing about. It's particularly confusing because there are various services (apparently) that use or refer to something called `NPM_TOKEN`, but provide no facilities to add this to npm's configuration file.

**Comment by kurttheviking** [comment]
@iarna I'm curious, what makes an environment parameter any more or less tenable than a string in an `.npmrc` file? Moreover, if more than one key is required, perhaps a comma-separated environment variable could be sufficient?

In my experience, services allow an `NPM_TOKEN` environment parameter because a repo-specific `.npmrc` should not be committed with secrets. So, the only tenable solution is to allow an external environment variable to be injected into the container/service/test suite.

**Comment by danielbayley** [comment]
I just ran into this and wasted a bunch of time based on that misleading blog post!

> what makes an environment parameter any more or less tenable than a string in an .npmrc file?

This.

**Comment by devboxr** [comment]
Thanks everybody, this was REALLY frustrating.

Luckily, Google has this one up there.

**Comment by mk-pmb** [comment]
Adding that config line makes npm (e.g. `npm --help`) crash with `Error: Failed to replace env in config: ${NPM_TOKEN}` in all shells where the var isn't set. Is there some way to write my `.npmrc` so the line will be ignored in those cases?

**Comment by SpainTrain** [comment]
> npm supports using more than one registry at a time. Because of this, supporting a single NPM_TOKEN environment variable is untenable.

@iarna can you expound on this?  Why does multi-registry support preclude having an env var for the (I assume overwhelming) common case of using `registry.npmjs.org`?  E.g., `NPM_NPMJS_REGISTRY_TOKEN`.  While obviously not ideal, the `.npmrc` approach done wrong could lead to credentials becoming exposed via git or published modules.

**Comment by mk-pmb** [comment]
I see no reason to make npm-cli prefer one registry, especially as long as there seem to be easy ways to delegate that decision to the user. If we had an env var syntax that makes npm just ignore the line if that var isn't set (instead of failing), you could easily configure any registry you like using any env var name you like. (For even fancier ideas, see #15566.)

**Comment by Starefossen** [comment]
The registry URL should be an environment variable as well! Environment variable configuration is becoming more and more best practice with the rise of container technology like Docker.

**Comment by mk-pmb** [comment]
> The registry URL should be an environment variable as well!

It's already supported as a config option, so you can use any supported config value source, including environment variables. Just add to your `~/.npmrc`: `registry=${NPM_REGISTRY}`
Then try in your shell: `NPM_REGISTRY='http://example.net/npm-registry/' npm config get registry`

**Comment by Starefossen** [comment]
Oh, thanks for the detailed info @mk-pmb 👍

**Comment by rwillians** [comment]
Thanks @Starefossen! This seems to be a VERY straightforward solution, I'll try it out.

**Comment by AustinHunt** [comment]
Not sure if this helps anyone experiencing issues, but I'll add my 2 cents:
1. When following the npm documentation on using private repositories with Docker, you will run into an issue where if you configure the .npmrc file to have "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" it will work flawlessly when deploying to Docker, but will break your local npm commands. For some reason ${NPM_TOKEN} does not work as expected.
2. To fix this issue, I did the following:

Follow the documentation to get your NPM_TOKEN env variable set correctly: [HERE](http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules)

I created a /path/to/project/.npmrc-deploy file:
`//registry.npmjs.org/:_authToken=${NPM_TOKEN}`

In my Docker config, I put the following: 
```
FROM risingstack/alpine:3.3-v4.3.1-3.0.1

ARG NPM_TOKEN  
COPY .npmrc-deploy .npmrc  
COPY package.json package.json  
RUN npm install  
RUN rm -f .npmrc

# Add your source files
COPY . .  
CMD npm start
```
This allows me to preserve my development environment and use private repositories when deploying to production.

**Comment by leomelzer** [comment]
@NomadGraphix Thanks for following up, just ran into the same issue when setting this up!

**Comment by simonc** [comment]
For anyone ending up on this issue, a quick solution to use private npm packages on Heroku is the following:

Add this to your `package.json` file
```json
"scripts": {
  "heroku-prebuild": "echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc",
}
```

* The `heroku-prebuild` is called by Heroku before installing dependencies.
* Don't add `~/` in front of `.npmrc` or it will not work

Before deploying use `heroku config:set NPM_TOKEN=…` to set your token on Heroku.

That's it ☺️

**Comment by adamxberlin** [comment]
^^ This guy! Thank you so much!
Been looking for a solution and none of the above mentioned ones worked.

You're a LEGEND mate! 👏🙏😌
