### ISSUE TITLE
running two simultanious npm script with ```&``` fails on windows

### ISSUE THREAD

**Issue by TheAlphaNerd** [npm/npm#8358]
Only one command runs, second one never starts. This is especially painful if neither command has an "ending state" such as a watch command or a dev server

**Comment by othiym23** [comment]
That's because `cmd.exe` doesn't have job control like Unix shells. Because it doesn't know how to run a task in the background, I _think_ it just treats `&` the same as `&&`. This is a limitation of the Windows platform, and not something that can be hacked around in npm.

If you need background task execution, you're probably going to have to write a little JavaScript task runner that uses child processes (and handles starting or stopping processes).

**Comment by TheAlphaNerd** [comment]
: (

**Comment by TheAlphaNerd** [comment]
git bash on windows 8 was running the command as expected when not wrapped in an npm script.

That being said... this is totally a rabbit hole not worth going down.

**Comment by rofrol** [comment]
Use parallelshell

    "dev": "parallelshell \"npm run watch\" \"npm run live-server\""

[Example](https://github.com/rofrol/es6-module-test)
