### ISSUE TITLE
packer: renames all .gyp files to binding.gyp

### ISSUE THREAD

**Issue by indutny** [npm/npm#8411]
Packer renames all .gyp files to binding.gyp, even if the binding.gyp was present. Maybe it could skip this step if binding.gyp was already found?

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by othiym23** [comment]
(And yes, this seems feasible and like something we should do – thanks, Fedor!)

**Comment by indutny** [comment]
Yay, thank you!

**Comment by othiym23** [comment]
This is a small change that would simplify a bunch of use cases around building native modules and also integrating with platforms like nwjs and Electron, so I see no reason not to do it soonish. It's a semver-major change, because there may be packages relying on this behavior, nondeterministic and yucky as it is. I think @mscdex asked for something similar that's also open; either way, the team will try to get this included in the next semver major version of npm, which I anticipate will be going out sometime around the middle of 2016 (don't worry; it's not going to be nearly as big a cheese-moving event as `npm@3` was). If you want to take a stab at putting together a PR for this, that would be excellent, but the team will take it on if nobody else gets to it first. Thanks for your patience and the suggestion, Фёдор! Спасибо!

**Comment by indutny** [comment]
Yay!

**Comment by indutny** [comment]
I will take a look.

**Comment by indutny** [comment]
Should be fixed by https://github.com/npm/fstream-npm/pull/18

**Comment by mikemorris** [comment]
Dupe of https://github.com/npm/npm/issues/10243?
