### ISSUE TITLE
Update readable-stream to 1.1.x?

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#8416]
Could you use version 1.1.x of the `readable-stream` module in 2.x branch?

In `iojs`, there are four copies of readable-stream in the bundled `npm` module:
* npm ⇒ readable-stream — `1.0.x`, 200K
* npm ⇒ npmlog ⇒ are-we-there-yet ⇒ readable-stream — `1.1.x`, 236K
* npm ⇒ sha ⇒ readable-stream — `1.1.x`, 236K
* npm ⇒ npm-registry-client ⇒ concat-stream ⇒ readable-stream — `1.1.x`, 236K

Updating the direct `readable-stream` dependency to `1.1.x` should allow deduping it and saving ~0.67MiB of the overall installed size (3% of the iojs distribution size).

**Comment by othiym23** [comment]
Landed in c929fd1d0604b5878ed05706447e078d3e41f5b3. Because the `npm@2` dedupe algorithm is somewhat capricious, it wasn't as simple as merely `npm install 'readable-stream@~1.1.13' && npm dedupe`. Instead, I had to install `readable-stream@1.1`, manually prune `readable-stream` from the dependencies including it, and then reinstall `request` so it would install `readable-stream@1.0.x`. That latter bit also means the space savings aren't as large as one might hope, but now it's done.

**Comment by ChALkeR** [comment]
Thanks. I missed that `request` still depends on `readable-stream@1.0.x`,
that means that the size is reduced by ~0.47 MiB instead of ~0.67 MiB (as I
thought before). That's still more than 2% of the iojs distribution size
(unpacked).
