### ISSUE TITLE
Pass arguments to `install` script

### ISSUE THREAD

**Issue by RSATom** [npm/npm#8431]
Hi, I'm developing native module which could be used with different runtimes (`Node.js`/`io.js`/`nw.js`/`Electron`). The main problem is, when user call `npm install module_name` there are no way to specify desired runtime (or maybe I just don't know such way) to install/build script.

The main question is, is it possible implement passing config parameters to `npm install` for example same way at it possible now for `npm run-scripts`?

Or maybe some other way already exists? - Will be glad to hear any hints.

Thanks in advance.

**Comment by RSATom** [comment]
I've posted small bounty on this feature: https://www.bountysource.com/issues/19649301-pass-arguments-to-install-script
I hope it will help a little bit. Thanks!

**Comment by Flet** [comment]
Maybe adding a `postinstall` script in package.json would work? Then have that script detect the OS?

This sounds similar to: https://github.com/mafintosh/electron-prebuilt

Check package.json and install.js in that repo and see if that is close to what you're looking to accomplish.

**Comment by RSATom** [comment]
@Flet, thank you for you help, but unfortunately, it's not enough for me to detect current OS. I need to know with which runtime ( `Node.js` or `io.js` or `nw.js` or `Electron` ) user plan use my addon. And if using of `Node.js` or `io.js` could be detected without problem (just check where we run right now), with `nw.js` and `Electron` it's not so easy. And I have ask user somehow if he want build addon for `nw.js` or `Electron`. I can't imagine any other way get this info without asking user directly.

Another obvious solution could be have multiple npm packages (one for every runtime) - but I don't like it.

**Comment by Flet** [comment]
Indeed it sounds tricky. I think `postinstall` is the right place to do runtime detection (of course it may not be straightforward to detect). 

Multiple packages sounds like it could work but yeah it could be painful to maintain. For me, installing a runtime specific package would feel more natural than passing arguments to install.

There are also `dist-tags` which could be rigged up to work too... For example: `npm install mypackage@iojs`

Anyways, just some ideas for workarounds. Good luck!

**Comment by RSATom** [comment]
> There are also dist-tags which could be rigged up to work too... For example: npm install mypackage@iojs

It's sounds interesting, thank you for hint!

**Comment by RSATom** [comment]
checked `dist-tags` - unfortunately it still will require have multiple *full* copy if package, since I can't tag only one file (in my case `package.json` to specify different build args), so it's not very different from having multiple packages in npm...

**Comment by zkat** [comment]
Hey, this can be done in two different ways right now:

* Add a custom run-script that manually applies those extra arguments as necessary (so you could do `npm run inst --my-custom-flag`)
* Use env variables to pass those values in.

Since there are what I consider sufficiently effective solutions for this in existence already, and it would frankly be too complicated right now to add this kind of custom flag feature, I'm closing this.

@ashleygwilliams might have some ideas about documenting this sort of thing to make it more discoverable/making sure folks know these solutions are available and how to use them.

Thanks for your time writing this up, and I hope the above solutions are sufficient. If there's anything glaringly troublesome about doing it that way, please let us know.
