### ISSUE TITLE
npm install same repo, different forks has incorrect behavior

### ISSUE THREAD

**Issue by davis** [npm/npm#8449]
I have 2 dependencies in a project, A and B.

so my package.json looks something like this:

```
dependencies: {
  A: 1.0.0,
  B: 3.0.0
}
```

A depends on a branch of a fork of B (not the main npm package or repo).

so I would expect the dependency tree to look like this:

```
A@1.0.0
├(forked B#branch)
B@3.0.0
```

however, it only installs

```
A@1.0.0
B@3.0.0
```

and in my code, when I do `require('A')`, A uses B@3.0.0 (non-forked)

I've made a repo containing the actual thing:
https://github.com/davis/test-merlin.js

**Comment by KenanY** [comment]
@davis From looking through that repository, I believe this is because that fork ([davis/superagent#handle-arrays-better](https://github.com/davis/superagent/tree/handle-arrays-better)) has version as `1.2.0`, which `npm` is treating as "equal to" `superagent@1.2.0` from the registry. Through using a higher `loglevel`, I can see that the fork is indeed cloned but I guess it gets deleted once `npm` realizes that it can just use `superagent@1.2.0` at the top-level directory. Not really what I would expect to happen.
