### ISSUE TITLE
suggestion for `npm test`

### ISSUE THREAD

**Issue by tunnckoCore** [npm/npm#8450]
I suggest to implement and can help if needed

```
npm test package-name
```

It would install the package if not installed (otherwise it would just install devdeps), then run it's tests and then delete the devDeps from it's node_modules. Actually I started it here [tunnckoCore/npm-run-tests](https://github.com/tunnckoCore/npm-run-tests) (I'm almost sure it can be done better) before two months, but it would be cool to add that functionality in the core.

**Comment by othiym23** [comment]
This is sort of how `npm explore` works (minus the install part), and you might want to play with that a little and see if it does what you need. Because `npm test` is just an alias for `npm run-script test`, it already probably does too much stuff that gets in the way of passing along arguments to the invoked run-scripts. What you suggest is analogous to how `npm test` worked in versions older than `npm@2.0.0`, and unfortunately, the new script argument handling pretty much precludes us from going back to that. Thanks for the suggestion, though!

**Comment by tunnckoCore** [comment]
> minus the install part

that's the main reason for that i'm suggesting, lol.

**Comment by othiym23** [comment]
Getting that feature into the CLI would be very tricky at this point, and isn't really part of the core feature set of the tool. However, that sounds like an awesome thing to build out as an external tool! Especially if it could, say, install multiple versions of a package and run the tests against all of them! That's something that a lot of people have been asking for recently.

**Comment by tunnckoCore** [comment]
> install multiple versions of a package and run the tests against all of them!

hm.. good idea. BUT.. which tests, from which version? tests may change from version to version.. so.. hm.
