### ISSUE TITLE
npm shrinkwrap output inconsistency

### ISSUE THREAD

**Issue by techtonik** [npm/npm#8467]
`npm shrinkwrap` produces too much noize for dependencies that don't change. See https://github.com/gratipay/gratipay.com/commit/cf35a41009870cf1ea7c61c7a7b19b4752845a54

**Comment by othiym23** [comment]
It's really best to think of `npm-shrinkwrap.json` as an opaque blob of configuration information that happens to be human-readable. `npm/npm#multi-stage` (soon to be known as `npm@3`) tries to keep the amount of change in the file to a minimum, but when you completely regenerate the shrinkwrap file, things are still going to change a fair amount.

In the case of https://github.com/gratipay/gratipay.com/commit/cf35a41009870cf1ea7c61c7a7b19b4752845a54, the default amount of noise caused by the regeneration of the file has been exacerbated by running `npm-shrinkwrap` or something similar on it, to strip out all of the `resolved` fields. That's fine, but it will cause the diff to be noisier, by intention and design. Also, to the best of our knowledge, this isn't something that npm does by itself.

**Comment by techtonik** [comment]
> the regeneration of the file has been exacerbated by running npm-shrinkwrap or something similar on it

No. The command that was run is: `npm shrinkwrap --dev`. See that some resolved fields are just migrate from one part of file to another.

Sorting the tree before processing and before dumping should resolve the problem.

**Comment by othiym23** [comment]
There aren't _any_ `resolved` fields in the new version of the file, which makes me suspect that a much older version of npm was used to generate the new file. What version of npm did you use for the new file? The dependencies are in the same order in both versions, and only a few have had `from` fields change (probably due to changes in the versions of those dependencies installed in the local application). As far as I can tell, the main change in the file _is_ the disappearance of the `resolved` fields. `resolved` is the primary mechanism that newer versions of npm uses to ensure that the same versions of dependencies get installed.

**Comment by techtonik** [comment]
# npm --version
1.3.10

**Comment by techtonik** [comment]
```
# npm --version
1.3.10
```

**Comment by techtonik** [comment]
This is the version that comes with Ubuntu.

**Comment by othiym23** [comment]
`npm@1.3` hasn't been supported for at least six months now (the Ubuntu versions of Node and npm are both incredibly out of date). The latest version is `npm@2.11.0`. Versions of npm that old don't use the `resolved` field. Update to [the latest stable version of Node](https://github.com/nodesource/distributions) and [then upgrade npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and you should get a less noisy shrinkwrap file, but as I said, npm makes no guarantees about the contents of `npm-shrinkwrap.json` staying stable over time.

**Comment by techtonik** [comment]
Is it possible to stuff updated `npm` into Ubuntu backports? It is backward compatible, yes?

**Comment by othiym23** [comment]
I'm sure it's possible to do so, but it would require somebody closer to Ubuntu to either get that into one of the backport channels, or to create an npm PPA for use by everybody. Because of the way that Node and npm are packaged together, most people just use the [NodeSource PPA](https://github.com/nodesource/distributions). The Debian packaging for Node and npm used by the default Ubuntu packages is pretty high-maintenance due to the requirements of Debian packaging policy. As an upstream vendor, it's neither appropriate nor practical for the npm team to take on that responsibility themselves.
