### ISSUE TITLE
Problem with atomic write & non configurable ./node_modules & docker compose

### ISSUE THREAD

**Issue by mathroc** [npm/npm#8477]
I'm trying to build a dev environment with docker-compose that would allow me to run npm as 'docker-compose run `npm [...]` and that would save node_modules inside a datacontainer (in `/scripts/node_modules/`)

the only file I'd like to be shared between the local host and 2 containers (npm & nodemodules) is `package.json`. however npm (actually the rename in `write-file-atomic` need to have write access to the folder containing `package.json`. As a workaround I could share a folder (eg: `./npm/`) containing `package.json` from the host but then I can't mount a volume (`/scripts/node_modules/`) from another container inside a volume from the host (`./npm/`)

To solve this, I can think of two ways, either have a `--no-atomic-write` switch or have a way to put `package.json` & `node_modules` in separate folders. I guess the first is easier to implement but it might not be something you want into npm as it's only for a very specific use-case. the later might be more interesting (I think I saw others asking for a way to configure the `./node_modules` folder)

do you have opinion on this ? or is there already work in either directions? or even an alternative I couldn't see ?

thank you

**Comment by othiym23** [comment]
The current way that files are written is the end result of nearly uncountable hours spent debugging race conditions within npm. For that reason `--no-atomic-write` is not an option, because it would reintroduce a class of error conditions that were (and still are – I'm not convinced we've found all of them) extremely subtle and pernicious.

On the other hand, `package.json` and `node_modules` and their relationship to each other are pretty much hardcoded into npm, and having that all conceptually unified is a pretty core component of how npm operates, so that's not going to change either.

This doesn't sound like something that requires changes to npm to implement, though. It seems to me that some combination of bind mounting (which allows you to mount down to individual files) and symlinking within each volume would give you what you need. That said, the scenario you're describe sounds pretty complicated to me, so I'm probably missing some important context.

I'm interested to hear what your goals are for the setup you describe, but I can tell you that we're unlikely to remove anything that was added to fix race conditions without addressing the underlying race in a different way.

**Comment by rlidwka** [comment]
> I think I saw others asking for a way to configure the ./node_modules folder

Yes, there is a lengthy discussion here: https://github.com/npm/npm/issues/3597
