### ISSUE TITLE
npm ERR! install Couldn't read dependencies

### ISSUE THREAD

**Issue by tskkh** [npm/npm#8488]
Hello,
I have a problem while installing Laravel Elixir.
I get error with command : $ npm install 
```
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/tsk/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tsk
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/tsk/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tsk/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@tskkh Does `/home/tsk/package.json` exist?

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like `npm` is looking for the file `/home/tsk/package.json` and is unable to find it.  Does that file exist?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by kaushalgosaliya5** [comment]
i have this same error, see my error log : 

npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/yama/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-97-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/yama
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/yama/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yama/npm-debug.log
npm ERR! not ok code 0

**Comment by legodude17** [comment]
@kaushalgosaliya5 Your versions of `node` and `npm` are years old and no longer supported. Please update.
