### ISSUE TITLE
Why is a version required in npm's package.json? I use it for dependencies only.

### ISSUE THREAD

**Issue by Daniel-Hug** [npm/npm#8512]
Why is a [version required in npm's package.json][1]? I'm only using npm in my project to include dependencies. It does not need to be an installable package.

Even if my package did need to be installable, couldn't npm just go off the git tags? That way I wouldn't have to update the package.json version with every change.

  [1]: https://docs.npmjs.com/files/package.json

**Comment by smikes** [comment]
Thanks for bringing this up.

It sounds like you don't need/use the `version` field.  What happens when you just leave it at the default of `1.0.0`?

I believe making `version` mandatory was a historically early decision, reflecting npm's early focus on making re-usable modules available.  Now, of course, this dependency has implicitly spread through the `npm` codebase, so I believe it would be quite hard to remove.

I find that the easiest way to manage git + `package.json` versions is to use the `npm version` command, e.g.,

```
$ npm version patch
```

This updates the package.json version by incrementing the patch level, and creates a git tag at the same time.

**Comment by Daniel-Hug** [comment]
> Now, of course, this dependency has implicitly spread through the npm
codebase, so I believe it would be quite hard to remove.

This sounds like really poor architecture.  :(

**Comment by sindresorhus** [comment]
That doc looks outdated. `name` and `version` are optional for non-published package.json.

**Comment by othiym23** [comment]
How long would it take @isaacs and I to discuss a seemingly simple point of documentation and implementation detail? The answer might surprise you!

@sindresorhus is not wrong that the documentation doesn't completely capture what's going on here now. In old versions of npm, if `package.json` were missing `name` or `version`, npm would throw up its hands and cryptically error out. Now, `npm install` and `npm ls` will both work (albeit with some weird-looking output in the case of `ls`) when either `name` or `version` are missing, but that's not the whole story.

npm is first and foremost a package manager, and the documentation is built around publishing packages. A published package must have a name and a version, and because the vast majority of npm's users are going to want to use that documentation to publish their packages, the documentation is written with that purpose in mind.

We have this problem with the npm documentation where it's tough to balance completeness with comprehensibility. This is a case of why that balance is tough to strike: if we want to be completely accurate about what npm actually _does_ (i.e. not care in practice whether `name` or `version` are there), we're going to put stuff in there that's going to be confusing in the general case.

If you _really think_ it's a problem that the documentation is at odds with reality, put together a patch and we'll work together to get it added. But it'll probably take a little wordsmithing, because I do think in general we do want people to be treating `package.json` like package manifests and not just dependency lists.

Thanks for the discussion, everybody!
