### ISSUE TITLE
Newbee trying to install phonegap and got error; told to come here...

### ISSUE THREAD

**Issue by lbray** [npm/npm#8538]
Please be gentle...i am a newbie :)
The error on the admin cmd.exe screen is...

npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

I tried attaching the log but the preview screen keeps telling me that the 1.28 MB "file is empty". I'll try to paste. That didn't work :(

ugh...now it recognizes the file but says it doesn't support it because it's not a pic!!!

ok...ok....i uploaded it to a server...
http://prbseminary.org/npm-debug-log.txt

Please help!

**Comment by johnwargo** [comment]
Its always best to simply read the error message, all the information you need to understand the issue is at the end:

26560 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
26561 error node v0.12.4
26562 error npm  v2.10.1
26563 error code ECONNRESET
26564 error errno ECONNRESET
26565 error syscall read
26566 error network read ECONNRESET
26566 error network This is most likely not a problem with npm itself
26566 error network and is related to network connectivity.
26566 error network In most cases you are behind a proxy or have bad network settings.
26566 error network
26566 error network If you are behind a proxy, please make sure that the
26566 error network 'proxy' config is set properly.  See: 'npm help config'
26567 verbose exit [ 1, true ]

The ECONNRESET is a network connection reset error - npm lost its connection to the server.  Did you reboot and try again?  Are you connected to the server via a proxy?  If so, there are proxy settings you will need to set for this to work. You can find how to do this on page 72 of Apache Cordova 4 Programming (www.cordova4programming.com).

**Comment by lbray** [comment]
Thank you so much...i will try to run this through again later today...making sure i have a strong connection first.
To be honest, i didn't even think about reading the log file because i am so new to this side of programming....dumb move on my part. Thanks so much for taking the time to set me straight, i really appreciate it.
