### ISSUE TITLE
How to get the result with npm.commands.test and npm.commands.install

### ISSUE THREAD

**Issue by LeaYeh** [npm/npm#8551]
I would like to create a function that can return the result by npm test.
I tried to use this function 
```javascript
npm.commands.test(packages, callback)
```
how to get the result (unit test is success or fail)? and what is the callback function look like?

**Comment by iarna** [comment]
It sounds like you're trying to use npm's internal API. This isn't supported (and we've since withdrawn the documentation for it) because we need the freedom to change it in possibly breaking ways. Right now it's very poorly structured and as you discovered, hard to use.

I would recommend instead that you use [`child_process.exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) to run the `npm test` command line– if the tests run ok then there won't be an error object in the callback, if they fail there will be.
