### ISSUE TITLE
remote: Invalid username or password (but no prompt)

### ISSUE THREAD

**Issue by batwood001** [npm/npm#8552]
I am running the command "npm install -g git+https://github.com/makersquare-labs/problemify.git" and getting the following lines of errors (sorry for readability):

npm ERR! git clone --template=/Users/brianatwood/.npm/_git-remotes/_templates --mirror https://github.com/makersquare-labs/problemify.git /Users/brianatwood/.npm/_git-remotes/https-github-com-makersquare-labs-problemify-git-8cf65cbe: Cloning into bare repository '/Users/brianatwood/.npm/_git-remotes/https-github-com-makersquare-labs-problemify-git-8cf65cbe'...
npm ERR! git clone --template=/Users/brianatwood/.npm/_git-remotes/_templates --mirror https://github.com/makersquare-labs/problemify.git /Users/brianatwood/.npm/_git-remotes/https-github-com-makersquare-labs-problemify-git-8cf65cbe: remote: Invalid username or password.
npm ERR! git clone --template=/Users/brianatwood/.npm/_git-remotes/_templates --mirror https://github.com/makersquare-labs/problemify.git /Users/brianatwood/.npm/_git-remotes/https-github-com-makersquare-labs-problemify-git-8cf65cbe: fatal: Authentication failed for 'https://github.com/makersquare-labs/problemify.git/'
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "git+https://github.com/makersquare-labs/problemify.git"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/brianatwood/.npm/_git-remotes/_templates --mirror https://github.com/makersquare-labs/problemify.git /Users/brianatwood/.npm/_git-remotes/https-github-com-makersquare-labs-problemify-git-8cf65cbe
npm ERR! Cloning into bare repository '/Users/brianatwood/.npm/_git-remotes/https-github-com-makersquare-labs-problemify-git-8cf65cbe'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/makersquare-labs/problemify.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brianatwood/npm-debug.log

**Comment by batwood001** [comment]
Changed https to ssh. Not sure why this worked, but fixed the issue.

**Comment by thynson** [comment]
+1

**Comment by gaurav21r** [comment]
@batwood001 I have the EXACT same problem. Changing to SSH is a temporary fix! I think you should reopen it!

**Comment by vikashvikram** [comment]
Though the issue is closed, I want to share how I solved the issue. When you try to fetch package that is written as https or as git+https (and your public key is not deployed at the place where package is residing), you need to give username and password. But npm does not ask for it. Rather it gives you error of `invalid username and password`. To solve this, you need to have your username and password in cache or on disk by running `git config --global credential.helper cache` or `git config --global credential.helper store`. If you run this command and do a manual git clone for any such git based repo, it will put your credentials in cache or on disk (kind of cache warming). afterwards you can run npm install with https or git+https and it will run fine. There are some gotcha though. When you put credentials in cache, it will be valid for only some time (may 15 minutes). You can of course configure it. When you put credentials in store, your credentials will be in plain text on disk (most probably at ~/.git-credentials file). Watchout for these hence.
