### ISSUE TITLE
ECMAScript version convergence

### ISSUE THREAD

**Issue by h2non** [npm/npm#8558]
I've some conflicting ideas about this, however I believe it's definitively a good point that worth to discuss.

ES6 is here, finally. ES5 is still there, and it will remain for a while. And the history will reappear with ES7 in the next years. Change is positive, and it should stimulate and inspire the community, not become a source of fear or uncertainty. 

Migration is usually hard. Convergence is not a trivial stuff.  I'm concerned about how `npm` could deal with this and how an efficient package manager could assist to that convergence process for the JS community evolution.

We know that `npm` packages could be restricted to an specific engine, but I think that is not enough.
We're seeing the last year a considerable number of package which are specifically for ES6 compatible runtime (e.g `io.js`).

I'm trying to imagine a brave world where multiple language standard can converge with peace and grace. The big thing here is about providing a convergent and natural ecosystem where you as package consumer shouldn't think about ES standard constraints when using packages. 

As library developer, you can decide which standard you wanna use, e.g ES6, and write your module for that standard. Then, you can publish it with specific metadata in `package.json` which specifies the standard version.

A possible idea to simplify and trying to abstract the convergence intrinsically problem could be using a custom ES6-to-ES5 transpiler called by `npm` in runtime when installing a new package, based and depending of the package metadata and runtime engine, so it could automatically transpile the code to compatible runtime engine. Ideally, the transpiler could be customized by the package developer (and provisioned if required by `npm` as well). 

I know that since the last year `npm` is tending to become a more generic `node`-agnostic package manager solution. I'm not sure about the proper scope of this proposal or if it's completely reasonable thinking about it or not these days for `npm`, but I strongly believe that this problem should be solved by someone to help and simplify the convergence between JS-today and JS-next, just because the community is claiming for that, and `npm` has a excellent position to start moving forward with this process.

**Comment by othiym23** [comment]
Having good support for new versions of the JavaScript language is important to the npm ecosystem. npm on its own is only capable of handling part of ES2015, though. There’s currently an [active discussion](https://github.com/nodejs/node-eps/pull/3) happening within the Node.js organization about how best to land support for ES modules. I bring this up because I believe that modules have the appropriate level of encapsulation for opting into new ES features at the package or module level (it’s not clear yet whether ES module support is going to be applied per package or per file). Depending on which version of Node you run, you get some or more of the ES2015 features (no version of V8 has full support for all ES2015 features).

ECMAScript has been moving to a “living standard”, release-train based model for rolling out new language features, which in practice means that support for ES2015 features is trickling into runtimes gradually. Because the Node runtime doesn’t export any kind of matrix of what newer language features it supports, and because maintaining such a matrix is out of scope for the npm CLI team, developers are going to need to use a transpiler or do feature detection for the foreseeable future. The safest way to use new features without transpilation is to say which minimum version of Node.js (or browser runtime) is necessary to include the features your application needs, which can be done with the current `engines` field. As such, for now the team is going to leave this alone, and close this feature request. Thank you for the detailed problem statement!
