### ISSUE TITLE
How to ship binaries with npm using package.json?

### ISSUE THREAD

**Issue by cookiengineer** [npm/npm#8585]
I wanted to ask what the proper way is to ship binaries with npm.
I realize that npm has no support for binaries at all, but they are in a seperate repository on github.

Is there a way to have a dependencies in the package.json that downloads the git repository to a specific subfolder?

Say I want repository `github.com/foo/bar.git` installed into the subfolder `./bin/foo` of my main project?

I already read the [package.json docs](https://docs.npmjs.com/files/package.json), but they are pretty much out of date (and commonjs website is down) and I couldn't find anything related in there.

**Comment by aredridel** [comment]
The package.json docs are up to date! Not much has changed in a while.

You probably want a script to do that downloading, rather than expressing it as a dependency. Either that or package it into the package in the first place.

**Comment by martensms** [comment]
The issue with that is that the binaries are beyond 300MB as it's an SDK dependency. As there's no way of having OS-specific determination inside NPM, I don't want to have users having to download gigabytes of files and deleting the unnecessary ones afterwards.

So is the shell script the way to go here? Then I might just avoid shipping the project via npm, as I need several features such as architecture detection, os detection and stuff like that.

Will something like this be possible with NPM in the future?

**Comment by othiym23** [comment]
> Will something like this be possible with NPM in the future?

This use case is partially handled by a number of existing tools, most notably [`node-pre-gyp`](http://npm.im/node-pre-gyp). That's designed to save time when installing packages with native-module components, but isn't exactly what you're looking for with respect downloading an entire SDK installer. For that, you might look at a package like [`phantomjs-prebuilt`](http://npm.im/phantomjs-prebuilt), which uses a custom Node script to determine platform and OS (and any other dependencies) before downloading an architecture-specific, prebuilt binary.

In general, the features you're asking for are really more the domain of distribution package manager like `pacman` or `apt-get`, and I don't see npm adding the full versions of that kind of multi-architecture support – it's a tool for application developers, rather than a full system tooling manager. That said, there are tools like the above to simplify platform-specific tasks, which should address your needs. For now, I'm going to close this issue because this isn't something the team intends to address in the next 6-12 months. Thanks for your time!

**Comment by cookiengineer** [comment]
[This](https://github.com/Medium/phantomjs/blob/master/install.js#L403) is a joke, right? You can't be serious about that ... I'm kind of speechless about how obviously this is error-prone with any kind of fixes or updates in the future.
