### ISSUE TITLE
npm unable to install the appdynamics agent for nodejs

### ISSUE THREAD

**Issue by su008si** [npm/npm#8633]
Hi,

I am not able to install the appdynamics agent fro nodejs. I am getting the below errors:
I am using node version :0.8.28. I have tried installing the various versions of appdyanamics agent but somehow it always fails with the below issues.
```
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-native.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-protobuf.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-zmq.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-native.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-protobuf.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-zmq.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-native.tgz
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-protobuf.tgz
npm ERR! fetch failed http://packages.appdynamics.com/npm/4.0.6.0/appdynamics-zmq.tgz
npm ERR! Linux 4.0.3-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install" "appdynamics@4.0.6"
npm ERR! node v0.8.28
npm ERR! npm  v2.11.1

npm ERR! fetch failed with status code 403
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /src/backend/npm-debug.log
```

**Comment by zkat** [comment]
Hi! It looks like you have credentials/access issues here -- try going back to the appdynamics docs for installation, or go to them for support on this.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by zone21** [comment]
Met the same issue, is this problem resolved ? And how to resolved?

**Comment by beingshashi** [comment]
i am still facing same issues @ehsalazar

**Comment by zkat** [comment]
@zone21 @beingshashi Note that we don't directly support AppDynamics' registry -- the issue seems to be with configuration or support related to them, specifically, instead of being an npm CLI issue (which is what this repo is for).

One clue as to the 403 might be over at https://community.appdynamics.com/t5/AppDynamics-Discussions/403-on-npm-install/td-p/21222, but besides that, there's not much we can do to help you here.

**Comment by beingshashi** [comment]
Hi,

i have to downgrade my npm and nodejs version in order to download your 
registry.

After downloading your registry i have attached your code into my nodejs 
server file.

after running server.js file on port 8000 , your application is not able 
to connect to the my application..

How to check what is going wrong.

Thanks,

**Comment by Meldryn** [comment]
Hi Beingsashi,

This is not a bug in npm itself. Please file a support case at help.appdynamics.com and we'll resolve this swiftly.

Best,
AppDynamics Support
