### ISSUE TITLE
npm i mailgun-js fails

### ISSUE THREAD

**Issue by abelino** [npm/npm#8641]
this is very interesting. This worked a couple days ago... So for some odd reason I am able to install any mailgun-js version prior to an including 0.6.7, anything after will through the following err

user$ npm i mailgun-js
npm ERR! addLocal Could not install /var/folders/v3/wzzkhj893j51p4cj94zm6fv00000gn/T/npm-28153-0610ceef/git-cache-f651c62a29f7/734ff0028274ab4254d2c06e67efbf2dceaf2b72
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "mailgun-js"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code EISDIR
npm ERR! errno -21

npm ERR! EISDIR, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ~/npm-debug.log

**Comment by abelino** [comment]
I traced it down to:
"esprima": "git+https://github.com/ariya/esprima.git#harmony" dependency in

https://github.com/TooTallNate/node-degenerator/blob/master/package.json

Any ideas?

**Comment by abelino** [comment]
Ahhhh the unofficial harmony branch has been removed...

This unofficial harmony branch has been removed.

Esprima 2.x continues to add supports for ES6 features (#1099). It is
recommended to use the latest 2.x release, e.g. from its official
[npm module](https://www.npmjs.com/package/esprima).

Which means anyone or any module using the latest node-degenerator module is currently BROKEN... will open a an issue with degenerator...

mark this issue as resolved as it does not directly pertain to NPM. Thanks

**Comment by tgriesser** [comment]
Just came here to comment the same, it looks like the harmony branch of that fork is [no longer a thing](https://github.com/ariya/esprima/tree/harmony)

Which is unfortunate because it looks like it's linked from at least a number of places: https://github.com/search?utf8=%E2%9C%93&q=%22ariya%2Fesprima.git%23harmony%22&type=Code&ref=searchresults

I can't even think of a way to work around this because the 1.0 dependency of degenerator is currently pointing to a non-existent git branch, so I don't even know if there's a way to specify something that can override this? Tried installing `espirma` locally but no dice.

Perhaps someone with better knowledge of npm would have a suggestion here?

**Comment by abelino** [comment]
It was wrong for people to use the unofficial branche in their node modules to begin with. The fault for this mess does not lie with npm nor esprima, but the devs that chose to use that branch. I am not familiar with esprima, and don't know why an official release couldn't have been used instead of that branch... I am guessing it had some functionality that wasn't in the latest release?? no idea... but as you pointed out already, many modules are currently broken because of this.

I just checked the standing issues for node-degenerator and looks like it has already been pointed out to the dev, but no response... Module might be dead for now... this is a huge mess

**Comment by othiym23** [comment]
Closing as not an npm bug, even though this is really awkward for users. :/ Good luck getting it sorted out!

**Comment by tgriesser** [comment]
I guess the lesson here not to depend on git repositories you don't have control over.
