### ISSUE TITLE
Support run script as fallback to non-existent command

### ISSUE THREAD

**Issue by adjohnson916** [npm/npm#8677]
Support run script as fallback to non-existent command. E.g. if I execute `npm build` where `build` is not an npm command, but is in my `scripts` in `package.json`, then it would be effectively like executing `npm run-script build`, or the current shortest possible variant of `npm ru build`.

**Comment by selbekk** [comment]
Hear hear!

**Comment by othiym23** [comment]
We're considering a few possible extensions to package scripts that will make them more useful, but this particular version of this feature is not particularly forward-compatible. For now, I'm going to close this issue because it doesn't fit in with what we're currently planning. We're going to be putting some work into improving the separation of concerns around builds and the lifecycles and making package scripts more self-contained, and this is an interesting idea to consider in that light. Thanks for the suggestion, and thanks for your time!

**Comment by adjohnson916** [comment]
@othiym23 Good point about forward-compatibility. I'll just have to stop accidentally forgetting to type `run`... :)

I'd be excited to hear about further enhancements coming to package scripts. One thing I often use is https://www.npmjs.com/package/npm-run-all.

**Comment by adjohnson916** [comment]
`yarn` does it!
