### ISSUE TITLE
`npm install` is noticeably slower

### ISSUE THREAD

**Issue by ajcrites** [npm/npm#8690]
This may just be an unavoidable product of new multi-stage installer, but `npm install` in npm@3 is measurably slower than npm@2.  My testing was done on Ubuntu 15.04.

`npm@3 i node-sass` takes a bit over 30 seconds on my system.  `npm@2 i node-sass` takes less than half that amount of time.  This is consistent and it is noticeable even for modules with few nested dependencies like `readable-string`.

Explicitly disabling the progress bar is not possible at this time so I tested with a hacked `npm` that disabled the progress bar.  This may have a small impact on performance, but not much.

Projects with a larger but still relatively short list of [depdendencies such as this](https://gist.github.com/ajcrites/4f3d10e1c2440e732839) still take over twice as long to install vs. npm@2.  With this particular list, `npm@3 i` on my system consistently took over 2.5 minutes, but `npm@2 i` took less than a minute.

**Comment by pushred** [comment]
Experiencing this as well.. thought that reverting to npm@2.12.0 wasn't even working because of the progress bar which took over a minute to indicate any progress.

**Comment by othiym23** [comment]
This should probably be added to the Known Issues section of the release notes – because `npm3`'s multi-stage installer stresses correctness, it's doing more work than the old install code, and is therefore slower, especially when doing global installs where there are many packages installed. The deeper your (logical) module tree, the slower `npm@3` will seem, because it's now always reading the entire dependency tree and creating the ideal tree in-memory before installing new packages.

Once the obvious bugs have been sorted out, we'll take a deeper look at performance.

**Comment by iarna** [comment]
There are definitely room for improvement here (there are some obvious bottlenecks, although none with obvious fixes).  But yeah, after we have it working correctly.

**Comment by iarna** [comment]
I'm consolidating this into #8826-- we definitely want to do some profiling and performance improvements before we call this beta over. =)
