### ISSUE TITLE
There are now 1,000 issues open on the npm issue tracker again.

### ISSUE THREAD

**Issue by othiym23** [npm/npm#8715]
Once again, we gotta come up with a plan to beat these back down to a reasonable number. Work on that is in progress.

**Comment by jhr007** [comment]
NPM isn't alone in this problem. I think this needs be solved on two fronts. OSS community awareness of best practices for triaging issues. Improved technologies that support that.

Success involves answering 2 questions:  
1. Do you know what you're supposed to do? 
2. Do you have the tools are resources?  

For Developers I think 2 is minor, we can make a tool. 1 is the harder question because awareness and adoption takes time. If this is your first trip to Rome, how do the Romans do it? :confused: 

Take my User Story: I'm a stranger around here. I was doing some issue browsing on #3573. Essentially chasing semantics and bikeshedding. Along the way I noticed a couple support requests that would be easy pickings for closure, but wasn't sure what to do(Q: 1). I don't have label permissions, and I'm not any more attached to this project than any other, so I don't need them. I didn't want to bump a dead thread. I did consider pinging a user because I saw her tagging things in that thread, but is that a faux pas? 

This could perhaps be solved extending the CONTRIBUTING.md to add a section on helping maintainers and friends triage issues. Maybe even an ISSUE-MANAGEMENT.md ? A link to said file on every issue(*HINT*HINT* @github)

My bikeshed implementation: 
Maybe a tagging method for the general public that a bot could take action on
eg
#NoReponse - OP is non reponsive with issue, bot can close week after this tag. 
#Resolved - Issue is resolved indirectly by a pull-request but issue didn't close. 
#StaleSupport - Close in a week with a message pointing OP to reopen if not resolved and suggestions to try stackoverflo and other resources. 
#ProblemElsewhere - Not something this repo supports. 

Hope that helps and good luck.

**Comment by sakshamsaxena** [comment]
Hey, it isn't that bad. Look at (Brackets)[https://github.com/adobe/brackets]. They have more open issues than npm. 
Hope that gives you some inspiration.
And yes, @jhr007 said a few which I had in mind, like the tagging method and bot's involvement.

**Comment by KenetJervet** [comment]
@sakshamsaxena No npm has finally beaten brackets (1790 vs 1567)
