### ISSUE TITLE
npm init brings in flattened dependencies in v3

### ISSUE THREAD

**Issue by substack** [npm/npm#8716]
I usually do `npm init` right before I publish, so I've already got a ton of files in `node_modules/` with the new flatter behavior in v3. When it comes time to `npm init`, npm thinks all of those flattened dependencies belong in my package.json as top-level dependencies.

**Comment by iarna** [comment]
Yup, it should totally do the right thing here.

To do this it needs to use `read-package-tree` like everything else in `npm@3` and then look for packages with a `_requiredBy` containing `#USER`, which indicates they were installed by direct user action and not due to a subdep or an existing `package.json`.  It might be reasonable to also include any module that _doesn't_ have a `_requiredBy` field– that'd be modules installed via `npm@2`, and any module that depends on `/`, which would be from a previous `package.json`.

**Comment by govpack** [comment]
I heard it always does the "right thing". 
*__  😱 based BOTH on universal standards & models for ethical and absolute correctness.__* 
I mean, they exist don't they!! RTFM or RTFSC it's all in there. init'ing after the fact, i like that, that's so manga, now they're busy re-wiring who put what where!!

**Comment by iarna** [comment]
Aaand, this lives off in `init-package-json`, which complicates matters because it's building its tree in an entirely npm independent manner. I think this is going to require some (much needed) refactoring to extract those parts of the new installer into independent modules.

**Comment by iarna** [comment]
So yeah, this landed in 2.14.0 and 3.3.0!
