### ISSUE TITLE
Pass module version on preversion and postversion scripts.

### ISSUE THREAD

**Issue by zanona** [npm/npm#8730]
Following up https://github.com/npm/npm/issues/7906#issuecomment-113053984

I am just wondering that it would be great to be able to know the version number being passed through the script `preversion` for example?

This would be helpful for those having hybrid modules (npm + bower) and bumping versions at the same time?

This could be a nice workflow:

``` js
{
    "name": "module",
    "version": "1.0.0",
    "scripts": {
        "preversion": "bower version $1"
    }
}
```

**Comment by jasonkarns** [comment]
Perhaps instead of having the new version "passed in" as a script arg, we just ensure that `$npm_package_version` is updated during the version bump so that it is the correct version? As it stands now, `$npm_package_version` is read in during the `preversion` phase and remains unchanged throughout the lifecycle. Which means it has the wrong value during `version` and `postversion` scripts.

Updating `$npm_package_version` to have the correct value gives scripts access to the correct version string, while also being referenced with a clearer name than `$1`.

**Comment by krnlde** [comment]
I second that use case with bower! Great request

**Comment by maxbarrett** [comment]
+1

**Comment by othiym23** [comment]
The CLI team agrees that the behavior described up top is the expected behavior, and can probably be achieved by simply tweaking the version post-change in the in-memory version of the package before calling the `postversion` lifecycle script. If somebody wanted to put together a patch to do this, we'd be happy to answer any questions about how to implement it. Thanks for filing this!

**Comment by jasonkarns** [comment]
I think this can be closed since `$npm_package_version` is available in `preversion`, `version` and `postversion` hooks.

The value of the version in `$npm_package_version` is the bumped version for all three hooks, and #11253 is open to address making `$npm_package_version` the pre-bumped version for the `preversion` hook.
