### ISSUE TITLE
npm outdated failes with 404 if module is not in the registry

### ISSUE THREAD

**Issue by dbrockman** [npm/npm#8752]
Issue found in version 2.12.0
Works fine with version 2.11.3

`npm outdated` fails with a 404 error when one of the dependencies is not published to the registry, e.g. a github url with a tag. Before 2.12.0 it would ignore those dependencies and list the ones available from the registry.

This might be by design but if so I think a better way would be to highlight that particular dependency instead of failing altogether.

**Comment by kostrse** [comment]
Having the same issue!

`npm outdated -g` fails with 404 when you have some private repos linked by `npm link` (thus they cannot be found in the public registry).

```
node v0.12.4
npm  v2.12.0
```

It should just list them as *"not found in registry"*, but not fail.

**Comment by KenanY** [comment]
Is `"private"` set to `true` on these modules?

**Comment by kostrse** [comment]
I believe this shouldn't matter.

npm should return adequate output, not crash with error:
```
boo: 1.2.3 ...
foo: not found in registry
zoo: 2.3.4 ...
```

**Comment by KenanY** [comment]
@kostrse Well, I patched (https://github.com/npm/npm/pull/6862) `outdated` a while ago to ignore _private_ packages to avoid 404 errors like these :), but I do see now how terminating with an error is less than ideal.

**Comment by kostrse** [comment]
Or maybe a better solution:
Could you just ignore symlinked packages and not make requests for them?

**My case:**
In my global packages directory I have:
1. several legit packages which came from the registry and need to be checked whether they outdated or not (e.g. `gulp`, `npm`, `typescript` etc.).
2. but also I'm having a couple of packages linked in this directory by `npm link`.

``` sh
ls -al ~/.node/lib/node_modules/

drwxr-xr-x  19 646 Jun 27 02:31 .
drwxr-xr-x   3 102 Jan 17 20:54 ..
drwxr-xr-x  11 374 Jun 16 19:12 gulp
drwxr-xr-x  26 884 Jun 27 02:16 npm
drwxr-xr-x  12 408 Jun 18 20:14 typescript
lrwxr-xr-x   1  60 Apr 28 22:44 my-dirty-package-1 -> /Users/user/Dev/my-dirty-package-1
lrwxr-xr-x   1  60 Apr 28 22:44 my-dirty-package-2 -> /Users/user/Dev/my-dirty-package-2
```

`npm link` is intended for simplification of development and debugging, and the packages in fact may be *dirty*. They are symlinked as global packages and break the npm commands, and this is confusing, because I didn't install them specifically with `-g` switch.

So, as long as they linked there, could they be just ignored?
This is the case not only for `outdated` command, but also for other commands like `update`.

**Non-global, project packages**

The same problem with local packages in project, if project has several downloaded packages, and some of linked packages, the linked packages should be ignored when invoking commands like `outdated` and `update`. This is even doesn't make sense - I don't need to update packages which I specifically *npm-linked* for development.

**Comment by kostrse** [comment]
Or better split this to another bug?

**Comment by jorrit** [comment]
I guess this broke in 765fd4bfca8ea3e2a4a399765b17eec40a3d893d . It would be great is `parsed` in `lib/outdated.js` could also contain `linked` or something like that, so the line could be:
`if (parsed.type !== 'local' && parsed.type !== 'linked') return cb(er)`

**Comment by detj** [comment]
I am also having the same issue while running `npm outdated --global`. I too have a few `npm link` packages.

**Comment by schmod** [comment]
At risk of sounding like a "+1", I am also having this issue.  

The module in question does indeed have `private:true`.

**Comment by privatmamtora** [comment]
If `link`ed modules are present, could skip and warn (not error)

The `private` option works (it is being used incorrectly `3.3.5`), but people don't want to do a edit before committing each time.

**Comment by schmod** [comment]
I think a skip/warn is desirable even if a `link`ed module is not present.  If I my `package.json` lets me successfully run `npm install`, `npm outdated` should not fail with a fatal error.

**Comment by AVVS** [comment]
any progress on that? It's been ages and this is really-really inconvenient

**Comment by williamboman** [comment]
Here's a temporary workaround;

```sh
global_packages="$(find "$(npm root --global)" -mindepth 1 -maxdepth 1 ! -type l -exec basename {} \;)";
outdated_global_packages="$(npm outdated --global --parseable ${global_packages} | cut -d: -f2)"
```

**Comment by halhenke** [comment]
From fiddling around with the source its pretty much as @jorrit says - 
e.g. if you mangle `updateDeps` like so
```javascript
  function updateDeps (er, d) {
    if (er) {
      if (parsed.type !== 'local') {
        return doIt('----', '----');
      }
      return updateLocalDeps()
    }
  ...
```

then you get back something like this

```
Package                    Current  Wanted  Latest  Location
caper                        1.0.0   0.0.2   0.0.2
caper-activities             1.0.0    ----    ----
child                        1.0.3     git     git
eslint-plugin-react          3.5.1   3.6.3   3.6.3
fly                          0.8.3   1.1.9   0.8.3
gulp                 4.0.0-alpha.1   3.9.0   3.9.0
live-server                  0.8.1   0.8.2   0.8.2
node-sass                    3.4.0   3.4.1   3.4.1
npm                          3.3.9  3.3.10   3.3.9
```

which prob breaks other stuff & just isnt ideal.

Again as @jorrit says there doesnt seem to be any distinction between symlinked dependencies or anything else - [here](https://github.com/npm/npm/blob/master/lib/outdated.js#L335) and [here](https://github.com/npm/npm-package-arg/blob/master/npa.js#L39) it seems we look at the requested dependecy source/version and theres no indication there if the package is actually being symlinked into `node_modules`. 

So I guess to do a deep/proper fix you would want to somehow/somewhere flag linked packages? Personally I'd be happy with something quick and easy as above (though not such a clueless hack obv). 

Just thought I would put this out here because I ended up going partially down this rabbit hole and just in case it helps someone who understands the codebase better come up with a solution.

**Comment by halhenke** [comment]
Following some discussion on the freenode channel with @othiym23 I would be happy to take a shot at this if @othiym23 or someone else felt comfortable assigning it to me...

**Comment by othiym23** [comment]
@halhenke Go for it! We use assignment as a tool to track which members of the CLI team are responsible for which things, so all you need to do is submit a PR, and we'll work with you from there. Thanks for your interest in contributing!

**Comment by halhenke** [comment]
Cool! Will throw up a WIP PR when I have something going :-)

**Comment by schmod** [comment]
Thanks @halhenke and @iarna!

**Comment by timbru31** [comment]
Am I doing something wrong or does neither npm v3.7.0 nor 2.14.17 fix this issue completely?
We have some dependencies that are installed via https from a .tgz file. These are only accessible within our company network.
npm outdated with 2.11.3  does work, but 2.14.17 still fails.

(if necessary I'll post a npm-debug.log)

**Comment by joelanman** [comment]
I'm still getting this issue in npm v2.14.12. I'd rather use the node 4 LTS release - do I need node 5 for this fix?

**Comment by halhenke** [comment]
@timbru31 Those fixes were only for packages that were present due to being symlinked - presumably by `npm link`. The sort of thing people commonly do when testing/using a package that is being locally developed. It shouldn't make any difference to tarballs installed from private repos.

Apparently this caused issues with calling update on linked modules but another PR from a few weeks ago should have dealt with that. Does any of this describe the issues you are experiencing?
