### ISSUE TITLE
ERR 404 while installing private scoped packages

### ISSUE THREAD

**Issue by mrcrgl** [npm/npm#8770]
Hey there,

I actually have a problem and cannot explain it on my own. Maybe someone of you.

I have a project which depends on scoped (private) packages and public ones. For continuous integration, I've put a `.npmrc` in the project root with contents like:

```
//registry.npmjs.org/:_authToken=(secret)
```

This works on my local maschine (npm 2.7.4, node 0.12.2) fine (cannot reproduce) but on codeships shell (tried many versions, but at least those from my local maschine) i'll get a 404 on my scoped packages when using `npm install`. The clou: If I try `npm install @account/package` it works. After installing ~2 packages manually, `npm install` works fine and installs the rest without errors. This is weird.

Hope someone would help me.

Thanks in advance!
Cheers

**Comment by hapontemloreto** [comment]
It looks like scoped packages being installed using the tarball are failing because the url is not being encoded: @scope/package -> @scope%2fpackage.

I was able to repro this on my dev setup where we have our own private couchdb.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\huaponte\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@aria/commands',
1 verbose cli   '-g' ]
2 info using npm@3.5.2
3 info using node@v4.1.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @aria/commands
8 silly fetchNamedPackageData @aria/commands
9 silly mapToRegistry name @aria/commands
10 silly mapToRegistry scope (from package name) @aria
11 silly mapToRegistry registry http://arianpmprivate.cloudapp.net:5984/
12 silly mapToRegistry uri http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands
13 verbose request uri http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:40:00 AM
16 verbose request id a790a5b7e56f4878
17 verbose etag "9FGSLN3X9B5GJSOYL7GGVFAM8"
18 http request GET http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands
19 http 304 http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands
20 verbose headers { server: 'CouchDB/1.6.0 (Erlang OTP/17)',
20 verbose headers   etag: '"9FGSLN3X9B5GJSOYL7GGVFAM8"',
20 verbose headers   date: 'Wed, 23 Dec 2015 18:40:00 GMT',
20 verbose headers   'content-length': '0' }
21 silly get cb [ 304,
21 silly get   { server: 'CouchDB/1.6.0 (Erlang OTP/17)',
21 silly get     etag: '"9FGSLN3X9B5GJSOYL7GGVFAM8"',
21 silly get     date: 'Wed, 23 Dec 2015 18:40:00 GMT',
21 silly get     'content-length': '0' } ]
22 verbose etag http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands from cache
23 verbose get saving @aria/commands to C:\Users\huaponte\AppData\Roaming\npm-cache\arianpmprivate.cloudapp.net_5984\_40aria_252fcommands\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule @aria/commands@0.0.97 checking installable status
37 silly cache add args [ '@aria/commands', null ]
38 verbose cache add spec @aria/commands
39 silly cache add parsed spec Result {
39 silly cache add   raw: '@aria/commands',
39 silly cache add   scope: '@aria',
39 silly cache add   name: '@aria/commands',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: 'latest',
39 silly cache add   type: 'tag' }
40 silly addNamed @aria/commands@latest
41 verbose addNamed "latest" is being treated as a dist-tag for @aria/commands
42 info addNameTag [ '@aria/commands', 'latest' ]
43 silly mapToRegistry name @aria/commands
44 silly mapToRegistry scope (from package name) @aria
45 silly mapToRegistry registry http://arianpmprivate.cloudapp.net:5984/
46 silly mapToRegistry uri http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands
47 verbose addNameTag registry:http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands not in flight; fetching
48 verbose get http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands not expired, no request
49 silly addNameTag next cb for @aria/commands with tag latest
50 silly addNamed @aria/commands@0.0.97
51 verbose addNamed "0.0.97" is a plain semver version for @aria/commands
52 silly mapToRegistry name @aria/commands
53 silly mapToRegistry scope (from package name) @aria
54 silly mapToRegistry registry http://arianpmprivate.cloudapp.net:5984/
55 silly mapToRegistry uri http://arianpmprivate.cloudapp.net:5984/@aria%2fcommands
56 verbose addRemoteTarball http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz not in flight; adding
57 verbose addRemoteTarball [ 'http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz',
57 verbose addRemoteTarball   'bb5d470eb537af3c3fec44c264861a1dd5176cb0' ]
58 info retry fetch attempt 1 at 10:40:00 AM
59 info attempt registry request try #1 at 10:40:00 AM
60 http fetch GET http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
61 http fetch 404 http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
62 error fetch failed http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
63 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
64 info retry fetch attempt 2 at 10:40:10 AM
65 info attempt registry request try #1 at 10:40:10 AM
66 http fetch GET http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
67 http fetch 404 http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
68 error fetch failed http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
69 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
70 info retry fetch attempt 3 at 10:41:10 AM
71 info attempt registry request try #1 at 10:41:10 AM
72 http fetch GET http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
73 http fetch 404 http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
74 error fetch failed http://arianpmprivate.cloudapp.net:5984/@aria/commands/-/@aria/commands-0.0.97.tgz
75 silly rollbackFailedOptional Starting
76 silly rollbackFailedOptional Finishing
77 silly runTopLevelLifecycles Starting
78 silly runTopLevelLifecycles Finishing
79 silly install printInstalled
80 verbose stack Error: fetch failed with status code 404
80 verbose stack     at Request.<anonymous> (C:\Users\huaponte\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
80 verbose stack     at emitOne (events.js:77:13)
80 verbose stack     at Request.emit (events.js:169:7)
80 verbose stack     at Request.onRequestResponse (C:\Users\huaponte\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:998:10)
80 verbose stack     at emitOne (events.js:77:13)
80 verbose stack     at ClientRequest.emit (events.js:169:7)
80 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
80 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
80 verbose stack     at Socket.socketOnData (_http_client.js:305:20)
80 verbose stack     at emitOne (events.js:77:13)
81 verbose cwd C:\Users\huaponte
82 error Windows_NT 10.0.10586
83 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\huaponte\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@aria/commands" "-g"
84 error node v4.1.2
85 error npm  v3.5.2
86 error fetch failed with status code 404
87 error If you need help, you may report this error at:
87 error     <https://github.com/npm/npm/issues>
88 verbose exit [ 1, true ]

**Comment by hapontemloreto** [comment]
Also, if the package is in the cache (i.e. you published it from the same pc), then you won't see any error, because the tarball won't be fetched.
