### ISSUE TITLE
new command: npm clone – install package for deployment purposes

### ISSUE THREAD

**Issue by iarna** [npm/npm#8808]
Suggested by @aredridel:

```
npm clone packageortarballorwhatever directory; cd directory; npm start
```

## `npm clone <specifier> [<targetdir>]`

Extracts package referred to by specifier into targetdir and installs all of its production dependencies.

**Comment by iarna** [comment]
She adds:

> aredridel [9:03 PM] Only frustration I can see is what life cycle scripts to run.
> aredridel [9:03 PM] I wish the command was called deploy, really, but it's also analogous to got clone.
> aredridel [9:04 PM] I know lots of people would want no install run. But maybe if they want that, they should use prepublish for their build actions and bundle dependencies

**Comment by othiym23** [comment]
This is a small part of a much larger conversation that needs to involve npm, Inc. product thinking, by which I mean our instantiated Turing Machine product manager simulation, @seldo. There is definitely a much better story to tell around deployment, and only a small portion of it needs to go into the CLI, and there's not yet a consensus of how much of even this command that needs to be. I'm going to close this issue because I'm absolutely confident that @seldo is going to return us to discussing npm's deployment story at a later date. But hold this thought! And thanks to @iarna for quarterbacking it and @aredridel for the idea.
