### ISSUE TITLE
Install npm@3 fails

### ISSUE THREAD

**Issue by kbariotis** [npm/npm#8819]
Am I doing something wrong? (Obviously I do)

```
> npm install -g npm@3.x
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.1.0 /usr/local/lib/node_modules/npm

> npm -v
2.11.2

> npm install -g npm@3.x-latest
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/Bariotis/.nvm/versions/node/v0.12.5/bin/node" "/Users/Bariotis/.nvm/versions/node/v0.12.5/bin/npm" "install" "-g" "npm@3.x-latest"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: npm@'3.x-latest'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.1.25","1.2.32","1.3.2","1.3.4","1.2.20","1.2.21","1.2.22","1.2.23","1.2.24","1.2.25","1.2.27","1.2.28","1.2.30","1.2.31","1.3.0","1.3.1","1.2.19","1.1.70","1.1.71","1.3.5","1.3.6","1.3.7","1.3.8","1.3.9","1.3.10","1.3.11","1.3.12","1.3.13","1.3.14","1.3.15","1.3.16","1.3.17","1.3.18","1.3.20","1.3.21","1.3.22","1.3.23","1.3.24","1.3.25","1.3.26","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.8","1.4.9","1.4.10","1.4.11","1.4.12","1.4.13","1.4.14","1.4.15","1.4.16","1.2.8000","1.4.17","1.4.18","1.4.19","1.5.0-alpha-0","1.5.0-alpha-1","1.4.20","1.5.0-alpha-2","1.4.21","1.5.0-alpha-3","1.5.0-alpha-4","2.0.0-alpha-5","1.4.22","1.4.23","2.0.0-alpha.6.0","1.4.24","2.0.0-alpha.6","2.0.0-alpha.7","2.0.0-beta.0","1.4.25","2.0.0-beta.1","1.4.26","2.0.0-beta.2","1.4.27","2.0.0-beta.3","1.4.28","2.0.0","2.0.1","2.0.2","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.1.5","2.1.6","2.1.7","2.1.8","2.1.9","2.1.10","2.1.11","2.1.12","2.1.13","2.1.14","2.1.15","2.1.16","2.1.17","2.1.18","2.2.0","2.3.0","2.4.0","2.4.1","2.5.0","2.5.1","2.6.0","2.6.1","2.7.0","2.7.1","2.7.2","2.7.3","2.7.4","2.7.5","2.7.6","2.8.0","2.8.1","2.8.2","2.8.3","2.8.4","2.9.0","2.9.1","2.10.0","2.10.1","2.11.0","2.11.1","2.11.2","2.11.3","2.12.0","3.0.0","2.12.1","2.13.0","3.1.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Bariotis/npm-debug.log

> npm install -g npm@3.1.x-latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.1.0 /usr/local/lib/node_modules/npm

> npm -v
2.11.2
```

**Comment by iarna** [comment]
You would want: 

`npm install -g npm@v3.x-latest`

npm@**v**3.x-latest

**Comment by kbariotis** [comment]
```
> which npm
/Users/Bariotis/.nvm/versions/node/v0.12.5/bin/npm
```

**Comment by impinball** [comment]
@kbariotis 
Also, another potential bug could be in the path order. If your nvm version is before your `$NPM_PREFIX/.bin` in your system path, that will also cause the above behavior. So that's another thing to check.

@iarna 
I highly doubt it is, [when you consider `v0.10` vs `0.10` (one would expect them to be equivalent)](https://github.com/npm/node-semver#versions). In simply comparing against `@3`, one would expect it to only consider the bracketed portion of `v[3].x-next`, `v[3].x-latest`, and `v[3].1.x-latest`. If comparing against `3.1.x-latest`, `3.x-latest` should fit that blank, since the minor version is wildcarded in the second one, despite erroneously given in the first.

**Comment by kbariotis** [comment]
you were right. I changed the order on my $PATH and now it picks the correct version when I am calling npm. Thanks guys.

**Comment by iarna** [comment]
@kbariotis Sooo, somehow you have `nvm` installed but stuffs getting installed to `/usr/local`. Thaaat shouldn't happen. 😁But I'm glad you all got it working. I'm gonna close this ticket now. 😄

@impinball I don't know what you're being skeptical about– `v3.x-next` and `v3.x-latest` being tags is simply a fact. They're official because I declare them so. ¯\_(ツ)_/¯ That `node-semver` throws away everything after the first wildcard it sees when evaluating a range is... non-intuitive at best. If you consider that  bug is really more a matter of semantics. But let's not discuss this here. 😜
