### ISSUE TITLE
run-scripts are too noisy while used in development

### ISSUE THREAD

**Issue by ngryman** [npm/npm#8821]
Hi,

As many other users, I'm starting to use `npm` as a development tool for simple projects. Now that the ecosystem provides enough matured `cli` tools to do most of the things we want, `gulp` or `grunt` can be overkill for small projects.

**tl;dr: `run-scripts` seems to be mostly addressed to package users, not developers. As developers, we would like to be able to use `npm` for development, and run in silent mode.**

As you already know, a `run-script` that exits with a non-zero error code triggers additional logging and a `npm-debug.log`. These are not necessary in a _development flow_ usage, as you:
- expect to understand what's going wrong, because you are the developer, not the user.
- expect tools to fail during development (lint, test, build, ...).
- process failures and report them with the adapted tool.

To counter this, developers can use the `|| true` trick which is **very dangerous**, or manually add `--silent` which is unnecessary verbose.

I totally understand the effort of communicating to the user that some script has failed and that is not related to `npm`. But I don't understand it anymore when it's addressed to the developer itself.
It seems that `run-scripts` usage is evolving in a way that was perhaps not intended by `npm`.

It would be awesome if we had a control on that log level somehow. Multiple solutions could be explored.
## dev-scripts

Would be the brother of `run-script` and invoked like this: `npm dev`. It would run in silent mode. The name can change, but it would be clear that these kind of scripts are used for development purposes only. It's like `devDependencies` but for scripts.
## more shortcuts

`test` for example is available as `npm test` and runs in silent mode (note that `npm run test` runs in verbose mode). Adding more shortcuts targeting most development use cases could do the job: `lint`, `build`, ...
## `package.json`: additional config variable

Like the existing `loglevel` variable but for `run-scripts`.
## `package.json`: deeper script property

Adding the possibility to specify a nested object like this for scripts:

``` json
"scripts": {
  "lint": {
    "command": "eslint lib/*.js",
    "loglevel": "silent"
  }
}
```
## support of an environment variable

Something like `NPM_RUNSCRIPT_LOGLEVEL=silent npm run lint` would be slient. We could setup our dev / ci environment accordingly.

---

We can choose one or several of those propositions, ~~but my personal taste would go in `dev-scripts` as it would be a clean and simple way of giving more control to the developer~~.

Thanks!

---

Refs: #5452, #5809, #3270.

**Comment by sindresorhus** [comment]
:+1: That extra noise is pretty annoying.

**Comment by adametry** [comment]
The ~18 lines of speculation, finger pointing, and instruction aren't very helpful when `npm owner ls [name]` prints my account name.

**Comment by ngryman** [comment]
Bump :speak_no_evil: 

I know you guys are busy, does a PR would help? Do you prefer one solution?

Thanks!

**Comment by othiym23** [comment]
This issue is one of a constellation of feature requests around finding and enacting the least obtrusive user experience for typical package development workflows. Some of the other pieces of this are #9567 and #10491. There's consensus within the CLI team that choosing better defaults for what gets displayed when by the lifecycle process is a project worth doing; ultimately we need to define some use cases and (if possible) do some user testing to ensure that we're actually going to improve things for typical users.

It's not yet clear to me that suppressing lifecycle script output by default is the best place to start, because a number of those lifecycle scripts produce information that they intend to be passed on to developers (like, say, linters and other static analysis tools). Hence the absence of a `patch-welcome` tag, and the presence of `needs-discussion`. We're probably not going to get to this until late in 2016, but if you want to play around with different ways of dealing with this and send it to us as a PR, we'd be happy to provide feedback and review.

**Comment by ngryman** [comment]
I think we should ask people what solution they prefer.
I've created a poll for this: http://bit.ly/1RudPTd.

I've tweeted it here: https://twitter.com/ngryman/status/697912524415447040.
@sindresorhus could you spread the word, it would be awesome :)

**Comment by sindresorhus** [comment]
There's an easy solution to this; just make custom run scripts + `npm test` & `npm start`, not output the noise. You still retain the debugging <del>noise</del> info for hooks used during install, like `postinstall`.

**Comment by ngryman** [comment]
@sindresorhus I totally agree, but I wanted to find a consensus where both could live together.
Perhaps only `install` should be verbose as it's probably the only task that *users* will execute, hence additional info.

**Comment by nathanmarks** [comment]
@ngryman It makes using npm as a build/dev tool really frustrating when you forget to add the `-s` and your terminal window when running tests ends up like:

(the test error detail is hidden above the visible output)

```
      ✖ should set the flex prop correctly


  total:     44
  passing:   41
  failing:   3
  duration:  3.1s



npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1/bin/node" "/usr/local/bin/npm" "run" "test:dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @poweredbysearch/react-flexlayout@0.0.7 test:dev: `npm run -s test | tap-spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @poweredbysearch/react-flexlayout@0.0.7 test:dev script 'npm run -s test | tap-spec'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @poweredbysearch/react-flexlayout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run -s test | tap-spec
npm ERR! You can get their info via:
npm ERR!     npm owner ls @poweredbysearch/react-flexlayout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hal9000/Development/repos/nathanmarks/react-flexlayout/npm-debug.log
```

**Comment by jesstelford** [comment]
Another possible solution:

## `quite` mode

Reduce the volume of output, rather than removing it completely as in `silent` mode.

For example, @nathanmarks example;

```
      ✖ should set the flex prop correctly


  total:     44
  passing:   41
  failing:   3
  duration:  3.1s



npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1/bin/node" "/usr/local/bin/npm" "run" "test:dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @poweredbysearch/react-flexlayout@0.0.7 test:dev: `npm run -s test | tap-spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @poweredbysearch/react-flexlayout@0.0.7 test:dev script 'npm run -s test | tap-spec'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @poweredbysearch/react-flexlayout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run -s test | tap-spec
npm ERR! You can get their info via:
npm ERR!     npm owner ls @poweredbysearch/react-flexlayout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hal9000/Development/repos/nathanmarks/react-flexlayout/npm-debug.log
```

becomes:

```
      ✖ should set the flex prop correctly


  total:     44
  passing:   41
  failing:   3
  duration:  3.1s



npm ERR! Exit status 1
npm ERR! Failed at the @poweredbysearch/react-flexlayout@0.0.7 test:dev script 'npm run -s test | tap-spec'.
```

**Comment by kevinkorngut** [comment]
I just discovered the .npmrc file which will let you do this:

```
loglevel=silent
```

and if they added in support for specifying values based on NODE_ENV then I think that would be a valid route.

**Comment by trygveaa** [comment]
@kevinkorngut: Doing that makes errors from all npm commands suppressed, e.g. errors from `npm install`:

```
trygve@george:~/npm$ echo loglevel=silent > .npmrc
trygve@george:~/npm$ npm install nonexisting
trygve@george:~/npm$ 
```

So that is not really a practical solution. Only errors from the run-scripts should be suppressed.

Since I'm adding a comment, I might as well state my preference. I vote for sindresorhus' suggestion; simply remove the error output and don't create a npm-debug file for the run-script command.

**Comment by styfle** [comment]
I think the original proposal from @ngryman is a great solution: create a `devScripts` for development scripts, the same way we have a `devDependencies` for development dependencies. These scripts are only invoked by the developer.

Therefore, devScripts have:
* no lifecycle hooks
* no debug log
* no ERR output (silent by default)
* optional `--verbose` flag if you need those things for some reason (chaining?)

**Comment by ljharb** [comment]
@styfle wouldn't devScripts still need `prepublish` and `postpublish`?

**Comment by styfle** [comment]
@ljharb I can see where this is a bit of a gray area.

I think the reason why this issue exists is because someone explicitly wrote `npm run build` which has valuable output that NPM ERR hides. The developer knows that the build script failed, and wants to see the output, not npm errors explaining that the script failed.

The reason why NPM ERR exists (correct me if I'm wrong) is to give you valuable information about which script failed and how. The failure could be caused by a lifecycle hook that got called when you ran `npm install`. You would want to know that the `build` script failed and not the `install`.

The proposal for `devDependencies` makes more sense for apps that are not being published as npm modules to a registry and should therefore avoid `prepublish` and `postpublish` because the silent error might not give you enough information.

The main value in `devDependencies` for me is `npm run build` and `npm run test`--scripts where the output is important and there is no chaining.

**Comment by ljharb** [comment]
I use pretest and posttest scripts all the time in developing my modules.

**Comment by ngryman** [comment]
Currently `npm` provides `run-scripts` to "run arbitrary package scripts". Some of these scripts can be invoked using builtin commands (i.e. test, build, ...). Otherwize they are invoked with `npm run <script>`.

These scripts are mostly meant to be executed during or after the release of package in *user space*, hence `npm err` messages. They have been designed for *packages being distributed*, not for *projects being developed*. After all `npm` is a package manager, not a build tool.

But, usage has evolved and needs too. Nowadays `npm-run` is mostly used by developers on their machine or by services (i.e. CI) during development. Because `npm` is the only command line tool that we know any `node` development environment will have, `npm-run` scripts have became a de facto standard to run (automated)tasks.

When you think about it, linting, testing, building, ... is also part of a package lifecycle, but developer/maintainer side, not user side.
During development, errors are meant to exist and even being processed by automated tools, `npm err` does not make sense anymore in that context.

So we need to, at least conceptually, split *development lifecycles* from *release/install lifecycles*, pretty much like *dependencies* and *devDependencies*, or even *public api* and *internal stub*.

That's where `dev-scripts` could exist. They would allow developers to use `npm` as a *frontend*, and even a standard, to call basic development tasks.

**Comment by ngryman** [comment]
To go further, instead of thinking about `dev-scripts` right of the bat, we could identify `development` vs `production` tasks. `npm` could provide additional commands for `development` tasks that would not use `npm err`.

#### Production tasks

- `install`
- `build`
- `start`
- `stop`

#### Development tasks

- `lint` (optional)
- `build` (already exists, could be `transpile` or `compile`)
- `test` (already exists, should be considered as a development task)
- `watch`
- `version` (already exists, should be considered as a development task)
- `publish` (already exists, should be considered as a development task)

**Comment by pushred** [comment]
```sh
alias npm-run='npm run --silent $*'
```

scratched this itch for me =)

**Comment by elliotlarson** [comment]
@pushred Thank you! That ended up solving the problem for me.  I used the alias `npr`:

```bash
alias npr='npm run --silent $*'
```

**Comment by k-funk** [comment]
Using an alias is a terrible solution. If you have an error as simple as a syntax error in your `package.json`, you'll get no feedback. Not to mention if this is solved in the future and now you've got junk in your `.profile` that makes you pull your hair out a year from now. I know it's a javascript-developer's nature to hack their way through problems, but please don't convince anyone to adopt bad practices.

Hopefully the npm team will prioritize this.

Personally, I've never found the 22+ lines of error helpful for debugging. Seems like it could be shortened to 2-3 lines unless `--verbose` is passed.

**Comment by elliotlarson** [comment]
@k-funk Thank you for your feedback.  I can appreciate what you're saying.  However, I disagree that it's a terrible solution.  It's just a workaround that has some drawbacks.  If a perfect solution was available, this discussion thread wouldn't exist.  

I also think people reading this thread are probably savvy enough to understand the down sides, which could lead to possible hair pulling and/or a dirty `.profile`.  I'm dubious that they need protection from adopting bad practices here.  Your language may be a bit overly strong on this point.

I hope the npm team will prioritize this too, but I suspect they have their reasons for dragging their feet.  Until then, I'll probably just use the imperfect alias.

**Comment by pygy** [comment]
The silent mode is not appropriate as is IMO because these headers are genuinely useful:

```
> project-name@x.y.z commandName /project/root
> full command goes here
```

Especially for meta-commands that run several sub-commands. If one of them hangs, in silent mode, you can't know which one did without re-running in noisy mode or making individual commands noisy manually (`scripts: {"foobar": "echo 'foobarizing...' && foobar the-baz the-qux", ...}`).

**Comment by alexose** [comment]
I think this is really the important thing:

> Personally, I've never found the 22+ lines of error helpful for debugging. Seems like it could be shortened to 2-3 lines unless --verbose is passed.

It's a whole lot of text that provides no value to developers, while also pushing all the useful debug information off the screen.

**Comment by adambuczynski** [comment]
> I think this is really the important thing. It's a whole lot of text that provides no value to developers, while also pushing all the useful debug information off the screen.

Don't want to add +1 noise, but yes, this is really the core of the issue in my opinion.

**Comment by nixpulvis** [comment]
From #5452
> For now, we can enforce a 0 exit code by appending || true to all of our commands. This feels clunky...

I'm curious why we would want to enforce 0 exit codes? If a test suite fails I would expect the command to give an erroneous code at the end.

**Comment by ryansobol** [comment]
@nixpulvis Intuitively, this is how I would expect it to work. I'm sure there are more scenarios that need consideration.

If a test suite "failed" and returned a 0 exit code, I would expect to see the test suite to have completed a run, but some of the tests cases to have failed.

If a test suited failed and returned a non-zero exit code, I would expect to see the test suite to have not completed a run due to a bug in the test suite's code or configuration.

**Comment by ljharb** [comment]
@ryansobol that's not how test suites or linux programs conventionally work - a zero exit code means everything worked perfectly - you'd use the specific value of the nonzero exit code to differentiate the kind of failure.

**Comment by pygy** [comment]
https://yarnpkg.com/ handles this nicely

    error Command failed with exit code 1.
    info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by paralin** [comment]
Yay, another place where Yarn is better... :)

**Comment by adambuczynski** [comment]
I don't want to derail this issue thread or turn it into an "omg Yarn" fanfest, but I am genuinely interested in how the npm team plans to respond to Yarn. 

Npm has been around for quite a while now, but seems to have become somewhat bloated and there are a bunch of issues like this one, which plague many developers and have been outstanding for months, if not years. Along comes Yarn, and boom, most if not all of the major concerns and issues now seem to be addressed.

I am usually quite skeptical of new things and prefer to stick with the known and well supported, but after trying it out for myself, Yarn's speed gains and quiet output alone were enough to win me over.

So what are the plans going forward for npm? Quietly ignore it and keep going the same direction? Join forces with Yarn?

Should we wait until this issue and others like this one are fixed or all jump on the Yarn bandwagon?

**Comment by gihrig** [comment]
FWIW, While yarn is great and I've (mostly) switched, as far as this issue is concerned, yarn runs npm 'under the hood' when executing npm-scripts. So until that changes this issue is still relevant.

For now, `-s` works for me 😄 

![image](https://cloud.githubusercontent.com/assets/1481063/21238381/ae6c120c-c2b7-11e6-88e8-274d0b442fd7.png)

**Comment by Jank1310** [comment]
@gihrig With yarn v0.18.1 you can omit the `-s`

**Comment by dmitriid** [comment]
One and a half years later...

Also, two years since this article: https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ (which for many was a starting point to use `npm run`)

Also, npm docs:

> scripts: If you have a special compilation or installation script, then you should put it in the scripts object.

Oh yes, we do.

**Comment by ngryman** [comment]
@dmitriid Now that `yarn` is gaining momentum and addressing those kind of issues, hopefully `npm` will follow 🎉

**Comment by tobia** [comment]
I would like to point out that using an alias in `.bashrc` is the correct solution, unless/until more options are available. In fact I have a very simple alias to address this issue:

    alias npm='npm -s'

An alias is a user's personal configuration item. Its purpose is to set preferred flags *only when using that command interactively in the terminal.* It does not affect scripts in any way. If it does, there is something very wrong with the script or with your setup. Moreover, you can easily ignore the alias whenever you need to, by prefixing the command with a backslash:

    $ \npm run ...

If you use `-s` (or any other flag) more often than not, then setting an alias is the correct way to go about it. Many distributions come with several alias already set, such as `alias ls='ls --color=auto'` or `alias ls='ls -F'`. No script has ever failed because you have an alias that changes the output of `ls`, because *scripts ignore aliases*. There is nothing wrong or dangerous about them.

**Comment by ljharb** [comment]
Scripts may ignore aliases, but tools that run in your own shell context, including aliases you may have copied from others' dot files, do not. Aliasing over other commands definitely can cause problems - it's irrelevant which tool's fault that is.

**Comment by tobia** [comment]
Which tool is at fault is anything but irrelevant. You cannot (and IMHO should not) play nice with other projects' bugs. In this case, if a tool parses the output of `npm`, but for some reason is not immune to the user's shell aliases, then that tool is written badly. Go ask the Bash developers if you don't believe me. Otherwise, what would be the purpose of aliases in the first place? Why would distributions ship with pre-made aliases for common commands such as `ls` and `grep`?

**Comment by paralin** [comment]
Bash aliases shouldn't apply to calls Npm makes internally. Also, I'm pretty sure nobody is screen scraping the npm output...

**Comment by dander401** [comment]
i think the aliasing is off topic of the bug report. The issue presented is that when a script fails, npm prints a whole paragraph after the actual error that says that the other script failed and that it wasn't npm. The problem with the paragraph is that it pushes the message detailing the error out of sight.

**Comment by adamreisnz** [comment]
🎉

**Comment by k-funk** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by ngryman** [comment]
![at-last](https://cloud.githubusercontent.com/assets/892048/25302263/d21b2bce-273a-11e7-9792-b0277b01dd2c.gif)

**Comment by stevenvachon** [comment]
While shorter, I'd still like to not see the lifecycle stuff at all.
