### ISSUE TITLE
Feature Request: Allow a `versionType` in package.json to opt-out of semver enforcement

### ISSUE THREAD

**Issue by getify** [npm/npm#8834]
I have operated under the assumption for quite awhile that semver didn't apply to 0.x version numbers, and as such it was OK to have my own scheme for a project while I'm still in 0.x. I was aware of small differences, like with ~ and ^, that npm applied, but those differences have never seemed to be too big of a deal.

However, now apparently, according to https://github.com/npm/npm/issues/8696#issuecomment-118731257, a **patch-level** change in npm in ef6be38 started enforcing additional semver rules, even on 0.x versions.

As [this comment](https://github.com/npm/npm/issues/8696#issuecomment-118840063) explains, I use my own version scheme on all my packages, of which all are still in 0.x. All of my packages are now suddenly affected, and [some flat out don't install correctly](https://github.com/getify/asynquence/issues/67) at all anymore.

The net effect is that unless npm rolls back this change quickly, I'm going to have to change the version scheme on every one of my packages, which is very hostile.

I don't want to argue about the change itself -- I disagree with it but I suspect no one will care what I think. I'm also not going to argue that npm should have only applied that rule to non 0.x, for similar reasons.

So, instead, I'd like to request that a `versionType` be added to package.json such that a package can opt-out of these semver rules entirely. That way, while I'm in 0.x land, I can have `versionType: "custom"` and not worry about semver changes in npm. Once I am ready to move to 1.x+, I'll begin to conform to semver, and remove the `versionType: "custom"` (or switch it to `versionType: "semver"`).

Is that possible?

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/5201

**Comment by othiym23** [comment]
This strikes to the heart of npm's design philosophy, and because this can be a contentious topic, let me be as clear as possible: npm has placed its bets on semver, and everything it does around dependencies and versioning is going to be done according to the semver spec, as best we understand it. This is a major deviation from that philosophy, and is not something that is every likely to get traction in the npm CLI. Thanks for describing the problem so crisply, and thanks for your time.
