### ISSUE TITLE
Easily install packages locally and/or globally?

### ISSUE THREAD

**Issue by JoshMcCullough** [npm/npm#8866]
Hi, I did a little research and it appears there is no way to indicate in your `package.json` where a package should be installed. Why not allow for a "globalDependcies" section? For example:

    {
      ...,
      "globalDependencies": {
        "bower": "^1.4.1",
        "gulp": "^3.9.0"
      },
      "devDependencies": {
        "rimraf": "^2.4.1",
        "gulp-concat": "^2.6.0",
        "gulp-cssmin": "^0.1.7",
        "gulp-rename": "^1.2.2",
        "gulp-sass": "^2.0.3",
        "gulp-uglify": "^1.2.0"
      }
    }

This would be helpful to get a new developer up and running on a project quickly. They could just run `npm install` and all dependencies would be installed both locally and globally.

**Comment by othiym23** [comment]
I see what you're getting at, but allowing a local package to make changes to the global environment is likely to cause both supportability problems (as it's likely to be very surprising to most users were we to roll it out) and cause a lot of environment churn (what happens when a package has a `globalDependencies` semver conflict with a previous install?). As such, we're not going to add this. _However_, I am growing more open to the idea of creating some way for people to capture the set of packages (with their versions) that are installed globally, and making it easier to replicate that environment across machines. If you wanted to create a new feature request to that effect, it would be worth discussing. Thanks for putting this together!

**Comment by JoshMcCullough** [comment]
Thanks for responding. I think it would be optional, or perhaps `npm install -g` would know to look at the `globalDependencies`. I wouldn't expect it to install unbeknownst to a user. As far as the global version/dependency issue goes, I think that's a problem regardless of how the global dependency is installed, right? E.g. a user will have to `npm install -g gulp bower` regardless, if they want to be able to use gulp/bower at the local level.

I'm new to this space (npm) so it's possible I'm out in left field. :)

**Comment by JoshMcCullough** [comment]
Also, can't this serve as the feature request, or where should that be created?

**Comment by iarna** [comment]
@JoshMcCullough Personally, I would install gulp and bower as dev dependencies and run them via entries in the "scripts" section of the `package.json`.

**Comment by JoshMcCullough** [comment]
@iarna Good idea, will give it a try. Thanks!

**Comment by othiym23** [comment]
@JoshMcCullough I'd prefer a new feature request be created in preference to continuing discussion on an old one because it helps keep the discussion more focused (we've had some issues with bikesheddy issues being a little meandering recently). I hope this makes sense!

**Comment by JoshMcCullough** [comment]
Sorry to get off topic here, but @iarna can you point me to an example to use local gulp/bower via `scripts` in `package.json`? Can't seem to find a good reference.

**Comment by iarna** [comment]
@JoshMcCullough I don't have something like that handy but:
`"scripts": { "bower": "bower" }` and then later `npm run bower -- install jquery`– if you have follow ups perhaps email (rebecca@npmjs.com) would be best at this point, though there is a limit to how much direct support I can do. 😁

**Comment by JoshMcCullough** [comment]
Excellent! That's all I need, thanks.
