### ISSUE TITLE
bundleDependencies and shrinkwrap

### ISSUE THREAD

**Issue by mdh-cc** [npm/npm#8954]
Hi,

I'm currently working with a third-party module in my project which relies on `node-falafel` 0.3.1 (https://github.com/substack/node-falafel/tree/0.3.1). They're using `bundleDependencies` to provide a customized version of `esprima`.

By using `npm shrinkwrap` I encounter an `invalid`-error which tells me that `*` was expected instead of `esprima@1.1.0-dev`.

This error only occurs with `npm@2.13.1` and `npm@3.1.2` but not with `npm@2.10.1`.

**Comment by othiym23** [comment]
Using `bundledDependencies` to include a forked version of a dependency is never going to work with shrinkwrap in a clean or pleasant way (because the shrinkwrap file needs to be able to point at a package tarball containing the correct version of `esprima`).

That said, the behavior you're seeing is a bug. npm has gotten pickier about how it uses package metadata in recent versions because before it allowed a race condition where the wrong `package.json` would get read, and I think shrinkwrap is now exposing an edge case where the wrong metadata is being written to disk (as far as shrinkwrap is concerned).
