### ISSUE TITLE
global bin name conflict resolution

### ISSUE THREAD

**Issue by bucaran** [npm/npm#9040]
Say my module exports:

```json
  "bin": {
    "app": "./bin/index.js"
  },
```

but there is another conflicting module using the same name for its binary `app`. Is there any way to hook into `npm i [-g]` and check whether `app` already exists in the current system and for example, export the `bin/index.js` with a name other than `app`?

**Comment by smikes** [comment]
At present, no, there isn't a way to do this.

Historically this has only been a problem for packages installed globally and for packages installed at the same level in the hierarchy, but with npm@3 auto-flattening, this sort of conflict may become more frequent.

**Comment by bucaran** [comment]
@smikes Thanks. 

#### Related

https://github.com/flyjs/fly/issues/45
https://github.com/flyjs/fly/issues/49

**Comment by othiym23** [comment]
The team just discussed this issue a bit, and we've decided the proper way to resolve this is to:

1. Link every bin with a unique name based on a prefix derived from the name of the package (including its scope!) and the name of the bin, and
2. Also try to create the short name, but don't overwrite anything, instead raising a warning that there was a conflict and printing out the link created by 1 so that users can fix the conflict manually.

It would be nice to resolve this completely automatically, but this is a surprisingly hard problem, and the above gets us 80% of the way to a clean solution that helps most folks, so this is what we're planning on doing.

**Comment by bucaran** [comment]
> but this is a surprisingly hard problem

I agree. I think a warning and leaving it up to the user to resolve the conflict is the best you can do correctly. You could have tried some of the more exotic ideas I gave above, but it's unlikely to be implemented any simpler than what you are saying in `#2` and I don't agree with myself anymore 5 months later.
