### ISSUE TITLE
Programatic usage of npm implies memory usage growing indefinitely on installs ?

### ISSUE THREAD

**Issue by maxleiko** [npm/npm#9042]
Hi,

I am using `npm` programatically a lot, and I just come to realize that, when you do a lot of `npm.commands.install`, the process memory heap used is just growing and growing. Is this "normal" ?  
I mean:
 1. load npm => ~10m of mem taken
 2. do a npm.commands.install of a module => ~25m more taken
 3. do another npm.commands.install of a module => ~25m more taken  
 4. etc...

The system I am building is supposed to run "indefinitely", so will this always grow like that ?

Is there a way to "unload" npm in order to free as much memory as possible once the install is done ?

**Comment by KenanY** [comment]
@maxleiko `npm --version`?

**Comment by maxleiko** [comment]
2.13.1

**Comment by othiym23** [comment]
> Is there a way to "unload" npm in order to free as much memory as possible once the install is done ?

In a way. When we want to do things like this within the npm team, what we do is run npm as a child process. I'm not sure I'd trust npm to ever completely release its resources and reset its configuration between installs in a single process. The process by which npm bootstraps itself is very complicated and pretty much has always been oriented towards performing a single action per invocation, and the state of the process is more or less undefined from that point onwards. This is one of the reasons that the current CLI programmatic API is both unsupported and not guaranteed to be fit for any particular purpose. (The primary reason is that the current API is kind of terrible, and we want / need the freedom to yank it around to do what we need without worrying about how that affects semver.)

My strong recommendation is to rework this so that the process running the installs is rewritten to call npm as a child process. Our [goal](https://github.com/npm/npm/wiki/Roadmap#decomposed-and-decoupled-internal-apis) is to eventually have npm broken down into a set of loosely coupled independent APIs, but it's still a ways off in the future.

**Comment by maxleiko** [comment]
Ok, thanks for info :+1:
