### ISSUE TITLE
Add an option in nodejs to enfore filepath case sensitively check

### ISSUE THREAD

**Issue by yahu577** [npm/npm#9051]
Hi, I'm having the same issue as provided reference below, since I'm developing on Mac and deploying on Linux. I understand we cannot enforce filename to be lower case due to backward compatibility. However, I think it's possible to provide an option to add case sensitivity check during 'require' a module. Possibly by comparing the nodejs module path to system's pwd(or however similar) output?

This would enforce the same behavior no matter the which file system.

Ref:
https://github.com/npm/npm/issues/3914

**Comment by othiym23** [comment]
I think I get what you're asking for, but npm doesn't control Node's module loader, and as such doesn't change how `require` behaves. If you wanted something like this, you'd need to write a little module that monkeypatches the module loader to check what's being required. If you do want to propose that Node be changed to work this way (which is going to have a tough road to acceptance, because the Node core team tries to treat the Node module loader as finished as much as possible), then you probably want to take this request over to [`nodejs/node`](https://github.com/nodejs/node) or [`nodejs/io.js`](https://github.com/nodejs/io.js). Good luck!
