### ISSUE TITLE
Cant install any npm's

### ISSUE THREAD

**Issue by MilesWilliams** [npm/npm#9064]
I've tried to install browser-sync, as well as other npms, however I keep getting this error message
![screen shot 2015-07-25 at 23 38 01](https://cloud.githubusercontent.com/assets/11831567/8891361/945fbb88-3326-11e5-958c-dd84cc503bb9.png)

**Comment by KenanY** [comment]
@MilesWilliams Looks like you don't have permission to read/write to `npm`'s cache directory. Could you try running the following?:

``` bash
$ sudo chown -R $(whoami) "$HOME/.npm"
```

Also be sure to prepend your `npm install -g` commands with `sudo`, since your global modules are being installed to `/usr/local` which you also do not have permissions to read/write to.

**Comment by MilesWilliams** [comment]
@KenanY Thanks Man - worked like a charm :D

**Comment by othiym23** [comment]
Closing as resolved!
