### ISSUE TITLE
Cannot install any project dependencies on elementary os.

### ISSUE THREAD

**Issue by drhartman** [npm/npm#9069]
console when I try to install express

```
npm ERR! Linux 3.2.0-51-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "express"
npm ERR! node v0.6.12
npm ERR! npm  v2.13.1

npm ERR! Object #<Object> has no method '_extend'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mr_rupert/StredmWeb/npm-debug.log
npm ERR! code 1
```

**Comment by KenanY** [comment]
@drhartman So, despite your very new version of `npm`, you have a very old version of Node.js. The v0.6 series ended years ago when v0.10 came out, and consequently it is no longer supported by `npm`. Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node)?

**Comment by othiym23** [comment]
As @KenanY indicated, npm no longer supports the use of Node 0.6. Upgrade to a newer version of Node. Since elementary OS is based on Ubuntu, it might be possible to get it to use the [.debs produced by NodeSource](https://github.com/nodesource/distributions) to get to a newer Node.

An alternative is to reinstall Node and npm using the system's package manager and use the bundled npm, but that won't work if you need to publish, and will require some pretty gross hacks to deal with the changes in how the registry handles SSL authentication. If it's at all possible, upgrade. Closing this as resolved as it's going to get for now.
