### ISSUE TITLE
Wrong version installed for peerDependencies

### ISSUE THREAD

**Issue by IgorAufricht** [npm/npm#9074]
When I create a new `package.json` file like this:

``` javascript
{
  "name": "peerdep-test",
  "version": "1.0.0",
  "devDependencies": {
    "grunt-karma": "~0.8.3",
    "karma-junit-reporter": "~0.2.2",
    "karma-webpack": "~1.5.1"
  }
}
```

And run `npm install`, I get this error:

```
npm ERR! peerinvalid The package karma@0.13.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-junit-reporter@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer grunt-karma@0.8.3 wants karma@~0.12.0
npm ERR! peerinvalid Peer karma-webpack@1.5.1 wants karma@>=0.12 < 1
```

Why is this particular version of karma (0.13.3) installed as a peer dependency, when it obviously does not meet all the requirements (grunt-karma requires ~0.12.0)? If npm chose e.g. karma@0.12.37, all the peer dependency requirements would be satisfied. We can verify this by installing the version directly and then checking with `npm list`:

```
$ npm install karma@0.12.37
(... install succeeds)

$ npm list -depth 0
peerdep-test@1.0.0 c:\dev\labs\peerdepend\test
├── grunt@0.4.5
├── grunt-karma@0.8.3
├── karma@0.12.37
├── karma-junit-reporter@0.2.2
├── karma-webpack@1.5.1
└── webpack@1.10.5
(... no peer dependency issues here)
```

I'm using npm version 2:

```
$ npm --version
2.13.3
```

(This issue does not exist in npm@3, since peer dependencies are not installed by npm@3 by default.)

**Comment by othiym23** [comment]
My guess is that due to the way that the `npm@2` dependency resolution algorithm works, it installs a version of `karma` that matches the semver of the first `peerDependency` declaration that it sees (which, as is implied, is nondeterministically chosen). The situation you're encountering is a bug, but we'll have to discuss whether it's a bug worth our time to fix, because one of the reasons motivating the changes to `peerDepedendencies` in `npm@3` was exactly this kind of conflict.

A way to work around this issue is simply to add `karma@~0.12.37` to your `devDependencies`, which has the added benefit of working with both `npm@2` and `npm@3` (which requires something like that to be there anyway). Thanks for the report!

**Comment by IgorAufricht** [comment]
Thanks for the response. Adding `karma@~0.12.37` to `devDependencies` solves the problem nicely indeed.

**Comment by deepakshrma** [comment]
This happens lot of the time when you have install old dependencies. To resolve this issue what i did. I simple remove old `node_modules`.
If you have idea how requires works, simple remove all parent `node_modules`. For ex.
I want to install `some_module` in "/home/deepak/WebstormProjects/learnyoureact". 
I simply have to remove `node_modules` inside 
`/home/deepak/WebstormProjects/`
`/home/deepak/`
`/home/`
if it is there.
