### ISSUE TITLE
Is npm run [command] [<args>] [-- <argsWithDashes>] intended to be valid?

### ISSUE THREAD

**Issue by alubbe** [npm/npm#9076]
Right now, it is perfectly valid to write
```sh
npm run gulp task1 task2 task3
```

However, according to https://docs.npmjs.com/cli/run-script, this should require `--` between `gulp` and `task1`. My understanding was that `--` is only need if the arguments use dashes, such as 
```sh
npm run gulp task1 task2 task3 -- --enable-the-hyperwarp
```

Since this is not documented, I would like some clarity on if the current behaviour is intended and thus, supported and maintained.

**Comment by othiym23** [comment]
Strictly speaking, the `--` is only required for passing arguments that might be confused with arguments used by npm itself (i.e. arguments looking like `-v` or `--foo=bar`). This observes a Unix convention for how command-line parameters containing dashes (that aren't themselves command-line arguments) are handled. Git is a prominent example of a tool that also uses this convention.

I think it's a good habit to get into using `--` with `npm run-script`, just because it's easy to forget the need to escape dashed arguments for scripts and to have a confusing time.

We have no plans to change how `npm run-script` handles arguments, and would treat any significant changes to argument parsing as a semver-major (breaking) change, so it's safe for you to keep doing what you're doing.

**Comment by alubbe** [comment]
Awesome - would you accept a PR to the documentation adding this?
