### ISSUE TITLE
make the npm v3 spinner square rotate independently of the text messages

### ISSUE THREAD

**Issue by trusktr** [npm/npm#9080]
Instead of being synchronized with changes to the text messages.

**Comment by othiym23** [comment]
The current spinner behavior is valuable, because it gives you a rough idea of what's going on: either there are log messages happening, which cause it to tick, or it's in the midst of a pending network request, in which case it's spinning at a steady speed, or npm's doing something time-consuming that isn't logging or waiting on the network, in which case it does nothing at all. Having it be be animated regardless of what the CLI is doing would be a regression at this point. Thanks for bringing this up, though!

**Comment by trusktr** [comment]
Interesting to know!
