### ISSUE TITLE
support "license": "<SPDX license> OR SEE LICENSE IN <file>"

### ISSUE THREAD

**Issue by sam-github** [npm/npm#9093]
We just updated a number of our license specs from the previously valid values to the new SPDX forms.

And now our licenses have become invalid, again, between npm 2.11 and 2.13.

PR https://github.com/npm/npm/pull/8609 lists some of our packages as affected, but we weren't told, unfortunately.

It also seems to me that this was a breaking change, better reserved for 3.x.

But more importantly, what happened to the **_OR**_ syntax?

I've tried converting https://github.com/strongloop/strongloop/blob/master/package.json#L70 to

> "Artistic-2.0 OR SEE LICENSE IN LICENSE.md"

and

> "Artistic-2.0 OR (SEE LICENSE IN LICENSE.md)"

and

> "(Artistic-2.0 OR (SEE LICENSE IN LICENSE.md))"

all without success.

I'm hoping that support for **_OR**_ did not get deleted intentionally, and I'm just not quite getting it right, or it was an unforeseen side-effect of supporting the new syntax that can be fixed.

/to @othiym23 @kemitchell @rmg

**Comment by kemitchell** [comment]
@sam-github, thanks for your note. Sorry for the trouble. We'll get this sorted.

I'll try to answer your immediate question, then give some sense of context and how the changes that lead to your warnings came about.

SPDX expressions like `(MIT OR Apache-2.0)` remain valid. The difference is the handling of licenses that haven't been assigned an identifier by SPDX, such as your license at https://strongloop.com/license/.

The original approach to nonstandard (as in non-SPDX-standardized) licenses was the `LicenseRef-X` syntax that you picked up on circa `npm@2.10`.

That syntax was a hack. SPDX is a standard for metadata files that describe assessments about the licensing terms of third-party software. One part of that standard is the license list, which assigns specific string identifiers to common licenses. Another is the expression syntax, which overlays `OR`, `AND`, and &c and their semantics. npm cherry picks these parts of the standard.

Both license identifiers and license expressions were designed to be used within SPDX metadata files. `LicenseRef-X` was built into the expression syntax to permit reference to information about nonstandard licenses that were nonetheless described within SPDX metadata files. Essentially, such identifiers are pointers to separate description XML within an SPDX metadata file.

That kind of structured reference doesn't really make sense in the npm package context, but neither did @othiym23 want to leave proprietary or custom-licensed packages with an inescapable warning. For that reason, in my original 2.10 PR, we permitted `LicenseRef-` identifiers within `"license"` properties, even though they really don't make sense there, and christened one particular such identifier, `LicenseRef-LICENSE`, to mean "look at the LICENSE file packaged with the code".

A later PR addressed the general hackishness of that approach by prohibiting `LicenseRef` in `"license"` and christening completely different magic magic values for nonstandard license situations. `SEE LICENSE in X` was one. These are much easier to use and understand in the typical nonstandard license case, which is exclusive licensing under a nonstandard license.

Those new magic values were implemented in the npm-specific validation routines, rather than in https://npmjs.com/packages/spdx, which remains true to the SPDX spec. As a result, composition of the npm-specific magic values and valid SPDX license identifiers, like your `(Artistic-2.0 OR SEE LICENSE IN LICENSE.md)`, was invalidated as neither absolutely equivalent to the magic value alone nor a valid SPDX license expression.

There are a few ways you could go to clear the warnings from current npm:

1. You can avoid warnings by just using `Artistic-2.0`. You could still mention the ability to license on different terms in README or elsewhere interested users might see it.

2. You can avoid warnings by just using `SEE LICENSE in LICENSE.md` and mentioning your dual licensing offer (and `Artistic-2.0`) in `README.md`.

I am definitely not StrongLoop's lawyer. But just as a dev and a contributor to npm, I'd like to point out some pros and cons for each, respectively:

1. Folks using automated license compliance tools would be able to confirm they are clear insofar as they permit `Artistic-2.0` by policy. However, use of npm by itself wouldn't alert them to the opportunity to license under different terms. This is what happens when you install most other dual-licensed projects, like MySQL, from public open-source repositories, like the Debian repos.

2. Automated license tools would probably not whitelist your packages automatically, but instead require investigation. This is rather more like the experience of downloading MySQL from MySQL.com.

Baking in support for npm's magic values within SPDX license expressions would mean diverging from SPDX expressions as described in the spec. I can't say I'd be enthused about that approach.

I wouldn't be happy about allowing `LicenseRef-X` (or just `LicenseRef-LICENSE`, but no other `LicenseRef-X`) in `"license"` once more, but I'll write that PR if @othiym23 wants it. A side effect is that it would also allow `(MIT OR LicenseRef-MeaninglessGarbage)` and the like.

Sorry for the length!

**Comment by othiym23** [comment]
Wow! Thanks for the very thorough explanation, @kemitchell!

I have a few random responses here, although I'm mostly interested in hearing what @sam-github has to say.

* I think Sam's expectation that `Artistic-2.0 OR SEE LICENSE IN LICENSE.md` should validate is a reasonable one, or at least the fact that it's not validating is surprising.
* I don't want to muck up the SPDX validation code with stuff that's not pertinent to SPDX in general. An idea that suggests itself is to partially duplicate the expression parsing in npm to look for `SEE LICENSE IN` and replace it with a placeholder of some kind before passing the expression on to the validator, but I freely admit there's probably something terrible about that idea.
* In addition to not being StrongLoop's lawyer, I'm not a lawyer at all. Based on what I do know about StrongLoop, though, I think my instinct would be to follow the second approach outlined by Kyle, and just point people at the specific terms in your license. When I've had to worry about compliance checking before, I've ended up having to whitelist anything involving a proprietary license anyway, so you might as well point people straight at that. Is that an acceptable workaround for you, Sam?
* I don't think going back to `LicenseRef-X` is a good idea. The current syntax feels good to me, and having the custom license checking decoupled from the SPDX validation feels cleaner than having a special value in the validator with no meaning within the SPDX universe. It's less hacky this way.

Having to parse the expression twice, potentially, is also kind of hacky, but I like the way it separates the concerns between the CLI and the SPDX module. How does that grab the two of you?

**Comment by kemitchell** [comment]
I, too, am interested in @sam-github's thoughts. I apparently had a lot to say on this, but am very, very open to learning form StrongLoop's point of view. I don't think anyone's interesting in passing off our own innovations as SPDX, but we have leeway to do right by our community.

@othiym23, if it's all the same to you, I might hold off weighing in on some of your follow-up points until we've heard from Sam & co.

**Comment by othiym23** [comment]
@kemitchell That sounds great to me. :bow:

**Comment by sam-github** [comment]
Well, here's some thoughts.

I'm not our lawyer, either, and I'd like to not have to invoke them again, they were happy last time, but I may have to. /cc @ijroth

Option 1, specifying the "most free license" in SPDX seems better than option 2, for the purpose of some hypothetical tool that automated license evaluation (or does such a tool exist?), but I don't think either should be necessary.

I'm not sure what changing the package.json format to use SPDX instead of json brings to the table in this regard, since package.json was already a structured file that allowed tools to parse out all the licenses and that supported OR clauses, it seems to me it should have been possible to map the old json format TO SPDX and not require any changes, or perhaps minimal ones (like a warning that a license label was unknown).

Automated analysis aside, one use of the license field is clearly displaying them on npmjs.org. That has value, and right now strong-pm looks like https://www.npmjs.com/package/strong-pm (for future readers, its a long string "Artistic-2.0 OR LicenseRef-LICENSE.md" that is hyperlinked to an OSI page saying "no idea what license that is"). From an npmjs.org point of view, in terms of a quality directory and distribution point of packages, I'd like to at a glance see that strong-pm is artistic-2.0 (and to click on that part of the license link to see the artistic text) as well as to see that there is another license available (and to be able to click on that link and see the LICENSE.md file). From the SPDX FAQ and about page, that seems the goal of spdx.org, too.

There is some reference above to the license file being required to have a specific name, either LICENSE or LICENSE.md. Maybe that makes sense, it worked fine for us, that's somewhat traditional naming, but it seems a bit restrictive as a general mechanism.

> The current syntax feels good to me, and having the custom license checking decoupled from the SPDX validation feels cleaner than having a special value in the validator with no meaning within the SPDX universe. It's less hacky this way.

The entire `LicenseRef-<filename>` thing definitely felt like a hack, but it seems a hack triggered by a deficiency in the validator, SPDX is intended to allow custom licenses:

```
How does one handle non open source licenses or licenses not found in the SPDX approved license list?
 When a license identified in the software package is not found in the list of approved SPDX licenses, one can add the license text to the SPDX file and define a new license label. That license label is defined only for that specific SPDX file.
```
- http://spdx.org/about-spdx/faqs

@kemitchell, why doesn't the validator library support this?

Based on the above, it seems the package syntax should be more like:

```
// pre-known license labels
license: "artistic-2.0 OR MIT",

// locally defined labels
license: {
   expression: "artistic-2.0 OR Fu-Bar-39",
   labels: {
      "Fu-Bar-39": {
           text: "..." // if its short, json is notoriously bad for multi-line text
           file: LICENSE.md // if its in-package
    },
  }
```

The SPDX FAQ suggests that SPDX files can contain lots of interesting information, like a history of who has reviewed the license, etc, all of which is perhaps a candidate for putting in the package.json. Or not, its hard to tell, to understand the spec syntax and suggest how to incorporate it into package.json I'd have to understand RDF, which I don't. :-)

**Comment by sam-github** [comment]
And btw, thanks both of you for your considered responses.

**Comment by kemitchell** [comment]
@sam-github, thanks for this.

> Option 1, specifying the "most free license" in SPDX seems better than option 2, for the purpose of some hypothetical tool that automated license evaluation (or does such a tool exist?), but I don't think either should be necessary.

There are a variety of tools both in use and in development. [npm Enterprise](https://www.npmjs.com/enterprise), for example, supports filtering on license metadata. For an other-than-compliance example, [Node|Source's npm visualization](https://unpm.nodesource.com/) makes use of license properties to give folks a sense of norms in the public registry.

The expected benefit of introducing the subset of the SPDX spec into package.json was to encourage regularity and avoid the need for complex methods like NLP to do automated license audit. Prior to the warning, folks were typing all manner of strings for even very common licenses, and ambiguous choices ("BSD", "GPL") were very common. (And they still are.) Given how deep dependency graphs are thanks to npm and Node, automation really pays.

I stumbled on the fact that license data in npm was noisy running [surveys on the public registry](https://gist.github.com/kemitchell/ad3bdc6ca8888599502e). My next step was automating PRs to correct metadata I could [automatically correct with confidence](https://www.npmjs.com/package/spdx-correct), since the package.json docs already asked for SPDX license identifiers. The next logical step was to introduce validation into npm itself, so folks could be warned in the moment.

> Automated analysis aside, one use of the license field is clearly displaying them on npmjs.org.

Absolutely!

I sent a pull request to correct display on npmjs.com shortly after the 2.10 release: npm/newww#996

Unfortunately, newww isn't yet to the point where non-npm folks can run the full test infrastructure. My flying blind attempt at a solution passed the test suite but didn't work when deployed, and neither did my next-best guess. The PR has languished a bit, and should be updated for the new magic values.

> @kemitchell, why doesn't the validator library support this?

Good question. The `spdx` module might have been better names `spdx-expression`. (I may yet go that way, as I split out functionality into separate modules.) Its scope is parsing SPDX license expressions, not implementing the whole of the SPDX spec.

The awkwardness of `LicenseRef`s in the npm world stems from the fact that it's the link between the parts of SPDX as a whole npm did cherry-pick---license identifiers and license expressions---and the parts it didn't, which mostly address the SPDX file format.

Alas, I think there are two reasons not to try and bring all of SPDX into npm:

1. It's massive, especially by npm standards. XML-to-JSON translations of even very basic SPDX metadata files would more than double the size of many package.json files.

2. It's fundamentally envisioned as a way for consumers of open-source packages to code (and share codings of) what they found in the wild. npm thus _repurposes_ license IDs and expressions for expressing authors' intentions in addition to _reusing_ them outside the context of standard SPDX metadata files.

There are some very promising corporate users of SPDX "proper", especially in the embedded and systems spaces. But overall, I think these two factors account for its relatively weak adoption in other niches.

@sam-github, many thanks again for your comments. Great stuff.

**Comment by kemitchell** [comment]
@othiym23, would you consider adding a string property to package.json for URLs describing additional licensing or add-on service offerings? Maybe, within package.json:

```json
"license": "Artistic-2.0",
"commercial": "https://strongloop.com/node-js/subscription-plans/"
```

Essentially meaining: "We share on the terms of `license`, but offer more and different kinds of relationships described at `commercial`".

This strikes me as a middle ground between enforcing (Debian), rather than merely doing everything possible to facilitate (npm), open-source software sharing, while giving businessfolk a recognized and machine-consumable way to note the additional value they offer.

**Comment by kemitchell** [comment]
@othiym23, on some of your earlier points:

> I think Sam's expectation that Artistic-2.0 OR SEE LICENSE IN LICENSE.md should validate is a reasonable one, or at least the fact that it's not validating is surprising.

Agreed.

> An idea that suggests itself is to partially duplicate the expression parsing in npm to look for SEE LICENSE IN and replace it with a placeholder of some kind before passing the expression on to the validator, but I freely admit there's probably something terrible about that idea.

It's a nice hack!

But there's that word again.

**Comment by sam-github** [comment]
I think you got a bit side-tracked by "entire SPDX".

I think the necessary parts of SPDX that is currently missing is allowing packages to define their own license labels. Supporting this, as SPDX does, avoids any "extra npm specific syntax" at all, both the `SEE LICENSE AT` hack, and the `LicenseRef-` hack, and any other kinds of hack.

Your expression parser already parses labels, the only thing it apparently lacks is user-provided labels, it only has some predefined set. Is it so difficult to add labels? Defining them in the package.json is trivial, I showed sample syntax above, only one example of lots of possible variations.

```
"license": "Artistic-2.0",
"commercial": "https://strongloop.com/node-js/subscription-plans/"
```

I can't say I like it, it has a number of problems:
- its non-SPDX, despite that SPDX is designed to allow custom licenses
- it allows only one non-OSI license
- it assumes the non-OSI license is "commercial", not necessarily true

**Comment by kemitchell** [comment]
@sam-github thanks again for your comments. We're ranging a bit broader than StrongLoop's immediate needs, but input is welcome all across the board.

I can't speak for @othiym23 or others, but I think there's a desire to end up with something much simpler than SPDX. The break-even point for npm seems to be license expressions, which is a step further than arrays of license identifiers, the RubyGems approach. Expressions allow users to address common multilicensing situations and conjunctions, say for packages that provide bindings to libraries in C or C++. But it's more complex.

We could support expressing even more situations, including StrongLoop's, by allowing `LicenseRef`s and a way to give them meaning, as you describe. (IIRC, SPDX spec does not allow user-defined license identifiers without a `LicenseRef` prefix.) The alternative is to offer the two choices I mentioned earlier: list just the standard open-source licenses in an expression or use the `SEE LICENSE` catch-all.

That alternative seems alright to me for a few reasons:

1. Most importantly, the user perspective that @othiym23 offered rings very true: In the context of an audit, the norm will be to examine dual-licensed projects by hand, whether or not the team's otherwise using automated analysis tools.

2. Distribution under open-source license without a warning is the norm elsewhere, as with MySQL in Debian repos. But authors would retain the ability to call attention to the choice of license terms by using the special "see the license file" strings.

3. Among the nearly 200,000 packages in the public registry, relatively few are dual licensed. Any new package.json semantics for user-defined identifiers would apply to a very small number of packages.

**Comment by sam-github** [comment]
We won't have any choice but to work around whatever npm does, npmjs.org is the only reasonable way to distribute node packages, and as the ecosystem builds around npm/node, I expect more companies to be distributing their node/npm/front-end JS tools through npmjs.org, not less, so I don't think this is a "StrongLoop issue". I guess we'll see with time whether others start to notice this.

1. The switch to SPDX is a loss of expressiveness in package.json license specs for no gain that I can see. The previous json format appears easily convertible to an SPDX expression with an `OR` of license labels for tools that require SPDX input.

2. Warning if a license label was used that wasn't defined explicitly, or known in the OSI database would have been a reasonable improvement to the previous json format, and made conversion to SPDX even more predictable.

3. The current implementation in npm while using SPDX expressions does not appear to me to adequately address a number of SPDX use cases, namely any license not on the OSI list. I doubt SPDX would have gotten off the ground if it lacked extensibility, but the variant npm uses lacks this feature. Note that this includes "commercial" licenses (as if the OSI "GPL2" and "Sleepcat License" are not commercial...?), as well as any open source license not in the OSI list, such as "Public Domain" or "WTFPL".

**Comment by rmg** [comment]
Out of curiosity, how does npm, Inc. distribute npme? Or is it all single-license?

**Comment by othiym23** [comment]
@rmg the bits that are open source are ISC, the bits that aren't are a proprietary license. We don't really do dual licensing, although the core CLI is dual ISC / Artistic, which I should probably confirm with @isaacs and then update in npm's own `package.json`.

@sam-github I'll have a more complete response later, but as someone who's had to deal with license compliance and verification within an enterprise software company before, the value of switching to a regular, codified syntax that allows for multi-licensing was _immediately_ apparent to me. Having to write a whole piece of software to verify that the licenses of your dependencies are a. OK and b. haven't changed since the last time you checked is a huge waste of everybody's time, so simplifying that as much as possible is a medium to large win for the whole enterprise software community. @kemitchell can speak to his own reasons for driving this work, but he's after something at least as significant himself. We're still iterating, so it's been a bit of a bumpy ride (for which I apologize – it always sucks to in effect be penalized for doing the right thing in a timely way), but I absolutely think it's a real problem that's worth solving.

**Comment by kemitchell** [comment]
@sam-github, again, thanks for your comments.

A few small points:

> I don't think this is a "StrongLoop issue".

Sorry! Didn't mean to imply that we're rolling something bespoke for StrongLoop here. Rather, we ended up talking about SPDX and npm's validation in a much broader way, and I wanted to make sure to keep my eye on finding a way to address the particular open/commercial dual licensing use case that prompted you to open the PR.

> The switch to SPDX is a loss of expressiveness in package.json license specs for no gain that I can see. The previous json format appears easily convertible to an SPDX expression with an OR of license labels for tools that require SPDX input.

SPDX expressions have an `AND` operator with different semantics than `OR`. That's very useful for projects that, say, apply a Creative Commons license to packaged content and MIT to code. It also works for packages that, say, bind LGPL libraries to Node, with binding code licensed `ISC`. There is also `WITH` for license exceptions, though the need for that doesn't seem to great as yet. 

> Warning if a license label was used that wasn't defined explicitly, or known in the OSI database would have been a reasonable improvement to the previous json format, and made conversion to SPDX even more predictable.

I supported this approach in a recent PR to RubyGems. It's a viable approach, less ambitious than the one npm took. I won't opine here on why the two packagers ended up taking different tacks. That was partly a decision before my time, as well. I'm not exactly sure when npm moved from Ruby-style license arrays to a single license string in its metadata guidelines.

> I doubt SPDX would have gotten off the ground if it lacked extensibility, but the variant npm uses lacks this feature.

Not to diminish the corporate users who are working very hard to utilize SPDX as written, but I think those involved have been disappointed in SPDX adoption overall. The npm use case---expressing authors' choice of licensing terms, rather than others' assessments---is also a bit off the intended course for the project, though members of the working groups have welcomed it.

> Note that this includes "commercial" licenses (as if the OSI "GPL2" and "Sleepcat License" are not commercial...?), as well as any open source license not in the OSI list, such as "Public Domain" or "WTFPL".

Good news! SPDX does not use the OSI list, but its own far more inclusive one: http://spdx.org/licenses/

**Comment by sam-github** [comment]
@othiym23 

> the value of switching to a regular, codified syntax that allows for multi-licensing was immediately apparent to me

I *totally* agree... but the json syntax supported that. The new SPDX syntax offers only one benefit over the prexisting json syntax: `AND` support (and maybe `WITH`?). But in the process, it also breaks `OR` for some licenses.

If doing `Artistic OR some-other` is being lost as "of marginal benefit", I don't see how being able to do "Artistic AND (GNU OR Affrero) WITH ...", or some similarly complex construction, is such a gain.

@kemitchell spdx-license-ids isn't even under an OSI approved license! You added your non-OSI license, `Unlicense`, a version of Public Domain which looks like it will never be OSI: http://opensource.org/faq#public-domain.

Mostly, I don't see this as an unreconcilable problem, since we just need to add package-defined license labels, allowing everything that is currently possible with the new SPDX to continue to work, and everything that used to be possible with the old json format to continue to work. Win/Win.

npm can even do it with the `spdx` public API, it looks to me, it would just have to push the package-specific license label onto https://github.com/kemitchell/spdx.js/blob/master/source/spdx.js#L151, this seems a long conversation over a trivial change. Well, non-trivial in that it requires update to the package format, which does deserve some careful consideration/bike shedding, but not requiring any huge technical hurdles.

**Comment by kemitchell** [comment]
@sam-github, the syntax prior to 2.10 was a single license string SPDX identifier. There was no blessed syntax for any kind of compound licensing situation. The `licenses` array in many packages is a holdover from Ruby via CommonJS, and its semantics were not well defined. I'm not sure when npm's package guidelines diverged, but that change in guidelines didn't have a corresponding validation change AFAIK.

The majority of use cases where complex expressions make sense involve licenses with assigned SPDX identifiers only. Some very well-known projects are something like `MIT OR GPL-2.0`, especially for license compatibility. Bindings that would otherwise just be marked `MIT` can now be marked `MIT AND LGPL-3.0`. That is very important information for, say, automated audits that whitelist academic licenses and blacklist copyleft licenses. This isn't to diminish dual-licensed projects with a commercial option. They punch well above their weight in terms of importance per package!

`spdx-license-ids` is @shinnn's package. Unlicense was his choice, and while "public domain" and related issues are both legally and politically fraught, this case didn't strike me as problematic. The list itself is SPDX' work, under a CC license. The package pulls it down with a script and packages for npm consumption. `Unlicense AND CC-BY-3.0` might be more accurate. Its debatable whether the list itself is even subject to copyright.

I'm reluctant to add "bare" custom license identifiers like `SuperSoftCoLicense` with definitions in package.json, because code designed to parse on-spec license expressions, in JS and other languages, will reject such definitions if they're not `LicenseRef-` prefixed. There is also the potential for collision with currently assigned and future-assigned official identifiers. (SPDX actively adds new licenses to its list.) `LicenseRef` is essentially an escape code to jump between the namespace SPDX itself defines and what users may define.

So the option is to allow `LicenseRef` in npm `license` once more, with or without additional syntax for giving meaning to those `LicenseRefs`, with or without validation that `LicenseRef`s used in `license` are defined elsewhere in `package.json`. The alternative is a more approachable magic value, like `SEE LICENSE in X`. 

Thanks again for helping us think through this.

**Comment by sam-github** [comment]
> @sam-github, the syntax prior to 2.10 was a single license string SPDX identifier. There was no blessed syntax for any kind of compound licensing situation. The licenses array in many packages is a holdover from Ruby via CommonJS, and its semantics were not well defined.

We've been using a `licenses` array for 2+ years, it was documented package.json syntax when we started, is as well defined as the current license property is, and I've no idea what Ruby has to do with any of this.

The docs were deleted in https://github.com/npm/npm/commit/0c8952fb1948e998e9896acb597b18908d200577, I've no idea why.

**Comment by othiym23** [comment]
I retitled this issue to reflect that this issue is still open as a reminder that there's a hole in npm's validation support, which is that it should be possible to declare a dependency on either a valid SPDX license expression or direct users to a file. It requires some monkeying around with `normalize-package-data` or `read-package-json`, because it doesn't make sense to put this change in the SPDX expression validator itself, as it's an npm CLI-specific extension. It's not very high priority, but it would be an excellent thing to come in as a patch.

**Comment by kemitchell** [comment]
@othiym23, I might clarify a just a little bit, since there's a lot for folks to read up there:

There is currently a gap in the license terms that valid package.json `license` values can express: They can't indicate that licensees can "choose", in a dual-licensing sense, between licenses specified with SPDX and additional license terms spelled out in a text file.

Does that ring true?

You'd mentioned `stat`'ing referenced license files in validation at some point. Does that belong here?

**Comment by othiym23** [comment]
> There is currently a gap in the license terms that valid package.json license values can express: They can't indicate that licensees can "choose", in a dual-licensing sense, between licenses specified with SPDX and additional license terms spelled out in a text file.
> 
> Does that ring true?

Yes. For developers following multi-licensing schemes, where one or more licenses are licenses with SPDX identifiers, and one (or more?) aren't, it would be nice to be able to surface those SPDX licenses on e.g. npm's web site and through other automated discovery mechanisms, and not forcing them to read the `LICENSE` just to find that out.

> You'd mentioned stat'ing referenced license files in validation at some point. Does that belong here?

It would be a nice thing to have as well, but I'm not sure the two need to land at the same time.

**Comment by othiym23** [comment]
We are still totally going to do this, but it requires a little more empty time than we've recently to turn it into a project, hence the lack of activity. It's in scope for the team for the next year, but if you feel like hacking on this, we'll be delighted to review and land it. Thanks to all for their participation!
