### ISSUE TITLE
npm ls doesn't show unmet dev dependencies

### ISSUE THREAD

**Issue by pauldijou** [npm/npm#9097]
When you have a dependency inside `package.json` which isn't locally installed, `npm ls` will show it as `UNMET` dependency. But if you have the same situation for devDependencies, `npm ls` will show nothing. Wouldn't it be better to be consistent and have the same output?

[Demo](https://asciinema.org/a/24113)

**Comment by othiym23** [comment]
Yes, a warning would be helpful, and I think the main reason it doesn't work that way today is that the rules are different for `devDependencies`. npm should always care about regular `dependencies`, regardless of how deep down the tree a missing dependency is. For `devDependencies`, by contrast, it only matters whether they're missing at the top level of the package you presently happen to be in, and even then it probably shouldn't be a warning if _no_ `devDependencies` are installed (because of `npm prune --production`).

So, npm ought to warn if some `devDependencies` are installed, but not all of them, or if there are semver issues with `devDependencies`. This is trickier than it looks at first! But if you want to take a stab at implementing this, it would be much appreciated. Otherwise, it may take a little while for this to make it to the head of the team's priority queue, because we have a lot on our plate. Thanks for pointing out this issue, either way!

**Comment by othiym23** [comment]
This would be nice to have, but it's not in scope for the team within the next 6-12 months, and so we're going to close it. Because it has `patch-welcome` on it, this is something that the team would love to have submitted as a patch from the community, but we don't have time to get to it ourselves. Thanks for your time, and your patience!
