### ISSUE TITLE
`git://github.com/*` is misinterpreted as `git@github.com:*`

### ISSUE THREAD

**Issue by chbrown** [npm/npm#9103]
I had a public Node.js npm-friendly [package](https://github.com/chbrown/signs-server) on GitHub that I didn't think was worth publishing to the npmjs registry, but wanted to install it from the GitHub repo using npm. The repository field in its `package.json` was set to `"git://github.com/chbrown/signs-server.git"`. However, running `npm install chbrown/signs-server` triggered a `git clone` call using the url `git@github.com:chbrown/signs-server.git`, which failed because I don't have a GitHub-registered public key on that machine (and I don't want one on it). Changing my package's repository field to `{"type": "git", "url": "https://github.com/chbrown/signs-server"}` is a work-around that has temporarily resolved the issue.

`git` [clearly differentiates](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols) between the different protocols. npm should too. If I say I want to use the "git" protocol, npm shouldn't assume that I want to use the "ssh" protocol.

**Comment by gagern** [comment]
As far as I understand things at the moment, npm would use exactly the protocol you chose for unknown servers. For big hosting services, however, it relies on [hosted-git-info](https://github.com/npm/hosted-git-info) to provide git, https and ssh urls for the same repository, and will try them in this order. Prior to 394c2f5a1227232c0baf42fbba1402aafe0d6ffb the order was git then ssh then https. Now it's git then https then ssh. #9470 thinks it should be https first. Perhaps it should be configurable. If it is configurable, then it probably should be configurable by the user installing the package, not by the package author. For this reason, detecting the fact that various github urls in fact refer to the same package, and that this package can be installed using various protocols in an order configured by the user, would make a lot of sense to me. I'd not want to be bound to ssh access just because the author of some package happened to prefer ssh.

**Comment by iarna** [comment]
When you say:
```
npm install chbrown/signs-server
```
It requests that npm install a module from github using _some_ protocol– right now it tries them in the order `git`, `ssh` and `https`. We _may_ change that order, but if any of them fails it should try the next. It should only fail out entirely if they all fail. So even if you don't have the a key needed for ssh, it should continue to `https`.

If you explicitly try to install from a repo, eg:

```
npm install git://github.com/chbrown/signs-server.git
```

It will only install via the `git` protocol.

Now, your `package.json` repository field is not used for ANY of these, because we don't have any way of reading it before we install your package. The repository is only used for `npm repo` and some related commands where it can intuit the right url from your repository url (`npm bugs` & `npm docs`). The registry website also makes use of it.

I'm going to close this, but if I misunderstood what you were asking for, please feel free to open a new issue.

**Comment by chbrown** [comment]
You know, I hadn't really thought the `package.json` "repository" field thing through. Of course the `npm` CLI doesn't know what that field's value is unless it's published in the npmjs registry, or until it installs the package, and at that point it's already installed.

Makes sense now; the misunderstanding was all mine!
