### ISSUE TITLE
err enospc although we clear a lot of space

### ISSUE THREAD

**Issue by liran89b** [npm/npm#9104]
```
npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install" "edison-io"
npm ERR! cwd /node_modules
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
```

**Comment by othiym23** [comment]
What does running `df -h` return on your system? It's possible that the place where your npm cache is is full, and also that `$TMPDIR` is full (maybe because the system's RAM is full? Temporary filesystems can be mysterious). Also, can you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) to a newer version of npm and / or node? `npm@1.4.9` is at least a year old at this point, and many many bugs have been fixed since then.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by liran89b** [comment]
Hi sorry for not replying earlier.  I didn't notice the email.  We are OK
now and the problem was solved thanks for your help
בתאריך 13 באוג׳ 2015 03:04,‏ "Ernie Salazar" <notifications@github.com> כתב:
