### ISSUE TITLE
`npm pack` bundles dependencies of bundledDependencies

### ISSUE THREAD

**Issue by seishun** [npm/npm#9131]
Consider a module A. It depends on a module B and has B listed in its `bundledDependencies`. The module B depends on a module C (not bundled).

When running `npm pack` in module A's directory, it creates an archive that contains C. (I assume `npm publish` would do the same. I have no idea how to test it without leaving a mess in npmjs)

npm shouldn't bundle non-bundled dependencies of bundled dependencies. If I wanted to bundle C as well, I would list it in `bundledDependencies` of module B. (I'm bundling B, so I can modify its package.json if I need to) There is currently no way to not bundle C except by manually deleting B's node_modules before packing/publishing.

**Comment by othiym23** [comment]
This is how bundling works; if a package is marked as a `bundledDependency`, that tells npm to copy everything logically under that package in the dependency tree into the tarball at `npm pack` time. Without doing this, the bundled dependency wouldn't be ready to use at unpack time, this defeating the purpose of having bundled dependencies in the first place. Bundling needs to work for bootstrapping purposes, and forcing an explicit enumeration of every dependency to be bundled down the tree would be ambiguous (multiple bundled dependencies might depend transitively on conflicting versions of the same dependency) and tedious (many packages using bundling, like npm itself, have hundreds of dependencies rolled up to a much smaller number of bundled dependencies).

The maintainer of package A may have no control of bundled package B, and therefore wouldn't be able to specify that package B's dependencies should be bundled. See above why forcing the maintainer of package A to explicitly enumerate all bundled dependencies is unreasonable.

This is also why `npm@3` figures out what to bundle from the logical (not filesystem) tree – to keep this behavior consistent and usable across all versions of npm that support bundling.

There would need to be a really compelling motivation to change this behavior, because it would force a large majority of packages using bundling to change. My guess is that you're trying to use bundling for something slightly different than its original purpose, and while I don't want npm to get in your way, your suggested solution won't work for bundiing's primary use case. What's the high-level thing you're trying to do? put that in a new issue, and we can try to come up with a solution.

**Comment by seishun** [comment]
>The maintainer of package A may have no control of bundled package B, and therefore wouldn't be able to specify that package B's dependencies should be bundled.

The maintainer is bundling package B, so they can modify package B's `package.json`.

>What's the high-level thing you're trying to do? put that in a new issue, and we can try to come up with a solution.

I would prefer not to open a new issue since I'm not sure my particular use case is something npm should support specifically.

I am writing a module (let's call it R) that does two things:

* In the prepublish script, it downloads resource files from a third-party server.
* When `require`d, it parses those resources and generates JS classes (required for communication with a certain service).

The resources update regularly, so I don't want to maintain an npm package (it will be on github only). I also don't want to put the downloading part into the install script since the end user doesn't need to have the latest resources. Instead, I want to move that responsibility to module authors who want to depend on R. They make sure everything works and publish to npm with the resources bundled.

Hopefully this is clear enough. I thought `bundledDependencies` would be a perfect solution for my use case (I still think it is - I just don't like how R's dependencies are bundled, too). But maybe there is a better way.
