### ISSUE TITLE
`npm install` doesn't update scoped package in-place to match package.json

### ISSUE THREAD

**Issue by ljharb** [npm/npm#9133]
In multiple packages, I've run into this with `npm` v2.13.2`on`io.js` `v2.5`:

I have `@ljharb/eslint-config` installed at `v1.0.3`, and `package.json` was changed from `^1.0.3` to `^1.0.4`.
- `npm ls` doesn't report any errors (which I'd expect it to, since `1.0.3` doesn't satisfy `^1.0.4`.
- `npm install` doesn't cause `v1.0.4` to be installed

If I `npm install @ljharb/eslint-config` manually, naturally everything works. If I instead `rm -rf node_modules && npm install`, naturally everything works.

Is there perhaps something different about the algorithm for scoped modules?

**Comment by othiym23** [comment]
There's probably something wacky going on in `lib/outdated.js` related to scoped packages. These are the risks of having multiple paths for installation. Thanks for the report! Out of curiosity, does `npm@3` fix this?

**Comment by ljharb** [comment]
`npm` `v3.2.0` does indeed work as I expect with `npm install`

**Comment by othiym23** [comment]
Oh wait – I thought you were talking about `npm update`, not `npm install`. Are you sure this behavior differs for scoped and unscoped packages? One of the motivators for the new multi-stage installer was the fact that the old installer basically says, "well, there's a package there, guess there's nothing for me to do!"

I think there's a bug here either way, but it sounds like it's probably in `lib/ls.js` – npm should definitely be flagging the invalid version. If there is a difference between scoped and unscoped packages on install, that's the root cause.

**Comment by ljharb** [comment]
My typical workflow is to run `salita` which updates the deps in package.json, and `npm install` to install them - I'd not had trouble with it in a long time, and all the unscoped packages I usually update this way seem to work just fine too.

It definitely makes sense that it'd be a bug in `ls` itself.

**Comment by ljharb** [comment]
fwiw, when i'm in a package with `"@ljharb/eslint-config": "^1.0.4"`, and I have `v1.0.3` installed, `npm ls` does not error out, and `npm3 ls` merely says that v1.0.3 is extraneous - and doesn't complain that 1.0.4 is missing.

**Comment by ljharb** [comment]
This also seemed to happen in npm3 with `ecmarkup` `v2.0.0-beta3`- ie, a non-latest version.

**Comment by ljharb** [comment]
Confirmed again, this is only broken in `npm v2`.
