### ISSUE TITLE
Ability to set default license for scoped modules

### ISSUE THREAD

**Issue by toddself** [npm/npm#9158]
Many of the things I create for work are non-open source projects, but we're using the NPM registry and private/scoped modules to provide an easy way for people to install/use these modules.

However, when I'm creating a non-scoped module, it's by default open-source.

It would be great to have the ability to set a default license for when you're creating a scoped module vs a non-scoped module. I always have to google whatever the magic incantation is for the license field in order to pass the license-check level boss, and it would be great to be able to just add this as a default.

**Comment by othiym23** [comment]
This use case, as you've defined it, is pretty narrowly applicable, and even if I reframe it in terms of being able to map license to scopes (because there is some notion of mapping registry configuration to particular scopes already), it still feels like it would be hard to discover and remember to use (to me – @zkat saw this as more useful when we were discussing it).

_However_, there is something that npm already offers – [`~/.npm-init.js`](https://docs.npmjs.com/misc/config#init-module). It's underdocumented and has [at least one bug](https://github.com/npm/npm/issues/9270), but I know there are at least a few people out there who are using this for more complicated / opinionated package initialization setups. Does this sound like a situation where being able to scratch your own itch would be sufficient?

**Comment by toddself** [comment]
Oh wow!  I hadn't noticed that was even available.  This looks like it would suffice for my needs.

Thanks again!
