### ISSUE TITLE
v3.2: Turn ENOENT missing package.json warnings and errors off?

### ISSUE THREAD

**Issue by eush77** [npm/npm#9161]
Is there going to be a config option to silence warnings and errors telling me that I miss `package.json` (when in reality this is intentional)?

I often install stuff to temporary directories just to play/experiment and I'm not comfortable seeing these errors all the time.

```
$ npm install thingy
…
npm WARN ENOENT ENOENT: no such file or directory, open '/tmp/tmpdir/R3semq/package.json'
npm WARN EPACKAGEJSON /tmp/tmpdir/R3semq No description
npm WARN EPACKAGEJSON /tmp/tmpdir/R3semq No repository field.
npm WARN EPACKAGEJSON /tmp/tmpdir/R3semq No README data
npm WARN EPACKAGEJSON /tmp/tmpdir/R3semq No license field.
```

Or even:

```
$ npm ls
…
npm ERR! error in /tmp/tmpdir/R3semq: ENOENT: no such file or directory, open '/tmp/tmpdir/R3semq/package.json'
```

**Comment by othiym23** [comment]
When I want to test people's repro cases for bugs (which I do many many times a week), this is what I do:

```
mkdir test-npm-is-being-bad
cd test-npm-is-being-bad
npm init -y
npm install -S package-npm-is-being-bad-to
```

This silences the warnings and also gives me something to refer to later when I'm trying to remember what I was doing. If you want to turn off warnings altogether, you can run `npm --loglevel=error` (or even `npm config set loglevel=error` if you want to be super hardcore about it), but you're going to lose a lot of useful feedback. I don't really see a place for a special config option just to silence these warnings.

**Comment by saper** [comment]
I am getting this in response to `node install node-sass ([npm-debug.log on gist](https://gist.github.com/f0153fa8886c0bb65ec0)) in `/tmp`:

````
npm WARN ENOENT ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN EPACKAGEJSON /tmp No description
npm WARN EPACKAGEJSON /tmp No repository field.
npm WARN EPACKAGEJSON /tmp No README data
npm WARN EPACKAGEJSON /tmp No license field.
```

This is at least confusing and unnecessary. Kind of violates [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

And it is not a reason (not even contributing to) the ultimate failure (which is https://github.com/sass/node-sass/issues/1061)

**Comment by acarstoiu** [comment]
@othiym23: the real issue here is **why** are those warnings displayed? What made _npm_  try to consult `(cwd)/package.json`? Nothing, at least not on the command line.

I believe this ticket was closed too quickly.

**Comment by othiym23** [comment]
`package.json` is npm's control file and manifest, and it _strongly prefers_ that `package.json` exist, to the point of printing out a warning if it's not found. In addition, due to the way that it navigates up the directory tree looking for a `package.json` when performing many default actions (i.e. `npm install --save <packagename>`), _not_ having a `package.json` in the current working directory, even if it's a stub, can lead to far more surprising behavior (i.e. the requested package being installed somewhere unexpected, like your home directory). The current warnings block may be slightly verbose (i.e. if there's no `package.json` file, it might be useful to just print that, instead of warnings about the missing package.json fields), but I believe that printing a warning about working without a `package.json` is appropriate.

**Comment by acarstoiu** [comment]
We're in the business of computers doing what they are told, _not_ what the operators actually want. Installing packages in unexpected places is one of the possible outcomes.
And indeed, I was referring to the `--save*` command line options: if any of them was specified, then the lack of a `package.json` file should be a fatal error. Otherwise, a warning message is unjustified, least the the individual warnings about various fields.

I can see the intention, but over time, _any_ operator will ignore them as noise. That's why they should be conditioned by actual need of `package.json`.

**Comment by saper** [comment]
So go ahead and disable the possibilty to run `npm install` in the directory without `package.json`. "strongly prefers" is a sign of a bad and confusing design.

**Comment by dhowe** [comment]
+1

**Comment by dhowe** [comment]
Agree ^

**Comment by Qkenkenu** [comment]
to start using NPM you need to initialize it for project you are developing, 
use https://www.npmjs.com/package/initialize

br, Q

**Comment by psigen** [comment]
Note that this warning also happens when installing packages outside any modules with a non-root user (at least on OSX).
```
~ $ npm install foobar
[...]
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/[USERNAME]/package.json'
npm WARN EPACKAGEJSON [USERNAME] No description
npm WARN EPACKAGEJSON [USERNAME] No repository field.
npm WARN EPACKAGEJSON [USERNAME] No README data
npm WARN EPACKAGEJSON [USERNAME] No license field.
```

At the very least, _this_ behavior seems pretty uninformative, and the above is not an unreasonable use case (as far as I can tell) for installing node-based CLI tools that are distributed by NPM as a non-root user.

**Comment by antics** [comment]
Fresh install on OSX 10.11.6 with node.js 6.4.0 Current:

`Creator:qr antics$ npm install qrcode-reader
/Users/antics/Nodes/qr
└── qrcode-reader@0.2.1 

npm WARN enoent ENOENT: no such file or directory, open '/Users/antics/Nodes/qr/package.json'
npm WARN qr No description
npm WARN qr No repository field.
npm WARN qr No README data
npm WARN qr No license field.`

**Comment by acarstoiu** [comment]
Please **reopen this issue** and eliminate these unjustified and annoying warnings.

**Comment by deepak040** [comment]
for remove these warnings from CLI when instaling it on magento local root then just check 2 files -
package.json.sample and Gruntfile.js.sample at magento root and try to rename them by removing .sample suffix and try again. i think now this issue being resolved

**Comment by asthagaur3** [comment]
i also get the same error but i am not able to remove it. give me any solution by which i can solve it

**Comment by deepak040** [comment]
check your magento root directory and find these 2 files :+1: 
package.json.sample and Gruntfile.js.sample
then  remove .sample from both files and try again i think its works now otherwise comment your error here.i will try to solved it.

**Comment by asthagaur3** [comment]
magento is not in my aptop

**Comment by asthagaur3** [comment]
this is the error msg

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Astha Gaur\package.json'
npm WARN Astha Gaur No description
npm WARN Astha Gaur No repository field.
npm WARN Astha Gaur No README data
npm WARN Astha Gaur No license field.

**Comment by pannous** [comment]
solution to some use cases (not OP) : replace
`sudo npm install`    with
`sudo npm install -g`

**Comment by fayeyen** [comment]
thanks Qkenkenu!
"to start using NPM you need to initialize it for project you are developing, 
use https://www.npmjs.com/package/initialize"

**Comment by asthagaur3** [comment]
i am using window

**Comment by asthagaur3** [comment]
i am using window

**Comment by RamMohan222** [comment]
I got this message while installing the newman and after that I'm checking the newman command it says

'newman' is not recognized as an internal or external command,
operable program or batch file.

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\SUNKPOLP18\package.json'
npm WARN SUNKPOLP18 No description
npm WARN SUNKPOLP18 No repository field.
npm WARN SUNKPOLP18 No README data
npm WARN SUNKPOLP18 No license field.

**Comment by asthagaur3** [comment]
fristly run npm init command

then it will ask some question , you have give ask to all these .

**Comment by TejashreeD** [comment]
This Works!
`sudo npm install -g --save [package_name] `

**Comment by tonybreak** [comment]
@TejashreeD this does work! thx a lot!

**Comment by acarstoiu** [comment]
[My comment](https://github.com/npm/npm/issues/9161#issuecomment-244318633) has seen so many votes, yet nobody from **npm** cares. And it's not the only comment that received public approval.

@othiym23, is it so difficult to admit that your way of thinking is not popular (to say the least) and fix this _nonsense_? Are you waiting for it to get even older than it already is (more than one year 👎 ) and then claim that "it's been working like this since forever"?

**Comment by legodude17** [comment]
@acarstoiu please be more respectful. Also, the CLI team has a lot of work todo, as noted by the 2400+ open issues. Please be patient.

**Comment by RamMohan222** [comment]
npm init command works for me thanks a lot

**Comment by acarstoiu** [comment]
@legodude17 I never ever accepted being thrown fake answers like "be respectful", "shut up now" and the like. And I do not intend to change that.
**Nobody said you have to fix this nonsense _right now_.** I just want you people to admit that this behaviour is wrong and reopen the issue. And just for that I've been _very_ patient, my first comment dates from more than **7 months ago**. 7 months for 10 seconds...

**Comment by legodude17** [comment]
@acarstoiu, `package.json` is `npm` and `nodejs`'s manifest file. Why would you need to install a module without `package.json`? The only one I think of is to just get the code, but that is what `git clone` is for. There is even a proposal for `npm fetch`, or a [gist](https://gist.github.com/legodude17/d8d52bb5a395512eee0cf75909980a75) that I wrote.

**Comment by eush77** [comment]
@legodude17 

> `package.json` is `npm` and `nodejs`'s manifest file. Why would you need to install a module without `package.json`?

Node.js works without `package.json` just fine. It is a convenient feature for small projects that don't need to be packaged: small experiments, proofs of concepts, trying out to tie several modules' APIs together or just random hacking in the REPL. Creating `package.json` for such one-off use cases seems redundant.

**Comment by psigen** [comment]
@legodude17 it is entirely reasonable to want to install one of the many CLI packages for node globally.

Doing `npm install -g gulp` should not result in an error if you don't happen to have a `package.json` in the current working directory where the command is run.

**Comment by KenanY** [comment]
@psigen Fortunately that's exactly the behavior you'd see today when globally installing packages.

**Comment by legodude17** [comment]
As @othiym23 said, you can just use `npm init -y` and then then the
`package.json` can help you with your messing around.

**Comment by acarstoiu** [comment]
For your information, Node.js works very well without any `package.json`, the only circumstance when this file helps is when a folder is `require()`d (namely, Node.js looks for the `main` property in `package.json`).

So, once again, a missing `package.json` is no reason for dummy warnings.

**Comment by legodude17** [comment]
@acarstoiu I don't understand why you are so devoted to removing the warnings, when you could talk like a second to run `npm init -y` and then be on your merry way.

**Comment by Camwyn** [comment]
I got here because of similar error messages but discovered it was because my editor had replaced all the spaces with tabs in package.json - so watch your package.json format!

**Comment by simonallison** [comment]
NPM professionalism...

**Comment by cvega** [comment]
@legodude17 It feels like a hack to init a package when you are not in fact creating a package just to install other packages and suppress warnings? I just got bit by this in our build process, and it took me 20 minutes to track down. I'm happy to use the work around but I think @acarstoiu has a valid point even if the delivery of the message could have been better. Would we benefit from a cli switch to suppress warnings? I personally rather see this thrown as INFO before the package install starts versus doing the right thing then throwing a warning.

**Comment by scganterh** [comment]
As said, there are a lot of use cases where you are not creating a package. I'm writing a demonstration in which I have to use an NPM installable tool. Having a warning printed in a demonstration is very inconvenient, because you don't want to waste time explaining why it is there (which I frankly don't understand) and you also don't want to confuse your audience with workarounds.

**Comment by sparr** [comment]
Chiming in alongside everyone else. I've just installed node and haven't started any projects yet. I do `npm install something` which seems quite happy to install to `~/.npm/something`... but then it complains that `~/package.json` doesn't exist and the other four warnings as well. This seems silly and misleading for an otherwise completely normal use case.

**Comment by tcsiwula** [comment]
+1 This is pretty annoying and unuseful error reporting. It would be cool if npm errors had hints to resolve the warning generated.

**Comment by legodude17** [comment]
@sparr What is the use case for putting packages in your home directory? I have done that multiple times, every time it was a mistake, hence the warning.

@tcsiwula that would be a different issue.

**Comment by sparr** [comment]
@legodude17 use case: I am not a Node module developer. I am just writing a five line node script without its own directory or npm init'd environment, and I need to install a dependency for it.

This is the equivalent of `pip install` without a python virtualenv environment, or `gem install` without a ruby rbenv environment, etc. Installing community libraries in my user's home directory is a perfectly normal thing to do in every language, apparently except for Node.

**Comment by legodude17** [comment]
If you think that is the best, ok. IMHO it would be better to make that five line script into a module/package.

**Comment by sparr** [comment]
@legodude17 YHO about what approach is better isn't relevant to the thousands of people who won't ever get involved with the node/npm community standards regarding module development, and just want to write a script and run it like they can in **any other language**

**Comment by sparr** [comment]
Personally, my five line script is now 200 lines long, and I *have* done `npm init` to create a package.json... and npm *still* complains that I don't have a npm repository established and specified for my module.

**Comment by proxa** [comment]
+1 For these warnings being unhelpful and confusing

**Comment by equazcion** [comment]
I got this error when trying to install jquery. 

I've never used Node.js before. Coming at this from the newbie's perspective, this is a noob-unfriendly warning. I'm trying to diagnose a problem and made the [quite natural] assumption that this might be the cause. It's the opposite of intuitive, and serves as a very efficient way of frustrating beginners away from pursuing work with Node. 

If the existence of package.json is so "strongly preferred," why not at least include some better clues in the warning message? 

"Package.json is not required but is strongly preferred. Use [command] to create one for your project."

...so that we don't have to do a few google searches to find this out, and hopefully get to read through several posts on this page before finding the full explanation?

**Comment by mhamzas** [comment]
npm install -g --save [package_name] 

This worked!

**Comment by Art4** [comment]
I got this error after I removed two unused packages (bower and grunt) with `npm remove`.

```
npm WARN enoent ENOENT: no such file or directory, open '[...]/node_modules/grunt/package.json'
npm WARN enoent ENOENT: no such file or directory, open '[...]/node_modules/bower/package.json'
```

**Neither** of the following tips had an effect:

- sudo npm install -g npm
- npm cache clean
- npm prune

Finally I resolved this warning by deleting the whole node_modules folder and run `npm install`.

This warnings are useless if you don't know where they came from!

**Comment by maheshkareeya** [comment]
**_Even I got same problem...
just check your path firstly.....after that every thing will work correctly..._**

**Comment by shivamgupta-gupta** [comment]
There is one simple solution to this issue. Make sure that you are inside your project's directory when you run `npm install`.

**Comment by Art4** [comment]
Doesn't worked for me, see https://github.com/npm/npm/issues/9161#issuecomment-294980602

**Comment by sparr** [comment]
@shivamgupta-gupta you may have missed it up-thread, but many of us are not working in a node project directory.

**Comment by shivamgupta-gupta** [comment]
@sparr I haven't worked on complex projects but did you try this in your root directory?

**Comment by sparr** [comment]
@shivamgupta-gupta Sorry if I was unclear. Some of us are not working on a thing that is a node project at all.

**Comment by jjc12** [comment]
Voting to close the issue...@mhamzas `npm install -g --save [package_name]` worked.

From a [StackOverflow answer](https://stackoverflow.com/a/36023013/2124148):

`npm install <package_name>` without an option, just installs the package but does not update the dependencies as listed in your package.json.

`npm install <package_name> --save` installs the package and updates the dependencies in your package.json.
