### ISSUE TITLE
HTTP api - minor verision query

### ISSUE THREAD

**Issue by groovy354** [npm/npm#9179]
Hi, 
Have there been any changes to npm's http api? We use HTTP queries like `GET http://registry.npmjs.org/sealious/0.4` to check if there are new patch versions available for that particular minor version, but this address returns an empty string since few hours ago...

A link with patch version number works, though (`GET http://registry.npmjs.org/sealious/0.4.9`)

Is it a bug? Is it a feature?

**Comment by debian-sh** [comment]
In my opinion it's a bug.

**Comment by othiym23** [comment]
The npm registry team rolled out a change to the registry last night that removed this route from being exposed to the world at large in an effort to secure some possibly risky access patterns to the registry. We have since restored the route, and will try to give more advance notice before dropping support for it in the future (which may happpen!). I apologize for the disruption and the lack of prior notice!
