### ISSUE TITLE
question: is the ability to run a dependency's scripts using `npm run-script <pkg> <script>` removed on purpose?

### ISSUE THREAD

**Issue by joakimbeng** [npm/npm#9186]
**Background:**

I was really glad when I found out that npm has (or had) the ability to run a dependency's scripts by running: `npm run-script <pkg> <script>`. Which is also stated in the [npm documentation](https://docs.npmjs.com/misc/scripts#description) as:

> Additionally, arbitrary scripts can be executed by running npm run-script <pkg> <stage>

When I tried: `npm init -y && npm i -S tap && npm run-script tap test`, it didn't work and I got this output:

```bash
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "tap" "test"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.1

npm ERR! missing script: tap
```

I then began tracing back when the feature was removed and have concluded that it has been so mistakenly.

**Related commits:**

* Taking a look at a commit from [run-script v.1.0](https://github.com/npm/npm/commit/03f782fe2978ddaae80fa5e094e9b319d2192066) one can see that the feature is there back then.
* When the [ability to pass arguments to scripts was added](https://github.com/npm/npm/commit/df4b0e7fc1abd9a54f98db75ec9e4d03d37d125b) the above mentioned feature was removed, even though the `runScripts.completion` still works for dependencies' scripts. Which feels to me like a mistake.

**Closure:**

Am I right that this was mistakenly removed and you would accept a PR for this? Or am I missing something and this feature should actually be removed?

**Comment by boennemann** [comment]
npm scripts changed w/2.0.0.
You might want to try `npm explore tap -- npm test` now. You might have to install its devDependencies first though.

**Comment by othiym23** [comment]
This is behavior that was changed in `npm@2` so that users could pass arguments to run-scripts, akthough I don't believe it was ever the intent that users be able to run arbitrary bins exported from dependencies (like @boennemann pointed out, that's what `npm explore <depname> -- <binname> <arguments>` is for). I'm pretty sure the current documentation is reasonably unambiguous on this, but if it's still confusing, we'd be happy to take a patch to clarify it. Aside from that, I don't think it would make sense to make more big changes to `npm run`, but do check out the discussion on [`npm-exec`](https://github.com/npm/npm/issues/6053), which sounds like exactly what you're looking for, with the teeny tiny caveat that it doesn't exist yet. ;)

**Comment by joakimbeng** [comment]
I see, didn't know about `npm explore`. Great, thanks! :)

**Comment by joakimbeng** [comment]
@othiym23 sounds nice, looking forward to it!
