### ISSUE TITLE
Possible folder redirrection issue with documentation

### ISSUE THREAD

**Issue by iplusplus** [npm/npm#9203]
Hi, I can't find the documentation on my system.  I came across this error log (here, in full).  
It's a corporate laptop, so it looks like it has tried to install to a global folder space on my domain (is my terminology correct here?).  Any help appreciated!
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'http' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: ENOENT, stat 'C:\Users\mlazarides\AppData\Roaming\npm'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.2.9200
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "http"
9 error cwd C:\Users\mlazarides
10 error node -v v0.10.36
11 error npm -v 1.4.28
12 error path C:\Users\mlazarides\AppData\Roaming\npm
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```

**Comment by othiym23** [comment]
You might want to take a look at the [npm troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting#error-enoent-stat-cusersuserappdataroamingnpm-on-windows-7), which has a section about this. Your might also want to consider [upgrading to a newer version of Node](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-windows), because the one you have is getting pretty old, and comes with a similarly old version of npm that's missing support for a lot of newer npm registry features.

**Comment by iplusplus** [comment]
Hey Othiym23,  many thanks for pointing me to the troubleshooting guide and the upgrade suggestion.

WM

**Comment by ehsalazar** [comment]
It sounds like you're good to go. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
