### ISSUE TITLE
npm install https://atom.io/download/atom-shell/nan-1.6.1.tgz  failed

### ISSUE THREAD

**Issue by kunyan** [npm/npm#9211]
the url https://atom.io/download/atom-shell/nan-1.6.1.tgz  will redirect to a AWS url

when I use npm@1.4.5, it worked, but when I use v2.x. it will show 
`npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz`

I think "npm install" can not handle the case which response http code is 302

**Comment by KenanY** [comment]
@kunyan I cannot reproduce this with the latest stable release of `npm` (`2.13.4`).

**Comment by kunyan** [comment]
@KenanY , it's weird, I can reproduce it again and again . 
I thought is my network problem , but when I use 

` curl -O https://atom.io/download/atom-shell/nan-1.6.1.tgz `

it can be downloaded. No matter with proxy or not, npm install always failed

**Comment by kunyan** [comment]
` npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error `

**Comment by KenanY** [comment]
@kunyan This is with `npm@2.13.4`?

**Comment by kunyan** [comment]
@KenanY  yes.

When I use npm@1.4.25, it will work. no error

**Comment by kunyan** [comment]
My OS is Fedora 22

**Comment by othiym23** [comment]
This is (probably) due to a bug in how `npm-registry-client` (the package that deals with talking to the npm registry and downloading stuff from wherever) handled sending certain HTTP headers (having problems with redirects is a good guess, but npm has handled those fine for years now). There is [a branch of npm](https://github.com/npm/npm/tree/othiym23/fetch-headers-hack-do-not-ship) where work is underway to fix this. The fix will probably land sometime in the next two or three releases. Thanks for the report, and I'm sorry there isn't a really good workaround for this right now!

**Comment by falms** [comment]
This problem is similar to https://github.com/request/request/pull/1894 and https://github.com/atom/apm/issues/322 .
request@2.67.0 or newer will probably solve this kind of problems.
