### ISSUE TITLE
EISGIT should not obscure the real problem

### ISSUE THREAD

**Issue by saper** [npm/npm#9229]
I have tried `npm install node-sass` in some directory (`/home/saper/sw/test`). As it happens, I have `/home/saper/sw/node_modules` already and there is some stuff in it (`nan` and some other modules).

`npm install node-sass` fails because of https://github.com/sass/node-sass/issues/1061 (btw. interesting failure mode for `node-gyp` modules).

The output:

````
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/iojs',
npm verb cli   '/home/saper/sw/npm/npm/bin/npm-cli.js',
npm verb cli   'install',
npm verb cli   '-ddd',
npm verb cli   '--no-progress',
npm verb cli   'node-sass' ]
npm info using npm@3.2.2
npm info using node@v3.0.0
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readLocalPackageData
^C
m> node /home/saper/sw/npm/npm/bin/npm-cli.js install --no-progress node-sass
npm WARN ENOENT ENOENT: no such file or directory, open '/home/saper/sw/package.json'
npm ERR! FreeBSD 10.1-STABLE
npm ERR! argv "/usr/local/bin/iojs" "/home/saper/sw/npm/npm/bin/npm-cli.js" "install" "--no-progress" "node-sass"
npm ERR! node v3.0.0
npm ERR! npm  v3.2.2
npm ERR! path /home/saper/sw/node_modules/nan
npm ERR! code EISGIT

npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     /home/saper/sw/node_modules/nan
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saper/sw/test/npm-debug.log
````

And here comes the full log: https://gist.github.com/1a79f70dc2ab5d20bcbe

How do I know why it failed? I tried in a different directory!

Exercise to the reader: try to find node-gyp related failure in the [npm-debug.log](https://gist.githubusercontent.com/saper/1a79f70dc2ab5d20bcbe/raw/2637483971ff23e14ac73e266f8e34505c4adab8/EISGIT.log) :)

Frankly now with auto-flatteing I start to be afraid that `npm` might choose to randomly nuke my `node_modules` directories (or maybe some other!)

**Comment by othiym23** [comment]
While the scenario described here is surprising to the point of being confounding, all of the pieces of npm are on their own behaving the way they're supposed to:

1. Since there's no `package.json` in `/home/saper/sw/test`, npm traverses up the filesystem hierarchy looking for either a `package.json` or a `node_modules` directory. It will go ahead and create a new `node_modules` in `/home/saper/sw/test` if and only if neither of those are found all the way back up to the root directory.
2. npm warns that there's no `package.json` in `/home/saper/sw` – it's traversed up to this directory and is erroring here because there's a `node_modules` subdirectory. If you want to keep the install happening in `/home/saper/sw/test`, you should run a quick `npm init -y` to generate a stub `package.json`.
3. There's a `node_modules` subdirectory for npm to install into, but some of its subdirectories are actually checked-out git repositories. npm errors at this point, because it's been the policy of the CLI for a long time to not move or replace Git repositories so as to not stomp on user code. (The place where you have those repos checked out probably shouldn't be called `node_modules` – it's safer to use `npm link` to make it so that they can be used elsewhere.)

It's worth pointing out that none of these behaviors are new in `npm@3` -- these are things that npm has always done.

It's not really clear to me what else npm could know to do at this point. I see the argument for a better error message, but the CLI lacks the situational awareness to know it should be doing something else, and I'm not sure that there's a heuristic that would let it make that call in this situation that didn't introduce a new set of edge conditions for it to guess wrongly about.

As such, I'm going to close this issue as not being a bug in npm, but if you have thoughts on how npm could consistently and simply provide more useful diagnostic information here, I'd love to hear them. Thanks for the report, and I'm sorry it took us so long to give you a response!
