### ISSUE TITLE
error npm install -g

### ISSUE THREAD

**Issue by OliverStrom** [npm/npm#9241]
```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\User\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\User\AppData\Roaming\npm\package.json
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: 'C:\\Users\\User',
8 silly cache add   type: 'local' }
9 error addLocal Could not install C:\Users\User
10 verbose stack Error: EISDIR, read
10 verbose stack     at Error (native)
11 verbose cwd C:\Users\User
12 error Windows_NT 6.1.7601
13 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code EISDIR
17 error errno -4068
18 error EISDIR, read
19 error If you need help, you may report this error at:
19 error     <https://github.com/npm/npm/issues>
20 verbose exit [ -4068, true ]
```
I don't really know what's happening here. I've had no problems before while running this. I'm really new to npm so I don't know what I've done wrong.

**Comment by KenanY** [comment]
@OliverStrom From the log, it appears that you are running `npm install -g`, without any arguments and without a `package.json` in your current working directory. Because of this, `npm` has no idea what you want it to install. If I may ask, what are you _expecting_ to happen when you run `npm install` like that? I can help steer you in the correct direction if I know what your intention is.

If it helps, there is [a getting-start guide on global installs](https://docs.npmjs.com/getting-started/installing-npm-packages-globally) and [a manual page on `npm install`](https://docs.npmjs.com/cli/install).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
