### ISSUE TITLE
Git repo skipped when install from package.json

### ISSUE THREAD

**Issue by kevincolten** [npm/npm#9254]
From the command line, I can type `npm install --save platfora/Canteen` to get Canteen added to my `package.json`

``` json
{
  "name": "npm_test",
  "version": "1.0.0",
  "dependencies": {
    "Canteen": "platfora/Canteen"
  }
}
```

and Canteen imported into my `node_modules` folder.

But if I remove Canteen from `node_modules`, and try to reinstall from my `package.json` with `npm install`, `npm` skips right over it without error, and will even install other npm packages if present.

Any clues regarding this behavior?

**Comment by mistakevin** [comment]
```
$ npm -v
2.11.3
```

**Comment by stevemao** [comment]
Try the latest npm?

**Comment by mattpap** [comment]
The issue persists in npm 2.13.5. I tried using full URL, i.e. `git://github.com/platfora/Canteen.git`, instead of simply `platfora/Canteen`, but the outcome is the same (exit code `0`, no error messages). I can misspell the URL as well, no 404, etc. npm appears to just ignore this entry in our `package.json`.
