### ISSUE TITLE
Publishing to multiple registries following a specific flow

### ISSUE THREAD

**Issue by marcellodesales** [npm/npm#9281]
Is there a way to support publishing to multiple registries supporting a given flow? 

This is specifically to address the development of modules using a flow, say Git flow where a given git merge would trigger a different npm publish:

* **Merges to the "master" branch**: triggers an npm publish to the public "registry.npmjs.com"
* **Merges to the "develop" branch**: triggers an npm publish to the private "registry.mycompany.com"

Of course, considering the "registry.mycompany.com" contains a proxy to the public "registry.npmjs.com" server.

Current Approach
------

At the moment, we have been using scripts to change the value of the key "publishConfig" with the private registry during all the merges to the "develop" (usually from "feature/*" branches). Also, we bump the version on "package.json" depending on pattern matching of the branch names prior to executing "npm publish".

Is there anyone who has faced this before? Is this supported?

thanks
Marcello

**Comment by daedelus-j** [comment]
+1

**Comment by othiym23** [comment]
This is a pretty specific workflow, and as such seems like it would best be handled by a script or a git hook that looks at what branch you're on, rather than something integrated into npm itself. The simplest approach would just be to look at the current branch, and then call `npm publish --registry=<private or public registry>`. Since there's nothing really for npm to do here, I'm going to close this, but feel free to ping this issue if you have further questions.
