### ISSUE TITLE
@ sign should maybe be optional in package name for npm access

### ISSUE THREAD

**Issue by seldo** [npm/npm#9328]
The command `npm access ls-collaborators npmcorp/example` fails with the error message `access commands are only accessible for scoped packages`. However, `npm access ls-collaborators @npmcorp/example` works because the package really exists.

The `/` in the package name is not legal in a global package. Therefore in the presence of a slash but the absence of an @ sign npm should probably assume the @, as we do in other situations like specifying team names.

We don't do this everywhere because of the long-standing github shorthand, but nobody is going to be using `npm access` expecting it to tell them their github permissions (I hope).

**Comment by othiym23** [comment]
It is much simpler, both in terms of getting people familiar with scoped packages, and in architectural terms, to consider `@scope/packagename` to be an atomic unit, with bot `@` and `/` being part of the name. I really dislike the idea of introducing this particular affordable because it increases cognitive load in the form of not knowing when it's safe to omit the `@`. You're my boss and all so I'm not going to close this, but I remain -1 on the idea.

**Comment by seldo** [comment]
This is more of a product call, therefore I invoke the @isaacs for when he gets back from vacation.

**Comment by othiym23** [comment]
This still makes me go "ugh" for all the reasons I outline above. @isaacs, it's time for us to take this to the npm All-Father: do you have an opinion on this one way or the other?

**Comment by zkat** [comment]
@seldo at the VERY LEAST we can do a much better error message for this -- specially since, as you point out, scoped and unscoped packages are unambiguously distinguishable even without the `@`. We're making this an error handling issue, but I personally also agree with Forrest that it's more tasteful to enforce the `@` everywhere if only to simplify things.

**Comment by othiym23** [comment]
> more tasteful

🤔

We've let this one sit for a while, @isaacs chose not to weigh in, and the CLI team is pretty much uniform in our consensus that consistency wins here, so we're going to close this out for now. If it turns out that we get feedback from support or beseeching entreaties from the community, we can take another look at changing this.
