### ISSUE TITLE
Why don't other encoded chars like %40 work in registry URLs?

### ISSUE THREAD

**Issue by jameslnewell** [npm/npm#9351]
eg:

    http://registry.npmjs.com/%40digitaledgeit%2fpaypal => 404
    http://registry.npmjs.com/@digitaledgeit%2fpaypal => 200

Is it a bug? The reason I ask: https://github.com/rlidwka/sinopia/pull/280#issuecomment-120665175

**Comment by othiym23** [comment]
`@` is a URL-safe character, but the escaping of `/` is necessary so that the npm registry software doesn't interpret the `/` in a scoped package name as part of a path delimiter. I agree, it looks a little funky, but it's that way by design. In a semi-ironic twist of fate, changing how the CLI encodes scoped package names would be a semver-major breaking change precisely because it might change how things work with third-party registries / private registries built on `sinopia`, `cnpmjs`, and Artifactory. Since it works the way it is, we'd need a pretty compelling reason to change it at this point.
