### ISSUE TITLE
Behavior of npm uninstall without args

### ISSUE THREAD

**Issue by codefoster** [npm/npm#9372]
When I use `npm uninstall` from inside the root directory of a module, it uninstalls that module from my global environment. I can't find that this behavior is documented anywhere. Is it intentional?

**Comment by sinkingshriek** [comment]
I believe that's the case. Atleast in [`v2.13.2`](https://github.com/npm/npm/blob/v2.13.2/lib/uninstall.js#L35) just by thoroughly looking at it. I haven't tried on other versions however. Which version are you using?

**Comment by othiym23** [comment]
`npm uninstall` == `npm rm` == `npm unlink`. Since `npm link` with no parameters links the package into the global prefix, `npm unlink` with no parameters is the symmetric operation to remove the link. It's a little bit counterintuitive, and it _is_ undocumented, so if you wanted to put together a PR to include this in the docs, it would be merged (with thanks from the team!).

**Comment by codefoster** [comment]
Awesome. I'll try to find time as I'm sure you are :)
