### ISSUE TITLE
lost in installing need Help! 

### ISSUE THREAD

**Issue by guiprix** [npm/npm#9414]
i had a previous problem that was : 
![screenshot 2015-08-26 10 00 34](https://cloud.githubusercontent.com/assets/5721937/9489604/82302806-4be2-11e5-9d08-07079f4c575c.png)

then i tried wrongly this solution :+1: sudo npm cache clean -f
sudo npm install -g n
sudo n stable
node -v

and now im lost with errors:
![screenshot 2015-08-26 11 04 38](https://cloud.githubusercontent.com/assets/5721937/9489638/af45316a-4be2-11e5-8f67-8558b9c64d48.png)

**Comment by KenanY** [comment]
@guiprix Looks like a couple of permissions problems to me. Could you try fixing the permissions on your `npm` cache directory?:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

Furthermore, since global modules are being installed to `/usr/local/`, you will have to prefix your `install -g` commands with `sudo`, or `chown` that entire directory to yourself (since a system default is that you don't have permission to modify that folder).

**Comment by guiprix** [comment]
Thank you a lot  for your answer Kenan. i follow your suggestion, and looks like now im back to my original problem with permission , at least!...I tried this as per screenshot: when i run it with sudo  still don't get permission i guess
![screenshot 2015-08-26 17 09 34](https://cloud.githubusercontent.com/assets/5721937/9497535/b09871b6-4c15-11e5-8b4d-2f489f493e14.png)

if i run it without sudo is the following: im bit lost coz this is not my pair of shoes:// thanks

![screenshot 2015-08-26 17 10 58](https://cloud.githubusercontent.com/assets/5721937/9497570/e773bdd0-4c15-11e5-90ca-7e48b122d3c5.png)

**Comment by guiprix** [comment]
this was the instruction as per installment: 
![image](https://cloud.githubusercontent.com/assets/5721937/9497759/e255d120-4c16-11e5-8d60-19844dd50dc0.png)

**Comment by othiym23** [comment]
Closing as resolved!
