### ISSUE TITLE
'npm: command not found' after trying 'npm update -g npm'

### ISSUE THREAD

**Issue by theclarkofben** [npm/npm#9457]
For some reason I keep losing access to npm after I attempt to update npm. 

Could someone help me identify and fix what has gone wrong? I'm a beginner so would really appreciate a little help and guidance. Thank you very much.

![npm problem](https://cloud.githubusercontent.com/assets/5796370/9603389/5c0976c6-50a8-11e5-83ef-3ca24edde179.jpg)

**Comment by othiym23** [comment]
It looks like you should run `sudo npm install -g npm` – note the lack of a dash in front of the second npm, and using `install` instead of `update`, which will still get you the latest version of npm. Your login user doesn't have write permission to install to `/usr/local/lib`, which is why you're getting those `EACCES` errors.

**Comment by othiym23** [comment]
Also, due to a fun quirk of npm, sometimes a failed update will nuke the symlink that npm makes into `/usr/local/bin` (where your login user _does_ have write permissions). If you rerun the Node installer, it'll reinstall npm for you and fix that. If you don't want to have to use sudo to do global installs, run `sudo chown -R $(whoami) /usr/local/lib/node_modules`, or look at using a Node version manager like nave or nvm.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Were you able to rerun the Node installer? If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by theclarkofben** [comment]
I found out that my $PATH environment variable did not include a necessary
path to Node. After adding it the issue was solved.
