### ISSUE TITLE
npm link broken on windows with node 4

### ISSUE THREAD

**Issue by jon-hall** [npm/npm#9505]
Using npm 3.3.2, after updating to node v4.0.0-rc.1, 'npm link' throws an error on Windows complaining that the node version is pre-0.7.9.

**Comment by jnfingerle** [comment]
Since this is a real world problem that happens to be a hassle for me: Is there any way I could help to work on this bug?

**Comment by othiym23** [comment]
As soon as Node 4.0.0 is released (which should be imminent), this problem will go away. The underlying issue is that semver range matching doesn't include prerelease versions like `4.0.0-rc.1`. We're still discussing how to deal with this inside npm, because it definitely makes Node RCs and nightlies less useful than they should be.

**Comment by jnfingerle** [comment]
You're right, the problem has disappeared for me with 4.0.0. That said, being able to test against future prerelease versions would be of much help for my team.

**Comment by othiym23** [comment]
This is fixed in 6665e5489bae2418696695c5e8f15642ea2339b1 and c4dd5213b2f3283ea0392845e5f78cac4573529e for `npm@3` and `npm@2` respectively. Thanks for filing this!
