### ISSUE TITLE
Make npm completion only suggest options related to command.

### ISSUE THREAD

**Issue by stefanmaric** [npm/npm#9524]
`npm completion` has the ability to complete options, but it suggests ALL options that might or might not apply to ALL commands.

![screenshot from 2015-09-08 12-22-15](https://cloud.githubusercontent.com/assets/1009040/9741615/1d6ddfe2-5625-11e5-8002-ea6614cb16ca.png)

Feature request: only suggest options available for the given command.

I will open a pull-request if I can do it myself.

**Comment by othiym23** [comment]
This isn't a bad idea, but be aware that it's more complicated than it at first appears, because of how much bits of npm call other bits of npm, and how frequently people find new uses for options inside existing pieces of the tool. I have concerns about the project's ability to keep this kind of completion up to date.

**Comment by stefanmaric** [comment]
@othiym23 I was thinking on generating a JSON parsing the options from [/doc/cli](https://github.com/npm/npm/tree/master/doc/cli). Does that sound reasonable? I find npm docs very complete, they even target edge cases.

**Comment by othiym23** [comment]
They do and they don't. There are a lot of commonly-used options that aren't documented in the individual pages because it would add a lot of bulk. I think what might be the tightest solution would be to add a second `completionOptions` function to each command, and then extend the config tests to ensure that those functions matched the options that were actually used in that command. Barring that, shipping something that just completes based on the docs is a perfectly good place to start.
