### ISSUE TITLE
Logic behind the `from` field for npm-shrinkwrap.json?

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#9550]
Can anyone shed some light on the logic that defines the contents of the `from` field when generating a shrinkwrap file?

For example case A

```
    "async": {
      "version": "1.4.2",
      "from": "http://<private npm repository>l/async/-/async-1.4.2.tgz",
      "resolved": "http://<private npm repository>/async/-/async-1.4.2.tgz"
    }
```

vs caseB

```
     "async": {
       "version": "1.4.2",
       "from": "async@1.4.2",
       "resolved": "http://<private npm repository>/async/-/async-1.4.2.tgz"
     }
```

Why do we sometimes see an URL in the from field, sometimes just the pinpointed version? What influences this logic and how can we control this behavior?

**Comment by KenanY** [comment]
@binarykitchen I've found https://github.com/npm/npm/issues/9117#issuecomment-127939062, which seems to be an independent investigation of it.

**Comment by binarykitchen** [comment]
@KenanY I read it before and it's not clear enough. His comments are vague, the recommended steps won't work and aren't the answer to my above question.

I am questioning the logic behind it. The code in few sentences. When is the from field a name, when it is an URL?

**Comment by Sinewyk** [comment]
It's a name when you first install with `npm i eslint@1.3`
```
// node_modules/eslint/package.json
"_resolved": "https://registry.npmjs.org/eslint/-/eslint-1.3.1.tgz",
"_from": "eslint@>=1.3.0 <1.4.0"
```
If you shrinkwrap right now it will copy/paste those field into the `npm-shrinkwrap.json`

Now if you remove your node_modules folder and install again `npm i` it will read the shrinkwrap, it will directly install from the resolved field, the from and resolved field will be equal inside node_modules/eslint/package.json
```
  "_resolved": "https://registry.npmjs.org/eslint/-/eslint-1.3.1.tgz",
  "_from": "https://registry.npmjs.org/eslint/-/eslint-1.3.1.tgz"
```
And if you shrinkwrap again, it will copy those fields into the shrinkwrap thus changing again the "from" field which will be equal to the "resolved" field
```
"from": "https://registry.npmjs.org/eslint/-/eslint-1.3.1.tgz",
"resolved": "https://registry.npmjs.org/eslint/-/eslint-1.3.1.tgz",
```
As far as I know of, only the resolved field is actually used when shrinkwrapping. Which is why there are tools like https://github.com/uber/npm-shrinkwrap or something along these lines.

Hope that helps.

PS: I literally did this to check it, and this is 100% reproducible, npm@2.14.3

**Comment by binarykitchen** [comment]
@Sinewyk thanks for explaining - this should be documented i think
