### ISSUE TITLE
I would love to see ENV variables get respected for dependencys to allow git user + pass

### ISSUE THREAD

**Issue by frank-dspeed** [npm/npm#9565]
Hello i have following reqest

When we dev on a git repo with user pass we need to add user pass to the depedencys json fild 

it would be nice to use env vars there so every one can use his own user pass with the same package.json

or supplying a config parameter that gets used with git would be a idea

**Comment by frank-dspeed** [comment]
At present environment extra char $ gets %24 because url parse we need to add that $ gets not replaced or even after url pase %24 gets $

**Comment by othiym23** [comment]
The underlying question here is how far npm needs to go to ensure parity between hosted-Git and registry dependencies. In general, we'd like to see the two of them be consistent with each other. At the same time, there's a significant amount of supporting infrastructure that would need to be built to improve npm's handling of Git repo credentials, and the CLI team isn't going to have the time to get to that in the next 6-12 months. Taking a step back, the thing to build would be some kind of mechanism for storing or caching credentials outside of `package.json` instead of using environment variables (it's not a good idea to put too much sensitive data into the process environment). Long-term, this would be useful as a way to store npm's own registry tokens, as well as other credentials used by the CLI. If somebody wanted to start working on that, that would be a very useful patch, and the project would love to have it.

As I said, we're not going to have time to get to it ourselves, so I'm going to close this feature request. If you're interested in an operational workaround, check out [`git-credential-cache`](https://git-scm.com/docs/git-credential-cache), which seems like something you could use as the basis for a small tool to speed up development and deployment. I think it should work out of the box with npm, but if it doesn't, because of the way that the CLI sanitizes the process environment to keep user git configuration from breaking the CLI's git integration, either file a PR fixing that or let us know we need to add another variable to the whitelist.

Thanks for your time!

**Comment by iarna** [comment]
(And more generally the chapter on git [Credential Storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage)– this can be hooked with solutions that are customized to your needs.)
