### ISSUE TITLE
 help:Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Vincent2015** [npm/npm#9569]
npm install

**Comment by KenanY** [comment]
@Vincent2015 A `npm-debug.log` file should be generated when you receive an error. Could you upload the contents of the file as a [gist](https://gist.github.com/)?

**Comment by othiym23** [comment]
Closing, because there's not enough information here for us to help you. If you're still having problems, please open a new issue. Information that helps us to help you includes log output, putting `npm-debug.log` into gist.github.com and including a link here, and including the versions of Node, npm, and the operating system you're using.
