### ISSUE TITLE
Can't download private modules from the EU registry mirror - 404

### ISSUE THREAD

**Issue by koresar** [npm/npm#9578]
In attempt to workaround this Australia-only bug https://github.com/npm/npm/issues/9574 we switched to the EU mirror (`npm set registry http://registry.npmjs.eu/`). It helped for non-private modules.

We **can't install any of our private modules** though. Please, fix (or refund :) ).

Any workarounds are very welcome.

```
[vagrant@localhost myapp]$ npm get registry
http://registry.npmjs.eu/

[vagrant@localhost myapp]$ npm install
npm ERR! fetch failed https://registry.npmjs.org/@safetyculture/blabla/-/blabla-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@safetyculture/blabla-segment/-/blabla-segment-1.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@safetyculture/blabla-segment/-/blabla-segment-1.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@safetyculture/blabla/-/blabla-1.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/@safetyculture/blabla-segment/-/blabla-segment-1.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/@safetyculture/blabla/-/blabla-1.1.0.tgz
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "node" "/home/vagrant/.nvm/v0.10.33/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.14.3

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /safetyculture/soter/npm-debug.log
```

**Comment by koresar** [comment]
Ok. I was just [told](https://twitter.com/othiym23/status/643242424555298816) by Forrest that EU "mirror" is not wunning by NPM Inc. Thus private modules obviously can't be accessed from there.

We are still looking for a workaroud to download private modules while this Australia-only outage is ongoing.

**Comment by seldo** [comment]
A workaround exists to point directly at a US PoP (the problem is with our CDN, not the registry itself): https://twitter.com/aredridel/status/643244115178745856

> set your hosts file to point http://registry.npmjs.com to 23.235.39.162 -- A US POP.

We are actively working on fully resolving the problem; updates are at http://status.npmjs.org/incidents/dhh4s6xdzdl4

**Comment by koresar** [comment]
Thanks for the workaround. Closing this issue then.
Cheers mate :)

**Comment by othiym23** [comment]
Yes, as I said [on Twitter](https://twitter.com/othiym23/status/643242424555298816), registry.npmjs.eu is a convenience set up by @mmalecki in the Before Times to help distribute the load of the old npm registry architecture for Europeans; it's never been modernized (and I believe Maciej is in the process of gradually winding it down), and as a result lacks the ACLs and other infrastructure services required to offer private packages. It doesn't really matter, because we do have CDN nodes in Europe, as well as a pretty much brand-new European DC built on top of AWS. That said, that doesn't help Australians much, so @aredridel's workaround, mentioned by Laurie above, is probably the best solution until we get things sorted out with our CDN.
