### ISSUE TITLE
Config with environment variables in .npmrc get destroyed

### ISSUE THREAD

**Issue by yamlfd** [npm/npm#9582]
Run 

```
npm config set prefix ${PROGRAMDATA}\npm
npm config set cache ${LOCALAPPDATA}\npm-cache
```

and you end with

```
prefix=C:\ProgramData\npm
cache=${LOCALAPPDATA}\npm-cache
```

If you run just the first command the file looks like

```
prefix=${PROGRAMDATA}\npm
```

It looks like the second command causes an EVAL on the content of the ".npmrc" file.

**Comment by meyian** [comment]
I'm unable to replicate the issue, instead, I see something else that might be wrong. I ran 
`npm config set prefix ${PROGRAMDATA}\npm`
and then ran
`npm config list`
it shows
`prefix = "/Users/abudu_h/Library/Application Support/Google/Chrome/Default/npm"`
and in .npmrc, prefix is now
'prefix=npm'

I'm not sure if ${PROGRAMDATA}, and ${LOCALAPPDATA} are Windows specific, but on my Mac, those variables are empty.

Now, if I try running  

`npm config set cache ${LOCALAPPDATA}\npm-cache`

.npmrc looks like

`prefix=/Users/abudu_h/Library/Application Support/Google/Chrome/Default/npm
cache=npm-cache`

And npm config list shows the two variables as

`cache = "/Users/abudu_h/Library/Application Support/Google/Chrome/Default/npm-cache"
prefix = "/Users/abudu_h/Library/Application Support/Google/Chrome/Default/npm"`

When I delete the cache and prefix variables, and try the npm config set commands in a different location, the "/Users/abudu_h/Library/Application Support/Google/Chrome/Default" is replaced with the current working directory.

This could be another bug. Could someone kindly let me know what the expected behavior for the

`npm config set prefix ${PROGRAMDATA}\npm
npm config set cache ${LOCALAPPDATA}\npm-cache`

commands is.

**Comment by yamlfd** [comment]
Sure `${PROGRAMDATA}` and `${LOCALAPPDATA}` are windows specific.

Running
```
npm config set prefix ${PROGRAMDATA}\npm
npm config set cache ${LOCALAPPDATA}\npm-cache
```

should end with a file:
```
prefix=${PROGRAMDATA}\npm
cache=${LOCALAPPDATA}\npm-cache
```
