### ISSUE TITLE
[idea] Rename node_modules to npm_modules

### ISSUE THREAD

**Issue by trusktr** [npm/npm#9625]
After all, since NPM isn't the "Node Package Manager" why not rename node_modules to npm_modules, and be agnostic of Node.js?

**Comment by othiym23** [comment]
The spelling of `node_modules` is as close to canon law as there is in the npm and Node worlds, which is why the single longest answer in the npm FAQ deals with exactly this question. It would be a monumental migration effort for extremely minimal gain, and the community has much more important problems to solve.
