### ISSUE TITLE
README.md not parsed correctly

### ISSUE THREAD

**Issue by thebergamo** [npm/npm#9646]
Hi, when I publish any of my projects in Github de README.md is correctly and pretty, but when I see the version on NPM my README.me not show the `###Title` correctly. Why this occurs?

**Comment by othiym23** [comment]
The Markdown renderer used by [the npm web site](https://github.com/npm/newww) (which is where this issue belongs, but I can answer this here no problem) is stricter about following CommonMark than GitHub's, and so follows the spec's requirement that there be a space between the header hashes and the title: `### Title`. It would be easier for everybody if npm and GitHub used the same rendering pipeline, but we're a ways out from that, because a _lot_ of stuff happens to your Markdown before it hits a web page, in both cases.

**Comment by thebergamo** [comment]
@othiym23 thanks for your answer =D
