### ISSUE TITLE
Migration to npm 3

### ISSUE THREAD

**Issue by ngerritsen** [npm/npm#9650]
Hey guys,

When migrating to npm 3, the peerDependencies are not automatically installed anymore. But a normal sized project has a lot of modules and an exponentially growing amount of peer dependencies. That would mean that you manually have to install all dependencies for your modules, which can be potentially be tenths or hundreds of modules!

Is there any migration path to follow? Maybe a command to automatically install all peerDependencies. There is also no distinction then between the modules you actually want and the peerDependencies of those modules, which will make you dependencies hard to maintain.

Kind regards,

Niels

**Comment by pcvandamcb** [comment]
I'm running into the same issue. Upgraded Node/NPM by installing the latest version from the site and apparently that also gives you NPM3 that no longer automatically installs peerDependencies.

My current projects do not update cleanly anymore. I understand I have to manually install the dependencies but sometimes this means installing dozens of packages. I can't imagine this being the normal way to install packages from now on. Also it makes it really hard to see what actually are peer dependencies and what are the actual packages that I need for my project.

Am I missing something here? I can't find any documentation on the subject. A migration guide for existing projects and some real world scenario's would be nice.

**Comment by emanb29** [comment]
This is also an issue with just a new "npm install" command, especially for things with many peerDependencies such as yeoman generators. I've seen this suggested elsewhere, but what about a --peer or --peers flag to indicate that peerDependencies should automatically be installed? I have personally just spent over 2 hours hunting down peerdependencies through many many packages (because, of course, packages depend upon packages depend upon...) and I feel that the removal of peerdependencies automation was a huge mistake. However, since it seems to be mostly supported by the community, why not a flag to appease those with projects such as mine?

**Comment by othiym23** [comment]
See #11213 for the team's resolution of this, which is that we don't have the time or cycles to work on it ourselves, but we'd be happy to land a patch that adds some functionality to ease working with `peerDependencies` in `npm@3`, or somebody could write a migration script to automate moving packages from `npm@2`-style peerDependency behavior to explicit dependencies. Thanks for your time!
