### ISSUE TITLE
dist-tags missing: `v3.x-next` and `3.x-latest`

### ISSUE THREAD

**Issue by ljharb** [npm/npm#9655]
Per advice from `npm` folks, for months I used these dist-tags in my package.json.

Now they appear to have been deleted.

Whether these are restored or not isn't that important (I think they should be) - a larger question is, if these can be deleted (as opposed to, say, just getting shunted to "latest"), why would anyone ever want to use them? Or, should a huge warning sign be included whenever someone is recommended to use it, that the tag may go away at any time? (Had I known that, I wouldn't have done nearly as much npm 3 testing over the past X months)

**Comment by othiym23** [comment]
Sorry for moving your cheese, Jordan. We'll probably put these back soon, and then give people more of a warning before we clean up `dist-tags` in the future. Making `dist-tags` unremovable is an interesting idea, but I think that would end up creating a fair amount of support overhead, because I think relatively few people would expect npm to do something so surprising.

**Comment by ljharb** [comment]
Thanks, I do love my cheese.

What if, however, "removing" a dist-tag could just set it to "latest" instead? At least that way, `npm install` wouldn't fail.

**Comment by othiym23** [comment]
@ljharb That seems kinda... magical? to me. Either way, this is an idea for the registry team to look at, so @ceej would probably need to find somebody on that side to weigh in on the feasibility / usability of something of that sort.

**Comment by iarna** [comment]
Hey, sorry about that. I've put them back!!

To my mind they were an interactive label, and scripts would use semver. But it's veeery clear that that isn't how many people understood them. =D
