### ISSUE TITLE
Strict version name checking on old version

### ISSUE THREAD

**Issue by jdassonvil** [npm/npm#9657]
Hello folks,

I'm trying `npm@3`and end up with the following error (for a project that were perfectly installed with `npm@2.X`).

```
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.3

npm ERR! Invalid Version: 1.0.5beta
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/workspace/mts-laposte-facteo-merchant-server-node/app/npm-debug.log
```

Here you can find the full npm debug log: https://gist.github.com/jdassonvil/15c9280d09a0d504b32b

It looks like the version naming is more strict than it used be, which I think is a good thing.  
But this is also applied to old version names from npm registry. For instance I think this install crash because there is a `1.0.5beta` version of `handlbars` in the npm registry, and this even if I use the version `3.0.3` in my project.

**Comment by yodeyer** [comment]
:+1:

**Comment by othiym23** [comment]
Hi! I dug into this, and you're right that it's a bug, but it's a bug that should be encountered relatively rarely, because at some point in the past the primary registry (registry.npmjs.org) was cleaned up so that all of the semver returned by it is valid. That makes this an interoperability concern, because it appears that sinopia is happy to return version strings that _aren't_ valid semver. This _could_ be considered a bug in sinopia, but this is also something the CLI should handle more gracefully.

**Comment by othiym23** [comment]
Here's what happens when I install `handlebars@1.0.5beta` from the primary registry:
```
bauchelain% npm -v
3.3.3
bauchelain% npm i -S handlebars@1.0.5beta
test-handlebars-1.0.5beta@1.0.0 /Users/ogd/Documents/projects/npm/test-handlebars-1.0.5beta
└─┬ handlebars@1.0.5-beta
  ├─┬ optimist@0.3.7
  │ └── wordwrap@0.0.3
  └── uglify-js@1.2.6

npm WARN EPACKAGEJSON test-handlebars-1.0.5beta@1.0.0 No description
npm WARN EPACKAGEJSON test-handlebars-1.0.5beta@1.0.0 No repository field.
```

Note that npm has loosely interpreted the requested version and actually installed `handlebars@1.0.5-beta`.

**Comment by gajjargaurav** [comment]
@othiym23  Thanks a lot as you saved us a lot of time
