### ISSUE TITLE
Downside to an entirely flat node_modules folder?

### ISSUE THREAD

**Issue by trusktr** [npm/npm#9660]
What are the downsides to having an entirely flat `node_modules` folder (even for dependency forks)?

**Comment by othiym23** [comment]
It will cause dependency hell, because it's very easy (in fact, likely, given the complexity of modern Node apps) to end up with a situation where multiple semver-incompatible version ranges of a single package are depended upon by other packages, and there's no safe, general way to resolve those incompatibilities while enforcing total flatness. We have [an area of focus](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-browser-dependencies) in the npm road map to talk about creating a fully flat installer for assets intended to be published to the web, but that will install somewhere other than `node_modules`.

**Comment by trusktr** [comment]
@othiym23 What about having folder names like `foo@1.2.3` in the totally flat structure? It seems like when there's a dependency fork, npm just installs those deps one level deeper than the root level (in the packages that need the incompatible ranges), but ultimately, what gets installed in the next level down is a specific version of a package, so wouldn't appending the version to the package name solve that problem? I noticed that's what JSPM does, and it seems to work just fine.

**Comment by othiym23** [comment]
Yes: it would either require changes to the Node module resolution algorithm, or it would require the use of symbolic links. The first is highly unlikely to happen because of the giant break with backwards compatibility it would represent, and the second would cause tremendous technical difficulties in environments like Windows, and Vagrant instances hosted on folders shared with Windows. This is something that's been discussed many times in the past, and at this point, I think everybody on the npm team considers it a settled topic: we're going to stick with nested `node_modules`, and take advantage of things like deduplication when we can.
