### ISSUE TITLE
npm v3.3.3 - Git `dependency` name !== package.json name → silent failure to install

### ISSUE THREAD

**Issue by neophob** [npm/npm#9661]
Example package.json:

```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "unofficial-nodejs-nest": "neophob/unofficial_nodejs_nest"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

when I run `npm install` nothing happens:

```
> npm install
npm WARN EPACKAGEJSON test@0.0.1 No description
npm WARN EPACKAGEJSON test@0.0.1 No repository field.
npm WARN EPACKAGEJSON test@0.0.1 No license field.

> ls -al node_modules/
total 0
drwxr-xr-x  2 me  staff   68 Sep 18 21:35 .
drwxr-xr-x  4 me  staff  136 Sep 18 21:31 ..
```

I don't see an error but I also don't see the module. Worked for npm 1.x and npm 2.x.

Installing the package manually works btw:

```
npm install neophob/unofficial_nodejs_nest
test@0.0.1 /Users/me/tmp/npm
└── unofficial-nest-api@0.1.6  extraneous (git://github.com/neophob/unofficial_nodejs_nest.git#add5b651a8c7f12f6b8052d2d2fbffdd1844f152)

npm WARN EPACKAGEJSON test@0.0.1 No description
npm WARN EPACKAGEJSON test@0.0.1 No repository field.
npm WARN EPACKAGEJSON test@0.0.1 No license field.

> ls node_modules/
unofficial-nest-api
```

**Comment by neophob** [comment]
npm list after the manual installation:

```
> npm list
test@0.0.1 /Users/me/tmp/npm
├── unofficial-nest-api@0.1.6 (git://github.com/neophob/unofficial_nodejs_nest.git#add5b651a8c7f12f6b8052d2d2fbffdd1844f152)
└── UNMET DEPENDENCY unofficial-nodejs-nest@github:neophob/unofficial_nodejs_nest

npm ERR! missing: unofficial-nodejs-nest@github:neophob/unofficial_nodejs_nest, required by test@0.0.1
``` 

the only difference I see is the URL "git://github.com/neophob/unofficial_nodejs_nest.git" vs "github:neophob/unofficial_nodejs_nest".

might be related to #9652

**Comment by othiym23** [comment]
Here's what's going on: In `npm@3`, the installer builds an ideal tree, compares it to the actual tree on disk, and then generates a set of operations to turn the actual tree into something that looks a lot more like the ideal tree. The bug is that when you have a hosted Git dependency that has a name in its `package.json` (in this case, `unofficial-nest-api`) that differs from the name you've used in _your_ `package.json` (in this case, it's `unofficial-nodejs-nest`), npm builds and installs the Git package, and then immediately removes it from the package tree as redundant. It should _instead_ notice the mismatch between package names and either error or update the ideal tree and warn about the name change. The workaround is to change what you have in your `dependencies` to `"unofficial-nest-api": "neophob/unofficial_nodejs_nest"`.

@iarna, is this description of the underlying issue correct?

**Comment by neophob** [comment]
Thanks @othiym23 - the workaround worked fine!
