### ISSUE TITLE
Package installed twice (in my node_modules) and in node_modules of another package my package depends on

### ISSUE THREAD

**Issue by hgezim** [npm/npm#9662]
I had `react` and `react-bootstrap` in my dependencies (amongst other things):

    "dependencies": {
        "react": "0.13.3",
        "react-bootstrap": "0.25.2"
    }

NPM ended up installing react for my package as well as for `react-bootstrap`:

    $ npm ls | grep react
    │ │ ├── babel-plugin-react-constant-elements@1.0.3
    │ │ ├── babel-plugin-react-display-name@1.0.3
    │   ├── babel-plugin-react-constant-elements@1.0.3
    │   ├── babel-plugin-react-display-name@1.0.3
    │ │ ├── babel-plugin-react-constant-elements@1.0.3
    │ │ ├── babel-plugin-react-display-name@1.0.3
    ├─┬ react@0.13.3
    ├─┬ react-bootstrap@0.25.2
    │ ├─┬ react@0.13.3
    │ ├─┬ react-overlays@0.4.4
    │ │ ├── react-prop-types@0.2.2
    ├─┬ react-router@1.0.0-rc1

Since these two packages were conflicting, I removed `react` in `react-bootstrap`:

    $ rm -rf node_modules/react-bootstrap/node_modules/react

I thought this was easily reproducible but running `npm install` again, didn't show me the same results:

    $ npm ls | grep react
    │ │ ├── babel-plugin-react-constant-elements@1.0.3
    │ │ ├── babel-plugin-react-display-name@1.0.3
    │   ├── babel-plugin-react-constant-elements@1.0.3
    │   ├── babel-plugin-react-display-name@1.0.3
    │ │ ├── babel-plugin-react-constant-elements@1.0.3
    │ │ ├── babel-plugin-react-display-name@1.0.3
    ├─┬ react@0.13.3
    ├─┬ react-bootstrap@0.25.2
    │ ├─┬ react-overlays@0.4.4
    │ │ ├── react-prop-types@0.2.2
    ├─┬ react-router@1.0.0-rc1

**Comment by othiym23** [comment]
What version of npm were / are you running?

**Comment by hgezim** [comment]
I have version `2.14.2`.

**Comment by othiym23** [comment]
In the case of `npm@2`, this is normal and expected behavior: my guess is that you (or npm) originally installed `react-bootstrap` before `react`, and the `npm@2` (and earlier) installer doesn't automatically deduplicate on install the way `npm@3` does. You would have gotten the same tree (with only one copy of react) if you'd run `npm dedupe` as well.

This wouldn't be an issue if React weren't so insistent on there being only one copy of itself in the package tree, which I believe they're working on fixing (via a redesign) right now. In the meantime, try upgrading to `npm@latest` (which as of now is `npm@3.3.3`) and either running `npm dedupe` or deleting `node_modules` and reinstalling, which will give you much the same results. Good luck!

**Comment by hgezim** [comment]
@othiym23, awesome explanation. Thank you!
