### ISSUE TITLE
npm 3.3.3 installs submodule dependencies in the root node_modules folder

### ISSUE THREAD

**Issue by jorisvervuurt** [npm/npm#9675]
As described in the title, npm 3.3.3 installs dependencies of submodules in the root node_modules folder.
This of course is NOT what should happen!

**Comment by othiym23** [comment]
If you take a look at the [release notes for 3.0.0](https://github.com/npm/npm/releases/tag/v3.0.0) (the section entitled "flat, flat, flat"), this behavior is exactly what npm is supposed to be doing, and is one of the major new features in npm 3. The flatter, largely deduplicated tree uses less space and is much friendlier to Windows users. npm is still aware of the dependency tree structure, because it adds metadata to packages when they're installed that tells it how they're related. Run `npm ls`, and you'll get the same hierarchical tree. Play around with it a little and it should make sense.

**Comment by jorisvervuurt** [comment]
Hmm, sorry, didn't see that.
To be honest, this is really going to be something I'll have to get used to.
