### ISSUE TITLE
npm install git+ssh://.... --save problem

### ISSUE THREAD

**Issue by mpr0xy** [npm/npm#9679]
i use npm 3.3.3

when i  run  

```
npm install git+ssh://....  --save
```

the package.json file add this dependencies is "ssh://...."  git+ is disappeared

then i run npm update or npm install when the dependencies is update. npm say the ssh://... url is  unsupported.

**Comment by JakeChampion** [comment]
Can confirm this happens in latest stable npm

**Comment by mpr0xy** [comment]
when I use Mac, not this issue

**Comment by lc60005457** [comment]
I closed my same issue. mac, npm v3.3.0/v3.5.0

**Comment by tomekwi** [comment]
Extra info:

Even if you write a `git+ssh://…` URL in your `package.json`, `npm run shrinkwrap` still saves the dep as `ssh://…`.

That results in a pile of crap afterwards:

```sh
$ npm install
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
npm ERR! git clone --template=/… --mirror ssh://… /…/ssh-…: Please make sure you have the correct access rights
```

**Comment by gagern** [comment]
The `git+` is vanishing [here](https://github.com/npm/npm-package-arg/blob/383b4783a076b825815be51eb1ab2e4bb8a1e1fc/npa.js#L154) in `npm-package-arg`.  For me, one effect is that I can't do a `npm install git+ssh://localhost/path/to/some/repo.git` since I get `Error: Unsupported URL Type` here:

```
npm verb stack Error: Unsupported URL Type: ssh://localhost/…
npm verb stack     at parseUrl (…/npm/node_modules/npm-package-arg/npa.js:169:13)
npm verb stack     at npa (…/npm/node_modules/npm-package-arg/npa.js:75:12)
npm verb stack     at isProdDep (…/npm/lib/install/deps.js:58:10)
npm verb stack     at isDep (…/npm/lib/install/deps.js:38:19)
npm verb stack     at addRequiredDep (…/npm/lib/install/deps.js:128:8)
npm verb stack     at …/npm/lib/install/deps.js:489:7
npm verb stack     at …/npm/node_modules/iferr/index.js:13:50
npm verb stack     at addBundled (…/npm/lib/fetch-package-metadata.js:231:39)
npm verb stack     at …/npm/lib/install/deps.js:476:5
npm verb stack     at …/npm/node_modules/iferr/index.js:13:50
```

The problem, in my opinion, is that the same package gets fed through `npa` twice. The first time, the URL is parsed correctly, the `git+` is stripped, and the remainder ends up in `spec`. Later on, the `spec` (instead of `rawSpec`) somehow ends up as the version (presumably for the same reason `--save` stores it that way) and that is combined with the name to cause the observed issue.
