### ISSUE TITLE
dedupe at install time

### ISSUE THREAD

**Issue by nickdesaulniers** [npm/npm#9699]
We have a project with a bunch of dependencies that themselves have lots of native add ons.  Most of these are shared, down to the exact version numbers.  `npm dedupe` works well, but has to be run after the fact (after install time).

Is it possible to specify during install time to dedupe, in order to cut down on install times when native addons are shared?

peerDependencies also seems to kinda work, but there's a deprecation warning?  Is the functionality currently supported?

**Comment by othiym23** [comment]
`npm@3` (which is now the default npm you get when you run `npm -g install npm`) installs maximally flat by default, as long as you're starting from no `node_modules`. If there _is_ a `node_modules` directory, `npm@3` will leave its structure as-is until you run `npm dedupe` (or delete `node_modules` and rerun `npm install`). This is because we didn't want to default to moving everybody's cheese at once, because @iarna and I decided that ops people and build managers would be totally grossed out if they ran a simple install and the entire structure of `node_modules` changed.

So, good news! If you want to take advantage of this new behavior, all you need to do is upgrade to the newest version of npm and do a new, clean install.

**Comment by nickdesaulniers** [comment]
right on, thanks for the info, Forrest, I appreciate it!
