### ISSUE TITLE
Use elegant-spinner

### ISSUE THREAD

**Issue by silvenon** [npm/npm#9709]
Current spinner feels gooey, [elegant-spiner](https://github.com/sindresorhus/elegant-spinner) seems much cooler :stuck_out_tongue:

**Comment by gillesdemey** [comment]
+1 is this something that the authors would be interested in, since it's so benign?

We also have to take Windows users into account, I'm not sure what the current behaviour is on Windows but they won't get the elegant spinner.

https://github.com/sindresorhus/elegant-spinner/blob/16a4079b7d6208959bb7e8801b95b7e87e0c4286/index.js#L4

**Comment by hashrock** [comment]
+1

**Comment by silvenon** [comment]
The new progress bar came with [v3.10.0](https://github.com/npm/npm/releases/tag/v3.10.0) with the suggested spinner! 🎉
