### ISSUE TITLE
npm ubuntu server 14

### ISSUE THREAD

**Issue by izakaria** [npm/npm#9712]
> node-sass@3.3.2 install /var/www/es/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: ENOENT, lstat '/home/izakaria/tmp/npm-15347-PE0oR34Z/1442935236114-0.763147855643183/package/external/cdnjs.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/es
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/izakaria/tmp/npm-15347-PE0oR34Z/1442935236114-0.763147855643183/package/external/cdnjs.json
npm ERR! fstream_path /home/izakaria/tmp/npm-15347-PE0oR34Z/1442935236114-0.763147855643183/package/external/cdnjs.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/es/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@izakaria A couple of things:

1. `npm@1.3.10` is very old and is riddled with so many bugs that support for it was dropped over a year ago. You really should [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to avoid receiving errors regarding race conditions like the one you are probably seeing now.
2. The Node.js binary on Debian is `nodejs` instead of `node`, so when `node-sass` wants to run `node scripts/install.js`, the command fails since there is no `node` binary on your system. This was a conscious decision made by the Debian maintainers, and said maintainers even patched `npm` to print the warning in your log:

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

Honestly, you are probably better off installing Node.js through [NodeSource's distribution](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-linux) instead of Debian's distribution. If you really don't want to do this, however, there is always [this solution](https://packages.debian.org/sid/nodejs-legacy) provided by Debian:

```
apt-get install nodejs-legacy
```

**Comment by izakaria** [comment]
thank you @KenanY

**Comment by ehsalazar** [comment]
@izakaria Are you back up and running? I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
