### ISSUE TITLE
"npm install --registry xxx yyy" not using xxx registry

### ISSUE THREAD

**Issue by yofreke** [npm/npm#9782]
I had to use the `--registry` option the other day, and found that it was not working.  This was what I discovered, wanted to raise an issue for it since the thread I put this on was a bit old.  I see that there was an update about a week ago, didn't look like it covered this though.

... Doing this made me realise that `npm install --registry` was not actually using the supplied registry.

    npm sill mapToRegistry name on-finished
    npm sill mapToRegistry using default registry
    npm sill mapToRegistry registry https://registry.npmjs.com/
    npm sill mapToRegistry uri https://registry.npmjs.com/on-finished
    npm verb addRemoteTarball http://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz not in flight; adding
    npm verb addRemoteTarball [ 'http://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz',
    npm verb addRemoteTarball   '20f1336481b083cd75337992a16971aa2d906947' ]

Changing lines [193-202 of add-named.js](https://github.com/npm/npm/blame/f18241032f7306ca9bf238c0eb909f65ae4ee58c/lib/cache/add-named.js#L193-L202) to be as follows:

    rp.path = tb.path
    rp.pathname = tb.pathname
    tb = url.format(rp)

Fixed the `npm install --registry` option, allowing me to use an alternate (presumably less visited, since i don't think the --registry option has worked since that blame in October) registry.

Excerpt from: https://github.com/npm/npm/issues/6451#issuecomment-140778232

**Comment by othiym23** [comment]
I'm not sure what you're expecting to happen here, but I'm not seeing unexpected or incorrect behavior. `registry.npmjs.com` and `registry.npmjs.org` both point at the primary npm, Inc. registry network. The canonical default registry is `https://registry.npmjs.org/`, even though the website is at `https://www.npmjs.com` for deeply unexciting historical and CDN-related reasons. Because the metadata for packages is in effect being redirected to the canonical registry domain, and the metadata it contains therefore points back to the canonical registry domain, that's where it's fetching the package tarballs from. That's why the log output above looks the way it does.

The more interesting question is why you want to override the default registry with an alternate that points to the same registry. Are you having connectivity issues? If so, either contact support@npmjs.com or open a new issue here describing your peoblem, and we'll see what we can do. For now, I'm going to close this, because I don't see a bug here.
