### ISSUE TITLE
Force npm 3 to install a node module always nested

### ISSUE THREAD

**Issue by Alphapage** [npm/npm#9809]
Hello,

npm 3 node modules installation is now flat.
I'm trying to build a frontend package, but this new feature breaks the import path in ES6.
With npm 2, all modules where nested except peerDependencies which could be set explicitly. It was very easy to find the path something like this:
```
import * from "mymodule/node_modules/mynestedmodule/file.js";
```

With npm 3, the path could be:
```
import * from "mymodule/node_modules/mynestedmodule/file.js";
```
or 
```
import * from "mynestedmodule/file.js";
```

This is a real problem to locate the package, so I think there is a need to be able to set "nestedDependencies" in package.json to find the frontend files.

Thanks in advance for your answers.

**Comment by othiym23** [comment]
When you say "in ES6," I'm guessing that you mean you're using babel or a similar ES6 transpiler. I mention this because the ES module loader spec isn't yet finished, and there isn't a standard implementation of it for Node (or any other JavaScript environment) yet, which that the behavior you're describing isn't defined by the ES standard. However, it seems unlikely that any implemented version of the spec will behave in a way surprising to users of the current Node require syntax, so I think(?) that what you're talking about is more about how Node module loading works than anything related to ES6.

The issue here is that this pattern relies on using the Node module resolution logic in a way that has never been guaranteed to be safe with npm. Using full paths to files could be broken at any time by users using `npm dedupe`, and so this isn't an issue that's new or exclusive to `npm@3`. The correct thing to do is to call `import * from 'mynestedmodule/file.js'`, and if you can't require `mynestedmodule` from the package trying to use it, that means the package in which that code is located should be explicitly depending on `mynestedmodule` itself.

To answer your original question, no, this behavior isn't configurable, and it's unlikely that it will be made configurable. We _are_ probably going to add a way to make it [easier to work with front-end dependencies using npm](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-browser-dependencies), but that work is still a little ways out (and is itself still undefined). Since this isn't something that's likely to change, I'm going to close this issue, but I'm happy to continue to discuss the specifics of what you're trying to do here or elsewhere. Thanks for your time!

**Comment by XadillaX** [comment]
BUT I NEED NESTED WAY! FLATTEN IS UGLY! I JUST HATE FLATTEN MODULE PATH! IT'S UGLY FOR ME!

How can I force install packages nested?

**Comment by xinyu198736** [comment]
when i install react-native module, i got 500 count directory under node_modules，then i install some third-party react-native plugin modules，now i don't know which is plugin and which is react-native's dependence ...

**Comment by othiym23** [comment]
@XadillaX If you want nested modules on disk, you can use `npm@2`, which is in LTS mode now, and will continue to receive support for critical issues, security fixes, backwards-compatible dependency updates, and registry compatibility for probably about as long as it's being included in Node LTS releases.

@xinyu198736 `npm ls` will reconstruct the logical dependency tree for you so you can see which packed are depended on by what; if you want to see that for a particular package, `npm ls <package>` will do that for you.

**Comment by XadillaX** [comment]
@othiym23 So the only way is to degrade NPM?

**Comment by othiym23** [comment]
@XadillaX That's correct. `npm@3` uses a new installer that instalks maximally flat (and dedupes) by default, which makes npm much less likely to cause problems for Windows users, and also uses significantly less disk space than older versions of npm for installs in many cases.

**Comment by othiym23** [comment]
I wouldn't use describe the `npm@2` experience as degraded, though. There are many new features in `npm@3`, and it's true you won't get those, but as I said above, new versions of `npm@2` will continue to be released for quite a while.

**Comment by XadillaX** [comment]
@othiym23 But why don't add `nested` as an optional parameter in `npm@3` CLI?

**Comment by othiym23** [comment]
Making that behavior switchable adds complexity and maintenance overhead to the installer, which is already the most complicated (and bug-prone and difficult to debug) part of npm, the new install algorithm has significant benefits for almost all users, and because we haven't yet seen a compelling use case for taking on the burden of dealing with that complexity.

**Comment by Alphapage** [comment]
npm3 flat installation is not a problem.
I only need "nestedDependencies" in package.json to force a module to be nested.

**Comment by XadillaX** [comment]
To be honest, flatten way is not convenient for us to debug `node_modules` path in editor. Sometime we need debug and make PR for some packages.

**Comment by othiym23** [comment]
@Alphapage In my original response to your issue, I outlined the reasons why I think the behavior you're asking for comes from what's at best a marginal assumption about how npm works. Do you have further information about your use case that could help me understand why you still think this is something npm should support?

@XadillaX I could use more context about the use case you're describing, as I'm having a tough time understanding why the flat layout causes problems for either debugging or fixing faulty packages. How does `npm ls <badly-behaved dependency>` not produce the information you need to create a PR?

**Comment by XadillaX** [comment]
@othiym23 I mean in my editor, like VIM or sublime. Imagine that you open `node_modules`, 500+ directories appeared.

**Comment by XadillaX** [comment]
@othiym23 But Node.js 5 is using npm 3! So the only way is to degrade the version of `npm` manually?

**Comment by lawlesscreation** [comment]
@XadillaX probably a good idea to use something like [NVM)]https://github.com/creationix/nvm). That will help managing your Node versions a lot easier (esp. on a per-project basis)

**Comment by derekargueta** [comment]
@othiym23 out of curiosity (I'm pretty new to Node) how would it be handled if 2+ dependencies require <i>different versions</i> of the same dependency?

**Comment by othiym23** [comment]
@derekargueta In that case, each dependency with a conflicting version on the same dependency would get its own, nested copy of that conflicting dependency. That's why we describe the install tree as _maximally_ flat – it will still allow nesting in the case of conflicts.

**Comment by kburson** [comment]
I tried to upgrade to the latest Node, which upgraded my npm to version 3.x, but then my application would no longer compile.  Most of my package dependencies fail because they are following the old rules.  This forces me to lock down to Node 12.x and NPM 2.x, which is sad.

I do not know how long it will take the various tool and package owners to update their packages to use the current reference pattern, but until then I cannot adopt NPM 3, or Node 4+  8-(

I am always looking for a workaround, if one become available in the interim...  Do you know any?

**Comment by pfumagalli** [comment]
@kburson: as _root_ I simply do `npm install -g 'npm@<3'` on my system every time I a new version of Node comes out; your mileage might vary, but it's fairly trivial to "downgrade" :-)

**Comment by scamden** [comment]
@othiym23 how would you handle the use case of referencing a scss or css file from a library without using paths? unless you are using a tool like browserify and a transform like sassify you can't require sass files, so we reference them via path in our root .scss file

**Comment by calidion** [comment]
npm3 can default to flat, but should provide a way to enabled intended nesting.
an new option ins package.json will solve this problem i think.
Extreme on both nested and flat is not a good idea.

**Comment by jasuperior** [comment]
I agree... We need a way to decoratively say whether a module is nested or not. IT has completely broken my module since the update because one of my dependencies uses a dependency which was constructed wierdly where it is referencing itself in its node_modules. 

REFERENCE: [Proteus](https://github.com/jhamlet/proteus) 

what i am assuming is happening is that when It is installing the package, it looks at proteuses node_modules and overwrites its main folder because they share the same name. 

I know this is a problem with the developer of this module, however, there may be more libraries which have similar issues and not being able to declare that i want it to install nested, makes for alot of headache.

**Comment by tqwhite** [comment]
This is an appalling change. Having to scroll through a hundred folders to find the one I want to work on is maddening. While I can't actually understand how a large project benefits from this change, I don't work on large projects. The thread above where (I won't insult him by highlighting his name) ignores the explanation of a frustrated user and explains how making it able to work the way WE HAVE ALL BEEN WORKING FOR YEARS is too much trouble reveals an arrogant disregard for the community that is infuriating. 

But, oh!, it's ok. "You can jump off the main development stream. No. You won't get the latest tools but you will be able to keep your petty preferences intact."

I remember feeling this way when PHP made irrevocable changes. I am agonized to find that the operators of NodeJS, having consolidated into a new 'democratic' organization, are now behaving with the same autocratic carelessness of every other group of power mad elites I've ever seen.

**Comment by calidion** [comment]
I think very few modules should be awared of it's update which would be better flat installed.
to most modules, we don't need to waste time focus on their updates while we are busy fixing bugs or developing new features,
and they should be nested and keep out of it's update.

I think we use npm to ease the way we develop and save more time for living, not to be dragged by the updates of the  packages, and waste time keep up with the updates.

**Comment by johnamiahford** [comment]
I'm not sure of others workflow, but shouldn't we do an `npm link path-to-package` to work on our node_modules dependencies rather than jumping in the `node_modules` directory? 

As far as this question from @jasuperior:

> We need a way to decoratively say whether a module is nested or not. IT has completely broken my module since the update because one of my dependencies uses a dependency which was constructed wierdly where it is referencing itself in its node_modules.

That sounds like a problem that should be addressed.

**Comment by chaddjohnson** [comment]
This change in NPM 3 **completely breaks** use of [parent-require](https://www.npmjs.com/package/parent-require) for requiring mongoose.

I have a package shared between multiple internal projects, and my data models are shared via one of those projects; thus, I have to use parent-require to pull in mongoose. With NPM 2, the parent-require Node module was installed in a nested node_modules directory; now, with NPM 3, it's installed in the top-level node_modules directory, and now I get this error:

```
/Users/chad/development/web/rpc/commonapi/node_modules/parent-require/index.js:8
  throw new Error("Cannot find module '" + id + "' from parent")
  ^

Error: Cannot find module 'mongoose' from parent
    at module.exports (/Users/chad/development/web/rpc/commonapi/node_modules/parent-require/index.js:8:9)
    at Object.<anonymous> (/Users/chad/development/web/rpc/commonapi/node_modules/APIUtil/lib/models/authorization.js:13:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/chad/development/web/rpc/commonapi/config/dbModels.js:3:21)
    at Module._compile (module.js:410:26)
```

This really sucks.

**Comment by VitaliyAT** [comment]
I just install gulp-util and got "too long path name" in windows because depth of it is amazing. Is it possible regulate somehow? maybe reformated utility or something? Some "Direct installed" and "dependencies" folders. I need more flat view. I understand that it's killing, but OS restrictiion don't give me live in 2016.

**Comment by kahboom** [comment]
If the npm dependency has a shrinkwrap file, npm3 will respect it and create a nested directory of sub-dependencies within it. Having said that, @othiym23 is right, relative paths are just bad practice for npm -- unless you are serving completely static assets from a dependency. It is better to allow npm to do a lookup, which is one of its core features and makes npm2 and npm3 installed dependencies "backwards compatible" if you reference them properly in your app: https://nodejs.org/api/modules.html#modules_addenda_package_manager_tips

**Comment by akashdeep-singh** [comment]
I second the need of npm2 style nested dependencies as an optional switch.
While I totally get why npm3 does what it does, I don't understand why the developers would sidelines all the use-cases that npm2 catered to.
I use `npm pack` to package my apps, and then use `npm install <xyz>.tgz` to install the .tgz on target machines.
Earlier, this worked perfectly. The `npm install` command would explode the tgz inside a root node_modules directory, name it properly, then go ahead and install its dependencies **inside** the app directory because _nested_. But, now instead of installing the deps of my app inside the app directory, I end up having a huge list of deps installed in my root node_modules, and my app is one of them. Its own dependencies are now at the same level as the app, so they are not really deps anymore. This is frustrating, since I need to degrade to npm2 for `npm install`. I switched from npm2 to npm3 because of a bug in npm2 that sometimes leaves out my app.js or index.js during `npm pack`.

**Comment by calidion** [comment]
npm3 may be the most stupid thing ever happened in nodejs.

**Comment by skerit** [comment]
Tree flattening is one thing, automatically deduping is another.

Certain (self-made) modules in my `node_modules` folder are symlinks, so I can code more easily. These modules can be used in several projects, so they all point to the same folder, but when doing an npm install now it will actually dedupe the node_modules inside those symlinked folders.

So, depending on from where I run `npm install` a dependency will disappear from that symlinked module, causing it to break somewhere else.

I found the "Please move your git repository out of the way" errors quite annoying, but they can be worked around. This is just awful.

**Comment by XadillaX** [comment]
So does NPM4 support nested?

**Comment by steelbrain** [comment]
I have found that `--global-style` has a similar effect, doing `npm install express --global-style` installs all the dependencies of express in it's `node_modules`, I'm on npm v4.2.0

**Comment by rwaldron** [comment]
Forced flat installation breaks Tessel 2's .tesselignore and .tesselinclude feature, which is expected to respect the rules defined in those files for all dependencies in node_modules. This:

> This is a real problem to locate the package, so I think there is a need to be able to set "nestedDependencies" in package.json to find the frontend files.

is exactly what is needed to address the problem.

**Comment by rwaldron** [comment]
Alternatively: some way for module authors to explicitly say "this module must be installed with `global-style: true`"

**Comment by sixcircuit** [comment]
The installer already does nested installs in the case of a conflict. You're already supporting that code. if(conflict || user_flag){ nest_it(); }
