### ISSUE TITLE
The --production flag is not mentioned by documentation for "npm start"

### ISSUE THREAD

**Issue by k-j-kleist** [npm/npm#9811]
This issue is practically identical to #4009

I assume that the only thing the "--production" flag does is setting NODE_ENV to "production"?

**Comment by KenanY** [comment]
@k-j-kleist Yeah, for scripts it just sets `NODE_ENV="production"`

While I am _not_ against adding more documentation, I do however think that since the `production` config affects all scripts I think it is better off documented in [`npm-scripts(7)`](https://docs.npmjs.com/misc/scripts), if at all. Alternatively, we could just leave everything how it is now and argue that it really does not affect scripts in a immediately-practical way like `npm install --production` does.

**Comment by othiym23** [comment]
I agree with @KenanY – this isn't something that needs to be documented for `run-scripts` in particular, especially because I think relatively few people actually use it with `npm start`. That said, at some point in the future we may break up the monolithic config documentation, because I'm not sure that the current form of that documentation is usable. Until then, though, things are functioning as intended.
