### ISSUE TITLE
Use native-builder instead of node-gyp

### ISSUE THREAD

**Issue by noamokman** [npm/npm#9822]
Hi there!
A small feature request / debate.

My team and I are working on a project named [native-builder](https://github.com/nachos/native-builder) :hammer: 

What it basically does is help native modules developer build their projects to what ever engine the package needs to be build for.

For example,
Your building a project running under [electron](http://electron.atom.io/).
Package `A` is a native package.
Package `B` is not a native package but it depends on package `A`.

When you install package `B` you need to know that it has a dependency on package 'A',
So something like this
``` bash
npm i
cd node_nodules/B/node_modules/A
HOME=~/.electron-gyp node-gyp rebuild --target 0.30.0 --dist-url=https://atom.io/download/atom-shell
```

To solve this problem we came up with native-builder that uses node-gyp and supports nw and electron.
However to [use it](https://github.com/nachos/native-builder#installation) you must:
*  Add this package as a dependency
``` bash
$ [sudo] npm install native-builder --save
```
* Add an install script
``` json 
{
  ...
  "scripts": {
    "install": "native-builder build"
  }
}
```

What if the defualt install script in npm would use native-builder instead?
It would solve this problem, for every package, immediatly.

So what do you think? :smile: 

P.S.
I am more than willing to start working on a pull request.
Also there is some work left on our package as well.

**Comment by othiym23** [comment]
I have no question but that the native build experience for Node could be improved tremendously. I don't see a really clear statement of what problem you're trying to solve with `native-builder`, but going by description of what it does, I'm going to guess that it makes working with native dependencies much simpler for embedders of Node like electron and nw. To me, it sounds like the changes it makes are changes that should probably be landed in `node-gyp`.

I don't want to just add another layer of intermediation between users of npm and `node-gyp`, because that makes it tougher for us to keep things up to date for Node users (because now another stakeholder is involved when upgrades to `node-gyp` drop). I think the best way for you to proceed is to try to get the changes in `native-builder` accepted upstream to `node-gyp`. If that doesn't seem like you're going to be able to get the necessary traction with `node-gyp`'s maintainers, put together a PR and come back to us. Thanks for bringing this up!

**Comment by noamokman** [comment]
You're right.
Thanks for the time, I'll try to suggest something to the node-gyp maintainers. :smile:
