### ISSUE TITLE
Problem install ionic with npm

### ISSUE THREAD

**Issue by amezdari** [npm/npm#9825]
Hi,
I want to install ionic with : 
npm install -g ionic
 but i have this message :
```
npm ERR! Linux 3.2.0-39-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ionic"
npm ERR! node v0.6.12
npm ERR! npm  v3.3.5

npm ERR! Object #<Object> has no method 'exists'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/linux-sysalia6/npm-debug.log
npm ERR! code 1
```

thx!

**Comment by KenanY** [comment]
@amezdari So, your `npm` version is very new, but your Node.js version is _very_ _very_ _very_ old. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) first. Node.js v0.6 is no longer supported.

**Comment by othiym23** [comment]
Closing as resolved. As @KenanY said, the CLI team officially dropped support for 0.6 over a year ago, and npm is unusually serious about backwards compatibility, so you're likely to run into other issues with packages you install due to having such an old Node. Especially if you want to use Ionic, you're going to need to upgrade. Good luck!

**Comment by amezdari** [comment]
ok thx ! its good thank you!
