### ISSUE TITLE
Use "table" package instead of "text-table"

### ISSUE THREAD

**Issue by gajus** [npm/npm#9842]
https://github.com/gajus/table package is a very modular, well documented and well tested module/function for generating text tables. It allows granular customisation of how table contents is aligned, text wrapping, text truncation, border style and text padding.

If accepted, I will happily create a PR.

**Comment by othiym23** [comment]
Good job! `table` looks nice.

Is there something wrong with the way tabular data is laid out by npm right now? As nice as your package is, I'd rather avoid the churn of switching out a dependency unless there's good reason to switch.

**Comment by gajus** [comment]
@othiym23 I cannot give a better argument than a well maintained codebase. : )

**Comment by othiym23** [comment]
I don't think @substack has made many changes to `text-table` because he hasn't needed to, and it works well for the (relatively limited) use cases we have for it. Thanks for offering to make us a patch, but like I said, I do like to keep dependency churn to a minimum, so I don't think this is a necessary change.

**Comment by gajus** [comment]
No worries. I will get back to this in case I ever see an actual issue with the tabular data in NPM.
