### ISSUE TITLE
npm install --prefix <module-name> : behavior differ between 2.x and 3.x

### ISSUE THREAD

**Issue by Unitech** [npm/npm#9852]
## NPM 2.x

```bash
$ npm -v
2.11.3

$ npm install --prefix /tmp/v2 pm2-server-monit 
pm2-server-monit@0.13.0 ../../tmp/v2/node_modules/pm2-server-monit
├── cpu-stats@1.0.0
├── shelljs@0.5.3
└── pmx@0.5.5 (json-stringify-safe@5.0.1, debug@2.2.0)
```

In the the /tmp/v2/node_modules I get this:
```
$ ll /tmp/v2/node_modules/
total 4,0K
drwxrwxr-x 4 shant shant 4,0K oct.   6 11:08 pm2-server-monit
```

## NPM 3.x

```bash
$ npm -v
3.3.5

$ npm install --prefix /tmp/v3 pm2-server-monit 
/tmp/v3
└─┬ pm2-server-monit@0.13.0 
  ├── cpu-stats@1.0.0 
  ├─┬ pmx@0.5.5 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ └── json-stringify-safe@5.0.1 
  └── shelljs@0.5.3 

npm WARN ENOENT ENOENT: no such file or directory, open '/tmp/v3/package.json'
npm WARN EPACKAGEJSON /tmp/v3 No description
npm WARN EPACKAGEJSON /tmp/v3 No repository field.
npm WARN EPACKAGEJSON /tmp/v3 No README data
npm WARN EPACKAGEJSON /tmp/v3 No license field.
```

In the the /tmp/v3/node_modules I get this:

```bash
$ ll /tmp/v3/node_modules/
total 28K
drwxrwxr-x 4 shant shant 4,0K oct.   6 11:09 cpu-stats
drwxrwxr-x 2 shant shant 4,0K oct.   6 11:09 debug
drwxrwxr-x 3 shant shant 4,0K oct.   6 11:09 json-stringify-safe
drwxrwxr-x 2 shant shant 4,0K oct.   6 11:09 ms
drwxrwxr-x 3 shant shant 4,0K oct.   6 11:09 pm2-server-monit
drwxrwxr-x 5 shant shant 4,0K oct.   6 11:09 pmx
drwxrwxr-x 5 shant shant 4,0K oct.   6 11:09 shelljs
```

Is it a planed breaking change for npm 3.x ?

Thank you

**Comment by othiym23** [comment]
It's not exactly a breaking change (unless code is making assumptions it probably shouldn't be about how modules are laid out), but [it is intentional](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat), and one of the chief features of the new installer in `npm@3`. In effect, running `npm install` with `npm@3` on a new directory is the same as running `npm install && npm dedupe` with older versions of npm – it will install maximally flat trees, only nesting modules when there are semver conflicts between multiple packages on the same dependency.

Note that for global installs, packagers are still siloed at the top level, so if you were to run `npm install -g pm2`, everything would be installed under `<global-prefix>/lib/node_modules/pm2`. We did this to make it easier to manage global packages, and to avoid turning the global `node_modules` into a mess.

**Comment by Unitech** [comment]
Alright gotcha, thank you for the explanation!
