### ISSUE TITLE
Installing package globally gives peer dependecy warning even when peer met

### ISSUE THREAD

**Issue by keirlawson** [npm/npm#9857]
Installing a global package (generator-mygenerator) that has a peer dependency on another (yo) which is also installed globally causes this warning:

/lib
├── generator-mygenerator@2.5.0-RC2 
└── UNMET PEER DEPENDENCY yo@>=1.0.0

Even though the dependend-upon package is installed globally.  I am using npm 3.3.5 with node 0.12.7 on Fedora

**Comment by thatfulvioguy** [comment]
This also happens for me with npm 3.3.5 and node 0.12.7 on Ubuntu 15.04 and Windows 7

**Comment by mzgol** [comment]
I've just hit the same with yo 1.5.0 & generator-keystone 0.3.9.

**Comment by chapati23** [comment]
same here. `UNMET PEER DEPENDENCY` although peer is installed globally.
node 5.1.1
npm 3.8.3
OSX 10.11.4

**Comment by SneakyMax** [comment]
So I looked into the npm codebase to figure this out. It turns out that effectively reverting #8876 (specifically, removing the filter to `readPackageTree` on line 575 of install.js) fixes this problem.

However, I'm not sure of the full ramifications of causing global installs to read the entire global package tree (because it would have to do that to find peer dependencies) - this was obviously removed for some reason or another.

I think there's probably is a _use case_ for global peer dependencies, e.g. `eslint` + `eslint-plugin-promise` for use by `SublimeLinter-eslint` is why I ran into this.

It installs even with the error so this whole thing is super minor, and if you really don't like the error you can include the peer you already had with the package (`npm install eslint eslint-plugin-promise` works fine)
