### ISSUE TITLE
npm shrinkwrap causes conflict with devDependencies in npm@3

### ISSUE THREAD

**Issue by brettporter** [npm/npm#9867]
This may be related to #9703, but I wanted to post the distinct test case and steps to reproduce.

I have a project which uses `lodash` 3.10 in production dependencies, and `nock` in dev dependencies. Nock depends on lodash 2.4.1 explicitly, and fails when it uses 3.x.

On such a project, `npm install` will work fine, but if you run `npm shrinkwrap` then remove `node_modules` and run `npm install` again, it will fail as nock has started using the newer version of lodash. This process works in npm@2.14

Sample project: https://gist.github.com/brettporter/9cd84f9ee0962ca32479

**Comment by brettporter** [comment]
@othiym23 was it closed as a dupe of the other?

**Comment by othiym23** [comment]
I'm pretty sure this was waffle.io just trying to "help". I didn't actually do anything myself!

**Comment by brettporter** [comment]
:smile:

**Comment by markstos** [comment]
When `npm shrinkwrap` was run, the `devDependencies` would not have been included in `npm-shrinkwrap.json` (because the `--dev` flag was not used). 

So what happens with `devDependencies` when `node_modules` is removed and `npm install` is run with a shrinkwrap file in place? 

According to `npm help install`, the answer is:

>  ...if the package has a shrinkwrap file, the installation of dependencies will be driven by that. See npm help shrinkwrap.

If you follow the docs advice here and read `npm help shrinkwrap`, you'll  find... nothing. The documented behavior of handling `devDependencies` with `npm install + shrinkwrap` is currently undefined.

Shouldn't `nock` have not been installed at all, since it wasn't in the shinkwrap file? 

Some design issue I see here:

  * `npm install` defaults to installing devDepends  by default but  `npm shrinkwrap` has the inverse behavior. How can `npm install` ever seamlessly be expected to manage and use shrinkwrap'ed files, if they have inverse defaults?
 *  Why not add a 'devDependencies' section to the shrinkwrap file for consistency? Our team recently lost several hours of work because `nodemon` had a broken update, and we use it via `gulp-nodemon`, and happened to re-install things. If this dependency had been locked down with Shrinkwrap, our team would have spared the headache of everyone having a broken checkout. Explicit dependencies can be as useful for development tools as they are in production. If the shrinkwrap file offered this consistency, it would be a step towards more seamless integration, and help integrate the class bugs of unexpected behavior related to 'npm install' installing "devDeps by default" while `npm shrinkwrap` "excludes devDeps by default".

**Comment by peterjwest** [comment]
+1
Complete agree with everything @markstos suggests. If dev dependencies were marked in some way in the shrinkwrap file, then you could do an `npm install --production` and skip them, without having to generate a separate shrinkwrap.

**Comment by markstos** [comment]
My workaround has been merge our devDependencies into our dependencies, so there's no more devDependencies in `package.json`.  Using shrinkwrap and avoiding this issue was move important to us than the dev vs. not-dev distinction in package.json.
