### ISSUE TITLE
npm prune --production removes dependencies with git+http url

### ISSUE THREAD

**Issue by tswaters** [npm/npm#9889]
If I run `npm prune --production` I expect devDedepndencies to be removed.

If I have a url as a dependency, something like: 

```
git+http://gitblit.local/r/some-package
```

This is unbuilt after running `npm prune --production`

```
C:\>node --version
v0.10.26

C:\>npm --version
1.4.3
```

Using windows 8.1 x64

**Comment by KenanY** [comment]
@tswaters Does this also occur on the [latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by jsonfry** [comment]
We thought we'd just run into this, but it turns out that what you call your dependency has to match in both `package.json` files. E.g.

Your dependency's package.json:
```
{
  "name": "my-dependecy",
}
``` 

And your amazing app's package.json:
```
{
...
"dependencies": {
    "my-dependecy": "git@git.org:git/blah.git#1.0.0",
}
```

The name `my-dependency` must be the same in both cases. Otherwise npm thinks it's extraneous (which you can see by running `npm ls` in your amazing app's directory) and deletes it when doing an `npm prune --production`

**Comment by elliotdickison** [comment]
I'm getting this on macOS 10.12.4 with
```
➜  app git:(mainline) node --version
v7.9.0
➜  app git:(mainline) npm --version
4.2.0
```

@jsonfry My package names and dependency names match, but they're still getting pruned.

**Comment by legodude17** [comment]
Can I see your `package.json`?

**Comment by elliotdickison** [comment]
@legodude17 Alright, turns out my problem was mixing `yarn` and `npm`. I had originally installed with yarn, but was then trying to prune with npm. Using npm consistently to install and prune solved my problem.

**Comment by KenanY** [comment]
Closing due to no reply from the OP after over a year. Feel free to open a new ticket if anyone runs into this again.
