### ISSUE TITLE
npm@3 allows to uninstall any (local) dependency packages

### ISSUE THREAD

**Issue by dacodekid** [npm/npm#9925]
The current 'flat' structure that exposes any node-package directly under 'node_modules', allows to uninstall them.  Is this expected?  For ex:, I install my npm package

```npm install --save-dev node-folder``` which has the following dependencies ```mkdirp, commander, brace-expansion, async```.  Now, I can ```npm uninstall async``` or ```npm uninstall mkdirp``` or any package that listed under node's root folder.

**Comment by othiym23** [comment]
Yes, this is the expected behavior, but answering your implied next question, no, this is not super helpful when you are about to put the tree into an invalid state. npm should at least warn you when removing something is going to break something else, and should also tell you what those somethings else are, and so I've created #10295 so that we will (eventually) add that warning. Thanks for asking about this!

**Comment by dacodekid** [comment]
@othiym23, thx for the update. I was just about to bump this issue again.  The flat structure is convenient in many occasions but also misleads as it allows us to `require` some other module's dependency that is not in my dev/dependencies. But then... the above issue.  Hope to see the `warning` soon.

**Comment by fritx** [comment]
Awesome.

> but also misleads as it allows us to require some other module's dependency that is not in my dev/dependencies.

What would be the solution to this problem?
