### ISSUE TITLE
Passing node options into run-script

### ISSUE THREAD

**Issue by segrey** [npm/npm#9964]
It'd be great to have a way to alter node options (like adding `--debug`) of the spawned process on the fly via environment variable.
That would allow to debug pure node scripts without package.json modification.

For example, `NPM_RUN_SCRIPT_NODE_OPTIONS=--debug npm run-script start` for

``` json
{
  "scripts": {
    "start": "node ./bin/www"
  }
}
```

**Comment by KenanY** [comment]
@segrey Is this what you are looking for?:

```
npm run-script start -- --debug
```

https://docs.npmjs.com/cli/run-script

Or do you specifically want an environment variable?

**Comment by segrey** [comment]
@KenanY No, I don't want an environment variable specifically. I just don't want to modify the script body (i.e. package.json file).
`npm run-script start -- --debug` doesn't spawn node process in debug mode.
It will run `node ./bin/www --debug`, but I need `node --debug ./bin/www`

**Comment by KenanY** [comment]
@segrey Ohhh I see.

**Comment by nikopavlica** [comment]
This would greatly improve developer experience, because it would ease the debugging process. Many IDEs or text editors would take advantage of this one in a form of 'debug npm script'. without manually having to add optional parameters in the script itself. 

For example: https://youtrack.jetbrains.com/issue/WEB-18581
