### ISSUE TITLE
npm ERR! code ETXTBSY

### ISSUE THREAD

**Issue by Stanzilla** [npm/npm#9979]
```
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.8
npm ERR! path /home/sites/weakauras/node_modules/.staging/npm-b1c9ad4e32635a2889440d8e71d4c069/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall mkdir

npm ERR! EPROTO: protocol error, mkdir '/home/sites/weakauras/node_modules/.staging/npm-b1c9ad4e32635a2889440d8e71d4c069/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.8
npm ERR! path npm-debug.log.a2a1aaba4ca976c5bb38419ff3dca8c8
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.a2a1aaba4ca976c5bb38419ff3dca8c8' -> 'npm-debug.log'

npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sites/weakauras/npm-debug.log
```

**Comment by Stanzilla** [comment]
Attaching files to reports to this repo requires write permissions, no idea why. Here's the debug log http://pastebin.com/KmkQXkd0

**Comment by samir1kumar** [comment]
Hi ,

I am also experiencing same issue. I am running ubuntu-trusty32 vagrant on windows 7. 
I get below error after "npm install"
npm WARN install Couldn't install optional dependency: Unsupported

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! path ../dev-ip/lib/dev-ip.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../dev-ip/lib/dev-ip.js' -> '/vagrant/wp/wp-content/themes/comfortmsh/node_modules/.bin/dev-ip'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! path npm-debug.log.7c7ae7c4bd3884ac2ef52d1d8f77f815
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.7c7ae7c4bd3884ac2ef52d1d8f77f815' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/wp/wp-content/themes/comfortmsh/npm-debug.log


Please find attached my log file.

**Comment by samir1kumar** [comment]
Hi ,

I am able to resolve my issue now after using below command:-

$ npm install --no-bin-links

since i had to further install bower, so i used:
$ bower install <------- worked fine.

Then i wanted to build my wordpress sage template. I used :-1:
$ gulp <---- further gave some error and pointed me to use "npm rebuild node-sass"

$ npm rebuild node-sass <- gave again some symbolic link error, I choose below command which worked fine.

$ npm rebuild node-sass --no-bin-links

Further i was able to use gulp to build. Thanks.

**Comment by Stanzilla** [comment]
Too long file paths again, I guess...

**Comment by othiym23** [comment]
My guess is that you're both running Linux inside Vagrant on a Windows host, because `ETXTBSY` is almost always due to Windows not wanting to let the guest OS remove or move a file. Generally, this happens when you have a `cmd.exe` process open in a directory, or are looking at the folder with Explorer, or have a file in there open in a text editor.

@Stanzilla, if you delete your current `node_modules` folder and reinstall, it will go from being the deeply nested `npm@<3` style tree to the new `npm@3` maximally flat tree, which should fix the original problem you were seeing.

@samir1kumar, it looks like you want to run your install with `--no-bin-links`, because you don't have your Vagrant shared directory configured to support symlinks (this is possible, but not done by default by VirtualBox or Vagrant because of security concerns). This also means you can't use linked modules in your shared directory. I shared [some more thoughts about this](https://twitter.com/othiym23/status/656176728750948352) on Twitter. Vagrant with shared directories seems like it should be the best of both worlds, but there are a surprising number of pitfalls to making it work without issues.

I think that will address both your issues, so I'm going to close this as resolved. Let me know if you feel otherwise, and one of the CLI team will help you out.

**Comment by Stanzilla** [comment]
@othiym23 Yes it is vagrant/homestead on Windows and I did a fresh folder and just `npm install` I still got

```
runTopLevelLifecycles     â â¢ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââânpm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.9
npm ERR! path /home/sites/weakauras/node_modules/.staging/npm-b1c9ad4e32635a2889440d8e71d4c069/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall mkdir

npm ERR! EPROTO: protocol error, mkdir '/home/sites/weakauras/node_modules/.staging/npm-b1c9ad4e32635a2889440d8e71d4c069/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.9
npm ERR! path npm-debug.log.ec138c5ee0cdde972c69599a411648a6
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.ec138c5ee0cdde972c69599a411648a6' -> 'npm-debug.log'

npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sites/weakauras/npm-debug.log
```

**Comment by samir1kumar** [comment]
@othiym23  Resolution provided by you in another issue "npm doesn't work in vagrant #7308"  worked for me.
Yes, I am running Ubuntu trusty 32-bit inside Vagrant on a Windows 7  host. I don't have my Vagrant shared directory configured to support symlinks by default.   I was simply using  "npm install" command and was getting above errors. Your suggestion in another issue as mentioned earlier helped me bypass this due to symlink.   Thank you so much. I used below command:-

$ npm install --no-bin-links

**Comment by Stanzilla** [comment]
I had added 
```
config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
end
``` 
to my vagrantfile but it didn't work :/

**Comment by Stanzilla** [comment]
@othiym23 is that still an npm issue then?

**Comment by othiym23** [comment]
Yes and no. Yes because you're still getting a long file path (and I'm not sure why – I would think that using `npm@3` to install request would lead to a much flatter tree than you're seeing, so maybe request has started bundling its dependencies), but the long path issue itself isn't something npm can do anything about, and isn't a bug in npm or Node, which are just using the supported Linux filesystem operations here. There's [a configuration option for Vagrant](https://github.com/npm/npm/wiki/Troubleshooting#running-a-vagrant-box-on-windows-fails-due-to-path-length-issues) that controls how it uses UNC (long) paths when hosting shared folders on Windows,  and that option needs to be enabled to avoid these issues.

**Comment by Stanzilla** [comment]
@othiym23 Alright, figured something out. It was actually fixed in vagrant, but they reverted it because of some regression. https://github.com/mitchellh/vagrant/issues/6409

**Comment by zubaer-ahammed** [comment]
@samir1kumar Thank you. I fall into the same problem with laravel and your comment fixed everything.

Used: `npm install --no-bin-links`

And the rebuilt the node-sass: `npm rebuild node-sass --no-bin-links`

**Comment by mecj2017** [comment]
Thanks @othiym23, you helpend without knowing

I had a two days problem, installing de sqlite3 nodejs driver, and always gettin the mkdir error, at end, it was the problem when working on shared folder from Windows 7 host to linux guest

I put the working folder copied to a non shared folder and it worked

**Comment by gueroverde** [comment]
Used: npm install --no-bin-links

**Comment by tankphper** [comment]
I used `sudo npm install` to resolved

**Comment by jonnyasmar** [comment]
If you're getting this error due to the `fsevents` package and you're in a Linux env, you might want to try forcing the install with:

`npm install -f`

Linux doesn't utilize fsevents anyways, so you lose nothing by forcing `npm install` to continue without successfully installing this package.

**Comment by ghost** [comment]
Hello, all.

 I also faced this problem.
My error message is as bellow;

npm ERR! path '/?11/?12/?13/?14/node_modules/boom/package.json.3599737334
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename
npm ERR! ETXTBSY: text file is busy, rename '/?11/?12/?13/?14/node_modules/boom/package.json.3599737334' -> '/?11/?12/?13/?14/
node_modules/boom/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-03-26T04_06_55_689Z-debug.log


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

?11, ?12, ?13, ?14, mean that ones of my  directory's name.

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

I am glad to reply if you have the time.

Thank you.
