### ISSUE TITLE
reactivex is not in the npm registry

### ISSUE THREAD

**Issue by mephisto83** [npm/npm#9997]
npm WARN package.json angular2-quickstart@0.0.0 No description
npm WARN package.json angular2-quickstart@0.0.0 No repository field.
npm WARN package.json angular2-quickstart@0.0.0 No README data
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:reactivex/rxjs)
npm ERR! git clone git@github.com:reactivex/rxjs Cloning into bare repository 'C
:\Users\aporter\AppData\Roaming\npm-cache\_git-remotes\git-github-com-reactivex-
rxjs-e4513236'...
npm ERR! git clone git@github.com:reactivex/rxjs Host key verification failed.
npm ERR! git clone git@github.com:reactivex/rxjs fatal: Could not read from remo
te repository.
npm ERR! git clone git@github.com:reactivex/rxjs
npm ERR! git clone git@github.com:reactivex/rxjs Please make sure you have the c
orrect access rights
npm ERR! git clone git@github.com:reactivex/rxjs and the repository exists.
npm ERR! addLocal Could not install reactivex/rxjs
npm ERR! Error: ENOENT, stat 'D:\test\angular2\angular2-quickstart\reactivex\rxj
s'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@reactivex/rxjs"
npm ERR! cwd D:\test\angular2\angular2-quickstart
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\test\angular2\angular2-quickstart\reactivex\rxjs
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\test\angular2\angular2-quickstart\npm-debug.log
npm ERR! not ok code 0

D:\test\angular2\angular2-quickstart>

**Comment by KenanY** [comment]
@mephisto83 Does this also occur if you [update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by chrismbeckett** [comment]
I am getting the same problem:

Ubuntu 14.04.2 LTS
Node v4.2.1
Npm v3.3.8

I can install 'npm install @reactivex/rxjs' manually, and then 'npm install angular2' will work. Can't get JSPM to install it though. I think the problem is that the dependency is listed as "npm:@reactivex/rxjs", when it needs to be loaded from GitHub directly "github:reactivex/rxjs"

**Comment by hawkup** [comment]
I got this error when try to install angular2 on node version 0.10.38
```
npm WARN package.json angular2-quickstart@1.0.0 No description
npm WARN package.json angular2-quickstart@1.0.0 No repository field.
npm WARN package.json angular2-quickstart@1.0.0 No README data
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'reactivex/rxjs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'angular2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-55-generic
npm ERR! command "/home/honn/.nvm/v0.10.38/bin/node" "/home/honn/.nvm/v0.10.38/bin/npm" "i" "angular2@2.0.0-alpha.42" "--save" "--save-exact"
npm ERR! cwd /home/honn/Projects/angular2-quickstart
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```

but when I change to use node v0.12.4 and npm v2.10.1 or higher
I can install angular2

**Comment by krisdahl** [comment]
Is it supposed to be '@reactivex/rxjs' instead of 'reactivex/rxjs'?

**Comment by ygayl** [comment]
I am running with node version 0.10.26 and npm version 1.4.3 and getting the error.
What is for some reason I can't upgrade those ones? Thanks!

**Comment by mephisto83** [comment]
This is the hiccup.

npm http 404 https://registry.npmjs.org/reactivex/rxjs/5.0.0-alpha.4 

There seems to be a missing dependency.

**Comment by mephisto83** [comment]
Upgrading node to the latest version fixed my problem.

**Comment by edgarvl** [comment]
update node with this

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

That worked with me

**Comment by MaxiSir** [comment]
I haven't solved this issue, I tried every suggestion above, updated node.JS and npm, cleaned cache, but still I am unable to install angular2, because:


    npm ERR! registry error parsing json
    npm ERR! Darwin 14.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v4.2.1
    npm ERR! npm  v3.3.9
    
    npm ERR! Unexpected token <
    npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    npm ERR! <html><head>
    npm ERR! <title>404 Not Found</title>
    npm ERR! </head><body>
    npm ERR! <h1>Not Found</h1>
    npm ERR! <p>The requested URL /api/npm/npm-virtual/@reactivex/rxjs was not found on this server. </p>
    npm ERR! <hr>
    npm ERR! <address>Apache/2.2.15 (CentOS) Server at artifactory-us.re.vendavo.com Port 443</address>
    npm ERR! </body></html>

**Comment by LawrieR** [comment]
I couldn't get any of these suggested solutions to work but I did get it to work by deleting my .npmrc file (in user dir). Hope this helps!

**Comment by pttnores** [comment]
Thanks @edgarvl

**Comment by MaxiSir** [comment]
Thanks @LawrieR it solved my issue

**Comment by henkieee** [comment]
Fixed by upgrading node to the latest

**Comment by StephenC16** [comment]
I upgraded to node v5.0.0 and nam v3.3.6. Cleared cache.

npm fails to install @reactivex/rxjs.

 npm fails to install angular2... (with same @reactivex dependency error)

**Comment by nwayve** [comment]
I just ran into this problem, tried all of the steps above and nothing worked.  As it turns out, I had npm installed via chocolatey, and even though I had npm update itself (it was showing the latest version of 3.4.0) but when I did `npm --version`, it kept showing 1.4.9 (the choco installed version).  I uninstalled it via chocolatey, `npm --version` now showed 3.4.0.  I guess there was a conflict there but that fixed the issue.

**Comment by StephenC16** [comment]
Uninstalling npm and reinstalling node ultimately fixed the problem for me. Npm was not updating itself properly from the version I had.

**Comment by jorawarsingh** [comment]
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo apt-get update
sudo apt-get dista-upgrade 
@reactivex/rxjs can be innstall only by npm 2.0.0 or higher
@reactivex/rxjs@5.0.0-alpha.7: wanted: {"npm":"~2.0.0"} (current: {"node":"5.0.0","npm":"3.3.6"}) this should resolve your problem

**Comment by othiym23** [comment]
@jorawarsingh the version of npm packaged with Debian and Ubuntu is so old that it's no longer supported by the CLI team. If you switch from using the Debian / Ubuntu packages for Node.js to using [the NodeSource distribution](https://github.com/nodesource/distributions), that will include a version of npm that should be new enough to install `@reactive/rxjs` (which, as the error message says, must be installed with at least `npm@2` because of being a scoped package).

**Comment by maufarinelli** [comment]
I just had the same problem and after trying the solutions above, I still got the 1.4.2 version.
The only thing that worked for me was doing:
`curl -L https://www.npmjs.org/install.sh | sh`
now I have 3.5.0
The solution was found here: https://github.com/npm/npm/wiki/Troubleshooting

**Comment by ChuckkNorris** [comment]
Found this on a [blog](http://www.centare.com/tutorial-angular2-mvc-6-asp-net-5/) which allows you to target your installed version of NodeJS:
While Node.js and its corresponding package manager, namely “npm” are part of the install for Visual Studio 2015 – it installs with 1.4.9 which is unfortunately an outdated version. Angular2 might play nicer with a later version of npm.
“Node.js” package ecosystem, npm, is the largest ecosystem of open source libraries in the world!
Let’s address this now, so that we do not run into issues once we start writing code. Install the latest version of Node.js here. Once installed navigate to the following directory:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\

Open the npm.cmd file in your favorite text editor (running as Administrator) and replace the contents of this file with the following:

@”C:\Program Files\nodejs\node.exe” “C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js” %*

Now Visual Studio 2015 will utilize the npm version that was installed from the aforementioned steps.
